package yuyu.def.db.id;

import javax.persistence.Transient;
import jp.co.slcs.swak.conversion.annotations.Padding;
import jp.co.slcs.swak.db.typesafe.AbstractExDBPrimaryKey;
import yuyu.def.db.entity.ZT_Sp2RnduyuSouseiritu3Rn;
import yuyu.def.db.mapping.GenZT_Sp2RnduyuSouseiritu3Rn;
import yuyu.def.db.meta.GenQZT_Sp2RnduyuSouseiritu3Rn;
import yuyu.def.db.meta.QZT_Sp2RnduyuSouseiritu3Rn;

/**
 * ＳＰ２連動用総成立Fテーブル３（連） のプライマリキークラスです。<br />
 * <table border="1" cellspacing="0" cellpadding="0">
 *  <tr bgcolor="whitesmoke"><th colspan="2">テーブルID</th><th colspan="3">名称</th></tr>
 *  <tr><td colspan="2">{@link ZT_Sp2RnduyuSouseiritu3Rn}</td><td colspan="3">ＳＰ２連動用総成立Fテーブル３（連）</td></tr>
 *  <tr bgcolor="whitesmoke"><th>フィールドID</th><th>フィールド名</th><th>PKey</th><th>DB型</th><th>Java型</th></tr>
 *  <tr><td>zrnktgysyrymd</td><td>（連携用）結合用処理日</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr bgcolor="pink"><td>{@link #getZrnktgysyono zrnktgysyono}</td><td>（連携用）結合用証券番号</td><td align="center">○</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnktgyfilerenno</td><td>（連携用）結合用ファイル連番</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbosyuukeirokbn</td><td>（連携用）募集経路区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyokaipcashlessnyukinhyj</td><td>（連携用）初回Ｐキャッシュレス入金表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigkyhsitihsyutkykarihyj</td><td>（連携用）介護給付最低保証特約有表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyokaipswingriyoukbn</td><td>（連携用）初回Ｐスイング利用区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsknjyututkykkykkbn</td><td>（連携用）資金充当特約契約区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbosyuudairitengyousyukbn</td><td>（連携用）募集代理店業種区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrncifcd</td><td>（連携用）ＣＩＦコード</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokusyujimutoriatukaikbn</td><td>（連携用）特殊事務取扱区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnpmentkykyutktbicdx1</td><td>（連携用）Ｐ免特約用特定部位コード＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnpmentkykyuhtnpkknx1</td><td>（連携用）Ｐ免特約用不担保期間＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnpmentkykyutktbicdx2</td><td>（連携用）Ｐ免特約用特定部位コード＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnpmentkykyuhtnpkknx2</td><td>（連携用）Ｐ免特約用不担保期間＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhosyouikkatumnoshyouji</td><td>（連携用）保障一括見直表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhsyuikktminaosikaisu</td><td>（連携用）保障一括見直回数</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhsyuikktmnosdfnyuknhyj</td><td>（連携用）保障一括見直ＤＦ入金表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnikktmnoskikiyutkykp</td><td>（連携用）一括見直会計用特約Ｐ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnikktmnoskikiyufndsistp</td><td>（連携用）一括見直会計用ファンド災疾Ｐ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnsknnjynbknsisnrt</td><td>（連携用）責任準備金精算率</td><td>&nbsp;</td><td align="center">N</td><td>BizNumber</td></tr>
 *  <tr><td>zrnkanyujisyono</td><td>（連携用）加入時証券番号</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkanyujikykymd</td><td>（連携用）加入時契約年月日</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkanyuujihihokensyaage</td><td>（連携用）加入時被保険者年令</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkanyuujitenkanhyouji</td><td>（連携用）加入時転換表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnksnyuhsyuikktminosnnskbn</td><td>（連携用）加算用保障一括見直年数区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnaatukaisyadirtnbsynnhyj</td><td>（連携用）Ａ扱者代理店募集人表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbatkisyadirtnbosyuninhyj</td><td>（連携用）Ｂ扱者代理店募集人表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndirtnaatukaisyakojincd</td><td>（連携用）代理店Ａ扱者個人コード</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndirtnbatukaisyakojincd</td><td>（連携用）代理店Ｂ扱者個人コード</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyuuseisyoukeikanensuu</td><td>（連携用）修正Ｓ用経過年数</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyuruihnkutkbttrtkhyj</td><td>（連携用）種類変更特別取扱表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbnktmekyktkykhkjyutikbn</td><td>（連携用）分割前契約特約付加状態区分</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkykjiqpackhyj</td><td>（連携用）契約時Ｑパック表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntnknsyokaipclessriyouhyj</td><td>（連携用）転換初回ＰＣレス利用表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhrkteisikibouhyouji</td><td>（連携用）払込停止希望表示</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbunkatugosonzokukeiyakus</td><td>（連携用）分割後存続契約Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnmoskizkphrkekngk</td><td>（連携用）申込継続Ｐ振替金額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnkeizokuphurikaejijikaip</td><td>（連携用）継続Ｐ振替時次回Ｐ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmekyksyono</td><td>（連携用）分割前契約証券番号</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnbunkatumaekeiyakukihons</td><td>（連携用）分割前契約基本Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbunkatumaekeiyakusibous</td><td>（連携用）分割前契約死亡Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmekykmods</td><td>（連携用）分割前契約修正Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmekyksigiwrmstkyks</td><td>（連携用）分割前契約災害割増特約Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmekyksyugitkyks</td><td>（連携用）分割前契約傷害特約Ｓ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmkyksiginyintkykntgk</td><td>（連携用）分割前契約災害入院特約日額</td><td>&nbsp;</td><td align="center">N</td><td>Integer</td></tr>
 *  <tr><td>zrnbnktmekykknkutkykntgk</td><td>（連携用）分割前契約健康特約日額</td><td>&nbsp;</td><td align="center">N</td><td>Integer</td></tr>
 *  <tr><td>zrnbnktmekykhntiyunbriknsnp</td><td>（連携用）分割前契約判定用年払換算Ｐ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrndai2naibuwarimodosigaku</td><td>（連携用）第２内部割戻額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrntnkngkykkstkgk</td><td>（連携用）転換後契約貸付額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnbnktmekykkstkgk</td><td>（連携用）分割前契約貸付額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnsonzokukykkasitukegk</td><td>（連携用）存続契約貸付額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnhngkmnryoujsitihsyukngk</td><td>（連携用）変額満了時最低保証金額</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnhngksitihsyuyusykykp</td><td>（連携用）変額最低保証用主契約Ｐ</td><td>&nbsp;</td><td align="center">N</td><td>Long</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x1</td><td>（連携用）被転換介護マル終記号予備＿１＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x1</td><td>（連携用）被転換介護マル終記号予備＿２＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x1</td><td>（連携用）被転換介護マル終記号予備＿３＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x1</td><td>（連携用）被転換介護マル終記号予備＿４＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x1</td><td>（連携用）被転換介護マル終記号予備＿５＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x2</td><td>（連携用）被転換介護マル終記号予備＿１＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x2</td><td>（連携用）被転換介護マル終記号予備＿２＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x2</td><td>（連携用）被転換介護マル終記号予備＿３＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x2</td><td>（連携用）被転換介護マル終記号予備＿４＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x2</td><td>（連携用）被転換介護マル終記号予備＿５＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x3</td><td>（連携用）被転換介護マル終記号予備＿１＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x3</td><td>（連携用）被転換介護マル終記号予備＿２＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x3</td><td>（連携用）被転換介護マル終記号予備＿３＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x3</td><td>（連携用）被転換介護マル終記号予備＿４＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x3</td><td>（連携用）被転換介護マル終記号予備＿５＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x4</td><td>（連携用）被転換介護マル終記号予備＿１＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x4</td><td>（連携用）被転換介護マル終記号予備＿２＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x4</td><td>（連携用）被転換介護マル終記号予備＿３＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x4</td><td>（連携用）被転換介護マル終記号予備＿４＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x4</td><td>（連携用）被転換介護マル終記号予備＿５＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x5</td><td>（連携用）被転換介護マル終記号予備＿１＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x5</td><td>（連携用）被転換介護マル終記号予備＿２＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x5</td><td>（連携用）被転換介護マル終記号予備＿３＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x5</td><td>（連携用）被転換介護マル終記号予備＿４＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x5</td><td>（連携用）被転換介護マル終記号予備＿５＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx1x6</td><td>（連携用）被転換介護マル終記号予備＿１＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx2x6</td><td>（連携用）被転換介護マル終記号予備＿２＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx3x6</td><td>（連携用）被転換介護マル終記号予備＿３＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx4x6</td><td>（連携用）被転換介護マル終記号予備＿４＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhtnknkigmrsyukguybx5x6</td><td>（連携用）被転換介護マル終記号予備＿５＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnyobiv1x3</td><td>（連携用）予備項目Ｖ１＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x1</td><td>（連携用）保険種類記号予備１＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x2</td><td>（連携用）保険種類記号予備１＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x3</td><td>（連携用）保険種類記号予備１＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x4</td><td>（連携用）保険種類記号予備１＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x5</td><td>（連携用）保険種類記号予備１＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x6</td><td>（連携用）保険種類記号予備１＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x7</td><td>（連携用）保険種類記号予備１＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x8</td><td>（連携用）保険種類記号予備１＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x9</td><td>（連携用）保険種類記号予備１＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x10</td><td>（連携用）保険種類記号予備１＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x11</td><td>（連携用）保険種類記号予備１＿１１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x12</td><td>（連携用）保険種類記号予備１＿１２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x13</td><td>（連携用）保険種類記号予備１＿１３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x14</td><td>（連携用）保険種類記号予備１＿１４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi1x15</td><td>（連携用）保険種類記号予備１＿１５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x1</td><td>（連携用）保険種類記号予備２＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x2</td><td>（連携用）保険種類記号予備２＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x3</td><td>（連携用）保険種類記号予備２＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x4</td><td>（連携用）保険種類記号予備２＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x5</td><td>（連携用）保険種類記号予備２＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x6</td><td>（連携用）保険種類記号予備２＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x7</td><td>（連携用）保険種類記号予備２＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x8</td><td>（連携用）保険種類記号予備２＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x9</td><td>（連携用）保険種類記号予備２＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi2x10</td><td>（連携用）保険種類記号予備２＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x1</td><td>（連携用）保険種類記号予備３＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x2</td><td>（連携用）保険種類記号予備３＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x3</td><td>（連携用）保険種類記号予備３＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x4</td><td>（連携用）保険種類記号予備３＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x5</td><td>（連携用）保険種類記号予備３＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x6</td><td>（連携用）保険種類記号予備３＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x7</td><td>（連携用）保険種類記号予備３＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x8</td><td>（連携用）保険種類記号予備３＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x9</td><td>（連携用）保険種類記号予備３＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnhokensyuruikigouyobi3x10</td><td>（連携用）保険種類記号予備３＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruteikigouyobix1</td><td>（連携用）マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruteikigouyobix2</td><td>（連携用）マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruteikigouyobix3</td><td>（連携用）マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruteikigouyobix4</td><td>（連携用）マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruteikigouyobix5</td><td>（連携用）マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruyoukigouyobix1</td><td>（連携用）マル養記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruyoukigouyobix2</td><td>（連携用）マル養記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruyoukigouyobix3</td><td>（連携用）マル養記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruyoukigouyobix4</td><td>（連携用）マル養記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmaruyoukigouyobix5</td><td>（連携用）マル養記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmarusyuukigouyobix1</td><td>（連携用）マル終記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmarusyuukigouyobix2</td><td>（連携用）マル終記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmarusyuukigouyobix3</td><td>（連携用）マル終記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmarusyuukigouyobix4</td><td>（連携用）マル終記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmarusyuukigouyobix5</td><td>（連携用）マル終記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokuteikigouyobix1</td><td>（連携用）トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokuteikigouyobix2</td><td>（連携用）トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokuteikigouyobix3</td><td>（連携用）トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokuteikigouyobix4</td><td>（連携用）トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntokuteikigouyobix5</td><td>（連携用）トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x1</td><td>（連携用）家族マル定記号予備＿１＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x1</td><td>（連携用）家族マル定記号予備＿２＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x1</td><td>（連携用）家族マル定記号予備＿３＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x1</td><td>（連携用）家族マル定記号予備＿４＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x1</td><td>（連携用）家族マル定記号予備＿５＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x2</td><td>（連携用）家族マル定記号予備＿１＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x2</td><td>（連携用）家族マル定記号予備＿２＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x2</td><td>（連携用）家族マル定記号予備＿３＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x2</td><td>（連携用）家族マル定記号予備＿４＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x2</td><td>（連携用）家族マル定記号予備＿５＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x3</td><td>（連携用）家族マル定記号予備＿１＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x3</td><td>（連携用）家族マル定記号予備＿２＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x3</td><td>（連携用）家族マル定記号予備＿３＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x3</td><td>（連携用）家族マル定記号予備＿４＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x3</td><td>（連携用）家族マル定記号予備＿５＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x4</td><td>（連携用）家族マル定記号予備＿１＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x4</td><td>（連携用）家族マル定記号予備＿２＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x4</td><td>（連携用）家族マル定記号予備＿３＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x4</td><td>（連携用）家族マル定記号予備＿４＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x4</td><td>（連携用）家族マル定記号予備＿５＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x5</td><td>（連携用）家族マル定記号予備＿１＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x5</td><td>（連携用）家族マル定記号予備＿２＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x5</td><td>（連携用）家族マル定記号予備＿３＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x5</td><td>（連携用）家族マル定記号予備＿４＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x5</td><td>（連携用）家族マル定記号予備＿５＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x6</td><td>（連携用）家族マル定記号予備＿１＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x6</td><td>（連携用）家族マル定記号予備＿２＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x6</td><td>（連携用）家族マル定記号予備＿３＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x6</td><td>（連携用）家族マル定記号予備＿４＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x6</td><td>（連携用）家族マル定記号予備＿５＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x7</td><td>（連携用）家族マル定記号予備＿１＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x7</td><td>（連携用）家族マル定記号予備＿２＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x7</td><td>（連携用）家族マル定記号予備＿３＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x7</td><td>（連携用）家族マル定記号予備＿４＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x7</td><td>（連携用）家族マル定記号予備＿５＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x8</td><td>（連携用）家族マル定記号予備＿１＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x8</td><td>（連携用）家族マル定記号予備＿２＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x8</td><td>（連携用）家族マル定記号予備＿３＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x8</td><td>（連携用）家族マル定記号予備＿４＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x8</td><td>（連携用）家族マル定記号予備＿５＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x9</td><td>（連携用）家族マル定記号予備＿１＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x9</td><td>（連携用）家族マル定記号予備＿２＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x9</td><td>（連携用）家族マル定記号予備＿３＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x9</td><td>（連携用）家族マル定記号予備＿４＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x9</td><td>（連携用）家族マル定記号予備＿５＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx1x10</td><td>（連携用）家族マル定記号予備＿１＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx2x10</td><td>（連携用）家族マル定記号予備＿２＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx3x10</td><td>（連携用）家族マル定記号予備＿３＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx4x10</td><td>（連携用）家族マル定記号予備＿４＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkmrtikguybx5x10</td><td>（連携用）家族マル定記号予備＿５＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyugittkykkguybx1</td><td>（連携用）傷害特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyugittkykkguybx2</td><td>（連携用）傷害特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyugittkykkguybx3</td><td>（連携用）傷害特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyugittkykkguybx4</td><td>（連携用）傷害特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsyugittkykkguybx5</td><td>（連携用）傷害特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsigiwrmstkykkguybx1</td><td>（連携用）災害割増特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsigiwrmstkykkguybx2</td><td>（連携用）災害割増特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsigiwrmstkykkguybx3</td><td>（連携用）災害割増特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsigiwrmstkykkguybx4</td><td>（連携用）災害割増特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsigiwrmstkykkguybx5</td><td>（連携用）災害割増特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiginyuintkykkguybx1</td><td>（連携用）災害入院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiginyuintkykkguybx2</td><td>（連携用）災害入院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiginyuintkykkguybx3</td><td>（連携用）災害入院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiginyuintkykkguybx4</td><td>（連携用）災害入院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiginyuintkykkguybx5</td><td>（連携用）災害入院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsppinyuintkykkguybx1</td><td>（連携用）疾病入院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsppinyuintkykkguybx2</td><td>（連携用）疾病入院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsppinyuintkykkguybx3</td><td>（連携用）疾病入院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsppinyuintkykkguybx4</td><td>（連携用）疾病入院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsppinyuintkykkguybx5</td><td>（連携用）疾病入院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsijnbyutkykkguybx1</td><td>（連携用）成人病特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsijnbyutkykkguybx2</td><td>（連携用）成人病特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsijnbyutkykkguybx3</td><td>（連携用）成人病特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsijnbyutkykkguybx4</td><td>（連携用）成人病特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsijnbyutkykkguybx5</td><td>（連携用）成人病特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkiryoutkykkguybx1</td><td>（連携用）家族医療特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkiryoutkykkguybx2</td><td>（連携用）家族医療特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkiryoutkykkguybx3</td><td>（連携用）家族医療特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkiryoutkykkguybx4</td><td>（連携用）家族医療特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkzkiryoutkykkguybx5</td><td>（連携用）家族医療特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsykkyuhtkykkguybx1</td><td>（連携用）初期給付特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsykkyuhtkykkguybx2</td><td>（連携用）初期給付特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsykkyuhtkykkguybx3</td><td>（連携用）初期給付特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsykkyuhtkykkguybx4</td><td>（連携用）初期給付特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsykkyuhtkykkguybx5</td><td>（連携用）初期給付特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdtmrtikguyobix1</td><td>（連携用）年金建マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdtmrtikguyobix2</td><td>（連携用）年金建マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdtmrtikguyobix3</td><td>（連携用）年金建マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdtmrtikguyobix4</td><td>（連携用）年金建マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdtmrtikguyobix5</td><td>（連携用）年金建マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdatetokuteikguyobix1</td><td>（連携用）年金建トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdatetokuteikguyobix2</td><td>（連携用）年金建トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdatetokuteikguyobix3</td><td>（連携用）年金建トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdatetokuteikguyobix4</td><td>（連携用）年金建トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnnkdatetokuteikguyobix5</td><td>（連携用）年金建トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdtmrtikguyobix1</td><td>（連携用）介護年金建マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdtmrtikguyobix2</td><td>（連携用）介護年金建マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdtmrtikguyobix3</td><td>（連携用）介護年金建マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdtmrtikguyobix4</td><td>（連携用）介護年金建マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdtmrtikguyobix5</td><td>（連携用）介護年金建マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdttktikguyobix1</td><td>（連携用）介護年金建トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdttktikguyobix2</td><td>（連携用）介護年金建トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdttktikguyobix3</td><td>（連携用）介護年金建トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdttktikguyobix4</td><td>（連携用）介護年金建トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonkdttktikguyobix5</td><td>（連携用）介護年金建トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigomaruteikigouyobix1</td><td>（連携用）介護マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigomaruteikigouyobix2</td><td>（連携用）介護マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigomaruteikigouyobix3</td><td>（連携用）介護マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigomaruteikigouyobix4</td><td>（連携用）介護マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigomaruteikigouyobix5</td><td>（連携用）介護マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigotokuteikigouyobix1</td><td>（連携用）介護トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigotokuteikigouyobix2</td><td>（連携用）介護トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigotokuteikigouyobix3</td><td>（連携用）介護トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigotokuteikigouyobix4</td><td>（連携用）介護トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigotokuteikigouyobix5</td><td>（連携用）介護トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiznmrtikguybx1</td><td>（連携用）生存マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiznmrtikguybx2</td><td>（連携用）生存マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiznmrtikguybx3</td><td>（連携用）生存マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiznmrtikguybx4</td><td>（連携用）生存マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsiznmrtikguybx5</td><td>（連携用）生存マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigenmaruteikigouyobix1</td><td>（連携用）逓減マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigenmaruteikigouyobix2</td><td>（連携用）逓減マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigenmaruteikigouyobix3</td><td>（連携用）逓減マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigenmaruteikigouyobix4</td><td>（連携用）逓減マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigenmaruteikigouyobix5</td><td>（連携用）逓減マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigentokuteikigouyobix1</td><td>（連携用）逓減トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigentokuteikigouyobix2</td><td>（連携用）逓減トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigentokuteikigouyobix3</td><td>（連携用）逓減トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigentokuteikigouyobix4</td><td>（連携用）逓減トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnteigentokuteikigouyobix5</td><td>（連携用）逓減トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtignmrtikguybx1</td><td>（連携用）介護逓減マル定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtignmrtikguybx2</td><td>（連携用）介護逓減マル定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtignmrtikguybx3</td><td>（連携用）介護逓減マル定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtignmrtikguybx4</td><td>（連携用）介護逓減マル定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtignmrtikguybx5</td><td>（連携用）介護逓減マル定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtigntktikguybx1</td><td>（連携用）介護逓減トク定記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtigntktikguybx2</td><td>（連携用）介護逓減トク定記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtigntktikguybx3</td><td>（連携用）介護逓減トク定記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtigntktikguybx4</td><td>（連携用）介護逓減トク定記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkigtigntktikguybx5</td><td>（連携用）介護逓減トク定記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntuuintokuyakukigouyobix1</td><td>（連携用）通院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntuuintokuyakukigouyobix2</td><td>（連携用）通院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntuuintokuyakukigouyobix3</td><td>（連携用）通院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntuuintokuyakukigouyobix4</td><td>（連携用）通院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntuuintokuyakukigouyobix5</td><td>（連携用）通院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnjysisppitkykkguyobix1</td><td>（連携用）女性疾病特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnjysisppitkykkguyobix2</td><td>（連携用）女性疾病特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnjysisppitkykkguyobix3</td><td>（連携用）女性疾病特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnjysisppitkykkguyobix4</td><td>（連携用）女性疾病特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnjysisppitkykkguyobix5</td><td>（連携用）女性疾病特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntksttkykkguybx1</td><td>（連携用）特疾特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntksttkykkguybx2</td><td>（連携用）特疾特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntksttkykkguybx3</td><td>（連携用）特疾特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntksttkykkguybx4</td><td>（連携用）特疾特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrntksttkykkguybx5</td><td>（連携用）特疾特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2tksttkykkguybx1</td><td>（連携用）第２特疾特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2tksttkykkguybx2</td><td>（連携用）第２特疾特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2tksttkykkguybx3</td><td>（連携用）第２特疾特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2tksttkykkguybx4</td><td>（連携用）第２特疾特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2tksttkykkguybx5</td><td>（連携用）第２特疾特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmnsttkykkguybx1</td><td>（連携用）慢疾特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmnsttkykkguybx2</td><td>（連携用）慢疾特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmnsttkykkguybx3</td><td>（連携用）慢疾特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmnsttkykkguybx4</td><td>（連携用）慢疾特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnmnsttkykkguybx5</td><td>（連携用）慢疾特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2mnsttkykkguybx1</td><td>（連携用）第２慢疾特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2mnsttkykkguybx2</td><td>（連携用）第２慢疾特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2mnsttkykkguybx3</td><td>（連携用）第２慢疾特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2mnsttkykkguybx4</td><td>（連携用）第２慢疾特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2mnsttkykkguybx5</td><td>（連携用）第２慢疾特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsugusnsyutkykkguybx1</td><td>（連携用）総合損傷特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsugusnsyutkykkguybx2</td><td>（連携用）総合損傷特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsugusnsyutkykkguybx3</td><td>（連携用）総合損傷特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsugusnsyutkykkguybx4</td><td>（連携用）総合損傷特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsugusnsyutkykkguybx5</td><td>（連携用）総合損傷特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonktkykkguyobix1</td><td>（連携用）介護年金特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonktkykkguyobix2</td><td>（連携用）介護年金特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonktkykkguyobix3</td><td>（連携用）介護年金特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonktkykkguyobix4</td><td>（連携用）介護年金特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnkaigonktkykkguyobix5</td><td>（連携用）介護年金特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnitjbrkignktkykkguybx1</td><td>（連携用）一時払介護年金特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnitjbrkignktkykkguybx2</td><td>（連携用）一時払介護年金特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnitjbrkignktkykkguybx3</td><td>（連携用）一時払介護年金特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnitjbrkignktkykkguybx4</td><td>（連携用）一時払介護年金特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnitjbrkignktkykkguybx5</td><td>（連携用）一時払介護年金特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2syugitkykkguybx1</td><td>（連携用）第２傷害特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2syugitkykkguybx2</td><td>（連携用）第２傷害特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2syugitkykkguybx3</td><td>（連携用）第２傷害特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2syugitkykkguybx4</td><td>（連携用）第２傷害特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2syugitkykkguybx5</td><td>（連携用）第２傷害特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sigiwrmstkykkguybx1</td><td>（連携用）第２災害割増特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sigiwrmstkykkguybx2</td><td>（連携用）第２災害割増特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sigiwrmstkykkguybx3</td><td>（連携用）第２災害割増特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sigiwrmstkykkguybx4</td><td>（連携用）第２災害割増特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sigiwrmstkykkguybx5</td><td>（連携用）第２災害割増特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2siginyuintkykkguybx1</td><td>（連携用）第２災害入院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2siginyuintkykkguybx2</td><td>（連携用）第２災害入院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2siginyuintkykkguybx3</td><td>（連携用）第２災害入院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2siginyuintkykkguybx4</td><td>（連携用）第２災害入院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2siginyuintkykkguybx5</td><td>（連携用）第２災害入院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sppinyuintkykkguybx1</td><td>（連携用）第２疾病入院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sppinyuintkykkguybx2</td><td>（連携用）第２疾病入院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sppinyuintkykkguybx3</td><td>（連携用）第２疾病入院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sppinyuintkykkguybx4</td><td>（連携用）第２疾病入院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sppinyuintkykkguybx5</td><td>（連携用）第２疾病入院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sijnbyutkykkguybx1</td><td>（連携用）第２成人病特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sijnbyutkykkguybx2</td><td>（連携用）第２成人病特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sijnbyutkykkguybx3</td><td>（連携用）第２成人病特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sijnbyutkykkguybx4</td><td>（連携用）第２成人病特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sijnbyutkykkguybx5</td><td>（連携用）第２成人病特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndai2tuintkykkguyobix1</td><td>（連携用）第２通院特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndai2tuintkykkguyobix2</td><td>（連携用）第２通院特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndai2tuintkykkguyobix3</td><td>（連携用）第２通院特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndai2tuintkykkguyobix4</td><td>（連携用）第２通院特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndai2tuintkykkguyobix5</td><td>（連携用）第２通院特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2jysisppitkykkguybx1</td><td>（連携用）第２女性疾病特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2jysisppitkykkguybx2</td><td>（連携用）第２女性疾病特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2jysisppitkykkguybx3</td><td>（連携用）第２女性疾病特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2jysisppitkykkguybx4</td><td>（連携用）第２女性疾病特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2jysisppitkykkguybx5</td><td>（連携用）第２女性疾病特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sugusnsyutkykkguybx1</td><td>（連携用）第２総合損傷特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sugusnsyutkykkguybx2</td><td>（連携用）第２総合損傷特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sugusnsyutkykkguybx3</td><td>（連携用）第２総合損傷特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sugusnsyutkykkguybx4</td><td>（連携用）第２総合損傷特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sugusnsyutkykkguybx5</td><td>（連携用）第２総合損傷特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sykkyuhtkykkguybx1</td><td>（連携用）第２初期給付特約記号予備＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sykkyuhtkykkguybx2</td><td>（連携用）第２初期給付特約記号予備＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sykkyuhtkykkguybx3</td><td>（連携用）第２初期給付特約記号予備＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sykkyuhtkykkguybx4</td><td>（連携用）第２初期給付特約記号予備＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrndi2sykkyuhtkykkguybx5</td><td>（連携用）第２初期給付特約記号予備＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x1</td><td>（連携用）セット相手保険種類予備１＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x2</td><td>（連携用）セット相手保険種類予備１＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x3</td><td>（連携用）セット相手保険種類予備１＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x4</td><td>（連携用）セット相手保険種類予備１＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x5</td><td>（連携用）セット相手保険種類予備１＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x6</td><td>（連携用）セット相手保険種類予備１＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x7</td><td>（連携用）セット相手保険種類予備１＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x8</td><td>（連携用）セット相手保険種類予備１＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x9</td><td>（連携用）セット相手保険種類予備１＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x10</td><td>（連携用）セット相手保険種類予備１＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x11</td><td>（連携用）セット相手保険種類予備１＿１１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x12</td><td>（連携用）セット相手保険種類予備１＿１２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x13</td><td>（連携用）セット相手保険種類予備１＿１３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x14</td><td>（連携用）セット相手保険種類予備１＿１４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi1x15</td><td>（連携用）セット相手保険種類予備１＿１５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x1</td><td>（連携用）セット相手保険種類予備２＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x2</td><td>（連携用）セット相手保険種類予備２＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x3</td><td>（連携用）セット相手保険種類予備２＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x4</td><td>（連携用）セット相手保険種類予備２＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x5</td><td>（連携用）セット相手保険種類予備２＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x6</td><td>（連携用）セット相手保険種類予備２＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x7</td><td>（連携用）セット相手保険種類予備２＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x8</td><td>（連携用）セット相手保険種類予備２＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x9</td><td>（連携用）セット相手保険種類予備２＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi2x10</td><td>（連携用）セット相手保険種類予備２＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x1</td><td>（連携用）セット相手保険種類予備３＿１</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x2</td><td>（連携用）セット相手保険種類予備３＿２</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x3</td><td>（連携用）セット相手保険種類予備３＿３</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x4</td><td>（連携用）セット相手保険種類予備３＿４</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x5</td><td>（連携用）セット相手保険種類予備３＿５</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x6</td><td>（連携用）セット相手保険種類予備３＿６</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x7</td><td>（連携用）セット相手保険種類予備３＿７</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x8</td><td>（連携用）セット相手保険種類予備３＿８</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x9</td><td>（連携用）セット相手保険種類予備３＿９</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 *  <tr><td>zrnsetaitehknsyuruiyobi3x10</td><td>（連携用）セット相手保険種類予備３＿１０</td><td>&nbsp;</td><td align="center">C</td><td>String</td></tr>
 * </table>
 * @see     ZT_Sp2RnduyuSouseiritu3Rn
 * @see     GenZT_Sp2RnduyuSouseiritu3Rn
 * @see     QZT_Sp2RnduyuSouseiritu3Rn
 * @see     GenQZT_Sp2RnduyuSouseiritu3Rn
 */
public class PKZT_Sp2RnduyuSouseiritu3Rn extends AbstractExDBPrimaryKey<ZT_Sp2RnduyuSouseiritu3Rn, PKZT_Sp2RnduyuSouseiritu3Rn> {

    private static final long serialVersionUID = 1L;

    public PKZT_Sp2RnduyuSouseiritu3Rn() {
    }

    public PKZT_Sp2RnduyuSouseiritu3Rn(String pZrnktgysyono) {
        zrnktgysyono = pZrnktgysyono;
    }

    @Transient
    @Override
    public Class<ZT_Sp2RnduyuSouseiritu3Rn> getEntityClass() {
        return ZT_Sp2RnduyuSouseiritu3Rn.class;
    }

    private String zrnktgysyono;

    public String getZrnktgysyono() {
        return zrnktgysyono;
    }

    public void setZrnktgysyono(String pZrnktgysyono) {
        zrnktgysyono = pZrnktgysyono;
    }

}