CREATE TABLE BT_KawaseRateData_Z (
     kwsratekjymd                                       VARCHAR     (8)                                                       NOT NULL  ,  /* 為替レート基準日 */
     kwsrendoukbn                                       VARCHAR     (1)                                                       NOT NULL  ,  /* 為替レート連動区分 */
     yobiv91                                            VARCHAR     (91)                                                                ,  /* 予備項目Ｖ９１ */
     usdjpytts                                          DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＳ） */
     usdjpyttb                                          DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＢ） */
     usdjpyttm                                          DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＭ） */
     eurjpytts                                          DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＳ） */
     eurjpyttb                                          DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＢ） */
     eurjpyttm                                          DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＭ） */
     audjpytts                                          DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＳ） */
     audjpyttb                                          DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＢ） */
     audjpyttm                                          DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＭ） */
     yobin9                                             DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９ */
     yobin9x2                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿２ */
     yobin9x3                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３ */
     yobin9x4                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿４ */
     yobin9x5                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５ */
     yobin9x6                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿６ */
     yobin9x7                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿７ */
     yobin9x8                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿８ */
     yobin9x9                                           DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿９ */
     yobin9x10                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０ */
     yobin9x11                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１１ */
     yobin9x12                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１２ */
     yobin9x13                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１３ */
     yobin9x14                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１４ */
     yobin9x15                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１５ */
     yobin9x16                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１６ */
     yobin9x17                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１７ */
     yobin9x18                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１８ */
     yobin9x19                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１９ */
     yobin9x20                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿２０ */
     yobin9x21                                          DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿２１ */
     usdjpynykn                                         DECIMAL     (9,2)                                                               ,  /* 米ドル－円（入金用） */
     eurjpynykn                                         DECIMAL     (9,2)                                                               ,  /* ユーロ－円（入金用） */
     audjpynykn                                         DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（入金用） */
     yobin9x101                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０１ */
     yobin9x102                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０２ */
     yobin9x103                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０３ */
     yobin9x104                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０４ */
     yobin9x105                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０５ */
     yobin9x106                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０６ */
     yobin9x107                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿１０７ */
     usdeurnykn                                         DECIMAL     (9,4)                                                               ,  /* 米ドル－ユーロ（入金用） */
     usdaudnykn                                         DECIMAL     (9,4)                                                               ,  /* 米ドル－豪ドル（入金用） */
     yobin9x111                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１１ */
     yobin9x112                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１２ */
     yobin9x113                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１３ */
     yobin9x114                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１４ */
     yobin9x115                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１５ */
     yobin9x116                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１６ */
     yobin9x117                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１１７ */
     eurusdnykn                                         DECIMAL     (9,4)                                                               ,  /* ユーロ－米ドル（入金用） */
     euraudnykn                                         DECIMAL     (9,4)                                                               ,  /* ユーロ－豪ドル（入金用） */
     yobin9x121                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２１ */
     yobin9x122                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２２ */
     yobin9x123                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２３ */
     yobin9x124                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２４ */
     yobin9x125                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２５ */
     yobin9x126                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２６ */
     yobin9x127                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１２７ */
     audusdnykn                                         DECIMAL     (9,4)                                                               ,  /* 豪ドル－米ドル（入金用） */
     audeurnykn                                         DECIMAL     (9,4)                                                               ,  /* 豪ドル－ユーロ（入金用） */
     yobin9x131                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３１ */
     yobin9x132                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３２ */
     yobin9x133                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３３ */
     yobin9x134                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３４ */
     yobin9x135                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３５ */
     yobin9x136                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３６ */
     yobin9x137                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１３７ */
     yobin9x141                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４１ */
     yobin9x142                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４２ */
     yobin9x143                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４３ */
     yobin9x144                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４４ */
     yobin9x145                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４５ */
     yobin9x146                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４６ */
     yobin9x147                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４７ */
     yobin9x148                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４８ */
     yobin9x149                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１４９ */
     yobin9x151                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５１ */
     yobin9x152                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５２ */
     yobin9x153                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５３ */
     yobin9x154                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５４ */
     yobin9x155                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５５ */
     yobin9x156                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５６ */
     yobin9x157                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５７ */
     yobin9x158                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５８ */
     yobin9x159                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１５９ */
     yobin9x161                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６１ */
     yobin9x162                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６２ */
     yobin9x163                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６３ */
     yobin9x164                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６４ */
     yobin9x165                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６５ */
     yobin9x166                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６６ */
     yobin9x167                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６７ */
     yobin9x168                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６８ */
     yobin9x169                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１６９ */
     yobin9x171                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７１ */
     yobin9x172                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７２ */
     yobin9x173                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７３ */
     yobin9x174                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７４ */
     yobin9x175                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７５ */
     yobin9x176                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７６ */
     yobin9x177                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７７ */
     yobin9x178                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７８ */
     yobin9x179                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１７９ */
     yobin9x181                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８１ */
     yobin9x182                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８２ */
     yobin9x183                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８３ */
     yobin9x184                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８４ */
     yobin9x185                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８５ */
     yobin9x186                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８６ */
     yobin9x187                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８７ */
     yobin9x188                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８８ */
     yobin9x189                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１８９ */
     yobin9x191                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９１ */
     yobin9x192                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９２ */
     yobin9x193                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９３ */
     yobin9x194                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９４ */
     yobin9x195                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９５ */
     yobin9x196                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９６ */
     yobin9x197                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９７ */
     yobin9x198                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９８ */
     yobin9x199                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿１９９ */
     yobin9x201                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０１ */
     yobin9x202                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０２ */
     yobin9x203                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０３ */
     yobin9x204                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０４ */
     yobin9x205                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０５ */
     yobin9x206                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０６ */
     yobin9x207                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０７ */
     yobin9x208                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０８ */
     yobin9x209                                         DECIMAL     (9,4)                                                               ,  /* 予備項目Ｎ９＿２０９ */
     usdjpysykn                                         DECIMAL     (9,2)                                                               ,  /* 米ドル－円（出金用） */
     eurjpysykn                                         DECIMAL     (9,2)                                                               ,  /* ユーロ－円（出金用） */
     audjpysykn                                         DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（出金用） */
     yobin9x301                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０１ */
     yobin9x302                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０２ */
     yobin9x303                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０３ */
     yobin9x304                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０４ */
     yobin9x305                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０５ */
     yobin9x306                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０６ */
     yobin9x307                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿３０７ */
     usdjpytts17pm                                      DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＳ）１７時 */
     usdjpyttb17pm                                      DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＢ）１７時 */
     usdjpyttm17pm                                      DECIMAL     (9,2)                                                               ,  /* 米ドル－円（ＴＴＭ）１７時 */
     eurjpytts17pm                                      DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＳ）１７時 */
     eurjpyttb17pm                                      DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＢ）１７時 */
     eurjpyttm17pm                                      DECIMAL     (9,2)                                                               ,  /* ユーロ－円（ＴＴＭ）１７時 */
     audjpytts17pm                                      DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＳ）１７時 */
     audjpyttb17pm                                      DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＢ）１７時 */
     audjpyttm17pm                                      DECIMAL     (9,2)                                                               ,  /* 豪ドル－円（ＴＴＭ）１７時 */
     yobin9x501                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０１ */
     yobin9x502                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０２ */
     yobin9x503                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０３ */
     yobin9x504                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０４ */
     yobin9x505                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０５ */
     yobin9x506                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０６ */
     yobin9x507                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０７ */
     yobin9x508                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０８ */
     yobin9x509                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５０９ */
     yobin9x510                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１０ */
     yobin9x511                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１１ */
     yobin9x512                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１２ */
     yobin9x513                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１３ */
     yobin9x514                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１４ */
     yobin9x515                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１５ */
     yobin9x516                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１６ */
     yobin9x517                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１７ */
     yobin9x518                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１８ */
     yobin9x519                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５１９ */
     yobin9x520                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５２０ */
     yobin9x521                                         DECIMAL     (9,2)                                                               ,  /* 予備項目Ｎ９＿５２１ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                                /* バージョン */
)
;

ALTER TABLE BT_KawaseRateData_Z ADD CONSTRAINT PK_KawaseRateData PRIMARY KEY (
     kwsratekjymd                                             , /* 為替レート基準日 */
     kwsrendoukbn                                               /* 為替レート連動区分 */
) ;
