CREATE TABLE HT_SisyaToukeiHokan_Z (
     sstmosno                                           VARCHAR     (9)                                                       NOT NULL  ,  /* 支社統計用申込番号 */
     renno                                              DECIMAL     (2)                                                       NOT NULL  ,  /* 連番 */
     syrctrltblkostime                                  VARCHAR     (17)                                                                ,  /* 処理コントロールTBL更新時間 */
     sstsyono                                           VARCHAR     (11)                                                                ,  /* 支社統計用証券番号 */
     sstmosym                                           VARCHAR     (6)                                                                 ,  /* 支社統計用申込月度 */
     sstmoskbn                                          VARCHAR     (1)                                                                 ,  /* 支社統計用申込区分 */
     sstbosyuudrtenatkikeitaikbn                        VARCHAR     (1)                                                                 ,  /* 支社統計用募集代理店扱形態区分 */
     sstkydatkikbn                                      VARCHAR     (1)                                                                 ,  /* 支社統計用共同扱区分 */
     sstatukaisyadrtenhyouji                            VARCHAR     (1)                                                                 ,  /* 支社統計用扱者代理店表示 */
     tratkiagcd                                         VARCHAR     (7)                                                                 ,  /* 取扱代理店コード */
     ssteigyouhonbusisyacd                              VARCHAR     (7)                                                                 ,  /* 支社統計用営業本部支社コード */
     sstsosikicd                                        VARCHAR     (7)                                                                 ,  /* 支社統計用組織コード */
     sstatkisyagyskkjsosikicd                           VARCHAR     (7)                                                                 ,  /* 支社統計用扱者業績計上先組織コード */
     sstcifcd                                           VARCHAR     (15)                                                                ,  /* 支社統計用ＣＩＦコード */
     sstatkisyadrtenatkiwari                            DECIMAL     (3)                                                                 ,  /* 支社統計用扱者代理店扱割合 */
     ssttsrybnwari                                      DECIMAL     (3)                                                                 ,  /* 支社統計用手数料分割割合 */
     sstsinhsys                                         DECIMAL     (11)                                                                ,  /* 支社統計用新保障Ｓ */
     sstsoukensuu                                       DECIMAL     (3)                                                                 ,  /* 支社統計用総件数 */
     sstkydatkidairitencd                               VARCHAR     (7)                                                                 ,  /* 支社統計用共同扱代理店コード */
     sstbosyuudrtenkobetuinfo1                          VARCHAR     (15)                                                                ,  /* 支社統計用募集代理店個別情報１ */
     sstbosyuudrtenkobetuinfo2                          VARCHAR     (15)                                                                ,  /* 支社統計用募集代理店個別情報２ */
     sstbosyuudrtenkobetuinfo3                          VARCHAR     (15)                                                                ,  /* 支社統計用募集代理店個別情報３ */
     sstbosyuudrtenkobetuinfo4                          VARCHAR     (15)                                                                ,  /* 支社統計用募集代理店個別情報４ */
     sstbosyuudrtenkobetuinfo5                          VARCHAR     (15)                                                                ,  /* 支社統計用募集代理店個別情報５ */
     sstbankkouincd                                     VARCHAR     (10)                                                                ,  /* 支社統計用銀行行員コード */
     sstdaihyoubosyuunincd                              VARCHAR     (6)                                                                 ,  /* 支社統計用代表募集人コード */
     sstatukaikojincd                                   VARCHAR     (6)                                                                 ,  /* 支社統計用扱者個人コード */
     sstkanjihihokensyanm                               VARCHAR     (32)                                                                ,  /* 支社統計用漢字被保険者名 */
     ssttansyukukjhhknnm                                VARCHAR     (16)                                                                ,  /* 支社統計用短縮漢字被保険者名 */
     ssthhknsyokugyoucd                                 VARCHAR     (3)                                                                 ,  /* 支社統計用被保険者職業コード */
     ssthhknnen2keta                                    VARCHAR     (2)                                                                 ,  /* 支社統計用被保険者年令（２桁） */
     ssthhknseikbn                                      VARCHAR     (1)                                                                 ,  /* 支社統計用被保険者性別区分 */
     ssthhknseiymd                                      VARCHAR     (8)                                                                 ,  /* 支社統計用被保険者生年月日 */
     sstkjkyknm                                         VARCHAR     (32)                                                                ,  /* 支社統計用漢字契約者名 */
     sstkjkyknm10                                       VARCHAR     (22)                                                                ,  /* 支社統計用漢字契約者名（１０文字） */
     sstknkyknm15                                       VARCHAR     (32)                                                                ,  /* 支社統計用カナ契約者名（１５文字） */
     sstknkyknm18                                       VARCHAR     (38)                                                                ,  /* 支社統計用カナ契約者名（１８文字） */
     sstkyksyanen                                       VARCHAR     (2)                                                                 ,  /* 支社統計用契約者年令 */
     sstkyksyaseikbn                                    VARCHAR     (1)                                                                 ,  /* 支社統計用契約者性別区分 */
     ssthjnkykhyj                                       VARCHAR     (1)                                                                 ,  /* 支社統計用法人契約表示 */
     sstkjhjnnm                                         VARCHAR     (62)                                                                ,  /* 支社統計用漢字法人名 */
     sstseirituyoukihontikucd                           VARCHAR     (8)                                                                 ,  /* 支社統計用成立率用基本地区コード */
     sstmossyoumetukbn                                  VARCHAR     (1)                                                                 ,  /* 支社統計用申込消滅区分 */
     sstkurikosiriyuukbn                                VARCHAR     (2)                                                                 ,  /* 支社統計用繰越理由区分 */
     sstnyknzumihyouji                                  VARCHAR     (1)                                                                 ,  /* 支社統計用入金済表示 */
     sstnyknjkkbn                                       VARCHAR     (1)                                                                 ,  /* 支社統計用入金状況区分 */
     ssthoujyoukokutikbn                                VARCHAR     (1)                                                                 ,  /* 支社統計用報状告知区分 */
     sstkykkeitaikbn                                    VARCHAR     (2)                                                                 ,  /* 支社統計用契約形態区分 */
     sstketteijkkbn                                     VARCHAR     (1)                                                                 ,  /* 支社統計用決定状況区分 */
     sstdakuhiketteijyoutaikbn                          VARCHAR     (2)                                                                 ,  /* 支社統計用諾否決定状態区分 */
     sstdakuhiketteikekkacd                             VARCHAR     (2)                                                                 ,  /* 支社統計用諾否決定結果コード */
     sstdakuhiketteiymd                                 VARCHAR     (8)                                                                 ,  /* 支社統計用諾否決定年月日 */
     ssttokusyujimutoriatukaikbn                        VARCHAR     (1)                                                                 ,  /* 支社統計用特殊事務取扱区分 */
     ssttoukeiyousinsakbn                               VARCHAR     (2)                                                                 ,  /* 支社統計用統計用診査区分 */
     ssthonninkakuninkbn                                VARCHAR     (2)                                                                 ,  /* 支社統計用本人確認区分 */
     sstdrtentsryhushrkykhyouji                         VARCHAR     (1)                                                                 ,  /* 支社統計用代理店手数料不支払契約表示 */
     sstnyknkanskanouhyouji                             VARCHAR     (1)                                                                 ,  /* 支社統計用入金勧奨可能表示 */
     sstdshukahyouji                                    VARCHAR     (1)                                                                 ,  /* 支社統計用ＤＳ付加表示 */
     sstsiteidairisktkykarihyouj                        VARCHAR     (1)                                                                 ,  /* 支社統計用指定代理請求特約有表示 */
     ssttokuteikanikokutikbn                            VARCHAR     (1)                                                                 ,  /* 支社統計用特定簡易告知区分 */
     sstkykkakuninsyuruikbn                             VARCHAR     (2)                                                                 ,  /* 支社統計用契約確認種類区分 */
     sstkykkakuninjkkbn1                                VARCHAR     (1)                                                                 ,  /* 支社統計用契約確認状況区分（1文字） */
     sstmosketteikekkakbn                               VARCHAR     (1)                                                                 ,  /* 支社統計用申込決定結果区分 */
     sstsinsazumihyouji                                 VARCHAR     (1)                                                                 ,  /* 支社統計用診査済表示 */
     sstannaisakicd                                     VARCHAR     (8)                                                                 ,  /* 支社統計用案内先コード */
     sstmosjkkbn                                        VARCHAR     (1)                                                                 ,  /* 支社統計用申込状況区分 */
     sstkihonhubi                                       VARCHAR     (1)                                                                 ,  /* 支社統計用基本不備 */
     sstsphubi                                          VARCHAR     (1)                                                                 ,  /* 支社統計用ＳＰ不備 */
     sstsseigenhubi                                     VARCHAR     (1)                                                                 ,  /* 支社統計用Ｓ制限不備 */
     sstnayosehumei                                     VARCHAR     (1)                                                                 ,  /* 支社統計用名寄不明 */
     ssttuusangendoover                                 VARCHAR     (1)                                                                 ,  /* 支社統計用通算限度オーバー */
     sstmosketteihoryuu                                 VARCHAR     (1)                                                                 ,  /* 支社統計用申込決定保留 */
     sstkykkakuninjissityuu                             VARCHAR     (1)                                                                 ,  /* 支社統計用契約確認実施中 */
     sstkokutiketteihoryuu                              VARCHAR     (1)                                                                 ,  /* 支社統計用告知決定保留 */
     ssthonsyaketteihoryuu                              VARCHAR     (1)                                                                 ,  /* 支社統計用本社決定保留 */
     sstseiymdhubi                                      VARCHAR     (1)                                                                 ,  /* 支社統計用生年月日不備 */
     sstphusoku                                         VARCHAR     (1)                                                                 ,  /* 支社統計用Ｐ不足 */
     sstseirituhoryuuuketuketyuu                        VARCHAR     (1)                                                                 ,  /* 支社統計用成立保留受付中 */
     sstpkakin                                          VARCHAR     (1)                                                                 ,  /* 支社統計用Ｐ過金 */
     sstketteihoryuuhubihyouji                          VARCHAR     (1)                                                                 ,  /* 支社統計用決定保留不備表示 */
     sstseirituhoryuuhubihyouji                         VARCHAR     (1)                                                                 ,  /* 支社統計用成立保留不備表示 */
     ssttoukeiyouhknsyuruikbn                           VARCHAR     (2)                                                                 ,  /* 支社統計用統計用保険種類区分 */
     ssthknsyuruinm                                     VARCHAR     (22)                                                                ,  /* 支社統計用保険種類名称 */
     ssthknkkn                                          VARCHAR     (2)                                                                 ,  /* 支社統計用保険期間 */
     sstphrkkikn                                        VARCHAR     (2)                                                                 ,  /* 支社統計用Ｐ払込期間 */
     ssthrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* 支社統計用払込回数区分 */
     ssthrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* 支社統計用払込経路区分 */
     sstnkshrtkykarihyouji                              VARCHAR     (1)                                                                 ,  /* 支社統計用年金支払特約有表示 */
     sstnkshrtkyknkkkn                                  VARCHAR     (2)                                                                 ,  /* 支社統計用年金支払特約年金期間 */
     sstjyunhsys                                        DECIMAL     (11)                                                                ,  /* 支社統計用純保障Ｓ */
     ssthsys                                            DECIMAL     (11)                                                                ,  /* 支社統計用保障Ｓ */
     sstkyktuuka                                        VARCHAR     (1)                                                                 ,  /* 支社統計用契約通貨 */
     ssthrktuuka                                        VARCHAR     (1)                                                                 ,  /* 支社統計用払込通貨 */
     ssttuukatanikbn                                    VARCHAR     (1)                                                                 ,  /* 支社統計用通貨単位区分 */
     sstfstphrkgkyen                                    DECIMAL     (11)                                                                ,  /* 支社統計用初回Ｐ払込必要額（円貨） */
     sstfstphrkgkhrktuukamoji                           VARCHAR     (11)                                                                ,  /* 支社統計用初回Ｐ払込必要額（払込通貨）（文字列） */
     sstfstphrkgkgaika                                  DECIMAL     (13,2)                                                              ,  /* 支社統計用初回Ｐ払込必要額（外貨） */
     sstfstpsshkhrkgkyen                                DECIMAL     (11)                                                                ,  /* 支社統計用初回Ｐ差引払込額（円貨） */
     sstyennykntkykarihyouji                            VARCHAR     (1)                                                                 ,  /* 支社統計用円入金特約有表示 */
     sstgaikanykntkykarihyouji                          VARCHAR     (1)                                                                 ,  /* 支社統計用外貨入金特約有表示 */
     ssyenshrtkykarihyouji                              VARCHAR     (1)                                                                 ,  /* 支社統計用円支払特約有表示 */
     sstkihonsgaika                                     DECIMAL     (13,2)                                                              ,  /* 支社統計用基本Ｓ（外貨） */
     ssttekiyoukawaserate                               DECIMAL     (7,4)                                                               ,  /* 支社統計用適用為替レート */
     sstkawaseratetekiyouymd                            VARCHAR     (8)                                                                 ,  /* 支社統計用為替レート適用年月日 */
     sstsakuseiymd                                      VARCHAR     (8)                                                                 ,  /* 支社統計用作成日 */
     sstmosymd                                          VARCHAR     (8)                                                                 ,  /* 支社統計用申込年月日 */
     sstkokutiymd                                       VARCHAR     (8)                                                                 ,  /* 支社統計用告知年月日 */
     sstmosnyuuryokuymd                                 VARCHAR     (8)                                                                 ,  /* 支社統計用申込入力年月日 */
     sstkykymd                                          VARCHAR     (8)                                                                 ,  /* 支社統計用契約年月日 */
     sstsekininkaisiymd                                 VARCHAR     (8)                                                                 ,  /* 支社統計用責任開始年月日 */
     sstsisyaketteisyoriymd                             VARCHAR     (8)                                                                 ,  /* 支社統計用支社決定処理年月日 */
     sstsyoukensakuseiymd                               VARCHAR     (8)                                                                 ,  /* 支社統計用証券作成年月日 */
     sstseisekikijyym                                   VARCHAR     (6)                                                                 ,  /* 支社統計用成績計上年月 */
     sstmossyoumetukakuteiymd                           VARCHAR     (8)                                                                 ,  /* 支社統計用申込消滅確定年月日 */
     sstdrtenkeijyouym                                  VARCHAR     (6)                                                                 ,  /* 支社統計用代理店計上年月 */
     sstmostoutyakuymd                                  VARCHAR     (8)                                                                 ,  /* 支社統計用申込書到着年月日 */
     sstkkttoutyakuymd                                  VARCHAR     (8)                                                                 ,  /* 支社統計用告知書到着年月日 */
     sstmossakuseiymd                                   VARCHAR     (8)                                                                 ,  /* 支社統計用申込書作成年月日 */
     sstmosksnym                                        VARCHAR     (6)                                                                 ,  /* 支社統計用申込起算年月 */
     sstkariseirituymd                                  VARCHAR     (8)                                                                 ,  /* 支社統計用仮成立年月日 */
     sstsinsayoteiymd                                   VARCHAR     (8)                                                                 ,  /* 支社統計用診査予定年月日 */
     sstkousinymd                                       VARCHAR     (8)                                                                 ,  /* 支社統計用更新年月日 */
     sstryousyuuymd                                     VARCHAR     (8)                                                                 ,  /* 支社統計用領収年月日 */
     sstfstpryousyuuymd                                 VARCHAR     (8)                                                                 ,  /* 支社統計用初回Ｐ領収年月日 */
     sstfstpnyknsyoriymd                                VARCHAR     (8)                                                                 ,  /* 支社統計用初回Ｐ入金処理年月日 */
     sstfstpnyknnaiyoukbn                               VARCHAR     (1)                                                                 ,  /* 支社統計用初回Ｐ入金内容区分 */
     sstfstpnyknhouhoukbn2                              VARCHAR     (2)                                                                 ,  /* 支社統計用初回Ｐ入金方法区分（２文字） */
     sstdrtenpaperlessmoshyj                            VARCHAR     (1)                                                                 ,  /* 支社統計用代理店ペーパーレス申込表示 */
     sstdrtenmostousyaukeymd                            VARCHAR     (8)                                                                 ,  /* 支社統計用代理店申込書当社受付年月日 */
     sstmkhyoutiyensysnikoukbn                          VARCHAR     (3)                                                                 ,  /* 支社統計用目標到達時円建終身保障移行区分 */
     sstsyksbyensitihsyutkykhyj                         VARCHAR     (1)                                                                 ,  /* 支社統計用初期死亡時円換算最低保証特約有表示 */
     sstjyudkaigomehrtkarihyj                           VARCHAR     (1)                                                                 ,  /* 支社統計用重度介護前払特約有表示 */
     gyoumuKousinKinou                                  VARCHAR     (50)                                                                ,  /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId                                  VARCHAR     (15)                                                                ,  /* 業務用更新者ＩＤ */
     gyoumuKousinTime                                   VARCHAR     (17)                                                                ,  /* 業務用更新時間 */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                             ,  /* バージョン */
     sstfstphrkgksiteituuka                             DECIMAL     (13,2)                                                              ,  /* 支社統計用初回Ｐ払込必要額（指定通貨） */
     sstteirituhaibunwari                               VARCHAR     (3)                                                                 ,  /* 支社統計用定率部分配分割合 */
     sstsueokikknkbn                                    VARCHAR     (1)                                                                 ,  /* 支社統計用据置期間区分 */
     sstnksyuruikbn1                                    VARCHAR     (1)                                                                 ,  /* 支社統計用年金種類（１文字） */
     sstyohurimiryou                                    VARCHAR     (1)                                                                 ,  /* 支社統計用預振未了 */
     sstkouzanyuuryokuymd                               VARCHAR     (8)                                                                 ,  /* 支社統計用口座入力年月日 */
     sstsetaitemosno                                    VARCHAR     (9)                                                                 ,  /* 支社統計用セット相手申込番号 */
     sstyakkanjyuryouhoukbn                             VARCHAR     (1)                                                                 ,  /* 支社統計用約款受領方法区分 */
     sstyakkanbunsyono                                  VARCHAR     (16)                                                                ,  /* 支社統計用約款文書番号 */
     sstkzhuritourokuhoukbn                             VARCHAR     (1)                                                                 ,  /* 支社統計用口座振替登録方法区分 */
     sstdai1hknkkn                                      VARCHAR     (2)                                                                 ,  /* 支社統計用第１保険期間 */
     sstcreditnyuuryokuymd                              VARCHAR     (8)                                                                 ,  /* 支社統計用クレジット入力年月日 */
     sstcreditmiryou                                    VARCHAR     (1)                                                                 ,  /* 支社統計用クレカ未了 */
     sstcredittrkhoukbn                                 VARCHAR     (1)                                                                 ,  /* 支社統計用クレジット登録方法区分 */
     sstcardbrandkbn                                    VARCHAR     (22)                                                                ,  /* 支社統計用カードブランド */
     sstcarddatasousinymd                               VARCHAR     (8)                                                                 ,  /* 支社統計用カードデータ送信日 */
     sstkzktrkservicekbn                                VARCHAR     (1)                                                                 ,  /* 支社統計用ご家族登録サービス区分 */
     sstkykdrtkykarihyj                                 VARCHAR     (1)                                                                 ,  /* 支社統計用契約者代理特約有表示 */
     sstteikishrtkykarihyouji                           VARCHAR     (1)                                                                 ,  /* 支社統計用定期支払特約有表示 */
     sstteikishrkinshrtuukakbn                          VARCHAR     (1)                                                                 ,  /* 支社統計用定期支払金支払通貨区分 */
     sstteikisiharaikin                                 DECIMAL     (13,2)                                                              ,  /* 支社統計用定期支払金 */
     sstkoureikzksetumeihoukbn                          VARCHAR     (1)                                                                 ,  /* 支社統計用高齢者ご家族等説明方法区分 */
     sstkoureimndnhukusuukaikbn                         VARCHAR     (1)                                                                 ,  /* 支社統計用高齢者面談複数回実施区分 */
     sstkoureitratkisyaigidskkbn                        VARCHAR     (1)                                                                    /* 支社統計用高齢者取扱者以外同席区分 */
)
;

ALTER TABLE HT_SisyaToukeiHokan_Z ADD CONSTRAINT PK_SisyaToukeiHokan PRIMARY KEY (
     sstmosno                                                 , /* 支社統計用申込番号 */
     renno                                                      /* 連番 */
) ;
