CREATE TABLE ZT_JigyounndsikiTkHoyuuRn_Z (
     zrnsequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnyobiv12                                         CHAR        (12)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１２ */
     zrndatakanrino                                     CHAR        (11)                                                      NOT NULL  ,  /* （連携用）データ管理番号 */
     zrnsuuriyoutokuyakukbn                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理用特約区分 */
     zrntokuyakugatakbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約型区分 */
     zrntokuyakukisi                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）特約期始 */
     zrnhihokensyaagev2                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令Ｖ２ */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnsisyacd                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支社コード */
     zrnsibucd                                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支部コード */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrnhhknhnsktodouhukencd                            CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者本籍都道府県コード */
     zrntokuyakus                                       DECIMAL     (9)                                                       NOT NULL  ,  /* （連携用）特約Ｓ */
     zrnsinkeityuutokbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契中途区分 */
     zrnsyukeiyakusrank                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約Ｓランク */
     zrnsyukeiyakuprank                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約Ｐランク */
     zrnsyukeiyakukykjigyouy                            CHAR        (4)                                                       NOT NULL  ,  /* （連携用）主契約契約事業年 */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrnryouritukbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）料率区分 */
     zrntksyuannaikykkbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特殊案内契約区分 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnmaruteiskeijihukahyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）マル定新契約時付加表示 */
     zrntenkankaisuu                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換回数 */
     zrntokuyakutokujyoukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約特条区分 */
     zrndai2maruhihyj                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第２マル被表示 */
     zrntokuteijyuusitusetkbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定重疾セット区分 */
     zrndugktnknsntkhuhukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）同額転換選択方法区分 */
     zrngengakutenkankykhyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）減額転換契約表示 */
     zrnhaitoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）配当区分 */
     zrnkusnmesyokaipjyuutouym                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）更新前初回Ｐ充当年月 */
     zrnsaigaitkyksyokusyucd                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）災害特約職種コード */
     zrnsykgycd                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）職業コード */
     zrntoukeiyousinsakbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）統計用診査区分 */
     zrngassansrank                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）合算Ｓランク */
     zrntoliplhyj                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＴＯＬＩＰＬ表示 */
     zrnpmenhukakbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免付加区分 */
     zrnpmenkbnv2                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ免区分Ｖ２ */
     zrnketteikijyunkanwakbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）決定基準緩和区分 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrntokuyakusedaikbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約世代区分 */
     zrnsiharainissuukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払日数区分 */
     zrnkakuseikatakbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カク成型区分 */
     zrnbosyuukeirokbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）募集経路区分 */
     zrndantaicd                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）団体コード */
     zrnpmenhutanpohyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免不担保表示 */
     zrntenkanhosyouminaosikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換保障見直区分 */
     zrnhosyouminaosikaisuu                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保障見直回数 */
     zrnqpackhyj                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｑパック表示 */
     zrnbunkatukbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分割区分 */
     zrnstdssnskbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出診査区分 */
     zrnstdssytikbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出集定区分 */
     zrnhosyoukikankbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保障期間区分 */
     zrnkeijyouym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）計上年月 */
     zrnbosyuukeitaikbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）募集形態区分 */
     zrndakuhikettisyacd                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定者コード */
     zrntokuyakukikan                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約期間 */
     zrnmannenreihyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）満年令表示 */
     zrnhhknnentysihyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者年令調整表示 */
     zrnkousinkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新区分 */
     zrnhokenhoutekiyouhyouji                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険法適用表示 */
     zrnsotodasiphkbnmnoshyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ不可分見直表示 */
     zrntokuteijyoutaihushrhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定状態不支払表示 */
     zrnrendouyousntkjyubbnhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）連動用新特条部分表示 */
     zrnmusentakukeiyakukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）無選択契約区分 */
     zrnknkuzusnzyrttekitkarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）健康増進乗率適用特約有表示 */
     zrnbluekeizokuhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｂｌｕｅ継続表示 */
     zrnzyrthntiyustatuskbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分 */
     zrnzyrthntiyustatuskbnx2                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿２ */
     zrnzyrthntiyustatuskbnx3                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿３ */
     zrnzyrthntiyustatuskbnx4                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿４ */
     zrnzyrthntiyustatuskbnx5                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿５ */
     zrnknkuzusnzyrt                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率 */
     zrnknkuzusnzyrtx2                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率＿２ */
     zrnpwrbksidhitekiyouhyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険料割引制度非適用表示 */
     zrnyobiv6                                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ６ */
     zrndatakanrino2                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号２ */
     zrndatakanrino3                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号３ */
     zrnsinkeiyakujivithkhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約時Ｖｉｔ保険表示 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnsuuriyouyobin4                                  CHAR        (4)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ４ */
     zrnyobin11x3                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３ */
     zrnraysystemhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＲＡＹシステム表示 */
     zrngaikakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外貨区分 */
     zrnkawaserate                                      DECIMAL     (9,6)                                                     NOT NULL  ,  /* （連携用）為替レート */
     zrnkawaseratetekiyouymd                            CHAR        (8)                                                       NOT NULL  ,  /* （連携用）為替レート適用年月日 */
     zrnkeiyakujiyoteiriritu                            DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）契約時予定利率 */
     zrngaikadatetokuyakus                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）外貨建特約Ｓ */
     zrngaikadatesyukeiyakus                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）外貨建主契約Ｓ */
     zrngaikadatesyukeiyakup                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）外貨建主契約Ｐ */
     zrnenkdtsbujsitihsyukngk                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）円貨建死亡時最低保証金額 */
     zrnsuuriyouyobin10x2                               CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０＿２ */
     zrnyobiv10x3                                       CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０＿３ */
     zrnmvatyouseigow                                   DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnyobin11x6                                       DECIMAL     (11)                                                      NOT NULL     /* （連携用）予備項目Ｎ１１＿６ */
)
;

ALTER TABLE ZT_JigyounndsikiTkHoyuuRn_Z ADD CONSTRAINT PK_JigyounndsikiTkHoyuuRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
