CREATE TABLE ZT_JigyounndsikiTkHoyuuTy_Z (
     ztysequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztyyobiv12                                         VARCHAR     (12)                                                                ,  /* （中継用）予備項目Ｖ１２ */
     ztydatakanrino                                     VARCHAR     (11)                                                                ,  /* （中継用）データ管理番号 */
     ztysuuriyoutokuyakukbn                             VARCHAR     (2)                                                                 ,  /* （中継用）数理用特約区分 */
     ztytokuyakugatakbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）特約型区分 */
     ztytokuyakukisi                                    VARCHAR     (8)                                                                 ,  /* （中継用）特約期始 */
     ztyhihokensyaagev2                                 VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令Ｖ２ */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztysisyacd                                         VARCHAR     (3)                                                                 ,  /* （中継用）支社コード */
     ztysibucd                                          VARCHAR     (3)                                                                 ,  /* （中継用）支部コード */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztyhhknhnsktodouhukencd                            VARCHAR     (2)                                                                 ,  /* （中継用）被保険者本籍都道府県コード */
     ztytokuyakus                                       DECIMAL     (9)                                                                 ,  /* （中継用）特約Ｓ */
     ztysinkeityuutokbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）新契中途区分 */
     ztysyukeiyakusrank                                 VARCHAR     (2)                                                                 ,  /* （中継用）主契約Ｓランク */
     ztysyukeiyakuprank                                 VARCHAR     (2)                                                                 ,  /* （中継用）主契約Ｐランク */
     ztysyukeiyakukykjigyouy                            VARCHAR     (4)                                                                 ,  /* （中継用）主契約契約事業年 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztyryouritukbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）料率区分 */
     ztytksyuannaikykkbn                                VARCHAR     (1)                                                                 ,  /* （中継用）特殊案内契約区分 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztymaruteiskeijihukahyj                            VARCHAR     (1)                                                                 ,  /* （中継用）マル定新契約時付加表示 */
     ztytenkankaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）転換回数 */
     ztytokuyakutokujyoukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）特約特条区分 */
     ztydai2maruhihyj                                   VARCHAR     (1)                                                                 ,  /* （中継用）第２マル被表示 */
     ztytokuteijyuusitusetkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）特定重疾セット区分 */
     ztydugktnknsntkhuhukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）同額転換選択方法区分 */
     ztygengakutenkankykhyj                             VARCHAR     (1)                                                                 ,  /* （中継用）減額転換契約表示 */
     ztyhaitoukbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）配当区分 */
     ztykusnmesyokaipjyuutouym                          VARCHAR     (6)                                                                 ,  /* （中継用）更新前初回Ｐ充当年月 */
     ztysaigaitkyksyokusyucd                            VARCHAR     (3)                                                                 ,  /* （中継用）災害特約職種コード */
     ztysykgycd                                         VARCHAR     (3)                                                                 ,  /* （中継用）職業コード */
     ztytoukeiyousinsakbn                               VARCHAR     (2)                                                                 ,  /* （中継用）統計用診査区分 */
     ztygassansrank                                     VARCHAR     (2)                                                                 ,  /* （中継用）合算Ｓランク */
     ztytoliplhyj                                       VARCHAR     (1)                                                                 ,  /* （中継用）ＴＯＬＩＰＬ表示 */
     ztypmenhukakbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免付加区分 */
     ztypmenkbnv2                                       VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ免区分Ｖ２ */
     ztyketteikijyunkanwakbn                            VARCHAR     (1)                                                                 ,  /* （中継用）決定基準緩和区分 */
     ztyhknsyuruikigousedaikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号世代区分 */
     ztytokuyakusedaikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）特約世代区分 */
     ztysiharainissuukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）支払日数区分 */
     ztykakuseikatakbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）カク成型区分 */
     ztybosyuukeirokbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）募集経路区分 */
     ztydantaicd                                        VARCHAR     (8)                                                                 ,  /* （中継用）団体コード */
     ztypmenhutanpohyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免不担保表示 */
     ztytenkanhosyouminaosikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）転換保障見直区分 */
     ztyhosyouminaosikaisuu                             VARCHAR     (1)                                                                 ,  /* （中継用）保障見直回数 */
     ztyqpackhyj                                        VARCHAR     (1)                                                                 ,  /* （中継用）Ｑパック表示 */
     ztybunkatukbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）分割区分 */
     ztystdssnskbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）外出診査区分 */
     ztystdssytikbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）外出集定区分 */
     ztyhosyoukikankbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）保障期間区分 */
     ztykeijyouym                                       VARCHAR     (6)                                                                 ,  /* （中継用）計上年月 */
     ztybosyuukeitaikbn                                 VARCHAR     (2)                                                                 ,  /* （中継用）募集形態区分 */
     ztydakuhikettisyacd                                VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定者コード */
     ztytokuyakukikan                                   VARCHAR     (2)                                                                 ,  /* （中継用）特約期間 */
     ztymannenreihyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）満年令表示 */
     ztyhhknnentysihyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）被保険者年令調整表示 */
     ztykousinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）更新区分 */
     ztyhokenhoutekiyouhyouji                           VARCHAR     (1)                                                                 ,  /* （中継用）保険法適用表示 */
     ztysotodasiphkbnmnoshyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ不可分見直表示 */
     ztytokuteijyoutaihushrhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）特定状態不支払表示 */
     ztyrendouyousntkjyubbnhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）連動用新特条部分表示 */
     ztymusentakukeiyakukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）無選択契約区分 */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekeizokuhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）Ｂｌｕｅ継続表示 */
     ztyzyrthntiyustatuskbn                             VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分 */
     ztyzyrthntiyustatuskbnx2                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿２ */
     ztyzyrthntiyustatuskbnx3                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿３ */
     ztyzyrthntiyustatuskbnx4                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿４ */
     ztyzyrthntiyustatuskbnx5                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿５ */
     ztyknkuzusnzyrt                                    VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率 */
     ztyknkuzusnzyrtx2                                  VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率＿２ */
     ztypwrbksidhitekiyouhyj                            VARCHAR     (1)                                                                 ,  /* （中継用）保険料割引制度非適用表示 */
     ztyyobiv6                                          VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６ */
     ztydatakanrino2                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号２ */
     ztydatakanrino3                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号３ */
     ztysinkeiyakujivithkhyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztysuuriyouyobin4                                  VARCHAR     (4)                                                                 ,  /* （中継用）数理用予備項目Ｎ４ */
     ztyyobin11x3                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿３ */
     ztyraysystemhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）外貨区分 */
     ztykawaserate                                      DECIMAL     (9,6)                                                               ,  /* （中継用）為替レート */
     ztykawaseratetekiyouymd                            VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日 */
     ztykeiyakujiyoteiriritu                            DECIMAL     (5,4)                                                               ,  /* （中継用）契約時予定利率 */
     ztygaikadatetokuyakus                              DECIMAL     (11)                                                                ,  /* （中継用）外貨建特約Ｓ */
     ztygaikadatesyukeiyakus                            DECIMAL     (11)                                                                ,  /* （中継用）外貨建主契約Ｓ */
     ztygaikadatesyukeiyakup                            DECIMAL     (11)                                                                ,  /* （中継用）外貨建主契約Ｐ */
     ztyenkdtsbujsitihsyukngk                           DECIMAL     (11)                                                                ,  /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10x2                               VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobiv10x3                                       VARCHAR     (10)                                                                ,  /* （中継用）予備項目Ｖ１０＿３ */
     ztymvatyouseigow                                   DECIMAL     (11)                                                                ,  /* （中継用）ＭＶＡ調整後Ｗ */
     ztymvakeisanjisknnjynbkn                           DECIMAL     (11)                                                                ,  /* （中継用）ＭＶＡ計算時責任準備金 */
     ztyyobin11x6                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿６ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                                /* バージョン */
)
;

ALTER TABLE ZT_JigyounndsikiTkHoyuuTy_Z ADD CONSTRAINT PK_JigyounndsikiTkHoyuuTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
