CREATE TABLE ZT_KeizokurituRenrakuULFTy_Z (
     ztysequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztysyono                                           VARCHAR     (11)                                                                ,  /* （中継用）証券番号 */
     ztyatukaikojincd                                   VARCHAR     (6)                                                                 ,  /* （中継用）扱者個人コード */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztysyukgu                                          VARCHAR     (2)                                                                 ,  /* （中継用）種類記号 */
     ztyhknkkn                                          VARCHAR     (2)                                                                 ,  /* （中継用）保険期間 */
     ztyphrkkikn                                        VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）才満期契約表示 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztytksyuannaikykkbn                                VARCHAR     (1)                                                                 ,  /* （中継用）特殊案内契約区分 */
     ztysyukinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）集金区分 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztyanniskcd                                        VARCHAR     (8)                                                                 ,  /* （中継用）案内先コード */
     ztysyuukintantousosikicd                           VARCHAR     (7)                                                                 ,  /* （中継用）集金担当組織コード */
     ztydnthrkkeirokbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）団体払込経路区分 */
     ztykhyuukousyoumetukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）（契約保全）有効消滅区分 */
     ztykeikatukisuu                                    VARCHAR     (2)                                                                 ,  /* （中継用）経過月数 */
     ztykeiyakukensuu                                   DECIMAL     (3,1)                                                               ,  /* （中継用）契約件数 */
     ztykihons                                          DECIMAL     (11)                                                                ,  /* （中継用）基本Ｓ */
     ztysyuuseis9keta                                   DECIMAL     (9)                                                                 ,  /* （中継用）修正Ｓ（９桁） */
     ztyhsys                                            DECIMAL     (11)                                                                ,  /* （中継用）保障Ｓ */
     ztyatukaisosikicd                                  VARCHAR     (7)                                                                 ,  /* （中継用）扱者組織コード */
     ztykyknm                                           VARCHAR     (38)                                                                ,  /* （中継用）契約者名 */
     ztykjkyknm                                         VARCHAR     (32)                                                                ,  /* （中継用）漢字契約者名 */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhhknnen2keta                                    VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令（２桁） */
     ztymarutokuhyj                                     VARCHAR     (1)                                                                 ,  /* （中継用）マル特表示 */
     ztytyohktyouseihyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）重複調整表示 */
     ztygyoumujyouhyouji                                VARCHAR     (1)                                                                 ,  /* （中継用）業務上表示 */
     ztykydatkihyj                                      VARCHAR     (1)                                                                 ,  /* （中継用）共同扱表示 */
     ztytenkankaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）転換回数 */
     ztykzktatkibanhktgksnkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）継続手当用基盤引継加算区分 */
     ztyjidoukousinhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）自動更新表示 */
     ztyskeijimrtiarihyj                                VARCHAR     (1)                                                                 ,  /* （中継用）新契約時マル定有表示 */
     ztyskeijikzkmrtiarihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）新契約時家族マル定有表示 */
     ztyhukkatukeiiarihyj                               VARCHAR     (1)                                                                 ,  /* （中継用）復活経緯有表示 */
     ztytyouhukutyouseiskeihyj                          VARCHAR     (1)                                                                 ,  /* （中継用）重複調整新契約表示 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztyphkbnmnoshyouji                                 VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ不可分見直表示 */
     ztykaigomarusyuuarihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）介護マル終有表示 */
     ztyheiyoubaraikeiyakukbn                           VARCHAR     (1)                                                                 ,  /* （中継用）併用払契約区分 */
     ztyhngkjidouentyoukbn                              VARCHAR     (1)                                                                 ,  /* （中継用）変額自動延長区分 */
     ztyhngkjidouentyoukikan                            VARCHAR     (3)                                                                 ,  /* （中継用）変額自動延長期間 */
     ztydoujihuhomrtisyukigou                           VARCHAR     (2)                                                                 ,  /* （中継用）同時付保マル定種類記号 */
     ztyyobiv1                                          VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１ */
     ztyseizonmrtiarihyj                                VARCHAR     (1)                                                                 ,  /* （中継用）生存マル定有表示 */
     ztyteigenmrtiarihyj                                VARCHAR     (1)                                                                 ,  /* （中継用）逓減マル定有表示 */
     ztyjyunkensuu                                      DECIMAL     (3,1)                                                               ,  /* （中継用）純件数 */
     ztyaltourokukeiyakuhyj                             VARCHAR     (1)                                                                 ,  /* （中継用）ＡＬ登録契約表示 */
     ztyjikokykhyj                                      VARCHAR     (1)                                                                 ,  /* （中継用）自己契約表示 */
     ztysynymrtiarihyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）収入マル定有表示 */
     ztykykniyutksytioukbn                              VARCHAR     (1)                                                                 ,  /* （中継用）契約内容特殊対応区分 */
     ztyreguardmrtiarihyj                               VARCHAR     (1)                                                                 ,  /* （中継用）リガードマル定有表示 */
     ztyreguardmrsyuarihyj                              VARCHAR     (1)                                                                 ,  /* （中継用）リガードマル終有表示 */
     ztyvguardmrtiarihyj                                VARCHAR     (1)                                                                 ,  /* （中継用）Ｖガードマル定有表示 */
     ztykousintkykhyj                                   VARCHAR     (1)                                                                 ,  /* （中継用）更新特約表示 */
     ztykousinkakuninnasihyj                            VARCHAR     (1)                                                                 ,  /* （中継用）更新確認無表示 */
     ztyfollowhunouhyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）フォロー不能表示 */
     ztykaigosynymrtiarihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）介護収入マル定有表示 */
     ztykaigoteigenmrtiarihyj                           VARCHAR     (1)                                                                 ,  /* （中継用）介護逓減マル定有表示 */
     ztysuperknkuseikatupackhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）スーパー健康生活パック表示 */
     ztykaigonktkykarihyj                               VARCHAR     (1)                                                                 ,  /* （中継用）介護年金特約有表示 */
     ztykaigomrtiarihyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）介護マル定有表示 */
     ztykeiyakukbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）契約区分 */
     ztykeizokutyuuihyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）継続注意表示 */
     ztykikeiyakutyuuihyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）既契約注意表示 */
     ztybosyuunincd                                     VARCHAR     (6)                                                                 ,  /* （中継用）募集人コード */
     ztyhsyuikktminaosikaisu                            VARCHAR     (2)                                                                 ,  /* （中継用）保障一括見直回数 */
     ztykykjiqpackhyj                                   VARCHAR     (1)                                                                 ,  /* （中継用）契約時Ｑパック表示 */
     ztybnkttnknkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）分割転換区分 */
     ztymrtikousinkbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）マル定更新区分 */
     ztypmenkbnv1                                       VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免区分Ｖ１ */
     ztyyouikunktkykarihyj                              VARCHAR     (1)                                                                 ,  /* （中継用）養育年金特約有表示 */
     ztysyoumetucd                                      VARCHAR     (4)                                                                 ,  /* （中継用）消滅コード */
     ztyseikatusyuunyuumrtis                            DECIMAL     (11)                                                                ,  /* （中継用）生活収入マル定Ｓ */
     ztyhitenkansyono1                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号１ */
     ztyhitenkansyono2                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号２ */
     ztyhitenkansyono3                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号３ */
     ztyhitenkansyono4                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号４ */
     ztyhitenkansyono5                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号５ */
     ztyhitenkansyono6                                  VARCHAR     (11)                                                                ,  /* （中継用）被転換証券番号６ */
     ztynenkansanp                                      DECIMAL     (11)                                                                ,  /* （中継用）年換算Ｐ */
     ztydai3bunyanenkansanp                             DECIMAL     (11)                                                                ,  /* （中継用）第３分野年換算Ｐ */
     ztykykym                                           VARCHAR     (6)                                                                 ,  /* （中継用）契約年月 */
     ztysytikbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）集定区分 */
     ztyfundbubunnenkansanp                             DECIMAL     (11)                                                                ,  /* （中継用）ファンド部分年換算Ｐ */
     ztyjikaipjyuutouym                                 VARCHAR     (6)                                                                 ,  /* （中継用）次回Ｐ充当年月 */
     ztykzktatsyuuseis                                  DECIMAL     (9)                                                                 ,  /* （中継用）継続手当用修正Ｓ */
     ztysiktsynymrtiarihyj                              VARCHAR     (1)                                                                 ,  /* （中継用）生活収入マル定有表示 */
     ztylivguardarihyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）ＬＩＶガード有表示 */
     ztylivguards                                       DECIMAL     (11)                                                                ,  /* （中継用）ＬＩＶガードＳ */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekzjtkaisiymd                                VARCHAR     (8)                                                                 ,  /* （中継用）Ｂｌｕｅ継続状態開始年月日　 */
     ztyknkuzusnzyrtstkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率用ステータス区分 */
     ztytokuyakuno                                      VARCHAR     (2)                                                                 ,  /* （中継用）特約番号 */
     ztyvityugusttkyuhyj                                VARCHAR     (1)                                                                 ,  /* （中継用）Ｖｉｔ優遇措置適用表示　 */
     ztykykdrtkykarihyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）契約者代理特約有表示 */
     ztystdairiseikyuutkykarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）指定代理請求特約有表示 */
     ztykzktourokuservicearihyj                         VARCHAR     (1)                                                                 ,  /* （中継用）家族登録サービス有表示 */
     ztyyendthnkymd8keta                                VARCHAR     (8)                                                                 ,  /* （中継用）円建変更日（８桁） */
     ztyyobiv16                                         VARCHAR     (16)                                                                ,  /* （中継用）予備項目Ｖ１６ */
     ztykhsyoumetujiyuu                                 VARCHAR     (2)                                                                 ,  /* （中継用）（契約保全）消滅事由 */
     ztyitijibaraipkyktuuka                             DECIMAL     (15,2)                                                              ,  /* （中継用）一時払Ｐ（契約通貨建） */
     ztykawaseraten5                                    DECIMAL     (5,2)                                                               ,  /* （中継用）為替レートＮ５ */
     ztynnknsnpssysyup                                  DECIMAL     (11)                                                                ,  /* （中継用）年換算Ｐ算出用主契約Ｐ */
     ztynknsnpssyhrkkskbn                               VARCHAR     (1)                                                                 ,  /* （中継用）年換算Ｐ算出用払込回数区分 */
     ztynnknsnpyennkgotmttrrt                           DECIMAL     (5,4)                                                               ,  /* （中継用）年換算Ｐ算出用円建年金変更後積立利率 */
     ztynnknsnpyennkgonksjtmttkn                        DECIMAL     (11)                                                                ,  /* （中継用）年換算Ｐ算出用円建年金変更後年金開始時積立金 */
     ztyyobiv71                                         VARCHAR     (71)                                                                ,  /* （中継用）予備項目Ｖ７１ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                                /* バージョン */
)
;

ALTER TABLE ZT_KeizokurituRenrakuULFTy_Z ADD CONSTRAINT PK_KeizokurituRenrakuULFTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
