CREATE TABLE ZT_KeizokurituRenrakuULFRn_Z (
     zrnsequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnatukaikojincd                                   CHAR        (6)                                                       NOT NULL  ,  /* （連携用）扱者個人コード */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrnsyukgu                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）種類記号 */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrntksyuannaikykkbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特殊案内契約区分 */
     zrnsyukinkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）集金区分 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnanniskcd                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）案内先コード */
     zrnsyuukintantousosikicd                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）集金担当組織コード */
     zrndnthrkkeirokbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）団体払込経路区分 */
     zrnkhyuukousyoumetukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）（契約保全）有効消滅区分 */
     zrnkeikatukisuu                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）経過月数 */
     zrnkeiyakukensuu                                   DECIMAL     (3,1)                                                     NOT NULL  ,  /* （連携用）契約件数 */
     zrnkihons                                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）基本Ｓ */
     zrnsyuuseis9keta                                   DECIMAL     (9)                                                       NOT NULL  ,  /* （連携用）修正Ｓ（９桁） */
     zrnhsys                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）保障Ｓ */
     zrnatukaisosikicd                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）扱者組織コード */
     zrnkyknm                                           CHAR        (18)                                                      NOT NULL  ,  /* （連携用）契約者名 */
     zrnkjkyknm                                         GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）漢字契約者名 */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhhknnen2keta                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令（２桁） */
     zrnmarutokuhyj                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）マル特表示 */
     zrntyohktyouseihyj                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）重複調整表示 */
     zrngyoumujyouhyouji                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）業務上表示 */
     zrnkydatkihyj                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）共同扱表示 */
     zrntenkankaisuu                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換回数 */
     zrnkzktatkibanhktgksnkbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）継続手当用基盤引継加算区分 */
     zrnjidoukousinhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）自動更新表示 */
     zrnskeijimrtiarihyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約時マル定有表示 */
     zrnskeijikzkmrtiarihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約時家族マル定有表示 */
     zrnhukkatukeiiarihyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）復活経緯有表示 */
     zrntyouhukutyouseiskeihyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）重複調整新契約表示 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnphkbnmnoshyouji                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ不可分見直表示 */
     zrnkaigomarusyuuarihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護マル終有表示 */
     zrnheiyoubaraikeiyakukbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）併用払契約区分 */
     zrnhngkjidouentyoukbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）変額自動延長区分 */
     zrnhngkjidouentyoukikan                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）変額自動延長期間 */
     zrndoujihuhomrtisyukigou                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）同時付保マル定種類記号 */
     zrnyobiv1                                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ１ */
     zrnseizonmrtiarihyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）生存マル定有表示 */
     zrnteigenmrtiarihyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）逓減マル定有表示 */
     zrnjyunkensuu                                      DECIMAL     (3,1)                                                     NOT NULL  ,  /* （連携用）純件数 */
     zrnaltourokukeiyakuhyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＡＬ登録契約表示 */
     zrnjikokykhyj                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）自己契約表示 */
     zrnsynymrtiarihyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）収入マル定有表示 */
     zrnkykniyutksytioukbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約内容特殊対応区分 */
     zrnreguardmrtiarihyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リガードマル定有表示 */
     zrnreguardmrsyuarihyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リガードマル終有表示 */
     zrnvguardmrtiarihyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｖガードマル定有表示 */
     zrnkousintkykhyj                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新特約表示 */
     zrnkousinkakuninnasihyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新確認無表示 */
     zrnfollowhunouhyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）フォロー不能表示 */
     zrnkaigosynymrtiarihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護収入マル定有表示 */
     zrnkaigoteigenmrtiarihyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護逓減マル定有表示 */
     zrnsuperknkuseikatupackhyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）スーパー健康生活パック表示 */
     zrnkaigonktkykarihyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護年金特約有表示 */
     zrnkaigomrtiarihyj                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護マル定有表示 */
     zrnkeiyakukbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約区分 */
     zrnkeizokutyuuihyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）継続注意表示 */
     zrnkikeiyakutyuuihyouji                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）既契約注意表示 */
     zrnbosyuunincd                                     CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集人コード */
     zrnhsyuikktminaosikaisu                            CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保障一括見直回数 */
     zrnkykjiqpackhyj                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約時Ｑパック表示 */
     zrnbnkttnknkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分割転換区分 */
     zrnmrtikousinkbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）マル定更新区分 */
     zrnpmenkbnv1                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免区分Ｖ１ */
     zrnyouikunktkykarihyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）養育年金特約有表示 */
     zrnsyoumetucd                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）消滅コード */
     zrnseikatusyuunyuumrtis                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）生活収入マル定Ｓ */
     zrnhitenkansyono1                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号１ */
     zrnhitenkansyono2                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号２ */
     zrnhitenkansyono3                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号３ */
     zrnhitenkansyono4                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号４ */
     zrnhitenkansyono5                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号５ */
     zrnhitenkansyono6                                  CHAR        (11)                                                      NOT NULL  ,  /* （連携用）被転換証券番号６ */
     zrnnenkansanp                                      DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）年換算Ｐ */
     zrndai3bunyanenkansanp                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）第３分野年換算Ｐ */
     zrnkykym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）契約年月 */
     zrnsytikbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）集定区分 */
     zrnfundbubunnenkansanp                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ファンド部分年換算Ｐ */
     zrnjikaipjyuutouym                                 CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回Ｐ充当年月 */
     zrnkzktatsyuuseis                                  DECIMAL     (9)                                                       NOT NULL  ,  /* （連携用）継続手当用修正Ｓ */
     zrnsiktsynymrtiarihyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）生活収入マル定有表示 */
     zrnlivguardarihyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＬＩＶガード有表示 */
     zrnlivguards                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ＬＩＶガードＳ */
     zrnknkuzusnzyrttekitkarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）健康増進乗率適用特約有表示 */
     zrnbluekzjtkaisiymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）Ｂｌｕｅ継続状態開始年月日　 */
     zrnknkuzusnzyrtstkbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）健康増進乗率用ステータス区分 */
     zrntokuyakuno                                      CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約番号 */
     zrnvityugusttkyuhyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｖｉｔ優遇措置適用表示　 */
     zrnkykdrtkykarihyj                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者代理特約有表示 */
     zrnstdairiseikyuutkykarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）指定代理請求特約有表示 */
     zrnkzktourokuservicearihyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）家族登録サービス有表示 */
     zrnyendthnkymd8keta                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）円建変更日（８桁） */
     zrnyobiv16                                         CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６ */
     zrnkhsyoumetujiyuu                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）（契約保全）消滅事由 */
     zrnitijibaraipkyktuuka                             DECIMAL     (15,2)                                                    NOT NULL  ,  /* （連携用）一時払Ｐ（契約通貨建） */
     zrnkawaseraten5                                    DECIMAL     (5,2)                                                     NOT NULL  ,  /* （連携用）為替レートＮ５ */
     zrnnnknsnpssysyup                                  DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）年換算Ｐ算出用主契約Ｐ */
     zrnnknsnpssyhrkkskbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年換算Ｐ算出用払込回数区分 */
     zrnnnknsnpyennkgotmttrrt                           DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）年換算Ｐ算出用円建年金変更後積立利率 */
     zrnnnknsnpyennkgonksjtmttkn                        DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）年換算Ｐ算出用円建年金変更後年金開始時積立金 */
     zrnyobiv71                                         CHAR        (71)                                                      NOT NULL     /* （連携用）予備項目Ｖ７１ */
)
;

ALTER TABLE ZT_KeizokurituRenrakuULFRn_Z ADD CONSTRAINT PK_KeizokurituRenrakuULFRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
