CREATE TABLE ZT_KydGWKykInfoRn_Z (
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnhknsyurui2keta                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類（２桁） */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnsinkeizkkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新規継続区分 */
     zrnsyuhosyucd                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）主契約保種コード */
     zrnmdhnaisyoumeicd                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）窓販用愛称名コード */
     zrnsyouhncd                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）商品コード */
     zrnmusymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込年月日 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnkykseirituymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約成立年月日 */
     zrnsekininkaisiymd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）責任開始年月日 */
     zrnsyokaipymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）初回Ｐ入金年月日 */
     zrnhjnkojinkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）法人個人区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrnhrkhuhukbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込方法区分 */
     zrnhrkymd                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払込日 */
     zrngoukeip2                                        DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）合計保険料２ */
     zrnitijibrp                                        DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）一時払保険料 */
     zrnbnkaisuu                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）分割回数 */
     zrnbnsyuruikbn                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）分割種類区分 */
     zrnbnkyk1kaip                                      DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）分割払契約１回分保険料 */
     zrnyobiv20                                         CHAR        (20)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２０ */
     zrnsyuhknkknkbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）主契約保険期間区分 */
     zrnsyuhknkkn                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約保険期間 */
     zrnsyuhrkkknkbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）主契約払込期間区分 */
     zrnsyuhrkkkn                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約払込期間 */
     zrnsyus                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）主契約保険金額 */
     zrnsyunm                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）主契約名称 */
     zrnidojiyukbn                                      CHAR        (2)                                                       NOT NULL  ,  /* （連携用）異動事由区分 */
     zrnsyoumetucd                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）消滅コード */
     zrnidokaiyakuymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）異動解約年月日 */
     zrnmankiymd                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）満期年月日 */
     zrnsibous                                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）死亡Ｓ */
     zrnidoukaiyakup                                    DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）異動解約保険料 */
     zrnsyukinkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）集金区分 */
     zrnhaitoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）配当区分 */
     zrncreditcardhrkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）クレジットカード払区分 */
     zrntkjykbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特条区分 */
     zrnsinsakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）診査区分 */
     zrnzeiseitekikakuhyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）税制適格表示 */
     zrnlivhukauhyj                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リビングニーズ付加表示 */
     zrnhrizmentyouhyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払済延長表示 */
     zrnkisokyknkshrhsykn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）基礎契約年金支払保証期間 */
     zrnnkshrkknkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金支払期間区分 */
     zrnnkshrkknnen                                     CHAR        (3)                                                       NOT NULL  ,  /* （連携用）年金支払期間年 */
     zrnnksueokikn                                      CHAR        (2)                                                       NOT NULL  ,  /* （連携用）年金据置期間 */
     zrnnkshrstartymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）年金支払開始年月日 */
     zrnnkuketorininkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金受取人区分 */
     zrnzennoup                                         DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）前納保険料 */
     zrnzennouendym                                     CHAR        (6)                                                       NOT NULL  ,  /* （連携用）前納終了年月 */
     zrnteikaiyakuhrkn                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）低解約返戻金期間 */
     zrnmosno                                           CHAR        (9)                                                       NOT NULL  ,  /* （連携用）申込番号 */
     zrntratkisyacd1                                    CHAR        (6)                                                       NOT NULL  ,  /* （連携用）取扱者コード１ */
     zrntratkisyacd2                                    CHAR        (6)                                                       NOT NULL  ,  /* （連携用）取扱者コード２ */
     zrndairiten1cd                                     CHAR        (7)                                                       NOT NULL  ,  /* （連携用）代理店１コード */
     zrndairiten2cd                                     CHAR        (7)                                                       NOT NULL  ,  /* （連携用）代理店２コード */
     zrnbsudirtnatkikeitaikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）募集代理店扱形態区分 */
     zrnbsyudiritnatkiwari1                             DECIMAL     (3)                                                       NOT NULL  ,  /* （連携用）募集代理店扱割合１ */
     zrnbsyudiritnatkiwari2                             DECIMAL     (3)                                                       NOT NULL  ,  /* （連携用）募集代理店扱割合２ */
     zrnyobiv20x2                                       CHAR        (20)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２０＿２ */
     zrntktyuutohukahyj                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約中途付加表示 */
     zrntksuu                                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）特約数 */
     zrntkhosyucd1                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード１ */
     zrntknm1                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称１ */
     zrntks1                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額１ */
     zrntkhknkknkbn1                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分１ */
     zrntkhknkkn1                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間１ */
     zrntkhrkkknkbn1                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分１ */
     zrntkhrkkkn1                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間１ */
     zrntkhosyucd2                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード２ */
     zrntknm2                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称２ */
     zrntks2                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額２ */
     zrntkhknkknkbn2                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分２ */
     zrntkhknkkn2                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間２ */
     zrntkhrkkknkbn2                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分２ */
     zrntkhrkkkn2                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間２ */
     zrntkhosyucd3                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード３ */
     zrntknm3                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称３ */
     zrntks3                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額３ */
     zrntkhknkknkbn3                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分３ */
     zrntkhknkkn3                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間３ */
     zrntkhrkkknkbn3                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分３ */
     zrntkhrkkkn3                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間３ */
     zrntkhosyucd4                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード４ */
     zrntknm4                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称４ */
     zrntks4                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額４ */
     zrntkhknkknkbn4                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分４ */
     zrntkhknkkn4                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間４ */
     zrntkhrkkknkbn4                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分４ */
     zrntkhrkkkn4                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間４ */
     zrntkhosyucd5                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード５ */
     zrntknm5                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称５ */
     zrntks5                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額５ */
     zrntkhknkknkbn5                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分５ */
     zrntkhknkkn5                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間５ */
     zrntkhrkkknkbn5                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分５ */
     zrntkhrkkkn5                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間５ */
     zrntkhosyucd6                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）特約保種コード６ */
     zrntknm6                                           GRAPHIC     (8)                                                       NOT NULL  ,  /* （連携用）特約名称６ */
     zrntks6                                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）特約保険金額６ */
     zrntkhknkknkbn6                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約保険期間区分６ */
     zrntkhknkkn6                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約保険期間６ */
     zrntkhrkkknkbn6                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約払込期間区分６ */
     zrntkhrkkkn6                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約払込期間６ */
     zrnsbuktnm                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名 */
     zrnkjsbuktnm                                       GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）漢字死亡受取人名 */
     zrnsbukttdk                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）死亡受取人続柄 */
     zrnsbuktnin                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）死亡受取人人数 */
     zrnyobiv28                                         CHAR        (28)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２８ */
     zrnyno7keta                                        CHAR        (7)                                                       NOT NULL  ,  /* （連携用）郵便番号（７桁） */
     zrntelnokydgw                                      CHAR        (15)                                                      NOT NULL  ,  /* （連携用）電話番号（共同ＧＷ） */
     zrnkyknmknkydgw                                    CHAR        (70)                                                      NOT NULL  ,  /* （連携用）契約者名（カナ）（共同ＧＷ） */
     zrnkyksyaseiymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約者生年月日 */
     zrnkyksyaseikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者性別区分 */
     zrntsinkihontikucd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）通信先基本地区コード */
     zrnkykadrkj50                                      GRAPHIC     (50)                                                      NOT NULL  ,  /* （連携用）契約者漢字住所５０ */
     zrnkyknmkjkydgw                                    GRAPHIC     (30)                                                      NOT NULL  ,  /* （連携用）契約者名（漢字）（共同ＧＷ） */
     zrnhhknmei                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）被保険者名 */
     zrnhhknnmkj                                        GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）被保険者名（漢字） */
     zrnhhknseiymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被保険者生年月日 */
     zrnhhknnen                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）被保険者年齢 */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhhkntdk                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者続柄 */
     zrnkzsyurui                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）口座種類 */
     zrnkouzano7keta                                    CHAR        (7)                                                       NOT NULL  ,  /* （連携用）口座番号（７桁） */
     zrnkzhurikaebankcd                                 CHAR        (4)                                                       NOT NULL  ,  /* （連携用）口座振替銀行番号 */
     zrnkzhurikaesitencd                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）口座振替支店番号 */
     zrnkanyuusyaknrno                                  CHAR        (15)                                                      NOT NULL  ,  /* （連携用）加入者管理番号 */
     zrnkyksiboumeighnkhyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者死亡名義変更表示 */
     zrnyobiv11                                         CHAR        (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１１ */
     zrnmnkuktkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）満期受取人区分 */
     zrnmnkuktnm1                                       CHAR        (18)                                                      NOT NULL  ,  /* （連携用）満期受取人名１ */
     zrnmnkuktnm2                                       CHAR        (18)                                                      NOT NULL  ,  /* （連携用）満期受取人名２ */
     zrnmnkuktnm3                                       CHAR        (18)                                                      NOT NULL  ,  /* （連携用）満期受取人名３ */
     zrnmnkuktnm4                                       CHAR        (18)                                                      NOT NULL  ,  /* （連携用）満期受取人名４ */
     zrnsbuktkbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）死亡受取人区分 */
     zrnsbuktnm1                                        CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名１ */
     zrnsbuktnm2                                        CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名２ */
     zrnsbuktnm3                                        CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名３ */
     zrnsbuktnm4                                        CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名４ */
     zrnyobiv20x3                                       CHAR        (20)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２０＿３ */
     zrnsyoriymd                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）処理年月日 */
     zrnkykmfksnctrlkh                                  DECIMAL     (7)                                                       NOT NULL  ,  /* （連携用）契約ＭＦ更新ＣＴＲ（保全） */
     zrnmkhtoutatuymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）目標到達年月日 */
     zrnkykhrkmtuuka                                    CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約者振込通貨 */
     zrnkykhrkmgk                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）契約者振込金額 */
     zrnikkatubaraikbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）一括払区分 */
     zrnikkatubaraikaisuu                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）一括払回数 */
     zrntousyokykjiyennyknrate                          DECIMAL     (7,2)                                                     NOT NULL  ,  /* （連携用）当初契約時円入金レート */
     zrnrendouritu                                      DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）連動率 */
     zrnteikishrritu                                    DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）定期支払率 */
     zrnyobiv25                                         CHAR        (25)                                                      NOT NULL     /* （連携用）予備項目Ｖ２５ */
)
;

ALTER TABLE ZT_KydGWKykInfoRn_Z ADD CONSTRAINT PK_KydGWKykInfoRn PRIMARY KEY (
     zrnsyono                                                 , /* （連携用）証券番号 */
     zrnsyoriymd                                              , /* （連携用）処理年月日 */
     zrnkykmfksnctrlkh                                          /* （連携用）契約ＭＦ更新ＣＴＲ（保全） */
) ;
