CREATE TABLE ZT_KbkSsuRnduHknKimatuVTy_Z (
     ztysequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztyyuukourecordlength                              DECIMAL     (7)                                                                 ,  /* （中継用）有効レコード長 */
     ztyrdwarea                                         VARCHAR     (4)                                                                 ,  /* （中継用）ＲＤＷ領域 */
     ztyrecordkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）レコード区分 */
     ztynenkinkaisigohyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）年金開始後表示 */
     ztynksgokurikosidhyj                               VARCHAR     (1)                                                                 ,  /* （中継用）年金開始後繰越Ｄ表示 */
     ztykeijyouym                                       VARCHAR     (6)                                                                 ,  /* （中継用）計上年月 */
     ztyidojiyukbn                                      VARCHAR     (2)                                                                 ,  /* （中継用）異動事由区分 */
     ztyzougenkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）増減区分 */
     ztyidourecordkbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）異動レコード区分 */
     ztykeijyouctrlkbn                                  VARCHAR     (2)                                                                 ,  /* （中継用）計上コントロール区分 */
     ztyhenkousyoriymd                                  VARCHAR     (8)                                                                 ,  /* （中継用）変更処理年月日 */
     ztykykmfksnctr                                     DECIMAL     (7)                                                                 ,  /* （中継用）契約ＭＦ更新ＣＴＲ */
     ztyrecordctr                                       DECIMAL     (3)                                                                 ,  /* （中継用）レコードＣＴＲ */
     ztysuuriyoukouryokukaisiymd                        VARCHAR     (8)                                                                 ,  /* （中継用）数理用効力開始年月日 */
     ztydenymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）伝票日付 */
     ztybluekeizokuhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）Ｂｌｕｅ継続表示 */
     ztysuuriyouyobin1x2                                VARCHAR     (1)                                                                 ,  /* （中継用）数理用予備項目Ｎ１＿２ */
     ztytoukeikeijyoukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）統計計上区分 */
     ztyraysystemhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）ＲＡＹシステム表示 */
     ztyzenkiidouteiseikbn                              VARCHAR     (1)                                                                 ,  /* （中継用）前期異動訂正区分 */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztytenkangokeiyakubosyuuym                         VARCHAR     (6)                                                                 ,  /* （中継用）転換後契約募集年月 */
     ztyidoujiyuucd                                     VARCHAR     (3)                                                                 ,  /* （中継用）異動事由コード */
     ztysyoricd                                         VARCHAR     (4)                                                                 ,  /* （中継用）処理コード */
     ztysekininteiseihyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）責任訂正表示 */
     ztysuuriyouyobin8                                  VARCHAR     (8)                                                                 ,  /* （中継用）数理用予備項目Ｎ８ */
     ztysihankibikinkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）四半期備金区分 */
     ztysuuriyouyobin1x3                                VARCHAR     (1)                                                                 ,  /* （中継用）数理用予備項目Ｎ１＿３ */
     ztydatakanrino                                     VARCHAR     (11)                                                                ,  /* （中継用）データ管理番号 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号世代区分 */
     ztysotodasipmenkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ免区分 */
     ztystdssytikbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）外出集定区分 */
     ztystdssnskbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）外出診査区分 */
     ztysotodasimanagehyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）外出満年令表示 */
     ztysotodasiphkbnmnoshyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ不可分見直表示 */
     ztystdsstkjytkyuhyj                                VARCHAR     (1)                                                                 ,  /* （中継用）外出新特条適用表示 */
     ztykbnkeiriyousegmentkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用利源分析区分 */
     ztysuurisyuruicd                                   VARCHAR     (2)                                                                 ,  /* （中継用）数理種類コード */
     ztyhosyoukinoukbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）保障機能区分 */
     ztydaikbn                                          VARCHAR     (2)                                                                 ,  /* （中継用）大区分 */
     ztytyuukbn                                         VARCHAR     (4)                                                                 ,  /* （中継用）中区分 */
     ztysyoukbn                                         VARCHAR     (4)                                                                 ,  /* （中継用）小区分 */
     ztysedaikbn                                        VARCHAR     (4)                                                                 ,  /* （中継用）世代区分 */
     ztyharaikatakbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）払方区分 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztyhknkkn                                          VARCHAR     (2)                                                                 ,  /* （中継用）保険期間 */
     ztyphrkkikn                                        VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）才満期契約表示 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztytksyuannaikykkbn                                VARCHAR     (1)                                                                 ,  /* （中継用）特殊案内契約区分 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztysdpdkbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ建Ｐ建区分 */
     ztyryouritukbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）料率区分 */
     ztyao3tyou3sibousdatehyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）青３長３死亡Ｓ建表示 */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2                                 VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令Ｖ２ */
     ztykyksyanen                                       VARCHAR     (2)                                                                 ,  /* （中継用）契約者年令 */
     ztydai2hhknnen                                     VARCHAR     (2)                                                                 ,  /* （中継用）第２被保険者年令 */
     ztytkbthsyumnryuhyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）特別保障満了表示 */
     ztysyukeiyakupwaribikikbn                          VARCHAR     (2)                                                                 ,  /* （中継用）主契約Ｐ割引区分 */
     ztytenkanwaribikikbn                               VARCHAR     (2)                                                                 ,  /* （中継用）転換割引区分 */
     ztyyuuhitutnknyuguryurtkbn                         VARCHAR     (2)                                                                 ,  /* （中継用）有配当転換優遇料率区分 */
     ztysyukeiyakup                                     DECIMAL     (11)                                                                ,  /* （中継用）主契約Ｐ */
     ztytokujyoup                                       DECIMAL     (11)                                                                ,  /* （中継用）特条Ｐ */
     ztysiteizukisyukeiyakup                            DECIMAL     (11)                                                                ,  /* （中継用）指定月主契約Ｐ */
     ztykihons                                          DECIMAL     (11)                                                                ,  /* （中継用）基本Ｓ */
     ztysibous                                          DECIMAL     (11)                                                                ,  /* （中継用）死亡Ｓ */
     ztyhenkougokihons                                  DECIMAL     (11)                                                                ,  /* （中継用）変更後基本Ｓ */
     ztyhenkougosibous                                  DECIMAL     (11)                                                                ,  /* （中継用）変更後死亡Ｓ */
     ztyhenkouymd                                       VARCHAR     (8)                                                                 ,  /* （中継用）変更年月日 */
     ztyentyoukikan                                     VARCHAR     (4)                                                                 ,  /* （中継用）延長期間 */
     ztyseizonkyuuhukinsiteimd                          VARCHAR     (4)                                                                 ,  /* （中継用）生存給付金指定月日 */
     ztysyukeiyakusiharaikingaku                        DECIMAL     (11)                                                                ,  /* （中継用）主契約支払金額 */
     ztyatukaisisyatodouhukencd                         VARCHAR     (2)                                                                 ,  /* （中継用）扱支社都道府県コード */
     ztytokuyakuhukasuu                                 DECIMAL     (3)                                                                 ,  /* （中継用）特約付加数 */
     ztydi2hknkknikoujihisyaage                         VARCHAR     (2)                                                                 ,  /* （中継用）第２保険期間移行時被者年令 */
     ztyhrimnentyoumaephrkkkn                           VARCHAR     (2)                                                                 ,  /* （中継用）払満延長前Ｐ払込期間 */
     ztytokubetuhosyoukikan                             VARCHAR     (2)                                                                 ,  /* （中継用）特別保障期間 */
     ztykousinmanryouage                                VARCHAR     (2)                                                                 ,  /* （中継用）更新満了年令 */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztykuriagekurisagekbn                              VARCHAR     (1)                                                                 ,  /* （中継用）繰上げ繰下げ区分 */
     ztyhrizmjhknsyukigousdkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）払済時保険種類記号世代区分 */
     ztykrsgjhknsyukigousdkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）繰下げ時保険種類記号世代区分 */
     ztysotodasisyouhinkaiteikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）外出商品改定区分 */
     ztyyobiv4                                          VARCHAR     (4)                                                                 ,  /* （中継用）予備項目Ｖ４ */
     ztygoukeitenkans                                   DECIMAL     (11)                                                                ,  /* （中継用）合計転換Ｓ */
     ztygoukeipbubuntenkans                             DECIMAL     (11)                                                                ,  /* （中継用）合計Ｐ部分転換Ｓ */
     ztytenkanteikisyuruikigou                          VARCHAR     (2)                                                                 ,  /* （中継用）転換定期種類記号 */
     ztytenkanteikikigousedaikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号世代区分 */
     ztytnkntiksotodasikusnkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期外出更新区分 */
     ztytnkntikstdspmenkbn                              VARCHAR     (1)                                                                 ,  /* （中継用）転換定期外出Ｐ免区分 */
     ztytenkanteikikigouyobi                            VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備 */
     ztytenkanteikikikan                                VARCHAR     (2)                                                                 ,  /* （中継用）転換定期期間 */
     ztygoukeitenkanteikis                              DECIMAL     (11)                                                                ,  /* （中継用）合計転換定期Ｓ */
     ztytnknteikinkshrkkn                               VARCHAR     (2)                                                                 ,  /* （中継用）転換定期年金支払期間 */
     ztytenkansiharaikingaku                            DECIMAL     (11)                                                                ,  /* （中継用）転換支払金額 */
     ztytnkntikshrkngk                                  DECIMAL     (11)                                                                ,  /* （中継用）転換定期支払金額 */
     ztytenkankaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）転換回数 */
     ztygoukeitenkankakaku                              DECIMAL     (11)                                                                ,  /* （中継用）合計転換価格 */
     ztytnknkhnbbnjyuturt                               DECIMAL     (11,6)                                                              ,  /* （中継用）転換基本部分充当率 */
     ztywnasigoukeitenkanteikis                         DECIMAL     (11)                                                                ,  /* （中継用）Ｗなし合計転換定期Ｓ */
     ztytnknteikikousinmnryouage                        VARCHAR     (2)                                                                 ,  /* （中継用）転換定期更新満了年令 */
     ztyyobiv5                                          VARCHAR     (5)                                                                 ,  /* （中継用）予備項目Ｖ５ */
     ztykanyujidatakanrino                              VARCHAR     (11)                                                                ,  /* （中継用）加入時データ管理番号 */
     ztykanyujikykymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）加入時契約年月日 */
     ztykanyuujihihokensyaage                           VARCHAR     (2)                                                                 ,  /* （中継用）加入時被保険者年令 */
     ztykanyuujitenkanhyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）加入時転換表示 */
     ztyhsyuikktminaosikaisu                            VARCHAR     (2)                                                                 ,  /* （中継用）保障一括見直回数 */
     ztysknnjynbknsisnrt                                DECIMAL     (11,9)                                                              ,  /* （中継用）責任準備金精算率 */
     ztytkjykbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）特条区分 */
     ztysakugenkikan                                    VARCHAR     (2)                                                                 ,  /* （中継用）削減期間 */
     ztyryoumasihyouten                                 DECIMAL     (5)                                                                 ,  /* （中継用）料増標点 */
     ztysykyktkjyuryumsratehyj                          VARCHAR     (1)                                                                 ,  /* （中継用）主契約特条料増レート表示 */
     ztysykyktkjyuryumsrate                             DECIMAL     (9,6)                                                               ,  /* （中継用）主契約特条料増レート */
     ztydai2tokujyoukbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）第２特条区分 */
     ztydai2sakugenkikan                                VARCHAR     (2)                                                                 ,  /* （中継用）第２削減期間 */
     ztydai2ryoumasihyouten                             DECIMAL     (5)                                                                 ,  /* （中継用）第２料増標点 */
     ztytokuteibuijyoukenhyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）特定部位条件表示 */
     ztytokuteibuino1                                   VARCHAR     (2)                                                                 ,  /* （中継用）特定部位番号１ */
     ztyhtnpkkn1                                        VARCHAR     (2)                                                                 ,  /* （中継用）不担保期間１ */
     ztytokuteibuino2                                   VARCHAR     (2)                                                                 ,  /* （中継用）特定部位番号２ */
     ztyhtnpkkn2                                        VARCHAR     (2)                                                                 ,  /* （中継用）不担保期間２ */
     ztymhituiryuyutktbijyknhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）無配当医療用特定部位条件表示 */
     ztymuhaitouiryouyoutktbino1                        VARCHAR     (2)                                                                 ,  /* （中継用）無配当医療用特定部位番号１ */
     ztymuhaitouiryouyouhtnpkkn1                        VARCHAR     (2)                                                                 ,  /* （中継用）無配当医療用不担保期間１ */
     ztymuhaitouiryouyoutktbino2                        VARCHAR     (2)                                                                 ,  /* （中継用）無配当医療用特定部位番号２ */
     ztymuhaitouiryouyouhtnpkkn2                        VARCHAR     (2)                                                                 ,  /* （中継用）無配当医療用不担保期間２ */
     ztysiteizukipwarimasihyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）指定月Ｐ割増表示 */
     ztypwarimasisiteim1                                VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ割増指定月１ */
     ztypwarimasisiteim2                                VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ割増指定月２ */
     ztysiteimsykykpbairitu                             VARCHAR     (2)                                                                 ,  /* （中継用）指定月主契約Ｐ倍率 */
     ztysaisyuusiteiym                                  VARCHAR     (6)                                                                 ,  /* （中継用）最終指定年月 */
     ztysykykkitmttvkeisanym                            VARCHAR     (6)                                                                 ,  /* （中継用）主契約既積立Ｖ計算年月 */
     ztysykykkitmttsknnjynbkngk                         DECIMAL     (11)                                                                ,  /* （中継用）主契約既積立責任準備金額 */
     ztydftumitatekingaku                               DECIMAL     (11)                                                                ,  /* （中継用）ＤＦ積立金額 */
     ztydftumimasikin                                   DECIMAL     (11)                                                                ,  /* （中継用）ＤＦ積増金 */
     ztyvbubundftenkankakaku                            DECIMAL     (11)                                                                ,  /* （中継用）Ｖ部分ＤＦ転換価格 */
     ztydpbubundftenkankakaku                           DECIMAL     (11)                                                                ,  /* （中継用）ＤＰ部分ＤＦ転換価格 */
     ztydftmttkngkitjbrbbn                              DECIMAL     (11)                                                                ,  /* （中継用）ＤＦ積立金額一時払部分 */
     ztyhendous                                         DECIMAL     (11)                                                                ,  /* （中継用）変動Ｓ */
     ztyhengakujigyounendomatucv                        DECIMAL     (11)                                                                ,  /* （中継用）変額事業年度末ＣＶ */
     ztyitibuitijibarais                                DECIMAL     (11)                                                                ,  /* （中継用）一部一時払Ｓ */
     ztyitibuitijibaraip                                DECIMAL     (11)                                                                ,  /* （中継用）一部一時払Ｐ */
     ztyitibitjbrshrkngk                                DECIMAL     (11)                                                                ,  /* （中継用）一部一時払支払金額 */
     ztygoukeicv                                        DECIMAL     (11)                                                                ,  /* （中継用）合計ＣＶ */
     ztyminasicv                                        DECIMAL     (11)                                                                ,  /* （中継用）みなしＣＶ */
     ztyloanfund                                        DECIMAL     (11)                                                                ,  /* （中継用）ローンファンド */
     ztysaiteihosyougaku                                DECIMAL     (11)                                                                ,  /* （中継用）最低保証額 */
     ztyhngksitihsyuyusykykp                            DECIMAL     (11)                                                                ,  /* （中継用）変額最低保証用主契約Ｐ */
     ztyhijynbrivasbujsitihsyugk                        DECIMAL     (11)                                                                ,  /* （中継用）平準払ＶＡ死亡時最低保証金額 */
     ztyhijynbrivamnkjsitihsyugk                        DECIMAL     (11)                                                                ,  /* （中継用）平準払ＶＡ満期時最低保証金額 */
     ztysiinkbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）死因区分 */
     ztymudkaimasikihons                                DECIMAL     (11)                                                                ,  /* （中継用）ミューＤ買増基本Ｓ */
     ztykaimasiymd                                      VARCHAR     (8)                                                                 ,  /* （中継用）買増年月日 */
     ztykaimasikikan                                    VARCHAR     (2)                                                                 ,  /* （中継用）買増期間 */
     ztyhikitugikaimasis                                DECIMAL     (11)                                                                ,  /* （中継用）引継買増Ｓ */
     ztymudkaimasisiharaikingaku                        DECIMAL     (11)                                                                ,  /* （中継用）ミューＤ買増支払金額 */
     ztyszoukouryokukaisiymdx1                          VARCHAR     (8)                                                                 ,  /* （中継用）Ｓ増効力開始年月日＿１ */
     ztyszouhokensyuruikigoux1                          VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増保険種類記号＿１ */
     ztyszoukigousedaikbnx1                             VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ増記号世代区分＿１ */
     ztyszoukikanx1                                     VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増期間＿１ */
     ztyszouhihokensyaagex1                             VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増被保険者年令＿１ */
     ztyszoudai2hihknsyaagex1                           VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増第２被保険者年令＿１ */
     ztyzoukasx1                                        DECIMAL     (11)                                                                ,  /* （中継用）増加Ｓ＿１ */
     ztyzennendozoukasx1                                DECIMAL     (11)                                                                ,  /* （中継用）前年度増加Ｓ＿１ */
     ztyszousiharaikingakux1                            DECIMAL     (11)                                                                ,  /* （中継用）Ｓ増支払金額＿１ */
     ztyszoukouryokukaisiymdx2                          VARCHAR     (8)                                                                 ,  /* （中継用）Ｓ増効力開始年月日＿２ */
     ztyszouhokensyuruikigoux2                          VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増保険種類記号＿２ */
     ztyszoukigousedaikbnx2                             VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ増記号世代区分＿２ */
     ztyszoukikanx2                                     VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増期間＿２ */
     ztyszouhihokensyaagex2                             VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増被保険者年令＿２ */
     ztyszoudai2hihknsyaagex2                           VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増第２被保険者年令＿２ */
     ztyzoukasx2                                        DECIMAL     (11)                                                                ,  /* （中継用）増加Ｓ＿２ */
     ztyzennendozoukasx2                                DECIMAL     (11)                                                                ,  /* （中継用）前年度増加Ｓ＿２ */
     ztyszousiharaikingakux2                            DECIMAL     (11)                                                                ,  /* （中継用）Ｓ増支払金額＿２ */
     ztysuuriyouyobin1x5                                VARCHAR     (1)                                                                 ,  /* （中継用）数理用予備項目Ｎ１＿５ */
     ztysuuriyouyobin1x6                                VARCHAR     (1)                                                                 ,  /* （中継用）数理用予備項目Ｎ１＿６ */
     ztyhrimngkizktkykpmenhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）払満後継続特約Ｐ免表示 */
     ztymisyuustartym                                   VARCHAR     (6)                                                                 ,  /* （中継用）未収開始年月 */
     ztymisyuukaisuu                                    VARCHAR     (2)                                                                 ,  /* （中継用）未収回数 */
     ztyitjbrtkykkousnuktkarhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）一時払特約更新受付有表示 */
     ztygyousekihyoujis                                 DECIMAL     (11)                                                                ,  /* （中継用）業績表示Ｓ */
     ztysykykgyusekihyjs                                DECIMAL     (11)                                                                ,  /* （中継用）主契約業績表示Ｓ */
     ztytenkangyousekihyoujis                           DECIMAL     (11)                                                                ,  /* （中継用）転換業績表示Ｓ */
     ztytnknteikigyousekihyjs                           DECIMAL     (11)                                                                ,  /* （中継用）転換定期業績表示Ｓ */
     ztytnkndpbbngyuskhyjs                              DECIMAL     (11)                                                                ,  /* （中継用）転換ＤＰ部分業績表示Ｓ */
     ztykykjyoutai                                      VARCHAR     (1)                                                                 ,  /* （中継用）契約状態 */
     ztypmenhukakbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免付加区分 */
     ztykousinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）更新区分 */
     ztymankiyoteikbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）満期予定区分 */
     ztysykyktikmnkyoteikbn                             VARCHAR     (1)                                                                 ,  /* （中継用）主契約定期満期予定区分 */
     ztytnknsykykkhnmnkytikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）転換主契約基本満期予定区分 */
     ztytnknsykyktikmnkytikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）転換主契約定期満期予定区分 */
     ztytenkanteikimankiyoteikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）転換定期満期予定区分 */
     ztyszoumankiyoteikbnx1                             VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ増満期予定区分＿１ */
     ztyszoumankiyoteikbnx2                             VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ増満期予定区分＿２ */
     ztyvestingmankiyoteikbn                            VARCHAR     (1)                                                                 ,  /* （中継用）ベスティング満期予定区分 */
     ztyvkeisanhyouji                                   VARCHAR     (1)                                                                 ,  /* （中継用）Ｖ計算表示 */
     ztytoukisinkeiyakuhyouji                           VARCHAR     (1)                                                                 ,  /* （中継用）当期新契約表示 */
     ztysykykhokenhoutekiyouhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）主契約保険法適用表示 */
     ztytokuteijyoutaihushrhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）特定状態不支払表示 */
     ztyytirrthndsysnmnskaisuu                          VARCHAR     (1)                                                                 ,  /* （中継用）予定利率変動終身見直回数 */
     ztysuuriyouyobin3                                  VARCHAR     (3)                                                                 ,  /* （中継用）数理用予備項目Ｎ３ */
     ztysuuriyouyobin11                                 VARCHAR     (11)                                                                ,  /* （中継用）数理用予備項目Ｎ１１ */
     ztywnasigoukeitenkankakaku                         DECIMAL     (11)                                                                ,  /* （中継用）Ｗなし合計転換価格 */
     ztyyobin11                                         DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２ */
     ztyyobin11x3                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿３ */
     ztytukibaraikansantokujyoup                        DECIMAL     (11)                                                                ,  /* （中継用）月払換算特条Ｐ */
     ztytnkngkykkssnkijyuym                             VARCHAR     (6)                                                                 ,  /* （中継用）転換後契約決算計上年月 */
     ztysaiteihosyouhyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）最低保証表示 */
     ztysuuriyouyobin8x2                                VARCHAR     (8)                                                                 ,  /* （中継用）数理用予備項目Ｎ８＿２ */
     ztysuuriyouyobin14                                 VARCHAR     (14)                                                                ,  /* （中継用）数理用予備項目Ｎ１４ */
     ztyhrimngtkykphrkkaisuukbn                         VARCHAR     (1)                                                                 ,  /* （中継用）払満後特約Ｐ払込回数区分 */
     ztyhrimngtkykphrkkirkbn                            VARCHAR     (1)                                                                 ,  /* （中継用）払満後特約Ｐ払込経路区分 */
     ztyhrimngtkykpryurtkbn                             VARCHAR     (1)                                                                 ,  /* （中継用）払満後特約Ｐ料率区分 */
     ztyyobiv13                                         VARCHAR     (13)                                                                ,  /* （中継用）予備項目Ｖ１３ */
     ztyidoujisaiteihosyoukngk                          DECIMAL     (11)                                                                ,  /* （中継用）異動時最低保証金額 */
     ztyidoujisaiteihosyoucost                          DECIMAL     (11)                                                                ,  /* （中継用）異動時最低保証コスト */
     ztysinhokenfundtumitatekin                         DECIMAL     (11)                                                                ,  /* （中継用）新保険ファンド積立金 */
     ztymsyuptusshkgkaiykhnrikn                         DECIMAL     (11)                                                                ,  /* （中継用）未収Ｐ等差引後解約返戻金 */
     ztyrrthndugtnkgetumatuv                            DECIMAL     (11)                                                                ,  /* （中継用）利率変動型年金月末Ｖ */
     ztyrrthndnksaiteihosyonkgns                        DECIMAL     (11)                                                                ,  /* （中継用）利率変動年金最低保証年金原資 */
     ztyrrthendougatanksibous                           DECIMAL     (11)                                                                ,  /* （中継用）利率変動型年金死亡Ｓ */
     ztyalmyousohutomeisyoukbn                          VARCHAR     (2)                                                                 ,  /* （中継用）ＡＬＭ用ソフト名称区分 */
     ztysnkyksoftmeisyoukbn                             VARCHAR     (2)                                                                 ,  /* （中継用）新契約ソフト名称区分 */
     ztysoftmeisyoukbn                                  VARCHAR     (2)                                                                 ,  /* （中継用）ソフト名称区分 */
     ztykykjitokujyouarihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）契約時特条有表示 */
     ztybnkttnknkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）分割転換区分 */
     ztytenkanminaosikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）転換見直区分 */
     ztysoujikeitenkankbn                               VARCHAR     (1)                                                                 ,  /* （中継用）相似形転換区分 */
     ztynenkinkaisinendo                                VARCHAR     (4)                                                                 ,  /* （中継用）年金開始年度 */
     ztynenkingatakbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）年金型区分 */
     ztynknshry                                         VARCHAR     (2)                                                                 ,  /* （中継用）年金支払期間 */
     ztyheiyoubaraikeiyakukbn                           VARCHAR     (1)                                                                 ,  /* （中継用）併用払契約区分 */
     ztynenkinmaruteihukakbn                            VARCHAR     (1)                                                                 ,  /* （中継用）年金マル定付加区分 */
     ztysinseizonmrtiarihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）新生存マル定有表示 */
     ztysnkykyouibokijyukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）新契約用異募計上区分 */
     ztytokusitujyuusitusetkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）特疾重疾セット区分 */
     ztysiktsyuknbyugnhsyunshyj                         VARCHAR     (1)                                                                 ,  /* （中継用）生活習慣病がん保障無表示 */
     ztypmensugugtganhsyunshyj                          VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免総合型がん保障無表示 */
     ztytkykgyousekihyjszerohyj                         VARCHAR     (1)                                                                 ,  /* （中継用）特約業績表示Ｓゼロ表示 */
     ztysuuriyouyobin7                                  VARCHAR     (7)                                                                 ,  /* （中継用）数理用予備項目Ｎ７ */
     ztysyussaikeitaikbn                                VARCHAR     (2)                                                                 ,  /* （中継用）出再形態区分 */
     ztyyobiv6                                          VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６ */
     ztybosyuukeitaikbn                                 VARCHAR     (2)                                                                 ,  /* （中継用）募集形態区分 */
     ztyaatukaisosikicd                                 VARCHAR     (7)                                                                 ,  /* （中継用）Ａ扱者組織コード */
     ztyaatukaikojincd                                  VARCHAR     (6)                                                                 ,  /* （中継用）Ａ扱者個人コード */
     ztybsydrtencd                                      VARCHAR     (7)                                                                 ,  /* （中継用）募集代理店コード */
     ztycifcd                                           VARCHAR     (15)                                                                ,  /* （中継用）ＣＩＦコード */
     ztysuuriyouyobiv8                                  VARCHAR     (8)                                                                 ,  /* （中継用）数理用予備項目Ｖ８ */
     ztysinsakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）診査区分 */
     ztydai2hihokensyasinsakbn                          VARCHAR     (1)                                                                 ,  /* （中継用）第２被保険者診査区分 */
     ztytoukeiyousinsakbn                               VARCHAR     (2)                                                                 ,  /* （中継用）統計用診査区分 */
     ztydai2toukeiyousinsakbn                           VARCHAR     (2)                                                                 ,  /* （中継用）第２統計用診査区分 */
     ztyketteikijyunkanwakbn                            VARCHAR     (1)                                                                 ,  /* （中継用）決定基準緩和区分 */
     ztykihonsibouhyoukbn                               VARCHAR     (2)                                                                 ,  /* （中継用）基本死亡表区分 */
     ztyteikisibouhyoukbn                               VARCHAR     (2)                                                                 ,  /* （中継用）定期死亡表区分 */
     ztysonotasibouhyoukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）その他死亡表区分 */
     ztymrarihyj                                        VARCHAR     (1)                                                                 ,  /* （中継用）ＭＲ有表示 */
     ztysentakujyouhouarihyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）選択情報有表示 */
     ztydugktnknsntkhuhukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）同額転換選択方法区分 */
     ztygengakutenkankykhyj                             VARCHAR     (1)                                                                 ,  /* （中継用）減額転換契約表示 */
     ztysykgycd                                         VARCHAR     (3)                                                                 ,  /* （中継用）職業コード */
     ztyjidoukousinkykkanyuuymd                         VARCHAR     (8)                                                                 ,  /* （中継用）自動更新契約加入年月日 */
     ztysaikohtnknkykkykymd                             VARCHAR     (8)                                                                 ,  /* （中継用）最古被転換契約契約年月日 */
     ztykousinmaesykyksburtkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）更新前主契約死亡率区分 */
     ztyhjnkykhyj                                       VARCHAR     (1)                                                                 ,  /* （中継用）法人契約表示 */
     ztyanniskcd                                        VARCHAR     (8)                                                                 ,  /* （中継用）案内先コード */
     ztyhjncd                                           VARCHAR     (9)                                                                 ,  /* （中継用）法人コード */
     ztyhjnjigyosyocd                                   VARCHAR     (3)                                                                 ,  /* （中継用）法人事業所コード */
     ztysaihokenno                                      VARCHAR     (5)                                                                 ,  /* （中継用）再保険番号 */
     ztydakuhikettikekkacd                              VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定結果コード */
     ztydai2dakuhiketteikekkacd                         VARCHAR     (2)                                                                 ,  /* （中継用）第２諾否決定結果コード */
     ztypmenkbnv2                                       VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ免区分Ｖ２ */
     ztysiboukyuuhukin                                  DECIMAL     (11)                                                                ,  /* （中継用）死亡給付金 */
     ztyjyudthumeharaitkykhkhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）重度痴呆前払特約付加表示 */
     ztyhaitoukbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）配当区分 */
     ztyhhknnentysihyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）被保険者年令調整表示 */
     ztydai2hhknnentysihyj                              VARCHAR     (1)                                                                 ,  /* （中継用）第２被保険者年令調整表示 */
     ztykyksyaagetyouseihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）契約者年令調整表示 */
     ztykituenkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）喫煙区分 */
     ztykituenhonsuu                                    VARCHAR     (2)                                                                 ,  /* （中継用）喫煙本数 */
     ztymusentakukeiyakukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）無選択契約区分 */
     ztyyobiv6x2                                        VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６＿２ */
     ztylivingneedstkykarihyj                           VARCHAR     (1)                                                                 ,  /* （中継用）リビングニーズ特約有表示 */
     ztylivingneedssiharaihyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）リビングニーズ支払表示 */
     ztylnseikyuuymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）ＬＮ請求年月日 */
     ztylnshrgenincd                                    VARCHAR     (4)                                                                 ,  /* （中継用）ＬＮ支払原因コード */
     ztydakuhikettisyacd                                VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定者コード */
     ztydai2dakuhiketteisyacd                           VARCHAR     (2)                                                                 ,  /* （中継用）第２諾否決定者コード */
     ztygansapotokuyakuarihyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）がんサポ特約有表示 */
     ztygnspshrhyj                                      VARCHAR     (1)                                                                 ,  /* （中継用）がんサポ支払表示 */
     ztygansaposeikyuuymd                               VARCHAR     (8)                                                                 ,  /* （中継用）がんサポ請求年月日 */
     ztygnspshrgenincd                                  VARCHAR     (4)                                                                 ,  /* （中継用）がんサポ支払原因コード */
     ztyyobiv3x2                                        VARCHAR     (3)                                                                 ,  /* （中継用）予備項目Ｖ３＿２ */
     ztytargetmokuhyouritu                              VARCHAR     (3)                                                                 ,  /* （中継用）ターゲット目標率 */
     ztyautoswitchmokuhyouritu                          VARCHAR     (3)                                                                 ,  /* （中継用）オートスイッチ目標率 */
     ztytumitatekinitenarihyj                           VARCHAR     (1)                                                                 ,  /* （中継用）積立金移転有表示 */
     ztytumitatekinitenkaisuu                           VARCHAR     (3)                                                                 ,  /* （中継用）積立金移転回数 */
     ztydatakanrino2                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号２ */
     ztydatakanrino3                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号３ */
     ztyknkuzusnzyrttekinendo                           VARCHAR     (4)                                                                 ,  /* （中継用）健康増進乗率適用年度 */
     ztyknkuzusnzyrt                                    VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率 */
     ztyknkuzusnzyrtx2                                  VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率＿２ */
     ztyknkuzusnzyrtx3                                  VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率＿３ */
     ztysinkeiyakujiknkuzusnzyrt                        VARCHAR     (3)                                                                 ,  /* （中継用）新契約時健康増進乗率 */
     ztytenkanjiknkuzusnzyrt                            VARCHAR     (3)                                                                 ,  /* （中継用）転換時健康増進乗率 */
     ztysinkeiyakujivithkhyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztykykjivithukusuukykhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）契約時Ｖｉｔ複数契約表示 */
     ztysuuriyouyobin9x2                                VARCHAR     (9)                                                                 ,  /* （中継用）数理用予備項目Ｎ９＿２ */
     ztypwrbksidhitekiyouhyj                            VARCHAR     (1)                                                                 ,  /* （中継用）保険料割引制度非適用表示 */
     ztysuuriyouyobin9                                  VARCHAR     (9)                                                                 ,  /* （中継用）数理用予備項目Ｎ９ */
     ztysuuriyouyobin10x7                               VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿７ */
     ztysuuriyouyobin10x8                               VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿８ */
     ztysuuriyouyobin10x9                               VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿９ */
     ztytumitatekinitenbubun                            DECIMAL     (11)                                                                ,  /* （中継用）積立金移転部分 */
     ztysagakusknnjynbknzndk                            DECIMAL     (11)                                                                ,  /* （中継用）差額責任準備金残高 */
     ztyyobin11x5                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿５ */
     ztyyobin11x6                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿６ */
     ztyyobin11x7                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿７ */
     ztyyobin11x8                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿８ */
     ztyyobin11x9                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿９ */
     ztyyobin11x10                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１０ */
     ztyyobin11x11                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１１ */
     ztyyobin11x12                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１２ */
     ztyyobin11x13                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１３ */
     ztyyobin11x14                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１４ */
     ztyyobin11x15                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１５ */
     ztyyobin11x16                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１６ */
     ztyyobin11x17                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１７ */
     ztyzyrthntiyustatuskbn                             VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分 */
     ztyzyrthntiyustatuskbnx2                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿２ */
     ztyzyrthntiyustatuskbnx3                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿３ */
     ztyzyrthntiyustatuskbnx4                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿４ */
     ztyzyrthntiyustatuskbnx5                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿５ */
     ztyyobiv10                                         VARCHAR     (10)                                                                ,  /* （中継用）予備項目Ｖ１０ */
     ztyyobiv15x2                                       VARCHAR     (15)                                                                ,  /* （中継用）予備項目Ｖ１５＿２ */
     ztyyobiv15x3                                       VARCHAR     (15)                                                                ,  /* （中継用）予備項目Ｖ１５＿３ */
     ztyyobiv15x4                                       VARCHAR     (15)                                                                ,  /* （中継用）予備項目Ｖ１５＿４ */
     ztygaikakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）外貨区分 */
     ztykawaserate1                                     DECIMAL     (9,6)                                                               ,  /* （中継用）為替レート１ */
     ztykawaseratetekiyouymd1                           VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日１ */
     ztykawaserate2                                     DECIMAL     (9,6)                                                               ,  /* （中継用）為替レート２ */
     ztykawaseratetekiyouymd2                           VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日２ */
     ztykykjikawaserate                                 DECIMAL     (9,6)                                                               ,  /* （中継用）契約時為替レート */
     ztykykjikawaseratetkyuymd                          VARCHAR     (8)                                                                 ,  /* （中継用）契約時為替レート適用年月日 */
     ztymvatyouseigow                                   DECIMAL     (11)                                                                ,  /* （中継用）ＭＶＡ調整後Ｗ */
     ztymvakeisanjisknnjynbkn                           DECIMAL     (11)                                                                ,  /* （中継用）ＭＶＡ計算時責任準備金 */
     ztykaiyakukoujyoritu                               DECIMAL     (5,4)                                                               ,  /* （中継用）解約控除率 */
     ztyrendouritu                                      DECIMAL     (5,4)                                                               ,  /* （中継用）連動率 */
     ztysrkaiyakusjkkktyouseirrt                        DECIMAL     (5,4)                                                               ,  /* （中継用）数理用解約時市場価格調整用利率 */
     ztysrkyksjkkktyouseiriritu                         DECIMAL     (5,4)                                                               ,  /* （中継用）数理用契約時市場価格調整用利率 */
     ztymvakeisankijyunymd                              VARCHAR     (8)                                                                 ,  /* （中継用）ＭＶＡ計算基準年月日 */
     ztymvatyouseikou                                   DECIMAL     (5,4)                                                               ,  /* （中継用）ＭＶＡ調整項 */
     ztyenkdtsbujsitihsyukngk                           DECIMAL     (11)                                                                ,  /* （中継用）円貨建死亡時最低保証金額 */
     ztyenkdtsbujsitihsyucost                           DECIMAL     (11)                                                                ,  /* （中継用）円貨建死亡時最低保証コスト */
     ztyenkdtsbujsitihsyuarihyj                         VARCHAR     (1)                                                                 ,  /* （中継用）円貨建死亡時最低保証あり表示 */
     ztykeiyakujiyoteiriritu                            DECIMAL     (5,4)                                                               ,  /* （中継用）契約時予定利率 */
     ztytumitateriritu                                  DECIMAL     (5,4)                                                               ,  /* （中継用）積立利率 */
     ztykaigomaebaraitkykarihyj                         VARCHAR     (1)                                                                 ,  /* （中継用）介護前払特約あり表示 */
     ztysibouhyoukbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）死亡表区分 */
     ztynyuukintuukakbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）入金通貨区分 */
     ztysiharaituukakbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）支払通貨区分 */
     ztywyendttargetmokuhyouritu                        VARCHAR     (3)                                                                 ,  /* （中継用）円建Ｗターゲット目標率 */
     ztysisuurendourate                                 VARCHAR     (3)                                                                 ,  /* （中継用）指数連動部分割合 */
     ztysisuukbn                                        VARCHAR     (2)                                                                 ,  /* （中継用）指数区分 */
     ztyteirituikouhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）定率移行表示 */
     ztysuuriyouyobin2x3                                VARCHAR     (2)                                                                 ,  /* （中継用）数理用予備項目Ｎ２＿３ */
     ztysuuriyouyobin10x11                              VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿１１ */
     ztytmttknzoukaritujygn                             DECIMAL     (5,4)                                                               ,  /* （中継用）積立金増加率上限 */
     ztysetteibairitu                                   DECIMAL     (3,2)                                                               ,  /* （中継用）設定倍率 */
     ztytykzenoutouymdsisuu                             DECIMAL     (10,5)                                                              ,  /* （中継用）直前応当日指数 */
     ztykimatusisuu                                     DECIMAL     (10,5)                                                              ,  /* （中継用）期末指数 */
     ztyyobiv3                                          VARCHAR     (3)                                                                 ,  /* （中継用）予備項目Ｖ３ */
     ztyyenkadatekihons                                 DECIMAL     (11)                                                                ,  /* （中継用）円貨建基本Ｓ */
     ztysitihsyumegkdtsibous                            DECIMAL     (11)                                                                ,  /* （中継用）最低保証前外貨建死亡Ｓ */
     ztyenkdtssrentumitatekin                           DECIMAL     (11)                                                                ,  /* （中継用）円貨建指数連動部分積立金 */
     ztysisuurentumitatekin                             DECIMAL     (11)                                                                ,  /* （中継用）指数連動部分積立金 */
     ztynksjitirttumitatekin                            DECIMAL     (11)                                                                ,  /* （中継用）年金開始時定率部分積立金 */
     ztykimatutirttumitatekin                           DECIMAL     (11)                                                                ,  /* （中継用）期末定率部分積立金 */
     ztygaikadatejyuutoup                               DECIMAL     (11)                                                                ,  /* （中継用）外貨建充当Ｐ */
     ztyyendttargetkijyunkingaku                        DECIMAL     (11)                                                                ,  /* （中継用）円建ターゲット基準金額 */
     ztyyobiv7                                          VARCHAR     (7)                                                                 ,  /* （中継用）予備項目Ｖ７ */
     ztysitivkisnyukykjikwsrate                         DECIMAL     (9,6)                                                               ,  /* （中継用）最低Ｖ計算用契約時為替レート */
     ztysisuurentyokugotmttkn                           DECIMAL     (11)                                                                ,  /* （中継用）指数連動部分直後積立金 */
     ztyyoteiririturironbase                            DECIMAL     (5,4)                                                               ,  /* （中継用）予定利率（理論ベース） */
     ztyyoteiriritujtnyknbase                           DECIMAL     (5,4)                                                               ,  /* （中継用）予定利率（実入金ベース） */
     ztykihrkmpjtnyknbase                               DECIMAL     (11)                                                                ,  /* （中継用）既払込Ｐ（実入金ベース） */
     ztysyuptumitatekin                                 DECIMAL     (11)                                                                ,  /* （中継用）主契約保険料積立金 */
     ztysyuptumitatekingsc                              DECIMAL     (11)                                                                ,  /* （中継用）主契約保険料積立金（月初） */
     ztygaikadatenkgns                                  DECIMAL     (11)                                                                ,  /* （中継用）外貨建年金原資 */
     ztyjikaipjyuutouym2                                VARCHAR     (6)                                                                 ,  /* （中継用）次回Ｐ充当年月２ */
     ztysuuriyobin9                                     DECIMAL     (9)                                                                 ,  /* （中継用）数理予備項目Ｎ９ */
     ztygessitumitatekin                                DECIMAL     (11)                                                                ,  /* （中継用）月始積立金 */
     ztygaikadatetougetujuutoup                         DECIMAL     (11)                                                                ,  /* （中継用）外貨建当月充当Ｐ */
     ztykihrkmpmsukisymbase                             DECIMAL     (11)                                                                ,  /* （中継用）既払込Ｐ（未収開始月ベース） */
     ztykeisanhanteiyoutmttkn                           DECIMAL     (11)                                                                ,  /* （中継用）計算判定用積立金 */
     ztygtmtv                                           DECIMAL     (11)                                                                ,  /* （中継用）月末Ｖ */
     ztyzettaisibouritu                                 DECIMAL     (13,11)                                                             ,  /* （中継用）絶対死亡率 */
     ztysoutaisibouritu                                 DECIMAL     (13,11)                                                             ,  /* （中継用）相対死亡率 */
     ztysoutaikaiyakuritu                               DECIMAL     (13,11)                                                             ,  /* （中継用）相対解約率 */
     ztyvhireilritu2                                    DECIMAL     (13,11)                                                             ,  /* （中継用）Ｖ比例Ｌ率２ */
     ztyphireialpha                                     DECIMAL     (13,11)                                                             ,  /* （中継用）Ｐ比例α */
     ztyphireibeta                                      DECIMAL     (13,11)                                                             ,  /* （中継用）Ｐ比例β */
     ztyphireiganma                                     DECIMAL     (13,11)                                                             ,  /* （中継用）Ｐ比例γ */
     ztyphireilwrbkritu                                 DECIMAL     (13,11)                                                             ,  /* （中継用）Ｐ比例Ｌ割引率 */
     ztyyoteiriritumsukisymbase                         DECIMAL     (5,4)                                                               ,  /* （中継用）予定利率（未収開始月ベース） */
     ztyrrthnduhknvkisovkisnyu1                         DECIMAL     (11)                                                                ,  /* （中継用）利率変動保険Ｖ基礎Ｖ計算用１ */
     ztyrrthnduhknvkisovkisnyu2                         DECIMAL     (11)                                                                ,  /* （中継用）利率変動保険Ｖ基礎Ｖ計算用２ */
     ztyrrthnduhknvkisovkisnyu3                         DECIMAL     (11)                                                                ,  /* （中継用）利率変動保険Ｖ基礎Ｖ計算用３ */
     ztyrrthnduhknvkisovkisnyu4                         DECIMAL     (11)                                                                ,  /* （中継用）利率変動保険Ｖ基礎Ｖ計算用４ */
     ztyrrthnduhknvkiso                                 DECIMAL     (11)                                                                ,  /* （中継用）利率変動保険Ｖ基礎Ｖ */
     ztytumitatekin                                     DECIMAL     (11)                                                                ,  /* （中継用）積立金 */
     ztykiharaikomip                                    DECIMAL     (11)                                                                ,  /* （中継用）既払込Ｐ */
     ztygaikadatesyukeiyakup                            DECIMAL     (11)                                                                ,  /* （中継用）外貨建主契約Ｐ */
     ztykykkjmmvatyouseigow                             DECIMAL     (11)                                                                ,  /* （中継用）解約控除前ＭＶＡ調整後Ｗ */
     ztyyobin11x39                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿３９ */
     ztyyobin11x41                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４１ */
     ztyyobin11x42                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４２ */
     ztyyobin11x43                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４３ */
     ztyyobin11x44                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４４ */
     ztyyobin11x45                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４５ */
     ztysuuriyouyobin15x3                               VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５＿３ */
     ztysuuriyouyobin15x4                               VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５＿４ */
     ztysuuriyouyobin15x5                               VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５＿５ */
     ztysuuriyouyobin15x6                               VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５＿６ */
     ztyyobiv14                                         VARCHAR     (14)                                                                ,  /* （中継用）予備項目Ｖ１４ */
     ztyvkimatutirttumitatekin                          DECIMAL     (11)                                                                ,  /* （中継用）Ｖ用期末定率部分積立金 */
     ztykimatusisuutumitatekin                          DECIMAL     (11)                                                                ,  /* （中継用）期末指数部分積立金 */
     ztyvyoutykzenoutouymdsisuu                         DECIMAL     (10,5)                                                              ,  /* （中継用）Ｖ用直前応当日指数 */
     ztytykzensisuukijyunymd                            VARCHAR     (8)                                                                 ,  /* （中継用）直前指数基準年月日 */
     ztyvyoukimatusisuu                                 DECIMAL     (10,5)                                                              ,  /* （中継用）Ｖ用期末指数 */
     ztykmtsisuukijyunymd                               VARCHAR     (8)                                                                 ,  /* （中継用）期末指数基準年月日 */
     ztyvyoutmttknzoukaritujygn                         DECIMAL     (5,4)                                                               ,  /* （中継用）Ｖ用積立金増加率上限 */
     ztyvyousetteibairitu                               DECIMAL     (3,2)                                                               ,  /* （中継用）Ｖ用設定倍率 */
     ztyvyourendouritu                                  DECIMAL     (5,4)                                                               ,  /* （中継用）Ｖ用連動率 */
     ztysuuriyouyobin3x2                                VARCHAR     (3)                                                                 ,  /* （中継用）数理用予備項目Ｎ３＿２ */
     ztyyobiv8x2                                        VARCHAR     (8)                                                                 ,  /* （中継用）予備項目Ｖ８＿２ */
     ztykimatusisuutyokugotmttkn                        DECIMAL     (11)                                                                ,  /* （中継用）期末指数部分直後積立金 */
     ztyyobin11x19                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿１９ */
     ztyyobin11x20                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２０ */
     ztyjmttirttumitatekinnplus0                        DECIMAL     (11)                                                                ,  /* （中継用）事末定率部分積立金（Ｎ＋０） */
     ztyjmttirttumitatekinnplus1                        DECIMAL     (11)                                                                ,  /* （中継用）事末定率部分積立金（Ｎ＋１） */
     ztyjmttirttumitatekinnplus2                        DECIMAL     (11)                                                                ,  /* （中継用）事末定率部分積立金（Ｎ＋２） */
     ztyjmtssutumitatekinnplus0                         DECIMAL     (11)                                                                ,  /* （中継用）事末指数部分積立金（Ｎ＋０） */
     ztyjmtssutumitatekinnplus1                         DECIMAL     (11)                                                                ,  /* （中継用）事末指数部分積立金（Ｎ＋１） */
     ztyjmtssutumitatekinnplus2                         DECIMAL     (11)                                                                ,  /* （中継用）事末指数部分積立金（Ｎ＋２） */
     ztyjmtmvatyouseigownplus0                          DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ調整後Ｗ（Ｎ＋０） */
     ztyjmtmvakeisanjiwnplus0                           DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ計算時Ｖ（Ｎ＋０） */
     ztyjmtmvatyouseigownplus1                          DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ調整後Ｗ（Ｎ＋１） */
     ztyjmtmvakeisanjiwnplus1                           DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ計算時Ｖ（Ｎ＋１） */
     ztyjmtmvatyouseigownplus2                          DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ調整後Ｗ（Ｎ＋２） */
     ztyjmtmvakeisanjiwnplus2                           DECIMAL     (11)                                                                ,  /* （中継用）事末ＭＶＡ計算時Ｖ（Ｎ＋２） */
     ztyyobin11x21                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２１ */
     ztyyobin11x22                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２２ */
     ztyyobin11x23                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２３ */
     ztyyobin11x4                                       DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４ */
     ztyyobin11x25                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２５ */
     ztyyobin11x26                                      DECIMAL     (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２６ */
     ztysuuriyouyobin15                                 VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５ */
     ztysuuriyouyobin15x2                               VARCHAR     (15)                                                                ,  /* （中継用）数理用予備項目Ｎ１５＿２ */
     ztyyobiv15                                         VARCHAR     (15)                                                                ,  /* （中継用）予備項目Ｖ１５ */
     ztyyobiv20                                         VARCHAR     (20)                                                                ,  /* （中継用）予備項目Ｖ２０ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                                /* バージョン */
)
;

ALTER TABLE ZT_KbkSsuRnduHknKimatuVTy_Z ADD CONSTRAINT PK_KbkSsuRnduHknKimatuVTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
