CREATE TABLE ZT_SaihakkouHokensyoukenRn_Z (
     zrnsyoruicd                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）書類コード */
     zrntyouhyouymd                                     CHAR        (8)                                                       NOT NULL  ,  /* （連携用）帳票作成日 */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnhassoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）発送区分 */
     zrnkanryoutuutidouhuukbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）完了通知同封区分 */
     zrnsikibetuno                                      CHAR        (20)                                                      NOT NULL  ,  /* （連携用）識別番号 */
     zrnstdrsktirasidouhuukbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）指定代理請求チラシ同封区分 */
     zrnaisyoumeikbn                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）愛称名区分 */
     zrnsagyoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）作業区分 */
     zrnyakkanbunsyono                                  CHAR        (16)                                                      NOT NULL  ,  /* （連携用）約款文書番号 */
     zrnyobiv23x2                                       CHAR        (23)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２３＿２ */
     zrnhyoujiranhidarimsgcd1                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１ */
     zrnhyoujiranhidarimsgcd2                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード２ */
     zrnhyoujiranhidarimsgcd3                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード３ */
     zrnhyoujiranhidarimsgcd4                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード４ */
     zrnhyoujiranhidarimsgcd5                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード５ */
     zrnhyoujiranhidarimsgcd6                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード６ */
     zrnhyoujiranhidarimsgcd7                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード７ */
     zrnhyoujiranhidarimsgcd8                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード８ */
     zrnhyoujiranhidarimsgcd9                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード９ */
     zrnhyoujiranhidarimsgcd10                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１０ */
     zrnhyoujiranhidarimsgcd11                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１１ */
     zrnhyoujiranhidarimsgcd12                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１２ */
     zrnhyoujiranhidarimsgcd13                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１３ */
     zrnhyoujiranhidarimsgcd14                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１４ */
     zrnhyoujiranhidarimsgcd15                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１５ */
     zrnhyoujiranhidarimsgcd16                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１６ */
     zrnhyoujiranhidarimsgcd17                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１７ */
     zrnhyoujiranhidarimsgcd18                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１８ */
     zrnhyoujiranhidarimsgcd19                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード１９ */
     zrnhyoujiranhidarimsgcd20                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄左メッセージコード２０ */
     zrnhyoujiranmigimsgcd1                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１ */
     zrnhyoujiranmigimsgcd2                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード２ */
     zrnhyoujiranmigimsgcd3                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード３ */
     zrnhyoujiranmigimsgcd4                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード４ */
     zrnhyoujiranmigimsgcd5                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード５ */
     zrnhyoujiranmigimsgcd6                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード６ */
     zrnhyoujiranmigimsgcd7                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード７ */
     zrnhyoujiranmigimsgcd8                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード８ */
     zrnhyoujiranmigimsgcd9                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード９ */
     zrnhyoujiranmigimsgcd10                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１０ */
     zrnhyoujiranmigimsgcd11                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１１ */
     zrnhyoujiranmigimsgcd12                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１２ */
     zrnhyoujiranmigimsgcd13                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１３ */
     zrnhyoujiranmigimsgcd14                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１４ */
     zrnhyoujiranmigimsgcd15                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１５ */
     zrnhyoujiranmigimsgcd16                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１６ */
     zrnhyoujiranmigimsgcd17                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１７ */
     zrnhyoujiranmigimsgcd18                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１８ */
     zrnhyoujiranmigimsgcd19                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード１９ */
     zrnhyoujiranmigimsgcd20                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）表示欄右メッセージコード２０ */
     zrnsknnkaisiymdseireki                             GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）責任開始日（西暦） */
     zrnhyoujiranytirrt                                 GRAPHIC     (5)                                                       NOT NULL  ,  /* （連携用）表示欄予定利率 */
     zrnhyoujiransjkkktusirrt                           GRAPHIC     (5)                                                       NOT NULL  ,  /* （連携用）表示欄市場価格調整用利率 */
     zrnhyoujirantumitateriritu                         GRAPHIC     (4)                                                       NOT NULL  ,  /* （連携用）表示欄積立利率 */
     zrnhyoujirantmttknzkrtjygn                         GRAPHIC     (5)                                                       NOT NULL  ,  /* （連携用）表示欄積立金増加率の上限 */
     zrnhyoujiransetteibairitu                          GRAPHIC     (4)                                                       NOT NULL  ,  /* （連携用）表示欄設定倍率 */
     zrnyobiv30x2                                       CHAR        (30)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ３０＿２ */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnsyoukenhakkouymd                                GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）証券発行年月日 */
     zrnkouryokukaisimsg                                GRAPHIC     (40)                                                      NOT NULL  ,  /* （連携用）効力開始メッセージ */
     zrnseisikihknnmsyouken                             GRAPHIC     (40)                                                      NOT NULL  ,  /* （連携用）正式保険名称（証券） */
     zrnnksyuruinmsyouken                               GRAPHIC     (40)                                                      NOT NULL  ,  /* （連携用）年金種類名称（証券用） */
     zrnyobiv116                                        CHAR        (116)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ１１６ */
     zrnkyknmkj                                         GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）契約者名（漢字） */
     zrnhhknnmkj                                        GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）被保険者名（漢字） */
     zrnhihknsyaseiymdwareki                            GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）被保険者生年月日（和暦） */
     zrnhhknsei                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別 */
     zrnhhknnen2                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年齢Ｃ２ */
     zrnuktmidasikbn1                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分１ */
     zrnuktkbn1                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分１ */
     zrnuktnm1                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名１ */
     zrnuktbnwari1                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合１ */
     zrnuktmidasikbn2                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分２ */
     zrnuktkbn2                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分２ */
     zrnuktnm2                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名２ */
     zrnuktbnwari2                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合２ */
     zrnuktmidasikbn3                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分３ */
     zrnuktkbn3                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分３ */
     zrnuktnm3                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名３ */
     zrnuktbnwari3                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合３ */
     zrnuktmidasikbn4                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分４ */
     zrnuktkbn4                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分４ */
     zrnuktnm4                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名４ */
     zrnuktbnwari4                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合４ */
     zrnuktmidasikbn5                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分５ */
     zrnuktkbn5                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分５ */
     zrnuktnm5                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名５ */
     zrnuktbnwari5                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合５ */
     zrnuktmidasikbn6                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分６ */
     zrnuktkbn6                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分６ */
     zrnuktnm6                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名６ */
     zrnuktbnwari6                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合６ */
     zrnuktmidasikbn7                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分７ */
     zrnuktkbn7                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分７ */
     zrnuktnm7                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名７ */
     zrnuktbnwari7                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合７ */
     zrnuktmidasikbn8                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分８ */
     zrnuktkbn8                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分８ */
     zrnuktnm8                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名８ */
     zrnuktbnwari8                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合８ */
     zrnuktmidasikbn9                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分９ */
     zrnuktkbn9                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分９ */
     zrnuktnm9                                          GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名９ */
     zrnuktbnwari9                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合９ */
     zrnuktmidasikbn10                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人見出し区分１０ */
     zrnuktkbn10                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）受取人区分１０ */
     zrnuktnm10                                         GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）受取人名１０ */
     zrnuktbnwari10                                     CHAR        (3)                                                       NOT NULL  ,  /* （連携用）受取人分割割合１０ */
     zrnyobiv45                                         CHAR        (45)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ４５ */
     zrnpmsgcd1                                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）保険料メッセージコード１ */
     zrnpmsgcd2                                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）保険料メッセージコード２ */
     zrnpmsgcd3                                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）保険料メッセージコード３ */
     zrnyobiv10                                         CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０ */
     zrnptuukatype                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）保険料金額通貨タイプ */
     zrnteikiikkatubaraitukisuu                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）定期一括払月数 */
     zrnztikiktbriyhrkgktuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）前納定期一括払円貨払込額通貨タイプ */
     zrnznntikiktbriyenhrkgk                            CHAR        (13)                                                      NOT NULL  ,  /* （連携用）前納定期一括払円貨払込額 */
     zrnznnkai                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）前納回数 */
     zrnpkngk                                           CHAR        (13)                                                      NOT NULL  ,  /* （連携用）保険料金額 */
     zrnpkngktuuka                                      GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）保険料金額通貨 */
     zrnptokuyakumsgcd                                  CHAR        (5)                                                       NOT NULL  ,  /* （連携用）保険料特約メッセージコード */
     zrnyobiv48                                         CHAR        (48)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ４８ */
     zrnkykymdseireki                                   GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）契約年月日（西暦） */
     zrnphrkkknmidasikbn                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険料払込期間見出し区分 */
     zrnhrkkknmsgkbn                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払込期間メッセージ区分 */
     zrnhrkkaisuumsgkbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払込回数メッセージ区分 */
     zrnphrkktuki                                       GRAPHIC     (15)                                                      NOT NULL  ,  /* （連携用）保険料払込期月 */
     zrnhrkhouhoumsgkbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払込方法メッセージ区分 */
     zrnyobiv18                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１８ */
     zrnsyukyktkykrenban1                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番１ */
     zrnsyukyktkykmsgkbn1                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分１ */
     zrnsyukyktkyksmsgkbn1                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分１ */
     zrnsyukyktkykhknkknmsgkbn1                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分１ */
     zrnsyukyktkykstuukatype1                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ１ */
     zrnsyukyktkykhknkngk1                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額１ */
     zrnsyutkdai1hknkknymdto1                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）１ */
     zrnsyutkdai2hknkknymdto1                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）１ */
     zrnyobiv22                                         CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２ */
     zrnsyukyktkykrenban2                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番２ */
     zrnsyukyktkykmsgkbn2                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分２ */
     zrnsyukyktkyksmsgkbn2                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分２ */
     zrnsyukyktkykhknkknmsgkbn2                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分２ */
     zrnsyukyktkykstuukatype2                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ２ */
     zrnsyukyktkykhknkngk2                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額２ */
     zrnsyutkdai1hknkknymdto2                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）２ */
     zrnsyutkdai2hknkknymdto2                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）２ */
     zrnyobiv22x2                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿２ */
     zrnsyukyktkykrenban3                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番３ */
     zrnsyukyktkykmsgkbn3                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分３ */
     zrnsyukyktkyksmsgkbn3                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分３ */
     zrnsyukyktkykhknkknmsgkbn3                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分３ */
     zrnsyukyktkykstuukatype3                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ３ */
     zrnsyukyktkykhknkngk3                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額３ */
     zrnsyutkdai1hknkknymdto3                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）３ */
     zrnsyutkdai2hknkknymdto3                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）３ */
     zrnyobiv22x3                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿３ */
     zrnsyukyktkykrenban4                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番４ */
     zrnsyukyktkykmsgkbn4                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分４ */
     zrnsyukyktkyksmsgkbn4                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分４ */
     zrnsyukyktkykhknkknmsgkbn4                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分４ */
     zrnsyukyktkykstuukatype4                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ４ */
     zrnsyukyktkykhknkngk4                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額４ */
     zrnsyutkdai1hknkknymdto4                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）４ */
     zrnsyutkdai2hknkknymdto4                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）４ */
     zrnyobiv22x4                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿４ */
     zrnsyukyktkykrenban5                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番５ */
     zrnsyukyktkykmsgkbn5                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分５ */
     zrnsyukyktkyksmsgkbn5                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分５ */
     zrnsyukyktkykhknkknmsgkbn5                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分５ */
     zrnsyukyktkykstuukatype5                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ５ */
     zrnsyukyktkykhknkngk5                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額５ */
     zrnsyutkdai1hknkknymdto5                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）５ */
     zrnsyutkdai2hknkknymdto5                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）５ */
     zrnyobiv22x5                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿５ */
     zrnsyukyktkykrenban6                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番６ */
     zrnsyukyktkykmsgkbn6                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分６ */
     zrnsyukyktkyksmsgkbn6                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分６ */
     zrnsyukyktkykhknkknmsgkbn6                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分６ */
     zrnsyukyktkykstuukatype6                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ６ */
     zrnsyukyktkykhknkngk6                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額６ */
     zrnsyutkdai1hknkknymdto6                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）６ */
     zrnsyutkdai2hknkknymdto6                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）６ */
     zrnyobiv22x6                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿６ */
     zrnsyukyktkykrenban7                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番７ */
     zrnsyukyktkykmsgkbn7                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分７ */
     zrnsyukyktkyksmsgkbn7                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分７ */
     zrnsyukyktkykhknkknmsgkbn7                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分７ */
     zrnsyukyktkykstuukatype7                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ７ */
     zrnsyukyktkykhknkngk7                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額７ */
     zrnsyutkdai1hknkknymdto7                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）７ */
     zrnsyutkdai2hknkknymdto7                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）７ */
     zrnyobiv22x7                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿７ */
     zrnsyukyktkykrenban8                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番８ */
     zrnsyukyktkykmsgkbn8                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分８ */
     zrnsyukyktkyksmsgkbn8                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分８ */
     zrnsyukyktkykhknkknmsgkbn8                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分８ */
     zrnsyukyktkykstuukatype8                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ８ */
     zrnsyukyktkykhknkngk8                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額８ */
     zrnsyutkdai1hknkknymdto8                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）８ */
     zrnsyutkdai2hknkknymdto8                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）８ */
     zrnyobiv22x8                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿８ */
     zrnsyukyktkykrenban9                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番９ */
     zrnsyukyktkykmsgkbn9                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分９ */
     zrnsyukyktkyksmsgkbn9                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分９ */
     zrnsyukyktkykhknkknmsgkbn9                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分９ */
     zrnsyukyktkykstuukatype9                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ９ */
     zrnsyukyktkykhknkngk9                              CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額９ */
     zrnsyutkdai1hknkknymdto9                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）９ */
     zrnsyutkdai2hknkknymdto9                           GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）９ */
     zrnyobiv22x9                                       CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿９ */
     zrnsyukyktkykrenban10                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約連番１０ */
     zrnsyukyktkykmsgkbn10                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約メッセージ区分１０ */
     zrnsyukyktkyksmsgkbn10                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額メッセージ区分１０ */
     zrnsyukyktkykhknkknmsgkbn10                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約特約保険期間メッセージ区分１０ */
     zrnsyukyktkykstuukatype10                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）主契約特約保険金額通貨タイプ１０ */
     zrnsyukyktkykhknkngk10                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）主契約特約保険金額１０ */
     zrnsyutkdai1hknkknymdto10                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第１保険期間年月日（至）１０ */
     zrnsyutkdai2hknkknymdto10                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）主契約特約第２保険期間年月日（至）１０ */
     zrnyobiv22x10                                      CHAR        (22)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２２＿１０ */
     zrnyobiv50                                         CHAR        (50)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ５０ */
     zrnkykniyustmsgcd1                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１ */
     zrnkykniyustmsgcd2                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード２ */
     zrnkykniyustmsgcd3                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード３ */
     zrnkykniyustmsgcd4                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード４ */
     zrnkykniyustmsgcd5                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード５ */
     zrnkykniyustmsgcd6                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード６ */
     zrnkykniyustmsgcd7                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード７ */
     zrnkykniyustmsgcd8                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード８ */
     zrnkykniyustmsgcd9                                 CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード９ */
     zrnkykniyustmsgcd10                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１０ */
     zrnkykniyustmsgcd11                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１１ */
     zrnkykniyustmsgcd12                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１２ */
     zrnkykniyustmsgcd13                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１３ */
     zrnkykniyustmsgcd14                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１４ */
     zrnkykniyustmsgcd15                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）契約内容欄下メッセージコード１５ */
     zrnkykniyustitjbrptuuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）契約内容欄下一時払保険料通貨タイプ */
     zrnkykniyustitjbrp                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）契約内容欄下一時払保険料 */
     zrnyobiv49                                         CHAR        (49)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ４９ */
     zrnsonotanyranmsgcd1                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１ */
     zrnsonotanyranmsgcd2                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード２ */
     zrnsonotanyranmsgcd3                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード３ */
     zrnsonotanyranmsgcd4                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード４ */
     zrnsonotanyranmsgcd5                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード５ */
     zrnsonotanyranmsgcd6                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード６ */
     zrnsonotanyranmsgcd7                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード７ */
     zrnsonotanyranmsgcd8                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード８ */
     zrnsonotanyranmsgcd9                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード９ */
     zrnsonotanyranmsgcd10                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１０ */
     zrnsonotanyranmsgcd11                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１１ */
     zrnsonotanyranmsgcd12                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１２ */
     zrnsonotanyranmsgcd13                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１３ */
     zrnsonotanyranmsgcd14                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１４ */
     zrnsonotanyranmsgcd15                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１５ */
     zrnsonotanyranmsgcd16                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１６ */
     zrnsonotanyranmsgcd17                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１７ */
     zrnsonotanyranmsgcd18                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１８ */
     zrnsonotanyranmsgcd19                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード１９ */
     zrnsonotanyranmsgcd20                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄メッセージコード２０ */
     zrnsonotanyransiteituuka                           GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄指定通貨 */
     zrnsonotanyrannykntuktype                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄入金通貨タイプ */
     zrnsonotanyrannykntuukap                           CHAR        (13)                                                      NOT NULL  ,  /* （連携用）その他内容欄入金通貨保険料 */
     zrnsonotanyrannykntuukasyu                         GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄入金通貨種類 */
     zrnsonotanyranenkhrikmrate                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄円貨払込特約レート */
     zrnsonotanyranstigikwsrate                         CHAR        (7)                                                       NOT NULL  ,  /* （連携用）その他内容欄指定外通貨払込特約レート */
     zrnsonotanykjnkngktuktype                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄基準金額通貨タイプ */
     zrnsonotanykjnkngk                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）その他内容欄基準金額 */
     zrnsonotanykjnkngkrate                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄基準金額換算レート */
     zrnsonotanykjnkngktuuka                            GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄基準金額通貨 */
     zrnsonotanyranpentuktype                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄保険料円換算通貨タイプ */
     zrnsonotanyranpenknsngk                            CHAR        (13)                                                      NOT NULL  ,  /* （連携用）その他内容欄保険料円換算額 */
     zrnpmkhtoutatuwariai                               GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄目標到達割合 */
     zrnsonotanyrannkshrstartymd                        GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）その他内容欄年金支払開始日 */
     zrnsonotanyrannkkkn                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）その他内容欄年金期間 */
     zrnsonotanyyensysnhkhnkymd                         GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）その他内容欄円建終身保険変更日 */
     zrnsonotanytmttkngktuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）その他内容欄積立金額通貨タイプ */
     zrnsonotanyteiritutmttkngk                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）その他内容欄定率積立金額 */
     zrnsonotanyransisuutmttkngk                        CHAR        (13)                                                      NOT NULL  ,  /* （連携用）その他内容欄指数積立金額 */
     zrnsonotanyransisuunm                              GRAPHIC     (50)                                                      NOT NULL  ,  /* （連携用）その他内容欄指数名 */
     zrnsonotanyrangaimsgcd                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）その他内容欄外メッセージコード */
     zrnyobiv19                                         CHAR        (19)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１９ */
     zrnhosyounymsgcd                                   CHAR        (5)                                                       NOT NULL  ,  /* （連携用）保障内容メッセージコード */
     zrnyobiv15                                         CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５ */
     zrnhosyounyhihknsyanmkanji                         GRAPHIC     (18)                                                      NOT NULL  ,  /* （連携用）保障内容被保険者名（漢字） */
     zrnyobiv24                                         CHAR        (24)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２４ */
     zrnsiboumidasimsgcd                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障見出しメッセージコード */
     zrnsiboumidasimsgcd2                               CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障見出しメッセージコード２ */
     zrnsiboudai1hknkknmsgcd1                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間メッセージコード１ */
     zrnsiboudai1hknkknmsgcd2                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間メッセージコード２ */
     zrnsiboudai1hknkknigimsgcd                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間不慮の事故以外Ｓ表メッセージコード */
     zrnsiboudai1hknkknigimsgcd2                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間不慮の事故以外Ｓ表メッセージコード２ */
     zrnsiboudai1hknkknhrsmsgcd                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間不慮の事故Ｓ表メッセージコード */
     zrnsiboudai1hknkknhrsmsgcd2                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間不慮の事故Ｓ表メッセージコード２ */
     zrnsiboudai1hknkknsmrmsgcd                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第１保険期間Ｓ表丸印メッセージコード */
     zrnsiboudai2hknkknmsgcd1                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第２保険期間メッセージコード１ */
     zrnsiboudai2hknkknmsgcd2                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第２保険期間メッセージコード２ */
     zrnsiboudai2hknkknsmsgcd                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第２保険期間Ｓ表メッセージコード */
     zrnsiboudai2hknkknsmsgcd2                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第２保険期間Ｓ表メッセージコード２ */
     zrnsiboudai3hknkknmsgcd1                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第３保険期間メッセージコード１ */
     zrnsiboudai3hknkknmsgcd2                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡保障第３保険期間メッセージコード２ */
     zrnyobiv15x2                                       CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５＿２ */
     zrnsiboudai1hknkknymdto                            GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）死亡保障第１保険期間年月日（至） */
     zrnsibouitjbrpyentuuktype                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）死亡保障一時払保険料相当円換算額通貨タイプ */
     zrnsibouitjbrpyentuukgk                            CHAR        (13)                                                      NOT NULL  ,  /* （連携用）死亡保障一時払保険料相当円換算額 */
     zrnsiboudai1kjnkngktuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）死亡保障第１基準金額通貨タイプ */
     zrnsiboudai1kjnkngk                                CHAR        (13)                                                      NOT NULL  ,  /* （連携用）死亡保障第１基準金額 */
     zrnsiboudai2hknkknymdto                            GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）死亡保障第２保険期間年月日（至） */
     zrnsiboudai2kjnkngktuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）死亡保障第２基準金額通貨タイプ */
     zrnsiboudai2kjnkngk                                CHAR        (13)                                                      NOT NULL  ,  /* （連携用）死亡保障第２基準金額 */
     zrnsiboudai3kjnkngktuktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）死亡保障第３基準金額通貨タイプ */
     zrnsiboudai3kjnkngk                                CHAR        (13)                                                      NOT NULL  ,  /* （連携用）死亡保障第３基準金額 */
     zrnyobiv23                                         CHAR        (23)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２３ */
     zrndai1skwsrateyendaka                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額為替レート（円高） */
     zrndai1skwsrateyenkijyun                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額為替レート（中央値） */
     zrndai1skwsrateyenyasu                             CHAR        (5)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額為替レート（円安） */
     zrndai1sibousnenoutouymd1                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０１ */
     zrndai1stuuktype01                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０１ */
     zrndai1s01                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０１ */
     zrndai1syenyendakaumu01                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０１ */
     zrndai1syenyenkijyunumu01                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０１ */
     zrndai1syenyenyasuumu01                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０１ */
     zrndai1syentuuktype01                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０１ */
     zrndai1syenyendaka01                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０１ */
     zrndai1syenyenkijyun01                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０１ */
     zrndai1syenyenyasu01                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０１ */
     zrndai1sibousnenoutouymd2                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０２ */
     zrndai1stuuktype02                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０２ */
     zrndai1s02                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０２ */
     zrndai1syenyendakaumu02                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０２ */
     zrndai1syenyenkijyunumu02                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０２ */
     zrndai1syenyenyasuumu02                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０２ */
     zrndai1syentuuktype02                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０２ */
     zrndai1syenyendaka02                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０２ */
     zrndai1syenyenkijyun02                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０２ */
     zrndai1syenyenyasu02                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０２ */
     zrndai1sibousnenoutouymd3                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０３ */
     zrndai1stuuktype03                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０３ */
     zrndai1s03                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０３ */
     zrndai1syenyendakaumu03                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０３ */
     zrndai1syenyenkijyunumu03                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０３ */
     zrndai1syenyenyasuumu03                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０３ */
     zrndai1syentuuktype03                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０３ */
     zrndai1syenyendaka03                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０３ */
     zrndai1syenyenkijyun03                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０３ */
     zrndai1syenyenyasu03                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０３ */
     zrndai1sibousnenoutouymd4                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０４ */
     zrndai1stuuktype04                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０４ */
     zrndai1s04                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０４ */
     zrndai1syenyendakaumu04                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０４ */
     zrndai1syenyenkijyunumu04                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０４ */
     zrndai1syenyenyasuumu04                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０４ */
     zrndai1syentuuktype04                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０４ */
     zrndai1syenyendaka04                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０４ */
     zrndai1syenyenkijyun04                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０４ */
     zrndai1syenyenyasu04                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０４ */
     zrndai1sibousnenoutouymd5                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０５ */
     zrndai1stuuktype05                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０５ */
     zrndai1s05                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０５ */
     zrndai1syenyendakaumu05                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０５ */
     zrndai1syenyenkijyunumu05                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０５ */
     zrndai1syenyenyasuumu05                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０５ */
     zrndai1syentuuktype05                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０５ */
     zrndai1syenyendaka05                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０５ */
     zrndai1syenyenkijyun05                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０５ */
     zrndai1syenyenyasu05                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０５ */
     zrndai1sibousnenoutouymd6                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０６ */
     zrndai1stuuktype06                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０６ */
     zrndai1s06                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０６ */
     zrndai1syenyendakaumu06                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０６ */
     zrndai1syenyenkijyunumu06                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０６ */
     zrndai1syenyenyasuumu06                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０６ */
     zrndai1syentuuktype06                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０６ */
     zrndai1syenyendaka06                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０６ */
     zrndai1syenyenkijyun06                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０６ */
     zrndai1syenyenyasu06                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０６ */
     zrndai1sibousnenoutouymd7                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０７ */
     zrndai1stuuktype07                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０７ */
     zrndai1s07                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０７ */
     zrndai1syenyendakaumu07                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０７ */
     zrndai1syenyenkijyunumu07                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０７ */
     zrndai1syenyenyasuumu07                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０７ */
     zrndai1syentuuktype07                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０７ */
     zrndai1syenyendaka07                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０７ */
     zrndai1syenyenkijyun07                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０７ */
     zrndai1syenyenyasu07                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０７ */
     zrndai1sibousnenoutouymd8                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０８ */
     zrndai1stuuktype08                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０８ */
     zrndai1s08                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０８ */
     zrndai1syenyendakaumu08                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０８ */
     zrndai1syenyenkijyunumu08                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０８ */
     zrndai1syenyenyasuumu08                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０８ */
     zrndai1syentuuktype08                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０８ */
     zrndai1syenyendaka08                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０８ */
     zrndai1syenyenkijyun08                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０８ */
     zrndai1syenyenyasu08                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０８ */
     zrndai1sibousnenoutouymd9                          GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日０９ */
     zrndai1stuuktype09                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ０９ */
     zrndai1s09                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額０９ */
     zrndai1syenyendakaumu09                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０９ */
     zrndai1syenyenkijyunumu09                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０９ */
     zrndai1syenyenyasuumu09                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０９ */
     zrndai1syentuuktype09                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ０９ */
     zrndai1syenyendaka09                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）０９ */
     zrndai1syenyenkijyun09                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）０９ */
     zrndai1syenyenyasu09                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）０９ */
     zrndai1sibousnenoutouymd10                         GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額年単位応当年月日１０ */
     zrndai1stuuktype10                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ１０ */
     zrndai1s10                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額１０ */
     zrndai1syenyendakaumu10                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無１０ */
     zrndai1syenyenkijyunumu10                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無１０ */
     zrndai1syenyenyasuumu10                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無１０ */
     zrndai1syentuuktype10                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ１０ */
     zrndai1syenyendaka10                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）１０ */
     zrndai1syenyenkijyun10                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）１０ */
     zrndai1syenyenyasu10                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）１０ */
     zrndai1stuuktypehuryo                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額通貨タイプ（不慮） */
     zrndai1shuryo                                      CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（不慮） */
     zrndai1syenyendakaumuhuryo                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無（不慮） */
     zrndai1syenyenkjnumuhuryo                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無（不慮） */
     zrndai1syenyenyasuumuhuryo                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無（不慮） */
     zrndai1syentuuktypehuryo                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）通貨タイプ（不慮） */
     zrndai1syenyendakahuryo                            CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円高）（不慮） */
     zrndai1syenyenkijyunhuryo                          CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（中央値）（不慮） */
     zrndai1syenyenyasuhuryo                            CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第１死亡保険金額（円貨）（円安）（不慮） */
     zrndai2stuuktype                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第２死亡保険金額通貨タイプ */
     zrndai2s                                           CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第２死亡保険金額 */
     zrndai2syentuuktype                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第２死亡保険金額（円貨）通貨タイプ */
     zrndai2syenyendaka                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第２死亡保険金額（円貨）（円高） */
     zrndai2syenyenkijyun                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第２死亡保険金額（円貨）（中央値） */
     zrndai2syenyenyasu                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第２死亡保険金額（円貨）（円安） */
     zrndai3stuuktype                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第３死亡保険金額通貨タイプ */
     zrndai3s                                           CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第３死亡保険金額 */
     zrndai3syentuuktype                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）第３死亡保険金額（円貨）通貨タイプ */
     zrndai3syenyendaka                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第３死亡保険金額（円貨）（円高） */
     zrndai3syenyenkijyun                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第３死亡保険金額（円貨）（中央値） */
     zrndai3syenyenyasu                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）第３死亡保険金額（円貨）（円安） */
     zrnsibouinjiptnkbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）死亡保障印字パターン */
     zrnyobiv25                                         CHAR        (25)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ２５ */
     zrnmkhyouyensysnikoumsgcd                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約メッセージコード */
     zrnmkhyouyensysnikoumsgcd2                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約メッセージコード２ */
     zrnmkhyouyensysnikoumsgcd3                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約メッセージコード３ */
     zrnmkhyouyensysnikougktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約目標額通貨タイプ */
     zrnmkhyouyensysnikougk                             CHAR        (13)                                                      NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約目標額 */
     zrnmkhyouyensysnikouwra                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）目標到達時円建終身保険移行特約目標割合 */
     zrnyobiv12                                         CHAR        (12)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１２ */
     zrnkaigomaehrtkykmsgcd1                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）介護前払特約メッセージコード１ */
     zrnkaigomaehrtkykmsgcd2                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）介護前払特約メッセージコード２ */
     zrnkaigomaehrtkykmsgcdst1                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）介護前払特約メッセージコード表下１ */
     zrnkaigomaehrtkykmsgcdst2                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）介護前払特約メッセージコード表下２ */
     zrnkgmaehrtkhknkkn1mnryymd                         GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）介護前払特約第１保険期間満了日 */
     zrnkaigomaehrtkykitrnumu                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護前払特約受取額一覧有無 */
     zrnkaigomaehrtkykkyktuuka                          GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）介護前払特約契約通貨 */
     zrnkaigomaehrtkykstdmsgcd                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）介護前払特約指定代理メッセージコード */
     zrnyobiv13                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１３ */
     zrnkaigomaehrjrugktype                             CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払受領額通貨タイプ */
     zrnkaigomaehrsikuhhknnen01                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０１ */
     zrnkaigomaehrstikkn01                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０１ */
     zrnkaigomaehrjrugk01                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０１ */
     zrnkaigomaehrsikuhhknnen02                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０２ */
     zrnkaigomaehrstikkn02                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０２ */
     zrnkaigomaehrjrugk02                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０２ */
     zrnkaigomaehrsikuhhknnen03                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０３ */
     zrnkaigomaehrstikkn03                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０３ */
     zrnkaigomaehrjrugk03                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０３ */
     zrnkaigomaehrsikuhhknnen04                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０４ */
     zrnkaigomaehrstikkn04                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０４ */
     zrnkaigomaehrjrugk04                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０４ */
     zrnkaigomaehrsikuhhknnen05                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０５ */
     zrnkaigomaehrstikkn05                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０５ */
     zrnkaigomaehrjrugk05                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０５ */
     zrnkaigomaehrsikuhhknnen06                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０６ */
     zrnkaigomaehrstikkn06                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０６ */
     zrnkaigomaehrjrugk06                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０６ */
     zrnkaigomaehrsikuhhknnen07                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０７ */
     zrnkaigomaehrstikkn07                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０７ */
     zrnkaigomaehrjrugk07                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０７ */
     zrnkaigomaehrsikuhhknnen08                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０８ */
     zrnkaigomaehrstikkn08                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０８ */
     zrnkaigomaehrjrugk08                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０８ */
     zrnkaigomaehrsikuhhknnen09                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢０９ */
     zrnkaigomaehrstikkn09                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間０９ */
     zrnkaigomaehrjrugk09                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額０９ */
     zrnkaigomaehrsikuhhknnen10                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払請求日時点被保険者年齢１０ */
     zrnkaigomaehrstikkn10                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）介護前払所定期間１０ */
     zrnkaigomaehrjrugk10                               CHAR        (13)                                                      NOT NULL  ,  /* （連携用）介護前払受領額１０ */
     zrnnkmsgcd1                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード１ */
     zrnnkmsgcd2                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード２ */
     zrnnkmsgcd3                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード３ */
     zrnnkmsgcd4                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード４ */
     zrnnkmsgcd5                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード５ */
     zrnnkmsgcd6                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード６ */
     zrnnkmsgcd7                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード７ */
     zrnnkmsgcd8                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード８ */
     zrnnkmsgcd9                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード９ */
     zrnnkmsgcd10                                       CHAR        (5)                                                       NOT NULL  ,  /* （連携用）年金メッセージコード１０ */
     zrnsiboukyuuhukinmsgcd1                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード１ */
     zrnsiboukyuuhukinmsgcd2                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード２ */
     zrnsiboukyuuhukinmsgcd3                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード３ */
     zrnsiboukyuuhukinmsgcd4                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード４ */
     zrnsiboukyuuhukinmsgcd5                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード５ */
     zrnsiboukyuuhukinmsgcd6                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード６ */
     zrnsiboukyuuhukinmsgcd7                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード７ */
     zrnsiboukyuuhukinmsgcd8                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード８ */
     zrnsiboukyuuhukinmsgcd9                            CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード９ */
     zrnsiboukyuuhukinmsgcd10                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）死亡給付金メッセージコード１０ */
     zrnnkshrstartzenymd                                GRAPHIC     (11)                                                      NOT NULL  ,  /* （連携用）年金支払開始日前日 */
     zrnmkhyouyennkhknhentktype                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）目標到達時円建年金保険変更特約目標額通貨タイプ */
     zrnmkhyouyennkhknhentkmkhgk                        CHAR        (13)                                                      NOT NULL  ,  /* （連携用）目標到達時円建年金保険変更特約目標額 */
     zrnmkhyennkhknhentkmkhwari                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）目標到達時円建年金保険変更特約目標割合 */
     zrnhaibunwarimsgcd1                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）配分割合メッセージコード１ */
     zrnhaibunwarimsgcd2                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）配分割合メッセージコード２ */
     zrnhaibunwarimsgcd3                                CHAR        (5)                                                       NOT NULL  ,  /* （連携用）配分割合メッセージコード３ */
     zrnteiritutmtthbnwr                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）定率積立部分配分割合 */
     zrnsisuutmtthbnwr                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）指数積立部分配分割合 */
     zrnsisuuannaimsg1                                  CHAR        (5)                                                       NOT NULL  ,  /* （連携用）指数案内メッセージコード１ */
     zrnsisuuannaimsg2                                  CHAR        (5)                                                       NOT NULL  ,  /* （連携用）指数案内メッセージコード２ */
     zrnsisuuannaimsg3                                  CHAR        (5)                                                       NOT NULL  ,  /* （連携用）指数案内メッセージコード３ */
     zrnhutanhiyustmmsgcdue01                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表上１ */
     zrnhutanhiyustmmsgcdue02                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表上２ */
     zrnhutanhiyustmmsgcdue03                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表上３ */
     zrnhutanhiyustmmsgcdue04                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表上４ */
     zrnhutanhiyustmknsnhyuptn                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄換算費用パターン */
     zrnhutanhiyustmmsgcdst01                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表下１ */
     zrnhutanhiyustmmsgcdst02                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表下２ */
     zrnhutanhiyustmmsgcdst03                           CHAR        (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄メッセージコード表下３ */
     zrnhutanhiyustmytijihiritu                         GRAPHIC     (3)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄予定維持費率 */
     zrnhutanhiyustmkyakkjrtmin                         GRAPHIC     (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄解約控除率最小 */
     zrnhutanhiyustmkyakkjrtmax                         GRAPHIC     (5)                                                       NOT NULL  ,  /* （連携用）ご負担費用説明欄解約控除率最大 */
     zrnyobiv7x2                                        CHAR        (7)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ７＿２ */
     zrnstdstmmsgcd                                     CHAR        (5)                                                       NOT NULL  ,  /* （連携用）指定代理請求特約説明欄メッセージコード */
     zrnyobiv15x4                                       CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５＿４ */
     zrnyobiv52                                         CHAR        (52)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ５２ */
     zrnyobiv7                                          CHAR        (7)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ７ */
     zrnyobiv4                                          CHAR        (4)                                                       NOT NULL     /* （連携用）予備項目Ｖ４ */
)
;

ALTER TABLE ZT_SaihakkouHokensyoukenRn_Z ADD CONSTRAINT PK_SaihakkouHokensyoukenRn PRIMARY KEY (
     zrntyouhyouymd                                           , /* （連携用）帳票作成日 */
     zrnsyono                                                   /* （連携用）証券番号 */
) ;
