CREATE TABLE ZT_SmbcPaperlessMos2Tr_Z (
     ztrseihowebidkbn                                   VARCHAR     (2)                                                       NOT NULL  ,  /* （取込用）生保ＷｅｂＩＤ区分 */
     ztrseihowebkojincd                                 VARCHAR     (6)                                                       NOT NULL  ,  /* （取込用）生保Ｗｅｂ個人コード */
     ztrseihowebitijihozonhyouji                        VARCHAR     (1)                                                       NOT NULL  ,  /* （取込用）生保Ｗｅｂ一時保存表示 */
     ztrseihowebseknoc                                  DECIMAL     (3)                                                       NOT NULL  ,  /* （取込用）生保Ｗｅｂ設計書番号Ｃ */
     ztrseihowebcalckijyunymdc                          VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ計算基準年月日Ｃ */
     ztrseihowebhhknknnm                                VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ被保険者カナ氏名 */
     ztrseihowebhhknseiymdc                             VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者生年月日Ｃ */
     ztrseihowebhhknseikbn                              VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者性別区分 */
     ztrseihowebkykknnm                                 VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ契約者カナ氏名 */
     ztrseihowebkyksyaseiymdc                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ契約者生年月日Ｃ */
     ztrseihowebkyksyaseikbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ契約者性別区分 */
     ztrseihowebhknsyuruinoc                            VARCHAR     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ保険種類番号Ｃ */
     ztrseihowebhknkknc                                 DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ保険期間Ｃ */
     ztrseihowebphrkkiknc                               DECIMAL     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰ払込期間Ｃ */
     ztrseihowebhrkkaisuukbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ払込回数区分 */
     ztrseihowebsdpdkbn                                 VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＳ建Ｐ建区分 */
     ztrseihowebkihonsc                                 DECIMAL     (9)                                                                 ,  /* （取込用）生保Ｗｅｂ基本ＳＣ */
     ztrseihowebnksyuruikbn                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ年金種類区分 */
     ztrseihoweblntkkbn                                 VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＬＮ特約区分 */
     ztrseihowebnkshrarihyj                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ年金支払特約有表示 */
     ztrseihowebmosnoc                                  VARCHAR     (9)                                                                 ,  /* （取込用）生保Ｗｅｂ申込番号Ｃ */
     ztrseihowebsekykkigenymdc                          VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ設計書有効期限年月日Ｃ */
     ztrseihowebsksjsitencd                             VARCHAR     (4)                                                                 ,  /* （取込用）生保Ｗｅｂ作成時支店コード */
     ztrseihowebfstmossksymdc                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ初回申込書作成年月日Ｃ */
     ztrseihowebhnsyukyktdkkbn                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ編集後契約者続柄区分 */
     ztrseihowebhjnkitikbn                              VARCHAR     (5)                                                                 ,  /* （取込用）生保Ｗｅｂ法人形態区分 */
     ztrseihowebhjnkykhyj                               VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ法人契約表示 */
     ztrseihowebtksykmcd1                               VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ特殊項目コード１ */
     ztrseihowebtksykmcd2                               VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ特殊項目コード２ */
     ztrseihowebtksykmcd3                               VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ特殊項目コード３ */
     ztrseihowebtksykmcd4                               VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ特殊項目コード４ */
     ztrseihowebtksykmcd5                               VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ特殊項目コード５　 */
     ztrseihowebteiwkknc                                DECIMAL     (9)                                                                 ,  /* （取込用）生保Ｗｅｂ低Ｗ期間Ｃ */
     ztrseihowebknhjnnm                                 VARCHAR     (78)                                                                ,  /* （取込用）生保Ｗｅｂカナ法人名 */
     ztrseihowebkjhjnnm                                 VARCHAR     (62)                                                                ,  /* （取込用）生保Ｗｅｂ漢字法人名 */
     ztrseihowebkndaihyounm                             VARCHAR     (62)                                                                ,  /* （取込用）生保Ｗｅｂカナ代表者名 */
     ztrseihowebkjdaihyounm                             VARCHAR     (62)                                                                ,  /* （取込用）生保Ｗｅｂ漢字代表者名 */
     ztrseihowebdaihyouktgkkbn                          VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ代表者肩書区分 */
     ztrseihowebsykihrkp1c                              DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ初回払込Ｐ１Ｃ */
     ztrseihowebmosp1c                                  DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ申込Ｐ１Ｃ */
     ztrseihowebtkiyougyoutaikbn                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ統計用業態区分 */
     ztrseihowebzennoukknc                              DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ前納期間Ｃ */
     ztrseihowebpaperlessmoshyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂペーパーレス申込表示 */
     ztrseihowebdatasousinzmhyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂデータ送信済表示 */
     ztrseihowebkknmskhjnkitikbn                        VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ契勤務先法人形態区分 */
     ztrseihowebkykottmsk                               VARCHAR     (122)                                                               ,  /* （取込用）生保Ｗｅｂ契約者お勤め先 */
     ztrseihowebhhknsykgycd                             VARCHAR     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者職業コード */
     ztrseihowebhknmskhjnkitikbn                        VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ被勤務先法人形態区分 */
     ztrseihowebhhknottmsk                              VARCHAR     (122)                                                               ,  /* （取込用）生保Ｗｅｂ被保険者お勤め先 */
     ztrseihowebhhknnensyuukbn                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者年収区分 */
     ztrseihowebsbukthksuninzuuc                        DECIMAL     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人複数人数Ｃ */
     ztrseihowebsbuktbnwari1c                           DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人分割割合１Ｃ */
     ztrseihowebsbukttdkkbn2                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人続柄区分２ */
     ztrseihowebsbuktknnm2                              VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名２ */
     ztrseihowebsbuktkjnm2                              VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名２ */
     ztrseihowebsbuktseiymd2c                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人生年月日２Ｃ */
     ztrseihowebsbuktbnwari2c                           DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人分割割合２Ｃ */
     ztrseihowebsbukttdkkbn3                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人続柄区分３ */
     ztrseihowebsbuktknnm3                              VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名３ */
     ztrseihowebsbuktkjnm3                              VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名３ */
     ztrseihowebsbuktseiymd3c                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人生年月日３Ｃ */
     ztrseihowebsbuktbnwari3c                           DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人分割割合３Ｃ */
     ztrseihowebsbukttdkkbn4                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人続柄区分４ */
     ztrseihowebsbuktknnm4                              VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名４ */
     ztrseihowebsbuktkjnm4                              VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名４ */
     ztrseihowebsbuktseiymd4c                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人生年月日４Ｃ */
     ztrseihowebsbuktbnwari4c                           DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡受取人分割割合４Ｃ */
     ztrseihowebnkuktmrhhyj                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ年金受取人マル被表示 */
     ztrseihowebsbnkkknc                                DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡年金期間Ｃ */
     ztrseihowebikokakkjarihyj                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ意向確認記事有表示 */
     ztrseihowebfatcasnsiarihyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＦＡＴＣＡ宣誓有表示 */
     ztrseihowebkouhurisitencd                          VARCHAR     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ口振支店コード */
     ztrseihowebkouhuriyokinkbn                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ口振預金種目区分 */
     ztrseihowebkouhurikouzano                          VARCHAR     (7)                                                                 ,  /* （取込用）生保Ｗｅｂ口振口座番号 */
     ztrseihowebkuhrshmnttdkhyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ口振書面手続表示 */
     ztrseihowebmosymdc                                 VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ申込年月日Ｃ */
     ztrseihowebsyokugyoukktymdc                        VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ職業告知年月日Ｃ */
     ztrseihowebhhknsintyouc                            DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者身長Ｃ */
     ztrseihowebhhkntaijyuuc                            DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ被保険者体重Ｃ */
     ztrseihowebkktymdc                                 VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ告知年月日Ｃ */
     ztrseihowebhukusuustskskbn                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ複数指定書作成区分 */
     ztrseihowebhnnkaksyoruikbn                         VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ本人確認書類区分 */
     ztrseihowebhsktkjikou                              VARCHAR     (72)                                                                ,  /* （取込用）生保Ｗｅｂ補足特定事項 */
     ztrseihowebskskaksyoruikbn                         VARCHAR     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ親権者確認書類区分 */
     ztrseihowebskshsktkjikou                           VARCHAR     (72)                                                                ,  /* （取込用）生保Ｗｅｂ親権者補足特定事項 */
     ztrseihowebbikkjnssinfoari                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ米国人示唆情報有表示 */
     ztrseihowebplbsyutrkno                             VARCHAR     (13)                                                                ,  /* （取込用）生保ＷｅｂＰＬ募集人登録番号 */
     ztrseihowebplbsyukouincd                           VARCHAR     (20)                                                                ,  /* （取込用）生保ＷｅｂＰＬ募集人行員コード */
     ztrseihowebnrkbsyutrkno                            VARCHAR     (13)                                                                ,  /* （取込用）生保Ｗｅｂ入力募集人登録番号 */
     ztrseihowebuktkid                                  VARCHAR     (11)                                                                ,  /* （取込用）生保Ｗｅｂ受付管理ＩＤ */
     ztrseihowebdatasousinymdc                          VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂデータ送信年月日Ｃ */
     ztrseihowebdatasousinhmsc                          VARCHAR     (6)                                                                 ,  /* （取込用）生保Ｗｅｂデータ送信時分秒Ｃ */
     ztrseihowebmosuktkymdc                             VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ申込書受付年月日Ｃ */
     ztrseihowebhnnkakhskjk1                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ本人確認補足事項欄１ */
     ztrseihowebhnnkakhskjk2                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ本人確認補足事項欄２ */
     ztrseihowebhnnkakhskjk3                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ本人確認補足事項欄３ */
     ztrseihowebhnnkakhskjk4                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ本人確認補足事項欄４ */
     ztrseihowebhnnkakhskjk5                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ本人確認補足事項欄５ */
     ztrseihowebtorihoutkjk1                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ取報特記事項欄１ */
     ztrseihowebtorihoutkjk2                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ取報特記事項欄２ */
     ztrseihowebtorihoutkjk3                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ取報特記事項欄３ */
     ztrseihowebtorihoutkjk4                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ取報特記事項欄４ */
     ztrseihowebtorihoutkjk5                            VARCHAR     (102)                                                               ,  /* （取込用）生保Ｗｅｂ取報特記事項欄５ */
     ztrseihowebdrtnskno                                VARCHAR     (11)                                                                ,  /* （取込用）生保Ｗｅｂ代理店設計書番号 */
     ztrseihowebsbnksyukbn                              VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ死亡年金種類区分 */
     ztrseihowebaatkisyaknyuucd                         VARCHAR     (4)                                                                 ,  /* （取込用）生保ＷｅｂＡ扱者金融機関コード */
     ztrseihowebkktttykknrhyj                           VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ告知書到着管理表示 */
     ztrseihowebdtlkktarihyj                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ詳細告知書有表示 */
     ztrseihowebfatcasyoruiari                          VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＦＡＴＣＡ書類有表示 */
     ztrseihowebkzhurikaebankcd                         VARCHAR     (4)                                                                 ,  /* （取込用）生保Ｗｅｂ口座振替銀行番号 */
     ztrseihowebkzkakiraikbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ口座確認依頼区分 */
     ztrseihowebbmierrorhyj                             VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＢＭＩエラー表示 */
     ztrseihowebkktkmgituarihyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ告知項目該当有表示 */
     ztrseihowebsnshuhukbn                              VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ診査方法区分 */
     ztrseihowebkeihidouituhyj                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ契被同一表示 */
     ztrseihowebaeoisnsiarihyj                          VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＡＥＯＩ宣誓有表示 */
     ztrseihowebsiteituukakbn                           VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ指定通貨区分 */
     ztrseihowebnykntuukakbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ入金通貨区分 */
     ztrseihowebtargettkarihyj                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂターゲット特約有表示 */
     ztrseihowebtargettkkbn                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂターゲット特約区分 */
     ztrseihowebtargettkmkhtc                           DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂターゲット特約目標値Ｃ */
     ztrseihowebnykntuukanykngkc                        DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ入金通貨入金額Ｃ */
     ztrseihowebnykntukfsthrkpc                         DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ入金通貨初回払込ＰＣ */
     ztrseihowebnykntuknexthrkpc                        DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ入金通貨次回払込ＰＣ */
     ztrseihowebtargetyenknsnpc                         DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂターゲット円換算ＰＣ */
     ztrseihowebtargetmkhgkc                            DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂターゲット目標額Ｃ */
     ztrseihowebsaimankihyj                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ才満期表示 */
     ztrseihowebrayhyj                                  VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＲＡＹ表示 */
     ztryobiv156                                        VARCHAR     (156)                                                               ,  /* （取込用）予備項目Ｖ１５６ */
     ztrseihowebpsyouhyj                                VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＳ要表示 */
     ztrseihowebplhhknkjnm                              VARCHAR     (24)                                                                ,  /* （取込用）生保ＷｅｂＰＬ被保険者漢字氏名 */
     ztryobiv1                                          VARCHAR     (1)                                                                 ,  /* （取込用）予備項目Ｖ１ */
     ztrseihowebplkykkjnm                               VARCHAR     (24)                                                                ,  /* （取込用）生保ＷｅｂＰＬ契約者漢字氏名 */
     ztrseihowebplhjkktkbn                              VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ報状告知区分 */
     ztrseihowebplhrkkeirokbn                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ払込経路区分 */
     ztrseihowebplnkshrarihyj                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ年金支払有表示 */
     ztryobiv2                                          VARCHAR     (2)                                                                 ,  /* （取込用）予備項目Ｖ２ */
     ztrseihowebplmosnoc                                VARCHAR     (9)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ申込番号Ｃ */
     ztrseihowebplsbuktnrkkbn                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ死亡受入力区分 */
     ztrseihowebplsbukttdkkbn                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ死亡受続柄区分 */
     ztrseihowebplsbuktknnm                             VARCHAR     (38)                                                                ,  /* （取込用）生保ＷｅｂＰＬ死亡受カナ氏名 */
     ztrseihowebplsbuktkjnm                             VARCHAR     (24)                                                                ,  /* （取込用）生保ＷｅｂＰＬ死亡受漢字氏名 */
     ztryobiv3                                          VARCHAR     (3)                                                                 ,  /* （取込用）予備項目Ｖ３ */
     ztrseihowebplsbuktseiymdc                          VARCHAR     (8)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ死亡受生年月日Ｃ */
     ztrseihowebpltksykmcd1                             VARCHAR     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ特殊項目コード１ */
     ztrseihowebpltksykmcd2                             VARCHAR     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ特殊項目コード２ */
     ztrseihowebpltksykmcd3                             VARCHAR     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ特殊項目コード３ */
     ztrseihowebpltksykmcd4                             VARCHAR     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ特殊項目コード４ */
     ztrseihowebpltksykmcd5                             VARCHAR     (2)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ特殊項目コード５ */
     ztrseihowebplkyktelno                              VARCHAR     (14)                                                                ,  /* （取込用）生保ＷｅｂＰＬ契約者電話番号 */
     ztrseihowebplhhkntelno                             VARCHAR     (14)                                                                ,  /* （取込用）生保ＷｅｂＰＬ被保険者電話番号 */
     ztryobiv3x2                                        VARCHAR     (3)                                                                 ,  /* （取込用）予備項目Ｖ３＿２ */
     ztrseihowebplkihontikucd                           VARCHAR     (8)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ基本地区コード */
     ztrseihowebpltsinadrkai                            VARCHAR     (126)                                                               ,  /* （取込用）生保ＷｅｂＰＬ通信先住所下位 */
     ztrseihowebplhiikihontikucd                        VARCHAR     (8)                                                                 ,  /* （取込用）生保ＷｅｂＰＬ被基本地区コード */
     ztrseihowebplhhknadr                               VARCHAR     (250)                                                               ,  /* （取込用）生保ＷｅｂＰＬ被保険者住所 */
     ztrseihowebgnykntuknykngkc                         DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨入金通貨入金額Ｃ */
     ztrseihowebgnykntukfsthrkpc                        DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨入金通貨初回ＰＣ */
     ztrseihowebgnykntuknxthrkpc                        DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨入金通貨次回ＰＣ */
     ztrseihowebgaikakihonpc                            DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨基本ＰＣ */
     ztrseihowebkaigmehrtkarihyj                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ介護前払特約有表示 */
     ztrseihowebyenhsyutkarihyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ円最低保証特約有表示 */
     ztrseihowebgaikakihonsc                            DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨基本ＳＣ */
     ztrseihowebdai1hknkknc                             DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ第１保険期間Ｃ */
     ztrseihowebdsmoshyj                                VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ申込有表示 */
     ztrseihowebdsmailaddress                           VARCHAR     (100)                                                               ,  /* （取込用）生保ＷｅｂＤＳメールアドレス */
     ztrseihowebankenkanrino                            VARCHAR     (15)                                                                ,  /* （取込用）生保Ｗｅｂ案件管理番号 */
     ztrseihowebkydbosyuukjncd                          VARCHAR     (7)                                                                 ,  /* （取込用）生保Ｗｅｂ共同募集個人コード */
     ztrseihowebhnyppltzmhyj                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ汎用ＰＰＬ対応済表示 */
     ztrseihowebssrndhbnwrc                             DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ指数連動部分配分割合Ｃ */
     ztrseihowebtrtrndhbnwrc                            DECIMAL     (3)                                                                 ,  /* （取込用）生保Ｗｅｂ定率積立部分配分割合Ｃ */
     ztrseihowebsueokikknc                              DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ据置期間Ｃ */
     ztrseihowebmnkuktnrkkbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ満期受取人入力区分 */
     ztrseihowebmnkukttdkkbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ満期受取人続柄区分 */
     ztrseihowebmnkuktknnm                              VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ満期受取人カナ氏名 */
     ztrseihowebmnkuktkjnm                              VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂ満期受取人漢字氏名 */
     ztrseihowebmnkuktseiymdc                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ満期受取人生年月日Ｃ */
     ztrseihowebdsknkzmeigi                             VARCHAR     (62)                                                                ,  /* （取込用）生保ＷｅｂＤＳカナ口座名義 */
     ztrseihowebdskzsyuruikbn                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ口座種類区分 */
     ztrseihowebdskinyuucd                              VARCHAR     (4)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ金融機関コード */
     ztrseihowebdssitencd                               VARCHAR     (3)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ支店コード */
     ztrseihowebdsyokinkbn                              VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ預金種目区分 */
     ztrseihowebdskouzano                               VARCHAR     (12)                                                                ,  /* （取込用）生保ＷｅｂＤＳ口座番号 */
     ztrseihowebdsansyono                               VARCHAR     (24)                                                                ,  /* （取込用）生保ＷｅｂＤＳ暗証番号 */
     ztrseihowebdssymnttdkhyj                           VARCHAR     (1)                                                                 ,  /* （取込用）生保ＷｅｂＤＳ書面手続表示 */
     ztrseihowebikkatupc                                DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ一括払ＰＣ */
     ztrseihowebikkatubaraikbn                          VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ一括払区分 */
     ztrseihowebiktbrikaisuuc                           DECIMAL     (2)                                                                 ,  /* （取込用）生保Ｗｅｂ一括払回数Ｃ */
     ztrseihowebzennoupc                                DECIMAL     (10)                                                                ,  /* （取込用）生保Ｗｅｂ前納ＰＣ */
     ztrseihowebgaikazennoupc                           DECIMAL     (13)                                                                ,  /* （取込用）生保Ｗｅｂ外貨前納ＰＣ */
     ztrseihowebzennouhyj                               VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ前納表示 */
     ztrseihowebyakkankbn                               VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ約款区分 */
     ztrseihowebnetkhrzmhyj                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂネット口振対応済表示 */
     ztrseihowebkzktrkmoskbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂご家族登録申込区分 */
     ztrseihowebkzktdkkbn1                              VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂご家族続柄区分１ */
     ztrseihowebkzkknnm1                                VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂご家族カナ氏名１ */
     ztrseihowebkzkkjnm1                                VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂご家族漢字氏名１ */
     ztrseihowebkzkseikbn1                              VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂご家族性別区分１ */
     ztrseihowebkzkseiymd1c                             VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂご家族生年月日１Ｃ */
     ztrseihowebkzkkykdoukyohyj1                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂご家族契同居表示１ */
     ztrseihowebkzkyno1                                 VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂご家族郵便番号１ */
     ztrseihowebkzkadr1                                 VARCHAR     (126)                                                               ,  /* （取込用）生保Ｗｅｂご家族住所１ */
     ztrseihowebkzktelno1                               VARCHAR     (14)                                                                ,  /* （取込用）生保Ｗｅｂご家族電話番号１ */
     ztrseihowebkykdrtkkanouhyj                         VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ契代理特約可能表示 */
     ztrseihowebhhkndrtkkanouhyj                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ被代理特約可能表示 */
     ztrseihowebdrtkkbn                                 VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ代理特約区分 */
     ztrseihowebkykdrnrkkbn                             VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ契代理入力区分 */
     ztrseihowebhhkndrnrkkbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ被代理入力区分 */
     ztrseihowebhhkndrtdkkbn                            VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ被代理続柄区分 */
     ztrseihowebhhkndrknnm                              VARCHAR     (38)                                                                ,  /* （取込用）生保Ｗｅｂ被代理カナ氏名 */
     ztrseihowebhhkndrkjnm                              VARCHAR     (24)                                                                ,  /* （取込用）生保Ｗｅｂ被代理漢字氏名 */
     ztrseihowebhhkndrseiymdc                           VARCHAR     (8)                                                                 ,  /* （取込用）生保Ｗｅｂ被代理生年月日Ｃ */
     ztrseihowebdaihituarihyj                           VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ代筆有表示 */
     ztrseihowebkoureisyakakkbn1                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ高齢者確認区分１ */
     ztrseihowebkoureisyakakkbn2                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ高齢者確認区分２ */
     ztrseihowebkoureisyakakkbn3                        VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ高齢者確認区分３ */
     ztrseihowebptuutihyj                               VARCHAR     (1)                                                                 ,  /* （取込用）生保Ｗｅｂ保険料通知有表示 */
     ztryobiv1546                                       VARCHAR     (1546)                                                              ,  /* （取込用）予備項目Ｖ１５４６ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL WITH DEFAULT 0                                                /* バージョン */
)
;

ALTER TABLE ZT_SmbcPaperlessMos2Tr_Z ADD CONSTRAINT PK_SmbcPaperlessMos2Tr PRIMARY KEY (
     ztrseihowebidkbn                                         , /* （取込用）生保ＷｅｂＩＤ区分 */
     ztrseihowebkojincd                                       , /* （取込用）生保Ｗｅｂ個人コード */
     ztrseihowebitijihozonhyouji                              , /* （取込用）生保Ｗｅｂ一時保存表示 */
     ztrseihowebseknoc                                          /* （取込用）生保Ｗｅｂ設計書番号Ｃ */
) ;
