CREATE TABLE ZT_SrKbkSsuRnduHknVKnsyuyuRn_Z (
     zrnsequenceno                                      DECIMAL     (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnyuukourecordlength                              DECIMAL     (7)                                                       NOT NULL  ,  /* （連携用）有効レコード長 */
     zrnrdwarea                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ＲＤＷ領域 */
     zrnkeijyouym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）計上年月 */
     zrnraysystemhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＲＡＹシステム表示 */
     zrndatakanrino                                     CHAR        (11)                                                      NOT NULL  ,  /* （連携用）データ管理番号 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ免区分 */
     zrnsotodasimanagehyouji                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出満年令表示 */
     zrnsuuriyouyobin6                                  CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６ */
     zrnyobiv12                                         CHAR        (12)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１２ */
     zrnkbnkeiriyousegmentkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理種類コード */
     zrnsuuriyouyobin6x2                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６＿２ */
     zrnyobiv8                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ８ */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令Ｖ２ */
     zrnkuriagekurisagekbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）繰上げ繰下げ区分 */
     zrnsuuriyouyobin6x3                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６＿３ */
     zrnyobiv8x2                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ８＿２ */
     zrnkeiyakujiyoteiriritu                            DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）契約時予定利率 */
     zrnsrkaiyakusjkkktyouseirrt                        DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）数理用解約時市場価格調整用利率 */
     zrnsrkyksjkkktyouseiriritu                         DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）数理用契約時市場価格調整用利率 */
     zrnmvatyouseikou                                   DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）ＭＶＡ調整項 */
     zrnsisuurendourate                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）指数連動部分割合 */
     zrnsisuukbn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）指数区分 */
     zrngaikakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外貨区分 */
     zrnkimatukawaserate                                DECIMAL     (9,6)                                                     NOT NULL  ,  /* （連携用）期末為替レート */
     zrnkaiyakukoujyoritu                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）解約控除率 */
     zrntumitateriritu                                  DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立利率 */
     zrnsknnkaisiymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）責任開始日 */
     zrnrendouritu                                      DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）連動率 */
     zrnsuuriyouyobin3                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ３ */
     zrnyobiv5                                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ５ */
     zrnsyukeiyakup                                     DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）主契約Ｐ */
     zrnmvatyouseigow                                   DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnyobin11                                         DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１ */
     zrnyobin11x2                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２ */
     zrnkmtsisuurentumitatekn                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）期末指数連動部分積立金 */
     zrnkmttirttmtttumitatekn                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）期末定率積立部分積立金 */
     zrnkmtsisuurentyokugotmttkn                        DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）期末指数連動部分直後積立金 */
     zrnyobin11x4                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４ */
     zrnyobin11x5                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿５ */
     zrnsisuubbncalckijyunymd                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日 */
     zrnsisuubbntumitatekin                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金 */
     zrntoukisisuu                                      DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数 */
     zrntoukisisuukijyunymd                             CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日 */
     zrnzenkisisuu                                      DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数 */
     zrnzenkisisuukijyunymd                             CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日 */
     zrntmttknzoukaritu                                 DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率 */
     zrntoukitumimasikin                                DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金 */
     zrnyobiv9                                          CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９ */
     zrnsisuubbncalckijyunymdx2                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿２ */
     zrnsisuubbntumitatekinx2                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿２ */
     zrntoukisisuux2                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿２ */
     zrntoukisisuukijyunymdx2                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿２ */
     zrnzenkisisuux2                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿２ */
     zrnzenkisisuukijyunymdx2                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿２ */
     zrntmttknzoukaritux2                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿２ */
     zrntoukitumimasikinx2                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿２ */
     zrnyobiv9x2                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿２ */
     zrnsisuubbncalckijyunymdx3                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿３ */
     zrnsisuubbntumitatekinx3                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿３ */
     zrntoukisisuux3                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿３ */
     zrntoukisisuukijyunymdx3                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿３ */
     zrnzenkisisuux3                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿３ */
     zrnzenkisisuukijyunymdx3                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿３ */
     zrntmttknzoukaritux3                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿３ */
     zrntoukitumimasikinx3                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿３ */
     zrnyobiv9x3                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿３ */
     zrnsisuubbncalckijyunymdx4                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿４ */
     zrnsisuubbntumitatekinx4                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿４ */
     zrntoukisisuux4                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿４ */
     zrntoukisisuukijyunymdx4                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿４ */
     zrnzenkisisuux4                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿４ */
     zrnzenkisisuukijyunymdx4                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿４ */
     zrntmttknzoukaritux4                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿４ */
     zrntoukitumimasikinx4                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿４ */
     zrnyobiv9x4                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿４ */
     zrnsisuubbncalckijyunymdx5                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿５ */
     zrnsisuubbntumitatekinx5                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿５ */
     zrntoukisisuux5                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿５ */
     zrntoukisisuukijyunymdx5                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿５ */
     zrnzenkisisuux5                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿５ */
     zrnzenkisisuukijyunymdx5                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿５ */
     zrntmttknzoukaritux5                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿５ */
     zrntoukitumimasikinx5                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿５ */
     zrnyobiv9x5                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿５ */
     zrnsisuubbncalckijyunymdx6                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿６ */
     zrnsisuubbntumitatekinx6                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿６ */
     zrntoukisisuux6                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿６ */
     zrntoukisisuukijyunymdx6                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿６ */
     zrnzenkisisuux6                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿６ */
     zrnzenkisisuukijyunymdx6                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿６ */
     zrntmttknzoukaritux6                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿６ */
     zrntoukitumimasikinx6                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿６ */
     zrnyobiv9x6                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿６ */
     zrnsisuubbncalckijyunymdx7                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿７ */
     zrnsisuubbntumitatekinx7                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿７ */
     zrntoukisisuux7                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿７ */
     zrntoukisisuukijyunymdx7                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿７ */
     zrnzenkisisuux7                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿７ */
     zrnzenkisisuukijyunymdx7                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿７ */
     zrntmttknzoukaritux7                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿７ */
     zrntoukitumimasikinx7                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿７ */
     zrnyobiv9x7                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿７ */
     zrnsisuubbncalckijyunymdx8                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿８ */
     zrnsisuubbntumitatekinx8                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿８ */
     zrntoukisisuux8                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿８ */
     zrntoukisisuukijyunymdx8                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿８ */
     zrnzenkisisuux8                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿８ */
     zrnzenkisisuukijyunymdx8                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿８ */
     zrntmttknzoukaritux8                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿８ */
     zrntoukitumimasikinx8                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿８ */
     zrnyobiv9x8                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿８ */
     zrnsisuubbncalckijyunymdx9                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿９ */
     zrnsisuubbntumitatekinx9                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿９ */
     zrntoukisisuux9                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿９ */
     zrntoukisisuukijyunymdx9                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿９ */
     zrnzenkisisuux9                                    DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿９ */
     zrnzenkisisuukijyunymdx9                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿９ */
     zrntmttknzoukaritux9                               DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿９ */
     zrntoukitumimasikinx9                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿９ */
     zrnyobiv9x9                                        CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿９ */
     zrnsisuubbncalckijyunymdx10                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１０ */
     zrnsisuubbntumitatekinx10                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１０ */
     zrntoukisisuux10                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１０ */
     zrntoukisisuukijyunymdx10                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１０ */
     zrnzenkisisuux10                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１０ */
     zrnzenkisisuukijyunymdx10                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１０ */
     zrntmttknzoukaritux10                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１０ */
     zrntoukitumimasikinx10                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１０ */
     zrnyobiv9x10                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１０ */
     zrnsisuubbncalckijyunymdx11                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１１ */
     zrnsisuubbntumitatekinx11                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１１ */
     zrntoukisisuux11                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１１ */
     zrntoukisisuukijyunymdx11                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１１ */
     zrnzenkisisuux11                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１１ */
     zrnzenkisisuukijyunymdx11                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１１ */
     zrntmttknzoukaritux11                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１１ */
     zrntoukitumimasikinx11                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１１ */
     zrnyobiv9x11                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１１ */
     zrnsisuubbncalckijyunymdx12                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１２ */
     zrnsisuubbntumitatekinx12                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１２ */
     zrntoukisisuux12                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１２ */
     zrntoukisisuukijyunymdx12                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１２ */
     zrnzenkisisuux12                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１２ */
     zrnzenkisisuukijyunymdx12                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１２ */
     zrntmttknzoukaritux12                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１２ */
     zrntoukitumimasikinx12                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１２ */
     zrnyobiv9x12                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１２ */
     zrnsisuubbncalckijyunymdx13                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１３ */
     zrnsisuubbntumitatekinx13                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１３ */
     zrntoukisisuux13                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１３ */
     zrntoukisisuukijyunymdx13                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１３ */
     zrnzenkisisuux13                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１３ */
     zrnzenkisisuukijyunymdx13                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１３ */
     zrntmttknzoukaritux13                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１３ */
     zrntoukitumimasikinx13                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１３ */
     zrnyobiv9x13                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１３ */
     zrnsisuubbncalckijyunymdx14                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１４ */
     zrnsisuubbntumitatekinx14                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１４ */
     zrntoukisisuux14                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１４ */
     zrntoukisisuukijyunymdx14                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１４ */
     zrnzenkisisuux14                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１４ */
     zrnzenkisisuukijyunymdx14                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１４ */
     zrntmttknzoukaritux14                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１４ */
     zrntoukitumimasikinx14                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１４ */
     zrnyobiv9x14                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１４ */
     zrnsisuubbncalckijyunymdx15                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）指数部分計算基準日＿１５ */
     zrnsisuubbntumitatekinx15                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）指数部分積立金＿１５ */
     zrntoukisisuux15                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）当期指数＿１５ */
     zrntoukisisuukijyunymdx15                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）当期指数基準年月日＿１５ */
     zrnzenkisisuux15                                   DECIMAL     (10,5)                                                    NOT NULL  ,  /* （連携用）前期指数＿１５ */
     zrnzenkisisuukijyunymdx15                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前期指数基準年月日＿１５ */
     zrntmttknzoukaritux15                              DECIMAL     (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率＿１５ */
     zrntoukitumimasikinx15                             DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）当期積増金＿１５ */
     zrnyobiv9x15                                       CHAR        (9)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ９＿１５ */
     zrnteiritucalckijyunymd                            CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日 */
     zrnteiritutumitatekin                              DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金 */
     zrnyobiv16                                         CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６ */
     zrnteiritucalckijyunymdx2                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿２ */
     zrnteiritutumitatekinx2                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿２ */
     zrnyobiv16x2                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿２ */
     zrnteiritucalckijyunymdx3                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿３ */
     zrnteiritutumitatekinx3                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿３ */
     zrnyobiv16x3                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿３ */
     zrnteiritucalckijyunymdx4                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿４ */
     zrnteiritutumitatekinx4                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿４ */
     zrnyobiv16x4                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿４ */
     zrnteiritucalckijyunymdx5                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿５ */
     zrnteiritutumitatekinx5                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿５ */
     zrnyobiv16x5                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿５ */
     zrnteiritucalckijyunymdx6                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿６ */
     zrnteiritutumitatekinx6                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿６ */
     zrnyobiv16x6                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿６ */
     zrnteiritucalckijyunymdx7                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿７ */
     zrnteiritutumitatekinx7                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿７ */
     zrnyobiv16x7                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿７ */
     zrnteiritucalckijyunymdx8                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿８ */
     zrnteiritutumitatekinx8                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿８ */
     zrnyobiv16x8                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿８ */
     zrnteiritucalckijyunymdx9                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿９ */
     zrnteiritutumitatekinx9                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿９ */
     zrnyobiv16x9                                       CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿９ */
     zrnteiritucalckijyunymdx10                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１０ */
     zrnteiritutumitatekinx10                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１０ */
     zrnyobiv16x10                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１０ */
     zrnteiritucalckijyunymdx11                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１１ */
     zrnteiritutumitatekinx11                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１１ */
     zrnyobiv16x11                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１１ */
     zrnteiritucalckijyunymdx12                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１２ */
     zrnteiritutumitatekinx12                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１２ */
     zrnyobiv16x12                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１２ */
     zrnteiritucalckijyunymdx13                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１３ */
     zrnteiritutumitatekinx13                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１３ */
     zrnyobiv16x13                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１３ */
     zrnteiritucalckijyunymdx14                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１４ */
     zrnteiritutumitatekinx14                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１４ */
     zrnyobiv16x14                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１４ */
     zrnteiritucalckijyunymdx15                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）定率部分計算基準日＿１５ */
     zrnteiritutumitatekinx15                           DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）定率部分積立金＿１５ */
     zrnyobiv16x15                                      CHAR        (16)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１６＿１５ */
     zrngengakujicalckijyunymd                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）減額時計算基準年月日 */
     zrngengakujisisuutmttkn                            DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）減額時指数部分積立金 */
     zrngengakujiteiritutmttkn                          DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）減額時定率部分積立金 */
     zrnyobiv10                                         CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０ */
     zrnyobin11x6                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿６ */
     zrnyobin11x7                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿７ */
     zrnyobin11x8                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿８ */
     zrnyobin11x9                                       DECIMAL     (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿９ */
     zrnsuuriyouyobin14                                 CHAR        (14)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１４ */
     zrnyobiv20                                         CHAR        (20)                                                      NOT NULL     /* （連携用）予備項目Ｖ２０ */
)
;

ALTER TABLE ZT_SrKbkSsuRnduHknVKnsyuyuRn_Z ADD CONSTRAINT PK_SrKbkSsuRnduHknVKnsyuyuRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
