CREATE VIEW ZT_KyhknShrJyoukyouRnrkTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     ztytksyukgu ,         /* （中継用）特約種類記号 */
     ztytokuyakugatakbn ,         /* （中継用）特約型区分 */
     ztytokuyakukisi ,         /* （中継用）特約期始 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztytyuutohukakbn ,         /* （中継用）中途付加区分 */
     ztyhyoukataikbn ,         /* （中継用）標下体区分 */
     ztyatukaisisyatodouhukencd ,         /* （中継用）扱支社都道府県コード */
     ztytokuyakusinkyuukbn ,         /* （中継用）特約新旧区分 */
     ztybsyym ,         /* （中継用）募集年月 */
     ztytkykdai2hihokensyahyj ,         /* （中継用）特約第２被保険者表示 */
     ztytokuteisippeisethyj ,         /* （中継用）特定疾病セット表示 */
     ztyjyusyousyaseibetukbn ,         /* （中継用）受傷者性別区分 */
     ztykazokujyusyousyakbn ,         /* （中継用）家族受傷者区分 */
     ztykeiyakunen ,         /* （中継用）契約年令 */
     ztymannenreihyj ,         /* （中継用）満年令表示 */
     ztyhhknnentysihyj ,         /* （中継用）被保険者年令調整表示 */
     ztyyobiv2 ,         /* （中継用）予備項目Ｖ２ */
     ztykyuuhukbn ,         /* （中継用）給付区分 */
     ztysiharaijyoutaikbn ,         /* （中継用）支払状態区分 */
     ztysyouincd ,         /* （中継用）消因コード */
     ztyjikohasseiymd2 ,         /* （中継用）事故発生年月日 */
     ztysyougaikoteiymd ,         /* （中継用）傷害固定年月日 */
     ztynyuuinymd ,         /* （中継用）入院年月日 */
     ztyshrymd ,         /* （中継用）支払年月日 */
     ztykyuuhuwariai ,         /* （中継用）給付割合 */
     ztysiharaikingakun9 ,         /* （中継用）支払金額Ｎ９ */
     ztykyoukaihoukokuyoukingaku ,         /* （中継用）協会報告用金額 */
     ztytuuinkakujyuuhukakbn ,         /* （中継用）通院カク充付加区分 */
     ztykangohukahyj ,         /* （中継用）看護付加表示 */
     ztysonsyoukyuuhukinkbn ,         /* （中継用）損傷給付金区分 */
     ztysiboukoudosyougaicd ,         /* （中継用）死亡高度障害コード */
     ztysyokikyuuhutandokushrhyj ,         /* （中継用）初期給付単独支払表示 */
     ztykakuseikyuuhukbn ,         /* （中継用）カク成給付区分 */
     ztysoukikeakyuuhutuusankisu ,         /* （中継用）早期ケア給付通算回数 */
     ztysyonendokyuuhuwariai ,         /* （中継用）初年度給付割合 */
     ztysyonendosiharaihyj ,         /* （中継用）初年度支払表示 */
     ztyyobiv4x2 ,         /* （中継用）予備項目Ｖ４＿２ */
     ztykousingohasseihyj ,         /* （中継用）更新後発生表示 */
     ztybyoumeicd1 ,         /* （中継用）病名コード１ */
     ztybyoumeicd2 ,         /* （中継用）病名コード２ */
     ztysaigaigenincd ,         /* （中継用）災害原因コード */
     ztysyougaitoukyuugou ,         /* （中継用）障害等級号 */
     ztysyujyutucd ,         /* （中継用）手術コード */
     ztysyujyutumeicd ,         /* （中継用）手術名コード */
     ztytuuinkangogeninkbn ,         /* （中継用）通院看護原因区分 */
     ztyundoukisonsyoukbn ,         /* （中継用）運動器損傷区分 */
     ztyganmensonsyoukbn ,         /* （中継用）顔面損傷区分 */
     ztysonsyougeninkbn ,         /* （中継用）損傷原因区分 */
     ztykikensportskbn ,         /* （中継用）危険スポーツ区分 */
     ztyyobiv2x2 ,         /* （中継用）予備項目Ｖ２＿２ */
     ztysiharainissuukbn ,         /* （中継用）支払日数区分 */
     ztykakuseikatakbn ,         /* （中継用）カク成型区分 */
     ztybosyuukeirokbn ,         /* （中継用）募集経路区分 */
     ztypmenhutanpohyj ,         /* （中継用）Ｐ免不担保表示 */
     ztykousinkbn ,         /* （中継用）更新区分 */
     ztykusnmetkyksykipjyutuym ,         /* （中継用）更新前特約初回Ｐ充当年月 */
     ztytoukeiyousinsakbn ,         /* （中継用）統計用診査区分 */
     ztypmenhukakbn ,         /* （中継用）Ｐ免付加区分 */
     ztypmenkbnv2 ,         /* （中継用）Ｐ免区分Ｖ２ */
     ztyketteikijyunkanwakbn ,         /* （中継用）決定基準緩和区分 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztytokuyakukigousedaikbn ,         /* （中継用）特約記号世代区分 */
     ztysotodasipmenkbn ,         /* （中継用）外出Ｐ免区分 */
     ztystdssnskbn ,         /* （中継用）外出診査区分 */
     ztysotodasikousinkbn ,         /* （中継用）外出更新区分 */
     ztybosyuukeitaikbn ,         /* （中継用）募集形態区分 */
     ztyyobiv5 ,         /* （中継用）予備項目Ｖ５ */
     ztyqpackhyj ,         /* （中継用）Ｑパック表示 */
     ztybunkatukbn ,         /* （中継用）分割区分 */
     ztytenkanhosyouminaosikbn ,         /* （中継用）転換保障見直区分 */
     ztykousinmaesiharaihyj ,         /* （中継用）更新前支払表示 */
     ztydouitunyuuinno ,         /* （中継用）同一入院番号 */
     ztysyujyutujinyuuinkbn ,         /* （中継用）手術時入院区分 */
     ztysyujyutusyuruikbn ,         /* （中継用）手術種類区分 */
     ztygannyuuinkbn ,         /* （中継用）がん入院区分 */
     ztyhokenhoutekiyouhyouji ,         /* （中継用）保険法適用表示 */
     ztysotodasiphkbnmnoshyouji ,         /* （中継用）外出Ｐ不可分見直表示 */
     ztytokuteijyoutaihushrhyj ,         /* （中継用）特定状態不支払表示 */
     ztysisyacd ,         /* （中継用）支社コード */
     ztysykgycd ,         /* （中継用）職業コード */
     ztysuuriyouyobiv11 ,         /* （中継用）数理用予備項目Ｖ１１ */
     ztyyoukaigojyoutaikaisiymd ,         /* （中継用）要介護状態開始年月日 */
     ztyyoukaigojyoutaiendymd ,         /* （中継用）要介護状態終了年月日 */
     ztyrendouyousntkjyubbnhyj ,         /* （中継用）連動用新特条部分表示 */
     ztymusentakukeiyakukbn ,         /* （中継用）無選択契約区分 */
     ztymaruteiskeijihukahyj ,         /* （中継用）マル定新契約時付加表示 */
     ztytoliplhyj ,         /* （中継用）ＴＯＬＩＰＬ表示 */
     ztystdssytikbn ,         /* （中継用）外出集定区分 */
     ztyhisei ,         /* （中継用）被性 */
     ztysuuriyobin9 ,         /* （中継用）数理予備項目Ｎ９ */
     ztysaigaisibousiharaikngk ,         /* （中継用）災害死亡支払金額 */
     ztytokuyakuhinen ,         /* （中継用）特約被年令 */
     ztygnykbttryukyuhkntusnkisu ,         /* （中継用）がん薬物治療給付金通算回数 */
     ztygansyuruikbn ,         /* （中継用）がん種類区分 */
     ztyganyakubutusyuruikbn ,         /* （中継用）がん薬物種類区分 */
     ztysyuuroukigjyujtjyutikbn ,         /* （中継用）就労介護充実状態区分 */
     ztysyuuroukigjyujtgeninkbn ,         /* （中継用）就労介護充実原因区分 */
     ztykigjyujtjyoutaigeninkbn ,         /* （中継用）介護充実状態原因区分 */
     ztysykmtssyukahikbn ,         /* （中継用）食物摂取可否区分 */
     ztyfktrsmtkahikbn ,         /* （中継用）拭き取り始末可否区分 */
     ztyhokoukahikbn ,         /* （中継用）歩行可否区分 */
     ztynyykkahikbn ,         /* （中継用）入浴可否区分 */
     ztyihukutyakudatukahikbn ,         /* （中継用）衣服着脱可否区分 */
     ztyngerkahikbn ,         /* （中継用）寝返り可否区分 */
     ztyseiketuseiyoukahikbn ,         /* （中継用）清潔整容可否区分 */
     ztynintisyougeninkbn ,         /* （中継用）認知症原因区分 */
     ztysyuruhnujyujtjyutikbn ,         /* （中継用）就労不能充実状態区分 */
     ztytokuteisyougaikbn ,         /* （中継用）特定障害区分 */
     ztydatakanrino2 ,         /* （中継用）データ管理番号２ */
     ztydatakanrino3 ,         /* （中継用）データ管理番号３ */
     ztyknkuzusnzyrttekitkarihyj ,         /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekeizokuhyouji ,         /* （中継用）Ｂｌｕｅ継続表示 */
     ztyzyrthntiyustatuskbn ,         /* （中継用）乗率判定用ステータス区分 */
     ztyzyrthntiyustatuskbnx2 ,         /* （中継用）乗率判定用ステータス区分＿２ */
     ztyzyrthntiyustatuskbnx3 ,         /* （中継用）乗率判定用ステータス区分＿３ */
     ztyzyrthntiyustatuskbnx4 ,         /* （中継用）乗率判定用ステータス区分＿４ */
     ztyzyrthntiyustatuskbnx5 ,         /* （中継用）乗率判定用ステータス区分＿５ */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyknkuzusnzyrtx2 ,         /* （中継用）健康増進乗率＿２ */
     ztysinkeiyakujivithkhyouji ,         /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztypwrbksidhitekiyouhyj ,         /* （中継用）保険料割引制度非適用表示 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztysuuriyouyobin4 ,         /* （中継用）数理用予備項目Ｎ４ */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztykawaserate ,         /* （中継用）為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztykeiyakujiyoteiriritu ,         /* （中継用）契約時予定利率 */
     ztygaikadatesiharais ,         /* （中継用）外貨建支払Ｓ */
     ztygaikadatesyukeiyakus ,         /* （中継用）外貨建主契約Ｓ */
     ztygaikadatesyukeiyakup ,         /* （中継用）外貨建主契約Ｐ */
     ztyenkdtsbujsitihsyukngk ,         /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10 ,         /* （中継用）数理用予備項目Ｎ１０ */
     ztyyobiv10x2 ,         /* （中継用）予備項目Ｖ１０＿２ */
     ztymvatyouseigow ,         /* （中継用）ＭＶＡ調整後Ｗ */
     ztymvakeisanjisknnjynbkn ,         /* （中継用）ＭＶＡ計算時責任準備金 */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_KyhknShrJyoukyouRnrkTy_Z;