CREATE VIEW ZT_DrtenSkKykDtlSyokaiTy AS SELECT
     ztysakuseiym ,         /* （中継用）作成年月 */
     ztybsydrtencd ,         /* （中継用）募集代理店コード */
     ztytntusycd ,         /* （中継用）担当者コード */
     ztysyono ,         /* （中継用）証券番号 */
     ztykykymwareki4keta ,         /* （中継用）契約年月（和暦）（４桁） */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztyatesakinm ,         /* （中継用）宛先名 */
     ztyhassinka ,         /* （中継用）発信課 */
     ztytelno15keta ,         /* （中継用）電話番号（１５桁） */
     ztybsyymwareki4keta ,         /* （中継用）募集年月（和暦）（４桁） */
     ztytntusynm ,         /* （中継用）担当者名 */
     ztykydatkikbnkj ,         /* （中継用）共同扱区分（漢字） */
     ztykyknmkj20 ,         /* （中継用）契約者名（漢字）（２０桁） */
     ztyskymdwareki ,         /* （中継用）失効年月日（和暦） */
     ztyhrkkaisuukj ,         /* （中継用）払込回数（漢字） */
     ztyhrkkeirokj ,         /* （中継用）払込経路（漢字） */
     ztyp11keta ,         /* （中継用）保険料（１１桁） */
     ztyskhr ,         /* （中継用）失効時返戻金 */
     ztyjizensyoukaiyouhyj ,         /* （中継用）事前照会要表示 */
     ztytntusygyouhaiinfo ,         /* （中継用）担当者業廃情報 */
     ztyhrkkeirobtjhmidasi ,         /* （中継用）払込経路別情報見出し */
     ztyhrkkeirobtjh ,         /* （中継用）払込経路別情報 */
     ztyhknsyuruimei ,         /* （中継用）保険種類名 */
     ztybkofccd ,         /* （中継用）バックオフィスコード */
     ztydbskyoteiymd ,         /* （中継用）ＤＢ削除予定年月 */
     ztyminyukaisuu ,         /* （中継用）未入回数 */
     ztyjikaipjyuutouym ,         /* （中継用）次回Ｐ充当年月 */
     ztyvitkaiinno ,         /* （中継用）Ｖｉｔ会員番号 */
     ztyvitkykym ,         /* （中継用）Ｖｉｔ契約年月 */
     ztyvitskymd ,         /* （中継用）Ｖｉｔ失効年月日 */
     ztyvithrkkaisuu ,         /* （中継用）Ｖｉｔ払込回数 */
     ztyvithrkkeiro ,         /* （中継用）Ｖｉｔ払込経路 */
     ztyzkomivitriyoury ,         /* （中継用）税込Ｖｉｔ利用料 */
     ztyvitnyknkaisuu ,         /* （中継用）Ｖｉｔ入金回数 */
     ztyvitbikou ,         /* （中継用）Ｖｉｔ備考 */
     ztyyobiv25           /* （中継用）予備項目Ｖ２５ */
FROM ZT_DrtenSkKykDtlSyokaiTy_Z;