CREATE VIEW ZT_KessanYokukiPRn AS SELECT
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnhokensyuruikigouyobi1x1 ,         /* （連携用）保険種類記号予備１＿１ */
     zrnhokensyuruikigouyobi1x2 ,         /* （連携用）保険種類記号予備１＿２ */
     zrnhokensyuruikigouyobi1x3 ,         /* （連携用）保険種類記号予備１＿３ */
     zrnhokensyuruikigouyobi1x4 ,         /* （連携用）保険種類記号予備１＿４ */
     zrnhokensyuruikigouyobi1x5 ,         /* （連携用）保険種類記号予備１＿５ */
     zrnhokensyuruikigouyobi1x6 ,         /* （連携用）保険種類記号予備１＿６ */
     zrnhokensyuruikigouyobi1x7 ,         /* （連携用）保険種類記号予備１＿７ */
     zrnhokensyuruikigouyobi1x8 ,         /* （連携用）保険種類記号予備１＿８ */
     zrnhokensyuruikigouyobi1x9 ,         /* （連携用）保険種類記号予備１＿９ */
     zrnhokensyuruikigouyobi1x10 ,         /* （連携用）保険種類記号予備１＿１０ */
     zrnhokensyuruikigouyobi1x11 ,         /* （連携用）保険種類記号予備１＿１１ */
     zrnhokensyuruikigouyobi1x12 ,         /* （連携用）保険種類記号予備１＿１２ */
     zrnhokensyuruikigouyobi1x13 ,         /* （連携用）保険種類記号予備１＿１３ */
     zrnhokensyuruikigouyobi1x14 ,         /* （連携用）保険種類記号予備１＿１４ */
     zrnhokensyuruikigouyobi1x15 ,         /* （連携用）保険種類記号予備１＿１５ */
     zrnhokensyuruikigouyobi2x1 ,         /* （連携用）保険種類記号予備２＿１ */
     zrnhokensyuruikigouyobi2x2 ,         /* （連携用）保険種類記号予備２＿２ */
     zrnhokensyuruikigouyobi2x3 ,         /* （連携用）保険種類記号予備２＿３ */
     zrnhokensyuruikigouyobi2x4 ,         /* （連携用）保険種類記号予備２＿４ */
     zrnhokensyuruikigouyobi2x5 ,         /* （連携用）保険種類記号予備２＿５ */
     zrnhokensyuruikigouyobi2x6 ,         /* （連携用）保険種類記号予備２＿６ */
     zrnhokensyuruikigouyobi2x7 ,         /* （連携用）保険種類記号予備２＿７ */
     zrnhokensyuruikigouyobi2x8 ,         /* （連携用）保険種類記号予備２＿８ */
     zrnhokensyuruikigouyobi2x9 ,         /* （連携用）保険種類記号予備２＿９ */
     zrnhokensyuruikigouyobi2x10 ,         /* （連携用）保険種類記号予備２＿１０ */
     zrnhokensyuruikigouyobi3x1 ,         /* （連携用）保険種類記号予備３＿１ */
     zrnhokensyuruikigouyobi3x2 ,         /* （連携用）保険種類記号予備３＿２ */
     zrnhokensyuruikigouyobi3x3 ,         /* （連携用）保険種類記号予備３＿３ */
     zrnhokensyuruikigouyobi3x4 ,         /* （連携用）保険種類記号予備３＿４ */
     zrnhokensyuruikigouyobi3x5 ,         /* （連携用）保険種類記号予備３＿５ */
     zrnhokensyuruikigouyobi3x6 ,         /* （連携用）保険種類記号予備３＿６ */
     zrnhokensyuruikigouyobi3x7 ,         /* （連携用）保険種類記号予備３＿７ */
     zrnhokensyuruikigouyobi3x8 ,         /* （連携用）保険種類記号予備３＿８ */
     zrnhokensyuruikigouyobi3x9 ,         /* （連携用）保険種類記号予備３＿９ */
     zrnhokensyuruikigouyobi3x10 ,         /* （連携用）保険種類記号予備３＿１０ */
     zrnkeiyakuymd ,         /* （連携用）契約日 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnsyoumetucd ,         /* （連携用）消滅コード */
     zrnjikaipjyuutouym ,         /* （連携用）次回Ｐ充当年月 */
     zrnharaikomip ,         /* （連携用）払込Ｐ */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrnzennyknmonth ,         /* （連携用）前回入金月数 */
     zrnzenyuukinymd ,         /* （連携用）前回入金年月日 */
     zrnjidoukousinhyouji ,         /* （連携用）自動更新表示 */
     zrntenkanhyouji ,         /* （連携用）転換表示 */
     zrnhosyouikkatumnoshyouji ,         /* （連携用）保障一括見直表示 */
     zrnyobi01xv40 ,         /* （連携用）予備０１＿Ｖ４０ */
     zrntkkzkp ,         /* （連携用）特約継続Ｐ */
     zrnkeizokuphurikaekngk ,         /* （連携用）継続Ｐ振替金額 */
     zrnkeizokuphurikaekaisiym ,         /* （連携用）継続Ｐ振替開始年月 */
     zrnharaikomipannaisaikaiym ,         /* （連携用）払込Ｐ案内再開年月 */
     zrntkkzkkouryokukaisiymd ,         /* （連携用）特約継続効力開始年月日 */
     zrnhrimngtkykpjyuutouhoukbn ,         /* （連携用）払満後特約Ｐ充当方法区分 */
     zrnjkitkpjytym ,         /* （連携用）次回特約Ｐ充当年月 */
     zrnitijibrzugktkp ,         /* （連携用）一時払増額特約Ｐ */
     zrnpazukarikingk ,         /* （連携用）Ｐ預り金額 */
     zrnzennoukbn ,         /* （連携用）前納区分 */
     zrnzennoukaisiymd ,         /* （連携用）前納開始年月日 */
     zrnzennounyuukinymd ,         /* （連携用）前納入金年月日 */
     zrnyokukipbunruicd ,         /* （連携用）翌期Ｐ分類コード */
     zrnmisyoricd1 ,         /* （連携用）未処理コード１ */
     zrnmisyoricd2 ,         /* （連携用）未処理コード２ */
     zrnmisyoricd3 ,         /* （連携用）未処理コード３ */
     zrnmisyoricd4 ,         /* （連携用）未処理コード４ */
     zrnmisyoricd5 ,         /* （連携用）未処理コード５ */
     zrnmisyoricd6 ,         /* （連携用）未処理コード６ */
     zrnmisyoricd7 ,         /* （連携用）未処理コード７ */
     zrnmisyoricd8 ,         /* （連携用）未処理コード８ */
     zrnmisyoricd9 ,         /* （連携用）未処理コード９ */
     zrnmisyoricd10 ,         /* （連携用）未処理コード１０ */
     zrnyobi02xv39 ,         /* （連携用）予備０２＿Ｖ３９ */
     zrnkbnkeiriyousegmentkbn ,         /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn ,         /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd ,         /* （連携用）数理種類コード */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnkeiyakunendo ,         /* （連携用）契約年度 */
     zrnkeiyakum ,         /* （連携用）契約月 */
     zrnharaikatakbn ,         /* （連携用）払方区分 */
     zrniktyknndp ,         /* （連携用）一括払翌年度保険料 */
     zrnkigetumaenyknyknndp ,         /* （連携用）期月前入金翌年度保険料 */
     zrnyknndpkei ,         /* （連携用）翌年度保険料合計 */
     zrnyobi03xn15 ,         /* （連携用）予備０３＿Ｎ１５ */
     zrnyobi04xv23           /* （連携用）予備０４＿Ｖ２３ */
FROM ZT_KessanYokukiPRn_Z;