CREATE VIEW ZT_SkSeirituRituTy AS SELECT
     ztyeigyouhonbusisyacd ,         /* （中継用）営業本部支社コード */
     ztysisyanm ,         /* （中継用）支社名 */
     ztysosikicd ,         /* （中継用）組織コード */
     ztykanjisosikinm20 ,         /* （中継用）漢字組織名（２０文字） */
     ztyatukaisyadrtenhyouji ,         /* （中継用）扱者代理店表示 */
     ztyatukaikojincd ,         /* （中継用）扱者個人コード */
     ztytansyukukjatukaisyanm ,         /* （中継用）短縮漢字扱者名 */
     ztymosno ,         /* （中継用）申込番号 */
     ztyknjhhknmei ,         /* （中継用）漢字被保険者名 */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztymosym ,         /* （中継用）申込月度 */
     ztymosnyuuryokuymd ,         /* （中継用）申込入力年月日 */
     ztymoskbn ,         /* （中継用）申込区分 */
     ztymossyoumetukbn ,         /* （中継用）申込消滅区分 */
     ztymossyumtkktymd ,         /* （中継用）申込消滅確定年月日 */
     ztykurikosiriyuukbn ,         /* （中継用）繰越理由区分 */
     ztynyknzumihyouji ,         /* （中継用）入金済表示 */
     ztynyknjkkbn ,         /* （中継用）入金状況区分 */
     ztyketjkkbn ,         /* （中継用）決定状況区分 */
     ztydakuhiktjyoutaikbn ,         /* （中継用）諾否決定状態区分 */
     ztykokutiymd ,         /* （中継用）告知年月日 */
     ztyhjykktkbn ,         /* （中継用）報状告知区分 */
     ztytokuteikanikokutikbn ,         /* （中継用）特定簡易告知区分 */
     ztydakuhikettikekkacd ,         /* （中継用）諾否決定結果コード */
     ztysinhsys ,         /* （中継用）新保障Ｓ */
     ztyjyunhsys ,         /* （中継用）純保障Ｓ */
     ztyhsys ,         /* （中継用）保障Ｓ */
     ztysoukensuu ,         /* （中継用）総件数 */
     ztytoukeihknsyruikbn ,         /* （中継用）統計用保険種類区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztykykktaikbn ,         /* （中継用）契約形態区分 */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztytokusyujimutoriatukaikbn ,         /* （中継用）特殊事務取扱区分 */
     ztykihonhubi ,         /* （中継用）基本不備 */
     ztysphubi ,         /* （中継用）ＳＰ不備 */
     ztysseigenhubi ,         /* （中継用）Ｓ制限不備 */
     ztynayosehumei ,         /* （中継用）名寄不明 */
     ztytuusangendoover ,         /* （中継用）通算限度オーバー */
     ztymosketteihoryuu ,         /* （中継用）申込決定保留 */
     ztykykkakjissityuu ,         /* （中継用）契約確認実施中 */
     ztykktketteihoryuu ,         /* （中継用）告知決定保留 */
     ztyhonsyakethoryuu ,         /* （中継用）本社決定保留 */
     ztyseiymdhubi ,         /* （中継用）生年月日不備 */
     ztyphusoku ,         /* （中継用）Ｐ不足 */
     ztysrhuketyu ,         /* （中継用）成立保留受付中 */
     ztypkakin ,         /* （中継用）Ｐ過金 */
     ztymostoutyakuymd ,         /* （中継用）申込書到着年月日 */
     ztykkttoutyakuymd ,         /* （中継用）告知書到着年月日 */
     ztysakuseiymd ,         /* （中継用）作成日 */
     ztysyokaipnyuknhuhukbn2 ,         /* （中継用）初回Ｐ入金方法区分（２文字） */
     ztysyokaiharaikomip ,         /* （中継用）初回払込Ｐ */
     ztyryousyuuymd ,         /* （中継用）領収年月日 */
     ztykeiyakukakuninsyuruikbn ,         /* （中継用）契約確認種類区分 */
     ztykykkakjkkbn1 ,         /* （中継用）契約確認状況区分（1文字） */
     ztymusymd ,         /* （中継用）申込年月日 */
     ztymossyosakuseiymd ,         /* （中継用）申込書作成年月日 */
     ztysyosakuseiymd ,         /* （中継用）証券作成年月日 */
     ztykjkyknm ,         /* （中継用）漢字契約者名 */
     ztyknkyknm18 ,         /* （中継用）カナ契約者名（１８文字） */
     ztyseirituyoukihontikucd ,         /* （中継用）成立率用基本地区コード */
     ztymosksnym ,         /* （中継用）申込起算年月 */
     ztyyohurimiryou ,         /* （中継用）預振未了 */
     ztycreditmiryou ,         /* （中継用）クレカ未了 */
     ztykzktrkservicekbn ,         /* （中継用）ご家族登録サービス区分 */
     ztykykdrtkykarihyj ,         /* （中継用）契約者代理特約有表示 */
     ztystdairiseikyuutkykarihyj ,         /* （中継用）指定代理請求特約有表示 */
     ztyyakkanjyuryouhoukbn ,         /* （中継用）約款受領方法区分 */
     ztyyakkanbunsyono ,         /* （中継用）約款文書番号 */
     ztyyobiv37 ,         /* （中継用）予備項目Ｖ３７ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SkSeirituRituTy_Z;