CREATE VIEW BM_RateW AS SELECT
     palhokensyuruikigou ,         /* ＰＡＬ保険種類記号 */
     palhokensyuruikigousdicode ,         /* ＰＡＬ保険種類記号世代コード */
     palyoteiriritu ,         /* ＰＡＬ予定利率 */
     palpmencode ,         /* ＰＡＬＰ免コード */
     palharaikomikaisuu ,         /* ＰＡＬ払込回数 */
     palhhknsei ,         /* ＰＡＬ被保険者性別 */
     palkeiyakujihhknnen ,         /* ＰＡＬ契約時被保険者年令 */
     palsaimankihyouji ,         /* ＰＡＬ才満期契約表示 */
     palhokenkikan ,         /* ＰＡＬ保険期間 */
     palpharaikomikikan ,         /* ＰＡＬＰ払込期間 */
     palannaihuyouriyuukbn ,         /* ＰＡＬ案内不要理由区分 */
     ratetuukasyukbn ,         /* レート用通貨種類区分 */
     ratedai1hknkkn ,         /* レート用第１保険期間 */
     wrate00 ,         /* Ｗレート００ */
     wrate01 ,         /* Ｗレート０１ */
     wrate02 ,         /* Ｗレート０２ */
     wrate03 ,         /* Ｗレート０３ */
     wrate04 ,         /* Ｗレート０４ */
     wrate05 ,         /* Ｗレート０５ */
     wrate06 ,         /* Ｗレート０６ */
     wrate07 ,         /* Ｗレート０７ */
     wrate08 ,         /* Ｗレート０８ */
     wrate09 ,         /* Ｗレート０９ */
     wrate10 ,         /* Ｗレート１０ */
     wrate11 ,         /* Ｗレート１１ */
     wrate12 ,         /* Ｗレート１２ */
     wrate13 ,         /* Ｗレート１３ */
     wrate14 ,         /* Ｗレート１４ */
     wrate15 ,         /* Ｗレート１５ */
     wrate16 ,         /* Ｗレート１６ */
     wrate17 ,         /* Ｗレート１７ */
     wrate18 ,         /* Ｗレート１８ */
     wrate19 ,         /* Ｗレート１９ */
     wrate20 ,         /* Ｗレート２０ */
     wrate21 ,         /* Ｗレート２１ */
     wrate22 ,         /* Ｗレート２２ */
     wrate23 ,         /* Ｗレート２３ */
     wrate24 ,         /* Ｗレート２４ */
     wrate25 ,         /* Ｗレート２５ */
     wrate26 ,         /* Ｗレート２６ */
     wrate27 ,         /* Ｗレート２７ */
     wrate28 ,         /* Ｗレート２８ */
     wrate29 ,         /* Ｗレート２９ */
     wrate30 ,         /* Ｗレート３０ */
     wrate31 ,         /* Ｗレート３１ */
     wrate32 ,         /* Ｗレート３２ */
     wrate33 ,         /* Ｗレート３３ */
     wrate34 ,         /* Ｗレート３４ */
     wrate35 ,         /* Ｗレート３５ */
     wrate36 ,         /* Ｗレート３６ */
     wrate37 ,         /* Ｗレート３７ */
     wrate38 ,         /* Ｗレート３８ */
     wrate39 ,         /* Ｗレート３９ */
     wrate40 ,         /* Ｗレート４０ */
     wrate41 ,         /* Ｗレート４１ */
     wrate42 ,         /* Ｗレート４２ */
     wrate43 ,         /* Ｗレート４３ */
     wrate44 ,         /* Ｗレート４４ */
     wrate45 ,         /* Ｗレート４５ */
     wrate46 ,         /* Ｗレート４６ */
     wrate47 ,         /* Ｗレート４７ */
     wrate48 ,         /* Ｗレート４８ */
     wrate49 ,         /* Ｗレート４９ */
     wrate50 ,         /* Ｗレート５０ */
     wrate51 ,         /* Ｗレート５１ */
     wrate52 ,         /* Ｗレート５２ */
     wrate53 ,         /* Ｗレート５３ */
     wrate54 ,         /* Ｗレート５４ */
     wrate55 ,         /* Ｗレート５５ */
     wrate56 ,         /* Ｗレート５６ */
     wrate57 ,         /* Ｗレート５７ */
     wrate58 ,         /* Ｗレート５８ */
     wrate59 ,         /* Ｗレート５９ */
     wrate60 ,         /* Ｗレート６０ */
     wrate61 ,         /* Ｗレート６１ */
     wrate62 ,         /* Ｗレート６２ */
     wrate63 ,         /* Ｗレート６３ */
     wrate64 ,         /* Ｗレート６４ */
     wrate65 ,         /* Ｗレート６５ */
     wrate66 ,         /* Ｗレート６６ */
     wrate67 ,         /* Ｗレート６７ */
     wrate68 ,         /* Ｗレート６８ */
     wrate69 ,         /* Ｗレート６９ */
     wrate70 ,         /* Ｗレート７０ */
     wrate71 ,         /* Ｗレート７１ */
     wrate72 ,         /* Ｗレート７２ */
     wrate73 ,         /* Ｗレート７３ */
     wrate74 ,         /* Ｗレート７４ */
     wrate75 ,         /* Ｗレート７５ */
     wrate76 ,         /* Ｗレート７６ */
     wrate77 ,         /* Ｗレート７７ */
     wrate78 ,         /* Ｗレート７８ */
     wrate79 ,         /* Ｗレート７９ */
     wrate80 ,         /* Ｗレート８０ */
     wrate81 ,         /* Ｗレート８１ */
     wrate82 ,         /* Ｗレート８２ */
     wrate83 ,         /* Ｗレート８３ */
     wrate84 ,         /* Ｗレート８４ */
     wrate85 ,         /* Ｗレート８５ */
     wrate86 ,         /* Ｗレート８６ */
     wrate87 ,         /* Ｗレート８７ */
     wrate88 ,         /* Ｗレート８８ */
     wrate89 ,         /* Ｗレート８９ */
     wrate90 ,         /* Ｗレート９０ */
     wrate91 ,         /* Ｗレート９１ */
     wrate92 ,         /* Ｗレート９２ */
     wrate93 ,         /* Ｗレート９３ */
     wrate94 ,         /* Ｗレート９４ */
     wrate95 ,         /* Ｗレート９５ */
     wrate96 ,         /* Ｗレート９６ */
     wrate97 ,         /* Ｗレート９７ */
     wrate98 ,         /* Ｗレート９８ */
     wrate99 ,         /* Ｗレート９９ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BM_RateW_Z;