CREATE VIEW IT_KhShrRireki AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     henkousikibetukey ,         /* 変更識別キー */
     shrymd ,         /* 支払日 */
     shrsyoriymd ,         /* 支払処理日 */
     shrsyorikbn ,         /* 支払処理区分 */
     torikesiflg ,         /* 取消フラグ */
     torikesiymd ,         /* 取消日 */
     syoruiukeymd ,         /* 書類受付日 */
     kouryokuhasseiymd ,         /* 効力発生日 */
     shrtienrskkisanymd ,         /* 支払遅延利息起算日 */
     tienrsknissuu ,         /* 遅延利息日数 */
     sinsagendokknkbn ,         /* 審査限度期間区分 */
     rikoukityuutuudannissuu ,         /* 履行期中断日数 */
     zeitratkikbn ,         /* 税取扱区分 */
     gsbunritaisyou ,         /* 源泉分離課税対象 */
     yenshrtkumu ,         /* 円支払特約有無 */
     kyktuukasyu ,         /* 契約通貨種類 */
     shrgkkei ,         /* 支払額合計 */
     shrgkkei$ ,         /* 支払額合計(通貨型) */
     syushrgkkeisyukbn ,         /* 主たる支払額小計種類区分 */
     syushrgkkei ,         /* 主たる支払額小計 */
     syushrgkkei$ ,         /* 主たる支払額小計(通貨型) */
     mikeikap ,         /* 未経過保険料 */
     mikeikap$ ,         /* 未経過保険料(通貨型) */
     haitoukin ,         /* 配当金 */
     haitoukin$ ,         /* 配当金(通貨型) */
     sonotaseisangk ,         /* その他精算額 */
     sonotaseisangk$ ,         /* その他精算額(通貨型) */
     gstszeigk ,         /* 源泉徴収税額 */
     gstszeigk$ ,         /* 源泉徴収税額(通貨型) */
     shrtienrsk ,         /* 支払遅延利息 */
     shrtienrsk$ ,         /* 支払遅延利息(通貨型) */
     shrtuukasyu ,         /* 支払通貨種類 */
     shrtuukashrgkgoukei ,         /* 支払通貨支払額合計 */
     shrtuukashrgkgoukei$ ,         /* 支払通貨支払額合計(通貨型) */
     shrtuukasyushrgkkei ,         /* 支払通貨主たる支払額小計 */
     shrtuukasyushrgkkei$ ,         /* 支払通貨主たる支払額小計(通貨型) */
     shrtuukahaitoukin ,         /* 支払通貨配当金 */
     shrtuukahaitoukin$ ,         /* 支払通貨配当金(通貨型) */
     shrtuukasonotaseisangk ,         /* 支払通貨その他精算額 */
     shrtuukasonotaseisangk$ ,         /* 支払通貨その他精算額(通貨型) */
     shrtuukagstszeigk ,         /* 支払通貨源泉徴収税額 */
     shrtuukagstszeigk$ ,         /* 支払通貨源泉徴収税額(通貨型) */
     shrtuukashrtienrsk ,         /* 支払通貨支払遅延利息 */
     shrtuukashrtienrsk$ ,         /* 支払通貨支払遅延利息(通貨型) */
     yenshrgkgoukei ,         /* 円換算支払額合計 */
     yenshrgkgoukei$ ,         /* 円換算支払額合計(通貨型) */
     yensyushrgkkei ,         /* 円換算主たる支払額小計 */
     yensyushrgkkei$ ,         /* 円換算主たる支払額小計(通貨型) */
     yenkansanhaitoukin ,         /* 円換算配当金 */
     yenkansanhaitoukin$ ,         /* 円換算配当金(通貨型) */
     yenkansansonotaseisangk ,         /* 円換算その他精算額 */
     yenkansansonotaseisangk$ ,         /* 円換算その他精算額(通貨型) */
     yenmikeikap ,         /* 円換算未経過保険料 */
     yenmikeikap$ ,         /* 円換算未経過保険料(通貨型) */
     yengstszeigk ,         /* 円換算源泉徴収税額 */
     yengstszeigk$ ,         /* 円換算源泉徴収税額(通貨型) */
     yengstszeigknationaltax ,         /* 円換算源泉徴収税額（国税） */
     yengstszeigknationaltax$ ,         /* 円換算源泉徴収税額（国税）(通貨型) */
     yengstszeigklocaltax ,         /* 円換算源泉徴収税額（地方税） */
     yengstszeigklocaltax$ ,         /* 円換算源泉徴収税額（地方税）(通貨型) */
     nztodouhukencd ,         /* 納税先都道府県コード */
     yenshrtienrsk ,         /* 円換算支払遅延利息 */
     yenshrtienrsk$ ,         /* 円換算支払遅延利息(通貨型) */
     htykeihi ,         /* 必要経費 */
     htykeihi$ ,         /* 必要経費(通貨型) */
     kztgk ,         /* 課税対象額 */
     kztgk$ ,         /* 課税対象額(通貨型) */
     yenhtykeihi ,         /* 円換算必要経費 */
     yenhtykeihi$ ,         /* 円換算必要経費(通貨型) */
     yenkztgk ,         /* 円換算課税対象額 */
     yenkztgk$ ,         /* 円換算課税対象額(通貨型) */
     shrkwsratekjnymd ,         /* 支払時為替レート基準日 */
     shrkwsrate ,         /* 支払時為替レート */
     zeimukwsratekjnymd ,         /* 税務用為替レート基準日 */
     zeimukwsrate ,         /* 税務用為替レート */
     soukinsakisiteikbn ,         /* 送金先指定区分 */
     soukinsakinmkn ,         /* 送金先氏名（カナ） */
     soukinsakinmkj ,         /* 送金先氏名（漢字） */
     soukinsakiyno ,         /* 送金先郵便番号 */
     soukinsakiadr1kj ,         /* 送金先住所１（漢字） */
     soukinsakiadr2kj ,         /* 送金先住所２（漢字） */
     soukinsakiadr3kj ,         /* 送金先住所３（漢字） */
     kyksyaszknmkn ,         /* 契約者相続人氏名（カナ） */
     kyksyaszknmkj ,         /* 契約者相続人氏名（漢字） */
     kyksyaszkyno ,         /* 契約者相続人郵便番号 */
     kyksyaszkadr1kj ,         /* 契約者相続人住所１（漢字） */
     kyksyaszkadr2kj ,         /* 契約者相続人住所２（漢字） */
     kyksyaszkadr3kj ,         /* 契約者相続人住所３（漢字） */
     saikennmkj ,         /* 債権者氏名（漢字） */
     saikennyno ,         /* 債権者郵便番号 */
     saikenadr1kj ,         /* 債権者住所１（漢字） */
     saikenadr2kj ,         /* 債権者住所２（漢字） */
     saikenadr3kj ,         /* 債権者住所３（漢字） */
     inputshrhousiteikbn ,         /* 入力用支払方法指定区分 */
     shrhousiteikbn ,         /* 支払方法指定区分 */
     kzsyuruikbn ,         /* 口座種類区分 */
     bankcd ,         /* 銀行コード */
     sitencd ,         /* 支店コード */
     yokinkbn ,         /* 預金種目区分 */
     kouzano ,         /* 口座番号 */
     kzdoukbn ,         /* 口座名義人同一区分 */
     kzmeiginmkn ,         /* 口座名義人氏名（カナ） */
     kykmnmeigibangou ,         /* 契約者ＭＮ名義番号 */
     uktmnmeigibangou ,         /* 受取人ＭＮ名義番号 */
     shrtysysyuruikbn ,         /* 支払調書種類区分 */
     denrenno ,         /* 伝票データ連番 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     yenshrkykhtykeihi ,         /* 円換算支払時契約者必要経費 */
     yenshrkykhtykeihi$ ,         /* 円換算支払時契約者必要経費(通貨型) */
     kykhnkkaisuu ,         /* 契約者変更回数 */
     shrmikeikap ,         /* 支払通貨未経過保険料 */
     shrmikeikap$ ,         /* 支払通貨未経過保険料(通貨型) */
     zennomikeikap ,         /* 前納未経過保険料 */
     zennomikeikap$ ,         /* 前納未経過保険料(通貨型) */
     shrzennomikeikap ,         /* 支払通貨前納未経過保険料 */
     shrzennomikeikap$ ,         /* 支払通貨前納未経過保険料(通貨型) */
     yenzennomikeikap ,         /* 円換算前納未経過保険料 */
     yenzennomikeikap$ ,         /* 円換算前納未経過保険料(通貨型) */
     zitkazukarikingksiteituuka ,         /* 税適預り金額（指定通貨） */
     zitkazukarikingksiteituuka$ ,         /* 税適預り金額（指定通貨）(通貨型) */
     zitkazukarikingkyen ,         /* 税適預り金額（円貨） */
     zitkazukarikingkyen$ ,         /* 税適預り金額（円貨）(通貨型) */
     shrazukarikingk ,         /* 支払通貨預り金額 */
     shrazukarikingk$ ,         /* 支払通貨預り金額(通貨型) */
     yenazukarikingk ,         /* 円換算預り金額 */
     yenazukarikingk$ ,         /* 円換算預り金額(通貨型) */
     sonotahaitoukin ,         /* その他配当金 */
     sonotahaitoukin$ ,         /* その他配当金(通貨型) */
     shrtuukasonotahaitoukin ,         /* 支払通貨その他配当金 */
     shrtuukasonotahaitoukin$ ,         /* 支払通貨その他配当金(通貨型) */
     yensonotahaitoukin ,         /* 円換算その他配当金 */
     yensonotahaitoukin$ ,         /* 円換算その他配当金(通貨型) */
     krkgk ,         /* 仮受金額 */
     krkgk$ ,         /* 仮受金額(通貨型) */
     shrkrkgk ,         /* 支払通貨仮受金額 */
     shrkrkgk$ ,         /* 支払通貨仮受金額(通貨型) */
     yenkrkgk ,         /* 円換算仮受金額 */
     yenkrkgk$ ,         /* 円換算仮受金額(通貨型) */
     zeitekiazukarikinkjumu ,         /* 税適預り金計上有無 */
     gaikashrkwsratekjnymd ,         /* 外貨支払時為替レート基準日 */
     gaikashrkwsrate ,         /* 外貨支払時為替レート */
     kaiyakuhrkngkkeisiteituuka ,         /* 解約返戻金額合計（指定通貨） */
     kaiyakuhrkngkkeisiteituuka$ ,         /* 解約返戻金額合計（指定通貨）(通貨型) */
     shrtuukakaiyakuhrkngkkei ,         /* 支払通貨解約返戻金額合計 */
     shrtuukakaiyakuhrkngkkei$ ,         /* 支払通貨解約返戻金額合計(通貨型) */
     kaiyakuhrkngkkeiyen ,         /* 解約返戻金額合計（円貨） */
     kaiyakuhrkngkkeiyen$ ,         /* 解約返戻金額合計（円貨）(通貨型) */
     sonotashrkngksiteituuka ,         /* その他支払金額（指定通貨） */
     sonotashrkngksiteituuka$ ,         /* その他支払金額（指定通貨）(通貨型) */
     shrtuukasonotashrkngk ,         /* 支払通貨その他支払金額 */
     shrtuukasonotashrkngk$ ,         /* 支払通貨その他支払金額(通貨型) */
     sonotashrkngkyen ,         /* その他支払金額（円貨） */
     sonotashrkngkyen$ ,         /* その他支払金額（円貨）(通貨型) */
     yensynykngk ,         /* 円換算収入金額 */
     yensynykngk$ ,         /* 円換算収入金額(通貨型) */
     shrtysykurikosiyouhi           /* 支払調書繰越要否 */
FROM IT_KhShrRireki_Z;