CREATE VIEW ZT_TtdkKanTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztytyouhyouymdwa ,         /* （中継用）帳票作成日（和暦） */
     ztysyono ,         /* （中継用）証券番号 */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztytantousitukbn ,         /* （中継用）担当室区分 */
     ztysyodouhuukbn ,         /* （中継用）証券同封区分 */
     ztysikibetuno ,         /* （中継用）識別番号 */
     ztyyobiv21 ,         /* （中継用）予備項目Ｖ２１ */
     ztyshskyno ,         /* （中継用）送付先郵便番号 */
     ztyshskadr1kj ,         /* （中継用）送付先住所１（漢字） */
     ztyshskadr2kj ,         /* （中継用）送付先住所２（漢字） */
     ztyshskadr3kj ,         /* （中継用）送付先住所３（漢字） */
     ztyshsnmkjttdk ,         /* （中継用）送付先名（漢字）（手続完了） */
     ztyshsnmkjttdk2 ,         /* （中継用）送付先名（漢字）（手続完了）２ */
     ztyyobiv3 ,         /* （中継用）予備項目Ｖ３ */
     ztytawyno ,         /* （中継用）問合せ先郵便番号 */
     ztytawadr1kj ,         /* （中継用）問合せ先住所１（漢字） */
     ztytawadr2kj ,         /* （中継用）問合せ先住所２（漢字） */
     ztytoiawasekaisyanmkj ,         /* （中継用）問合せ先会社名（漢字） */
     ztytawsosikikj ,         /* （中継用）問合せ先組織名（漢字） */
     ztytawtelnov14 ,         /* （中継用）問合せ先電話番号Ｖ１４ */
     ztytawteluktkkanou1x18keta ,         /* （中継用）問合せ先電話受付可能時間１（１８桁） */
     ztytawteluktkkanou2x18keta ,         /* （中継用）問合せ先電話受付可能時間２（１８桁） */
     ztyyobiv26 ,         /* （中継用）予備項目Ｖ２６ */
     ztytetudukisyunm ,         /* （中継用）手続種類名 */
     ztysyokakmngnumkbn ,         /* （中継用）証券確認文言有無区分 */
     ztysyono2 ,         /* （中継用）証券番号２ */
     ztykyknmkj ,         /* （中継用）契約者名（漢字） */
     ztyhhknnmkj ,         /* （中継用）被保険者名（漢字） */
     ztyyobiv28 ,         /* （中継用）予備項目Ｖ２８ */
     ztyttdknaiyou1 ,         /* （中継用）手続内容１ */
     ztyttdknaiyou2 ,         /* （中継用）手続内容２ */
     ztyttdknaiyou3 ,         /* （中継用）手続内容３ */
     ztyttdknaiyou4 ,         /* （中継用）手続内容４ */
     ztyttdknaiyou5 ,         /* （中継用）手続内容５ */
     ztyttdknaiyou6 ,         /* （中継用）手続内容６ */
     ztyttdknaiyou7 ,         /* （中継用）手続内容７ */
     ztyttdknaiyou8 ,         /* （中継用）手続内容８ */
     ztyttdknaiyou9 ,         /* （中継用）手続内容９ */
     ztyttdknaiyou10 ,         /* （中継用）手続内容１０ */
     ztyttdknaiyouumukbn ,         /* （中継用）手続内容有無区分 */
     ztykykniyuhnkkbn ,         /* （中継用）契約内容変更区分 */
     ztykykniyuhnkymd ,         /* （中継用）契約内容変更日 */
     ztykykniyuhnkinfo ,         /* （中継用）契約内容変更情報 */
     ztykykniyuhnkkngkhugou1 ,         /* （中継用）契約内容変更金額明細符号１ */
     ztykykniyuhnkkngk1 ,         /* （中継用）契約内容変更金額１ */
     ztykykniyuhnkkngktuksyu1 ,         /* （中継用）契約内容変更金額通貨種類１ */
     ztykykniyuhnkkngkhugou2 ,         /* （中継用）契約内容変更金額明細符号２ */
     ztykykniyuhnkkngk2 ,         /* （中継用）契約内容変更金額２ */
     ztykykniyuhnkkngktuksyu2 ,         /* （中継用）契約内容変更金額通貨種類２ */
     ztyyobiv102 ,         /* （中継用）予備項目Ｖ１０２ */
     ztysiharaibiwareki ,         /* （中継用）支払日（和暦） */
     ztykaiyakuymdwa ,         /* （中継用）解約日（和暦） */
     ztytekiyou1 ,         /* （中継用）摘要１ */
     ztyshrkngkmeisaihugou1 ,         /* （中継用）支払金額明細符号１ */
     ztyshrgkmeisai1 ,         /* （中継用）支払金額明細１ */
     ztyshrgktuukasyu1 ,         /* （中継用）支払金額通貨種類１ */
     ztybikou1 ,         /* （中継用）備考１ */
     ztytekiyou2 ,         /* （中継用）摘要２ */
     ztyshrkngkmeisaihugou2 ,         /* （中継用）支払金額明細符号２ */
     ztyshrgkmeisai2 ,         /* （中継用）支払金額明細２ */
     ztyshrgktuukasyu2 ,         /* （中継用）支払金額通貨種類２ */
     ztybikou2 ,         /* （中継用）備考２ */
     ztytekiyou3 ,         /* （中継用）摘要３ */
     ztyshrkngkmeisaihugou3 ,         /* （中継用）支払金額明細符号３ */
     ztyshrgkmeisai3 ,         /* （中継用）支払金額明細３ */
     ztyshrgktuukasyu3 ,         /* （中継用）支払金額通貨種類３ */
     ztybikou3 ,         /* （中継用）備考３ */
     ztytekiyou4 ,         /* （中継用）摘要４ */
     ztyshrkngkmeisaihugou4 ,         /* （中継用）支払金額明細符号４ */
     ztyshrgkmeisai4 ,         /* （中継用）支払金額明細４ */
     ztyshrgktuukasyu4 ,         /* （中継用）支払金額通貨種類４ */
     ztybikou4 ,         /* （中継用）備考４ */
     ztytekiyou5 ,         /* （中継用）摘要５ */
     ztyshrkngkmeisaihugou5 ,         /* （中継用）支払金額明細符号５ */
     ztyshrgkmeisai5 ,         /* （中継用）支払金額明細５ */
     ztyshrgktuukasyu5 ,         /* （中継用）支払金額通貨種類５ */
     ztybikou5 ,         /* （中継用）備考５ */
     ztytekiyou6 ,         /* （中継用）摘要６ */
     ztyshrkngkmeisaihugou6 ,         /* （中継用）支払金額明細符号６ */
     ztyshrgkmeisai6 ,         /* （中継用）支払金額明細６ */
     ztyshrgktuukasyu6 ,         /* （中継用）支払金額通貨種類６ */
     ztybikou6 ,         /* （中継用）備考６ */
     ztytekiyou7 ,         /* （中継用）摘要７ */
     ztyshrkngkmeisaihugou7 ,         /* （中継用）支払金額明細符号７ */
     ztyshrgkmeisai7 ,         /* （中継用）支払金額明細７ */
     ztyshrgktuukasyu7 ,         /* （中継用）支払金額通貨種類７ */
     ztybikou7 ,         /* （中継用）備考７ */
     ztytekiyou8 ,         /* （中継用）摘要８ */
     ztyshrkngkmeisaihugou8 ,         /* （中継用）支払金額明細符号８ */
     ztyshrgkmeisai8 ,         /* （中継用）支払金額明細８ */
     ztyshrgktuukasyu8 ,         /* （中継用）支払金額通貨種類８ */
     ztybikou8 ,         /* （中継用）備考８ */
     ztytekiyou9 ,         /* （中継用）摘要９ */
     ztyshrkngkmeisaihugou9 ,         /* （中継用）支払金額明細符号９ */
     ztyshrgkmeisai9 ,         /* （中継用）支払金額明細９ */
     ztyshrgktuukasyu9 ,         /* （中継用）支払金額通貨種類９ */
     ztybikou9 ,         /* （中継用）備考９ */
     ztytekiyou10 ,         /* （中継用）摘要１０ */
     ztyshrkngkmeisaihugou10 ,         /* （中継用）支払金額明細符号１０ */
     ztyshrgkmeisai10 ,         /* （中継用）支払金額明細１０ */
     ztyshrgktuukasyu10 ,         /* （中継用）支払金額通貨種類１０ */
     ztybikou10 ,         /* （中継用）備考１０ */
     ztyshrgkgoukei ,         /* （中継用）支払額合計 */
     ztyshrtuukasyu ,         /* （中継用）支払通貨種類 */
     ztydseisanshrttdknm ,         /* （中継用）Ｄ精算支払手続名 */
     ztyyobiv26x3 ,         /* （中継用）予備項目Ｖ２６＿３ */
     ztybanknmkj ,         /* （中継用）銀行名（漢字） */
     ztysitennmkj ,         /* （中継用）支店名（漢字） */
     ztyyokinkbn ,         /* （中継用）預金種目区分 */
     ztykouzano12keta ,         /* （中継用）口座番号（１２桁） */
     ztykzmeiginmknhan ,         /* （中継用）口座名義人氏名（カナ）（半角） */
     ztykouzasyuruikbn ,         /* （中継用）口座種類区分 */
     ztyyobiv26x2 ,         /* （中継用）予備項目Ｖ２６＿２ */
     ztysynykngk ,         /* （中継用）収入金額 */
     ztysynykngktuukasyu ,         /* （中継用）収入金額通貨種類 */
     ztyhtykeihi ,         /* （中継用）必要経費 */
     ztyhtykeihituukasyu ,         /* （中継用）必要経費通貨種類 */
     ztyshrkyksyahtykeihi ,         /* （中継用）お支払時の契約者の必要経費 */
     ztyshrkykhtykeihituukasyu ,         /* （中継用）お支払時の契約者の必要経費通貨種類 */
     ztygsbnrkzthtykeihi ,         /* （中継用）源泉分離課税対象の必要経費 */
     ztygsbnrkzthtykeihituksyu ,         /* （中継用）源泉分離課税対象の必要経費通貨種類 */
     ztygsbnrkztsaeki ,         /* （中継用）源泉分離課税対象の差益 */
     ztygsbnrkztsaekituksyu ,         /* （中継用）源泉分離課税対象の差益通貨種類 */
     ztyzeimunaiyouhensyuctrlkbn ,         /* （中継用）税務内容編集制御区分 */
     ztyzeimumongonoutkbn ,         /* （中継用）税務文言出力区分 */
     ztyzeimumongon1 ,         /* （中継用）税務文言１ */
     ztyzeimumongon2 ,         /* （中継用）税務文言２ */
     ztyzeimumongon3 ,         /* （中継用）税務文言３ */
     ztyzeimumongon4 ,         /* （中継用）税務文言４ */
     ztyzeimumongon5 ,         /* （中継用）税務文言５ */
     ztyyendthnkzeimuinfohskkbn ,         /* （中継用）円建変更時税務情報補足区分 */
     ztyyobiv36 ,         /* （中継用）予備項目Ｖ３６ */
     ztyosirasehyoudai ,         /* （中継用）お知らせ表題 */
     ztyosirasemongon1 ,         /* （中継用）お知らせ文言１ */
     ztyosirasemongon2 ,         /* （中継用）お知らせ文言２ */
     ztyosirasemongon3 ,         /* （中継用）お知らせ文言３ */
     ztyosirasemongon4 ,         /* （中継用）お知らせ文言４ */
     ztyosirasemongon5 ,         /* （中継用）お知らせ文言５ */
     ztyosirasemongon6 ,         /* （中継用）お知らせ文言６ */
     ztyosirasemongon7 ,         /* （中継用）お知らせ文言７ */
     ztyosirasemongon8 ,         /* （中継用）お知らせ文言８ */
     ztyosirasemongon9 ,         /* （中継用）お知らせ文言９ */
     ztyosirasemongon10 ,         /* （中継用）お知らせ文言１０ */
     ztyosirasemongon11 ,         /* （中継用）お知らせ文言１１ */
     ztyosirasemongon12 ,         /* （中継用）お知らせ文言１２ */
     ztyosirasemongon13 ,         /* （中継用）お知らせ文言１３ */
     ztyosirasemongon14 ,         /* （中継用）お知らせ文言１４ */
     ztyosirasemongon15 ,         /* （中継用）お知らせ文言１５ */
     ztyosirasemongon16 ,         /* （中継用）お知らせ文言１６ */
     ztyosirasemongon17 ,         /* （中継用）お知らせ文言１７ */
     ztyosirasemongon18 ,         /* （中継用）お知らせ文言１８ */
     ztyosirasemongon19 ,         /* （中継用）お知らせ文言１９ */
     ztyosirasemongon20 ,         /* （中継用）お知らせ文言２０ */
     ztyosirasemongon21 ,         /* （中継用）お知らせ文言２１ */
     ztyosirasemongon22 ,         /* （中継用）お知らせ文言２２ */
     ztyosirasemongon23 ,         /* （中継用）お知らせ文言２３ */
     ztyosirasemongon24 ,         /* （中継用）お知らせ文言２４ */
     ztyosirasemongon25 ,         /* （中継用）お知らせ文言２５ */
     ztyosirasemongon26 ,         /* （中継用）お知らせ文言２６ */
     ztyosirasemongon27 ,         /* （中継用）お知らせ文言２７ */
     ztyosirasemongon28 ,         /* （中継用）お知らせ文言２８ */
     ztyosirasemongon29 ,         /* （中継用）お知らせ文言２９ */
     ztyosirasemongon30 ,         /* （中継用）お知らせ文言３０ */
     ztyosirasemongon31 ,         /* （中継用）お知らせ文言３１ */
     ztyosirasemongon32 ,         /* （中継用）お知らせ文言３２ */
     ztyosirasemongon33 ,         /* （中継用）お知らせ文言３３ */
     ztyosirasemongon34 ,         /* （中継用）お知らせ文言３４ */
     ztyosirasemongon35 ,         /* （中継用）お知らせ文言３５ */
     ztyosirasemongon36 ,         /* （中継用）お知らせ文言３６ */
     ztyosirasemongon37 ,         /* （中継用）お知らせ文言３７ */
     ztyosirasemongon38 ,         /* （中継用）お知らせ文言３８ */
     ztyosirasemongon39 ,         /* （中継用）お知らせ文言３９ */
     ztyosirasemongon40 ,         /* （中継用）お知らせ文言４０ */
     ztyosirasemongon41 ,         /* （中継用）お知らせ文言４１ */
     ztyosirasemongon42 ,         /* （中継用）お知らせ文言４２ */
     ztyosirasemongon43 ,         /* （中継用）お知らせ文言４３ */
     ztyosirasemongon44 ,         /* （中継用）お知らせ文言４４ */
     ztyosirasemongon45 ,         /* （中継用）お知らせ文言４５ */
     ztyosirasemongon46 ,         /* （中継用）お知らせ文言４６ */
     ztyosirasemongon47 ,         /* （中継用）お知らせ文言４７ */
     ztyosirasemongon48 ,         /* （中継用）お知らせ文言４８ */
     ztyosirasemongon49 ,         /* （中継用）お知らせ文言４９ */
     ztyosirasemongon50 ,         /* （中継用）お知らせ文言５０ */
     ztyosiraseinjihuyouhyouji ,         /* （中継用）お知らせ印字不要表示 */
     ztyyobiv254 ,         /* （中継用）予備項目Ｖ２５４ */
     ztyshrnaiyouhskmongon1 ,         /* （中継用）支払内容補足文言１ */
     ztyshrnaiyouhskmongon2 ,         /* （中継用）支払内容補足文言２ */
     ztydocumentid ,         /* （中継用）ドキュメントＩＤ */
     ztysksmongonkbn1 ,         /* （中継用）請求書文言区分１ */
     ztysksmongonkbn2 ,         /* （中継用）請求書文言区分２ */
     ztytoritugisyasyozokunm ,         /* （中継用）取次者所属名 */
     ztytoritugisyakjncd ,         /* （中継用）取次者個人コード */
     ztytoritugisyanm ,         /* （中継用）取次者氏名 */
     ztyhozonkkny ,         /* （中継用）保存期間（年） */
     ztytsintelno ,         /* （中継用）通信先電話番号 */
     version ,         /* バージョン */
     ztytrkkzkkbn1 ,         /* （中継用）登録家族区分１ */
     ztytrkkzknmkj1 ,         /* （中継用）登録家族名（漢字）１ */
     ztytrkkzkseiymd1zenkaku ,         /* （中継用）登録家族１人目生年月日 */
     ztytrkkzkyno1 ,         /* （中継用）登録家族郵便番号１ */
     ztytrkkzkadr1kj1 ,         /* （中継用）登録家族住所１（漢字）１　 */
     ztytrkkzkadr2kj1 ,         /* （中継用）登録家族住所２（漢字）１　 */
     ztytrkkzkadr3kj1 ,         /* （中継用）登録家族住所３（漢字）１　 */
     ztytrkkzktelno1 ,         /* （中継用）登録家族電話番号１ */
     ztytrkkzktelnomtrkhyouji1 ,         /* （中継用）登録家族電話番号未登録表示１ */
     ztytrkkzkkbn2 ,         /* （中継用）登録家族区分２ */
     ztytrkkzknmkj2 ,         /* （中継用）登録家族名（漢字）２ */
     ztytrkkzkseiymd2zenkaku ,         /* （中継用）登録家族２人目生年月日 */
     ztytrkkzkyno2 ,         /* （中継用）登録家族郵便番号２ */
     ztytrkkzkadr1kj2 ,         /* （中継用）登録家族住所１（漢字）２　 */
     ztytrkkzkadr2kj2 ,         /* （中継用）登録家族住所２（漢字）２　 */
     ztytrkkzkadr3kj2 ,         /* （中継用）登録家族住所３（漢字）２　 */
     ztytrkkzktelno2 ,         /* （中継用）登録家族電話番号２ */
     ztykykdairinmkj ,         /* （中継用）契約者代理人名（漢字） */
     ztykykomttutkbn ,         /* （中継用）契約者用表通知区分 */
     ztykzkomttutkbn1 ,         /* （中継用）家族１用表通知区分 */
     ztykzkomttutkbn2 ,         /* （中継用）家族２用表通知区分 */
     ztyhhkomttutkbn ,         /* （中継用）被保険者用表通知区分 */
     ztyhhkdromttutkbn ,         /* （中継用）被保険者代理人用表通知区分 */
     ztykykdairiomttutkbn ,         /* （中継用）契約者代理人用表通知区分 */
     ztykykurtutkbn ,         /* （中継用）契約者用裏通知区分 */
     ztykzkurtutkbn1 ,         /* （中継用）家族１用裏通知区分 */
     ztykzkurtutkbn2 ,         /* （中継用）家族２用裏通知区分 */
     ztyhhkdrurtutkbn ,         /* （中継用）被保険者代理人用裏通知区分 */
     ztykykdairiurtutkbn ,         /* （中継用）契約者代理人用裏通知区分 */
     ztykykaistmsgkbn ,         /* （中継用）契約者用挨拶ＭＳＧ区分 */
     ztykzkaistmsgkbn1 ,         /* （中継用）家族１用挨拶ＭＳＧ区分 */
     ztykzkaistmsgkbn2 ,         /* （中継用）家族２用挨拶ＭＳＧ区分 */
     ztyhhkaistmsgkbn ,         /* （中継用）被保険者用挨拶ＭＳＧ区分 */
     ztyhhkdraistmsgkbn ,         /* （中継用）被保険者代理人用挨拶ＭＳＧ区分 */
     ztykykdairiaistmsgkbn ,         /* （中継用）契約者代理人用挨拶ＭＳＧ区分 */
     ztysakujyokzknmkj ,         /* （中継用）削除家族名 */
     ztyttdknaiyoukbn ,         /* （中継用）手続内容区分 */
     ztykzktaisyoukykkbn ,         /* （中継用）家族用対象契約区分 */
     ztyhhkdrtaisyoukykkbn ,         /* （中継用）被保険者代理人用対象契約区分 */
     ztykykdairitaisyoukykkbn ,         /* （中継用）契約者代理人用対象契約区分 */
     ztymoshnkniymsgkbn1 ,         /* （中継用）申込変更内容ＭＳＧ区分１ */
     ztykykmoshnkniymsg2 ,         /* （中継用）契約者用申込変更内容ＭＳＧ区分２ */
     ztykzkmoshnkniymsg21 ,         /* （中継用）家族１用申込変更内容ＭＳＧ区分２ */
     ztykzkmoshnkniymsg22 ,         /* （中継用）家族２用申込変更内容ＭＳＧ区分２ */
     ztyhhkdrmoshnkniymsg2 ,         /* （中継用）被保険者代理人用申込変更内容ＭＳＧ区分２ */
     ztykykdairimoshnkniymsg2 ,         /* （中継用）契約者代理人用申込変更内容ＭＳＧ区分２ */
     ztykykdrmsgkbn ,         /* （中継用）契約者代理ＭＳＧ区分 */
     ztykykhhkdrmsg ,         /* （中継用）契約者用被保険者代理ＭＳＧ区分 */
     ztykzkhhkdrmsg1 ,         /* （中継用）家族１用被保険者代理ＭＳＧ区分 */
     ztykzkhhkdrmsg2 ,         /* （中継用）家族２用被保険者代理ＭＳＧ区分 */
     ztyhhkdrnmkj ,         /* （中継用）被保険者代理人名（漢字） */
     ztyduhubutumsg1 ,         /* （中継用）同封物ＭＳＧ区分１ */
     ztyduhubutumsg2 ,         /* （中継用）同封物ＭＳＧ区分２ */
     ztyduhubutumsg3 ,         /* （中継用）同封物ＭＳＧ区分３ */
     ztyduhubutumsg4 ,         /* （中継用）同封物ＭＳＧ区分４ */
     ztyduhubutumsg5 ,         /* （中継用）同封物ＭＳＧ区分５ */
     ztyduhubutumsg6 ,         /* （中継用）同封物ＭＳＧ区分６ */
     ztyduhubutumsg7 ,         /* （中継用）同封物ＭＳＧ区分７ */
     ztykykigaidhbtmsg1 ,         /* （中継用）契約者以外用同封物ＭＳＧ区分１ */
     ztykykigaidhbtmsg2 ,         /* （中継用）契約者以外用同封物ＭＳＧ区分２ */
     ztykykigaidhbtmsg3 ,         /* （中継用）契約者以外用同封物ＭＳＧ区分３ */
     ztykykigaidhbtmsg4 ,         /* （中継用）契約者以外用同封物ＭＳＧ区分４ */
     ztyyakkankiyakuhunyuuhyouji ,         /* （中継用）約款規約封入表示 */
     ztykyktrktrshuunyuuhyouji ,         /* （中継用）登録チラシ封入表示（契） */
     ztykzktrktrshuunyuuhyouji1 ,         /* （中継用）登録チラシ封入表示（家族１） */
     ztykzktrktrshuunyuuhyouji2 ,         /* （中継用）登録チラシ封入表示（家族２） */
     ztykykdrhuunyuuhyouji ,         /* （中継用）契約者代理封入表示 */
     ztyhhkdrhuunyuuhyouji ,         /* （中継用）被保険者代理封入表示 */
     ztykykdairinmkj2 ,         /* （中継用）契約者代理人名（漢字）２ */
     ztykykdrseiymd ,         /* （中継用）契約者代理人生年月日 */
     ztykykdryno ,         /* （中継用）契約者代理人郵便番号 */
     ztykykdradr1kj ,         /* （中継用）契約者代理人住所１（漢字） */
     ztykykdradr2kj ,         /* （中継用）契約者代理人住所２（漢字） */
     ztykykdradr3kj ,         /* （中継用）契約者代理人住所３（漢字） */
     ztykykdrtelno ,         /* （中継用）契約者代理人電話番号 */
     ztyhhkdrnmkj2 ,         /* （中継用）被保険者代理人名（漢字）２ */
     ztyhhkdrseiymd ,         /* （中継用）被保険者代理人生年月日 */
     ztyhhkdryno ,         /* （中継用）被保険者代理人郵便番号 */
     ztyhhkdradr1kj ,         /* （中継用）被保険者代理人住所１（漢字） */
     ztyhhkdradr2kj ,         /* （中継用）被保険者代理人住所２（漢字） */
     ztyhhkdradr3kj ,         /* （中継用）被保険者代理人住所３（漢字） */
     ztyhhkdrtelno ,         /* （中継用）被保険者代理人電話番号 */
     ztyhhkdrtelnomtrkhyouji ,         /* （中継用）被保険者代理人電話番号未登録表示 */
     ztykhsyono2 ,         /* （中継用）（契約保全）証券番号２ */
     ztykhsyono3 ,         /* （中継用）（契約保全）証券番号３ */
     ztykhsyono4 ,         /* （中継用）（契約保全）証券番号４ */
     ztykhsyono5 ,         /* （中継用）（契約保全）証券番号５ */
     ztykhsyono6 ,         /* （中継用）（契約保全）証券番号６ */
     ztykhsyono7 ,         /* （中継用）（契約保全）証券番号７ */
     ztykhsyono8 ,         /* （中継用）（契約保全）証券番号８ */
     ztykhsyono9 ,         /* （中継用）（契約保全）証券番号９ */
     ztykhsyono10 ,         /* （中継用）（契約保全）証券番号１０ */
     ztykhmosno1 ,         /* （中継用）（契約保全）申込番号１ */
     ztykhmosno2 ,         /* （中継用）（契約保全）申込番号２ */
     ztykhmosno3 ,         /* （中継用）（契約保全）申込番号３ */
     ztykhmosno4 ,         /* （中継用）（契約保全）申込番号４ */
     ztykhmosno5 ,         /* （中継用）（契約保全）申込番号５ */
     ztykhmosno6 ,         /* （中継用）（契約保全）申込番号６ */
     ztykhmosno7 ,         /* （中継用）（契約保全）申込番号７ */
     ztykhmosno8 ,         /* （中継用）（契約保全）申込番号８ */
     ztykhmosno9 ,         /* （中継用）（契約保全）申込番号９ */
     ztykhmosno10 ,         /* （中継用）（契約保全）申込番号１０ */
     ztyhnsnhutouhuunyuuhyouji ,         /* （中継用）返信用封筒封入表示 */
     ztyyobiv204 ,         /* （中継用）予備項目Ｖ２０４ */
     ztyyobiv255x2 ,         /* （中継用）予備項目Ｖ２５５＿２ */
     ztyyobiv255x3 ,         /* （中継用）予備項目Ｖ２５５＿３ */
     ztyyobiv255x4 ,         /* （中継用）予備項目Ｖ２５５＿４ */
     ztyyobiv141 ,         /* （中継用）予備項目Ｖ１４１ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou           /* 更新機能 */
FROM ZT_TtdkKanTy_Z;