CREATE VIEW ZT_RatedRn AS SELECT
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnyoteiriritu ,         /* （連携用）予定利率 */
     zrnpmenkbn ,         /* （連携用）Ｐ免区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhhknsei ,         /* （連携用）被保険者性別 */
     zrnkeiyakujihhknnen ,         /* （連携用）契約時被保険者年令 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrndnendo ,         /* （連携用）Ｄ年度 */
     zrnnaiteikakuteikbn ,         /* （連携用）Ｄレート内定確定区分 */
     zrndrate00 ,         /* （連携用）Ｄレート００ */
     zrndrate01 ,         /* （連携用）Ｄレート０１ */
     zrndrate02 ,         /* （連携用）Ｄレート０２ */
     zrndrate03 ,         /* （連携用）Ｄレート０３ */
     zrndrate04 ,         /* （連携用）Ｄレート０４ */
     zrndrate05 ,         /* （連携用）Ｄレート０５ */
     zrndrate06 ,         /* （連携用）Ｄレート０６ */
     zrndrate07 ,         /* （連携用）Ｄレート０７ */
     zrndrate08 ,         /* （連携用）Ｄレート０８ */
     zrndrate09 ,         /* （連携用）Ｄレート０９ */
     zrndrate10 ,         /* （連携用）Ｄレート１０ */
     zrndrate11 ,         /* （連携用）Ｄレート１１ */
     zrndrate12 ,         /* （連携用）Ｄレート１２ */
     zrndrate13 ,         /* （連携用）Ｄレート１３ */
     zrndrate14 ,         /* （連携用）Ｄレート１４ */
     zrndrate15 ,         /* （連携用）Ｄレート１５ */
     zrndrate16 ,         /* （連携用）Ｄレート１６ */
     zrndrate17 ,         /* （連携用）Ｄレート１７ */
     zrndrate18 ,         /* （連携用）Ｄレート１８ */
     zrndrate19 ,         /* （連携用）Ｄレート１９ */
     zrndrate20 ,         /* （連携用）Ｄレート２０ */
     zrndrate21 ,         /* （連携用）Ｄレート２１ */
     zrndrate22 ,         /* （連携用）Ｄレート２２ */
     zrndrate23 ,         /* （連携用）Ｄレート２３ */
     zrndrate24 ,         /* （連携用）Ｄレート２４ */
     zrndrate25 ,         /* （連携用）Ｄレート２５ */
     zrndrate26 ,         /* （連携用）Ｄレート２６ */
     zrndrate27 ,         /* （連携用）Ｄレート２７ */
     zrndrate28 ,         /* （連携用）Ｄレート２８ */
     zrndrate29 ,         /* （連携用）Ｄレート２９ */
     zrndrate30 ,         /* （連携用）Ｄレート３０ */
     zrndrate31 ,         /* （連携用）Ｄレート３１ */
     zrndrate32 ,         /* （連携用）Ｄレート３２ */
     zrndrate33 ,         /* （連携用）Ｄレート３３ */
     zrndrate34 ,         /* （連携用）Ｄレート３４ */
     zrndrate35 ,         /* （連携用）Ｄレート３５ */
     zrndrate36 ,         /* （連携用）Ｄレート３６ */
     zrndrate37 ,         /* （連携用）Ｄレート３７ */
     zrndrate38 ,         /* （連携用）Ｄレート３８ */
     zrndrate39 ,         /* （連携用）Ｄレート３９ */
     zrndrate40 ,         /* （連携用）Ｄレート４０ */
     zrndrate41 ,         /* （連携用）Ｄレート４１ */
     zrndrate42 ,         /* （連携用）Ｄレート４２ */
     zrndrate43 ,         /* （連携用）Ｄレート４３ */
     zrndrate44 ,         /* （連携用）Ｄレート４４ */
     zrndrate45 ,         /* （連携用）Ｄレート４５ */
     zrndrate46 ,         /* （連携用）Ｄレート４６ */
     zrndrate47 ,         /* （連携用）Ｄレート４７ */
     zrndrate48 ,         /* （連携用）Ｄレート４８ */
     zrndrate49 ,         /* （連携用）Ｄレート４９ */
     zrndrate50 ,         /* （連携用）Ｄレート５０ */
     zrndrate51 ,         /* （連携用）Ｄレート５１ */
     zrndrate52 ,         /* （連携用）Ｄレート５２ */
     zrndrate53 ,         /* （連携用）Ｄレート５３ */
     zrndrate54 ,         /* （連携用）Ｄレート５４ */
     zrndrate55 ,         /* （連携用）Ｄレート５５ */
     zrndrate56 ,         /* （連携用）Ｄレート５６ */
     zrndrate57 ,         /* （連携用）Ｄレート５７ */
     zrndrate58 ,         /* （連携用）Ｄレート５８ */
     zrndrate59 ,         /* （連携用）Ｄレート５９ */
     zrndrate60 ,         /* （連携用）Ｄレート６０ */
     zrndrate61 ,         /* （連携用）Ｄレート６１ */
     zrndrate62 ,         /* （連携用）Ｄレート６２ */
     zrndrate63 ,         /* （連携用）Ｄレート６３ */
     zrndrate64 ,         /* （連携用）Ｄレート６４ */
     zrndrate65 ,         /* （連携用）Ｄレート６５ */
     zrndrate66 ,         /* （連携用）Ｄレート６６ */
     zrndrate67 ,         /* （連携用）Ｄレート６７ */
     zrndrate68 ,         /* （連携用）Ｄレート６８ */
     zrndrate69 ,         /* （連携用）Ｄレート６９ */
     zrndrate70 ,         /* （連携用）Ｄレート７０ */
     zrndrate71 ,         /* （連携用）Ｄレート７１ */
     zrndrate72 ,         /* （連携用）Ｄレート７２ */
     zrndrate73 ,         /* （連携用）Ｄレート７３ */
     zrndrate74 ,         /* （連携用）Ｄレート７４ */
     zrndrate75 ,         /* （連携用）Ｄレート７５ */
     zrndrate76 ,         /* （連携用）Ｄレート７６ */
     zrndrate77 ,         /* （連携用）Ｄレート７７ */
     zrndrate78 ,         /* （連携用）Ｄレート７８ */
     zrndrate79 ,         /* （連携用）Ｄレート７９ */
     zrndrate80 ,         /* （連携用）Ｄレート８０ */
     zrndrate81 ,         /* （連携用）Ｄレート８１ */
     zrndrate82 ,         /* （連携用）Ｄレート８２ */
     zrndrate83 ,         /* （連携用）Ｄレート８３ */
     zrndrate84 ,         /* （連携用）Ｄレート８４ */
     zrndrate85 ,         /* （連携用）Ｄレート８５ */
     zrndrate86 ,         /* （連携用）Ｄレート８６ */
     zrndrate87 ,         /* （連携用）Ｄレート８７ */
     zrndrate88 ,         /* （連携用）Ｄレート８８ */
     zrndrate89 ,         /* （連携用）Ｄレート８９ */
     zrndrate90 ,         /* （連携用）Ｄレート９０ */
     zrndrate91 ,         /* （連携用）Ｄレート９１ */
     zrndrate92 ,         /* （連携用）Ｄレート９２ */
     zrndrate93 ,         /* （連携用）Ｄレート９３ */
     zrndrate94 ,         /* （連携用）Ｄレート９４ */
     zrndrate95 ,         /* （連携用）Ｄレート９５ */
     zrndrate96 ,         /* （連携用）Ｄレート９６ */
     zrndrate97 ,         /* （連携用）Ｄレート９７ */
     zrndrate98 ,         /* （連携用）Ｄレート９８ */
     zrndrate99 ,         /* （連携用）Ｄレート９９ */
     zrnsisadrate00 ,         /* （連携用）死差Ｄレート００ */
     zrnsisadrate01 ,         /* （連携用）死差Ｄレート０１ */
     zrnsisadrate02 ,         /* （連携用）死差Ｄレート０２ */
     zrnsisadrate03 ,         /* （連携用）死差Ｄレート０３ */
     zrnsisadrate04 ,         /* （連携用）死差Ｄレート０４ */
     zrnsisadrate05 ,         /* （連携用）死差Ｄレート０５ */
     zrnsisadrate06 ,         /* （連携用）死差Ｄレート０６ */
     zrnsisadrate07 ,         /* （連携用）死差Ｄレート０７ */
     zrnsisadrate08 ,         /* （連携用）死差Ｄレート０８ */
     zrnsisadrate09 ,         /* （連携用）死差Ｄレート０９ */
     zrnsisadrate10 ,         /* （連携用）死差Ｄレート１０ */
     zrnsisadrate11 ,         /* （連携用）死差Ｄレート１１ */
     zrnsisadrate12 ,         /* （連携用）死差Ｄレート１２ */
     zrnsisadrate13 ,         /* （連携用）死差Ｄレート１３ */
     zrnsisadrate14 ,         /* （連携用）死差Ｄレート１４ */
     zrnsisadrate15 ,         /* （連携用）死差Ｄレート１５ */
     zrnsisadrate16 ,         /* （連携用）死差Ｄレート１６ */
     zrnsisadrate17 ,         /* （連携用）死差Ｄレート１７ */
     zrnsisadrate18 ,         /* （連携用）死差Ｄレート１８ */
     zrnsisadrate19 ,         /* （連携用）死差Ｄレート１９ */
     zrnsisadrate20 ,         /* （連携用）死差Ｄレート２０ */
     zrnsisadrate21 ,         /* （連携用）死差Ｄレート２１ */
     zrnsisadrate22 ,         /* （連携用）死差Ｄレート２２ */
     zrnsisadrate23 ,         /* （連携用）死差Ｄレート２３ */
     zrnsisadrate24 ,         /* （連携用）死差Ｄレート２４ */
     zrnsisadrate25 ,         /* （連携用）死差Ｄレート２５ */
     zrnsisadrate26 ,         /* （連携用）死差Ｄレート２６ */
     zrnsisadrate27 ,         /* （連携用）死差Ｄレート２７ */
     zrnsisadrate28 ,         /* （連携用）死差Ｄレート２８ */
     zrnsisadrate29 ,         /* （連携用）死差Ｄレート２９ */
     zrnsisadrate30 ,         /* （連携用）死差Ｄレート３０ */
     zrnsisadrate31 ,         /* （連携用）死差Ｄレート３１ */
     zrnsisadrate32 ,         /* （連携用）死差Ｄレート３２ */
     zrnsisadrate33 ,         /* （連携用）死差Ｄレート３３ */
     zrnsisadrate34 ,         /* （連携用）死差Ｄレート３４ */
     zrnsisadrate35 ,         /* （連携用）死差Ｄレート３５ */
     zrnsisadrate36 ,         /* （連携用）死差Ｄレート３６ */
     zrnsisadrate37 ,         /* （連携用）死差Ｄレート３７ */
     zrnsisadrate38 ,         /* （連携用）死差Ｄレート３８ */
     zrnsisadrate39 ,         /* （連携用）死差Ｄレート３９ */
     zrnsisadrate40 ,         /* （連携用）死差Ｄレート４０ */
     zrnsisadrate41 ,         /* （連携用）死差Ｄレート４１ */
     zrnsisadrate42 ,         /* （連携用）死差Ｄレート４２ */
     zrnsisadrate43 ,         /* （連携用）死差Ｄレート４３ */
     zrnsisadrate44 ,         /* （連携用）死差Ｄレート４４ */
     zrnsisadrate45 ,         /* （連携用）死差Ｄレート４５ */
     zrnsisadrate46 ,         /* （連携用）死差Ｄレート４６ */
     zrnsisadrate47 ,         /* （連携用）死差Ｄレート４７ */
     zrnsisadrate48 ,         /* （連携用）死差Ｄレート４８ */
     zrnsisadrate49 ,         /* （連携用）死差Ｄレート４９ */
     zrnsisadrate50 ,         /* （連携用）死差Ｄレート５０ */
     zrnsisadrate51 ,         /* （連携用）死差Ｄレート５１ */
     zrnsisadrate52 ,         /* （連携用）死差Ｄレート５２ */
     zrnsisadrate53 ,         /* （連携用）死差Ｄレート５３ */
     zrnsisadrate54 ,         /* （連携用）死差Ｄレート５４ */
     zrnsisadrate55 ,         /* （連携用）死差Ｄレート５５ */
     zrnsisadrate56 ,         /* （連携用）死差Ｄレート５６ */
     zrnsisadrate57 ,         /* （連携用）死差Ｄレート５７ */
     zrnsisadrate58 ,         /* （連携用）死差Ｄレート５８ */
     zrnsisadrate59 ,         /* （連携用）死差Ｄレート５９ */
     zrnsisadrate60 ,         /* （連携用）死差Ｄレート６０ */
     zrnsisadrate61 ,         /* （連携用）死差Ｄレート６１ */
     zrnsisadrate62 ,         /* （連携用）死差Ｄレート６２ */
     zrnsisadrate63 ,         /* （連携用）死差Ｄレート６３ */
     zrnsisadrate64 ,         /* （連携用）死差Ｄレート６４ */
     zrnsisadrate65 ,         /* （連携用）死差Ｄレート６５ */
     zrnsisadrate66 ,         /* （連携用）死差Ｄレート６６ */
     zrnsisadrate67 ,         /* （連携用）死差Ｄレート６７ */
     zrnsisadrate68 ,         /* （連携用）死差Ｄレート６８ */
     zrnsisadrate69 ,         /* （連携用）死差Ｄレート６９ */
     zrnsisadrate70 ,         /* （連携用）死差Ｄレート７０ */
     zrnsisadrate71 ,         /* （連携用）死差Ｄレート７１ */
     zrnsisadrate72 ,         /* （連携用）死差Ｄレート７２ */
     zrnsisadrate73 ,         /* （連携用）死差Ｄレート７３ */
     zrnsisadrate74 ,         /* （連携用）死差Ｄレート７４ */
     zrnsisadrate75 ,         /* （連携用）死差Ｄレート７５ */
     zrnsisadrate76 ,         /* （連携用）死差Ｄレート７６ */
     zrnsisadrate77 ,         /* （連携用）死差Ｄレート７７ */
     zrnsisadrate78 ,         /* （連携用）死差Ｄレート７８ */
     zrnsisadrate79 ,         /* （連携用）死差Ｄレート７９ */
     zrnsisadrate80 ,         /* （連携用）死差Ｄレート８０ */
     zrnsisadrate81 ,         /* （連携用）死差Ｄレート８１ */
     zrnsisadrate82 ,         /* （連携用）死差Ｄレート８２ */
     zrnsisadrate83 ,         /* （連携用）死差Ｄレート８３ */
     zrnsisadrate84 ,         /* （連携用）死差Ｄレート８４ */
     zrnsisadrate85 ,         /* （連携用）死差Ｄレート８５ */
     zrnsisadrate86 ,         /* （連携用）死差Ｄレート８６ */
     zrnsisadrate87 ,         /* （連携用）死差Ｄレート８７ */
     zrnsisadrate88 ,         /* （連携用）死差Ｄレート８８ */
     zrnsisadrate89 ,         /* （連携用）死差Ｄレート８９ */
     zrnsisadrate90 ,         /* （連携用）死差Ｄレート９０ */
     zrnsisadrate91 ,         /* （連携用）死差Ｄレート９１ */
     zrnsisadrate92 ,         /* （連携用）死差Ｄレート９２ */
     zrnsisadrate93 ,         /* （連携用）死差Ｄレート９３ */
     zrnsisadrate94 ,         /* （連携用）死差Ｄレート９４ */
     zrnsisadrate95 ,         /* （連携用）死差Ｄレート９５ */
     zrnsisadrate96 ,         /* （連携用）死差Ｄレート９６ */
     zrnsisadrate97 ,         /* （連携用）死差Ｄレート９７ */
     zrnsisadrate98 ,         /* （連携用）死差Ｄレート９８ */
     zrnsisadrate99 ,         /* （連携用）死差Ｄレート９９ */
     zrnrisadrate00 ,         /* （連携用）利差Ｄレート００ */
     zrnrisadrate01 ,         /* （連携用）利差Ｄレート０１ */
     zrnrisadrate02 ,         /* （連携用）利差Ｄレート０２ */
     zrnrisadrate03 ,         /* （連携用）利差Ｄレート０３ */
     zrnrisadrate04 ,         /* （連携用）利差Ｄレート０４ */
     zrnrisadrate05 ,         /* （連携用）利差Ｄレート０５ */
     zrnrisadrate06 ,         /* （連携用）利差Ｄレート０６ */
     zrnrisadrate07 ,         /* （連携用）利差Ｄレート０７ */
     zrnrisadrate08 ,         /* （連携用）利差Ｄレート０８ */
     zrnrisadrate09 ,         /* （連携用）利差Ｄレート０９ */
     zrnrisadrate10 ,         /* （連携用）利差Ｄレート１０ */
     zrnrisadrate11 ,         /* （連携用）利差Ｄレート１１ */
     zrnrisadrate12 ,         /* （連携用）利差Ｄレート１２ */
     zrnrisadrate13 ,         /* （連携用）利差Ｄレート１３ */
     zrnrisadrate14 ,         /* （連携用）利差Ｄレート１４ */
     zrnrisadrate15 ,         /* （連携用）利差Ｄレート１５ */
     zrnrisadrate16 ,         /* （連携用）利差Ｄレート１６ */
     zrnrisadrate17 ,         /* （連携用）利差Ｄレート１７ */
     zrnrisadrate18 ,         /* （連携用）利差Ｄレート１８ */
     zrnrisadrate19 ,         /* （連携用）利差Ｄレート１９ */
     zrnrisadrate20 ,         /* （連携用）利差Ｄレート２０ */
     zrnrisadrate21 ,         /* （連携用）利差Ｄレート２１ */
     zrnrisadrate22 ,         /* （連携用）利差Ｄレート２２ */
     zrnrisadrate23 ,         /* （連携用）利差Ｄレート２３ */
     zrnrisadrate24 ,         /* （連携用）利差Ｄレート２４ */
     zrnrisadrate25 ,         /* （連携用）利差Ｄレート２５ */
     zrnrisadrate26 ,         /* （連携用）利差Ｄレート２６ */
     zrnrisadrate27 ,         /* （連携用）利差Ｄレート２７ */
     zrnrisadrate28 ,         /* （連携用）利差Ｄレート２８ */
     zrnrisadrate29 ,         /* （連携用）利差Ｄレート２９ */
     zrnrisadrate30 ,         /* （連携用）利差Ｄレート３０ */
     zrnrisadrate31 ,         /* （連携用）利差Ｄレート３１ */
     zrnrisadrate32 ,         /* （連携用）利差Ｄレート３２ */
     zrnrisadrate33 ,         /* （連携用）利差Ｄレート３３ */
     zrnrisadrate34 ,         /* （連携用）利差Ｄレート３４ */
     zrnrisadrate35 ,         /* （連携用）利差Ｄレート３５ */
     zrnrisadrate36 ,         /* （連携用）利差Ｄレート３６ */
     zrnrisadrate37 ,         /* （連携用）利差Ｄレート３７ */
     zrnrisadrate38 ,         /* （連携用）利差Ｄレート３８ */
     zrnrisadrate39 ,         /* （連携用）利差Ｄレート３９ */
     zrnrisadrate40 ,         /* （連携用）利差Ｄレート４０ */
     zrnrisadrate41 ,         /* （連携用）利差Ｄレート４１ */
     zrnrisadrate42 ,         /* （連携用）利差Ｄレート４２ */
     zrnrisadrate43 ,         /* （連携用）利差Ｄレート４３ */
     zrnrisadrate44 ,         /* （連携用）利差Ｄレート４４ */
     zrnrisadrate45 ,         /* （連携用）利差Ｄレート４５ */
     zrnrisadrate46 ,         /* （連携用）利差Ｄレート４６ */
     zrnrisadrate47 ,         /* （連携用）利差Ｄレート４７ */
     zrnrisadrate48 ,         /* （連携用）利差Ｄレート４８ */
     zrnrisadrate49 ,         /* （連携用）利差Ｄレート４９ */
     zrnrisadrate50 ,         /* （連携用）利差Ｄレート５０ */
     zrnrisadrate51 ,         /* （連携用）利差Ｄレート５１ */
     zrnrisadrate52 ,         /* （連携用）利差Ｄレート５２ */
     zrnrisadrate53 ,         /* （連携用）利差Ｄレート５３ */
     zrnrisadrate54 ,         /* （連携用）利差Ｄレート５４ */
     zrnrisadrate55 ,         /* （連携用）利差Ｄレート５５ */
     zrnrisadrate56 ,         /* （連携用）利差Ｄレート５６ */
     zrnrisadrate57 ,         /* （連携用）利差Ｄレート５７ */
     zrnrisadrate58 ,         /* （連携用）利差Ｄレート５８ */
     zrnrisadrate59 ,         /* （連携用）利差Ｄレート５９ */
     zrnrisadrate60 ,         /* （連携用）利差Ｄレート６０ */
     zrnrisadrate61 ,         /* （連携用）利差Ｄレート６１ */
     zrnrisadrate62 ,         /* （連携用）利差Ｄレート６２ */
     zrnrisadrate63 ,         /* （連携用）利差Ｄレート６３ */
     zrnrisadrate64 ,         /* （連携用）利差Ｄレート６４ */
     zrnrisadrate65 ,         /* （連携用）利差Ｄレート６５ */
     zrnrisadrate66 ,         /* （連携用）利差Ｄレート６６ */
     zrnrisadrate67 ,         /* （連携用）利差Ｄレート６７ */
     zrnrisadrate68 ,         /* （連携用）利差Ｄレート６８ */
     zrnrisadrate69 ,         /* （連携用）利差Ｄレート６９ */
     zrnrisadrate70 ,         /* （連携用）利差Ｄレート７０ */
     zrnrisadrate71 ,         /* （連携用）利差Ｄレート７１ */
     zrnrisadrate72 ,         /* （連携用）利差Ｄレート７２ */
     zrnrisadrate73 ,         /* （連携用）利差Ｄレート７３ */
     zrnrisadrate74 ,         /* （連携用）利差Ｄレート７４ */
     zrnrisadrate75 ,         /* （連携用）利差Ｄレート７５ */
     zrnrisadrate76 ,         /* （連携用）利差Ｄレート７６ */
     zrnrisadrate77 ,         /* （連携用）利差Ｄレート７７ */
     zrnrisadrate78 ,         /* （連携用）利差Ｄレート７８ */
     zrnrisadrate79 ,         /* （連携用）利差Ｄレート７９ */
     zrnrisadrate80 ,         /* （連携用）利差Ｄレート８０ */
     zrnrisadrate81 ,         /* （連携用）利差Ｄレート８１ */
     zrnrisadrate82 ,         /* （連携用）利差Ｄレート８２ */
     zrnrisadrate83 ,         /* （連携用）利差Ｄレート８３ */
     zrnrisadrate84 ,         /* （連携用）利差Ｄレート８４ */
     zrnrisadrate85 ,         /* （連携用）利差Ｄレート８５ */
     zrnrisadrate86 ,         /* （連携用）利差Ｄレート８６ */
     zrnrisadrate87 ,         /* （連携用）利差Ｄレート８７ */
     zrnrisadrate88 ,         /* （連携用）利差Ｄレート８８ */
     zrnrisadrate89 ,         /* （連携用）利差Ｄレート８９ */
     zrnrisadrate90 ,         /* （連携用）利差Ｄレート９０ */
     zrnrisadrate91 ,         /* （連携用）利差Ｄレート９１ */
     zrnrisadrate92 ,         /* （連携用）利差Ｄレート９２ */
     zrnrisadrate93 ,         /* （連携用）利差Ｄレート９３ */
     zrnrisadrate94 ,         /* （連携用）利差Ｄレート９４ */
     zrnrisadrate95 ,         /* （連携用）利差Ｄレート９５ */
     zrnrisadrate96 ,         /* （連携用）利差Ｄレート９６ */
     zrnrisadrate97 ,         /* （連携用）利差Ｄレート９７ */
     zrnrisadrate98 ,         /* （連携用）利差Ｄレート９８ */
     zrnrisadrate99 ,         /* （連携用）利差Ｄレート９９ */
     zrnhisadrate00 ,         /* （連携用）費差Ｄレート００ */
     zrnhisadrate01 ,         /* （連携用）費差Ｄレート０１ */
     zrnhisadrate02 ,         /* （連携用）費差Ｄレート０２ */
     zrnhisadrate03 ,         /* （連携用）費差Ｄレート０３ */
     zrnhisadrate04 ,         /* （連携用）費差Ｄレート０４ */
     zrnhisadrate05 ,         /* （連携用）費差Ｄレート０５ */
     zrnhisadrate06 ,         /* （連携用）費差Ｄレート０６ */
     zrnhisadrate07 ,         /* （連携用）費差Ｄレート０７ */
     zrnhisadrate08 ,         /* （連携用）費差Ｄレート０８ */
     zrnhisadrate09 ,         /* （連携用）費差Ｄレート０９ */
     zrnhisadrate10 ,         /* （連携用）費差Ｄレート１０ */
     zrnhisadrate11 ,         /* （連携用）費差Ｄレート１１ */
     zrnhisadrate12 ,         /* （連携用）費差Ｄレート１２ */
     zrnhisadrate13 ,         /* （連携用）費差Ｄレート１３ */
     zrnhisadrate14 ,         /* （連携用）費差Ｄレート１４ */
     zrnhisadrate15 ,         /* （連携用）費差Ｄレート１５ */
     zrnhisadrate16 ,         /* （連携用）費差Ｄレート１６ */
     zrnhisadrate17 ,         /* （連携用）費差Ｄレート１７ */
     zrnhisadrate18 ,         /* （連携用）費差Ｄレート１８ */
     zrnhisadrate19 ,         /* （連携用）費差Ｄレート１９ */
     zrnhisadrate20 ,         /* （連携用）費差Ｄレート２０ */
     zrnhisadrate21 ,         /* （連携用）費差Ｄレート２１ */
     zrnhisadrate22 ,         /* （連携用）費差Ｄレート２２ */
     zrnhisadrate23 ,         /* （連携用）費差Ｄレート２３ */
     zrnhisadrate24 ,         /* （連携用）費差Ｄレート２４ */
     zrnhisadrate25 ,         /* （連携用）費差Ｄレート２５ */
     zrnhisadrate26 ,         /* （連携用）費差Ｄレート２６ */
     zrnhisadrate27 ,         /* （連携用）費差Ｄレート２７ */
     zrnhisadrate28 ,         /* （連携用）費差Ｄレート２８ */
     zrnhisadrate29 ,         /* （連携用）費差Ｄレート２９ */
     zrnhisadrate30 ,         /* （連携用）費差Ｄレート３０ */
     zrnhisadrate31 ,         /* （連携用）費差Ｄレート３１ */
     zrnhisadrate32 ,         /* （連携用）費差Ｄレート３２ */
     zrnhisadrate33 ,         /* （連携用）費差Ｄレート３３ */
     zrnhisadrate34 ,         /* （連携用）費差Ｄレート３４ */
     zrnhisadrate35 ,         /* （連携用）費差Ｄレート３５ */
     zrnhisadrate36 ,         /* （連携用）費差Ｄレート３６ */
     zrnhisadrate37 ,         /* （連携用）費差Ｄレート３７ */
     zrnhisadrate38 ,         /* （連携用）費差Ｄレート３８ */
     zrnhisadrate39 ,         /* （連携用）費差Ｄレート３９ */
     zrnhisadrate40 ,         /* （連携用）費差Ｄレート４０ */
     zrnhisadrate41 ,         /* （連携用）費差Ｄレート４１ */
     zrnhisadrate42 ,         /* （連携用）費差Ｄレート４２ */
     zrnhisadrate43 ,         /* （連携用）費差Ｄレート４３ */
     zrnhisadrate44 ,         /* （連携用）費差Ｄレート４４ */
     zrnhisadrate45 ,         /* （連携用）費差Ｄレート４５ */
     zrnhisadrate46 ,         /* （連携用）費差Ｄレート４６ */
     zrnhisadrate47 ,         /* （連携用）費差Ｄレート４７ */
     zrnhisadrate48 ,         /* （連携用）費差Ｄレート４８ */
     zrnhisadrate49 ,         /* （連携用）費差Ｄレート４９ */
     zrnhisadrate50 ,         /* （連携用）費差Ｄレート５０ */
     zrnhisadrate51 ,         /* （連携用）費差Ｄレート５１ */
     zrnhisadrate52 ,         /* （連携用）費差Ｄレート５２ */
     zrnhisadrate53 ,         /* （連携用）費差Ｄレート５３ */
     zrnhisadrate54 ,         /* （連携用）費差Ｄレート５４ */
     zrnhisadrate55 ,         /* （連携用）費差Ｄレート５５ */
     zrnhisadrate56 ,         /* （連携用）費差Ｄレート５６ */
     zrnhisadrate57 ,         /* （連携用）費差Ｄレート５７ */
     zrnhisadrate58 ,         /* （連携用）費差Ｄレート５８ */
     zrnhisadrate59 ,         /* （連携用）費差Ｄレート５９ */
     zrnhisadrate60 ,         /* （連携用）費差Ｄレート６０ */
     zrnhisadrate61 ,         /* （連携用）費差Ｄレート６１ */
     zrnhisadrate62 ,         /* （連携用）費差Ｄレート６２ */
     zrnhisadrate63 ,         /* （連携用）費差Ｄレート６３ */
     zrnhisadrate64 ,         /* （連携用）費差Ｄレート６４ */
     zrnhisadrate65 ,         /* （連携用）費差Ｄレート６５ */
     zrnhisadrate66 ,         /* （連携用）費差Ｄレート６６ */
     zrnhisadrate67 ,         /* （連携用）費差Ｄレート６７ */
     zrnhisadrate68 ,         /* （連携用）費差Ｄレート６８ */
     zrnhisadrate69 ,         /* （連携用）費差Ｄレート６９ */
     zrnhisadrate70 ,         /* （連携用）費差Ｄレート７０ */
     zrnhisadrate71 ,         /* （連携用）費差Ｄレート７１ */
     zrnhisadrate72 ,         /* （連携用）費差Ｄレート７２ */
     zrnhisadrate73 ,         /* （連携用）費差Ｄレート７３ */
     zrnhisadrate74 ,         /* （連携用）費差Ｄレート７４ */
     zrnhisadrate75 ,         /* （連携用）費差Ｄレート７５ */
     zrnhisadrate76 ,         /* （連携用）費差Ｄレート７６ */
     zrnhisadrate77 ,         /* （連携用）費差Ｄレート７７ */
     zrnhisadrate78 ,         /* （連携用）費差Ｄレート７８ */
     zrnhisadrate79 ,         /* （連携用）費差Ｄレート７９ */
     zrnhisadrate80 ,         /* （連携用）費差Ｄレート８０ */
     zrnhisadrate81 ,         /* （連携用）費差Ｄレート８１ */
     zrnhisadrate82 ,         /* （連携用）費差Ｄレート８２ */
     zrnhisadrate83 ,         /* （連携用）費差Ｄレート８３ */
     zrnhisadrate84 ,         /* （連携用）費差Ｄレート８４ */
     zrnhisadrate85 ,         /* （連携用）費差Ｄレート８５ */
     zrnhisadrate86 ,         /* （連携用）費差Ｄレート８６ */
     zrnhisadrate87 ,         /* （連携用）費差Ｄレート８７ */
     zrnhisadrate88 ,         /* （連携用）費差Ｄレート８８ */
     zrnhisadrate89 ,         /* （連携用）費差Ｄレート８９ */
     zrnhisadrate90 ,         /* （連携用）費差Ｄレート９０ */
     zrnhisadrate91 ,         /* （連携用）費差Ｄレート９１ */
     zrnhisadrate92 ,         /* （連携用）費差Ｄレート９２ */
     zrnhisadrate93 ,         /* （連携用）費差Ｄレート９３ */
     zrnhisadrate94 ,         /* （連携用）費差Ｄレート９４ */
     zrnhisadrate95 ,         /* （連携用）費差Ｄレート９５ */
     zrnhisadrate96 ,         /* （連携用）費差Ｄレート９６ */
     zrnhisadrate97 ,         /* （連携用）費差Ｄレート９７ */
     zrnhisadrate98 ,         /* （連携用）費差Ｄレート９８ */
     zrnhisadrate99 ,         /* （連携用）費差Ｄレート９９ */
     zrndyouvrate00 ,         /* （連携用）Ｄ用Ｖレート００ */
     zrndyouvrate01 ,         /* （連携用）Ｄ用Ｖレート０１ */
     zrndyouvrate02 ,         /* （連携用）Ｄ用Ｖレート０２ */
     zrndyouvrate03 ,         /* （連携用）Ｄ用Ｖレート０３ */
     zrndyouvrate04 ,         /* （連携用）Ｄ用Ｖレート０４ */
     zrndyouvrate05 ,         /* （連携用）Ｄ用Ｖレート０５ */
     zrndyouvrate06 ,         /* （連携用）Ｄ用Ｖレート０６ */
     zrndyouvrate07 ,         /* （連携用）Ｄ用Ｖレート０７ */
     zrndyouvrate08 ,         /* （連携用）Ｄ用Ｖレート０８ */
     zrndyouvrate09 ,         /* （連携用）Ｄ用Ｖレート０９ */
     zrndyouvrate10 ,         /* （連携用）Ｄ用Ｖレート１０ */
     zrndyouvrate11 ,         /* （連携用）Ｄ用Ｖレート１１ */
     zrndyouvrate12 ,         /* （連携用）Ｄ用Ｖレート１２ */
     zrndyouvrate13 ,         /* （連携用）Ｄ用Ｖレート１３ */
     zrndyouvrate14 ,         /* （連携用）Ｄ用Ｖレート１４ */
     zrndyouvrate15 ,         /* （連携用）Ｄ用Ｖレート１５ */
     zrndyouvrate16 ,         /* （連携用）Ｄ用Ｖレート１６ */
     zrndyouvrate17 ,         /* （連携用）Ｄ用Ｖレート１７ */
     zrndyouvrate18 ,         /* （連携用）Ｄ用Ｖレート１８ */
     zrndyouvrate19 ,         /* （連携用）Ｄ用Ｖレート１９ */
     zrndyouvrate20 ,         /* （連携用）Ｄ用Ｖレート２０ */
     zrndyouvrate21 ,         /* （連携用）Ｄ用Ｖレート２１ */
     zrndyouvrate22 ,         /* （連携用）Ｄ用Ｖレート２２ */
     zrndyouvrate23 ,         /* （連携用）Ｄ用Ｖレート２３ */
     zrndyouvrate24 ,         /* （連携用）Ｄ用Ｖレート２４ */
     zrndyouvrate25 ,         /* （連携用）Ｄ用Ｖレート２５ */
     zrndyouvrate26 ,         /* （連携用）Ｄ用Ｖレート２６ */
     zrndyouvrate27 ,         /* （連携用）Ｄ用Ｖレート２７ */
     zrndyouvrate28 ,         /* （連携用）Ｄ用Ｖレート２８ */
     zrndyouvrate29 ,         /* （連携用）Ｄ用Ｖレート２９ */
     zrndyouvrate30 ,         /* （連携用）Ｄ用Ｖレート３０ */
     zrndyouvrate31 ,         /* （連携用）Ｄ用Ｖレート３１ */
     zrndyouvrate32 ,         /* （連携用）Ｄ用Ｖレート３２ */
     zrndyouvrate33 ,         /* （連携用）Ｄ用Ｖレート３３ */
     zrndyouvrate34 ,         /* （連携用）Ｄ用Ｖレート３４ */
     zrndyouvrate35 ,         /* （連携用）Ｄ用Ｖレート３５ */
     zrndyouvrate36 ,         /* （連携用）Ｄ用Ｖレート３６ */
     zrndyouvrate37 ,         /* （連携用）Ｄ用Ｖレート３７ */
     zrndyouvrate38 ,         /* （連携用）Ｄ用Ｖレート３８ */
     zrndyouvrate39 ,         /* （連携用）Ｄ用Ｖレート３９ */
     zrndyouvrate40 ,         /* （連携用）Ｄ用Ｖレート４０ */
     zrndyouvrate41 ,         /* （連携用）Ｄ用Ｖレート４１ */
     zrndyouvrate42 ,         /* （連携用）Ｄ用Ｖレート４２ */
     zrndyouvrate43 ,         /* （連携用）Ｄ用Ｖレート４３ */
     zrndyouvrate44 ,         /* （連携用）Ｄ用Ｖレート４４ */
     zrndyouvrate45 ,         /* （連携用）Ｄ用Ｖレート４５ */
     zrndyouvrate46 ,         /* （連携用）Ｄ用Ｖレート４６ */
     zrndyouvrate47 ,         /* （連携用）Ｄ用Ｖレート４７ */
     zrndyouvrate48 ,         /* （連携用）Ｄ用Ｖレート４８ */
     zrndyouvrate49 ,         /* （連携用）Ｄ用Ｖレート４９ */
     zrndyouvrate50 ,         /* （連携用）Ｄ用Ｖレート５０ */
     zrndyouvrate51 ,         /* （連携用）Ｄ用Ｖレート５１ */
     zrndyouvrate52 ,         /* （連携用）Ｄ用Ｖレート５２ */
     zrndyouvrate53 ,         /* （連携用）Ｄ用Ｖレート５３ */
     zrndyouvrate54 ,         /* （連携用）Ｄ用Ｖレート５４ */
     zrndyouvrate55 ,         /* （連携用）Ｄ用Ｖレート５５ */
     zrndyouvrate56 ,         /* （連携用）Ｄ用Ｖレート５６ */
     zrndyouvrate57 ,         /* （連携用）Ｄ用Ｖレート５７ */
     zrndyouvrate58 ,         /* （連携用）Ｄ用Ｖレート５８ */
     zrndyouvrate59 ,         /* （連携用）Ｄ用Ｖレート５９ */
     zrndyouvrate60 ,         /* （連携用）Ｄ用Ｖレート６０ */
     zrndyouvrate61 ,         /* （連携用）Ｄ用Ｖレート６１ */
     zrndyouvrate62 ,         /* （連携用）Ｄ用Ｖレート６２ */
     zrndyouvrate63 ,         /* （連携用）Ｄ用Ｖレート６３ */
     zrndyouvrate64 ,         /* （連携用）Ｄ用Ｖレート６４ */
     zrndyouvrate65 ,         /* （連携用）Ｄ用Ｖレート６５ */
     zrndyouvrate66 ,         /* （連携用）Ｄ用Ｖレート６６ */
     zrndyouvrate67 ,         /* （連携用）Ｄ用Ｖレート６７ */
     zrndyouvrate68 ,         /* （連携用）Ｄ用Ｖレート６８ */
     zrndyouvrate69 ,         /* （連携用）Ｄ用Ｖレート６９ */
     zrndyouvrate70 ,         /* （連携用）Ｄ用Ｖレート７０ */
     zrndyouvrate71 ,         /* （連携用）Ｄ用Ｖレート７１ */
     zrndyouvrate72 ,         /* （連携用）Ｄ用Ｖレート７２ */
     zrndyouvrate73 ,         /* （連携用）Ｄ用Ｖレート７３ */
     zrndyouvrate74 ,         /* （連携用）Ｄ用Ｖレート７４ */
     zrndyouvrate75 ,         /* （連携用）Ｄ用Ｖレート７５ */
     zrndyouvrate76 ,         /* （連携用）Ｄ用Ｖレート７６ */
     zrndyouvrate77 ,         /* （連携用）Ｄ用Ｖレート７７ */
     zrndyouvrate78 ,         /* （連携用）Ｄ用Ｖレート７８ */
     zrndyouvrate79 ,         /* （連携用）Ｄ用Ｖレート７９ */
     zrndyouvrate80 ,         /* （連携用）Ｄ用Ｖレート８０ */
     zrndyouvrate81 ,         /* （連携用）Ｄ用Ｖレート８１ */
     zrndyouvrate82 ,         /* （連携用）Ｄ用Ｖレート８２ */
     zrndyouvrate83 ,         /* （連携用）Ｄ用Ｖレート８３ */
     zrndyouvrate84 ,         /* （連携用）Ｄ用Ｖレート８４ */
     zrndyouvrate85 ,         /* （連携用）Ｄ用Ｖレート８５ */
     zrndyouvrate86 ,         /* （連携用）Ｄ用Ｖレート８６ */
     zrndyouvrate87 ,         /* （連携用）Ｄ用Ｖレート８７ */
     zrndyouvrate88 ,         /* （連携用）Ｄ用Ｖレート８８ */
     zrndyouvrate89 ,         /* （連携用）Ｄ用Ｖレート８９ */
     zrndyouvrate90 ,         /* （連携用）Ｄ用Ｖレート９０ */
     zrndyouvrate91 ,         /* （連携用）Ｄ用Ｖレート９１ */
     zrndyouvrate92 ,         /* （連携用）Ｄ用Ｖレート９２ */
     zrndyouvrate93 ,         /* （連携用）Ｄ用Ｖレート９３ */
     zrndyouvrate94 ,         /* （連携用）Ｄ用Ｖレート９４ */
     zrndyouvrate95 ,         /* （連携用）Ｄ用Ｖレート９５ */
     zrndyouvrate96 ,         /* （連携用）Ｄ用Ｖレート９６ */
     zrndyouvrate97 ,         /* （連携用）Ｄ用Ｖレート９７ */
     zrndyouvrate98 ,         /* （連携用）Ｄ用Ｖレート９８ */
     zrndyouvrate99 ,         /* （連携用）Ｄ用Ｖレート９９ */
     zrnkikensrate00 ,         /* （連携用）危険Ｓレート００ */
     zrnkikensrate01 ,         /* （連携用）危険Ｓレート０１ */
     zrnkikensrate02 ,         /* （連携用）危険Ｓレート０２ */
     zrnkikensrate03 ,         /* （連携用）危険Ｓレート０３ */
     zrnkikensrate04 ,         /* （連携用）危険Ｓレート０４ */
     zrnkikensrate05 ,         /* （連携用）危険Ｓレート０５ */
     zrnkikensrate06 ,         /* （連携用）危険Ｓレート０６ */
     zrnkikensrate07 ,         /* （連携用）危険Ｓレート０７ */
     zrnkikensrate08 ,         /* （連携用）危険Ｓレート０８ */
     zrnkikensrate09 ,         /* （連携用）危険Ｓレート０９ */
     zrnkikensrate10 ,         /* （連携用）危険Ｓレート１０ */
     zrnkikensrate11 ,         /* （連携用）危険Ｓレート１１ */
     zrnkikensrate12 ,         /* （連携用）危険Ｓレート１２ */
     zrnkikensrate13 ,         /* （連携用）危険Ｓレート１３ */
     zrnkikensrate14 ,         /* （連携用）危険Ｓレート１４ */
     zrnkikensrate15 ,         /* （連携用）危険Ｓレート１５ */
     zrnkikensrate16 ,         /* （連携用）危険Ｓレート１６ */
     zrnkikensrate17 ,         /* （連携用）危険Ｓレート１７ */
     zrnkikensrate18 ,         /* （連携用）危険Ｓレート１８ */
     zrnkikensrate19 ,         /* （連携用）危険Ｓレート１９ */
     zrnkikensrate20 ,         /* （連携用）危険Ｓレート２０ */
     zrnkikensrate21 ,         /* （連携用）危険Ｓレート２１ */
     zrnkikensrate22 ,         /* （連携用）危険Ｓレート２２ */
     zrnkikensrate23 ,         /* （連携用）危険Ｓレート２３ */
     zrnkikensrate24 ,         /* （連携用）危険Ｓレート２４ */
     zrnkikensrate25 ,         /* （連携用）危険Ｓレート２５ */
     zrnkikensrate26 ,         /* （連携用）危険Ｓレート２６ */
     zrnkikensrate27 ,         /* （連携用）危険Ｓレート２７ */
     zrnkikensrate28 ,         /* （連携用）危険Ｓレート２８ */
     zrnkikensrate29 ,         /* （連携用）危険Ｓレート２９ */
     zrnkikensrate30 ,         /* （連携用）危険Ｓレート３０ */
     zrnkikensrate31 ,         /* （連携用）危険Ｓレート３１ */
     zrnkikensrate32 ,         /* （連携用）危険Ｓレート３２ */
     zrnkikensrate33 ,         /* （連携用）危険Ｓレート３３ */
     zrnkikensrate34 ,         /* （連携用）危険Ｓレート３４ */
     zrnkikensrate35 ,         /* （連携用）危険Ｓレート３５ */
     zrnkikensrate36 ,         /* （連携用）危険Ｓレート３６ */
     zrnkikensrate37 ,         /* （連携用）危険Ｓレート３７ */
     zrnkikensrate38 ,         /* （連携用）危険Ｓレート３８ */
     zrnkikensrate39 ,         /* （連携用）危険Ｓレート３９ */
     zrnkikensrate40 ,         /* （連携用）危険Ｓレート４０ */
     zrnkikensrate41 ,         /* （連携用）危険Ｓレート４１ */
     zrnkikensrate42 ,         /* （連携用）危険Ｓレート４２ */
     zrnkikensrate43 ,         /* （連携用）危険Ｓレート４３ */
     zrnkikensrate44 ,         /* （連携用）危険Ｓレート４４ */
     zrnkikensrate45 ,         /* （連携用）危険Ｓレート４５ */
     zrnkikensrate46 ,         /* （連携用）危険Ｓレート４６ */
     zrnkikensrate47 ,         /* （連携用）危険Ｓレート４７ */
     zrnkikensrate48 ,         /* （連携用）危険Ｓレート４８ */
     zrnkikensrate49 ,         /* （連携用）危険Ｓレート４９ */
     zrnkikensrate50 ,         /* （連携用）危険Ｓレート５０ */
     zrnkikensrate51 ,         /* （連携用）危険Ｓレート５１ */
     zrnkikensrate52 ,         /* （連携用）危険Ｓレート５２ */
     zrnkikensrate53 ,         /* （連携用）危険Ｓレート５３ */
     zrnkikensrate54 ,         /* （連携用）危険Ｓレート５４ */
     zrnkikensrate55 ,         /* （連携用）危険Ｓレート５５ */
     zrnkikensrate56 ,         /* （連携用）危険Ｓレート５６ */
     zrnkikensrate57 ,         /* （連携用）危険Ｓレート５７ */
     zrnkikensrate58 ,         /* （連携用）危険Ｓレート５８ */
     zrnkikensrate59 ,         /* （連携用）危険Ｓレート５９ */
     zrnkikensrate60 ,         /* （連携用）危険Ｓレート６０ */
     zrnkikensrate61 ,         /* （連携用）危険Ｓレート６１ */
     zrnkikensrate62 ,         /* （連携用）危険Ｓレート６２ */
     zrnkikensrate63 ,         /* （連携用）危険Ｓレート６３ */
     zrnkikensrate64 ,         /* （連携用）危険Ｓレート６４ */
     zrnkikensrate65 ,         /* （連携用）危険Ｓレート６５ */
     zrnkikensrate66 ,         /* （連携用）危険Ｓレート６６ */
     zrnkikensrate67 ,         /* （連携用）危険Ｓレート６７ */
     zrnkikensrate68 ,         /* （連携用）危険Ｓレート６８ */
     zrnkikensrate69 ,         /* （連携用）危険Ｓレート６９ */
     zrnkikensrate70 ,         /* （連携用）危険Ｓレート７０ */
     zrnkikensrate71 ,         /* （連携用）危険Ｓレート７１ */
     zrnkikensrate72 ,         /* （連携用）危険Ｓレート７２ */
     zrnkikensrate73 ,         /* （連携用）危険Ｓレート７３ */
     zrnkikensrate74 ,         /* （連携用）危険Ｓレート７４ */
     zrnkikensrate75 ,         /* （連携用）危険Ｓレート７５ */
     zrnkikensrate76 ,         /* （連携用）危険Ｓレート７６ */
     zrnkikensrate77 ,         /* （連携用）危険Ｓレート７７ */
     zrnkikensrate78 ,         /* （連携用）危険Ｓレート７８ */
     zrnkikensrate79 ,         /* （連携用）危険Ｓレート７９ */
     zrnkikensrate80 ,         /* （連携用）危険Ｓレート８０ */
     zrnkikensrate81 ,         /* （連携用）危険Ｓレート８１ */
     zrnkikensrate82 ,         /* （連携用）危険Ｓレート８２ */
     zrnkikensrate83 ,         /* （連携用）危険Ｓレート８３ */
     zrnkikensrate84 ,         /* （連携用）危険Ｓレート８４ */
     zrnkikensrate85 ,         /* （連携用）危険Ｓレート８５ */
     zrnkikensrate86 ,         /* （連携用）危険Ｓレート８６ */
     zrnkikensrate87 ,         /* （連携用）危険Ｓレート８７ */
     zrnkikensrate88 ,         /* （連携用）危険Ｓレート８８ */
     zrnkikensrate89 ,         /* （連携用）危険Ｓレート８９ */
     zrnkikensrate90 ,         /* （連携用）危険Ｓレート９０ */
     zrnkikensrate91 ,         /* （連携用）危険Ｓレート９１ */
     zrnkikensrate92 ,         /* （連携用）危険Ｓレート９２ */
     zrnkikensrate93 ,         /* （連携用）危険Ｓレート９３ */
     zrnkikensrate94 ,         /* （連携用）危険Ｓレート９４ */
     zrnkikensrate95 ,         /* （連携用）危険Ｓレート９５ */
     zrnkikensrate96 ,         /* （連携用）危険Ｓレート９６ */
     zrnkikensrate97 ,         /* （連携用）危険Ｓレート９７ */
     zrnkikensrate98 ,         /* （連携用）危険Ｓレート９８ */
     zrnkikensrate99           /* （連携用）危険Ｓレート９９ */
FROM ZT_RatedRn_Z;