CREATE VIEW IT_HrhnTtdkKan AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     henkousikibetukey ,         /* 変更識別キー */
     syoruiCd ,         /* 書類コード */
     tyouhyouymd ,         /* 帳票作成日 */
     shskyno ,         /* 送付先郵便番号 */
     shsadr1kj ,         /* 送付先住所１（漢字）（３０桁） */
     shsadr2kj ,         /* 送付先住所２（漢字）（３０桁） */
     shsadr3kj ,         /* 送付先住所３（漢字）（３０桁） */
     shsnmkj ,         /* 送付先氏名（漢字） */
     toiawasesosikinmkj ,         /* 問合せ先組織名（漢字） */
     toiawaseyno ,         /* 問合せ先郵便番号 */
     toiawaseadr1kj ,         /* 問合せ先住所１（漢字） */
     toiawaseadr2kj ,         /* 問合せ先住所２（漢字） */
     toiawaseadr3kj ,         /* 問合せ先住所３（漢字） */
     toiawasekaisyanmkj ,         /* 問合せ先会社名（漢字） */
     toiawasetelno ,         /* 問合せ先電話番号 */
     toiawaseteluktkkanou1 ,         /* 問合せ先電話受付可能時間１ */
     toiawaseteluktkkanou2 ,         /* 問合せ先電話受付可能時間２ */
     toiawasesosikinmkj2 ,         /* 第２問合せ先組織名（漢字） */
     toiawasetelno2 ,         /* 第２問合せ先電話番号 */
     kyknmkj ,         /* 契約者名（漢字） */
     hhknnmkj ,         /* 被保険者名（漢字） */
     kouzamaskingmsg ,         /* 口座マスキングＭＳＧ */
     hrkkaisuutkiktbrisyu ,         /* 払込回数・定期一括払種類 */
     hrkkeiro ,         /* 払込経路 */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     kouryokuhasseiym ,         /* 効力発生年月 */
     msgarea34keta1 ,         /* メッセージエリア（３４桁）１ */
     msgarea34keta2 ,         /* メッセージエリア（３４桁）２ */
     msgarea34keta3 ,         /* メッセージエリア（３４桁）３ */
     msgarea34keta4 ,         /* メッセージエリア（３４桁）４ */
     msgarea34keta5 ,         /* メッセージエリア（３４桁）５ */
     msgarea34keta6 ,         /* メッセージエリア（３４桁）６ */
     msgarea34keta7 ,         /* メッセージエリア（３４桁）７ */
     hrkykkmsg34keta1 ,         /* 振替予告メッセージ（３４桁）１ */
     hrkykkmsg34keta2 ,         /* 振替予告メッセージ（３４桁）２ */
     hrkykkmsg34keta3 ,         /* 振替予告メッセージ（３４桁）３ */
     hrkykkmsg34keta4 ,         /* 振替予告メッセージ（３４桁）４ */
     hrkykkmsg34keta5 ,         /* 振替予告メッセージ（３４桁）５ */
     hrkykkmsg34keta6 ,         /* 振替予告メッセージ（３４桁）６ */
     hrkykkmsg34keta7 ,         /* 振替予告メッセージ（３４桁）７ */
     hrkykkmsg34keta8 ,         /* 振替予告メッセージ（３４桁）８ */
     hrkykkmsg34keta9 ,         /* 振替予告メッセージ（３４桁）９ */
     hrkykkmsg34keta10 ,         /* 振替予告メッセージ（３４桁）１０ */
     hrkykkmsg34keta11 ,         /* 振替予告メッセージ（３４桁）１１ */
     hrkykkmsg34keta12 ,         /* 振替予告メッセージ（３４桁）１２ */
     hrkykkmsg34keta13 ,         /* 振替予告メッセージ（３４桁）１３ */
     hrkykkmsg34keta14 ,         /* 振替予告メッセージ（３４桁）１４ */
     hrkykkmsg34keta15 ,         /* 振替予告メッセージ（３４桁）１５ */
     hrkykkmsg34keta16 ,         /* 振替予告メッセージ（３４桁）１６ */
     hrkykkmsg34keta17 ,         /* 振替予告メッセージ（３４桁）１７ */
     hrkykkmsg34keta18 ,         /* 振替予告メッセージ（３４桁）１８ */
     hrkykkmsg34keta19 ,         /* 振替予告メッセージ（３４桁）１９ */
     hrkykkmsg34keta20 ,         /* 振替予告メッセージ（３４桁）２０ */
     hrkykkmsg34keta21 ,         /* 振替予告メッセージ（３４桁）２１ */
     hrkykkmsg34keta22 ,         /* 振替予告メッセージ（３４桁）２２ */
     hrkykkmsg34keta23 ,         /* 振替予告メッセージ（３４桁）２３ */
     hrkykkmsg34keta24 ,         /* 振替予告メッセージ（３４桁）２４ */
     hrkykkmsg34keta25 ,         /* 振替予告メッセージ（３４桁）２５ */
     hrkykkmsg34keta26 ,         /* 振替予告メッセージ（３４桁）２６ */
     hrkykkmsg34keta27 ,         /* 振替予告メッセージ（３４桁）２７ */
     hrkykkmsg34keta28 ,         /* 振替予告メッセージ（３４桁）２８ */
     hassoukbn ,         /* 発送区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     honsyakaisouriyuu           /* 本社回送理由 */
FROM IT_HrhnTtdkKan_Z;