CREATE VIEW MT_DsMailHaisin AS SELECT
     sousinymd ,         /* 送信日 */
     dskokmailaddressskbtkey ,         /* ＤＳ顧客メールアドレス識別キー */
     dssousinmailsyubetukbn ,         /* ＤＳ送信メール種別区分 */
     dssousinno ,         /* ＤＳ送信番号 */
     syono ,         /* 証券番号 */
     dsmailaddress ,         /* ＤＳメールアドレス */
     sasikomikoumokusyou01 ,         /* 差込項目（小）０１ */
     sasikomikoumokusyou02 ,         /* 差込項目（小）０２ */
     sasikomikoumokusyou03 ,         /* 差込項目（小）０３ */
     sasikomikoumokusyou04 ,         /* 差込項目（小）０４ */
     sasikomikoumokusyou05 ,         /* 差込項目（小）０５ */
     sasikomikoumokusyou06 ,         /* 差込項目（小）０６ */
     sasikomikoumokusyou07 ,         /* 差込項目（小）０７ */
     sasikomikoumokusyou08 ,         /* 差込項目（小）０８ */
     sasikomikoumokusyou09 ,         /* 差込項目（小）０９ */
     sasikomikoumokusyou10 ,         /* 差込項目（小）１０ */
     sasikomikoumokusyou11 ,         /* 差込項目（小）１１ */
     sasikomikoumokusyou12 ,         /* 差込項目（小）１２ */
     sasikomikoumokusyou13 ,         /* 差込項目（小）１３ */
     sasikomikoumokusyou14 ,         /* 差込項目（小）１４ */
     sasikomikoumokusyou15 ,         /* 差込項目（小）１５ */
     sasikomikoumokusyou16 ,         /* 差込項目（小）１６ */
     sasikomikoumokusyou17 ,         /* 差込項目（小）１７ */
     sasikomikoumokusyou18 ,         /* 差込項目（小）１８ */
     sasikomikoumokusyou19 ,         /* 差込項目（小）１９ */
     sasikomikoumokusyou20 ,         /* 差込項目（小）２０ */
     sasikomikoumokusyou21 ,         /* 差込項目（小）２１ */
     sasikomikoumokusyou22 ,         /* 差込項目（小）２２ */
     sasikomikoumokusyou23 ,         /* 差込項目（小）２３ */
     sasikomikoumokusyou24 ,         /* 差込項目（小）２４ */
     sasikomikoumokusyou25 ,         /* 差込項目（小）２５ */
     sasikomikoumokusyou26 ,         /* 差込項目（小）２６ */
     sasikomikoumokusyou27 ,         /* 差込項目（小）２７ */
     sasikomikoumokusyou28 ,         /* 差込項目（小）２８ */
     sasikomikoumokusyou29 ,         /* 差込項目（小）２９ */
     sasikomikoumokusyou30 ,         /* 差込項目（小）３０ */
     sasikomikoumokutyuu01 ,         /* 差込項目（中）０１ */
     sasikomikoumokutyuu02 ,         /* 差込項目（中）０２ */
     sasikomikoumokutyuu03 ,         /* 差込項目（中）０３ */
     sasikomikoumokutyuu04 ,         /* 差込項目（中）０４ */
     sasikomikoumokutyuu05 ,         /* 差込項目（中）０５ */
     sasikomikoumokutyuu06 ,         /* 差込項目（中）０６ */
     sasikomikoumokutyuu07 ,         /* 差込項目（中）０７ */
     sasikomikoumokutyuu08 ,         /* 差込項目（中）０８ */
     sasikomikoumokutyuu09 ,         /* 差込項目（中）０９ */
     sasikomikoumokutyuu10 ,         /* 差込項目（中）１０ */
     sasikomikoumokutyuu11 ,         /* 差込項目（中）１１ */
     sasikomikoumokutyuu12 ,         /* 差込項目（中）１２ */
     sasikomikoumokutyuu13 ,         /* 差込項目（中）１３ */
     sasikomikoumokutyuu14 ,         /* 差込項目（中）１４ */
     sasikomikoumokutyuu15 ,         /* 差込項目（中）１５ */
     sasikomikoumokutyuu16 ,         /* 差込項目（中）１６ */
     sasikomikoumokutyuu17 ,         /* 差込項目（中）１７ */
     sasikomikoumokutyuu18 ,         /* 差込項目（中）１８ */
     sasikomikoumokutyuu19 ,         /* 差込項目（中）１９ */
     sasikomikoumokutyuu20 ,         /* 差込項目（中）２０ */
     sasikomikoumokudai01 ,         /* 差込項目（大）０１ */
     sasikomikoumokudai02 ,         /* 差込項目（大）０２ */
     sasikomikoumokudai03 ,         /* 差込項目（大）０３ */
     sasikomikoumokudai04 ,         /* 差込項目（大）０４ */
     sasikomikoumokudai05 ,         /* 差込項目（大）０５ */
     sasikomikoumokudai06 ,         /* 差込項目（大）０６ */
     sasikomikoumokudai07 ,         /* 差込項目（大）０７ */
     sasikomikoumokudai08 ,         /* 差込項目（大）０８ */
     sasikomikoumokudai09 ,         /* 差込項目（大）０９ */
     sasikomikoumokudai10 ,         /* 差込項目（大）１０ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM MT_DsMailHaisin_Z;