CREATE VIEW ZT_RrtHndugtHknJigyohiRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnyuukourecordlength ,         /* （連携用）有効レコード長 */
     zrnrdwarea ,         /* （連携用）ＲＤＷ領域 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnsuuriyoupjytouym ,         /* （連携用）数理用Ｐ充当年月 */
     zrnsihankibikinkbn ,         /* （連携用）四半期備金区分 */
     zrnhenkousyoriymd ,         /* （連携用）変更処理年月日 */
     zrndenymd ,         /* （連携用）伝票日付 */
     zrnsyoricd ,         /* （連携用）処理コード */
     zrnkykymdmaekykhyj ,         /* （連携用）契約日前契約表示 */
     zrnkarikasikbn ,         /* （連携用）借方貸方区分 */
     zrnsuuriyouyobin8 ,         /* （連携用）数理用予備項目Ｎ８ */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrndatakanrino ,         /* （連携用）データ管理番号 */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn ,         /* （連携用）外出Ｐ免区分 */
     zrnstdssytikbn ,         /* （連携用）外出集定区分 */
     zrnstdssnskbn ,         /* （連携用）外出診査区分 */
     zrnsotodasimanagehyouji ,         /* （連携用）外出満年令表示 */
     zrnsotodasiphkbnmnoshyouji ,         /* （連携用）外出Ｐ不可分見直表示 */
     zrnstdsstkjytkyuhyj ,         /* （連携用）外出新特条適用表示 */
     zrnsuuriyouyobin5 ,         /* （連携用）数理用予備項目Ｎ５ */
     zrnyobiv4 ,         /* （連携用）予備項目Ｖ４ */
     zrnkbnkeiriyousegmentkbn ,         /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn ,         /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd ,         /* （連携用）数理種類コード */
     zrnhosyoukinoukbn ,         /* （連携用）保障機能区分 */
     zrndaikbn ,         /* （連携用）大区分 */
     zrntyuukbn ,         /* （連携用）中区分 */
     zrnsyoukbn ,         /* （連携用）小区分 */
     zrnsedaikbn ,         /* （連携用）世代区分 */
     zrnharaikatakbn ,         /* （連携用）払方区分 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnsdpdkbn ,         /* （連携用）Ｓ建Ｐ建区分 */
     zrnryouritukbn ,         /* （連携用）料率区分 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrnhhknnentysihyj ,         /* （連携用）被保険者年令調整表示 */
     zrnsyukeiyakupwaribikikbn ,         /* （連携用）主契約Ｐ割引区分 */
     zrnkuriagekurisagekbn ,         /* （連携用）繰上げ繰下げ区分 */
     zrnsuuriyouyobin11 ,         /* （連携用）数理用予備項目Ｎ１１ */
     zrnyobiv10 ,         /* （連携用）予備項目Ｖ１０ */
     zrnalmyousohutomeisyoukbn ,         /* （連携用）ＡＬＭ用ソフト名称区分 */
     zrnsnkyksoftmeisyoukbn ,         /* （連携用）新契約ソフト名称区分 */
     zrnsoftmeisyoukbn ,         /* （連携用）ソフト名称区分 */
     zrnnenkinkaisinendo ,         /* （連携用）年金開始年度 */
     zrnnenkingatakbn ,         /* （連携用）年金型区分 */
     zrnnknshry ,         /* （連携用）年金支払期間 */
     zrnbosyuukeitaikbn ,         /* （連携用）募集形態区分 */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnsuuriyouyobin8x2 ,         /* （連携用）数理用予備項目Ｎ８＿２ */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnpjuutoujikawaserate ,         /* （連携用）保険料充当時為替レート */
     zrnpjuutoujikawasekijyunymd ,         /* （連携用）保険料充当時為替基準年月日 */
     zrngessitumitatekin ,         /* （連携用）月始積立金 */
     zrnyoteiriritun5 ,         /* （連携用）予定利率Ｎ５ */
     zrntumitateriritu ,         /* （連携用）積立利率 */
     zrngaikadatetougetujuutoup ,         /* （連携用）外貨建当月充当Ｐ */
     zrnkiharaikomip ,         /* （連携用）既払込Ｐ */
     zrnkeisanhanteiyoutmttkn ,         /* （連携用）計算判定用積立金 */
     zrnzettaisibouritu ,         /* （連携用）絶対死亡率 */
     zrnsoutaisibouritu ,         /* （連携用）相対死亡率 */
     zrnsoutaikaiyakuritu ,         /* （連携用）相対解約率 */
     zrnvhireilritu ,         /* （連携用）Ｖ比例Ｌ率 */
     zrnyobin13 ,         /* （連携用）予備項目Ｎ１３ */
     zrnphireilwrbkritu ,         /* （連携用）Ｐ比例Ｌ割引率 */
     zrngetumatutumitatekin ,         /* （連携用）月末積立金 */
     zrnzennoujiikkatubaraijytgk ,         /* （連携用）前納時一括払充当額 */
     zrngaikadatenkgns ,         /* （連携用）外貨建年金原資 */
     zrnphireialpha ,         /* （連携用）Ｐ比例α */
     zrnphireibeta ,         /* （連携用）Ｐ比例β */
     zrnphireiganma ,         /* （連携用）Ｐ比例γ */
     zrnkykjikawaserate ,         /* （連携用）契約時為替レート */
     zrnkykjikawaseratetkyuymd ,         /* （連携用）契約時為替レート適用年月日 */
     zrnyobiv11           /* （連携用）予備項目Ｖ１１ */
FROM ZT_RrtHndugtHknJigyohiRn_Z;