CREATE VIEW ZT_SntkInfoTourokuTy AS SELECT
     ztysntkinfono ,         /* （中継用）選択情報番号 */
     ztyrenno ,         /* （中継用）連番 */
     ztysntkinfotourokusyskbn ,         /* （中継用）選択情報登録システム区分 */
     ztysyoriymd ,         /* （中継用）処理年月日 */
     ztyhuho2kyknokbn ,         /* （中継用）普保Ⅱ契約番号区分 */
     ztyhuho2kykno ,         /* （中継用）普保Ⅱ契約番号 */
     ztysyouhncd ,         /* （中継用）商品コード */
     ztysntkinfofsegkbn ,         /* （中継用）選択情報ＦＳＥＧ区分 */
     ztysntkinfofkojinkbn ,         /* （中継用）選択情報Ｆ個人区分 */
     ztytaisyounm ,         /* （中継用）対象者名 */
     ztykjtaisyounm ,         /* （中継用）漢字対象者名 */
     ztytaisyouseiymd ,         /* （中継用）対象者生年月日 */
     ztytaisyouseibetu ,         /* （中継用）対象者性別区分 */
     ztydakuhiketnaiyouarihyj ,         /* （中継用）諾否決定内容有表示 */
     ztykktnaiyouarihyj ,         /* （中継用）告知内容有表示 */
     ztykijinaiyouarihyj ,         /* （中継用）記事内容有表示 */
     ztymrarihyj ,         /* （中継用）ＭＲ有表示 */
     ztykoudosyougaiarihyj ,         /* （中継用）高度障害有表示 */
     ztytorikaijoarihyj ,         /* （中継用）取消解除有表示 */
     ztyskhuseirituhyouji ,         /* （中継用）新契約不成立表示 */
     ztysntkinfotourokuyobi01 ,         /* （中継用）選択情報登録予備０１ */
     ztydeckbn ,         /* （中継用）ＤＥＣ区分 */
     ztyketymd ,         /* （中継用）決定年月日 */
     ztyketkekkacd ,         /* （中継用）決定結果コード */
     ztyketriyuucd1 ,         /* （中継用）決定理由コード１ */
     ztyketriyuucd2 ,         /* （中継用）決定理由コード２ */
     ztyketriyuucd3 ,         /* （中継用）決定理由コード３ */
     ztyketriyuucd4 ,         /* （中継用）決定理由コード４ */
     ztyketsyacd ,         /* （中継用）決定者コード */
     ztysntkinfotourokuyobi02 ,         /* （中継用）選択情報登録予備０２ */
     ztysntkinfosintyou ,         /* （中継用）選択情報身長 */
     ztysntkinfotaijyuu ,         /* （中継用）選択情報体重 */
     ztykokutiymd ,         /* （中継用）告知年月日 */
     ztysntkinfotourokuyobi03 ,         /* （中継用）選択情報登録予備０３ */
     ztysyoubyoucd1 ,         /* （中継用）傷病コード１ */
     ztykantiym1 ,         /* （中継用）完治年月１ */
     ztysyoubyoucd2 ,         /* （中継用）傷病コード２ */
     ztykantiym2 ,         /* （中継用）完治年月２ */
     ztysntkinfotourokuyobi04 ,         /* （中継用）選択情報登録予備０４ */
     ztymrriyuucdkbn ,         /* （中継用）ＭＲ理由コード区分 */
     ztysntkinfotourokuyobi05 ,         /* （中継用）選択情報登録予備０５ */
     ztysntkinfokyktorikesikbn ,         /* （中継用）選択情報用契約取消処理区分 */
     ztysntkinfotourokuyobi06 ,         /* （中継用）選択情報登録予備０６ */
     ztykdsssiharaijyoutaikbn ,         /* （中継用）高度障害Ｓ支払状態区分 */
     ztykdsssiharaiymd ,         /* （中継用）高度障害Ｓ支払年月日 */
     ztykdsymd ,         /* （中継用）高度障害年月日 */
     ztykdssiharaisosikicd ,         /* （中継用）高度障害支払組織コード */
     ztysntkinfotourokuyobi07 ,         /* （中継用）選択情報登録予備０７ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SntkInfoTourokuTy_Z;