CREATE VIEW ZT_KesikomiSousinCreditRn AS SELECT
     zrnkskmsousinrenno ,         /* （連携用）消込送信連番 */
     zrnkskmkamokucd ,         /* （連携用）消込科目コード */
     zrnsuitoukbn ,         /* （連携用）出納区分 */
     zrnsuitousosikicd ,         /* （連携用）出納組織コード */
     zrnhasseidenymd ,         /* （連携用）発生伝票日付 */
     zrnkarikanjyono ,         /* （連携用）仮勘定番号 */
     zrnnkkakusyounyuuryokuymd1 ,         /* （連携用）入金確証入力年月日１ */
     zrniktannaidantaizaikeikbn ,         /* （連携用）一括案内団体財形区分 */
     zrnkskmfanniskcd ,         /* （連携用）（消込Ｆ）案内先コード */
     zrndantaiannaijyuutouym1 ,         /* （連携用）団体案内充当年月１ */
     zrnannaino1 ,         /* （連携用）案内番号１ */
     zrnbonusharaihyouji1 ,         /* （連携用）ボーナス払表示１ */
     zrnkskmfkzhurikaebankcd ,         /* （連携用）（消込Ｆ）口座振替銀行番号 */
     zrnkskmfhurikaeymd ,         /* （連携用）（消込Ｆ）振替年月日 */
     zrndairitenuketukeno1 ,         /* （連携用）代理店受付番号１ */
     zrnzaikeihrkkaisuukbn1 ,         /* （連携用）財形払込回数区分１ */
     zrnnoukinhyouno ,         /* （連携用）納金票番号 */
     zrnkskmfcreditkaisyacd ,         /* （連携用）（消込Ｆ）クレジット会社コード */
     zrnkinyuukikankbn ,         /* （連携用）金融機関区分 */
     zrnyobiv18 ,         /* （連携用）予備項目Ｖ１８ */
     zrnkskmfsyoriymd ,         /* （連携用）（消込Ｆ）処理年月日 */
     zrnkskmfdenymd ,         /* （連携用）（消込Ｆ）伝票日付 */
     zrndenatesakicd ,         /* （連携用）伝票宛先部課コード */
     zrnkskmftaisyakukbn ,         /* （連携用）（消込Ｆ）貸借区分 */
     zrnhutuuhokenkamokucd ,         /* （連携用）普通保険用科目コード */
     zrndengk ,         /* （連携用）伝票金額 */
     zrntabakariknjykskmdatakbn ,         /* （連携用）束仮勘定消込項目データ区分 */
     zrnkskmfryousyuuymd ,         /* （連携用）（消込Ｆ）領収年月日 */
     zrnryousyuuhm ,         /* （連携用）領収時分 */
     zrnyobiv3 ,         /* （連携用）予備項目Ｖ３ */
     zrnnkkakusyounyuuryokuymd2 ,         /* （連携用）入金確証入力年月日２ */
     zrnkskmfsyono ,         /* （連携用）（消込Ｆ）証券番号 */
     zrnnkhoukokuhyoutantouka ,         /* （連携用）入金報告票担当課 */
     zrnnkhoukokuhyoukihyouymd ,         /* （連携用）入金報告票起票年月日 */
     zrnnkhoukokuhyoubunkaino ,         /* （連携用）入金報告票分解表番号 */
     zrnnkkakusyounyuuryokuno ,         /* （連携用）入金確証入力番号 */
     zrnkskmfdantaicd ,         /* （連携用）（消込Ｆ）団体コード */
     zrndantaiannaijyuutouym2 ,         /* （連携用）団体案内充当年月２ */
     zrnbonusharaihyouji2 ,         /* （連携用）ボーナス払表示２ */
     zrnannaino2 ,         /* （連携用）案内番号２ */
     zrndantaipkbn ,         /* （連携用）団体保険料区分 */
     zrndantainyuukinymd ,         /* （連携用）団体入金年月日 */
     zrnkskmfjyuutouym ,         /* （連携用）（消込Ｆ）充当年月 */
     zrnsuitouymd ,         /* （連携用）出納年月日 */
     zrnnyuuryokuhouhoukbn ,         /* （連携用）入力方法区分 */
     zrnkskmfnyknaiyoukbn ,         /* （連携用）（消込Ｆ）入金内容区分 */
     zrnkzhurikaekykhndnkhyouji ,         /* （連携用）口座振替契約ハンド入金表示 */
     zrnkskmfdairitencd ,         /* （連携用）（消込Ｆ）代理店コード */
     zrndairitenuketukeno2 ,         /* （連携用）代理店受付番号２ */
     zrnikkatudantaicd ,         /* （連携用）一括団体コード */
     zrnikkatuannaihikisariym ,         /* （連携用）一括案内引去年月 */
     zrnikkatuannaino ,         /* （連携用）一括案内番号 */
     zrnzaikeihrkkaisuukbn2 ,         /* （連携用）財形払込回数区分２ */
     zrnzaikeikyksyano ,         /* （連携用）財形契約者番号 */
     zrnhasseisosikicd ,         /* （連携用）発生組織コード */
     zrnteikeisakikaisyacd ,         /* （連携用）提携先会社コード */
     zrnkskmfbankcd ,         /* （連携用）（消込Ｆ）銀行番号 */
     zrnsuitousyorisosikicd ,         /* （連携用）出納処理組織コード */
     zrnaitekanjyouyomikaekbn ,         /* （連携用）相手勘定読替区分 */
     zrncreditcardhrkskmkbn ,         /* （連携用）クレ払消込区分 */
     zrnlastteiseiymd ,         /* （連携用）最終訂正年月日 */
     zrnkskmkanryouymd ,         /* （連携用）消込完了年月日 */
     zrnkskmteiseino ,         /* （連携用）消込訂正番号 */
     zrnkskmkanryousijihyouji ,         /* （連携用）消込完了指示表示 */
     zrnuketuketencd ,         /* （連携用）受付店コード */
     zrncvscd ,         /* （連携用）ＣＶＳコード */
     zrnhurikomiyousinyuukinkbn ,         /* （連携用）振込用紙入金区分 */
     zrnhurikomiyousiokyksmno ,         /* （連携用）振込用紙お客さま番号 */
     zrnhurikomiyousikakuninno ,         /* （連携用）振込用紙確認番号 */
     zrnegsyokuinhurikomiymd ,         /* （連携用）営業職員振込年月日 */
     zrnvitkaiinno ,         /* （連携用）Ｖｉｔ会員番号 */
     zrnyobiv74           /* （連携用）予備項目Ｖ７４ */
FROM ZT_KesikomiSousinCreditRn_Z;