CREATE VIEW ZT_Sp2RnduyuSouseiritu6Rn AS SELECT
     zrnktgysyrymd ,         /* （連携用）結合用処理日 */
     zrnktgysyono ,         /* （連携用）結合用証券番号 */
     zrnktgyfilerenno ,         /* （連携用）結合用ファイル連番 */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnkawaserate ,         /* （連携用）為替レート */
     zrnkawaseratetekiyouymd ,         /* （連携用）為替レート適用年月日 */
     zrnkykjikawaserate ,         /* （連携用）契約時為替レート */
     zrnkykjikawaseratetkyuymd ,         /* （連携用）契約時為替レート適用年月日 */
     zrnkeiyakujiyoteiriritu ,         /* （連携用）契約時予定利率 */
     zrntumitateriritu ,         /* （連携用）積立利率 */
     zrnsrkyksjkkktyouseiriritu ,         /* （連携用）数理用契約時市場価格調整用利率 */
     zrnenkdtsbujsitihsyukngk ,         /* （連携用）円貨建死亡時最低保証金額 */
     zrnkaigomaebaraitkykarihyj ,         /* （連携用）介護前払特約あり表示 */
     zrnsuuriyouyobin1 ,         /* （連携用）数理用予備項目Ｎ１ */
     zrnsibouhyoukbn ,         /* （連携用）死亡表区分 */
     zrnmvatyouseikou ,         /* （連携用）ＭＶＡ調整項 */
     zrnnyuukintuukakbn ,         /* （連携用）入金通貨区分 */
     zrnhtnknkykliveonearhyj ,         /* （連携用）被転換契約ライブワン有表示 */
     zrnliveonepackagesyouhinkbn ,         /* （連携用）ライブワンパッケージ商品区分 */
     zrnhtnkngukisisttkknsnp ,         /* （連携用）被転換合計災疾月換算Ｐ */
     zrnwyendttargetmokuhyouritu ,         /* （連携用）円建Ｗターゲット目標率 */
     zrnsisuurendourate ,         /* （連携用）指数連動部分割合 */
     zrnsisuukbn ,         /* （連携用）指数区分 */
     zrnsuuriyouyobin2 ,         /* （連携用）数理用予備項目Ｎ２ */
     zrnsuuriyouyobin10x2 ,         /* （連携用）数理用予備項目Ｎ１０＿２ */
     zrnsuuriyouyobin10x3 ,         /* （連携用）数理用予備項目Ｎ１０＿３ */
     zrntmttknzoukaritujygn ,         /* （連携用）積立金増加率上限 */
     zrnsetteibairitu ,         /* （連携用）設定倍率 */
     zrnkykymdsisuu ,         /* （連携用）契約日指数 */
     zrnrendouritu ,         /* （連携用）連動率 */
     zrnyobin5 ,         /* （連携用）予備項目Ｎ５ */
     zrnyobin5x2 ,         /* （連携用）予備項目Ｎ５＿２ */
     zrnyobiv10x6 ,         /* （連携用）予備項目Ｖ１０＿６ */
     zrnyendttargetkijyunkingaku ,         /* （連携用）円建ターゲット基準金額 */
     zrnsisuurentumitatekin ,         /* （連携用）指数連動部分積立金 */
     zrntirttmtttumitatekin ,         /* （連携用）定率積立部分積立金 */
     zrnnksjitirttmttkn ,         /* （連携用）年金開始時定率積立金 */
     zrnnendomatutirttumitatekin ,         /* （連携用）年度末定率部分積立金 */
     zrnsyuptumitatekin ,         /* （連携用）主契約保険料積立金 */
     zrngaikadatenkgns ,         /* （連携用）外貨建年金原資 */
     zrntumitatekin ,         /* （連携用）積立金 */
     zrnkiharaikomip ,         /* （連携用）既払込Ｐ */
     zrngaikadatesyukeiyakup ,         /* （連携用）外貨建主契約Ｐ */
     zrnsitivkisnyukykjikwsrate ,         /* （連携用）最低Ｖ計算用契約時為替レート */
     zrnyobiv16           /* （連携用）予備項目Ｖ１６ */
FROM ZT_Sp2RnduyuSouseiritu6Rn_Z;