CREATE VIEW BT_HuriDenpyou AS SELECT
     densyskbn ,         /* 伝票用システム区分 */
     denrenno ,         /* 伝票データ連番 */
     edano ,         /* 枝番号 */
     torihikino ,         /* 取引番号 */
     keirisyskbn ,         /* 経理システム区分 */
     keirisyono ,         /* 経理用証券番号 */
     huridenatesakicd ,         /* 振替伝票宛先部課コード */
     tantocd ,         /* 担当コード */
     denymd ,         /* 伝票日付 */
     taisyakukbn ,         /* 貸借区分 */
     kanjyoukmkcd ,         /* 勘定科目コード */
     denkanjokamokucd ,         /* 伝票用勘定科目コード */
     jigyouhiutiwakecd ,         /* 事業費内訳コード */
     jigyouhiutiwakenm ,         /* 事業費内訳名 */
     tekiyoucd ,         /* 摘要コード */
     suitoubumoncd ,         /* 出納部門コード */
     denyenkagk ,         /* 伝票金額（円） */
     denyenkagk$ ,         /* 伝票金額（円）(通貨型) */
     huridenskskbn ,         /* 振替伝票作成区分 */
     denhnknhoukbn ,         /* 伝票用返金方法区分 */
     denshrhoukbn ,         /* 伝票用支払方法区分 */
     syoriYmd ,         /* 処理年月日 */
     syoricd ,         /* 処理コード */
     sougoukobetukbn ,         /* 総合個別区分 */
     furikaedenpyouitirenno ,         /* 振替伝票一連番号 */
     huridenpyoukyktuukakbn ,         /* 振替伝票用契約通貨区分 */
     tuukasyu ,         /* 通貨種類 */
     dengyoumucd ,         /* 伝票用業務コード */
     denkarikanjyono ,         /* 伝票用仮勘定番号 */
     densyorisyousaikbn ,         /* 伝票用処理詳細区分 */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BT_HuriDenpyou_Z;