CREATE VIEW ZT_SeisanDHaneiTuutiTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztykeysyono ,         /* （中継用）キー証券番号 */
     ztyhaitounendo ,         /* （中継用）配当年度 */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztyatesakiyno ,         /* （中継用）宛先郵便番号 */
     ztyrigikbn ,         /* （中継用）例外区分 */
     ztyhrkkeiro ,         /* （中継用）払込経路 */
     ztysclatosyono ,         /* （中継用）スクランブル後証券番号 */
     ztyatesakiadr1 ,         /* （中継用）宛先住所１ */
     ztyatesakiadr2 ,         /* （中継用）宛先住所２ */
     ztyatesakiadr3 ,         /* （中継用）宛先住所３ */
     ztyatena1 ,         /* （中継用）宛名１ */
     ztydai1syoukaisakifreearea1 ,         /* （中継用）第１照会先フリーエリア１ */
     ztydai1syoukaisakifreearea2 ,         /* （中継用）第１照会先フリーエリア２ */
     ztydai1syoukaisakifreearea3 ,         /* （中継用）第１照会先フリーエリア３ */
     ztydai1syoukaisakifreearea4 ,         /* （中継用）第１照会先フリーエリア４ */
     ztydai1syoukaisakifreearea5 ,         /* （中継用）第１照会先フリーエリア５ */
     ztysakunm ,         /* （中継用）作成番号 */
     ztysakuseiymdseireki ,         /* （中継用）作成年月日（西暦） */
     ztysyono ,         /* （中継用）証券番号 */
     ztykykymdseireki ,         /* （中継用）契約年月日（西暦） */
     ztyseisikihknnm ,         /* （中継用）正式保険名称 */
     ztyhhknnmkj17 ,         /* （中継用）被保険者名（漢字）（１７桁） */
     ztyfreearea37keta11 ,         /* （中継用）フリーエリア（３７桁）１＿１ */
     ztyfreearea37keta12 ,         /* （中継用）フリーエリア（３７桁）１＿２ */
     ztyfreearea37keta13 ,         /* （中継用）フリーエリア（３７桁）１＿３ */
     ztyfreearea37keta14 ,         /* （中継用）フリーエリア（３７桁）１＿４ */
     ztyfreearea37keta15 ,         /* （中継用）フリーエリア（３７桁）１＿５ */
     ztyfreearea37keta16 ,         /* （中継用）フリーエリア（３７桁）１＿６ */
     ztyfreearea37keta17 ,         /* （中継用）フリーエリア（３７桁）１＿７ */
     ztyfreearea37keta18 ,         /* （中継用）フリーエリア（３７桁）１＿８ */
     ztyfreearea37keta19 ,         /* （中継用）フリーエリア（３７桁）１＿９ */
     ztyfreearea37keta110 ,         /* （中継用）フリーエリア（３７桁）１＿１０ */
     ztyfreearea37keta111 ,         /* （中継用）フリーエリア（３７桁）１＿１１ */
     ztyfreearea37keta112 ,         /* （中継用）フリーエリア（３７桁）１＿１２ */
     ztyfreearea37keta113 ,         /* （中継用）フリーエリア（３７桁）１＿１３ */
     ztyfreearea37keta114 ,         /* （中継用）フリーエリア（３７桁）１＿１４ */
     ztyfreearea37keta115 ,         /* （中継用）フリーエリア（３７桁）１＿１５ */
     ztyfreearea37keta116 ,         /* （中継用）フリーエリア（３７桁）１＿１６ */
     ztyfreearea37keta117 ,         /* （中継用）フリーエリア（３７桁）１＿１７ */
     ztyfreearea37keta118 ,         /* （中継用）フリーエリア（３７桁）１＿１８ */
     ztyfreearea37keta119 ,         /* （中継用）フリーエリア（３７桁）１＿１９ */
     ztyfreearea37keta120 ,         /* （中継用）フリーエリア（３７桁）１＿２０ */
     ztyfreearea37keta121 ,         /* （中継用）フリーエリア（３７桁）１＿２１ */
     ztyfreearea37keta122 ,         /* （中継用）フリーエリア（３７桁）１＿２２ */
     ztyfreearea37keta123 ,         /* （中継用）フリーエリア（３７桁）１＿２３ */
     ztyfreearea37keta124 ,         /* （中継用）フリーエリア（３７桁）１＿２４ */
     ztyfreearea37keta125 ,         /* （中継用）フリーエリア（３７桁）１＿２５ */
     ztymidasi11 ,         /* （中継用）見出し１＿１ */
     ztytouduketorihouhou ,         /* （中継用）当Ｄ受取方法 */
     ztymidasi21 ,         /* （中継用）見出し２＿１ */
     ztykakuteidkgk ,         /* （中継用）確定Ｄ金額 */
     ztymidasi31 ,         /* （中継用）見出し３＿１ */
     ztynaiteidkgk ,         /* （中継用）内定Ｄ金額 */
     ztymidasi41 ,         /* （中継用）見出し４＿１ */
     ztyseisandkgk ,         /* （中継用）精算Ｄ金額 */
     ztyfreearea21 ,         /* （中継用）フリーエリア２＿１ */
     ztyfreearea22 ,         /* （中継用）フリーエリア２＿２ */
     ztyfreearea23 ,         /* （中継用）フリーエリア２＿３ */
     ztyfreearea24 ,         /* （中継用）フリーエリア２＿４ */
     ztyfreearea25 ,         /* （中継用）フリーエリア２＿５ */
     ztyyobiv141 ,         /* （中継用）予備項目Ｖ１４１ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SeisanDHaneiTuutiTy_Z;