CREATE VIEW ZT_RrtHndugtHknVKnsyuyuTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyuukourecordlength ,         /* （中継用）有効レコード長 */
     ztyrdwarea ,         /* （中継用）ＲＤＷ領域 */
     ztykeijyouym ,         /* （中継用）計上年月 */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztysotodasipmenkbn ,         /* （中継用）外出Ｐ免区分 */
     ztysotodasimanagehyouji ,         /* （中継用）外出満年令表示 */
     ztysuuriyouyobin6 ,         /* （中継用）数理用予備項目Ｎ６ */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztykbnkeiriyousegmentkbn ,         /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn ,         /* （中継用）区分経理用利源分析区分 */
     ztysuurisyuruicd ,         /* （中継用）数理種類コード */
     ztysuuriyouyobin6x2 ,         /* （中継用）数理用予備項目Ｎ６＿２ */
     ztyyobiv8 ,         /* （中継用）予備項目Ｖ８ */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztykuriagekurisagekbn ,         /* （中継用）繰上げ繰下げ区分 */
     ztysyukeiyakupwaribikikbn ,         /* （中継用）主契約Ｐ割引区分 */
     ztyjikaipjyuutouym2 ,         /* （中継用）次回Ｐ充当年月２ */
     ztysyokainyknjikawasekjnymd ,         /* （中継用）初回入金時為替基準年月日 */
     ztysuuriyouyobin6x3 ,         /* （中継用）数理用予備項目Ｎ６＿３ */
     ztyyobiv7 ,         /* （中継用）予備項目Ｖ７ */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztykimatukawaserate ,         /* （中継用）期末為替レート */
     ztyyoteiriritun5 ,         /* （中継用）予定利率Ｎ５ */
     ztyyoteiriritun5x2 ,         /* （中継用）予定利率Ｎ５＿２ */
     ztyyoteiriritun5x3 ,         /* （中継用）予定利率Ｎ５＿３ */
     ztyyoteiriritun5x4 ,         /* （中継用）予定利率Ｎ５＿４ */
     ztyyoteiriritun5x5 ,         /* （中継用）予定利率Ｎ５＿５ */
     ztyyoteiriritun5x6 ,         /* （中継用）予定利率Ｎ５＿６ */
     ztyyoteiriritun5x7 ,         /* （中継用）予定利率Ｎ５＿７ */
     ztyyoteiriritun5x8 ,         /* （中継用）予定利率Ｎ５＿８ */
     ztyyoteiriritun5x9 ,         /* （中継用）予定利率Ｎ５＿９ */
     ztyyoteiriritun5x10 ,         /* （中継用）予定利率Ｎ５＿１０ */
     ztyyoteiriritun5x11 ,         /* （中継用）予定利率Ｎ５＿１１ */
     ztyyoteiriritun5x12 ,         /* （中継用）予定利率Ｎ５＿１２ */
     ztyyoteiriritun5x13 ,         /* （中継用）予定利率Ｎ５＿１３ */
     ztyyoteiriritun5x14 ,         /* （中継用）予定利率Ｎ５＿１４ */
     ztyyoteiriritun5x15 ,         /* （中継用）予定利率Ｎ５＿１５ */
     ztyyoteiriritun5x16 ,         /* （中継用）予定利率Ｎ５＿１６ */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztysyuptumitatekin ,         /* （中継用）主契約保険料積立金 */
     ztyptumitatekin ,         /* （中継用）保険料積立金 */
     ztyptumitatekinx2 ,         /* （中継用）保険料積立金＿２ */
     ztyptumitatekinx3 ,         /* （中継用）保険料積立金＿３ */
     ztyptumitatekinx4 ,         /* （中継用）保険料積立金＿４ */
     ztyptumitatekinx5 ,         /* （中継用）保険料積立金＿５ */
     ztyptumitatekinx6 ,         /* （中継用）保険料積立金＿６ */
     ztyptumitatekinx7 ,         /* （中継用）保険料積立金＿７ */
     ztyptumitatekinx8 ,         /* （中継用）保険料積立金＿８ */
     ztyptumitatekinx9 ,         /* （中継用）保険料積立金＿９ */
     ztyptumitatekinx10 ,         /* （中継用）保険料積立金＿１０ */
     ztyptumitatekinx11 ,         /* （中継用）保険料積立金＿１１ */
     ztyptumitatekinx12 ,         /* （中継用）保険料積立金＿１２ */
     ztyptumitatekinx13 ,         /* （中継用）保険料積立金＿１３ */
     ztyptumitatekinx14 ,         /* （中継用）保険料積立金＿１４ */
     ztyptumitatekinx15 ,         /* （中継用）保険料積立金＿１５ */
     ztyptumitatekinx16 ,         /* （中継用）保険料積立金＿１６ */
     ztygaikadatejyuutoup ,         /* （中継用）外貨建充当Ｐ */
     ztygaikadatejyuutoupx2 ,         /* （中継用）外貨建充当Ｐ＿２ */
     ztygaikadatejyuutoupx3 ,         /* （中継用）外貨建充当Ｐ＿３ */
     ztygaikadatejyuutoupx4 ,         /* （中継用）外貨建充当Ｐ＿４ */
     ztygaikadatejyuutoupx5 ,         /* （中継用）外貨建充当Ｐ＿５ */
     ztygaikadatejyuutoupx6 ,         /* （中継用）外貨建充当Ｐ＿６ */
     ztygaikadatejyuutoupx7 ,         /* （中継用）外貨建充当Ｐ＿７ */
     ztygaikadatejyuutoupx8 ,         /* （中継用）外貨建充当Ｐ＿８ */
     ztygaikadatejyuutoupx9 ,         /* （中継用）外貨建充当Ｐ＿９ */
     ztygaikadatejyuutoupx10 ,         /* （中継用）外貨建充当Ｐ＿１０ */
     ztygaikadatejyuutoupx11 ,         /* （中継用）外貨建充当Ｐ＿１１ */
     ztygaikadatejyuutoupx12 ,         /* （中継用）外貨建充当Ｐ＿１２ */
     ztygaikadatejyuutoupx13 ,         /* （中継用）外貨建充当Ｐ＿１３ */
     ztygaikadatejyuutoupx14 ,         /* （中継用）外貨建充当Ｐ＿１４ */
     ztygaikadatejyuutoupx15 ,         /* （中継用）外貨建充当Ｐ＿１５ */
     ztygaikadatejyuutoupx16 ,         /* （中継用）外貨建充当Ｐ＿１６ */
     ztysykykkitmttvkeisanym1 ,         /* （中継用）主契約既積立Ｖ計算年月１ */
     ztysykykkitmttv1 ,         /* （中継用）主契約既積立Ｖ１ */
     ztysykykkitmttvkeisanym2 ,         /* （中継用）主契約既積立Ｖ計算年月２ */
     ztysykykkitmttv2 ,         /* （中継用）主契約既積立Ｖ２ */
     ztyrrthnduhknvkisovkisnyu1 ,         /* （中継用）利率変動保険Ｖ基礎Ｖ計算用１ */
     ztyrrthnduhknvkisovkisnyu2 ,         /* （中継用）利率変動保険Ｖ基礎Ｖ計算用２ */
     ztyrrthnduhknvkisovkisnyu3 ,         /* （中継用）利率変動保険Ｖ基礎Ｖ計算用３ */
     ztyrrthnduhknvkisovkisnyu4 ,         /* （中継用）利率変動保険Ｖ基礎Ｖ計算用４ */
     ztyrrthnduhknvkiso ,         /* （中継用）利率変動保険Ｖ基礎Ｖ */
     ztysuuriyouyobin9 ,         /* （中継用）数理用予備項目Ｎ９ */
     ztyyobiv14 ,         /* （中継用）予備項目Ｖ１４ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_RrtHndugtHknVKnsyuyuTy_Z;