CREATE VIEW BM_RateNenkinPkisoV AS SELECT
     palnenkinsisutemusyurui ,         /* ＰＡＬ年金システム種類 */
     palnenkinsyuruikigou ,         /* ＰＡＬ年金種類記号 */
     palnenkinkigousedaicode ,         /* ＰＡＬ年金記号世代コード */
     palnenkinsiharaikikan ,         /* ＰＡＬ年金支払期間 */
     palnnknksgyoteiriritucode ,         /* ＰＡＬ年金開始後予定利率コード */
     palnnknksgjmtesuuryoucode ,         /* ＰＡＬ年金開始後事務手数料コード */
     nenkinkaisigopkisovrate00 ,         /* 年金開始後Ｖレート００ */
     nenkinkaisigopkisovrate01 ,         /* 年金開始後Ｖレート０１ */
     nenkinkaisigopkisovrate02 ,         /* 年金開始後Ｖレート０２ */
     nenkinkaisigopkisovrate03 ,         /* 年金開始後Ｖレート０３ */
     nenkinkaisigopkisovrate04 ,         /* 年金開始後Ｖレート０４ */
     nenkinkaisigopkisovrate05 ,         /* 年金開始後Ｖレート０５ */
     nenkinkaisigopkisovrate06 ,         /* 年金開始後Ｖレート０６ */
     nenkinkaisigopkisovrate07 ,         /* 年金開始後Ｖレート０７ */
     nenkinkaisigopkisovrate08 ,         /* 年金開始後Ｖレート０８ */
     nenkinkaisigopkisovrate09 ,         /* 年金開始後Ｖレート０９ */
     nenkinkaisigopkisovrate10 ,         /* 年金開始後Ｖレート１０ */
     nenkinkaisigopkisovrate11 ,         /* 年金開始後Ｖレート１１ */
     nenkinkaisigopkisovrate12 ,         /* 年金開始後Ｖレート１２ */
     nenkinkaisigopkisovrate13 ,         /* 年金開始後Ｖレート１３ */
     nenkinkaisigopkisovrate14 ,         /* 年金開始後Ｖレート１４ */
     nenkinkaisigopkisovrate15 ,         /* 年金開始後Ｖレート１５ */
     nenkinkaisigopkisovrate16 ,         /* 年金開始後Ｖレート１６ */
     nenkinkaisigopkisovrate17 ,         /* 年金開始後Ｖレート１７ */
     nenkinkaisigopkisovrate18 ,         /* 年金開始後Ｖレート１８ */
     nenkinkaisigopkisovrate19 ,         /* 年金開始後Ｖレート１９ */
     nenkinkaisigopkisovrate20 ,         /* 年金開始後Ｖレート２０ */
     nenkinkaisigopkisovrate21 ,         /* 年金開始後Ｖレート２１ */
     nenkinkaisigopkisovrate22 ,         /* 年金開始後Ｖレート２２ */
     nenkinkaisigopkisovrate23 ,         /* 年金開始後Ｖレート２３ */
     nenkinkaisigopkisovrate24 ,         /* 年金開始後Ｖレート２４ */
     nenkinkaisigopkisovrate25 ,         /* 年金開始後Ｖレート２５ */
     nenkinkaisigopkisovrate26 ,         /* 年金開始後Ｖレート２６ */
     nenkinkaisigopkisovrate27 ,         /* 年金開始後Ｖレート２７ */
     nenkinkaisigopkisovrate28 ,         /* 年金開始後Ｖレート２８ */
     nenkinkaisigopkisovrate29 ,         /* 年金開始後Ｖレート２９ */
     nenkinkaisigopkisovrate30 ,         /* 年金開始後Ｖレート３０ */
     nenkinkaisigopkisovrate31 ,         /* 年金開始後Ｖレート３１ */
     nenkinkaisigopkisovrate32 ,         /* 年金開始後Ｖレート３２ */
     nenkinkaisigopkisovrate33 ,         /* 年金開始後Ｖレート３３ */
     nenkinkaisigopkisovrate34 ,         /* 年金開始後Ｖレート３４ */
     nenkinkaisigopkisovrate35 ,         /* 年金開始後Ｖレート３５ */
     nenkinkaisigopkisovrate36 ,         /* 年金開始後Ｖレート３６ */
     nenkinkaisigopkisovrate37 ,         /* 年金開始後Ｖレート３７ */
     nenkinkaisigopkisovrate38 ,         /* 年金開始後Ｖレート３８ */
     nenkinkaisigopkisovrate39 ,         /* 年金開始後Ｖレート３９ */
     nenkinkaisigopkisovrate40 ,         /* 年金開始後Ｖレート４０ */
     nenkinkaisigopkisovrate41 ,         /* 年金開始後Ｖレート４１ */
     nenkinkaisigopkisovrate42 ,         /* 年金開始後Ｖレート４２ */
     nenkinkaisigopkisovrate43 ,         /* 年金開始後Ｖレート４３ */
     nenkinkaisigopkisovrate44 ,         /* 年金開始後Ｖレート４４ */
     nenkinkaisigopkisovrate45 ,         /* 年金開始後Ｖレート４５ */
     nenkinkaisigopkisovrate46 ,         /* 年金開始後Ｖレート４６ */
     nenkinkaisigopkisovrate47 ,         /* 年金開始後Ｖレート４７ */
     nenkinkaisigopkisovrate48 ,         /* 年金開始後Ｖレート４８ */
     nenkinkaisigopkisovrate49 ,         /* 年金開始後Ｖレート４９ */
     nenkinkaisigopkisovrate50 ,         /* 年金開始後Ｖレート５０ */
     nenkinkaisigopkisovrate51 ,         /* 年金開始後Ｖレート５１ */
     nenkinkaisigopkisovrate52 ,         /* 年金開始後Ｖレート５２ */
     nenkinkaisigopkisovrate53 ,         /* 年金開始後Ｖレート５３ */
     nenkinkaisigopkisovrate54 ,         /* 年金開始後Ｖレート５４ */
     nenkinkaisigopkisovrate55 ,         /* 年金開始後Ｖレート５５ */
     nenkinkaisigopkisovrate56 ,         /* 年金開始後Ｖレート５６ */
     nenkinkaisigopkisovrate57 ,         /* 年金開始後Ｖレート５７ */
     nenkinkaisigopkisovrate58 ,         /* 年金開始後Ｖレート５８ */
     nenkinkaisigopkisovrate59 ,         /* 年金開始後Ｖレート５９ */
     nenkinkaisigopkisovrate60 ,         /* 年金開始後Ｖレート６０ */
     nenkinkaisigopkisovrate61 ,         /* 年金開始後Ｖレート６１ */
     nenkinkaisigopkisovrate62 ,         /* 年金開始後Ｖレート６２ */
     nenkinkaisigopkisovrate63 ,         /* 年金開始後Ｖレート６３ */
     nenkinkaisigopkisovrate64 ,         /* 年金開始後Ｖレート６４ */
     nenkinkaisigopkisovrate65 ,         /* 年金開始後Ｖレート６５ */
     nenkinkaisigopkisovrate66 ,         /* 年金開始後Ｖレート６６ */
     nenkinkaisigopkisovrate67 ,         /* 年金開始後Ｖレート６７ */
     nenkinkaisigopkisovrate68 ,         /* 年金開始後Ｖレート６８ */
     nenkinkaisigopkisovrate69 ,         /* 年金開始後Ｖレート６９ */
     nenkinkaisigopkisovrate70 ,         /* 年金開始後Ｖレート７０ */
     nenkinkaisigopkisovrate71 ,         /* 年金開始後Ｖレート７１ */
     nenkinkaisigopkisovrate72 ,         /* 年金開始後Ｖレート７２ */
     nenkinkaisigopkisovrate73 ,         /* 年金開始後Ｖレート７３ */
     nenkinkaisigopkisovrate74 ,         /* 年金開始後Ｖレート７４ */
     nenkinkaisigopkisovrate75 ,         /* 年金開始後Ｖレート７５ */
     nenkinkaisigopkisovrate76 ,         /* 年金開始後Ｖレート７６ */
     nenkinkaisigopkisovrate77 ,         /* 年金開始後Ｖレート７７ */
     nenkinkaisigopkisovrate78 ,         /* 年金開始後Ｖレート７８ */
     nenkinkaisigopkisovrate79 ,         /* 年金開始後Ｖレート７９ */
     nenkinkaisigopkisovrate80 ,         /* 年金開始後Ｖレート８０ */
     nenkinkaisigopkisovrate81 ,         /* 年金開始後Ｖレート８１ */
     nenkinkaisigopkisovrate82 ,         /* 年金開始後Ｖレート８２ */
     nenkinkaisigopkisovrate83 ,         /* 年金開始後Ｖレート８３ */
     nenkinkaisigopkisovrate84 ,         /* 年金開始後Ｖレート８４ */
     nenkinkaisigopkisovrate85 ,         /* 年金開始後Ｖレート８５ */
     nenkinkaisigopkisovrate86 ,         /* 年金開始後Ｖレート８６ */
     nenkinkaisigopkisovrate87 ,         /* 年金開始後Ｖレート８７ */
     nenkinkaisigopkisovrate88 ,         /* 年金開始後Ｖレート８８ */
     nenkinkaisigopkisovrate89 ,         /* 年金開始後Ｖレート８９ */
     nenkinkaisigopkisovrate90 ,         /* 年金開始後Ｖレート９０ */
     nenkinkaisigopkisovrate91 ,         /* 年金開始後Ｖレート９１ */
     nenkinkaisigopkisovrate92 ,         /* 年金開始後Ｖレート９２ */
     nenkinkaisigopkisovrate93 ,         /* 年金開始後Ｖレート９３ */
     nenkinkaisigopkisovrate94 ,         /* 年金開始後Ｖレート９４ */
     nenkinkaisigopkisovrate95 ,         /* 年金開始後Ｖレート９５ */
     nenkinkaisigopkisovrate96 ,         /* 年金開始後Ｖレート９６ */
     nenkinkaisigopkisovrate97 ,         /* 年金開始後Ｖレート９７ */
     nenkinkaisigopkisovrate98 ,         /* 年金開始後Ｖレート９８ */
     nenkinkaisigopkisovrate99 ,         /* 年金開始後Ｖレート９９ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BM_RateNenkinPkisoV_Z;