CREATE VIEW ZT_RrtHndugtHknVKnsyuyuRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnyuukourecordlength ,         /* （連携用）有効レコード長 */
     zrnrdwarea ,         /* （連携用）ＲＤＷ領域 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrndatakanrino ,         /* （連携用）データ管理番号 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn ,         /* （連携用）外出Ｐ免区分 */
     zrnsotodasimanagehyouji ,         /* （連携用）外出満年令表示 */
     zrnsuuriyouyobin6 ,         /* （連携用）数理用予備項目Ｎ６ */
     zrnyobiv12 ,         /* （連携用）予備項目Ｖ１２ */
     zrnkbnkeiriyousegmentkbn ,         /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn ,         /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd ,         /* （連携用）数理種類コード */
     zrnsuuriyouyobin6x2 ,         /* （連携用）数理用予備項目Ｎ６＿２ */
     zrnyobiv8 ,         /* （連携用）予備項目Ｖ８ */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrnkuriagekurisagekbn ,         /* （連携用）繰上げ繰下げ区分 */
     zrnsyukeiyakupwaribikikbn ,         /* （連携用）主契約Ｐ割引区分 */
     zrnjikaipjyuutouym2 ,         /* （連携用）次回Ｐ充当年月２ */
     zrnsyokainyknjikawasekjnymd ,         /* （連携用）初回入金時為替基準年月日 */
     zrnsuuriyouyobin6x3 ,         /* （連携用）数理用予備項目Ｎ６＿３ */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnkimatukawaserate ,         /* （連携用）期末為替レート */
     zrnyoteiriritun5 ,         /* （連携用）予定利率Ｎ５ */
     zrnyoteiriritun5x2 ,         /* （連携用）予定利率Ｎ５＿２ */
     zrnyoteiriritun5x3 ,         /* （連携用）予定利率Ｎ５＿３ */
     zrnyoteiriritun5x4 ,         /* （連携用）予定利率Ｎ５＿４ */
     zrnyoteiriritun5x5 ,         /* （連携用）予定利率Ｎ５＿５ */
     zrnyoteiriritun5x6 ,         /* （連携用）予定利率Ｎ５＿６ */
     zrnyoteiriritun5x7 ,         /* （連携用）予定利率Ｎ５＿７ */
     zrnyoteiriritun5x8 ,         /* （連携用）予定利率Ｎ５＿８ */
     zrnyoteiriritun5x9 ,         /* （連携用）予定利率Ｎ５＿９ */
     zrnyoteiriritun5x10 ,         /* （連携用）予定利率Ｎ５＿１０ */
     zrnyoteiriritun5x11 ,         /* （連携用）予定利率Ｎ５＿１１ */
     zrnyoteiriritun5x12 ,         /* （連携用）予定利率Ｎ５＿１２ */
     zrnyoteiriritun5x13 ,         /* （連携用）予定利率Ｎ５＿１３ */
     zrnyoteiriritun5x14 ,         /* （連携用）予定利率Ｎ５＿１４ */
     zrnyoteiriritun5x15 ,         /* （連携用）予定利率Ｎ５＿１５ */
     zrnyoteiriritun5x16 ,         /* （連携用）予定利率Ｎ５＿１６ */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrnsyuptumitatekin ,         /* （連携用）主契約保険料積立金 */
     zrnptumitatekin ,         /* （連携用）保険料積立金 */
     zrnptumitatekinx2 ,         /* （連携用）保険料積立金＿２ */
     zrnptumitatekinx3 ,         /* （連携用）保険料積立金＿３ */
     zrnptumitatekinx4 ,         /* （連携用）保険料積立金＿４ */
     zrnptumitatekinx5 ,         /* （連携用）保険料積立金＿５ */
     zrnptumitatekinx6 ,         /* （連携用）保険料積立金＿６ */
     zrnptumitatekinx7 ,         /* （連携用）保険料積立金＿７ */
     zrnptumitatekinx8 ,         /* （連携用）保険料積立金＿８ */
     zrnptumitatekinx9 ,         /* （連携用）保険料積立金＿９ */
     zrnptumitatekinx10 ,         /* （連携用）保険料積立金＿１０ */
     zrnptumitatekinx11 ,         /* （連携用）保険料積立金＿１１ */
     zrnptumitatekinx12 ,         /* （連携用）保険料積立金＿１２ */
     zrnptumitatekinx13 ,         /* （連携用）保険料積立金＿１３ */
     zrnptumitatekinx14 ,         /* （連携用）保険料積立金＿１４ */
     zrnptumitatekinx15 ,         /* （連携用）保険料積立金＿１５ */
     zrnptumitatekinx16 ,         /* （連携用）保険料積立金＿１６ */
     zrngaikadatejyuutoup ,         /* （連携用）外貨建充当Ｐ */
     zrngaikadatejyuutoupx2 ,         /* （連携用）外貨建充当Ｐ＿２ */
     zrngaikadatejyuutoupx3 ,         /* （連携用）外貨建充当Ｐ＿３ */
     zrngaikadatejyuutoupx4 ,         /* （連携用）外貨建充当Ｐ＿４ */
     zrngaikadatejyuutoupx5 ,         /* （連携用）外貨建充当Ｐ＿５ */
     zrngaikadatejyuutoupx6 ,         /* （連携用）外貨建充当Ｐ＿６ */
     zrngaikadatejyuutoupx7 ,         /* （連携用）外貨建充当Ｐ＿７ */
     zrngaikadatejyuutoupx8 ,         /* （連携用）外貨建充当Ｐ＿８ */
     zrngaikadatejyuutoupx9 ,         /* （連携用）外貨建充当Ｐ＿９ */
     zrngaikadatejyuutoupx10 ,         /* （連携用）外貨建充当Ｐ＿１０ */
     zrngaikadatejyuutoupx11 ,         /* （連携用）外貨建充当Ｐ＿１１ */
     zrngaikadatejyuutoupx12 ,         /* （連携用）外貨建充当Ｐ＿１２ */
     zrngaikadatejyuutoupx13 ,         /* （連携用）外貨建充当Ｐ＿１３ */
     zrngaikadatejyuutoupx14 ,         /* （連携用）外貨建充当Ｐ＿１４ */
     zrngaikadatejyuutoupx15 ,         /* （連携用）外貨建充当Ｐ＿１５ */
     zrngaikadatejyuutoupx16 ,         /* （連携用）外貨建充当Ｐ＿１６ */
     zrnsykykkitmttvkeisanym1 ,         /* （連携用）主契約既積立Ｖ計算年月１ */
     zrnsykykkitmttv1 ,         /* （連携用）主契約既積立Ｖ１ */
     zrnsykykkitmttvkeisanym2 ,         /* （連携用）主契約既積立Ｖ計算年月２ */
     zrnsykykkitmttv2 ,         /* （連携用）主契約既積立Ｖ２ */
     zrnrrthnduhknvkisovkisnyu1 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用１ */
     zrnrrthnduhknvkisovkisnyu2 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用２ */
     zrnrrthnduhknvkisovkisnyu3 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用３ */
     zrnrrthnduhknvkisovkisnyu4 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用４ */
     zrnrrthnduhknvkiso ,         /* （連携用）利率変動保険Ｖ基礎Ｖ */
     zrnsuuriyouyobin9 ,         /* （連携用）数理用予備項目Ｎ９ */
     zrnyobiv14           /* （連携用）予備項目Ｖ１４ */
FROM ZT_RrtHndugtHknVKnsyuyuRn_Z;