CREATE VIEW IT_KouzahuriStartAnnai AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     tyouhyouymd ,         /* 帳票作成日 */
     kyknmkj ,         /* 契約者名（漢字） */
     tsinyno ,         /* 通信先郵便番号 */
     tsinadr1kj ,         /* 通信先住所１（漢字） */
     tsinadr2kj ,         /* 通信先住所２（漢字） */
     tsinadr3kj ,         /* 通信先住所３（漢字） */
     kykymd ,         /* 契約日 */
     hhknnmkj ,         /* 被保険者名（漢字） */
     syouhnnm ,         /* 商品名 */
     tuutinm ,         /* 通知名称 */
     aisatumongon1 ,         /* 挨拶文言１ */
     aisatumongon2 ,         /* 挨拶文言２ */
     aisatumongon3 ,         /* 挨拶文言３ */
     aisatumongon4 ,         /* 挨拶文言４ */
     aisatumongon5 ,         /* 挨拶文言５ */
     kzhurikaeonegai1 ,         /* 口座振替についてのお願い１ */
     kzhurikaeonegai2 ,         /* 口座振替についてのお願い２ */
     kzhurikaeonegai3 ,         /* 口座振替についてのお願い３ */
     kzhurikaeonegai4 ,         /* 口座振替についてのお願い４ */
     kzhurikaeonegai5 ,         /* 口座振替についてのお願い５ */
     kzhurikaeonegai6 ,         /* 口座振替についてのお願い６ */
     kzhurikaeonegai7 ,         /* 口座振替についてのお願い７ */
     kzhurikaeonegai8 ,         /* 口座振替についてのお願い８ */
     kzhurikaeonegai9 ,         /* 口座振替についてのお願い９ */
     kzhurikaeonegai10 ,         /* 口座振替についてのお願い１０ */
     kzhurikaeonegai11 ,         /* 口座振替についてのお願い１１ */
     kzhurikaeonegai12 ,         /* 口座振替についてのお願い１２ */
     kzhurikaeonegai13 ,         /* 口座振替についてのお願い１３ */
     kzhurikaeonegai14 ,         /* 口座振替についてのお願い１４ */
     kzhurikaeonegai15 ,         /* 口座振替についてのお願い１５ */
     tkbriphurikaeyoteigk ,         /* 月払保険料（振替予定金額） */
     hurikaekzhosokumongon ,         /* 振替口座補足文言 */
     hurikaekz1 ,         /* 振替口座１ */
     hurikaekz2 ,         /* 振替口座２ */
     hurikaekz3 ,         /* 振替口座３ */
     hurikaekz4 ,         /* 振替口座４ */
     hurikaekz5 ,         /* 振替口座５ */
     toiawasesosikinmkj ,         /* 問合せ先組織名（漢字） */
     toiawaseyno ,         /* 問合せ先郵便番号 */
     toiawaseadr1kj ,         /* 問合せ先住所１（漢字） */
     toiawaseadr2kj ,         /* 問合せ先住所２（漢字） */
     toiawaseadr3kj ,         /* 問合せ先住所３（漢字） */
     toiawasetelno ,         /* 問合せ先電話番号 */
     toiawaseteluktkkanou1 ,         /* 問合せ先電話受付可能時間１ */
     toiawaseteluktkkanou2 ,         /* 問合せ先電話受付可能時間２ */
     toiawasesosikinmkj2 ,         /* 第２問合せ先組織名（漢字） */
     toiawasetelno2 ,         /* 第２問合せ先電話番号 */
     syoruiCd ,         /* 書類コード */
     hassoukbn ,         /* 発送区分 */
     kzhuristartanfreearea1 ,         /* 口座振替開始案内フリーエリア１ */
     kzhuristartanfreearea2 ,         /* 口座振替開始案内フリーエリア２ */
     kzhuristartanfreearea3 ,         /* 口座振替開始案内フリーエリア３ */
     kzhuristartanfreearea4 ,         /* 口座振替開始案内フリーエリア４ */
     kzhuristartanfreearea5 ,         /* 口座振替開始案内フリーエリア５ */
     kzhuristartanfreearea6 ,         /* 口座振替開始案内フリーエリア６ */
     kzhuristartanfreearea7 ,         /* 口座振替開始案内フリーエリア７ */
     kzhuristartanfreearea8 ,         /* 口座振替開始案内フリーエリア８ */
     kzhuristartanfreearea9 ,         /* 口座振替開始案内フリーエリア９ */
     kzhuristartanfreearea10 ,         /* 口座振替開始案内フリーエリア１０ */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_KouzahuriStartAnnai_Z;