CREATE VIEW IT_SinkokuyokokuTuuti AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     nendo ,         /* 年度 */
     kktyhysksitisykbn ,         /* 契約管理帳票作成対象区分 */
     tyouhyouymd ,         /* 帳票作成日 */
     tyouhyouprtymd ,         /* 帳票作成日（印刷用） */
     renno ,         /* 連番 */
     tekiyouseidokbn ,         /* 適用制度区分 */
     pjyutoustartyoteiym ,         /* 保険料充当開始予定年月 */
     pjyutouendyoteiym ,         /* 保険料充当終了予定年月 */
     pjyutouyoteikkntukisuu ,         /* 保険料充当予定期間月数 */
     kyknmkj ,         /* 契約者名（漢字） */
     uktnmkj ,         /* 受取人名（漢字） */
     hknsyuruinmrykkj ,         /* 保険種類略称（漢字） */
     kykymd ,         /* 契約日 */
     hknkknsmnkbnsyu ,         /* 保険期間歳満期区分（主契約） */
     hknkknsyu ,         /* 保険期間（主契約） */
     nenkanhrkkaisuu ,         /* 年間払込回数 */
     kykjyoutai ,         /* 契約状態 */
     yuukousyoumetukbn ,         /* 有効消滅区分 */
     haitoukinuketorihoukbn ,         /* 配当金受取方法区分 */
     oldippanykkp ,         /* 旧制度一般予告保険料 */
     oldippanykkp$ ,         /* 旧制度一般予告保険料(通貨型) */
     oldippanykkhaitoukin ,         /* 旧制度一般予告配当金 */
     oldippanykkhaitoukin$ ,         /* 旧制度一般予告配当金(通貨型) */
     oldippanykksyoumeigk ,         /* 旧制度一般予告証明額 */
     oldippanykksyoumeigk$ ,         /* 旧制度一般予告証明額(通貨型) */
     newippanykkp ,         /* 新制度一般予告保険料 */
     newippanykkp$ ,         /* 新制度一般予告保険料(通貨型) */
     newippanykkhaitoukin ,         /* 新制度一般予告配当金 */
     newippanykkhaitoukin$ ,         /* 新制度一般予告配当金(通貨型) */
     newippanykksyoumeigk ,         /* 新制度一般予告証明額 */
     newippanykksyoumeigk$ ,         /* 新制度一般予告証明額(通貨型) */
     newiryouykkp ,         /* 新制度介護医療予告保険料 */
     newiryouykkp$ ,         /* 新制度介護医療予告保険料(通貨型) */
     newiryouykkhaitoukin ,         /* 新制度介護医療予告配当金 */
     newiryouykkhaitoukin$ ,         /* 新制度介護医療予告配当金(通貨型) */
     newiryouykksyoumeigk ,         /* 新制度介護医療予告証明額 */
     newiryouykksyoumeigk$ ,         /* 新制度介護医療予告証明額(通貨型) */
     newnenkinykkp ,         /* 新制度年金予告保険料 */
     newnenkinykkp$ ,         /* 新制度年金予告保険料(通貨型) */
     newnenkinykkhaitoukin ,         /* 新制度年金予告配当金 */
     newnenkinykkhaitoukin$ ,         /* 新制度年金予告配当金(通貨型) */
     newnenkinykksyoumeigk ,         /* 新制度年金予告証明額 */
     newnenkinykksyoumeigk$ ,         /* 新制度年金予告証明額(通貨型) */
     tsinyno ,         /* 通信先郵便番号 */
     tsinadr1kj ,         /* 通信先住所１（漢字） */
     tsinadr2kj ,         /* 通信先住所２（漢字） */
     tsinadr3kj ,         /* 通信先住所３（漢字） */
     tsinadr4kj ,         /* 通信先住所４（漢字） */
     drtencd ,         /* 代理店コード */
     drtennmkj ,         /* 代理店名（漢字） */
     rtratkicd ,         /* （帳票用）取扱コード */
     rtyouhyoucd ,         /* （帳票用）帳票コード */
     tyhyrenrakusikibetukbn ,         /* 帳票連絡先識別区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_SinkokuyokokuTuuti_Z;