CREATE VIEW BM_RateV AS SELECT
     palhokensyuruikigou ,         /* ＰＡＬ保険種類記号 */
     palhokensyuruikigousdicode ,         /* ＰＡＬ保険種類記号世代コード */
     palyoteiriritu ,         /* ＰＡＬ予定利率 */
     palpmencode ,         /* ＰＡＬＰ免コード */
     palharaikomikaisuu ,         /* ＰＡＬ払込回数 */
     palhhknsei ,         /* ＰＡＬ被保険者性別 */
     palkeiyakujihhknnen ,         /* ＰＡＬ契約時被保険者年令 */
     palsaimankihyouji ,         /* ＰＡＬ才満期契約表示 */
     palhokenkikan ,         /* ＰＡＬ保険期間 */
     palpharaikomikikan ,         /* ＰＡＬＰ払込期間 */
     vrate00 ,         /* Ｖレート００ */
     vrate01 ,         /* Ｖレート０１ */
     vrate02 ,         /* Ｖレート０２ */
     vrate03 ,         /* Ｖレート０３ */
     vrate04 ,         /* Ｖレート０４ */
     vrate05 ,         /* Ｖレート０５ */
     vrate06 ,         /* Ｖレート０６ */
     vrate07 ,         /* Ｖレート０７ */
     vrate08 ,         /* Ｖレート０８ */
     vrate09 ,         /* Ｖレート０９ */
     vrate10 ,         /* Ｖレート１０ */
     vrate11 ,         /* Ｖレート１１ */
     vrate12 ,         /* Ｖレート１２ */
     vrate13 ,         /* Ｖレート１３ */
     vrate14 ,         /* Ｖレート１４ */
     vrate15 ,         /* Ｖレート１５ */
     vrate16 ,         /* Ｖレート１６ */
     vrate17 ,         /* Ｖレート１７ */
     vrate18 ,         /* Ｖレート１８ */
     vrate19 ,         /* Ｖレート１９ */
     vrate20 ,         /* Ｖレート２０ */
     vrate21 ,         /* Ｖレート２１ */
     vrate22 ,         /* Ｖレート２２ */
     vrate23 ,         /* Ｖレート２３ */
     vrate24 ,         /* Ｖレート２４ */
     vrate25 ,         /* Ｖレート２５ */
     vrate26 ,         /* Ｖレート２６ */
     vrate27 ,         /* Ｖレート２７ */
     vrate28 ,         /* Ｖレート２８ */
     vrate29 ,         /* Ｖレート２９ */
     vrate30 ,         /* Ｖレート３０ */
     vrate31 ,         /* Ｖレート３１ */
     vrate32 ,         /* Ｖレート３２ */
     vrate33 ,         /* Ｖレート３３ */
     vrate34 ,         /* Ｖレート３４ */
     vrate35 ,         /* Ｖレート３５ */
     vrate36 ,         /* Ｖレート３６ */
     vrate37 ,         /* Ｖレート３７ */
     vrate38 ,         /* Ｖレート３８ */
     vrate39 ,         /* Ｖレート３９ */
     vrate40 ,         /* Ｖレート４０ */
     vrate41 ,         /* Ｖレート４１ */
     vrate42 ,         /* Ｖレート４２ */
     vrate43 ,         /* Ｖレート４３ */
     vrate44 ,         /* Ｖレート４４ */
     vrate45 ,         /* Ｖレート４５ */
     vrate46 ,         /* Ｖレート４６ */
     vrate47 ,         /* Ｖレート４７ */
     vrate48 ,         /* Ｖレート４８ */
     vrate49 ,         /* Ｖレート４９ */
     vrate50 ,         /* Ｖレート５０ */
     vrate51 ,         /* Ｖレート５１ */
     vrate52 ,         /* Ｖレート５２ */
     vrate53 ,         /* Ｖレート５３ */
     vrate54 ,         /* Ｖレート５４ */
     vrate55 ,         /* Ｖレート５５ */
     vrate56 ,         /* Ｖレート５６ */
     vrate57 ,         /* Ｖレート５７ */
     vrate58 ,         /* Ｖレート５８ */
     vrate59 ,         /* Ｖレート５９ */
     vrate60 ,         /* Ｖレート６０ */
     vrate61 ,         /* Ｖレート６１ */
     vrate62 ,         /* Ｖレート６２ */
     vrate63 ,         /* Ｖレート６３ */
     vrate64 ,         /* Ｖレート６４ */
     vrate65 ,         /* Ｖレート６５ */
     vrate66 ,         /* Ｖレート６６ */
     vrate67 ,         /* Ｖレート６７ */
     vrate68 ,         /* Ｖレート６８ */
     vrate69 ,         /* Ｖレート６９ */
     vrate70 ,         /* Ｖレート７０ */
     vrate71 ,         /* Ｖレート７１ */
     vrate72 ,         /* Ｖレート７２ */
     vrate73 ,         /* Ｖレート７３ */
     vrate74 ,         /* Ｖレート７４ */
     vrate75 ,         /* Ｖレート７５ */
     vrate76 ,         /* Ｖレート７６ */
     vrate77 ,         /* Ｖレート７７ */
     vrate78 ,         /* Ｖレート７８ */
     vrate79 ,         /* Ｖレート７９ */
     vrate80 ,         /* Ｖレート８０ */
     vrate81 ,         /* Ｖレート８１ */
     vrate82 ,         /* Ｖレート８２ */
     vrate83 ,         /* Ｖレート８３ */
     vrate84 ,         /* Ｖレート８４ */
     vrate85 ,         /* Ｖレート８５ */
     vrate86 ,         /* Ｖレート８６ */
     vrate87 ,         /* Ｖレート８７ */
     vrate88 ,         /* Ｖレート８８ */
     vrate89 ,         /* Ｖレート８９ */
     vrate90 ,         /* Ｖレート９０ */
     vrate91 ,         /* Ｖレート９１ */
     vrate92 ,         /* Ｖレート９２ */
     vrate93 ,         /* Ｖレート９３ */
     vrate94 ,         /* Ｖレート９４ */
     vrate95 ,         /* Ｖレート９５ */
     vrate96 ,         /* Ｖレート９６ */
     vrate97 ,         /* Ｖレート９７ */
     vrate98 ,         /* Ｖレート９８ */
     vrate99 ,         /* Ｖレート９９ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BM_RateV_Z;