CREATE VIEW IT_BAK_KykKihon AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     trkssikibetukey ,         /* 取消識別キー */
     aitesyono ,         /* 相手証券番号 */
     haitoukbn ,         /* 配当区分 */
     hrkkaisuu ,         /* 払込回数 */
     hrkkeiro ,         /* 払込経路 */
     sdpdkbn ,         /* Ｓ建Ｐ建区分 */
     dntryouritukbn ,         /* 団体料率区分 */
     dntcd ,         /* 団体コード */
     sntkhoukbn ,         /* 選択方法区分 */
     sinsakbn ,         /* 診査区分 */
     mosymd ,         /* 申込日 */
     kktymd ,         /* 告知日 */
     fstpnyknymd ,         /* 初回保険料入金日 */
     mosukeymd ,         /* 申込書受付日 */
     mosjimosuktymd ,         /* 申込時申込書受付日 */
     seirituymd ,         /* 成立日 */
     itiprsymd ,         /* １Ｐ領収予定日 */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     bosyuuym ,         /* 募集年月 */
     seisekiym ,         /* 成績計上年月 */
     skeikeijyouym ,         /* 新契約計上年月 */
     plancd ,         /* プランコード */
     planrenno ,         /* プラン連番 */
     aisyoumeikbn ,         /* 愛称名区分 */
     syusaiumu ,         /* 出再有無 */
     stknsetkbn ,         /* 質権設定区分 */
     kykksykjyumu ,         /* 契約者貸付約定有無 */
     kykksumu ,         /* 契約者貸付有無 */
     aplkahikbn ,         /* ＡＰＬ可否区分 */
     aplumu ,         /* ＡＰＬ有無 */
     fstphrkkeirokbn ,         /* 初回保険料払込経路区分 */
     haitounendo ,         /* 配当年度 */
     haitoukinuketorihoukbn ,         /* 配当金受取方法区分 */
     tratkityuiumu ,         /* 取扱注意有無 */
     tratkityuiuny ,         /* 取扱注意内容 */
     sbuktnin ,         /* 死亡受取人人数 */
     gansindankakuteiymd ,         /* がん診断確定日 */
     mosuketukekbn ,         /* 申込受付区分 */
     kijikbn ,         /* 記事区分 */
     hhknsykgycd ,         /* 被保険者職業コード */
     hhknnensyuukbn ,         /* 被保険者年収区分 */
     drtenkanritodoufukencd ,         /* 代理店管理都道府県コード */
     cifcd ,         /* ＣＩＦコード */
     smbckanriid ,         /* ＳＭＢＣ受付管理ＩＤ */
     tsryhshrkykumukbn ,         /* 手数料不支払契約有無区分 */
     kykhonninkakninsyoruikbn ,         /* 契約者本人確認書類区分 */
     skskknhonninkakninsyoruikbn ,         /* 親権者後見人本人確認書類区分 */
     boskykjyoutai ,         /* 募集契約状態 */
     kanyuusyano ,         /* 加入者番号 */
     drctservicemoskbn ,         /* ダイレクトサービス申込区分 */
     sksyoukenskskbn ,         /* 新契約証券作成区分 */
     sinkyksyokensakuseiymd ,         /* 新契約証券作成日 */
     syoyousinkyksyohakkouymd ,         /* 証券用新契約証券発行日 */
     skjmosno ,         /* 新契約時申込番号 */
     nkuikosumikbn ,         /* 年金移行済区分 */
     syhenkouymd ,         /* 最終変更日 */
     lastsyosaihkymd ,         /* 最終証券再発行日 */
     lastmeihenymd ,         /* 最終名義変更日 */
     lastkykmeighnkymd ,         /* 最終契約者名義変更日 */
     lastsbukthenymd ,         /* 最終死亡受取人変更日 */
     lastkyknmseiymdhenkouymd ,         /* 最終契約者名生年月日変更日 */
     lastkyknmkanakjteiymd ,         /* 最終契約者名仮名漢字訂正日 */
     lasttsinynohenkouymd ,         /* 最終通信先郵便番号変更日 */
     lastjyuuhenymd ,         /* 最終住所変更日 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     seiritujitrhkjikakkbn ,         /* 成立時取引時確認区分 */
     tikiktbrisyuruikbn ,         /* 定期一括払種類区分 */
     yakkanjyuryouhoukbn ,         /* 約款受領方法区分 */
     yakkanbunsyono ,         /* 約款文書番号 */
     siorino ,         /* しおり番号 */
     ynkhrkmgkannituutikbn           /* 円貨払込額案内通知区分 */
FROM IT_BAK_KykKihon_Z;