CREATE VIEW BT_SikinIdouRireki AS SELECT
     syoriYmd ,         /* 処理年月日 */
     keirisyorirenno ,         /* 経理用処理連番 */
     syono ,         /* 証券番号 */
     henkousikibetukey ,         /* 変更識別キー */
     targetKinouId ,         /* 対象機能ＩＤ */
     skno ,         /* 請求番号 */
     seikyuurirekino ,         /* 請求履歴番号 */
     sakujyoflg ,         /* 削除フラグ */
     nykshrkbn ,         /* 入金支払区分 */
     syoricd ,         /* 処理コード */
     densyskbn ,         /* 伝票用システム区分 */
     denrenno ,         /* 伝票データ連番 */
     seg1cd ,         /* セグメント１コード */
     kyktuukasyu ,         /* 契約通貨種類 */
     syutkkbn ,         /* 主契約特約区分 */
     hrkkaisuu ,         /* 払込回数 */
     syouhncd ,         /* 商品コード */
     syouhnsdno ,         /* 商品世代番号 */
     kyksyouhnrenno ,         /* 契約商品連番 */
     shrhousiteikbn ,         /* 支払方法指定区分 */
     phendoukaisiym ,         /* Ｐ変動開始年月 */
     phendoumaegk ,         /* Ｐ変動前金額 */
     phendoumaegk$ ,         /* Ｐ変動前金額(通貨型) */
     phendougogk ,         /* Ｐ変動後金額 */
     phendougogk$ ,         /* Ｐ変動後金額(通貨型) */
     kykymd ,         /* 契約日 */
     seirituymd ,         /* 成立日 */
     syoumetuymd ,         /* 消滅日 */
     misyuupjyuutouym ,         /* 未収保険料充当年月 */
     shrsyorikbn ,         /* 支払処理区分 */
     seikyuusyubetu ,         /* 請求種別 */
     syoumetujiyuu ,         /* 消滅事由 */
     jkipjytym ,         /* 次回Ｐ充当年月 */
     jyutoustartym ,         /* 充当開始年月 */
     jyutouendym ,         /* 充当終了年月 */
     nykkeiro ,         /* 入金経路 */
     nyknaiyoukbn ,         /* 入金内容区分 */
     nyktrksflg ,         /* 入金取消フラグ */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     hokenryou ,         /* 保険料 */
     hokenryou$ ,         /* 保険料(通貨型) */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BT_SikinIdouRireki_Z;