CREATE VIEW ST_SkOikmKaikei AS SELECT
     densyskbn ,         /* 伝票用システム区分 */
     denrenno ,         /* 伝票データ連番 */
     edano ,         /* 枝番号 */
     mosno ,         /* 申込番号 */
     huridenatesakicd ,         /* 振替伝票宛先部課コード */
     tantocd ,         /* 担当コード */
     denymd ,         /* 伝票日付 */
     taisyakukbn ,         /* 貸借区分 */
     kanjyoukmkcd ,         /* 勘定科目コード */
     suitoubumoncd ,         /* 出納部門コード */
     tuukasyu ,         /* 通貨種類 */
     dengaikagk ,         /* 伝票金額（外貨） */
     dengaikagk$ ,         /* 伝票金額（外貨）(通貨型) */
     denkawaserate ,         /* 伝票用為替レート */
     denyenkagk ,         /* 伝票金額（円） */
     denyenkagk$ ,         /* 伝票金額（円）(通貨型) */
     syoriYmd ,         /* 処理年月日 */
     syoricd ,         /* 処理コード */
     syorisosikicd ,         /* 処理組織コード */
     seg1cd ,         /* セグメント１コード */
     seg2cd ,         /* セグメント２コード */
     kessantyouseikbn ,         /* 決算調整区分 */
     naibukeiyakukbn ,         /* 内部契約区分 */
     tekiyoukbn ,         /* 摘要区分 */
     densyorikbn ,         /* 伝票処理区分 */
     aatsukaishasuitososhikicd ,         /* Ａ扱者出納組織コード */
     hnknriyuukbn ,         /* 返金理由区分 */
     fstpryosyuymd ,         /* 初回Ｐ領収日 */
     bosyuuym ,         /* 募集年月 */
     mosymd ,         /* 申込日 */
     kykymd ,         /* 契約日 */
     sknnkaisiymd ,         /* 責任開始日 */
     syusyouhncd ,         /* 主契約商品コード */
     ryouritusdno ,         /* 料率世代番号 */
     hrkkaisuu ,         /* 払込回数 */
     hrkkeiro ,         /* 払込経路 */
     sdpdkbn ,         /* Ｓ建Ｐ建区分 */
     aatsukaishasoshikicd ,         /* Ａ扱者組織コード */
     aatkisyadaibosyuucd ,         /* Ａ扱者代表募集人コード */
     aatkisyabosyuucd ,         /* Ａ扱者募集人コード */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ST_SkOikmKaikei_Z;