CREATE VIEW ZT_GaikaKokyakuTuutiTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztysyono ,         /* （中継用）証券番号 */
     ztysclatosyono ,         /* （中継用）スクランブル後証券番号 */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztydskaiyktirasidouhuukbn ,         /* （中継用）ＤＳ解約チラシ同封区分 */
     ztyhrknkanssiryodouhuukbn ,         /* （中継用）返戻金請求勧奨資料同封区分 */
     ztyassistplustirasidhkbn ,         /* （中継用）アシストプラスチラシ同封区分 */
     ztykoktuutireportlayoutptn ,         /* （中継用）顧客通知帳票レイアウトパターン */
     ztygengkumu ,         /* （中継用）減額有無 */
     ztykytkmkyobi1 ,         /* （中継用）共通項目予備項目１ */
     ztytuusinsakiyuubinno ,         /* （中継用）通信先郵便番号 */
     ztytsinadr1kj ,         /* （中継用）通信先住所１（漢字） */
     ztytsinadr2kj ,         /* （中継用）通信先住所２（漢字） */
     ztytsinadr3kj ,         /* （中継用）通信先住所３（漢字） */
     ztytsintelno ,         /* （中継用）通信先電話番号 */
     ztytsinnm18 ,         /* （中継用）通信先氏名（１８桁） */
     ztyyobiv19 ,         /* （中継用）予備項目Ｖ１９ */
     ztysyoukaisakidrtennm1 ,         /* （中継用）照会先代理店名１ */
     ztysyoukaisakidrtennm2 ,         /* （中継用）照会先代理店名２ */
     ztyyobiv20 ,         /* （中継用）予備項目Ｖ２０ */
     ztyaisatumsgcd1 ,         /* （中継用）挨拶文メッセージコード１ */
     ztyaisatumsgcd2 ,         /* （中継用）挨拶文メッセージコード２ */
     ztyaisatumsgcd3 ,         /* （中継用）挨拶文メッセージコード３ */
     ztyosirasetuutisakuseiymwa ,         /* （中継用）お知らせ通知作成年月（和暦） */
     ztysyono2 ,         /* （中継用）証券番号２ */
     ztyaisyoumeikbn ,         /* （中継用）愛称名区分 */
     ztykyknmkj18 ,         /* （中継用）契約者名（漢字）（１８桁） */
     ztyhhknnmkj18 ,         /* （中継用）被保険者名（漢字）（１８桁） */
     ztyuktmidasikbn1 ,         /* （中継用）受取人見出し区分１ */
     ztyuktkbn1 ,         /* （中継用）受取人区分１ */
     ztyuktnm118 ,         /* （中継用）受取人名１（１８桁） */
     ztyuktmidasikbn2 ,         /* （中継用）受取人見出し区分２ */
     ztyuktkbn2 ,         /* （中継用）受取人区分２ */
     ztyuktnm218 ,         /* （中継用）受取人名２（１８桁） */
     ztyuktmidasikbn3 ,         /* （中継用）受取人見出し区分３ */
     ztyuktkbn3 ,         /* （中継用）受取人区分３ */
     ztyuktnm318 ,         /* （中継用）受取人名３（１８桁） */
     ztyuktmidasikbn4 ,         /* （中継用）受取人見出し区分４ */
     ztyuktkbn4 ,         /* （中継用）受取人区分４ */
     ztyuktnm418 ,         /* （中継用）受取人名４（１８桁） */
     ztyuktmidasikbn5 ,         /* （中継用）受取人見出し区分５ */
     ztyuktkbn5 ,         /* （中継用）受取人区分５ */
     ztyuktnm518 ,         /* （中継用）受取人名５（１８桁） */
     ztykykymdwa ,         /* （中継用）契約年月日（和暦） */
     ztydai1hknkknfromwa ,         /* （中継用）第１保険期間至（和暦） */
     ztydai1hknkkn ,         /* （中継用）第１保険期間 */
     ztydai2hknkknfromwa ,         /* （中継用）第２保険期間自（和暦） */
     ztydai2hknkkntowa ,         /* （中継用）第２保険期間至（和暦） */
     ztydai3hknkknfromwa ,         /* （中継用）第３保険期間自（和暦） */
     ztydai3hknkknto ,         /* （中継用）第３保険期間至 */
     ztykyktuukasyuzn ,         /* （中継用）契約通貨種類（全） */
     ztykyktuukatype ,         /* （中継用）契約通貨タイプ */
     ztytk1msgcd ,         /* （中継用）特約１メッセージコード */
     ztytk2msgcd ,         /* （中継用）特約２メッセージコード */
     ztytk3msgcd ,         /* （中継用）特約３メッセージコード */
     ztytk4msgcd ,         /* （中継用）特約４メッセージコード */
     ztytk5msgcd ,         /* （中継用）特約５メッセージコード */
     ztytk6msgcd ,         /* （中継用）特約６メッセージコード */
     ztytk7msgcd ,         /* （中継用）特約７メッセージコード */
     ztytk8msgcd ,         /* （中継用）特約８メッセージコード */
     ztytk9msgcd ,         /* （中継用）特約９メッセージコード */
     ztytk10msgcd ,         /* （中継用）特約１０メッセージコード */
     ztydstourokujyou ,         /* （中継用）ＤＳ登録状況 */
     ztysd1msgcd ,         /* （中継用）スミセイダイレクト１メッセージコード */
     ztysd2msgcd ,         /* （中継用）スミセイダイレクト２メッセージコード */
     ztysd3msgcd ,         /* （中継用）スミセイダイレクト３メッセージコード */
     ztykrpassword ,         /* （中継用）仮パスワード */
     ztyyuukoukigenwareki ,         /* （中継用）有効期限（和暦） */
     ztykzktrkjk ,         /* （中継用）家族登録状況 */
     ztytrkkzknm118 ,         /* （中継用）登録家族名１（１８桁） */
     ztytrkkzknm218 ,         /* （中継用）登録家族名２（１８桁） */
     ztyyendthnkymd ,         /* （中継用）円建変更日 */
     ztynkshrstartymdstr ,         /* （中継用）年金支払開始日（文字列） */
     ztynenkinstartnen ,         /* （中継用）年金開始年齢 */
     ztynksyuruinm ,         /* （中継用）年金種類名称 */
     ztyhrkkaisuu ,         /* （中継用）払込回数 */
     ztytikiktbrisyuruikbn ,         /* （中継用）定期一括払種類区分 */
     ztyzennouumu ,         /* （中継用）前納有無 */
     ztyhrkkeiro ,         /* （中継用）払込経路 */
     ztyphrkkkn ,         /* （中継用）保険料払込期間 */
     ztysueokikkn ,         /* （中継用）据置期間 */
     ztyyakkanbunsyono ,         /* （中継用）約款文書番号 */
     ztygkykniyuosiraseyobi ,         /* （中継用）ご契約内容お知らせ予備項目 */
     ztysakuseikijyunymdwa ,         /* （中継用）作成基準日（和暦） */
     ztyitijibrpkyktuuka ,         /* （中継用）一時払保険料（契約通貨） */
     ztykihonsktuuka ,         /* （中継用）基本保険金額（契約通貨） */
     ztyyenhrkgk ,         /* （中継用）円貨払込額 */
     ztystigituukahrkgk ,         /* （中継用）指定外通貨払込額 */
     ztyhrktuukasyuzn ,         /* （中継用）払込通貨種類（全） */
     ztyhrktuukatype ,         /* （中継用）払込通貨タイプ */
     ztyyenkhrikmrate ,         /* （中継用）円貨払込特約レート */
     ztystigikwsrate ,         /* （中継用）指定外通貨払込特約レート */
     ztyhrkgkhyoujikbn ,         /* （中継用）払込額表示区分 */
     ztykijyunkingaku ,         /* （中継用）基準金額 */
     ztykjnkngkkawaserate ,         /* （中継用）基準金額為替レート */
     ztykjnkngkhyoujikbn ,         /* （中継用）基準金額表示区分 */
     ztysakuseikijyunymdkwsrate ,         /* （中継用）作成基準日時点為替レート */
     ztysbhknkngkhknkkn ,         /* （中継用）死亡保険金額保険期間 */
     ztysbhknkngkhknkknfromwa ,         /* （中継用）死亡保険金額保険期間自（和暦） */
     ztysbhknkngkhknkkntowa ,         /* （中継用）死亡保険金額保険期間至（和暦） */
     ztysbhknkngkkyktuuka ,         /* （中継用）死亡保険金額（契約通貨） */
     ztysbhknkngkyen ,         /* （中継用）死亡保険金額（円貨） */
     ztysaigaisbhknkngakuumu ,         /* （中継用）災害死亡保険金額表示有無 */
     ztysaigaisbhknkngakuktuuka ,         /* （中継用）災害死亡保険金額（契約通貨） */
     ztysaigaisbhknkngakukyen ,         /* （中継用）災害死亡保険金額（円貨） */
     ztytumitatekngkktuuka ,         /* （中継用）保険料積立金額（契約通貨） */
     ztytumitatekngkkyen ,         /* （中継用）保険料積立金額（円貨） */
     ztykaiyakuhrkngakkyktuuka ,         /* （中継用）解約返戻金額（契約通貨） */
     ztykaiyakuhrkngakyen ,         /* （中継用）解約返戻金額（円貨） */
     ztymkhgkyen ,         /* （中継用）目標額（円貨） */
     ztymkhgkwari ,         /* （中継用）目標額割合 */
     ztymkhgkhyoujikbn ,         /* （中継用）目標額表示区分 */
     ztyhosyouhskmsgcd1 ,         /* （中継用）保障内容補足メッセージコード１ */
     ztyhosyouhskmsgcd2 ,         /* （中継用）保障内容補足メッセージコード２ */
     ztyhosyouhskmsgcd3 ,         /* （中継用）保障内容補足メッセージコード３ */
     ztyhosyouhskmsgcd4 ,         /* （中継用）保障内容補足メッセージコード４ */
     ztyhosyouhskmsgcd5 ,         /* （中継用）保障内容補足メッセージコード５ */
     ztyhosyouhskmsgcd6 ,         /* （中継用）保障内容補足メッセージコード６ */
     ztyhosyouhskmsgcd7 ,         /* （中継用）保障内容補足メッセージコード７ */
     ztyhosyouhskmsgcd8 ,         /* （中継用）保障内容補足メッセージコード８ */
     ztyhosyouhskmsgcd9 ,         /* （中継用）保障内容補足メッセージコード９ */
     ztykihonsyen ,         /* （中継用）基本保険金額（円貨） */
     ztyyoteirirituv4 ,         /* （中継用）予定利率（４桁） */
     ztyyendthnkhrkngakyen ,         /* （中継用）円建変更時返戻金額（円貨） */
     ztytmtthaitoukinzndkyen ,         /* （中継用）積立配当金残高（円貨） */
     ztynkgnsgkkyktuuka ,         /* （中継用）年金原資額（契約通貨） */
     ztysbhknkngkhyoujikbn ,         /* （中継用）死亡保険金額表示区分 */
     ztykijyunkingakukyktuuka ,         /* （中継用）基準金額（契約通貨） */
     ztyyenhrkgkiktnkgk ,         /* （中継用）円貨払込額（一括入金額） */
     ztyzennoutikiktyenhrkgkkykj ,         /* （中継用）前納定期一括払円貨払込額（契約時） */
     ztykaiyakusiharaigk ,         /* （中継用）解約時支払額 */
     ztykaiyakusiharaigkznnuzndk ,         /* （中継用）解約時支払額（前納残高） */
     ztykaiyakusiharaigksntshrgk ,         /* （中継用）解約時支払額（その他支払金額） */
     ztyyenhrkgkgoukei ,         /* （中継用）円貨払込額の合計額 */
     ztyhrritu ,         /* （中継用）返戻率 */
     ztynkgnsyensyourai ,         /* （中継用）年金原資（円貨）（将来予想金額） */
     ztynkgnsgaikasyourai ,         /* （中継用）年金原資（契約通貨）（将来予想金額） */
     ztyyenhrkgkgoukeisyourai ,         /* （中継用）円貨払込額の合計額（将来予想金額） */
     ztyhrritusyourai ,         /* （中継用）返戻率（将来予想金額） */
     ztynkgnshskmsgcd1 ,         /* （中継用）年金原資試算補足メッセージコード１ */
     ztynkgnshskmsgcd2 ,         /* （中継用）年金原資試算補足メッセージコード２ */
     ztynkgnshskmsgcd3 ,         /* （中継用）年金原資試算補足メッセージコード３ */
     ztynkgnshskmsgcd4 ,         /* （中継用）年金原資試算補足メッセージコード４ */
     ztynkgnshskmsgcd5 ,         /* （中継用）年金原資試算補足メッセージコード５ */
     ztyhosyounaiyouyobi ,         /* （中継用）保障内容予備項目 */
     ztykwsratekijyunymd1maewa ,         /* （中継用）為替レート基準日１ヶ月前（和暦） */
     ztykwsrateusdjpy1mae ,         /* （中継用）為替レート米ドル（円）１ヶ月前 */
     ztykwsrateaudjpy1mae ,         /* （中継用）為替レート豪ドル（円）１ヶ月前 */
     ztyyobiv10 ,         /* （中継用）予備項目Ｖ１０ */
     ztykwsratekijyunymd2maewa ,         /* （中継用）為替レート基準日２ヶ月前（和暦） */
     ztykwsrateusdjpy2mae ,         /* （中継用）為替レート米ドル（円）２ヶ月前 */
     ztykwsrateaudjpy2mae ,         /* （中継用）為替レート豪ドル（円）２ヶ月前 */
     ztyyobiv10x2 ,         /* （中継用）予備項目Ｖ１０＿２ */
     ztykwsratekijyunymd3maewa ,         /* （中継用）為替レート基準日３ヶ月前（和暦） */
     ztykwsrateusdjpy3mae ,         /* （中継用）為替レート米ドル（円）３ヶ月前 */
     ztykwsrateaudjpy3mae ,         /* （中継用）為替レート豪ドル（円）３ヶ月前 */
     ztyyobiv10x3 ,         /* （中継用）予備項目Ｖ１０＿３ */
     ztykwsratekijyunymd4maewa ,         /* （中継用）為替レート基準日４ヶ月前（和暦） */
     ztykwsrateusdjpy4mae ,         /* （中継用）為替レート米ドル（円）４ヶ月前 */
     ztykwsrateaudjpy4mae ,         /* （中継用）為替レート豪ドル（円）４ヶ月前 */
     ztyyobiv10x4 ,         /* （中継用）予備項目Ｖ１０＿４ */
     ztykwsratekijyunymd5maewa ,         /* （中継用）為替レート基準日５ヶ月前（和暦） */
     ztykwsrateusdjpy5mae ,         /* （中継用）為替レート米ドル（円）５ヶ月前 */
     ztykwsrateaudjpy5mae ,         /* （中継用）為替レート豪ドル（円）５ヶ月前 */
     ztyyobiv10x5 ,         /* （中継用）予備項目Ｖ１０＿５ */
     ztykwsratekijyunymd6maewa ,         /* （中継用）為替レート基準日６ヶ月前（和暦） */
     ztykwsrateusdjpy6mae ,         /* （中継用）為替レート米ドル（円）６ヶ月前 */
     ztykwsrateaudjpy6mae ,         /* （中継用）為替レート豪ドル（円）６ヶ月前 */
     ztyyobiv10x6 ,         /* （中継用）予備項目Ｖ１０＿６ */
     ztykwsratemsgcd ,         /* （中継用）為替レートメッセージコード */
     ztyyobiv23 ,         /* （中継用）予備項目Ｖ２３ */
     ztyosirasemsgcd1 ,         /* （中継用）お知らせメッセージコード１ */
     ztyosirasemsgcd2 ,         /* （中継用）お知らせメッセージコード２ */
     ztyosirasemsgcd3 ,         /* （中継用）お知らせメッセージコード３ */
     ztyosirasemsgcd4 ,         /* （中継用）お知らせメッセージコード４ */
     ztyosirasemsgcd5 ,         /* （中継用）お知らせメッセージコード５ */
     ztyyobiv15 ,         /* （中継用）予備項目Ｖ１５ */
     ztysetteibairitustr ,         /* （中継用）設定倍率（文字列） */
     ztytmttknzkrtjygnstr ,         /* （中継用）積立金増加率上限（文字列） */
     ztytmttknzkrtkgnstr ,         /* （中継用）積立金増加率下限（文字列） */
     ztytumitateriritustr ,         /* （中継用）積立利率（文字列） */
     ztysisuunm ,         /* （中継用）指数名 */
     ztytmttknsuiirirekikbnx1 ,         /* （中継用）積立金推移履歴区分＿１ */
     ztykeiyakuoutoubix1 ,         /* （中継用）契約応当日＿１ */
     ztytmttknjyoutaix1 ,         /* （中継用）積立金状態＿１ */
     ztyptumitatekngkktuukax1 ,         /* （中継用）保険料積立金額（契約通貨）＿１ */
     ztyptumitatekngkyenx1 ,         /* （中継用）保険料積立金額（円貨）＿１ */
     ztysisuux1 ,         /* （中継用）指数＿１ */
     ztysisuuuprituhugoux1 ,         /* （中継用）指数上昇率符号＿１ */
     ztysisuuupritux1 ,         /* （中継用）指数上昇率＿１ */
     ztytmttknzoukaritustrx1 ,         /* （中継用）積立金増加率（文字列）＿１ */
     ztykawaseratex1 ,         /* （中継用）為替レート＿１ */
     ztytmttknsuiirirekikbnx2 ,         /* （中継用）積立金推移履歴区分＿２ */
     ztykeiyakuoutoubix2 ,         /* （中継用）契約応当日＿２ */
     ztytmttknjyoutaix2 ,         /* （中継用）積立金状態＿２ */
     ztyptumitatekngkktuukax2 ,         /* （中継用）保険料積立金額（契約通貨）＿２ */
     ztyptumitatekngkyenx2 ,         /* （中継用）保険料積立金額（円貨）＿２ */
     ztysisuux2 ,         /* （中継用）指数＿２ */
     ztysisuuuprituhugoux2 ,         /* （中継用）指数上昇率符号＿２ */
     ztysisuuupritux2 ,         /* （中継用）指数上昇率＿２ */
     ztytmttknzoukaritustrx2 ,         /* （中継用）積立金増加率（文字列）＿２ */
     ztykawaseratex2 ,         /* （中継用）為替レート＿２ */
     ztytmttknsuiirirekikbnx3 ,         /* （中継用）積立金推移履歴区分＿３ */
     ztykeiyakuoutoubix3 ,         /* （中継用）契約応当日＿３ */
     ztytmttknjyoutaix3 ,         /* （中継用）積立金状態＿３ */
     ztyptumitatekngkktuukax3 ,         /* （中継用）保険料積立金額（契約通貨）＿３ */
     ztyptumitatekngkyenx3 ,         /* （中継用）保険料積立金額（円貨）＿３ */
     ztysisuux3 ,         /* （中継用）指数＿３ */
     ztysisuuuprituhugoux3 ,         /* （中継用）指数上昇率符号＿３ */
     ztysisuuupritux3 ,         /* （中継用）指数上昇率＿３ */
     ztytmttknzoukaritustrx3 ,         /* （中継用）積立金増加率（文字列）＿３ */
     ztykawaseratex3 ,         /* （中継用）為替レート＿３ */
     ztytmttknsuiirirekikbnx4 ,         /* （中継用）積立金推移履歴区分＿４ */
     ztykeiyakuoutoubix4 ,         /* （中継用）契約応当日＿４ */
     ztytmttknjyoutaix4 ,         /* （中継用）積立金状態＿４ */
     ztyptumitatekngkktuukax4 ,         /* （中継用）保険料積立金額（契約通貨）＿４ */
     ztyptumitatekngkyenx4 ,         /* （中継用）保険料積立金額（円貨）＿４ */
     ztysisuux4 ,         /* （中継用）指数＿４ */
     ztysisuuuprituhugoux4 ,         /* （中継用）指数上昇率符号＿４ */
     ztysisuuupritux4 ,         /* （中継用）指数上昇率＿４ */
     ztytmttknzoukaritustrx4 ,         /* （中継用）積立金増加率（文字列）＿４ */
     ztykawaseratex4 ,         /* （中継用）為替レート＿４ */
     ztytmttknsuiirirekikbnx5 ,         /* （中継用）積立金推移履歴区分＿５ */
     ztykeiyakuoutoubix5 ,         /* （中継用）契約応当日＿５ */
     ztytmttknjyoutaix5 ,         /* （中継用）積立金状態＿５ */
     ztyptumitatekngkktuukax5 ,         /* （中継用）保険料積立金額（契約通貨）＿５ */
     ztyptumitatekngkyenx5 ,         /* （中継用）保険料積立金額（円貨）＿５ */
     ztysisuux5 ,         /* （中継用）指数＿５ */
     ztysisuuuprituhugoux5 ,         /* （中継用）指数上昇率符号＿５ */
     ztysisuuupritux5 ,         /* （中継用）指数上昇率＿５ */
     ztytmttknzoukaritustrx5 ,         /* （中継用）積立金増加率（文字列）＿５ */
     ztykawaseratex5 ,         /* （中継用）為替レート＿５ */
     ztytmttknsuiirirekikbnx6 ,         /* （中継用）積立金推移履歴区分＿６ */
     ztykeiyakuoutoubix6 ,         /* （中継用）契約応当日＿６ */
     ztytmttknjyoutaix6 ,         /* （中継用）積立金状態＿６ */
     ztyptumitatekngkktuukax6 ,         /* （中継用）保険料積立金額（契約通貨）＿６ */
     ztyptumitatekngkyenx6 ,         /* （中継用）保険料積立金額（円貨）＿６ */
     ztysisuux6 ,         /* （中継用）指数＿６ */
     ztysisuuuprituhugoux6 ,         /* （中継用）指数上昇率符号＿６ */
     ztysisuuupritux6 ,         /* （中継用）指数上昇率＿６ */
     ztytmttknzoukaritustrx6 ,         /* （中継用）積立金増加率（文字列）＿６ */
     ztykawaseratex6 ,         /* （中継用）為替レート＿６ */
     ztytmttknsuiirirekikbnx7 ,         /* （中継用）積立金推移履歴区分＿７ */
     ztykeiyakuoutoubix7 ,         /* （中継用）契約応当日＿７ */
     ztytmttknjyoutaix7 ,         /* （中継用）積立金状態＿７ */
     ztyptumitatekngkktuukax7 ,         /* （中継用）保険料積立金額（契約通貨）＿７ */
     ztyptumitatekngkyenx7 ,         /* （中継用）保険料積立金額（円貨）＿７ */
     ztysisuux7 ,         /* （中継用）指数＿７ */
     ztysisuuuprituhugoux7 ,         /* （中継用）指数上昇率符号＿７ */
     ztysisuuupritux7 ,         /* （中継用）指数上昇率＿７ */
     ztytmttknzoukaritustrx7 ,         /* （中継用）積立金増加率（文字列）＿７ */
     ztykawaseratex7 ,         /* （中継用）為替レート＿７ */
     ztytmttknsuiirirekikbnx8 ,         /* （中継用）積立金推移履歴区分＿８ */
     ztykeiyakuoutoubix8 ,         /* （中継用）契約応当日＿８ */
     ztytmttknjyoutaix8 ,         /* （中継用）積立金状態＿８ */
     ztyptumitatekngkktuukax8 ,         /* （中継用）保険料積立金額（契約通貨）＿８ */
     ztyptumitatekngkyenx8 ,         /* （中継用）保険料積立金額（円貨）＿８ */
     ztysisuux8 ,         /* （中継用）指数＿８ */
     ztysisuuuprituhugoux8 ,         /* （中継用）指数上昇率符号＿８ */
     ztysisuuupritux8 ,         /* （中継用）指数上昇率＿８ */
     ztytmttknzoukaritustrx8 ,         /* （中継用）積立金増加率（文字列）＿８ */
     ztykawaseratex8 ,         /* （中継用）為替レート＿８ */
     ztytmttknsuiirirekikbnx9 ,         /* （中継用）積立金推移履歴区分＿９ */
     ztykeiyakuoutoubix9 ,         /* （中継用）契約応当日＿９ */
     ztytmttknjyoutaix9 ,         /* （中継用）積立金状態＿９ */
     ztyptumitatekngkktuukax9 ,         /* （中継用）保険料積立金額（契約通貨）＿９ */
     ztyptumitatekngkyenx9 ,         /* （中継用）保険料積立金額（円貨）＿９ */
     ztysisuux9 ,         /* （中継用）指数＿９ */
     ztysisuuuprituhugoux9 ,         /* （中継用）指数上昇率符号＿９ */
     ztysisuuupritux9 ,         /* （中継用）指数上昇率＿９ */
     ztytmttknzoukaritustrx9 ,         /* （中継用）積立金増加率（文字列）＿９ */
     ztykawaseratex9 ,         /* （中継用）為替レート＿９ */
     ztytmttknsuiirirekikbnx10 ,         /* （中継用）積立金推移履歴区分＿１０ */
     ztykeiyakuoutoubix10 ,         /* （中継用）契約応当日＿１０ */
     ztytmttknjyoutaix10 ,         /* （中継用）積立金状態＿１０ */
     ztyptumitatekngkktuukax10 ,         /* （中継用）保険料積立金額（契約通貨）＿１０ */
     ztyptumitatekngkyenx10 ,         /* （中継用）保険料積立金額（円貨）＿１０ */
     ztysisuux10 ,         /* （中継用）指数＿１０ */
     ztysisuuuprituhugoux10 ,         /* （中継用）指数上昇率符号＿１０ */
     ztysisuuupritux10 ,         /* （中継用）指数上昇率＿１０ */
     ztytmttknzoukaritustrx10 ,         /* （中継用）積立金増加率（文字列）＿１０ */
     ztykawaseratex10 ,         /* （中継用）為替レート＿１０ */
     ztytmttknsuiirirekikbnx11 ,         /* （中継用）積立金推移履歴区分＿１１ */
     ztykeiyakuoutoubix11 ,         /* （中継用）契約応当日＿１１ */
     ztytmttknjyoutaix11 ,         /* （中継用）積立金状態＿１１ */
     ztyptumitatekngkktuukax11 ,         /* （中継用）保険料積立金額（契約通貨）＿１１ */
     ztyptumitatekngkyenx11 ,         /* （中継用）保険料積立金額（円貨）＿１１ */
     ztysisuux11 ,         /* （中継用）指数＿１１ */
     ztysisuuuprituhugoux11 ,         /* （中継用）指数上昇率符号＿１１ */
     ztysisuuupritux11 ,         /* （中継用）指数上昇率＿１１ */
     ztytmttknzoukaritustrx11 ,         /* （中継用）積立金増加率（文字列）＿１１ */
     ztykawaseratex11 ,         /* （中継用）為替レート＿１１ */
     ztytmttknsuiiyobi ,         /* （中継用）積立金推移予備項目 */
     ztyttdkkigen ,         /* （中継用）お手続き期限 */
     ztykrnkgnsgk ,         /* （中継用）仮年金原資額 */
     ztytirtitnttdkyobi ,         /* （中継用）定率移転の手続き予備項目 */
     ztyskshozonnensuu ,         /* （中継用）請求書保存年数 */
     ztydocumentid ,         /* （中継用）ドキュメントＩＤ */
     ztytoritugisyasyozokunm ,         /* （中継用）取次者所属名 */
     ztyyendthnkhrsksyobi ,         /* （中継用）円建変更時返戻金請求書予備項目 */
     ztyyoteiriritukijyunym1 ,         /* （中継用）予定利率基準年月＿１ */
     ztyyoteiriritu1 ,         /* （中継用）予定利率＿１ */
     ztyytirrtcalckijyunrrt1 ,         /* （中継用）予定利率計算基準利率＿１ */
     ztykwsratekijyunym1 ,         /* （中継用）為替レート基準年月＿１ */
     ztykaknsnkwsrate1 ,         /* （中継用）換算為替レート＿１ */
     ztypgaika1 ,         /* （中継用）保険料（契約通貨）＿１ */
     ztypyen1 ,         /* （中継用）保険料（円貨）＿１ */
     ztyyoteiriritukijyunym2 ,         /* （中継用）予定利率基準年月＿２ */
     ztyyoteiriritu2 ,         /* （中継用）予定利率＿２ */
     ztyytirrtcalckijyunrrt2 ,         /* （中継用）予定利率計算基準利率＿２ */
     ztykwsratekijyunym2 ,         /* （中継用）為替レート基準年月＿２ */
     ztykaknsnkwsrate2 ,         /* （中継用）換算為替レート＿２ */
     ztypgaika2 ,         /* （中継用）保険料（契約通貨）＿２ */
     ztypyen2 ,         /* （中継用）保険料（円貨）＿２ */
     ztyyoteiriritukijyunym3 ,         /* （中継用）予定利率基準年月＿３ */
     ztyyoteiriritu3 ,         /* （中継用）予定利率＿３ */
     ztyytirrtcalckijyunrrt3 ,         /* （中継用）予定利率計算基準利率＿３ */
     ztykwsratekijyunym3 ,         /* （中継用）為替レート基準年月＿３ */
     ztykaknsnkwsrate3 ,         /* （中継用）換算為替レート＿３ */
     ztypgaika3 ,         /* （中継用）保険料（契約通貨）＿３ */
     ztypyen3 ,         /* （中継用）保険料（円貨）＿３ */
     ztyyoteiriritukijyunym4 ,         /* （中継用）予定利率基準年月＿４ */
     ztyyoteiriritu4 ,         /* （中継用）予定利率＿４ */
     ztyytirrtcalckijyunrrt4 ,         /* （中継用）予定利率計算基準利率＿４ */
     ztykwsratekijyunym4 ,         /* （中継用）為替レート基準年月＿４ */
     ztykaknsnkwsrate4 ,         /* （中継用）換算為替レート＿４ */
     ztypgaika4 ,         /* （中継用）保険料（契約通貨）＿４ */
     ztypyen4 ,         /* （中継用）保険料（円貨）＿４ */
     ztyyoteiriritukijyunym5 ,         /* （中継用）予定利率基準年月＿５ */
     ztyyoteiriritu5 ,         /* （中継用）予定利率＿５ */
     ztyytirrtcalckijyunrrt5 ,         /* （中継用）予定利率計算基準利率＿５ */
     ztykwsratekijyunym5 ,         /* （中継用）為替レート基準年月＿５ */
     ztykaknsnkwsrate5 ,         /* （中継用）換算為替レート＿５ */
     ztypgaika5 ,         /* （中継用）保険料（契約通貨）＿５ */
     ztypyen5 ,         /* （中継用）保険料（円貨）＿５ */
     ztyyoteiriritukijyunym6 ,         /* （中継用）予定利率基準年月＿６ */
     ztyyoteiriritu6 ,         /* （中継用）予定利率＿６ */
     ztyytirrtcalckijyunrrt6 ,         /* （中継用）予定利率計算基準利率＿６ */
     ztykwsratekijyunym6 ,         /* （中継用）為替レート基準年月＿６ */
     ztykaknsnkwsrate6 ,         /* （中継用）換算為替レート＿６ */
     ztypgaika6 ,         /* （中継用）保険料（契約通貨）＿６ */
     ztypyen6 ,         /* （中継用）保険料（円貨）＿６ */
     ztyyoteiriritukijyunym7 ,         /* （中継用）予定利率基準年月＿７ */
     ztyyoteiriritu7 ,         /* （中継用）予定利率＿７ */
     ztyytirrtcalckijyunrrt7 ,         /* （中継用）予定利率計算基準利率＿７ */
     ztykwsratekijyunym7 ,         /* （中継用）為替レート基準年月＿７ */
     ztykaknsnkwsrate7 ,         /* （中継用）換算為替レート＿７ */
     ztypgaika7 ,         /* （中継用）保険料（契約通貨）＿７ */
     ztypyen7 ,         /* （中継用）保険料（円貨）＿７ */
     ztyyoteiriritukijyunym8 ,         /* （中継用）予定利率基準年月＿８ */
     ztyyoteiriritu8 ,         /* （中継用）予定利率＿８ */
     ztyytirrtcalckijyunrrt8 ,         /* （中継用）予定利率計算基準利率＿８ */
     ztykwsratekijyunym8 ,         /* （中継用）為替レート基準年月＿８ */
     ztykaknsnkwsrate8 ,         /* （中継用）換算為替レート＿８ */
     ztypgaika8 ,         /* （中継用）保険料（契約通貨）＿８ */
     ztypyen8 ,         /* （中継用）保険料（円貨）＿８ */
     ztyyoteiriritukijyunym9 ,         /* （中継用）予定利率基準年月＿９ */
     ztyyoteiriritu9 ,         /* （中継用）予定利率＿９ */
     ztyytirrtcalckijyunrrt9 ,         /* （中継用）予定利率計算基準利率＿９ */
     ztykwsratekijyunym9 ,         /* （中継用）為替レート基準年月＿９ */
     ztykaknsnkwsrate9 ,         /* （中継用）換算為替レート＿９ */
     ztypgaika9 ,         /* （中継用）保険料（契約通貨）＿９ */
     ztypyen9 ,         /* （中継用）保険料（円貨）＿９ */
     ztyyoteiriritukijyunym10 ,         /* （中継用）予定利率基準年月＿１０ */
     ztyyoteiriritu10 ,         /* （中継用）予定利率＿１０ */
     ztyytirrtcalckijyunrrt10 ,         /* （中継用）予定利率計算基準利率＿１０ */
     ztykwsratekijyunym10 ,         /* （中継用）為替レート基準年月＿１０ */
     ztykaknsnkwsrate10 ,         /* （中継用）換算為替レート＿１０ */
     ztypgaika10 ,         /* （中継用）保険料（契約通貨）＿１０ */
     ztypyen10 ,         /* （中継用）保険料（円貨）＿１０ */
     ztyyoteiriritukijyunym11 ,         /* （中継用）予定利率基準年月＿１１ */
     ztyyoteiriritu11 ,         /* （中継用）予定利率＿１１ */
     ztyytirrtcalckijyunrrt11 ,         /* （中継用）予定利率計算基準利率＿１１ */
     ztykwsratekijyunym11 ,         /* （中継用）為替レート基準年月＿１１ */
     ztykaknsnkwsrate11 ,         /* （中継用）換算為替レート＿１１ */
     ztypgaika11 ,         /* （中継用）保険料（契約通貨）＿１１ */
     ztypyen11 ,         /* （中継用）保険料（円貨）＿１１ */
     ztyyoteiriritukijyunym12 ,         /* （中継用）予定利率基準年月＿１２ */
     ztyyoteiriritu12 ,         /* （中継用）予定利率＿１２ */
     ztyytirrtcalckijyunrrt12 ,         /* （中継用）予定利率計算基準利率＿１２ */
     ztykwsratekijyunym12 ,         /* （中継用）為替レート基準年月＿１２ */
     ztykaknsnkwsrate12 ,         /* （中継用）換算為替レート＿１２ */
     ztypgaika12 ,         /* （中継用）保険料（契約通貨）＿１２ */
     ztypyen12 ,         /* （中継用）保険料（円貨）＿１２ */
     ztyfstphyoujikbn1 ,         /* （中継用）初回保険料表示区分＿１ */
     ztyfstphyoujikbn2 ,         /* （中継用）初回保険料表示区分＿２ */
     ztyfstphyoujikbn3 ,         /* （中継用）初回保険料表示区分＿３ */
     ztyfstphyoujikbn4 ,         /* （中継用）初回保険料表示区分＿４ */
     ztyfstphyoujikbn5 ,         /* （中継用）初回保険料表示区分＿５ */
     ztyfstphyoujikbn6 ,         /* （中継用）初回保険料表示区分＿６ */
     ztyfstphyoujikbn7 ,         /* （中継用）初回保険料表示区分＿７ */
     ztyfstphyoujikbn8 ,         /* （中継用）初回保険料表示区分＿８ */
     ztyfstphyoujikbn9 ,         /* （中継用）初回保険料表示区分＿９ */
     ztyfstphyoujikbn10 ,         /* （中継用）初回保険料表示区分＿１０ */
     ztyfstphyoujikbn11 ,         /* （中継用）初回保険料表示区分＿１１ */
     ztyfstphyoujikbn12 ,         /* （中継用）初回保険料表示区分＿１２ */
     ztyytirrtitrnyobi2 ,         /* （中継用）予定利率一覧予備項目２ */
     ztyytirrtitrnhskmsgcd1 ,         /* （中継用）予定利率一覧補足メッセージコード１ */
     ztyytirrtitrnhskmsgcd2 ,         /* （中継用）予定利率一覧補足メッセージコード２ */
     ztyytirrtitrnhskmsgcd3 ,         /* （中継用）予定利率一覧補足メッセージコード３ */
     ztyytirrtitrnhskmsgcd4 ,         /* （中継用）予定利率一覧補足メッセージコード４ */
     ztyytirrtitrnhskmsgcd5 ,         /* （中継用）予定利率一覧補足メッセージコード５ */
     ztyytirrtitrnhskmsgcd6 ,         /* （中継用）予定利率一覧補足メッセージコード６ */
     ztyytirrtitrnhskmsgcd7 ,         /* （中継用）予定利率一覧補足メッセージコード７ */
     ztyytirrtitrnhskmsgcd8 ,         /* （中継用）予定利率一覧補足メッセージコード８ */
     ztyytirrtitrnyobi ,         /* （中継用）過去１年間の予定利率予備項目 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_GaikaKokyakuTuutiTy_Z;