CREATE VIEW ZT_Skeiksnbsgetujisr3Ty AS SELECT
     ztyktgysyrymd ,         /* （中継用）結合用処理日 */
     ztyktgysyono ,         /* （中継用）結合用証券番号 */
     ztyktgyfilerenno ,         /* （中継用）結合用ファイル連番 */
     ztybosyuukeirokbn ,         /* （中継用）募集経路区分 */
     ztysyokaipcashlessnyukinhyj ,         /* （中継用）初回Ｐキャッシュレス入金表示 */
     ztykigkyhsitihsyutkykarihyj ,         /* （中継用）介護給付最低保証特約有表示 */
     ztysyokaipswingriyoukbn ,         /* （中継用）初回Ｐスイング利用区分 */
     ztysknjyututkykkykkbn ,         /* （中継用）資金充当特約契約区分 */
     ztybosyuudairitengyousyukbn ,         /* （中継用）募集代理店業種区分 */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztytokusyujimutoriatukaikbn ,         /* （中継用）特殊事務取扱区分 */
     ztypmentkykyutktbicdx1 ,         /* （中継用）Ｐ免特約用特定部位コード＿１ */
     ztypmentkykyuhtnpkknx1 ,         /* （中継用）Ｐ免特約用不担保期間＿１ */
     ztypmentkykyutktbicdx2 ,         /* （中継用）Ｐ免特約用特定部位コード＿２ */
     ztypmentkykyuhtnpkknx2 ,         /* （中継用）Ｐ免特約用不担保期間＿２ */
     ztyhosyouikkatumnoshyouji ,         /* （中継用）保障一括見直表示 */
     ztyhsyuikktminaosikaisu ,         /* （中継用）保障一括見直回数 */
     ztyhsyuikktmnosdfnyuknhyj ,         /* （中継用）保障一括見直ＤＦ入金表示 */
     ztyikktmnoskikiyutkykp ,         /* （中継用）一括見直会計用特約Ｐ */
     ztyikktmnoskikiyufndsistp ,         /* （中継用）一括見直会計用ファンド災疾Ｐ */
     ztysknnjynbknsisnrt ,         /* （中継用）責任準備金精算率 */
     ztykanyujisyono ,         /* （中継用）加入時証券番号 */
     ztykanyujikykymd ,         /* （中継用）加入時契約年月日 */
     ztykanyuujihihokensyaage ,         /* （中継用）加入時被保険者年令 */
     ztykanyuujitenkanhyouji ,         /* （中継用）加入時転換表示 */
     ztyksnyuhsyuikktminosnnskbn ,         /* （中継用）加算用保障一括見直年数区分 */
     ztyaatukaisyadirtnbsynnhyj ,         /* （中継用）Ａ扱者代理店募集人表示 */
     ztybatkisyadirtnbosyuninhyj ,         /* （中継用）Ｂ扱者代理店募集人表示 */
     ztydirtnaatukaisyakojincd ,         /* （中継用）代理店Ａ扱者個人コード */
     ztydirtnbatukaisyakojincd ,         /* （中継用）代理店Ｂ扱者個人コード */
     ztysyuuseisyoukeikanensuu ,         /* （中継用）修正Ｓ用経過年数 */
     ztysyuruihnkutkbttrtkhyj ,         /* （中継用）種類変更特別取扱表示 */
     ztybnktmekyktkykhkjyutikbn ,         /* （中継用）分割前契約特約付加状態区分 */
     ztykykjiqpackhyj ,         /* （中継用）契約時Ｑパック表示 */
     ztytnknsyokaipclessriyouhyj ,         /* （中継用）転換初回ＰＣレス利用表示 */
     ztyhrkteisikibouhyouji ,         /* （中継用）払込停止希望表示 */
     ztybunkatugosonzokukeiyakus ,         /* （中継用）分割後存続契約Ｓ */
     ztymoskizkphrkekngk ,         /* （中継用）申込継続Ｐ振替金額 */
     ztykeizokuphurikaejijikaip ,         /* （中継用）継続Ｐ振替時次回Ｐ */
     ztybnktmekyksyono ,         /* （中継用）分割前契約証券番号 */
     ztybunkatumaekeiyakukihons ,         /* （中継用）分割前契約基本Ｓ */
     ztybunkatumaekeiyakusibous ,         /* （中継用）分割前契約死亡Ｓ */
     ztybnktmekykmods ,         /* （中継用）分割前契約修正Ｓ */
     ztybnktmekyksigiwrmstkyks ,         /* （中継用）分割前契約災害割増特約Ｓ */
     ztybnktmekyksyugitkyks ,         /* （中継用）分割前契約傷害特約Ｓ */
     ztybnktmkyksiginyintkykntgk ,         /* （中継用）分割前契約災害入院特約日額 */
     ztybnktmekykknkutkykntgk ,         /* （中継用）分割前契約健康特約日額 */
     ztybnktmekykhntiyunbriknsnp ,         /* （中継用）分割前契約判定用年払換算Ｐ */
     ztydai2naibuwarimodosigaku ,         /* （中継用）第２内部割戻額 */
     ztytnkngkykkstkgk ,         /* （中継用）転換後契約貸付額 */
     ztybnktmekykkstkgk ,         /* （中継用）分割前契約貸付額 */
     ztysonzokukykkasitukegk ,         /* （中継用）存続契約貸付額 */
     ztyhngkmnryoujsitihsyukngk ,         /* （中継用）変額満了時最低保証金額 */
     ztyhngksitihsyuyusykykp ,         /* （中継用）変額最低保証用主契約Ｐ */
     ztyhtnknkigmrsyukguybx1x1 ,         /* （中継用）被転換介護マル終記号予備＿１＿１ */
     ztyhtnknkigmrsyukguybx2x1 ,         /* （中継用）被転換介護マル終記号予備＿２＿１ */
     ztyhtnknkigmrsyukguybx3x1 ,         /* （中継用）被転換介護マル終記号予備＿３＿１ */
     ztyhtnknkigmrsyukguybx4x1 ,         /* （中継用）被転換介護マル終記号予備＿４＿１ */
     ztyhtnknkigmrsyukguybx5x1 ,         /* （中継用）被転換介護マル終記号予備＿５＿１ */
     ztyhtnknkigmrsyukguybx1x2 ,         /* （中継用）被転換介護マル終記号予備＿１＿２ */
     ztyhtnknkigmrsyukguybx2x2 ,         /* （中継用）被転換介護マル終記号予備＿２＿２ */
     ztyhtnknkigmrsyukguybx3x2 ,         /* （中継用）被転換介護マル終記号予備＿３＿２ */
     ztyhtnknkigmrsyukguybx4x2 ,         /* （中継用）被転換介護マル終記号予備＿４＿２ */
     ztyhtnknkigmrsyukguybx5x2 ,         /* （中継用）被転換介護マル終記号予備＿５＿２ */
     ztyhtnknkigmrsyukguybx1x3 ,         /* （中継用）被転換介護マル終記号予備＿１＿３ */
     ztyhtnknkigmrsyukguybx2x3 ,         /* （中継用）被転換介護マル終記号予備＿２＿３ */
     ztyhtnknkigmrsyukguybx3x3 ,         /* （中継用）被転換介護マル終記号予備＿３＿３ */
     ztyhtnknkigmrsyukguybx4x3 ,         /* （中継用）被転換介護マル終記号予備＿４＿３ */
     ztyhtnknkigmrsyukguybx5x3 ,         /* （中継用）被転換介護マル終記号予備＿５＿３ */
     ztyhtnknkigmrsyukguybx1x4 ,         /* （中継用）被転換介護マル終記号予備＿１＿４ */
     ztyhtnknkigmrsyukguybx2x4 ,         /* （中継用）被転換介護マル終記号予備＿２＿４ */
     ztyhtnknkigmrsyukguybx3x4 ,         /* （中継用）被転換介護マル終記号予備＿３＿４ */
     ztyhtnknkigmrsyukguybx4x4 ,         /* （中継用）被転換介護マル終記号予備＿４＿４ */
     ztyhtnknkigmrsyukguybx5x4 ,         /* （中継用）被転換介護マル終記号予備＿５＿４ */
     ztyhtnknkigmrsyukguybx1x5 ,         /* （中継用）被転換介護マル終記号予備＿１＿５ */
     ztyhtnknkigmrsyukguybx2x5 ,         /* （中継用）被転換介護マル終記号予備＿２＿５ */
     ztyhtnknkigmrsyukguybx3x5 ,         /* （中継用）被転換介護マル終記号予備＿３＿５ */
     ztyhtnknkigmrsyukguybx4x5 ,         /* （中継用）被転換介護マル終記号予備＿４＿５ */
     ztyhtnknkigmrsyukguybx5x5 ,         /* （中継用）被転換介護マル終記号予備＿５＿５ */
     ztyhtnknkigmrsyukguybx1x6 ,         /* （中継用）被転換介護マル終記号予備＿１＿６ */
     ztyhtnknkigmrsyukguybx2x6 ,         /* （中継用）被転換介護マル終記号予備＿２＿６ */
     ztyhtnknkigmrsyukguybx3x6 ,         /* （中継用）被転換介護マル終記号予備＿３＿６ */
     ztyhtnknkigmrsyukguybx4x6 ,         /* （中継用）被転換介護マル終記号予備＿４＿６ */
     ztyhtnknkigmrsyukguybx5x6 ,         /* （中継用）被転換介護マル終記号予備＿５＿６ */
     ztyyobiv1x3 ,         /* （中継用）予備項目Ｖ１＿３ */
     ztyhokensyuruikigouyobi1x1 ,         /* （中継用）保険種類記号予備１＿１ */
     ztyhokensyuruikigouyobi1x2 ,         /* （中継用）保険種類記号予備１＿２ */
     ztyhokensyuruikigouyobi1x3 ,         /* （中継用）保険種類記号予備１＿３ */
     ztyhokensyuruikigouyobi1x4 ,         /* （中継用）保険種類記号予備１＿４ */
     ztyhokensyuruikigouyobi1x5 ,         /* （中継用）保険種類記号予備１＿５ */
     ztyhokensyuruikigouyobi1x6 ,         /* （中継用）保険種類記号予備１＿６ */
     ztyhokensyuruikigouyobi1x7 ,         /* （中継用）保険種類記号予備１＿７ */
     ztyhokensyuruikigouyobi1x8 ,         /* （中継用）保険種類記号予備１＿８ */
     ztyhokensyuruikigouyobi1x9 ,         /* （中継用）保険種類記号予備１＿９ */
     ztyhokensyuruikigouyobi1x10 ,         /* （中継用）保険種類記号予備１＿１０ */
     ztyhokensyuruikigouyobi1x11 ,         /* （中継用）保険種類記号予備１＿１１ */
     ztyhokensyuruikigouyobi1x12 ,         /* （中継用）保険種類記号予備１＿１２ */
     ztyhokensyuruikigouyobi1x13 ,         /* （中継用）保険種類記号予備１＿１３ */
     ztyhokensyuruikigouyobi1x14 ,         /* （中継用）保険種類記号予備１＿１４ */
     ztyhokensyuruikigouyobi1x15 ,         /* （中継用）保険種類記号予備１＿１５ */
     ztyhokensyuruikigouyobi2x1 ,         /* （中継用）保険種類記号予備２＿１ */
     ztyhokensyuruikigouyobi2x2 ,         /* （中継用）保険種類記号予備２＿２ */
     ztyhokensyuruikigouyobi2x3 ,         /* （中継用）保険種類記号予備２＿３ */
     ztyhokensyuruikigouyobi2x4 ,         /* （中継用）保険種類記号予備２＿４ */
     ztyhokensyuruikigouyobi2x5 ,         /* （中継用）保険種類記号予備２＿５ */
     ztyhokensyuruikigouyobi2x6 ,         /* （中継用）保険種類記号予備２＿６ */
     ztyhokensyuruikigouyobi2x7 ,         /* （中継用）保険種類記号予備２＿７ */
     ztyhokensyuruikigouyobi2x8 ,         /* （中継用）保険種類記号予備２＿８ */
     ztyhokensyuruikigouyobi2x9 ,         /* （中継用）保険種類記号予備２＿９ */
     ztyhokensyuruikigouyobi2x10 ,         /* （中継用）保険種類記号予備２＿１０ */
     ztyhokensyuruikigouyobi3x1 ,         /* （中継用）保険種類記号予備３＿１ */
     ztyhokensyuruikigouyobi3x2 ,         /* （中継用）保険種類記号予備３＿２ */
     ztyhokensyuruikigouyobi3x3 ,         /* （中継用）保険種類記号予備３＿３ */
     ztyhokensyuruikigouyobi3x4 ,         /* （中継用）保険種類記号予備３＿４ */
     ztyhokensyuruikigouyobi3x5 ,         /* （中継用）保険種類記号予備３＿５ */
     ztyhokensyuruikigouyobi3x6 ,         /* （中継用）保険種類記号予備３＿６ */
     ztyhokensyuruikigouyobi3x7 ,         /* （中継用）保険種類記号予備３＿７ */
     ztyhokensyuruikigouyobi3x8 ,         /* （中継用）保険種類記号予備３＿８ */
     ztyhokensyuruikigouyobi3x9 ,         /* （中継用）保険種類記号予備３＿９ */
     ztyhokensyuruikigouyobi3x10 ,         /* （中継用）保険種類記号予備３＿１０ */
     ztymaruteikigouyobix1 ,         /* （中継用）マル定記号予備＿１ */
     ztymaruteikigouyobix2 ,         /* （中継用）マル定記号予備＿２ */
     ztymaruteikigouyobix3 ,         /* （中継用）マル定記号予備＿３ */
     ztymaruteikigouyobix4 ,         /* （中継用）マル定記号予備＿４ */
     ztymaruteikigouyobix5 ,         /* （中継用）マル定記号予備＿５ */
     ztymaruyoukigouyobix1 ,         /* （中継用）マル養記号予備＿１ */
     ztymaruyoukigouyobix2 ,         /* （中継用）マル養記号予備＿２ */
     ztymaruyoukigouyobix3 ,         /* （中継用）マル養記号予備＿３ */
     ztymaruyoukigouyobix4 ,         /* （中継用）マル養記号予備＿４ */
     ztymaruyoukigouyobix5 ,         /* （中継用）マル養記号予備＿５ */
     ztymarusyuukigouyobix1 ,         /* （中継用）マル終記号予備＿１ */
     ztymarusyuukigouyobix2 ,         /* （中継用）マル終記号予備＿２ */
     ztymarusyuukigouyobix3 ,         /* （中継用）マル終記号予備＿３ */
     ztymarusyuukigouyobix4 ,         /* （中継用）マル終記号予備＿４ */
     ztymarusyuukigouyobix5 ,         /* （中継用）マル終記号予備＿５ */
     ztytokuteikigouyobix1 ,         /* （中継用）トク定記号予備＿１ */
     ztytokuteikigouyobix2 ,         /* （中継用）トク定記号予備＿２ */
     ztytokuteikigouyobix3 ,         /* （中継用）トク定記号予備＿３ */
     ztytokuteikigouyobix4 ,         /* （中継用）トク定記号予備＿４ */
     ztytokuteikigouyobix5 ,         /* （中継用）トク定記号予備＿５ */
     ztykzkmrtikguybx1x1 ,         /* （中継用）家族マル定記号予備＿１＿１ */
     ztykzkmrtikguybx2x1 ,         /* （中継用）家族マル定記号予備＿２＿１ */
     ztykzkmrtikguybx3x1 ,         /* （中継用）家族マル定記号予備＿３＿１ */
     ztykzkmrtikguybx4x1 ,         /* （中継用）家族マル定記号予備＿４＿１ */
     ztykzkmrtikguybx5x1 ,         /* （中継用）家族マル定記号予備＿５＿１ */
     ztykzkmrtikguybx1x2 ,         /* （中継用）家族マル定記号予備＿１＿２ */
     ztykzkmrtikguybx2x2 ,         /* （中継用）家族マル定記号予備＿２＿２ */
     ztykzkmrtikguybx3x2 ,         /* （中継用）家族マル定記号予備＿３＿２ */
     ztykzkmrtikguybx4x2 ,         /* （中継用）家族マル定記号予備＿４＿２ */
     ztykzkmrtikguybx5x2 ,         /* （中継用）家族マル定記号予備＿５＿２ */
     ztykzkmrtikguybx1x3 ,         /* （中継用）家族マル定記号予備＿１＿３ */
     ztykzkmrtikguybx2x3 ,         /* （中継用）家族マル定記号予備＿２＿３ */
     ztykzkmrtikguybx3x3 ,         /* （中継用）家族マル定記号予備＿３＿３ */
     ztykzkmrtikguybx4x3 ,         /* （中継用）家族マル定記号予備＿４＿３ */
     ztykzkmrtikguybx5x3 ,         /* （中継用）家族マル定記号予備＿５＿３ */
     ztykzkmrtikguybx1x4 ,         /* （中継用）家族マル定記号予備＿１＿４ */
     ztykzkmrtikguybx2x4 ,         /* （中継用）家族マル定記号予備＿２＿４ */
     ztykzkmrtikguybx3x4 ,         /* （中継用）家族マル定記号予備＿３＿４ */
     ztykzkmrtikguybx4x4 ,         /* （中継用）家族マル定記号予備＿４＿４ */
     ztykzkmrtikguybx5x4 ,         /* （中継用）家族マル定記号予備＿５＿４ */
     ztykzkmrtikguybx1x5 ,         /* （中継用）家族マル定記号予備＿１＿５ */
     ztykzkmrtikguybx2x5 ,         /* （中継用）家族マル定記号予備＿２＿５ */
     ztykzkmrtikguybx3x5 ,         /* （中継用）家族マル定記号予備＿３＿５ */
     ztykzkmrtikguybx4x5 ,         /* （中継用）家族マル定記号予備＿４＿５ */
     ztykzkmrtikguybx5x5 ,         /* （中継用）家族マル定記号予備＿５＿５ */
     ztykzkmrtikguybx1x6 ,         /* （中継用）家族マル定記号予備＿１＿６ */
     ztykzkmrtikguybx2x6 ,         /* （中継用）家族マル定記号予備＿２＿６ */
     ztykzkmrtikguybx3x6 ,         /* （中継用）家族マル定記号予備＿３＿６ */
     ztykzkmrtikguybx4x6 ,         /* （中継用）家族マル定記号予備＿４＿６ */
     ztykzkmrtikguybx5x6 ,         /* （中継用）家族マル定記号予備＿５＿６ */
     ztykzkmrtikguybx1x7 ,         /* （中継用）家族マル定記号予備＿１＿７ */
     ztykzkmrtikguybx2x7 ,         /* （中継用）家族マル定記号予備＿２＿７ */
     ztykzkmrtikguybx3x7 ,         /* （中継用）家族マル定記号予備＿３＿７ */
     ztykzkmrtikguybx4x7 ,         /* （中継用）家族マル定記号予備＿４＿７ */
     ztykzkmrtikguybx5x7 ,         /* （中継用）家族マル定記号予備＿５＿７ */
     ztykzkmrtikguybx1x8 ,         /* （中継用）家族マル定記号予備＿１＿８ */
     ztykzkmrtikguybx2x8 ,         /* （中継用）家族マル定記号予備＿２＿８ */
     ztykzkmrtikguybx3x8 ,         /* （中継用）家族マル定記号予備＿３＿８ */
     ztykzkmrtikguybx4x8 ,         /* （中継用）家族マル定記号予備＿４＿８ */
     ztykzkmrtikguybx5x8 ,         /* （中継用）家族マル定記号予備＿５＿８ */
     ztykzkmrtikguybx1x9 ,         /* （中継用）家族マル定記号予備＿１＿９ */
     ztykzkmrtikguybx2x9 ,         /* （中継用）家族マル定記号予備＿２＿９ */
     ztykzkmrtikguybx3x9 ,         /* （中継用）家族マル定記号予備＿３＿９ */
     ztykzkmrtikguybx4x9 ,         /* （中継用）家族マル定記号予備＿４＿９ */
     ztykzkmrtikguybx5x9 ,         /* （中継用）家族マル定記号予備＿５＿９ */
     ztykzkmrtikguybx1x10 ,         /* （中継用）家族マル定記号予備＿１＿１０ */
     ztykzkmrtikguybx2x10 ,         /* （中継用）家族マル定記号予備＿２＿１０ */
     ztykzkmrtikguybx3x10 ,         /* （中継用）家族マル定記号予備＿３＿１０ */
     ztykzkmrtikguybx4x10 ,         /* （中継用）家族マル定記号予備＿４＿１０ */
     ztykzkmrtikguybx5x10 ,         /* （中継用）家族マル定記号予備＿５＿１０ */
     ztysyugittkykkguybx1 ,         /* （中継用）傷害特約記号予備＿１ */
     ztysyugittkykkguybx2 ,         /* （中継用）傷害特約記号予備＿２ */
     ztysyugittkykkguybx3 ,         /* （中継用）傷害特約記号予備＿３ */
     ztysyugittkykkguybx4 ,         /* （中継用）傷害特約記号予備＿４ */
     ztysyugittkykkguybx5 ,         /* （中継用）傷害特約記号予備＿５ */
     ztysigiwrmstkykkguybx1 ,         /* （中継用）災害割増特約記号予備＿１ */
     ztysigiwrmstkykkguybx2 ,         /* （中継用）災害割増特約記号予備＿２ */
     ztysigiwrmstkykkguybx3 ,         /* （中継用）災害割増特約記号予備＿３ */
     ztysigiwrmstkykkguybx4 ,         /* （中継用）災害割増特約記号予備＿４ */
     ztysigiwrmstkykkguybx5 ,         /* （中継用）災害割増特約記号予備＿５ */
     ztysiginyuintkykkguybx1 ,         /* （中継用）災害入院特約記号予備＿１ */
     ztysiginyuintkykkguybx2 ,         /* （中継用）災害入院特約記号予備＿２ */
     ztysiginyuintkykkguybx3 ,         /* （中継用）災害入院特約記号予備＿３ */
     ztysiginyuintkykkguybx4 ,         /* （中継用）災害入院特約記号予備＿４ */
     ztysiginyuintkykkguybx5 ,         /* （中継用）災害入院特約記号予備＿５ */
     ztysppinyuintkykkguybx1 ,         /* （中継用）疾病入院特約記号予備＿１ */
     ztysppinyuintkykkguybx2 ,         /* （中継用）疾病入院特約記号予備＿２ */
     ztysppinyuintkykkguybx3 ,         /* （中継用）疾病入院特約記号予備＿３ */
     ztysppinyuintkykkguybx4 ,         /* （中継用）疾病入院特約記号予備＿４ */
     ztysppinyuintkykkguybx5 ,         /* （中継用）疾病入院特約記号予備＿５ */
     ztysijnbyutkykkguybx1 ,         /* （中継用）成人病特約記号予備＿１ */
     ztysijnbyutkykkguybx2 ,         /* （中継用）成人病特約記号予備＿２ */
     ztysijnbyutkykkguybx3 ,         /* （中継用）成人病特約記号予備＿３ */
     ztysijnbyutkykkguybx4 ,         /* （中継用）成人病特約記号予備＿４ */
     ztysijnbyutkykkguybx5 ,         /* （中継用）成人病特約記号予備＿５ */
     ztykzkiryoutkykkguybx1 ,         /* （中継用）家族医療特約記号予備＿１ */
     ztykzkiryoutkykkguybx2 ,         /* （中継用）家族医療特約記号予備＿２ */
     ztykzkiryoutkykkguybx3 ,         /* （中継用）家族医療特約記号予備＿３ */
     ztykzkiryoutkykkguybx4 ,         /* （中継用）家族医療特約記号予備＿４ */
     ztykzkiryoutkykkguybx5 ,         /* （中継用）家族医療特約記号予備＿５ */
     ztysykkyuhtkykkguybx1 ,         /* （中継用）初期給付特約記号予備＿１ */
     ztysykkyuhtkykkguybx2 ,         /* （中継用）初期給付特約記号予備＿２ */
     ztysykkyuhtkykkguybx3 ,         /* （中継用）初期給付特約記号予備＿３ */
     ztysykkyuhtkykkguybx4 ,         /* （中継用）初期給付特約記号予備＿４ */
     ztysykkyuhtkykkguybx5 ,         /* （中継用）初期給付特約記号予備＿５ */
     ztynkdtmrtikguyobix1 ,         /* （中継用）年金建マル定記号予備＿１ */
     ztynkdtmrtikguyobix2 ,         /* （中継用）年金建マル定記号予備＿２ */
     ztynkdtmrtikguyobix3 ,         /* （中継用）年金建マル定記号予備＿３ */
     ztynkdtmrtikguyobix4 ,         /* （中継用）年金建マル定記号予備＿４ */
     ztynkdtmrtikguyobix5 ,         /* （中継用）年金建マル定記号予備＿５ */
     ztynkdatetokuteikguyobix1 ,         /* （中継用）年金建トク定記号予備＿１ */
     ztynkdatetokuteikguyobix2 ,         /* （中継用）年金建トク定記号予備＿２ */
     ztynkdatetokuteikguyobix3 ,         /* （中継用）年金建トク定記号予備＿３ */
     ztynkdatetokuteikguyobix4 ,         /* （中継用）年金建トク定記号予備＿４ */
     ztynkdatetokuteikguyobix5 ,         /* （中継用）年金建トク定記号予備＿５ */
     ztykaigonkdtmrtikguyobix1 ,         /* （中継用）介護年金建マル定記号予備＿１ */
     ztykaigonkdtmrtikguyobix2 ,         /* （中継用）介護年金建マル定記号予備＿２ */
     ztykaigonkdtmrtikguyobix3 ,         /* （中継用）介護年金建マル定記号予備＿３ */
     ztykaigonkdtmrtikguyobix4 ,         /* （中継用）介護年金建マル定記号予備＿４ */
     ztykaigonkdtmrtikguyobix5 ,         /* （中継用）介護年金建マル定記号予備＿５ */
     ztykaigonkdttktikguyobix1 ,         /* （中継用）介護年金建トク定記号予備＿１ */
     ztykaigonkdttktikguyobix2 ,         /* （中継用）介護年金建トク定記号予備＿２ */
     ztykaigonkdttktikguyobix3 ,         /* （中継用）介護年金建トク定記号予備＿３ */
     ztykaigonkdttktikguyobix4 ,         /* （中継用）介護年金建トク定記号予備＿４ */
     ztykaigonkdttktikguyobix5 ,         /* （中継用）介護年金建トク定記号予備＿５ */
     ztykaigomaruteikigouyobix1 ,         /* （中継用）介護マル定記号予備＿１ */
     ztykaigomaruteikigouyobix2 ,         /* （中継用）介護マル定記号予備＿２ */
     ztykaigomaruteikigouyobix3 ,         /* （中継用）介護マル定記号予備＿３ */
     ztykaigomaruteikigouyobix4 ,         /* （中継用）介護マル定記号予備＿４ */
     ztykaigomaruteikigouyobix5 ,         /* （中継用）介護マル定記号予備＿５ */
     ztykaigotokuteikigouyobix1 ,         /* （中継用）介護トク定記号予備＿１ */
     ztykaigotokuteikigouyobix2 ,         /* （中継用）介護トク定記号予備＿２ */
     ztykaigotokuteikigouyobix3 ,         /* （中継用）介護トク定記号予備＿３ */
     ztykaigotokuteikigouyobix4 ,         /* （中継用）介護トク定記号予備＿４ */
     ztykaigotokuteikigouyobix5 ,         /* （中継用）介護トク定記号予備＿５ */
     ztysiznmrtikguybx1 ,         /* （中継用）生存マル定記号予備＿１ */
     ztysiznmrtikguybx2 ,         /* （中継用）生存マル定記号予備＿２ */
     ztysiznmrtikguybx3 ,         /* （中継用）生存マル定記号予備＿３ */
     ztysiznmrtikguybx4 ,         /* （中継用）生存マル定記号予備＿４ */
     ztysiznmrtikguybx5 ,         /* （中継用）生存マル定記号予備＿５ */
     ztyteigenmaruteikigouyobix1 ,         /* （中継用）逓減マル定記号予備＿１ */
     ztyteigenmaruteikigouyobix2 ,         /* （中継用）逓減マル定記号予備＿２ */
     ztyteigenmaruteikigouyobix3 ,         /* （中継用）逓減マル定記号予備＿３ */
     ztyteigenmaruteikigouyobix4 ,         /* （中継用）逓減マル定記号予備＿４ */
     ztyteigenmaruteikigouyobix5 ,         /* （中継用）逓減マル定記号予備＿５ */
     ztyteigentokuteikigouyobix1 ,         /* （中継用）逓減トク定記号予備＿１ */
     ztyteigentokuteikigouyobix2 ,         /* （中継用）逓減トク定記号予備＿２ */
     ztyteigentokuteikigouyobix3 ,         /* （中継用）逓減トク定記号予備＿３ */
     ztyteigentokuteikigouyobix4 ,         /* （中継用）逓減トク定記号予備＿４ */
     ztyteigentokuteikigouyobix5 ,         /* （中継用）逓減トク定記号予備＿５ */
     ztykigtignmrtikguybx1 ,         /* （中継用）介護逓減マル定記号予備＿１ */
     ztykigtignmrtikguybx2 ,         /* （中継用）介護逓減マル定記号予備＿２ */
     ztykigtignmrtikguybx3 ,         /* （中継用）介護逓減マル定記号予備＿３ */
     ztykigtignmrtikguybx4 ,         /* （中継用）介護逓減マル定記号予備＿４ */
     ztykigtignmrtikguybx5 ,         /* （中継用）介護逓減マル定記号予備＿５ */
     ztykigtigntktikguybx1 ,         /* （中継用）介護逓減トク定記号予備＿１ */
     ztykigtigntktikguybx2 ,         /* （中継用）介護逓減トク定記号予備＿２ */
     ztykigtigntktikguybx3 ,         /* （中継用）介護逓減トク定記号予備＿３ */
     ztykigtigntktikguybx4 ,         /* （中継用）介護逓減トク定記号予備＿４ */
     ztykigtigntktikguybx5 ,         /* （中継用）介護逓減トク定記号予備＿５ */
     ztytuuintokuyakukigouyobix1 ,         /* （中継用）通院特約記号予備＿１ */
     ztytuuintokuyakukigouyobix2 ,         /* （中継用）通院特約記号予備＿２ */
     ztytuuintokuyakukigouyobix3 ,         /* （中継用）通院特約記号予備＿３ */
     ztytuuintokuyakukigouyobix4 ,         /* （中継用）通院特約記号予備＿４ */
     ztytuuintokuyakukigouyobix5 ,         /* （中継用）通院特約記号予備＿５ */
     ztyjysisppitkykkguyobix1 ,         /* （中継用）女性疾病特約記号予備＿１ */
     ztyjysisppitkykkguyobix2 ,         /* （中継用）女性疾病特約記号予備＿２ */
     ztyjysisppitkykkguyobix3 ,         /* （中継用）女性疾病特約記号予備＿３ */
     ztyjysisppitkykkguyobix4 ,         /* （中継用）女性疾病特約記号予備＿４ */
     ztyjysisppitkykkguyobix5 ,         /* （中継用）女性疾病特約記号予備＿５ */
     ztytksttkykkguybx1 ,         /* （中継用）特疾特約記号予備＿１ */
     ztytksttkykkguybx2 ,         /* （中継用）特疾特約記号予備＿２ */
     ztytksttkykkguybx3 ,         /* （中継用）特疾特約記号予備＿３ */
     ztytksttkykkguybx4 ,         /* （中継用）特疾特約記号予備＿４ */
     ztytksttkykkguybx5 ,         /* （中継用）特疾特約記号予備＿５ */
     ztydi2tksttkykkguybx1 ,         /* （中継用）第２特疾特約記号予備＿１ */
     ztydi2tksttkykkguybx2 ,         /* （中継用）第２特疾特約記号予備＿２ */
     ztydi2tksttkykkguybx3 ,         /* （中継用）第２特疾特約記号予備＿３ */
     ztydi2tksttkykkguybx4 ,         /* （中継用）第２特疾特約記号予備＿４ */
     ztydi2tksttkykkguybx5 ,         /* （中継用）第２特疾特約記号予備＿５ */
     ztymnsttkykkguybx1 ,         /* （中継用）慢疾特約記号予備＿１ */
     ztymnsttkykkguybx2 ,         /* （中継用）慢疾特約記号予備＿２ */
     ztymnsttkykkguybx3 ,         /* （中継用）慢疾特約記号予備＿３ */
     ztymnsttkykkguybx4 ,         /* （中継用）慢疾特約記号予備＿４ */
     ztymnsttkykkguybx5 ,         /* （中継用）慢疾特約記号予備＿５ */
     ztydi2mnsttkykkguybx1 ,         /* （中継用）第２慢疾特約記号予備＿１ */
     ztydi2mnsttkykkguybx2 ,         /* （中継用）第２慢疾特約記号予備＿２ */
     ztydi2mnsttkykkguybx3 ,         /* （中継用）第２慢疾特約記号予備＿３ */
     ztydi2mnsttkykkguybx4 ,         /* （中継用）第２慢疾特約記号予備＿４ */
     ztydi2mnsttkykkguybx5 ,         /* （中継用）第２慢疾特約記号予備＿５ */
     ztysugusnsyutkykkguybx1 ,         /* （中継用）総合損傷特約記号予備＿１ */
     ztysugusnsyutkykkguybx2 ,         /* （中継用）総合損傷特約記号予備＿２ */
     ztysugusnsyutkykkguybx3 ,         /* （中継用）総合損傷特約記号予備＿３ */
     ztysugusnsyutkykkguybx4 ,         /* （中継用）総合損傷特約記号予備＿４ */
     ztysugusnsyutkykkguybx5 ,         /* （中継用）総合損傷特約記号予備＿５ */
     ztykaigonktkykkguyobix1 ,         /* （中継用）介護年金特約記号予備＿１ */
     ztykaigonktkykkguyobix2 ,         /* （中継用）介護年金特約記号予備＿２ */
     ztykaigonktkykkguyobix3 ,         /* （中継用）介護年金特約記号予備＿３ */
     ztykaigonktkykkguyobix4 ,         /* （中継用）介護年金特約記号予備＿４ */
     ztykaigonktkykkguyobix5 ,         /* （中継用）介護年金特約記号予備＿５ */
     ztyitjbrkignktkykkguybx1 ,         /* （中継用）一時払介護年金特約記号予備＿１ */
     ztyitjbrkignktkykkguybx2 ,         /* （中継用）一時払介護年金特約記号予備＿２ */
     ztyitjbrkignktkykkguybx3 ,         /* （中継用）一時払介護年金特約記号予備＿３ */
     ztyitjbrkignktkykkguybx4 ,         /* （中継用）一時払介護年金特約記号予備＿４ */
     ztyitjbrkignktkykkguybx5 ,         /* （中継用）一時払介護年金特約記号予備＿５ */
     ztydi2syugitkykkguybx1 ,         /* （中継用）第２傷害特約記号予備＿１ */
     ztydi2syugitkykkguybx2 ,         /* （中継用）第２傷害特約記号予備＿２ */
     ztydi2syugitkykkguybx3 ,         /* （中継用）第２傷害特約記号予備＿３ */
     ztydi2syugitkykkguybx4 ,         /* （中継用）第２傷害特約記号予備＿４ */
     ztydi2syugitkykkguybx5 ,         /* （中継用）第２傷害特約記号予備＿５ */
     ztydi2sigiwrmstkykkguybx1 ,         /* （中継用）第２災害割増特約記号予備＿１ */
     ztydi2sigiwrmstkykkguybx2 ,         /* （中継用）第２災害割増特約記号予備＿２ */
     ztydi2sigiwrmstkykkguybx3 ,         /* （中継用）第２災害割増特約記号予備＿３ */
     ztydi2sigiwrmstkykkguybx4 ,         /* （中継用）第２災害割増特約記号予備＿４ */
     ztydi2sigiwrmstkykkguybx5 ,         /* （中継用）第２災害割増特約記号予備＿５ */
     ztydi2siginyuintkykkguybx1 ,         /* （中継用）第２災害入院特約記号予備＿１ */
     ztydi2siginyuintkykkguybx2 ,         /* （中継用）第２災害入院特約記号予備＿２ */
     ztydi2siginyuintkykkguybx3 ,         /* （中継用）第２災害入院特約記号予備＿３ */
     ztydi2siginyuintkykkguybx4 ,         /* （中継用）第２災害入院特約記号予備＿４ */
     ztydi2siginyuintkykkguybx5 ,         /* （中継用）第２災害入院特約記号予備＿５ */
     ztydi2sppinyuintkykkguybx1 ,         /* （中継用）第２疾病入院特約記号予備＿１ */
     ztydi2sppinyuintkykkguybx2 ,         /* （中継用）第２疾病入院特約記号予備＿２ */
     ztydi2sppinyuintkykkguybx3 ,         /* （中継用）第２疾病入院特約記号予備＿３ */
     ztydi2sppinyuintkykkguybx4 ,         /* （中継用）第２疾病入院特約記号予備＿４ */
     ztydi2sppinyuintkykkguybx5 ,         /* （中継用）第２疾病入院特約記号予備＿５ */
     ztydi2sijnbyutkykkguybx1 ,         /* （中継用）第２成人病特約記号予備＿１ */
     ztydi2sijnbyutkykkguybx2 ,         /* （中継用）第２成人病特約記号予備＿２ */
     ztydi2sijnbyutkykkguybx3 ,         /* （中継用）第２成人病特約記号予備＿３ */
     ztydi2sijnbyutkykkguybx4 ,         /* （中継用）第２成人病特約記号予備＿４ */
     ztydi2sijnbyutkykkguybx5 ,         /* （中継用）第２成人病特約記号予備＿５ */
     ztydai2tuintkykkguyobix1 ,         /* （中継用）第２通院特約記号予備＿１ */
     ztydai2tuintkykkguyobix2 ,         /* （中継用）第２通院特約記号予備＿２ */
     ztydai2tuintkykkguyobix3 ,         /* （中継用）第２通院特約記号予備＿３ */
     ztydai2tuintkykkguyobix4 ,         /* （中継用）第２通院特約記号予備＿４ */
     ztydai2tuintkykkguyobix5 ,         /* （中継用）第２通院特約記号予備＿５ */
     ztydi2jysisppitkykkguybx1 ,         /* （中継用）第２女性疾病特約記号予備＿１ */
     ztydi2jysisppitkykkguybx2 ,         /* （中継用）第２女性疾病特約記号予備＿２ */
     ztydi2jysisppitkykkguybx3 ,         /* （中継用）第２女性疾病特約記号予備＿３ */
     ztydi2jysisppitkykkguybx4 ,         /* （中継用）第２女性疾病特約記号予備＿４ */
     ztydi2jysisppitkykkguybx5 ,         /* （中継用）第２女性疾病特約記号予備＿５ */
     ztydi2sugusnsyutkykkguybx1 ,         /* （中継用）第２総合損傷特約記号予備＿１ */
     ztydi2sugusnsyutkykkguybx2 ,         /* （中継用）第２総合損傷特約記号予備＿２ */
     ztydi2sugusnsyutkykkguybx3 ,         /* （中継用）第２総合損傷特約記号予備＿３ */
     ztydi2sugusnsyutkykkguybx4 ,         /* （中継用）第２総合損傷特約記号予備＿４ */
     ztydi2sugusnsyutkykkguybx5 ,         /* （中継用）第２総合損傷特約記号予備＿５ */
     ztydi2sykkyuhtkykkguybx1 ,         /* （中継用）第２初期給付特約記号予備＿１ */
     ztydi2sykkyuhtkykkguybx2 ,         /* （中継用）第２初期給付特約記号予備＿２ */
     ztydi2sykkyuhtkykkguybx3 ,         /* （中継用）第２初期給付特約記号予備＿３ */
     ztydi2sykkyuhtkykkguybx4 ,         /* （中継用）第２初期給付特約記号予備＿４ */
     ztydi2sykkyuhtkykkguybx5 ,         /* （中継用）第２初期給付特約記号予備＿５ */
     ztysetaitehknsyuruiyobi1x1 ,         /* （中継用）セット相手保険種類予備１＿１ */
     ztysetaitehknsyuruiyobi1x2 ,         /* （中継用）セット相手保険種類予備１＿２ */
     ztysetaitehknsyuruiyobi1x3 ,         /* （中継用）セット相手保険種類予備１＿３ */
     ztysetaitehknsyuruiyobi1x4 ,         /* （中継用）セット相手保険種類予備１＿４ */
     ztysetaitehknsyuruiyobi1x5 ,         /* （中継用）セット相手保険種類予備１＿５ */
     ztysetaitehknsyuruiyobi1x6 ,         /* （中継用）セット相手保険種類予備１＿６ */
     ztysetaitehknsyuruiyobi1x7 ,         /* （中継用）セット相手保険種類予備１＿７ */
     ztysetaitehknsyuruiyobi1x8 ,         /* （中継用）セット相手保険種類予備１＿８ */
     ztysetaitehknsyuruiyobi1x9 ,         /* （中継用）セット相手保険種類予備１＿９ */
     ztysetaitehknsyuruiyobi1x10 ,         /* （中継用）セット相手保険種類予備１＿１０ */
     ztysetaitehknsyuruiyobi1x11 ,         /* （中継用）セット相手保険種類予備１＿１１ */
     ztysetaitehknsyuruiyobi1x12 ,         /* （中継用）セット相手保険種類予備１＿１２ */
     ztysetaitehknsyuruiyobi1x13 ,         /* （中継用）セット相手保険種類予備１＿１３ */
     ztysetaitehknsyuruiyobi1x14 ,         /* （中継用）セット相手保険種類予備１＿１４ */
     ztysetaitehknsyuruiyobi1x15 ,         /* （中継用）セット相手保険種類予備１＿１５ */
     ztysetaitehknsyuruiyobi2x1 ,         /* （中継用）セット相手保険種類予備２＿１ */
     ztysetaitehknsyuruiyobi2x2 ,         /* （中継用）セット相手保険種類予備２＿２ */
     ztysetaitehknsyuruiyobi2x3 ,         /* （中継用）セット相手保険種類予備２＿３ */
     ztysetaitehknsyuruiyobi2x4 ,         /* （中継用）セット相手保険種類予備２＿４ */
     ztysetaitehknsyuruiyobi2x5 ,         /* （中継用）セット相手保険種類予備２＿５ */
     ztysetaitehknsyuruiyobi2x6 ,         /* （中継用）セット相手保険種類予備２＿６ */
     ztysetaitehknsyuruiyobi2x7 ,         /* （中継用）セット相手保険種類予備２＿７ */
     ztysetaitehknsyuruiyobi2x8 ,         /* （中継用）セット相手保険種類予備２＿８ */
     ztysetaitehknsyuruiyobi2x9 ,         /* （中継用）セット相手保険種類予備２＿９ */
     ztysetaitehknsyuruiyobi2x10 ,         /* （中継用）セット相手保険種類予備２＿１０ */
     ztysetaitehknsyuruiyobi3x1 ,         /* （中継用）セット相手保険種類予備３＿１ */
     ztysetaitehknsyuruiyobi3x2 ,         /* （中継用）セット相手保険種類予備３＿２ */
     ztysetaitehknsyuruiyobi3x3 ,         /* （中継用）セット相手保険種類予備３＿３ */
     ztysetaitehknsyuruiyobi3x4 ,         /* （中継用）セット相手保険種類予備３＿４ */
     ztysetaitehknsyuruiyobi3x5 ,         /* （中継用）セット相手保険種類予備３＿５ */
     ztysetaitehknsyuruiyobi3x6 ,         /* （中継用）セット相手保険種類予備３＿６ */
     ztysetaitehknsyuruiyobi3x7 ,         /* （中継用）セット相手保険種類予備３＿７ */
     ztysetaitehknsyuruiyobi3x8 ,         /* （中継用）セット相手保険種類予備３＿８ */
     ztysetaitehknsyuruiyobi3x9 ,         /* （中継用）セット相手保険種類予備３＿９ */
     ztysetaitehknsyuruiyobi3x10 ,         /* （中継用）セット相手保険種類予備３＿１０ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_Skeiksnbsgetujisr3Ty_Z;