CREATE VIEW ZT_IdouTyousyoTy AS SELECT
     ztysubsystemid ,         /* （中継用）サブシステムＩＤ */
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztysyono ,         /* （中継用）証券番号 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztykacd ,         /* （中継用）課コード */
     ztytantocd ,         /* （中継用）担当コード */
     ztysyorisosikicd ,         /* （中継用）処理組織コード */
     ztyshrtysysyuruicd ,         /* （中継用）支払調書種類コード */
     ztysyoritaisyoukbn ,         /* （中継用）処理対象区分 */
     ztybaitaiskshunoriyuukbn1 ,         /* （中継用）媒体作成不能理由区分１ */
     ztybaitaiskshunoriyuukbn2 ,         /* （中継用）媒体作成不能理由区分２ */
     ztybaitaiskshunoriyuukbn3 ,         /* （中継用）媒体作成不能理由区分３ */
     ztybaitaiskshunoriyuukbn4 ,         /* （中継用）媒体作成不能理由区分４ */
     ztybaitaiskshunoriyuukbn5 ,         /* （中継用）媒体作成不能理由区分５ */
     ztyshrtysyjyuusyocd ,         /* （中継用）支払調書住所コード */
     ztyshrtysyjyuusyo ,         /* （中継用）支払調書住所 */
     ztykyknmkj35 ,         /* （中継用）契約者名（漢字）（３５桁） */
     ztyyobiv3 ,         /* （中継用）予備項目Ｖ３ */
     ztyyobiv25 ,         /* （中継用）予備項目Ｖ２５ */
     ztyoldkykadrcd ,         /* （中継用）旧契約者住所コード */
     ztykjoldkykadr ,         /* （中継用）漢字旧契約者住所 */
     ztykjoldkyknm35 ,         /* （中継用）漢字旧契約者名（３５桁） */
     ztyyobiv3x2 ,         /* （中継用）予備項目Ｖ３＿２ */
     ztyyobiv25x1 ,         /* （中継用）予備項目Ｖ２５＿１ */
     ztyhhknnmkj ,         /* （中継用）被保険者名（漢字） */
     ztyyobiv3x3 ,         /* （中継用）予備項目Ｖ３＿３ */
     ztyyobiv17 ,         /* （中継用）予備項目Ｖ１７ */
     ztykyksibouymd ,         /* （中継用）契約者死亡年月日 */
     ztykouryokuhasseiymd ,         /* （中継用）効力発生日 */
     ztykyksiboumeihensyoriymd ,         /* （中継用）契約者死亡名義変更処理年月日 */
     ztyyobiv8 ,         /* （中継用）予備項目Ｖ８ */
     ztyyobiv8x2 ,         /* （中継用）予備項目Ｖ８＿２ */
     ztyyobiv8x3 ,         /* （中継用）予備項目Ｖ８＿３ */
     ztyyobiv8x4 ,         /* （中継用）予備項目Ｖ８＿４ */
     ztykyksibouhyoukagk ,         /* （中継用）契約者死亡評価額 */
     ztykihrkmp ,         /* （中継用）既払込保険料 */
     ztyoldkykkihrkmpyouhyj ,         /* （中継用）旧契約者既払込保険料要表示 */
     ztyoldkykkihrkmp ,         /* （中継用）旧契約者既払込保険料 */
     ztyyobin11 ,         /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2 ,         /* （中継用）予備項目Ｎ１１＿２ */
     ztyyobin11x3 ,         /* （中継用）予備項目Ｎ１１＿３ */
     ztyyobin11x4 ,         /* （中継用）予備項目Ｎ１１＿４ */
     ztysakuseiymd ,         /* （中継用）作成日 */
     ztyhuho2kykdisp ,         /* （中継用）普保Ⅱ契約表示 */
     ztyshrtysyhknsyukbn ,         /* （中継用）支払調書保険種類区分 */
     ztyyobiv9 ,         /* （中継用）予備項目Ｖ９ */
     ztytekiyouranhensyuukbn1 ,         /* （中継用）摘要欄編集区分１ */
     ztytekiyouranhensyuukbn2 ,         /* （中継用）摘要欄編集区分２ */
     ztytekiyouranhensyuukbn3 ,         /* （中継用）摘要欄編集区分３ */
     ztytekiyouranhensyuukbn4 ,         /* （中継用）摘要欄編集区分４ */
     ztytekiyouranhensyuukbn5 ,         /* （中継用）摘要欄編集区分５ */
     ztyyobiv116 ,         /* （中継用）予備項目Ｖ１１６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_IdouTyousyoTy_Z;