CREATE VIEW IM_KhTyouhyoumsg AS SELECT
     syoruiCd ,         /* 書類コード */
     meigihnkjiyuu ,         /* 名義変更事由 */
     kyksbumu ,         /* 契約者死亡有無 */
     shrumu ,         /* 支払有無区分 */
     tuityouumu ,         /* 追徴有無区分 */
     tyouhyoutitle ,         /* 帳票タイトル */
     rsouhuannaimsg1 ,         /* （帳票用）送付案内メッセージ１ */
     rsouhuannaimsg2 ,         /* （帳票用）送付案内メッセージ２ */
     rsouhuannaimsg3 ,         /* （帳票用）送付案内メッセージ３ */
     rsouhuannaimsg4 ,         /* （帳票用）送付案内メッセージ４ */
     rsouhuannaimsg5 ,         /* （帳票用）送付案内メッセージ５ */
     rsouhuannaimsg6 ,         /* （帳票用）送付案内メッセージ６ */
     rsouhuannaimsg7 ,         /* （帳票用）送付案内メッセージ７ */
     rsouhuannaimsg8 ,         /* （帳票用）送付案内メッセージ８ */
     rsouhuannaimsg9 ,         /* （帳票用）送付案内メッセージ９ */
     rsouhuannaimsg10 ,         /* （帳票用）送付案内メッセージ１０ */
     rannainaiyoumsg1 ,         /* （帳票用）案内内容メッセージ１ */
     rannainaiyoumsg2 ,         /* （帳票用）案内内容メッセージ２ */
     rannainaiyoumsg3 ,         /* （帳票用）案内内容メッセージ３ */
     rannainaiyoumsg4 ,         /* （帳票用）案内内容メッセージ４ */
     rannainaiyoumsg5 ,         /* （帳票用）案内内容メッセージ５ */
     rannainaiyoumsg6 ,         /* （帳票用）案内内容メッセージ６ */
     rannainaiyoumsg7 ,         /* （帳票用）案内内容メッセージ７ */
     rannainaiyoumsg8 ,         /* （帳票用）案内内容メッセージ８ */
     rannainaiyoumsg9 ,         /* （帳票用）案内内容メッセージ９ */
     rannainaiyoumsg10 ,         /* （帳票用）案内内容メッセージ１０ */
     rannainaiyoumsg11 ,         /* （帳票用）案内内容メッセージ１１ */
     rannainaiyoumsg12 ,         /* （帳票用）案内内容メッセージ１２ */
     rannainaiyoumsg13 ,         /* （帳票用）案内内容メッセージ１３ */
     rannainaiyoumsg14 ,         /* （帳票用）案内内容メッセージ１４ */
     rannainaiyoumsg15 ,         /* （帳票用）案内内容メッセージ１５ */
     rannainaiyoumsg16 ,         /* （帳票用）案内内容メッセージ１６ */
     rannainaiyoumsg17 ,         /* （帳票用）案内内容メッセージ１７ */
     rannainaiyoumsg18 ,         /* （帳票用）案内内容メッセージ１８ */
     rannainaiyoumsg19 ,         /* （帳票用）案内内容メッセージ１９ */
     rannainaiyoumsg20 ,         /* （帳票用）案内内容メッセージ２０ */
     rannainaiyoumsg21 ,         /* （帳票用）案内内容メッセージ２１ */
     rannainaiyoumsg22 ,         /* （帳票用）案内内容メッセージ２２ */
     rannainaiyoumsg23 ,         /* （帳票用）案内内容メッセージ２３ */
     rannainaiyoumsg24 ,         /* （帳票用）案内内容メッセージ２４ */
     rannainaiyoumsg25 ,         /* （帳票用）案内内容メッセージ２５ */
     rannainaiyoumsg26 ,         /* （帳票用）案内内容メッセージ２６ */
     rannainaiyoumsg27 ,         /* （帳票用）案内内容メッセージ２７ */
     rannainaiyoumsg28 ,         /* （帳票用）案内内容メッセージ２８ */
     rannainaiyoumsg29 ,         /* （帳票用）案内内容メッセージ２９ */
     rannainaiyoumsg30 ,         /* （帳票用）案内内容メッセージ３０ */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IM_KhTyouhyoumsg_Z;