CREATE VIEW IT_SougouTuuti AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     tyouhyouymd ,         /* 帳票作成日 */
     tyouhyouprtymd ,         /* 帳票作成日（印刷用） */
     kykymd ,         /* 契約日 */
     sknnkaisiymd ,         /* 責任開始日 */
     syouhnnmsyouken ,         /* 商品名（証券用） */
     kyknmkj ,         /* 契約者名（漢字） */
     kyknmkjkhukakbn ,         /* 契約者名漢字化不可区分 */
     hhknnmkj ,         /* 被保険者名（漢字） */
     hhknnmkjkhukakbn ,         /* 被保険者名漢字化不可区分 */
     hhknseiymd ,         /* 被保険者生年月日 */
     hhknsei ,         /* 被保険者性別 */
     hhknnen ,         /* 被保険者年齢 */
     sbhenkanuktnmkj ,         /* 死亡返還金受取人氏名（漢字） */
     sibouhenkankinuktseiymd ,         /* 死亡返還金受取人生年月日 */
     stdrsknmkj ,         /* 指定代理請求人名（漢字） */
     stdrskseiymd ,         /* 指定代理請求人生年月日 */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     hrkkaisuu ,         /* 払込回数 */
     hrkkeiro ,         /* 払込経路 */
     syutkkbn1 ,         /* 主契約特約区分_1 */
     syutkkbn2 ,         /* 主契約特約区分_2 */
     syutkkbn3 ,         /* 主契約特約区分_3 */
     syutkkbn4 ,         /* 主契約特約区分_4 */
     syutkkbn5 ,         /* 主契約特約区分_5 */
     syutkkbn6 ,         /* 主契約特約区分_6 */
     syutkkbn7 ,         /* 主契約特約区分_7 */
     syutkkbn8 ,         /* 主契約特約区分_8 */
     syutkkbn9 ,         /* 主契約特約区分_9 */
     syutkkbn10 ,         /* 主契約特約区分_10 */
     syouhncd1 ,         /* 商品コード_1 */
     syouhncd2 ,         /* 商品コード_2 */
     syouhncd3 ,         /* 商品コード_3 */
     syouhncd4 ,         /* 商品コード_4 */
     syouhncd5 ,         /* 商品コード_5 */
     syouhncd6 ,         /* 商品コード_6 */
     syouhncd7 ,         /* 商品コード_7 */
     syouhncd8 ,         /* 商品コード_8 */
     syouhncd9 ,         /* 商品コード_9 */
     syouhncd10 ,         /* 商品コード_10 */
     syouhnsdno1 ,         /* 商品世代番号_1 */
     syouhnsdno2 ,         /* 商品世代番号_2 */
     syouhnsdno3 ,         /* 商品世代番号_3 */
     syouhnsdno4 ,         /* 商品世代番号_4 */
     syouhnsdno5 ,         /* 商品世代番号_5 */
     syouhnsdno6 ,         /* 商品世代番号_6 */
     syouhnsdno7 ,         /* 商品世代番号_7 */
     syouhnsdno8 ,         /* 商品世代番号_8 */
     syouhnsdno9 ,         /* 商品世代番号_9 */
     syouhnsdno10 ,         /* 商品世代番号_10 */
     kyksyouhnrenno1 ,         /* 契約商品連番_1 */
     kyksyouhnrenno2 ,         /* 契約商品連番_2 */
     kyksyouhnrenno3 ,         /* 契約商品連番_3 */
     kyksyouhnrenno4 ,         /* 契約商品連番_4 */
     kyksyouhnrenno5 ,         /* 契約商品連番_5 */
     kyksyouhnrenno6 ,         /* 契約商品連番_6 */
     kyksyouhnrenno7 ,         /* 契約商品連番_7 */
     kyksyouhnrenno8 ,         /* 契約商品連番_8 */
     kyksyouhnrenno9 ,         /* 契約商品連番_9 */
     kyksyouhnrenno10 ,         /* 契約商品連番_10 */
     kyhgndkatakbn1 ,         /* 給付限度型区分_1 */
     kyhgndkatakbn2 ,         /* 給付限度型区分_2 */
     kyhgndkatakbn3 ,         /* 給付限度型区分_3 */
     kyhgndkatakbn4 ,         /* 給付限度型区分_4 */
     kyhgndkatakbn5 ,         /* 給付限度型区分_5 */
     kyhgndkatakbn6 ,         /* 給付限度型区分_6 */
     kyhgndkatakbn7 ,         /* 給付限度型区分_7 */
     kyhgndkatakbn8 ,         /* 給付限度型区分_8 */
     kyhgndkatakbn9 ,         /* 給付限度型区分_9 */
     kyhgndkatakbn10 ,         /* 給付限度型区分_10 */
     hknkknsmnkbn1 ,         /* 保険期間歳満期区分_1 */
     hknkknsmnkbn2 ,         /* 保険期間歳満期区分_2 */
     hknkknsmnkbn3 ,         /* 保険期間歳満期区分_3 */
     hknkknsmnkbn4 ,         /* 保険期間歳満期区分_4 */
     hknkknsmnkbn5 ,         /* 保険期間歳満期区分_5 */
     hknkknsmnkbn6 ,         /* 保険期間歳満期区分_6 */
     hknkknsmnkbn7 ,         /* 保険期間歳満期区分_7 */
     hknkknsmnkbn8 ,         /* 保険期間歳満期区分_8 */
     hknkknsmnkbn9 ,         /* 保険期間歳満期区分_9 */
     hknkknsmnkbn10 ,         /* 保険期間歳満期区分_10 */
     hknkkn1 ,         /* 保険期間_1 */
     hknkkn2 ,         /* 保険期間_2 */
     hknkkn3 ,         /* 保険期間_3 */
     hknkkn4 ,         /* 保険期間_4 */
     hknkkn5 ,         /* 保険期間_5 */
     hknkkn6 ,         /* 保険期間_6 */
     hknkkn7 ,         /* 保険期間_7 */
     hknkkn8 ,         /* 保険期間_8 */
     hknkkn9 ,         /* 保険期間_9 */
     hknkkn10 ,         /* 保険期間_10 */
     hrkkknsmnkbn1 ,         /* 払込期間歳満期区分_1 */
     hrkkknsmnkbn2 ,         /* 払込期間歳満期区分_2 */
     hrkkknsmnkbn3 ,         /* 払込期間歳満期区分_3 */
     hrkkknsmnkbn4 ,         /* 払込期間歳満期区分_4 */
     hrkkknsmnkbn5 ,         /* 払込期間歳満期区分_5 */
     hrkkknsmnkbn6 ,         /* 払込期間歳満期区分_6 */
     hrkkknsmnkbn7 ,         /* 払込期間歳満期区分_7 */
     hrkkknsmnkbn8 ,         /* 払込期間歳満期区分_8 */
     hrkkknsmnkbn9 ,         /* 払込期間歳満期区分_9 */
     hrkkknsmnkbn10 ,         /* 払込期間歳満期区分_10 */
     hrkkkn1 ,         /* 払込期間_1 */
     hrkkkn2 ,         /* 払込期間_2 */
     hrkkkn3 ,         /* 払込期間_3 */
     hrkkkn4 ,         /* 払込期間_4 */
     hrkkkn5 ,         /* 払込期間_5 */
     hrkkkn6 ,         /* 払込期間_6 */
     hrkkkn7 ,         /* 払込期間_7 */
     hrkkkn8 ,         /* 払込期間_8 */
     hrkkkn9 ,         /* 払込期間_9 */
     hrkkkn10 ,         /* 払込期間_10 */
     syouhnnm1 ,         /* 商品名_1 */
     syouhnnm2 ,         /* 商品名_2 */
     syouhnnm3 ,         /* 商品名_3 */
     syouhnnm4 ,         /* 商品名_4 */
     syouhnnm5 ,         /* 商品名_5 */
     syouhnnm6 ,         /* 商品名_6 */
     syouhnnm7 ,         /* 商品名_7 */
     syouhnnm8 ,         /* 商品名_8 */
     syouhnnm9 ,         /* 商品名_9 */
     syouhnnm10 ,         /* 商品名_10 */
     kihons1 ,         /* 基本Ｓ_1 */
     kihons1$ ,         /* 基本Ｓ_1(通貨型) */
     kihons2 ,         /* 基本Ｓ_2 */
     kihons2$ ,         /* 基本Ｓ_2(通貨型) */
     kihons3 ,         /* 基本Ｓ_3 */
     kihons3$ ,         /* 基本Ｓ_3(通貨型) */
     kihons4 ,         /* 基本Ｓ_4 */
     kihons4$ ,         /* 基本Ｓ_4(通貨型) */
     kihons5 ,         /* 基本Ｓ_5 */
     kihons5$ ,         /* 基本Ｓ_5(通貨型) */
     kihons6 ,         /* 基本Ｓ_6 */
     kihons6$ ,         /* 基本Ｓ_6(通貨型) */
     kihons7 ,         /* 基本Ｓ_7 */
     kihons7$ ,         /* 基本Ｓ_7(通貨型) */
     kihons8 ,         /* 基本Ｓ_8 */
     kihons8$ ,         /* 基本Ｓ_8(通貨型) */
     kihons9 ,         /* 基本Ｓ_9 */
     kihons9$ ,         /* 基本Ｓ_9(通貨型) */
     kihons10 ,         /* 基本Ｓ_10 */
     kihons10$ ,         /* 基本Ｓ_10(通貨型) */
     p1 ,         /* 保険料_1 */
     p1$ ,         /* 保険料_1(通貨型) */
     p2 ,         /* 保険料_2 */
     p2$ ,         /* 保険料_2(通貨型) */
     p3 ,         /* 保険料_3 */
     p3$ ,         /* 保険料_3(通貨型) */
     p4 ,         /* 保険料_4 */
     p4$ ,         /* 保険料_4(通貨型) */
     p5 ,         /* 保険料_5 */
     p5$ ,         /* 保険料_5(通貨型) */
     p6 ,         /* 保険料_6 */
     p6$ ,         /* 保険料_6(通貨型) */
     p7 ,         /* 保険料_7 */
     p7$ ,         /* 保険料_7(通貨型) */
     p8 ,         /* 保険料_8 */
     p8$ ,         /* 保険料_8(通貨型) */
     p9 ,         /* 保険料_9 */
     p9$ ,         /* 保険料_9(通貨型) */
     p10 ,         /* 保険料_10 */
     p10$ ,         /* 保険料_10(通貨型) */
     kihonssyuruikbn1 ,         /* 基本Ｓ種類区分_1 */
     kihonssyuruikbn2 ,         /* 基本Ｓ種類区分_2 */
     kihonssyuruikbn3 ,         /* 基本Ｓ種類区分_3 */
     kihonssyuruikbn4 ,         /* 基本Ｓ種類区分_4 */
     kihonssyuruikbn5 ,         /* 基本Ｓ種類区分_5 */
     kihonssyuruikbn6 ,         /* 基本Ｓ種類区分_6 */
     kihonssyuruikbn7 ,         /* 基本Ｓ種類区分_7 */
     kihonssyuruikbn8 ,         /* 基本Ｓ種類区分_8 */
     kihonssyuruikbn9 ,         /* 基本Ｓ種類区分_9 */
     kihonssyuruikbn10 ,         /* 基本Ｓ種類区分_10 */
     syukyhkinkatakbn1 ,         /* 手術給付金型区分_1 */
     syukyhkinkatakbn2 ,         /* 手術給付金型区分_2 */
     syukyhkinkatakbn3 ,         /* 手術給付金型区分_3 */
     syukyhkinkatakbn4 ,         /* 手術給付金型区分_4 */
     syukyhkinkatakbn5 ,         /* 手術給付金型区分_5 */
     syukyhkinkatakbn6 ,         /* 手術給付金型区分_6 */
     syukyhkinkatakbn7 ,         /* 手術給付金型区分_7 */
     syukyhkinkatakbn8 ,         /* 手術給付金型区分_8 */
     syukyhkinkatakbn9 ,         /* 手術給付金型区分_9 */
     syukyhkinkatakbn10 ,         /* 手術給付金型区分_10 */
     rokudaissbtkkyhktkbn1 ,         /* ６大生活習慣病追加給付型区分_1 */
     rokudaissbtkkyhktkbn2 ,         /* ６大生活習慣病追加給付型区分_2 */
     rokudaissbtkkyhktkbn3 ,         /* ６大生活習慣病追加給付型区分_3 */
     rokudaissbtkkyhktkbn4 ,         /* ６大生活習慣病追加給付型区分_4 */
     rokudaissbtkkyhktkbn5 ,         /* ６大生活習慣病追加給付型区分_5 */
     rokudaissbtkkyhktkbn6 ,         /* ６大生活習慣病追加給付型区分_6 */
     rokudaissbtkkyhktkbn7 ,         /* ６大生活習慣病追加給付型区分_7 */
     rokudaissbtkkyhktkbn8 ,         /* ６大生活習慣病追加給付型区分_8 */
     rokudaissbtkkyhktkbn9 ,         /* ６大生活習慣病追加給付型区分_9 */
     rokudaissbtkkyhktkbn10 ,         /* ６大生活習慣病追加給付型区分_10 */
     khnkyhgk1 ,         /* 基本給付金額_1 */
     khnkyhgk1$ ,         /* 基本給付金額_1(通貨型) */
     khnkyhgk2 ,         /* 基本給付金額_2 */
     khnkyhgk2$ ,         /* 基本給付金額_2(通貨型) */
     khnkyhgk3 ,         /* 基本給付金額_3 */
     khnkyhgk3$ ,         /* 基本給付金額_3(通貨型) */
     khnkyhgk4 ,         /* 基本給付金額_4 */
     khnkyhgk4$ ,         /* 基本給付金額_4(通貨型) */
     khnkyhgk5 ,         /* 基本給付金額_5 */
     khnkyhgk5$ ,         /* 基本給付金額_5(通貨型) */
     khnkyhgk6 ,         /* 基本給付金額_6 */
     khnkyhgk6$ ,         /* 基本給付金額_6(通貨型) */
     khnkyhgk7 ,         /* 基本給付金額_7 */
     khnkyhgk7$ ,         /* 基本給付金額_7(通貨型) */
     khnkyhgk8 ,         /* 基本給付金額_8 */
     khnkyhgk8$ ,         /* 基本給付金額_8(通貨型) */
     khnkyhgk9 ,         /* 基本給付金額_9 */
     khnkyhgk9$ ,         /* 基本給付金額_9(通貨型) */
     khnkyhgk10 ,         /* 基本給付金額_10 */
     khnkyhgk10$ ,         /* 基本給付金額_10(通貨型) */
     tsinyno ,         /* 通信先郵便番号 */
     tsinadr1kj ,         /* 通信先住所１（漢字） */
     tsinadr2kj ,         /* 通信先住所２（漢字） */
     tsinadr3kj ,         /* 通信先住所３（漢字） */
     tsinadr4kj ,         /* 通信先住所４（漢字） */
     aitesyono ,         /* 相手証券番号 */
     drtencd ,         /* 代理店コード */
     drtennmkj ,         /* 代理店名（漢字） */
     rkaiyakuhrumukbn ,         /* （帳票用）解約返戻金有無区分 */
     rkaiyakuhr ,         /* （帳票用）解約返戻金 */
     rkaiyakuhr$ ,         /* （帳票用）解約返戻金(通貨型) */
     rsbhenkan ,         /* （帳票用）死亡返還金 */
     rsbhenkan$ ,         /* （帳票用）死亡返還金(通貨型) */
     rhtnpbuinm1 ,         /* （帳票用）不担保部位名１ */
     htnpkkn1 ,         /* 不担保期間１ */
     rhtnpbuinm2 ,         /* （帳票用）不担保部位名２ */
     htnpkkn2 ,         /* 不担保期間２ */
     rhtnpbuinm3 ,         /* （帳票用）不担保部位名３ */
     htnpkkn3 ,         /* 不担保期間３ */
     rhtnpbuinm4 ,         /* （帳票用）不担保部位名４ */
     htnpkkn4 ,         /* 不担保期間４ */
     tokkoudosghtnpkbn ,         /* 特定高度障害不担保区分 */
     rtratkicd ,         /* （帳票用）取扱コード */
     rtyouhyoucd ,         /* （帳票用）帳票コード */
     tyhyrenrakusikibetukbn ,         /* 帳票連絡先識別区分 */
     gansknnkaisiymd ,         /* がん責任開始日 */
     gannyukyhntgk ,         /* がん入院給付日額 */
     gannyukyhntgk$ ,         /* がん入院給付日額(通貨型) */
     katakbn1 ,         /* 型区分_1 */
     katakbn2 ,         /* 型区分_2 */
     katakbn3 ,         /* 型区分_3 */
     katakbn4 ,         /* 型区分_4 */
     katakbn5 ,         /* 型区分_5 */
     katakbn6 ,         /* 型区分_6 */
     katakbn7 ,         /* 型区分_7 */
     katakbn8 ,         /* 型区分_8 */
     katakbn9 ,         /* 型区分_9 */
     katakbn10 ,         /* 型区分_10 */
     sbhkuktnmkj1 ,         /* 死亡保険金受取人氏名（漢字）_1 */
     sbhkuktnmkj2 ,         /* 死亡保険金受取人氏名（漢字）_2 */
     sbhkuktnmkj3 ,         /* 死亡保険金受取人氏名（漢字）_3 */
     sbhkuktnmkj4 ,         /* 死亡保険金受取人氏名（漢字）_4 */
     sbhkuktnmkj5 ,         /* 死亡保険金受取人氏名（漢字）_5 */
     sbhkuktseiymd1 ,         /* 死亡保険金受取人生年月日_1 */
     sbhkuktseiymd2 ,         /* 死亡保険金受取人生年月日_2 */
     sbhkuktseiymd3 ,         /* 死亡保険金受取人生年月日_3 */
     sbhkuktseiymd4 ,         /* 死亡保険金受取人生年月日_4 */
     sbhkuktseiymd5 ,         /* 死亡保険金受取人生年月日_5 */
     sbhkkukttyoukanin ,         /* 死亡保険金受取人超過人数 */
     sbhktyoukaninbunwari ,         /* 死亡保険金超過人数分割割合 */
     bnwari1 ,         /* 分割割合_1 */
     bnwari2 ,         /* 分割割合_2 */
     bnwari3 ,         /* 分割割合_3 */
     bnwari4 ,         /* 分割割合_4 */
     bnwari5 ,         /* 分割割合_5 */
     pmnjtkkbn ,         /* 保険料免除特約区分 */
     mosukeymd ,         /* 申込書受付日 */
     sknnkaisikitkkbn ,         /* 責任開始期特約区分 */
     koujyosyoumeirecnum ,         /* 控除証明書レコード数 */
     hksknnkaisiymd ,         /* 復活責任開始日 */
     hkgansknnkaisiymd ,         /* 復活がん責任開始日 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_SougouTuuti_Z;