CREATE VIEW ZT_BosyuuDrtenHoyuuKykTy AS SELECT
     ztydatasyurui ,         /* （中継用）データ種類 */
     ztyhknsyumoku ,         /* （中継用）保険種目 */
     ztytyoubokbn ,         /* （中継用）帳簿区分 */
     ztysyonosyuban ,         /* （中継用）証券番号主番 */
     ztyhknsyurui2keta ,         /* （中継用）保険種類（２桁） */
     ztyhrkhuhukbn ,         /* （中継用）払込方法区分 */
     ztysyukinkbn ,         /* （中継用）集金区分 */
     ztybnkaisuu ,         /* （中継用）分割回数 */
     ztykyouhocd ,         /* （中継用）共保コード */
     ztydaibuncd ,         /* （中継用）代分コード */
     ztydaibunkanjishare ,         /* （中継用）代分幹事分シェア */
     ztydntcd7keta ,         /* （中継用）団体コード（７桁） */
     ztysyumokugrpkbn ,         /* （中継用）種目グループ区分 */
     ztygoukeipbsdirtnhykyk ,         /* （中継用）合計保険料（募集代理店保有契約） */
     ztyyno7keta ,         /* （中継用）郵便番号（７桁） */
     ztysikiymd ,         /* （中継用）始期年月日 */
     ztymankiymd ,         /* （中継用）満期年月日 */
     ztyidokaiyakuymd ,         /* （中継用）異動解約年月日 */
     ztymusymd ,         /* （中継用）申込年月日 */
     ztyjikokykhyj ,         /* （中継用）自己契約表示 */
     ztymeisaioyakokbn ,         /* （中継用）明細親子区分 */
     ztykihontikucdkami3 ,         /* （中継用）基本地区コード上３桁 */
     ztyyobiv2 ,         /* （中継用）予備項目Ｖ２ */
     ztytelnobsdirtnhykyk ,         /* （中継用）電話番号（募集代理店保有契約） */
     ztykyknmknbsdirtnhykyk ,         /* （中継用）契約者名（カナ）（募集代理店保有契約） */
     ztybnkyk1kaipbsdirtnhykyk ,         /* （中継用）分割払契約１回分保険料（募集代理店保有契約） */
     ztybnsyuruikbn ,         /* （中継用）分割種類区分 */
     ztyhrkymd ,         /* （中継用）払込日 */
     ztydntfsthrkym ,         /* （中継用）団体扱初回払込年月 */
     ztyfstpkzhurikbn ,         /* （中継用）初回保険料口座振替区分 */
     ztykeijyouym4keta ,         /* （中継用）計上年月（４桁） */
     ztyhknkaisyacd ,         /* （中継用）保険会社コード */
     ztyhhknnmknbsdirtnhykyk ,         /* （中継用）被保険者名（カナ）（募集代理店保有契約） */
     ztyknjhhknmei ,         /* （中継用）漢字被保険者名 */
     ztyhhknseiymd ,         /* （中継用）被保険者生年月日 */
     ztyhhknnenbsdirtnhykyk ,         /* （中継用）被保険者年令（募集代理店保有契約） */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhhkntdk ,         /* （中継用）被保険者続柄 */
     ztyhhknynobsdirtnhykyk ,         /* （中継用）被保険者郵便番号（募集代理店保有契約） */
     ztyhhknadrkj50 ,         /* （中継用）被保険者漢字住所５０ */
     ztyhrkkeiro ,         /* （中継用）払込経路 */
     ztyitijibrpbsdirtnhykyk ,         /* （中継用）一時払保険料（募集代理店保有契約） */
     ztynkshrkknkbn ,         /* （中継用）年金支払期間区分 */
     ztynkshrkknnen ,         /* （中継用）年金支払期間年 */
     ztynkshrstartymd ,         /* （中継用）年金支払開始年月日 */
     ztytokutaiumu ,         /* （中継用）特体有無 */
     ztytktyuutohuka ,         /* （中継用）特約中途付加 */
     ztytksuu ,         /* （中継用）特約数 */
     ztysinsakbn ,         /* （中継用）診査区分 */
     ztyzeiseitekikaku ,         /* （中継用）税制適格 */
     ztylivingneeds ,         /* （中継用）リビングニーズ */
     ztyknjsyuhsynm ,         /* （中継用）漢字主契約保種名 */
     ztysyusbsdirtnhykyk ,         /* （中継用）主契約保険金額（募集代理店保有契約） */
     ztysyuhknkknkbn ,         /* （中継用）主契約保険期間区分 */
     ztysyuhknkkn ,         /* （中継用）主契約保険期間 */
     ztysyuhrkkknkbn ,         /* （中継用）主契約払込期間区分 */
     ztysyuhrkkkn ,         /* （中継用）主契約払込期間 */
     ztykjtkhosyunm1 ,         /* （中継用）漢字特約保種名１ */
     ztytks1bsdirtnhykyk ,         /* （中継用）特約保険金額１（募集代理店保有契約） */
     ztytkhknkknkbn1 ,         /* （中継用）特約保険期間区分１ */
     ztytkhknkkn1 ,         /* （中継用）特約保険期間１ */
     ztytkhrkkknkbn1 ,         /* （中継用）特約払込期間区分１ */
     ztytkhrkkkn1 ,         /* （中継用）特約払込期間１ */
     ztykjtkhosyunm2 ,         /* （中継用）漢字特約保種名２ */
     ztytks2bsdirtnhykyk ,         /* （中継用）特約保険金額２（募集代理店保有契約） */
     ztytkhknkknkbn2 ,         /* （中継用）特約保険期間区分２ */
     ztytkhknkkn2 ,         /* （中継用）特約保険期間２ */
     ztytkhrkkknkbn2 ,         /* （中継用）特約払込期間区分２ */
     ztytkhrkkkn2 ,         /* （中継用）特約払込期間２ */
     ztykjtkhosyunm3 ,         /* （中継用）漢字特約保種名３ */
     ztytks3bsdirtnhykyk ,         /* （中継用）特約保険金額３（募集代理店保有契約） */
     ztytkhknkknkbn3 ,         /* （中継用）特約保険期間区分３ */
     ztytkhknkkn3 ,         /* （中継用）特約保険期間３ */
     ztytkhrkkknkbn3 ,         /* （中継用）特約払込期間区分３ */
     ztytkhrkkkn3 ,         /* （中継用）特約払込期間３ */
     ztykjtkhosyunm4 ,         /* （中継用）漢字特約保種名４ */
     ztytks4bsdirtnhykyk ,         /* （中継用）特約保険金額４（募集代理店保有契約） */
     ztytkhknkknkbn4 ,         /* （中継用）特約保険期間区分４ */
     ztytkhknkkn4 ,         /* （中継用）特約保険期間４ */
     ztytkhrkkknkbn4 ,         /* （中継用）特約払込期間区分４ */
     ztytkhrkkkn4 ,         /* （中継用）特約払込期間４ */
     ztykjtkhosyunm5 ,         /* （中継用）漢字特約保種名５ */
     ztytks5bsdirtnhykyk ,         /* （中継用）特約保険金額５（募集代理店保有契約） */
     ztytkhknkknkbn5 ,         /* （中継用）特約保険期間区分５ */
     ztytkhknkkn5 ,         /* （中継用）特約保険期間５ */
     ztytkhrkkknkbn5 ,         /* （中継用）特約払込期間区分５ */
     ztytkhrkkkn5 ,         /* （中継用）特約払込期間５ */
     ztykjtkhosyunm6 ,         /* （中継用）漢字特約保種名６ */
     ztytks6bsdirtnhykyk ,         /* （中継用）特約保険金額６（募集代理店保有契約） */
     ztytkhknkknkbn6 ,         /* （中継用）特約保険期間区分６ */
     ztytkhknkkn6 ,         /* （中継用）特約保険期間６ */
     ztytkhrkkknkbn6 ,         /* （中継用）特約払込期間区分６ */
     ztytkhrkkkn6 ,         /* （中継用）特約払込期間６ */
     ztydatasyubetucd ,         /* （中継用）データ種別コード */
     ztyhjnkojinkbn ,         /* （中継用）法人個人区分 */
     ztykykadrkj50 ,         /* （中継用）契約者漢字住所５０ */
     ztykyknmkjbsdirtnhykyk ,         /* （中継用）契約者名(漢字）（募集代理店保有契約） */
     ztykyksyaseiymd ,         /* （中継用）契約者生年月日 */
     ztysakuseiym ,         /* （中継用）作成年月 */
     ztydairitencd ,         /* （中継用）代理店コード */
     ztydairitenkanrisskcd ,         /* （中継用）代理店管理組織コード */
     ztybosyuunincd ,         /* （中継用）募集人コード */
     ztybosyuunm ,         /* （中継用）募集人氏名 */
     ztybosyuujtkbn ,         /* （中継用）募集人状態区分 */
     ztydairitenkbtinfo1 ,         /* （中継用）代理店個別情報１ */
     ztydairitenkbtinfo2 ,         /* （中継用）代理店個別情報２ */
     ztydairitenkbtinfo3 ,         /* （中継用）代理店個別情報３ */
     ztysyouhinbunruikbn ,         /* （中継用）商品分類区分 */
     ztyhknnmcd ,         /* （中継用）保険名称コード */
     ztykykjyutikbn ,         /* （中継用）契約状態区分 */
     ztytkbthsyukiknmanryouym ,         /* （中継用）特別保障期間満了年月 */
     ztyldownym ,         /* （中継用）Ｌダウン年月 */
     ztyhrkmanryouym ,         /* （中継用）払込満了年月 */
     ztymrtiksnym ,         /* （中継用）マル定更新年月 */
     ztyhaneikykhyj ,         /* （中継用）繁栄契約表示 */
     ztyzenzeikyohyj ,         /* （中継用）全税共表示 */
     ztysikijikbn ,         /* （中継用）職事区分 */
     ztysbuktdisphukusuhyj ,         /* （中継用）死亡受取人複数表示 */
     ztysbuktnmbsdirtnhykyk ,         /* （中継用）死亡受取人名（募集代理店保有契約） */
     ztymnkuktdisphukusuhyj ,         /* （中継用）満期受取人複数表示 */
     ztymnkuktnmbsdirtnhykyk ,         /* （中継用）満期受取人名（募集代理店保有契約） */
     ztytodouhukencd ,         /* （中継用）都道府県コード */
     ztybankcd ,         /* （中継用）銀行番号 */
     ztyshitencd ,         /* （中継用）支店番号 */
     ztyyokinkbn ,         /* （中継用）預金種目区分 */
     ztykouzano7keta ,         /* （中継用）口座番号（７桁） */
     ztyalcardkbn ,         /* （中継用）ＡＬカード区分 */
     ztysibous ,         /* （中継用）死亡Ｓ */
     ztysgsbs ,         /* （中継用）災害死亡S */
     ztysgwrmstksbsdirtnhykyk ,         /* （中継用）災害割増特約Ｓ（募集代理店保有契約） */
     ztysyougaitkkatakbn ,         /* （中継用）傷害特約型区分 */
     ztysyougaitksbsdirtnhykyk ,         /* （中継用）傷害特約Ｓ（募集代理店保有契約） */
     ztyreguardtksbsdirtnhykyk ,         /* （中継用）リガード特約Ｓ（募集代理店保有契約） */
     ztyreguardtkkbn ,         /* （中継用）リガード特約区分 */
     ztyvreguardtksbsdirtnhykyk ,         /* （中継用）Ｖガード特約Ｓ（募集代理店保有契約） */
     ztykzkmrthgukatakbn ,         /* （中継用）家族マル定配偶者型区分 */
     ztykzkmrthgusbsdirtnhykyk ,         /* （中継用）家族マル定配偶者Ｓ（募集代理店保有契約） */
     ztykzkmrtkosbsdirtnhykyk ,         /* （中継用）家族マル定子Ｓ（募集代理店保有契約） */
     ztykaneeztkarihyj ,         /* （中継用）ケアニーズ特約有表示 */
     ztydrtenkinyuucd ,         /* （中継用）代理店金融機関コード */
     ztydrtensitencd ,         /* （中継用）代理店支店コード */
     ztystjmkbn ,         /* （中継用）集中事務組織区分 */
     ztysyokaiphrkkeiro ,         /* （中継用）初回Ｐ払込経路区分 */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztykanjidairitennm ,         /* （中継用）漢字代理店名 */
     ztytsrybnwari ,         /* （中継用）手数料分割割合 */
     ztydrtenkeijyouym ,         /* （中継用）代理店計上年月 */
     ztykydatkidairitencd ,         /* （中継用）共同扱代理店コード */
     ztymdhnsyouhntsryshrkbn ,         /* （中継用）窓販商品手数料支払区分 */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztymdhnaisyoumeicd ,         /* （中継用）窓販用愛称名コード */
     ztysyokaipryosyuymd ,         /* （中継用）初回Ｐ領収年月日 */
     ztysykgycd ,         /* （中継用）職業コード */
     ztykaiyakuhrmkhritu ,         /* （中継用）解約返戻金目標率 */
     ztytoutatukaiyakuhrmkhritu ,         /* （中継用）到達解約返戻金目標率（募集代理店保有契約） */
     ztykaiyakuhrmkhtoutatuymd ,         /* （中継用）解約返戻金目標到達年月日 */
     ztyanniskcd ,         /* （中継用）案内先コード */
     ztyhjnkykhyj ,         /* （中継用）法人契約表示 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztylivguardtkyks ,         /* （中継用）ＬｉＶガード特約Ｓ */
     ztysiteituukaitijibrp ,         /* （中継用）指定通貨建一時払保険料 */
     ztysiteituukasyus ,         /* （中継用）指定通貨建主契約保険金額 */
     ztysiteituukasbs ,         /* （中継用）指定通貨建死亡保険金額 */
     ztysiteituukasaigaisbs ,         /* （中継用）指定通貨建災害死亡保険金額 */
     ztysiteituukacd ,         /* （中継用）指定通貨コード */
     ztyhrktuukaitijibrp ,         /* （中継用）払込通貨建一時払保険料 */
     ztyhrktuukacd ,         /* （中継用）払込通貨コード */
     ztytumitateriritu ,         /* （中継用）積立利率 */
     ztytmttknzoukaritujygn ,         /* （中継用）積立金増加率上限 */
     ztysetteibairitu ,         /* （中継用）設定倍率 */
     ztytumitatekngk ,         /* （中継用）積立金額 */
     ztykjsbuktnm30 ,         /* （中継用）漢字死亡受取人名３０ */
     ztymnkuktnm30 ,         /* （中継用）漢字満期受取人名３０ */
     ztykjkykdairinm ,         /* （中継用）漢字契約者代理人名 */
     ztykjsiteidairinm30 ,         /* （中継用）漢字指定代理人名３０ */
     ztytrkkzknmkj1 ,         /* （中継用）登録家族名（漢字）１ */
     ztytrkkzknmkj2 ,         /* （中継用）登録家族名（漢字）２ */
     ztyikkatubaraikbn ,         /* （中継用）一括払区分 */
     ztyikkatubaraikaisuu ,         /* （中継用）一括払回数 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztyrendouritu ,         /* （中継用）連動率 */
     ztyteikishrritu ,         /* （中継用）定期支払率 */
     ztytikskzuktnmkj ,         /* （中継用）定期支払金受取人名（漢字） */
     ztytikskzbankcd ,         /* （中継用）定期支払金受取口座銀行コード */
     ztytikskzsitencd ,         /* （中継用）定期支払金受取口座支店コード */
     ztytikskzyokinkbn ,         /* （中継用）定期支払金受取口座預金種目区分 */
     ztytikskzkouzano ,         /* （中継用）定期支払金受取口座番号 */
     ztytikskzkzmeiginmkn ,         /* （中継用）定期支払金受取口座名義人氏名（カナ） */
     ztyteikishrkinshrtuukasyu ,         /* （中継用）定期支払金支払通貨 */
     ztyyobiv58 ,         /* （中継用）予備項目Ｖ５８ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_BosyuuDrtenHoyuuKykTy_Z;