CREATE VIEW ZT_RisaTjHitNminusZeroRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnyuukourecordlength ,         /* （連携用）有効レコード長 */
     zrnrdwarea ,         /* （連携用）ＲＤＷ領域 */
     zrndatakanrino ,         /* （連携用）データ管理番号 */
     zrnerrkbnv1 ,         /* （連携用）エラー区分Ｖ１ */
     zrnratekbn ,         /* （連携用）レート区分 */
     zrnsuurisyuruicd ,         /* （連携用）数理種類コード */
     zrnyobiv2 ,         /* （連携用）予備項目Ｖ２ */
     zrnkbnkeiriyousegmentkbn ,         /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn ,         /* （連携用）区分経理用利源分析区分 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnhokensyuruikigouyobi1x1 ,         /* （連携用）保険種類記号予備１＿１ */
     zrnhokensyuruikigouyobi1x2 ,         /* （連携用）保険種類記号予備１＿２ */
     zrnhokensyuruikigouyobi1x3 ,         /* （連携用）保険種類記号予備１＿３ */
     zrnhokensyuruikigouyobi1x4 ,         /* （連携用）保険種類記号予備１＿４ */
     zrnhokensyuruikigouyobi1x5 ,         /* （連携用）保険種類記号予備１＿５ */
     zrnhokensyuruikigouyobi1x6 ,         /* （連携用）保険種類記号予備１＿６ */
     zrnhokensyuruikigouyobi1x7 ,         /* （連携用）保険種類記号予備１＿７ */
     zrnhokensyuruikigouyobi1x8 ,         /* （連携用）保険種類記号予備１＿８ */
     zrnhokensyuruikigouyobi1x9 ,         /* （連携用）保険種類記号予備１＿９ */
     zrnhokensyuruikigouyobi1x10 ,         /* （連携用）保険種類記号予備１＿１０ */
     zrnhokensyuruikigouyobi1x11 ,         /* （連携用）保険種類記号予備１＿１１ */
     zrnhokensyuruikigouyobi1x12 ,         /* （連携用）保険種類記号予備１＿１２ */
     zrnhokensyuruikigouyobi1x13 ,         /* （連携用）保険種類記号予備１＿１３ */
     zrnhokensyuruikigouyobi1x14 ,         /* （連携用）保険種類記号予備１＿１４ */
     zrnhokensyuruikigouyobi1x15 ,         /* （連携用）保険種類記号予備１＿１５ */
     zrnhokensyuruikigouyobi2x1 ,         /* （連携用）保険種類記号予備２＿１ */
     zrnhokensyuruikigouyobi2x2 ,         /* （連携用）保険種類記号予備２＿２ */
     zrnhokensyuruikigouyobi2x3 ,         /* （連携用）保険種類記号予備２＿３ */
     zrnhokensyuruikigouyobi2x4 ,         /* （連携用）保険種類記号予備２＿４ */
     zrnhokensyuruikigouyobi2x5 ,         /* （連携用）保険種類記号予備２＿５ */
     zrnhokensyuruikigouyobi2x6 ,         /* （連携用）保険種類記号予備２＿６ */
     zrnhokensyuruikigouyobi2x7 ,         /* （連携用）保険種類記号予備２＿７ */
     zrnhokensyuruikigouyobi2x8 ,         /* （連携用）保険種類記号予備２＿８ */
     zrnhokensyuruikigouyobi2x9 ,         /* （連携用）保険種類記号予備２＿９ */
     zrnhokensyuruikigouyobi2x10 ,         /* （連携用）保険種類記号予備２＿１０ */
     zrnhokensyuruikigouyobi3x1 ,         /* （連携用）保険種類記号予備３＿１ */
     zrnhokensyuruikigouyobi3x2 ,         /* （連携用）保険種類記号予備３＿２ */
     zrnhokensyuruikigouyobi3x3 ,         /* （連携用）保険種類記号予備３＿３ */
     zrnhokensyuruikigouyobi3x4 ,         /* （連携用）保険種類記号予備３＿４ */
     zrnhokensyuruikigouyobi3x5 ,         /* （連携用）保険種類記号予備３＿５ */
     zrnhokensyuruikigouyobi3x6 ,         /* （連携用）保険種類記号予備３＿６ */
     zrnhokensyuruikigouyobi3x7 ,         /* （連携用）保険種類記号予備３＿７ */
     zrnhokensyuruikigouyobi3x8 ,         /* （連携用）保険種類記号予備３＿８ */
     zrnhokensyuruikigouyobi3x9 ,         /* （連携用）保険種類記号予備３＿９ */
     zrnhokensyuruikigouyobi3x10 ,         /* （連携用）保険種類記号予備３＿１０ */
     zrnharaikatakbn ,         /* （連携用）払方区分 */
     zrnkeiyakunendo ,         /* （連携用）契約年度 */
     zrnkeiyakum ,         /* （連携用）契約月 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrn5nenmeoutoubikbn ,         /* （連携用）５年目応当日区分 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnkeiyakuoutoubikbn ,         /* （連携用）契約応当日区分 */
     zrnsuuriyouyobin1 ,         /* （連携用）数理用予備項目Ｎ１ */
     zrnsuuriyouyobin11 ,         /* （連携用）数理用予備項目Ｎ１１ */
     zrnsaisitutokuyakuhukasuu ,         /* （連携用）災疾特約付加数 */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnsibous ,         /* （連携用）死亡Ｓ */
     zrntounendmtwrhrgkruikeigk ,         /* （連携用）当年度末割振額累計額 */
     zrnwarihurigakurisoku1 ,         /* （連携用）割振額利息１ */
     zrnwarihurigakurisoku2 ,         /* （連携用）割振額利息２ */
     zrnyokunendosyoyougakuyou ,         /* （連携用）翌年度所要額用 */
     zrnyokuyokunendosyoyougkyou ,         /* （連携用）翌々年度所要額用 */
     zrnyuukoutyuusyoyougaku ,         /* （連携用）有効中所要額 */
     zrnsyoumetuyousyoyougaku1 ,         /* （連携用）消滅用所要額１ */
     zrnsyoumetuyousyoyougaku2 ,         /* （連携用）消滅用所要額２ */
     zrntenkanyousyoyougaku1 ,         /* （連携用）転換用所要額１ */
     zrntenkanyousyoyougaku2 ,         /* （連携用）転換用所要額２ */
     zrntnknyutuujyoudsyoyougk1 ,         /* （連携用）転換用通常Ｄ所要額１ */
     zrntnknyutuujyoudsyoyougk2 ,         /* （連携用）転換用通常Ｄ所要額２ */
     zrntnknyuhrkbbnksyoyougk1 ,         /* （連携用）転換用払込部分Ｋ所要額１ */
     zrntnknyuhrkbbnksyoyougk2 ,         /* （連携用）転換用払込部分Ｋ所要額２ */
     zrntnknyuhrkbbnknnknsnp1 ,         /* （連携用）転換用払込部分Ｋ年換算Ｐ１ */
     zrntnknyuhrkbbnknnknsnp2 ,         /* （連携用）転換用払込部分Ｋ年換算Ｐ２ */
     zrntnknyutnknhktgksyoyougk1 ,         /* （連携用）転換用転換引継Ｋ所要額１ */
     zrntnknyutnknhktgksyoyougk2 ,         /* （連携用）転換用転換引継Ｋ所要額２ */
     zrntnknyutnknhktgknnknsnp1 ,         /* （連携用）転換用転換引継Ｋ年換算Ｐ１ */
     zrntnknyutnknhktgknnknsnp2 ,         /* （連携用）転換用転換引継Ｋ年換算Ｐ２ */
     zrntnknyusaisituksyoyougk1 ,         /* （連携用）転換用災疾Ｋ所要額１ */
     zrntnknyusaisituksyoyougk2 ,         /* （連携用）転換用災疾Ｋ所要額２ */
     zrntnknyusaisitukkyhntgk1 ,         /* （連携用）転換用災疾Ｋ給付日額１ */
     zrntnknyusaisitukkyhntgk2 ,         /* （連携用）転換用災疾Ｋ給付日額２ */
     zrnhrkbbnkdsyoyougk ,         /* （連携用）払込部分ＫＤ所要額 */
     zrnhrkbbnkdtisyunnknsnp ,         /* （連携用）払込部分ＫＤ対象年換算Ｐ */
     zrntusangohrkbbnkappad ,         /* （連携用）通算後払込部分カッパーＤ */
     zrntnknhktgkdsyoyougk ,         /* （連携用）転換引継ＫＤ所要額 */
     zrntnknhktgkdtisyunenknsnp ,         /* （連携用）転換引継ＫＤ対象年換算Ｐ */
     zrntusangotnknhktgkappad ,         /* （連携用）通算後転換引継カッパーＤ */
     zrntuusangohutuusiboukappad ,         /* （連携用）通算後普通死亡カッパーＤ */
     zrnsaisitukappadsyoyougaku ,         /* （連携用）災疾カッパーＤ所要額 */
     zrntuusangosaisitukappad ,         /* （連携用）通算後災疾カッパーＤ */
     zrnsistkappadtisyukyhntgk ,         /* （連携用）災疾カッパーＤ対象給付日額 */
     zrntuusangogoukeikappad ,         /* （連携用）通算後合計カッパーＤ */
     zrndtaisyouv ,         /* （連携用）Ｄ対象Ｖ */
     zrnyobin11 ,         /* （連携用）予備項目Ｎ１１ */
     zrndaihyouyoteiriritu ,         /* （連携用）代表予定利率 */
     zrnknkuzusnzyrt ,         /* （連携用）健康増進乗率 */
     zrnzyrthntiyustatuskbn ,         /* （連携用）乗率判定用ステータス区分 */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrntnknyusyusistksyoyougk1 ,         /* （連携用）転換用主契約災疾Ｋ所要額１ */
     zrntnknyusyusistksyoyougk2 ,         /* （連携用）転換用主契約災疾Ｋ所要額２ */
     zrntnknyusyusistkkyhntgk1 ,         /* （連携用）転換用主契約災疾Ｋ給付日額１ */
     zrntnknyusyusistkkyhntgk2 ,         /* （連携用）転換用主契約災疾Ｋ給付日額２ */
     zrnsyusistkappadsyoyougk ,         /* （連携用）主契約災疾カッパーＤ所要額 */
     zrnsyusistkdtisyukyhntgk ,         /* （連携用）主契約災疾ＫＤ対象給付日額 */
     zrnyobin11x8 ,         /* （連携用）予備項目Ｎ１１＿８ */
     zrnyobin11x9 ,         /* （連携用）予備項目Ｎ１１＿９ */
     zrnyobin11x10 ,         /* （連携用）予備項目Ｎ１１＿１０ */
     zrnyobin11x11 ,         /* （連携用）予備項目Ｎ１１＿１１ */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnkawaserate ,         /* （連携用）為替レート */
     zrnkawaseratetekiyouymd ,         /* （連携用）為替レート適用年月日 */
     zrnkeiyakujiyoteiriritu ,         /* （連携用）契約時予定利率 */
     zrnenkdtsbujsitihsyukngk ,         /* （連携用）円貨建死亡時最低保証金額 */
     zrntumitatekin ,         /* （連携用）積立金 */
     zrnkiharaikomip ,         /* （連携用）既払込Ｐ */
     zrngaikadatesyukeiyakup ,         /* （連携用）外貨建主契約Ｐ */
     zrnyobiv2x2 ,         /* （連携用）予備項目Ｖ２＿２ */
     zrnnksjitirttumitatekin ,         /* （連携用）年金開始時定率部分積立金 */
     zrnsisuurentumitatekin ,         /* （連携用）指数連動部分積立金 */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnyoteiririturironbase ,         /* （連携用）予定利率（理論ベース） */
     zrngkdtyknndsyoyougakuyou ,         /* （連携用）外貨建翌年度所要額用 */
     zrngkdtykyknndsyoyougakuyou ,         /* （連携用）外貨建翌々年度所要額用 */
     zrndkeisanjikwsrate ,         /* （連携用）Ｄ計算時為替レート */
     zrndkeisanjikwsratetkyymd ,         /* （連携用）Ｄ計算時為替レート適用年月日 */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrnyobiv6x2 ,         /* （連携用）予備項目Ｖ６＿２ */
     zrnyobiv6x3 ,         /* （連携用）予備項目Ｖ６＿３ */
     zrnyobiv7x2 ,         /* （連携用）予備項目Ｖ７＿２ */
     zrntokuyakukoumokuv120 ,         /* （連携用）特約項目Ｖ１２０ */
     zrntokuyakukoumokuv120x2 ,         /* （連携用）特約項目Ｖ１２０＿２ */
     zrntokuyakukoumokuv120x3 ,         /* （連携用）特約項目Ｖ１２０＿３ */
     zrntokuyakukoumokuv120x4 ,         /* （連携用）特約項目Ｖ１２０＿４ */
     zrntokuyakukoumokuv120x5 ,         /* （連携用）特約項目Ｖ１２０＿５ */
     zrntokuyakukoumokuv120x6 ,         /* （連携用）特約項目Ｖ１２０＿６ */
     zrntokuyakukoumokuv120x7 ,         /* （連携用）特約項目Ｖ１２０＿７ */
     zrntokuyakukoumokuv120x8 ,         /* （連携用）特約項目Ｖ１２０＿８ */
     zrntokuyakukoumokuv120x9 ,         /* （連携用）特約項目Ｖ１２０＿９ */
     zrntokuyakukoumokuv120x10 ,         /* （連携用）特約項目Ｖ１２０＿１０ */
     zrntokuyakukoumokuv120x11 ,         /* （連携用）特約項目Ｖ１２０＿１１ */
     zrntokuyakukoumokuv120x12 ,         /* （連携用）特約項目Ｖ１２０＿１２ */
     zrntokuyakukoumokuv120x13 ,         /* （連携用）特約項目Ｖ１２０＿１３ */
     zrntokuyakukoumokuv120x14 ,         /* （連携用）特約項目Ｖ１２０＿１４ */
     zrntokuyakukoumokuv120x15 ,         /* （連携用）特約項目Ｖ１２０＿１５ */
     zrntokuyakukoumokuv120x16 ,         /* （連携用）特約項目Ｖ１２０＿１６ */
     zrntokuyakukoumokuv120x17 ,         /* （連携用）特約項目Ｖ１２０＿１７ */
     zrntokuyakukoumokuv120x18 ,         /* （連携用）特約項目Ｖ１２０＿１８ */
     zrntokuyakukoumokuv120x19 ,         /* （連携用）特約項目Ｖ１２０＿１９ */
     zrntokuyakukoumokuv120x20 ,         /* （連携用）特約項目Ｖ１２０＿２０ */
     zrntokuyakukoumokuv120x21 ,         /* （連携用）特約項目Ｖ１２０＿２１ */
     zrntokuyakukoumokuv120x22 ,         /* （連携用）特約項目Ｖ１２０＿２２ */
     zrntokuyakukoumokuv120x23 ,         /* （連携用）特約項目Ｖ１２０＿２３ */
     zrntokuyakukoumokuv120x24 ,         /* （連携用）特約項目Ｖ１２０＿２４ */
     zrntokuyakukoumokuv120x25 ,         /* （連携用）特約項目Ｖ１２０＿２５ */
     zrntokuyakukoumokuv120x26 ,         /* （連携用）特約項目Ｖ１２０＿２６ */
     zrntokuyakukoumokuv120x27 ,         /* （連携用）特約項目Ｖ１２０＿２７ */
     zrntokuyakukoumokuv120x28 ,         /* （連携用）特約項目Ｖ１２０＿２８ */
     zrntokuyakukoumokuv120x29 ,         /* （連携用）特約項目Ｖ１２０＿２９ */
     zrntokuyakukoumokuv120x30 ,         /* （連携用）特約項目Ｖ１２０＿３０ */
     zrntokuyakukoumokuv120x31 ,         /* （連携用）特約項目Ｖ１２０＿３１ */
     zrntokuyakukoumokuv120x32 ,         /* （連携用）特約項目Ｖ１２０＿３２ */
     zrntokuyakukoumokuv120x33 ,         /* （連携用）特約項目Ｖ１２０＿３３ */
     zrntokuyakukoumokuv120x34 ,         /* （連携用）特約項目Ｖ１２０＿３４ */
     zrntokuyakukoumokuv120x35 ,         /* （連携用）特約項目Ｖ１２０＿３５ */
     zrntokuyakukoumokuv120x36 ,         /* （連携用）特約項目Ｖ１２０＿３６ */
     zrntokuyakukoumokuv120x37 ,         /* （連携用）特約項目Ｖ１２０＿３７ */
     zrntokuyakukoumokuv120x38 ,         /* （連携用）特約項目Ｖ１２０＿３８ */
     zrntokuyakukoumokuv120x39 ,         /* （連携用）特約項目Ｖ１２０＿３９ */
     zrntokuyakukoumokuv120x40           /* （連携用）特約項目Ｖ１２０＿４０ */
FROM ZT_RisaTjHitNminusZeroRn_Z;