CREATE VIEW ZT_KsnKbkSsuRnduHknJigyohiRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnyuukourecordlength ,         /* （連携用）有効レコード長 */
     zrnrdwarea ,         /* （連携用）ＲＤＷ領域 */
     zrnrecordkbn ,         /* （連携用）レコード区分 */
     zrnnenkinkaisigohyouji ,         /* （連携用）年金開始後表示 */
     zrnnksgokurikosidhyj ,         /* （連携用）年金開始後繰越Ｄ表示 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnidojiyukbn ,         /* （連携用）異動事由区分 */
     zrnzougenkbn ,         /* （連携用）増減区分 */
     zrnidourecordkbn ,         /* （連携用）異動レコード区分 */
     zrnkeijyouctrlkbn ,         /* （連携用）計上コントロール区分 */
     zrnhenkousyoriymd ,         /* （連携用）変更処理年月日 */
     zrnkykmfksnctr ,         /* （連携用）契約ＭＦ更新ＣＴＲ */
     zrnrecordctr ,         /* （連携用）レコードＣＴＲ */
     zrnsuuriyoukouryokukaisiymd ,         /* （連携用）数理用効力開始年月日 */
     zrndenymd ,         /* （連携用）伝票日付 */
     zrnbluekeizokuhyouji ,         /* （連携用）Ｂｌｕｅ継続表示 */
     zrnsuuriyouyobin1x2 ,         /* （連携用）数理用予備項目Ｎ１＿２ */
     zrntoukeikeijyoukbn ,         /* （連携用）統計計上区分 */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrnzenkiidouteiseikbn ,         /* （連携用）前期異動訂正区分 */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrntenkangokeiyakubosyuuym ,         /* （連携用）転換後契約募集年月 */
     zrnidoujiyuucd ,         /* （連携用）異動事由コード */
     zrnsyoricd ,         /* （連携用）処理コード */
     zrnsekininteiseihyouji ,         /* （連携用）責任訂正表示 */
     zrnsuuriyouyobin8 ,         /* （連携用）数理用予備項目Ｎ８ */
     zrnsihankibikinkbn ,         /* （連携用）四半期備金区分 */
     zrnsuuriyouyobin1x3 ,         /* （連携用）数理用予備項目Ｎ１＿３ */
     zrndatakanrino ,         /* （連携用）データ管理番号 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn ,         /* （連携用）外出Ｐ免区分 */
     zrnstdssytikbn ,         /* （連携用）外出集定区分 */
     zrnstdssnskbn ,         /* （連携用）外出診査区分 */
     zrnsotodasimanagehyouji ,         /* （連携用）外出満年令表示 */
     zrnsotodasiphkbnmnoshyouji ,         /* （連携用）外出Ｐ不可分見直表示 */
     zrnstdsstkjytkyuhyj ,         /* （連携用）外出新特条適用表示 */
     zrnkbnkeiriyousegmentkbn ,         /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn ,         /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd ,         /* （連携用）数理種類コード */
     zrnhosyoukinoukbn ,         /* （連携用）保障機能区分 */
     zrndaikbn ,         /* （連携用）大区分 */
     zrntyuukbn ,         /* （連携用）中区分 */
     zrnsyoukbn ,         /* （連携用）小区分 */
     zrnsedaikbn ,         /* （連携用）世代区分 */
     zrnharaikatakbn ,         /* （連携用）払方区分 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrntksyuannaikykkbn ,         /* （連携用）特殊案内契約区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnsdpdkbn ,         /* （連携用）Ｓ建Ｐ建区分 */
     zrnryouritukbn ,         /* （連携用）料率区分 */
     zrnao3tyou3sibousdatehyouji ,         /* （連携用）青３長３死亡Ｓ建表示 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrnkyksyanen ,         /* （連携用）契約者年令 */
     zrndai2hhknnen ,         /* （連携用）第２被保険者年令 */
     zrntkbthsyumnryuhyouji ,         /* （連携用）特別保障満了表示 */
     zrnsyukeiyakupwaribikikbn ,         /* （連携用）主契約Ｐ割引区分 */
     zrntenkanwaribikikbn ,         /* （連携用）転換割引区分 */
     zrnyuuhitutnknyuguryurtkbn ,         /* （連携用）有配当転換優遇料率区分 */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrntokujyoup ,         /* （連携用）特条Ｐ */
     zrnsiteizukisyukeiyakup ,         /* （連携用）指定月主契約Ｐ */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnsibous ,         /* （連携用）死亡Ｓ */
     zrnhenkougokihons ,         /* （連携用）変更後基本Ｓ */
     zrnhenkougosibous ,         /* （連携用）変更後死亡Ｓ */
     zrnhenkouymd ,         /* （連携用）変更年月日 */
     zrnentyoukikan ,         /* （連携用）延長期間 */
     zrnseizonkyuuhukinsiteimd ,         /* （連携用）生存給付金指定月日 */
     zrnsyukeiyakusiharaikingaku ,         /* （連携用）主契約支払金額 */
     zrnatukaisisyatodouhukencd ,         /* （連携用）扱支社都道府県コード */
     zrntokuyakuhukasuu ,         /* （連携用）特約付加数 */
     zrndi2hknkknikoujihisyaage ,         /* （連携用）第２保険期間移行時被者年令 */
     zrnhrimnentyoumaephrkkkn ,         /* （連携用）払満延長前Ｐ払込期間 */
     zrntokubetuhosyoukikan ,         /* （連携用）特別保障期間 */
     zrnkousinmanryouage ,         /* （連携用）更新満了年令 */
     zrnknkuzusnzyrttekitkarihyj ,         /* （連携用）健康増進乗率適用特約有表示 */
     zrnkuriagekurisagekbn ,         /* （連携用）繰上げ繰下げ区分 */
     zrnhrizmjhknsyukigousdkbn ,         /* （連携用）払済時保険種類記号世代区分 */
     zrnkrsgjhknsyukigousdkbn ,         /* （連携用）繰下げ時保険種類記号世代区分 */
     zrnsotodasisyouhinkaiteikbn ,         /* （連携用）外出商品改定区分 */
     zrnyobiv4 ,         /* （連携用）予備項目Ｖ４ */
     zrngoukeitenkans ,         /* （連携用）合計転換Ｓ */
     zrngoukeipbubuntenkans ,         /* （連携用）合計Ｐ部分転換Ｓ */
     zrntenkanteikisyuruikigou ,         /* （連携用）転換定期種類記号 */
     zrntenkanteikikigousedaikbn ,         /* （連携用）転換定期記号世代区分 */
     zrntnkntiksotodasikusnkbn ,         /* （連携用）転換定期外出更新区分 */
     zrntnkntikstdspmenkbn ,         /* （連携用）転換定期外出Ｐ免区分 */
     zrntenkanteikikigouyobi ,         /* （連携用）転換定期記号予備 */
     zrntenkanteikikikan ,         /* （連携用）転換定期期間 */
     zrngoukeitenkanteikis ,         /* （連携用）合計転換定期Ｓ */
     zrntnknteikinkshrkkn ,         /* （連携用）転換定期年金支払期間 */
     zrntenkansiharaikingaku ,         /* （連携用）転換支払金額 */
     zrntnkntikshrkngk ,         /* （連携用）転換定期支払金額 */
     zrntenkankaisuu ,         /* （連携用）転換回数 */
     zrngoukeitenkankakaku ,         /* （連携用）合計転換価格 */
     zrntnknkhnbbnjyuturt ,         /* （連携用）転換基本部分充当率 */
     zrnwnasigoukeitenkanteikis ,         /* （連携用）Ｗなし合計転換定期Ｓ */
     zrntnknteikikousinmnryouage ,         /* （連携用）転換定期更新満了年令 */
     zrnyobiv5 ,         /* （連携用）予備項目Ｖ５ */
     zrnkanyujidatakanrino ,         /* （連携用）加入時データ管理番号 */
     zrnkanyujikykymd ,         /* （連携用）加入時契約年月日 */
     zrnkanyuujihihokensyaage ,         /* （連携用）加入時被保険者年令 */
     zrnkanyuujitenkanhyouji ,         /* （連携用）加入時転換表示 */
     zrnhsyuikktminaosikaisu ,         /* （連携用）保障一括見直回数 */
     zrnsknnjynbknsisnrt ,         /* （連携用）責任準備金精算率 */
     zrntkjykbn ,         /* （連携用）特条区分 */
     zrnsakugenkikan ,         /* （連携用）削減期間 */
     zrnryoumasihyouten ,         /* （連携用）料増標点 */
     zrnsykyktkjyuryumsratehyj ,         /* （連携用）主契約特条料増レート表示 */
     zrnsykyktkjyuryumsrate ,         /* （連携用）主契約特条料増レート */
     zrndai2tokujyoukbn ,         /* （連携用）第２特条区分 */
     zrndai2sakugenkikan ,         /* （連携用）第２削減期間 */
     zrndai2ryoumasihyouten ,         /* （連携用）第２料増標点 */
     zrntokuteibuijyoukenhyouji ,         /* （連携用）特定部位条件表示 */
     zrntokuteibuino1 ,         /* （連携用）特定部位番号１ */
     zrnhtnpkkn1 ,         /* （連携用）不担保期間１ */
     zrntokuteibuino2 ,         /* （連携用）特定部位番号２ */
     zrnhtnpkkn2 ,         /* （連携用）不担保期間２ */
     zrnmhituiryuyutktbijyknhyj ,         /* （連携用）無配当医療用特定部位条件表示 */
     zrnmuhaitouiryouyoutktbino1 ,         /* （連携用）無配当医療用特定部位番号１ */
     zrnmuhaitouiryouyouhtnpkkn1 ,         /* （連携用）無配当医療用不担保期間１ */
     zrnmuhaitouiryouyoutktbino2 ,         /* （連携用）無配当医療用特定部位番号２ */
     zrnmuhaitouiryouyouhtnpkkn2 ,         /* （連携用）無配当医療用不担保期間２ */
     zrnsiteizukipwarimasihyouji ,         /* （連携用）指定月Ｐ割増表示 */
     zrnpwarimasisiteim1 ,         /* （連携用）Ｐ割増指定月１ */
     zrnpwarimasisiteim2 ,         /* （連携用）Ｐ割増指定月２ */
     zrnsiteimsykykpbairitu ,         /* （連携用）指定月主契約Ｐ倍率 */
     zrnsaisyuusiteiym ,         /* （連携用）最終指定年月 */
     zrnsykykkitmttvkeisanym ,         /* （連携用）主契約既積立Ｖ計算年月 */
     zrnsykykkitmttsknnjynbkngk ,         /* （連携用）主契約既積立責任準備金額 */
     zrndftumitatekingaku ,         /* （連携用）ＤＦ積立金額 */
     zrndftumimasikin ,         /* （連携用）ＤＦ積増金 */
     zrnvbubundftenkankakaku ,         /* （連携用）Ｖ部分ＤＦ転換価格 */
     zrndpbubundftenkankakaku ,         /* （連携用）ＤＰ部分ＤＦ転換価格 */
     zrndftmttkngkitjbrbbn ,         /* （連携用）ＤＦ積立金額一時払部分 */
     zrnhendous ,         /* （連携用）変動Ｓ */
     zrnhengakujigyounendomatucv ,         /* （連携用）変額事業年度末ＣＶ */
     zrnitibuitijibarais ,         /* （連携用）一部一時払Ｓ */
     zrnitibuitijibaraip ,         /* （連携用）一部一時払Ｐ */
     zrnitibitjbrshrkngk ,         /* （連携用）一部一時払支払金額 */
     zrngoukeicv ,         /* （連携用）合計ＣＶ */
     zrnminasicv ,         /* （連携用）みなしＣＶ */
     zrnloanfund ,         /* （連携用）ローンファンド */
     zrnsaiteihosyougaku ,         /* （連携用）最低保証額 */
     zrnhngksitihsyuyusykykp ,         /* （連携用）変額最低保証用主契約Ｐ */
     zrnhijynbrivasbujsitihsyugk ,         /* （連携用）平準払ＶＡ死亡時最低保証金額 */
     zrnhijynbrivamnkjsitihsyugk ,         /* （連携用）平準払ＶＡ満期時最低保証金額 */
     zrnsiinkbn ,         /* （連携用）死因区分 */
     zrnmudkaimasikihons ,         /* （連携用）ミューＤ買増基本Ｓ */
     zrnkaimasiymd ,         /* （連携用）買増年月日 */
     zrnkaimasikikan ,         /* （連携用）買増期間 */
     zrnhikitugikaimasis ,         /* （連携用）引継買増Ｓ */
     zrnmudkaimasisiharaikingaku ,         /* （連携用）ミューＤ買増支払金額 */
     zrnszoukouryokukaisiymdx1 ,         /* （連携用）Ｓ増効力開始年月日＿１ */
     zrnszouhokensyuruikigoux1 ,         /* （連携用）Ｓ増保険種類記号＿１ */
     zrnszoukigousedaikbnx1 ,         /* （連携用）Ｓ増記号世代区分＿１ */
     zrnszoukikanx1 ,         /* （連携用）Ｓ増期間＿１ */
     zrnszouhihokensyaagex1 ,         /* （連携用）Ｓ増被保険者年令＿１ */
     zrnszoudai2hihknsyaagex1 ,         /* （連携用）Ｓ増第２被保険者年令＿１ */
     zrnzoukasx1 ,         /* （連携用）増加Ｓ＿１ */
     zrnzennendozoukasx1 ,         /* （連携用）前年度増加Ｓ＿１ */
     zrnszousiharaikingakux1 ,         /* （連携用）Ｓ増支払金額＿１ */
     zrnszoukouryokukaisiymdx2 ,         /* （連携用）Ｓ増効力開始年月日＿２ */
     zrnszouhokensyuruikigoux2 ,         /* （連携用）Ｓ増保険種類記号＿２ */
     zrnszoukigousedaikbnx2 ,         /* （連携用）Ｓ増記号世代区分＿２ */
     zrnszoukikanx2 ,         /* （連携用）Ｓ増期間＿２ */
     zrnszouhihokensyaagex2 ,         /* （連携用）Ｓ増被保険者年令＿２ */
     zrnszoudai2hihknsyaagex2 ,         /* （連携用）Ｓ増第２被保険者年令＿２ */
     zrnzoukasx2 ,         /* （連携用）増加Ｓ＿２ */
     zrnzennendozoukasx2 ,         /* （連携用）前年度増加Ｓ＿２ */
     zrnszousiharaikingakux2 ,         /* （連携用）Ｓ増支払金額＿２ */
     zrnsuuriyouyobin1x5 ,         /* （連携用）数理用予備項目Ｎ１＿５ */
     zrnsuuriyouyobin1x6 ,         /* （連携用）数理用予備項目Ｎ１＿６ */
     zrnhrimngkizktkykpmenhyj ,         /* （連携用）払満後継続特約Ｐ免表示 */
     zrnmisyuustartym ,         /* （連携用）未収開始年月 */
     zrnmisyuukaisuu ,         /* （連携用）未収回数 */
     zrnitjbrtkykkousnuktkarhyj ,         /* （連携用）一時払特約更新受付有表示 */
     zrngyousekihyoujis ,         /* （連携用）業績表示Ｓ */
     zrnsykykgyusekihyjs ,         /* （連携用）主契約業績表示Ｓ */
     zrntenkangyousekihyoujis ,         /* （連携用）転換業績表示Ｓ */
     zrntnknteikigyousekihyjs ,         /* （連携用）転換定期業績表示Ｓ */
     zrntnkndpbbngyuskhyjs ,         /* （連携用）転換ＤＰ部分業績表示Ｓ */
     zrnkykjyoutai ,         /* （連携用）契約状態 */
     zrnpmenhukakbn ,         /* （連携用）Ｐ免付加区分 */
     zrnkousinkbn ,         /* （連携用）更新区分 */
     zrnmankiyoteikbn ,         /* （連携用）満期予定区分 */
     zrnsykyktikmnkyoteikbn ,         /* （連携用）主契約定期満期予定区分 */
     zrntnknsykykkhnmnkytikbn ,         /* （連携用）転換主契約基本満期予定区分 */
     zrntnknsykyktikmnkytikbn ,         /* （連携用）転換主契約定期満期予定区分 */
     zrntenkanteikimankiyoteikbn ,         /* （連携用）転換定期満期予定区分 */
     zrnszoumankiyoteikbnx1 ,         /* （連携用）Ｓ増満期予定区分＿１ */
     zrnszoumankiyoteikbnx2 ,         /* （連携用）Ｓ増満期予定区分＿２ */
     zrnvestingmankiyoteikbn ,         /* （連携用）ベスティング満期予定区分 */
     zrnvkeisanhyouji ,         /* （連携用）Ｖ計算表示 */
     zrntoukisinkeiyakuhyouji ,         /* （連携用）当期新契約表示 */
     zrnsykykhokenhoutekiyouhyj ,         /* （連携用）主契約保険法適用表示 */
     zrntokuteijyoutaihushrhyj ,         /* （連携用）特定状態不支払表示 */
     zrnytirrthndsysnmnskaisuu ,         /* （連携用）予定利率変動終身見直回数 */
     zrnsuuriyouyobin3 ,         /* （連携用）数理用予備項目Ｎ３ */
     zrnsuuriyouyobin11 ,         /* （連携用）数理用予備項目Ｎ１１ */
     zrnwnasigoukeitenkankakaku ,         /* （連携用）Ｗなし合計転換価格 */
     zrnyobin11 ,         /* （連携用）予備項目Ｎ１１ */
     zrnyobin11x2 ,         /* （連携用）予備項目Ｎ１１＿２ */
     zrnyobin11x3 ,         /* （連携用）予備項目Ｎ１１＿３ */
     zrntukibaraikansantokujyoup ,         /* （連携用）月払換算特条Ｐ */
     zrntnkngkykkssnkijyuym ,         /* （連携用）転換後契約決算計上年月 */
     zrnsaiteihosyouhyouji ,         /* （連携用）最低保証表示 */
     zrnsuuriyouyobin8x2 ,         /* （連携用）数理用予備項目Ｎ８＿２ */
     zrnsuuriyouyobin14 ,         /* （連携用）数理用予備項目Ｎ１４ */
     zrnhrimngtkykphrkkaisuukbn ,         /* （連携用）払満後特約Ｐ払込回数区分 */
     zrnhrimngtkykphrkkirkbn ,         /* （連携用）払満後特約Ｐ払込経路区分 */
     zrnhrimngtkykpryurtkbn ,         /* （連携用）払満後特約Ｐ料率区分 */
     zrnyobiv13 ,         /* （連携用）予備項目Ｖ１３ */
     zrnidoujisaiteihosyoukngk ,         /* （連携用）異動時最低保証金額 */
     zrnidoujisaiteihosyoucost ,         /* （連携用）異動時最低保証コスト */
     zrnsinhokenfundtumitatekin ,         /* （連携用）新保険ファンド積立金 */
     zrnmsyuptusshkgkaiykhnrikn ,         /* （連携用）未収Ｐ等差引後解約返戻金 */
     zrnrrthndugtnkgetumatuv ,         /* （連携用）利率変動型年金月末Ｖ */
     zrnrrthndnksaiteihosyonkgns ,         /* （連携用）利率変動年金最低保証年金原資 */
     zrnrrthendougatanksibous ,         /* （連携用）利率変動型年金死亡Ｓ */
     zrnalmyousohutomeisyoukbn ,         /* （連携用）ＡＬＭ用ソフト名称区分 */
     zrnsnkyksoftmeisyoukbn ,         /* （連携用）新契約ソフト名称区分 */
     zrnsoftmeisyoukbn ,         /* （連携用）ソフト名称区分 */
     zrnkykjitokujyouarihyj ,         /* （連携用）契約時特条有表示 */
     zrnbnkttnknkbn ,         /* （連携用）分割転換区分 */
     zrntenkanminaosikbn ,         /* （連携用）転換見直区分 */
     zrnsoujikeitenkankbn ,         /* （連携用）相似形転換区分 */
     zrnnenkinkaisinendo ,         /* （連携用）年金開始年度 */
     zrnnenkingatakbn ,         /* （連携用）年金型区分 */
     zrnnknshry ,         /* （連携用）年金支払期間 */
     zrnheiyoubaraikeiyakukbn ,         /* （連携用）併用払契約区分 */
     zrnnenkinmaruteihukakbn ,         /* （連携用）年金マル定付加区分 */
     zrnsinseizonmrtiarihyj ,         /* （連携用）新生存マル定有表示 */
     zrnsnkykyouibokijyukbn ,         /* （連携用）新契約用異募計上区分 */
     zrntokusitujyuusitusetkbn ,         /* （連携用）特疾重疾セット区分 */
     zrnsiktsyuknbyugnhsyunshyj ,         /* （連携用）生活習慣病がん保障無表示 */
     zrnpmensugugtganhsyunshyj ,         /* （連携用）Ｐ免総合型がん保障無表示 */
     zrntkykgyousekihyjszerohyj ,         /* （連携用）特約業績表示Ｓゼロ表示 */
     zrnsuuriyouyobin7 ,         /* （連携用）数理用予備項目Ｎ７ */
     zrnsyussaikeitaikbn ,         /* （連携用）出再形態区分 */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrnbosyuukeitaikbn ,         /* （連携用）募集形態区分 */
     zrnaatukaisosikicd ,         /* （連携用）Ａ扱者組織コード */
     zrnaatukaikojincd ,         /* （連携用）Ａ扱者個人コード */
     zrnbsydrtencd ,         /* （連携用）募集代理店コード */
     zrncifcd ,         /* （連携用）ＣＩＦコード */
     zrnsuuriyouyobiv8 ,         /* （連携用）数理用予備項目Ｖ８ */
     zrnsinsakbn ,         /* （連携用）診査区分 */
     zrndai2hihokensyasinsakbn ,         /* （連携用）第２被保険者診査区分 */
     zrntoukeiyousinsakbn ,         /* （連携用）統計用診査区分 */
     zrndai2toukeiyousinsakbn ,         /* （連携用）第２統計用診査区分 */
     zrnketteikijyunkanwakbn ,         /* （連携用）決定基準緩和区分 */
     zrnkihonsibouhyoukbn ,         /* （連携用）基本死亡表区分 */
     zrnteikisibouhyoukbn ,         /* （連携用）定期死亡表区分 */
     zrnsonotasibouhyoukbn ,         /* （連携用）その他死亡表区分 */
     zrnmrarihyj ,         /* （連携用）ＭＲ有表示 */
     zrnsentakujyouhouarihyouji ,         /* （連携用）選択情報有表示 */
     zrndugktnknsntkhuhukbn ,         /* （連携用）同額転換選択方法区分 */
     zrngengakutenkankykhyj ,         /* （連携用）減額転換契約表示 */
     zrnsykgycd ,         /* （連携用）職業コード */
     zrnjidoukousinkykkanyuuymd ,         /* （連携用）自動更新契約加入年月日 */
     zrnsaikohtnknkykkykymd ,         /* （連携用）最古被転換契約契約年月日 */
     zrnkousinmaesykyksburtkbn ,         /* （連携用）更新前主契約死亡率区分 */
     zrnhjnkykhyj ,         /* （連携用）法人契約表示 */
     zrnanniskcd ,         /* （連携用）案内先コード */
     zrnhjncd ,         /* （連携用）法人コード */
     zrnhjnjigyosyocd ,         /* （連携用）法人事業所コード */
     zrnsaihokenno ,         /* （連携用）再保険番号 */
     zrndakuhikettikekkacd ,         /* （連携用）諾否決定結果コード */
     zrndai2dakuhiketteikekkacd ,         /* （連携用）第２諾否決定結果コード */
     zrnpmenkbnv2 ,         /* （連携用）Ｐ免区分Ｖ２ */
     zrnsiboukyuuhukin ,         /* （連携用）死亡給付金 */
     zrnjyudthumeharaitkykhkhyj ,         /* （連携用）重度痴呆前払特約付加表示 */
     zrnhaitoukbn ,         /* （連携用）配当区分 */
     zrnhhknnentysihyj ,         /* （連携用）被保険者年令調整表示 */
     zrndai2hhknnentysihyj ,         /* （連携用）第２被保険者年令調整表示 */
     zrnkyksyaagetyouseihyj ,         /* （連携用）契約者年令調整表示 */
     zrnkituenkbn ,         /* （連携用）喫煙区分 */
     zrnkituenhonsuu ,         /* （連携用）喫煙本数 */
     zrnmusentakukeiyakukbn ,         /* （連携用）無選択契約区分 */
     zrnyobiv6x2 ,         /* （連携用）予備項目Ｖ６＿２ */
     zrnlivingneedstkykarihyj ,         /* （連携用）リビングニーズ特約有表示 */
     zrnlivingneedssiharaihyouji ,         /* （連携用）リビングニーズ支払表示 */
     zrnlnseikyuuymd ,         /* （連携用）ＬＮ請求年月日 */
     zrnlnshrgenincd ,         /* （連携用）ＬＮ支払原因コード */
     zrndakuhikettisyacd ,         /* （連携用）諾否決定者コード */
     zrndai2dakuhiketteisyacd ,         /* （連携用）第２諾否決定者コード */
     zrngansapotokuyakuarihyouji ,         /* （連携用）がんサポ特約有表示 */
     zrngnspshrhyj ,         /* （連携用）がんサポ支払表示 */
     zrngansaposeikyuuymd ,         /* （連携用）がんサポ請求年月日 */
     zrngnspshrgenincd ,         /* （連携用）がんサポ支払原因コード */
     zrnyobiv3x2 ,         /* （連携用）予備項目Ｖ３＿２ */
     zrntargetmokuhyouritu ,         /* （連携用）ターゲット目標率 */
     zrnautoswitchmokuhyouritu ,         /* （連携用）オートスイッチ目標率 */
     zrntumitatekinitenarihyj ,         /* （連携用）積立金移転有表示 */
     zrntumitatekinitenkaisuu ,         /* （連携用）積立金移転回数 */
     zrndatakanrino2 ,         /* （連携用）データ管理番号２ */
     zrndatakanrino3 ,         /* （連携用）データ管理番号３ */
     zrnknkuzusnzyrttekinendo ,         /* （連携用）健康増進乗率適用年度 */
     zrnknkuzusnzyrt ,         /* （連携用）健康増進乗率 */
     zrnknkuzusnzyrtx2 ,         /* （連携用）健康増進乗率＿２ */
     zrnknkuzusnzyrtx3 ,         /* （連携用）健康増進乗率＿３ */
     zrnsinkeiyakujiknkuzusnzyrt ,         /* （連携用）新契約時健康増進乗率 */
     zrntenkanjiknkuzusnzyrt ,         /* （連携用）転換時健康増進乗率 */
     zrnsinkeiyakujivithkhyouji ,         /* （連携用）新契約時Ｖｉｔ保険表示 */
     zrnkykjivithukusuukykhyj ,         /* （連携用）契約時Ｖｉｔ複数契約表示 */
     zrnsuuriyouyobin9x2 ,         /* （連携用）数理用予備項目Ｎ９＿２ */
     zrnpwrbksidhitekiyouhyj ,         /* （連携用）保険料割引制度非適用表示 */
     zrnsuuriyouyobin9 ,         /* （連携用）数理用予備項目Ｎ９ */
     zrnsuuriyouyobin10x7 ,         /* （連携用）数理用予備項目Ｎ１０＿７ */
     zrnsuuriyouyobin10x8 ,         /* （連携用）数理用予備項目Ｎ１０＿８ */
     zrnsuuriyouyobin10x9 ,         /* （連携用）数理用予備項目Ｎ１０＿９ */
     zrntumitatekinitenbubun ,         /* （連携用）積立金移転部分 */
     zrnsagakusknnjynbknzndk ,         /* （連携用）差額責任準備金残高 */
     zrnyobin11x5 ,         /* （連携用）予備項目Ｎ１１＿５ */
     zrnyobin11x6 ,         /* （連携用）予備項目Ｎ１１＿６ */
     zrnyobin11x7 ,         /* （連携用）予備項目Ｎ１１＿７ */
     zrnyobin11x8 ,         /* （連携用）予備項目Ｎ１１＿８ */
     zrnyobin11x9 ,         /* （連携用）予備項目Ｎ１１＿９ */
     zrnyobin11x10 ,         /* （連携用）予備項目Ｎ１１＿１０ */
     zrnyobin11x11 ,         /* （連携用）予備項目Ｎ１１＿１１ */
     zrnyobin11x12 ,         /* （連携用）予備項目Ｎ１１＿１２ */
     zrnyobin11x13 ,         /* （連携用）予備項目Ｎ１１＿１３ */
     zrnyobin11x14 ,         /* （連携用）予備項目Ｎ１１＿１４ */
     zrnyobin11x15 ,         /* （連携用）予備項目Ｎ１１＿１５ */
     zrnyobin11x16 ,         /* （連携用）予備項目Ｎ１１＿１６ */
     zrnyobin11x17 ,         /* （連携用）予備項目Ｎ１１＿１７ */
     zrnzyrthntiyustatuskbn ,         /* （連携用）乗率判定用ステータス区分 */
     zrnzyrthntiyustatuskbnx2 ,         /* （連携用）乗率判定用ステータス区分＿２ */
     zrnzyrthntiyustatuskbnx3 ,         /* （連携用）乗率判定用ステータス区分＿３ */
     zrnzyrthntiyustatuskbnx4 ,         /* （連携用）乗率判定用ステータス区分＿４ */
     zrnzyrthntiyustatuskbnx5 ,         /* （連携用）乗率判定用ステータス区分＿５ */
     zrnyobiv10 ,         /* （連携用）予備項目Ｖ１０ */
     zrnyobiv15x2 ,         /* （連携用）予備項目Ｖ１５＿２ */
     zrnyobiv15x3 ,         /* （連携用）予備項目Ｖ１５＿３ */
     zrnyobiv15x4 ,         /* （連携用）予備項目Ｖ１５＿４ */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnkawaserate1 ,         /* （連携用）為替レート１ */
     zrnkawaseratetekiyouymd1 ,         /* （連携用）為替レート適用年月日１ */
     zrnkawaserate2 ,         /* （連携用）為替レート２ */
     zrnkawaseratetekiyouymd2 ,         /* （連携用）為替レート適用年月日２ */
     zrnkykjikawaserate ,         /* （連携用）契約時為替レート */
     zrnkykjikawaseratetkyuymd ,         /* （連携用）契約時為替レート適用年月日 */
     zrnmvatyouseigow ,         /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn ,         /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnkaiyakukoujyoritu ,         /* （連携用）解約控除率 */
     zrnrendouritu ,         /* （連携用）連動率 */
     zrnsrkaiyakusjkkktyouseirrt ,         /* （連携用）数理用解約時市場価格調整用利率 */
     zrnsrkyksjkkktyouseiriritu ,         /* （連携用）数理用契約時市場価格調整用利率 */
     zrnmvakeisankijyunymd ,         /* （連携用）ＭＶＡ計算基準年月日 */
     zrnmvatyouseikou ,         /* （連携用）ＭＶＡ調整項 */
     zrnenkdtsbujsitihsyukngk ,         /* （連携用）円貨建死亡時最低保証金額 */
     zrnenkdtsbujsitihsyucost ,         /* （連携用）円貨建死亡時最低保証コスト */
     zrnenkdtsbujsitihsyuarihyj ,         /* （連携用）円貨建死亡時最低保証あり表示 */
     zrnkeiyakujiyoteiriritu ,         /* （連携用）契約時予定利率 */
     zrntumitateriritu ,         /* （連携用）積立利率 */
     zrnkaigomaebaraitkykarihyj ,         /* （連携用）介護前払特約あり表示 */
     zrnsibouhyoukbn ,         /* （連携用）死亡表区分 */
     zrnnyuukintuukakbn ,         /* （連携用）入金通貨区分 */
     zrnsiharaituukakbn ,         /* （連携用）支払通貨区分 */
     zrnwyendttargetmokuhyouritu ,         /* （連携用）円建Ｗターゲット目標率 */
     zrnsisuurendourate ,         /* （連携用）指数連動部分割合 */
     zrnsisuukbn ,         /* （連携用）指数区分 */
     zrnteirituikouhyouji ,         /* （連携用）定率移行表示 */
     zrnsuuriyouyobin2x3 ,         /* （連携用）数理用予備項目Ｎ２＿３ */
     zrnsuuriyouyobin10x11 ,         /* （連携用）数理用予備項目Ｎ１０＿１１ */
     zrntmttknzoukaritujygn ,         /* （連携用）積立金増加率上限 */
     zrnsetteibairitu ,         /* （連携用）設定倍率 */
     zrntykzenoutouymdsisuu ,         /* （連携用）直前応当日指数 */
     zrnkimatusisuu ,         /* （連携用）期末指数 */
     zrnyobiv3 ,         /* （連携用）予備項目Ｖ３ */
     zrnyenkadatekihons ,         /* （連携用）円貨建基本Ｓ */
     zrnsitihsyumegkdtsibous ,         /* （連携用）最低保証前外貨建死亡Ｓ */
     zrnenkdtssrentumitatekin ,         /* （連携用）円貨建指数連動部分積立金 */
     zrnsisuurentumitatekin ,         /* （連携用）指数連動部分積立金 */
     zrnnksjitirttumitatekin ,         /* （連携用）年金開始時定率部分積立金 */
     zrnkimatutirttumitatekin ,         /* （連携用）期末定率部分積立金 */
     zrngaikadatejyuutoup ,         /* （連携用）外貨建充当Ｐ */
     zrnyendttargetkijyunkingaku ,         /* （連携用）円建ターゲット基準金額 */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrnsitivkisnyukykjikwsrate ,         /* （連携用）最低Ｖ計算用契約時為替レート */
     zrnsisuurentyokugotmttkn ,         /* （連携用）指数連動部分直後積立金 */
     zrnyoteiririturironbase ,         /* （連携用）予定利率（理論ベース） */
     zrnyoteiriritujtnyknbase ,         /* （連携用）予定利率（実入金ベース） */
     zrnkihrkmpjtnyknbase ,         /* （連携用）既払込Ｐ（実入金ベース） */
     zrnsyuptumitatekin ,         /* （連携用）主契約保険料積立金 */
     zrnsyuptumitatekingsc ,         /* （連携用）主契約保険料積立金（月初） */
     zrngaikadatenkgns ,         /* （連携用）外貨建年金原資 */
     zrnjikaipjyuutouym2 ,         /* （連携用）次回Ｐ充当年月２ */
     zrnsuuriyobin9 ,         /* （連携用）数理予備項目Ｎ９ */
     zrngessitumitatekin ,         /* （連携用）月始積立金 */
     zrngaikadatetougetujuutoup ,         /* （連携用）外貨建当月充当Ｐ */
     zrnkihrkmpmsukisymbase ,         /* （連携用）既払込Ｐ（未収開始月ベース） */
     zrnkeisanhanteiyoutmttkn ,         /* （連携用）計算判定用積立金 */
     zrngtmtv ,         /* （連携用）月末Ｖ */
     zrnzettaisibouritu ,         /* （連携用）絶対死亡率 */
     zrnsoutaisibouritu ,         /* （連携用）相対死亡率 */
     zrnsoutaikaiyakuritu ,         /* （連携用）相対解約率 */
     zrnvhireilritu2 ,         /* （連携用）Ｖ比例Ｌ率２ */
     zrnphireialpha ,         /* （連携用）Ｐ比例α */
     zrnphireibeta ,         /* （連携用）Ｐ比例β */
     zrnphireiganma ,         /* （連携用）Ｐ比例γ */
     zrnphireilwrbkritu ,         /* （連携用）Ｐ比例Ｌ割引率 */
     zrnyoteiriritumsukisymbase ,         /* （連携用）予定利率（未収開始月ベース） */
     zrnrrthnduhknvkisovkisnyu1 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用１ */
     zrnrrthnduhknvkisovkisnyu2 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用２ */
     zrnrrthnduhknvkisovkisnyu3 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用３ */
     zrnrrthnduhknvkisovkisnyu4 ,         /* （連携用）利率変動保険Ｖ基礎Ｖ計算用４ */
     zrnrrthnduhknvkiso ,         /* （連携用）利率変動保険Ｖ基礎Ｖ */
     zrntumitatekin ,         /* （連携用）積立金 */
     zrnkiharaikomip ,         /* （連携用）既払込Ｐ */
     zrngaikadatesyukeiyakup ,         /* （連携用）外貨建主契約Ｐ */
     zrnkykkjmmvatyouseigow ,         /* （連携用）解約控除前ＭＶＡ調整後Ｗ */
     zrnyobin11x39 ,         /* （連携用）予備項目Ｎ１１＿３９ */
     zrnyobin11x41 ,         /* （連携用）予備項目Ｎ１１＿４１ */
     zrnyobin11x42 ,         /* （連携用）予備項目Ｎ１１＿４２ */
     zrnyobin11x43 ,         /* （連携用）予備項目Ｎ１１＿４３ */
     zrnyobin11x44 ,         /* （連携用）予備項目Ｎ１１＿４４ */
     zrnyobin11x45 ,         /* （連携用）予備項目Ｎ１１＿４５ */
     zrnsuuriyouyobin15x3 ,         /* （連携用）数理用予備項目Ｎ１５＿３ */
     zrnsuuriyouyobin15x4 ,         /* （連携用）数理用予備項目Ｎ１５＿４ */
     zrnsuuriyouyobin15x5 ,         /* （連携用）数理用予備項目Ｎ１５＿５ */
     zrnsuuriyouyobin15x6 ,         /* （連携用）数理用予備項目Ｎ１５＿６ */
     zrnyobiv14 ,         /* （連携用）予備項目Ｖ１４ */
     zrnloadingkeijyoym ,         /* （連携用）ローディング計上年月 */
     zrnsihankiksnydatahyj ,         /* （連携用）四半期決算用データ表示 */
     zrngmkijyhyj ,         /* （連携用）月末計上表示 */
     zrnsuuriyouyobin12 ,         /* （連携用）数理用予備項目Ｎ１２ */
     zrnyobiv20 ,         /* （連携用）予備項目Ｖ２０ */
     zrnyobin11x18 ,         /* （連携用）予備項目Ｎ１１＿１８ */
     zrnvhireilkisnyukngkx1 ,         /* （連携用）Ｖ比例Ｌ計算用金額＿１ */
     zrnyobin11x19 ,         /* （連携用）予備項目Ｎ１１＿１９ */
     zrnyobin11x20 ,         /* （連携用）予備項目Ｎ１１＿２０ */
     zrnyobin11x21 ,         /* （連携用）予備項目Ｎ１１＿２１ */
     zrnvhireilkisnyukngkx2 ,         /* （連携用）Ｖ比例Ｌ計算用金額＿２ */
     zrnyobin11x22 ,         /* （連携用）予備項目Ｎ１１＿２２ */
     zrnyobin11x23 ,         /* （連携用）予備項目Ｎ１１＿２３ */
     zrnrpkeisanyousibous ,         /* （連携用）ＲＰ計算用死亡Ｓ */
     zrnkikens ,         /* （連携用）危険保険金 */
     zrnvhireialpha ,         /* （連携用）Ｖ比例α */
     zrnvhireibeta ,         /* （連携用）Ｖ比例β */
     zrnkikenp ,         /* （連携用）危険保険料 */
     zrnvhireilritu ,         /* （連携用）Ｖ比例Ｌ率 */
     zrnkikenpritu ,         /* （連携用）危険保険料率 */
     zrntumimasimaew ,         /* （連携用）積増前Ｗ */
     zrnyobin11x25 ,         /* （連携用）予備項目Ｎ１１＿２５ */
     zrnyobin11x26 ,         /* （連携用）予備項目Ｎ１１＿２６ */
     zrnyobin11x27 ,         /* （連携用）予備項目Ｎ１１＿２７ */
     zrnyobin11x28 ,         /* （連携用）予備項目Ｎ１１＿２８ */
     zrnyobin11x29 ,         /* （連携用）予備項目Ｎ１１＿２９ */
     zrnyobin11x30 ,         /* （連携用）予備項目Ｎ１１＿３０ */
     zrnyobin11x31 ,         /* （連携用）予備項目Ｎ１１＿３１ */
     zrnyobin11x32 ,         /* （連携用）予備項目Ｎ１１＿３２ */
     zrnsuuriyouyobin15 ,         /* （連携用）数理用予備項目Ｎ１５ */
     zrnyobiv19           /* （連携用）予備項目Ｖ１９ */
FROM ZT_KsnKbkSsuRnduHknJigyohiRn_Z;