CREATE VIEW ZT_JigyounndsikiTkHoyuuRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnyobiv12 ,         /* （連携用）予備項目Ｖ１２ */
     zrndatakanrino ,         /* （連携用）データ管理番号 */
     zrnsuuriyoutokuyakukbn ,         /* （連携用）数理用特約区分 */
     zrntokuyakugatakbn ,         /* （連携用）特約型区分 */
     zrntokuyakukisi ,         /* （連携用）特約期始 */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnsisyacd ,         /* （連携用）支社コード */
     zrnsibucd ,         /* （連携用）支部コード */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrnhhknhnsktodouhukencd ,         /* （連携用）被保険者本籍都道府県コード */
     zrntokuyakus ,         /* （連携用）特約Ｓ */
     zrnsinkeityuutokbn ,         /* （連携用）新契中途区分 */
     zrnsyukeiyakusrank ,         /* （連携用）主契約Ｓランク */
     zrnsyukeiyakuprank ,         /* （連携用）主契約Ｐランク */
     zrnsyukeiyakukykjigyouy ,         /* （連携用）主契約契約事業年 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnryouritukbn ,         /* （連携用）料率区分 */
     zrntksyuannaikykkbn ,         /* （連携用）特殊案内契約区分 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnmaruteiskeijihukahyj ,         /* （連携用）マル定新契約時付加表示 */
     zrntenkankaisuu ,         /* （連携用）転換回数 */
     zrntokuyakutokujyoukbn ,         /* （連携用）特約特条区分 */
     zrndai2maruhihyj ,         /* （連携用）第２マル被表示 */
     zrntokuteijyuusitusetkbn ,         /* （連携用）特定重疾セット区分 */
     zrndugktnknsntkhuhukbn ,         /* （連携用）同額転換選択方法区分 */
     zrngengakutenkankykhyj ,         /* （連携用）減額転換契約表示 */
     zrnhaitoukbn ,         /* （連携用）配当区分 */
     zrnkusnmesyokaipjyuutouym ,         /* （連携用）更新前初回Ｐ充当年月 */
     zrnsaigaitkyksyokusyucd ,         /* （連携用）災害特約職種コード */
     zrnsykgycd ,         /* （連携用）職業コード */
     zrntoukeiyousinsakbn ,         /* （連携用）統計用診査区分 */
     zrngassansrank ,         /* （連携用）合算Ｓランク */
     zrntoliplhyj ,         /* （連携用）ＴＯＬＩＰＬ表示 */
     zrnpmenhukakbn ,         /* （連携用）Ｐ免付加区分 */
     zrnpmenkbnv2 ,         /* （連携用）Ｐ免区分Ｖ２ */
     zrnketteikijyunkanwakbn ,         /* （連携用）決定基準緩和区分 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrntokuyakusedaikbn ,         /* （連携用）特約世代区分 */
     zrnsiharainissuukbn ,         /* （連携用）支払日数区分 */
     zrnkakuseikatakbn ,         /* （連携用）カク成型区分 */
     zrnbosyuukeirokbn ,         /* （連携用）募集経路区分 */
     zrndantaicd ,         /* （連携用）団体コード */
     zrnpmenhutanpohyj ,         /* （連携用）Ｐ免不担保表示 */
     zrntenkanhosyouminaosikbn ,         /* （連携用）転換保障見直区分 */
     zrnhosyouminaosikaisuu ,         /* （連携用）保障見直回数 */
     zrnqpackhyj ,         /* （連携用）Ｑパック表示 */
     zrnbunkatukbn ,         /* （連携用）分割区分 */
     zrnstdssnskbn ,         /* （連携用）外出診査区分 */
     zrnstdssytikbn ,         /* （連携用）外出集定区分 */
     zrnhosyoukikankbn ,         /* （連携用）保障期間区分 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrnbosyuukeitaikbn ,         /* （連携用）募集形態区分 */
     zrndakuhikettisyacd ,         /* （連携用）諾否決定者コード */
     zrntokuyakukikan ,         /* （連携用）特約期間 */
     zrnmannenreihyj ,         /* （連携用）満年令表示 */
     zrnhhknnentysihyj ,         /* （連携用）被保険者年令調整表示 */
     zrnkousinkbn ,         /* （連携用）更新区分 */
     zrnhokenhoutekiyouhyouji ,         /* （連携用）保険法適用表示 */
     zrnsotodasiphkbnmnoshyouji ,         /* （連携用）外出Ｐ不可分見直表示 */
     zrntokuteijyoutaihushrhyj ,         /* （連携用）特定状態不支払表示 */
     zrnrendouyousntkjyubbnhyj ,         /* （連携用）連動用新特条部分表示 */
     zrnmusentakukeiyakukbn ,         /* （連携用）無選択契約区分 */
     zrnknkuzusnzyrttekitkarihyj ,         /* （連携用）健康増進乗率適用特約有表示 */
     zrnbluekeizokuhyouji ,         /* （連携用）Ｂｌｕｅ継続表示 */
     zrnzyrthntiyustatuskbn ,         /* （連携用）乗率判定用ステータス区分 */
     zrnzyrthntiyustatuskbnx2 ,         /* （連携用）乗率判定用ステータス区分＿２ */
     zrnzyrthntiyustatuskbnx3 ,         /* （連携用）乗率判定用ステータス区分＿３ */
     zrnzyrthntiyustatuskbnx4 ,         /* （連携用）乗率判定用ステータス区分＿４ */
     zrnzyrthntiyustatuskbnx5 ,         /* （連携用）乗率判定用ステータス区分＿５ */
     zrnknkuzusnzyrt ,         /* （連携用）健康増進乗率 */
     zrnknkuzusnzyrtx2 ,         /* （連携用）健康増進乗率＿２ */
     zrnpwrbksidhitekiyouhyj ,         /* （連携用）保険料割引制度非適用表示 */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrndatakanrino2 ,         /* （連携用）データ管理番号２ */
     zrndatakanrino3 ,         /* （連携用）データ管理番号３ */
     zrnsinkeiyakujivithkhyouji ,         /* （連携用）新契約時Ｖｉｔ保険表示 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnsuuriyouyobin4 ,         /* （連携用）数理用予備項目Ｎ４ */
     zrnyobin11x3 ,         /* （連携用）予備項目Ｎ１１＿３ */
     zrnraysystemhyj ,         /* （連携用）ＲＡＹシステム表示 */
     zrngaikakbn ,         /* （連携用）外貨区分 */
     zrnkawaserate ,         /* （連携用）為替レート */
     zrnkawaseratetekiyouymd ,         /* （連携用）為替レート適用年月日 */
     zrnkeiyakujiyoteiriritu ,         /* （連携用）契約時予定利率 */
     zrngaikadatetokuyakus ,         /* （連携用）外貨建特約Ｓ */
     zrngaikadatesyukeiyakus ,         /* （連携用）外貨建主契約Ｓ */
     zrngaikadatesyukeiyakup ,         /* （連携用）外貨建主契約Ｐ */
     zrnenkdtsbujsitihsyukngk ,         /* （連携用）円貨建死亡時最低保証金額 */
     zrnsuuriyouyobin10x2 ,         /* （連携用）数理用予備項目Ｎ１０＿２ */
     zrnyobiv10x3 ,         /* （連携用）予備項目Ｖ１０＿３ */
     zrnmvatyouseigow ,         /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn ,         /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnyobin11x6           /* （連携用）予備項目Ｎ１１＿６ */
FROM ZT_JigyounndsikiTkHoyuuRn_Z;