CREATE VIEW IT_BAK_KykSyouhnRireki AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     trkssikibetukey ,         /* 取消識別キー */
     syutkkbn ,         /* 主契約特約区分 */
     syouhncd ,         /* 商品コード */
     syouhnsdno ,         /* 商品世代番号 */
     kyksyouhnrenno ,         /* 契約商品連番 */
     henkousikibetukey ,         /* 変更識別キー */
     yuukousyoumetukbn ,         /* 有効消滅区分 */
     kykjyoutai ,         /* 契約状態 */
     syoumetujiyuu ,         /* 消滅事由 */
     syoumetuymd ,         /* 消滅日 */
     kouryokuhasseiymd ,         /* 効力発生日 */
     kykymd ,         /* 契約日 */
     kykymdsiteiumukbn ,         /* 契約日指定有無区分 */
     sknnkaisiymd ,         /* 責任開始日 */
     gansknnkaisiymd ,         /* がん責任開始日 */
     hksknnkaisiymd ,         /* 復活責任開始日 */
     hkgansknnkaisiymd ,         /* 復活がん責任開始日 */
     hknkknsmnkbn ,         /* 保険期間歳満期区分 */
     hknkkn ,         /* 保険期間 */
     hrkkknsmnkbn ,         /* 払込期間歳満期区分 */
     hrkkkn ,         /* 払込期間 */
     kyknen ,         /* 契約者年齢 */
     hhknnen ,         /* 被保険者年齢 */
     hhknseiymd ,         /* 被保険者生年月日 */
     hhknsei ,         /* 被保険者性別 */
     haraimanymd ,         /* 払満日 */
     hknkknmanryouymd ,         /* 保険期間満了日 */
     katakbn ,         /* 型区分 */
     kyhgndkatakbn ,         /* 給付限度型区分 */
     syukyhkinkatakbn ,         /* 手術給付金型区分 */
     khnkyhkgbairitukbn ,         /* 基本給付金額倍率区分 */
     rokudaildkbn ,         /* ６大生活習慣病追加給付型区分 */
     pmnjtkkbn ,         /* 保険料免除特約区分 */
     kihons ,         /* 基本Ｓ */
     kihons$ ,         /* 基本Ｓ(通貨型) */
     hokenryou ,         /* 保険料 */
     hokenryou$ ,         /* 保険料(通貨型) */
     kyktuukasyu ,         /* 契約通貨種類 */
     ryouritusdno ,         /* 料率世代番号 */
     yoteiriritu ,         /* 予定利率 */
     yoteirrthendohosyurrt ,         /* 予定利率変動時保証利率 */
     ytirrthndmnskaisuu ,         /* 予定利率変動見直回数 */
     kyksjkkktyouseiriritu ,         /* 契約時市場価格調整用利率 */
     nksyukbn ,         /* 年金種類区分 */
     nenkinkkn ,         /* 年金期間 */
     nkgnshosyouritu ,         /* 年金原資最低保証率 */
     nkgnshosyougk ,         /* 年金原資最低保証額 */
     nkgnshosyougk$ ,         /* 年金原資最低保証額(通貨型) */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     gengakugoyenitijibrpstgk ,         /* 減額後円換算一時払保険料相当額 */
     gengakugoyenitijibrpstgk$ ,         /* 減額後円換算一時払保険料相当額(通貨型) */
     yendthnkymd ,         /* 円建変更日 */
     setteibairitu ,         /* 設定倍率 */
     kykjisisuurendourate ,         /* 契約時指数連動部分割合 */
     tmttknzoukaritujygn ,         /* 積立金増加率上限 */
     tumitateriritu ,         /* 積立利率 */
     tmttknhaibunjyoutai ,         /* 積立金配分状態 */
     sisuukbn ,         /* 指数区分 */
     gsbunrikzkakuninumu ,         /* 源泉分離課税確認有無 */
     gsbunritaisyou ,         /* 源泉分離課税対象 */
     pharaikomisougaku ,         /* 保険料払込総額 */
     pharaikomisougaku$ ,         /* 保険料払込総額(通貨型) */
     tmttknitenymd ,         /* 積立金移転日 */
     loadinghnkgtumitateriritu ,         /* ローディング変更後積立利率 */
     rendouritu ,         /* 連動率 */
     teikishrritu ,         /* 定期支払率 */
     dai1hknkkn           /* 第１保険期間 */
FROM IT_BAK_KykSyouhnRireki_Z;