CREATE VIEW IT_KijituTouraiAnnai AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     tyouhyouymd ,         /* 帳票作成日 */
     shskyno ,         /* 送付先郵便番号 */
     shsadr1kj ,         /* 送付先住所１（漢字）（３０桁） */
     shsadr2kj ,         /* 送付先住所２（漢字）（３０桁） */
     shsadr3kj ,         /* 送付先住所３（漢字）（３０桁） */
     shsnmkj ,         /* 送付先氏名（漢字） */
     toiawasesosikinmkj ,         /* 問合せ先組織名（漢字） */
     toiawaseyno ,         /* 問合せ先郵便番号 */
     toiawaseadr1kj ,         /* 問合せ先住所１（漢字） */
     toiawaseadr2kj ,         /* 問合せ先住所２（漢字） */
     toiawaseadr3kj ,         /* 問合せ先住所３（漢字） */
     toiawasetelno ,         /* 問合せ先電話番号 */
     toiawaseteluktkkanou1 ,         /* 問合せ先電話受付可能時間１ */
     toiawaseteluktkkanou2 ,         /* 問合せ先電話受付可能時間２ */
     toiawasesosikinmkj2 ,         /* 第２問合せ先組織名（漢字） */
     toiawasetelno2 ,         /* 第２問合せ先電話番号 */
     tuutinm20keta ,         /* 通知名称（２０桁） */
     hrkykkmsg32keta1 ,         /* 振替予告メッセージ（３２桁）１ */
     hrkykkmsg32keta2 ,         /* 振替予告メッセージ（３２桁）２ */
     hrkykkmsg32keta3 ,         /* 振替予告メッセージ（３２桁）３ */
     hrkykkmsg32keta4 ,         /* 振替予告メッセージ（３２桁）４ */
     hrkykkmsg32keta5 ,         /* 振替予告メッセージ（３２桁）５ */
     hrkykkmsg32keta6 ,         /* 振替予告メッセージ（３２桁）６ */
     hrkykkmsg32keta7 ,         /* 振替予告メッセージ（３２桁）７ */
     hrkykkmsg32keta8 ,         /* 振替予告メッセージ（３２桁）８ */
     hrkkeiro ,         /* 払込経路 */
     syouhnnm ,         /* 商品名 */
     kykymd ,         /* 契約日 */
     hhknnmkj ,         /* 被保険者名（漢字） */
     kjttrnnfreearea1 ,         /* 期日到来案内フリーエリア１ */
     kjttrnnfreearea2 ,         /* 期日到来案内フリーエリア２ */
     kjttrnnfreearea3 ,         /* 期日到来案内フリーエリア３ */
     kjttrnnfreearea4 ,         /* 期日到来案内フリーエリア４ */
     kjttrnnfreearea5 ,         /* 期日到来案内フリーエリア５ */
     kjttrnnfreearea6 ,         /* 期日到来案内フリーエリア６ */
     kjttrnnfreearea7 ,         /* 期日到来案内フリーエリア７ */
     hurikaeymd ,         /* 振替日 */
     kzinfo1 ,         /* 口座情報１ */
     kzinfo2 ,         /* 口座情報２ */
     kzinfo3 ,         /* 口座情報３ */
     kzinfo4 ,         /* 口座情報４ */
     kzinfo5 ,         /* 口座情報５ */
     kzinfo6 ,         /* 口座情報６ */
     kzinfo7 ,         /* 口座情報７ */
     kzinfo8 ,         /* 口座情報８ */
     hknjytukikan ,         /* 保険充当期間 */
     hrkgk1 ,         /* 払込金額１ */
     hrkgk2 ,         /* 払込金額２ */
     hrkgk3 ,         /* 払込金額３ */
     hrkgk4 ,         /* 払込金額４ */
     kjttrnnfreearea8 ,         /* 期日到来案内フリーエリア８ */
     kjttrnnfreearea9 ,         /* 期日到来案内フリーエリア９ */
     kjttrnnfreearea10 ,         /* 期日到来案内フリーエリア１０ */
     kjttrnnfreearea11 ,         /* 期日到来案内フリーエリア１１ */
     kjttrnnfreearea12 ,         /* 期日到来案内フリーエリア１２ */
     kjttrnnfreearea13 ,         /* 期日到来案内フリーエリア１３ */
     syoruiCd ,         /* 書類コード */
     hassoukbn ,         /* 発送区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_KijituTouraiAnnai_Z;