CREATE VIEW ZT_HonsyaToukeiRn AS SELECT
     zrnkijyunym ,         /* （連携用）基準年月 */
     zrnmosym ,         /* （連携用）申込月度 */
     zrnmosno ,         /* （連携用）申込番号 */
     zrnsosikicd ,         /* （連携用）組織コード */
     zrnmossyoumetukbn ,         /* （連携用）申込消滅区分 */
     zrnmossyumtkktymd ,         /* （連携用）申込消滅確定年月日 */
     zrnrenseihhknkbn ,         /* （連携用）連生被保険者区分 */
     zrndakuhikettikekkacd ,         /* （連携用）諾否決定結果コード */
     zrndkhktiymd ,         /* （連携用）諾否決定年月日 */
     zrnketkbn ,         /* （連携用）決定区分 */
     zrntoukeihknsyruikbn ,         /* （連携用）統計用保険種類区分 */
     zrnhhknnen2keta ,         /* （連携用）被保険者年令（２桁） */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhjykktkbn ,         /* （連携用）報状告知区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnryouritukbn ,         /* （連携用）料率区分 */
     zrndakuhikts ,         /* （連携用）諾否決定Ｓ */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnhhkndaisansyakykkbn ,         /* （連携用）被保険者第三者契約区分 */
     zrndainisentakuinfokakjkkbn ,         /* （連携用）第２選択情報確認状況区分 */
     zrnmusymd ,         /* （連携用）申込年月日 */
     zrnryousyuuymd ,         /* （連携用）領収年月日 */
     zrnkokutiymd ,         /* （連携用）告知年月日 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnseikeirenrakuymd ,         /* （連携用）成契連絡年月日 */
     zrnnyknnyuuryokuymd ,         /* （連携用）入金入力年月日 */
     zrnsisyaketnyuuryokuymd ,         /* （連携用）支社決定入力年月日 */
     zrnkykkakiraiymd ,         /* （連携用）契約確認依頼年月日 */
     zrnkeiyakukakuninsyuruikbn ,         /* （連携用）契約確認種類区分 */
     zrnsiteidairikbn2 ,         /* （連携用）指定代理人区分（２文字） */
     zrnkykkakjkkbn1 ,         /* （連携用）契約確認状況区分（１文字） */
     zrnkykkakkanryouymd ,         /* （連携用）契約確認完了年月日 */
     zrnkykkakketymd ,         /* （連携用）契約確認決定年月日 */
     zrnkykkakketkekkakbn ,         /* （連携用）契約確認決定結果区分 */
     zrnkykkaktantoukojincd ,         /* （連携用）契約確認担当者個人コード */
     zrnketsyacd ,         /* （連携用）決定者コード */
     zrnsyosakuseiymd ,         /* （連携用）証券作成年月日 */
     zrnseisekiym ,         /* （連携用）成績計上年月 */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrnsyokaiharaikomip ,         /* （連携用）初回払込Ｐ */
     zrnmossyosakuseiymd ,         /* （連携用）申込書作成年月日 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrndakuhiketteiriyuucdx1 ,         /* （連携用）諾否決定理由コード＿１ */
     zrndakuhiketteiriyuucdx2 ,         /* （連携用）諾否決定理由コード＿２ */
     zrndakuhiketteiriyuucdx3 ,         /* （連携用）諾否決定理由コード＿３ */
     zrndakuhiketteiriyuucdx4 ,         /* （連携用）諾否決定理由コード＿４ */
     zrnhenkouteiseisyorikaisuu ,         /* （連携用）変更訂正処理回数 */
     zrnsyosisyatodokekibouhyj ,         /* （連携用）証券支社届希望表示 */
     zrnhndketkaisuu ,         /* （連携用）ハンド決定回数 */
     zrndakuhiketkeiikekkacd1 ,         /* （連携用）諾否決定経緯結果コード１ */
     zrndakuhiketkeiiketmd1 ,         /* （連携用）諾否決定経緯決定月日１ */
     zrndakuhiketkeiikekkacd2 ,         /* （連携用）諾否決定経緯結果コード２ */
     zrndakuhiketkeiiketmd2 ,         /* （連携用）諾否決定経緯決定月日２ */
     zrndakuhiketkeiikekkacd3 ,         /* （連携用）諾否決定経緯結果コード３ */
     zrndakuhiketkeiiketmd3 ,         /* （連携用）諾否決定経緯決定月日３ */
     zrndakuhiketkeiikekkacd4 ,         /* （連携用）諾否決定経緯結果コード４ */
     zrndakuhiketkeiiketmd4 ,         /* （連携用）諾否決定経緯決定月日４ */
     zrndakuhiketkeiikekkacd5 ,         /* （連携用）諾否決定経緯結果コード５ */
     zrndakuhiketkeiiketmd5 ,         /* （連携用）諾否決定経緯決定月日５ */
     zrndakuhiketkeiikekkacd6 ,         /* （連携用）諾否決定経緯結果コード６ */
     zrndakuhiketkeiiketmd6 ,         /* （連携用）諾否決定経緯決定月日６ */
     zrnkojincd ,         /* （連携用）個人コード */
     zrnsyokaipnyuukinhouhoukbn ,         /* （連携用）初回Ｐ入金方法区分 */
     zrnsentakuinfoumuhyj ,         /* （連携用）選択情報有無表示 */
     zrnhaitousiharaikbn ,         /* （連携用）配当支払区分 */
     zrnhonsyatkkohojyunhsys ,         /* （連携用）本社統計個保純保障Ｓ */
     zrntoukeiyousinsakbn ,         /* （連携用）統計用診査区分 */
     zrnsknnkaisiymd ,         /* （連携用）責任開始日 */
     zrnbsudirtnatkikeitaikbn ,         /* （連携用）募集代理店扱形態区分 */
     zrnhhknsynensyuukbn ,         /* （連携用）被保険者年収区分 */
     zrntokusyujimutoriatukaikbn ,         /* （連携用）特殊事務取扱区分 */
     zrninputmissteiseikaisuu ,         /* （連携用）インプットミス訂正処理回数 */
     zrnkjkyknm ,         /* （連携用）漢字契約者名 */
     zrnknjhhknmei ,         /* （連携用）漢字被保険者名 */
     zrnhonninkknnkbn ,         /* （連携用）本人確認区分 */
     zrnnyknzumihyouji ,         /* （連携用）入金済表示 */
     zrnhhknsykgycd ,         /* （連携用）被保険者職業コード */
     zrnnyknjkkbn ,         /* （連携用）入金状況区分 */
     zrnbatukaisyakojincd ,         /* （連携用）Ｂ扱者個人コード */
     zrnsinfstpnyknhouhoukbn ,         /* （連携用）新初回Ｐ入金方法区分 */
     zrnmostorikesikbn ,         /* （連携用）申込取消区分 */
     zrnmostrkssyousairiyuukbn ,         /* （連携用）申込取消詳細理由区分 */
     zrnmossakuseino ,         /* （連携用）申込書作成番号 */
     zrnsibous ,         /* （連携用）死亡Ｓ */
     zrnharaikomip ,         /* （連携用）払込Ｐ */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnkyknm ,         /* （連携用）契約者名 */
     zrnkyktdkkbn ,         /* （連携用）契約者続柄区分 */
     zrnkyksyanen ,         /* （連携用）契約者年令 */
     zrnkyksyaseikbn ,         /* （連携用）契約者性別区分 */
     zrnmosjihonninkknnkbn ,         /* （連携用）申込時本人確認区分 */
     zrnhhknmei ,         /* （連携用）被保険者名 */
     zrnsbuktkbn ,         /* （連携用）死亡受取人区分 */
     zrnkjsbuktnm ,         /* （連携用）漢字死亡受取人名 */
     zrnsbuktnm ,         /* （連携用）死亡受取人名 */
     zrnsbuktseiymd ,         /* （連携用）死亡受取人生年月日 */
     zrnsbukttdkkbn ,         /* （連携用）死亡受取人続柄区分 */
     zrnkjsiteidairininnm ,         /* （連携用）漢字指定代理人名 */
     zrnsiteidairininnm ,         /* （連携用）指定代理人名 */
     zrnfatcakakkekkakbn ,         /* （連携用）ＦＡＴＣＡ確認結果区分 */
     zrnfatcamosjikakkokusekikbn ,         /* （連携用）ＦＡＴＣＡ申込時確認国籍区分 */
     zrnfatcatorjikakkokusekikbn ,         /* （連携用）ＦＡＴＣＡ取引時確認国籍区分 */
     zrnkzkakiraikbn ,         /* （連携用）口座確認依頼区分 */
     zrnkzkakiraiymd ,         /* （連携用）口座確認依頼年月日 */
     zrnbankyohurikzhyouji ,         /* （連携用）銀行預振口座表示 */
     zrnkzmeigikakuninzumikbn ,         /* （連携用）口座名義人確認済区分 */
     zrnznnkai ,         /* （連携用）前納回数 */
     zrnkzktrkservicekbn ,         /* （連携用）ご家族登録サービス区分 */
     zrnkykdrkbn ,         /* （連携用）契約者代理人区分 */
     zrnkjkykdairinm ,         /* （連携用）漢字契約者代理人名 */
     zrnkykdairinm ,         /* （連携用）契約者代理人名 */
     zrntrkkzktdk1keta1 ,         /* （連携用）登録家族続柄１（１桁） */
     zrnkjkzktourokunm1 ,         /* （連携用）漢字家族登録名１ */
     zrnkzktourokunm1 ,         /* （連携用）家族登録名１ */
     zrntrkkzktdk2keta1 ,         /* （連携用）登録家族続柄２（１桁） */
     zrnkjkzktourokunm2 ,         /* （連携用）漢字家族登録名２ */
     zrnkzktourokunm2 ,         /* （連携用）家族登録名２ */
     zrnyakkanjyuryouhoukbn ,         /* （連携用）約款受領方法区分 */
     zrnyakkanbunsyono ,         /* （連携用）約款文書番号 */
     zrnyobiv250 ,         /* （連携用）予備項目Ｖ２５０ */
     zrnyobiv28           /* （連携用）予備項目Ｖ２８ */
FROM ZT_HonsyaToukeiRn_Z;