CREATE VIEW IT_KouzahuriMinyuTuuti AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     tyouhyouymd ,         /* 帳票作成日 */
     syoruiCd ,         /* 書類コード */
     hassoukbn ,         /* 発送区分 */
     shskyno ,         /* 送付先郵便番号 */
     shsadr1kj ,         /* 送付先住所１（漢字）（３０桁） */
     shsadr2kj ,         /* 送付先住所２（漢字）（３０桁） */
     shsadr3kj ,         /* 送付先住所３（漢字）（３０桁） */
     shsnmkj ,         /* 送付先氏名（漢字） */
     toiawasesosikinmkj ,         /* 問合せ先組織名（漢字） */
     toiawaseyno ,         /* 問合せ先郵便番号 */
     toiawaseadr1kj ,         /* 問合せ先住所１（漢字） */
     toiawaseadr2kj ,         /* 問合せ先住所２（漢字） */
     toiawaseadr3kj ,         /* 問合せ先住所３（漢字） */
     toiawasetelno ,         /* 問合せ先電話番号 */
     toiawaseteluktkkanou1 ,         /* 問合せ先電話受付可能時間１ */
     toiawaseteluktkkanou2 ,         /* 問合せ先電話受付可能時間２ */
     toiawasesosikinmkj2 ,         /* 第２問合せ先組織名（漢字） */
     toiawasetelno2 ,         /* 第２問合せ先電話番号 */
     tuutinm30keta ,         /* 通知名称（３０桁） */
     minyuttmsg1 ,         /* 未入通知メッセージ１ */
     minyuttmsg2 ,         /* 未入通知メッセージ２ */
     minyuttmsg3 ,         /* 未入通知メッセージ３ */
     minyuttmsg4 ,         /* 未入通知メッセージ４ */
     minyuttmsg5 ,         /* 未入通知メッセージ５ */
     minyuttmsg6 ,         /* 未入通知メッセージ６ */
     minyuttmsg7 ,         /* 未入通知メッセージ７ */
     minyuttmsg8 ,         /* 未入通知メッセージ８ */
     minyuttmsg9 ,         /* 未入通知メッセージ９ */
     minyuttmsg10 ,         /* 未入通知メッセージ１０ */
     minyuttmsg11 ,         /* 未入通知メッセージ１１ */
     minyuttmsg12 ,         /* 未入通知メッセージ１２ */
     pannainm ,         /* 保険料案内名称 */
     hrkhou12keta ,         /* 払込方法（１２桁） */
     hhknnmkj ,         /* 被保険者名（漢字） */
     nexthurikaenaiyou1 ,         /* 次回振替内容１ */
     nexthurikaenaiyou2 ,         /* 次回振替内容２ */
     nexthurikaenaiyou3 ,         /* 次回振替内容３ */
     saikokutukiyykkn1 ,         /* 催告月猶予期間１ */
     saikokutukiyykkn2 ,         /* 催告月猶予期間２ */
     hrkmirmsg1 ,         /* 振込依頼メッセージ１ */
     hrkmirmsg2 ,         /* 振込依頼メッセージ２ */
     hrkmirmsg3 ,         /* 振込依頼メッセージ３ */
     zenhurikaenaiyou1 ,         /* 前回振替内容１ */
     zenhurikaenaiyou2 ,         /* 前回振替内容２ */
     zenhurikaenaiyou3 ,         /* 前回振替内容３ */
     zenhurikaenaiyou4 ,         /* 前回振替内容４ */
     hurikaekz37keta1 ,         /* 振替口座（３７桁）１ */
     hurikaekz37keta2 ,         /* 振替口座（３７桁）２ */
     hurikaekz37keta3 ,         /* 振替口座（３７桁）３ */
     hurikaekz37keta4 ,         /* 振替口座（３７桁）４ */
     hurikaekz37keta5 ,         /* 振替口座（３７桁）５ */
     hurikaekz37keta6 ,         /* 振替口座（３７桁）６ */
     minyuttaddmsg1 ,         /* 未入通知追加メッセージ１ */
     minyuttaddmsg2 ,         /* 未入通知追加メッセージ２ */
     minyuttaddmsg3 ,         /* 未入通知追加メッセージ３ */
     minyuttaddmsg4 ,         /* 未入通知追加メッセージ４ */
     minyuttaddmsg5 ,         /* 未入通知追加メッセージ５ */
     minyuttaddmsg6 ,         /* 未入通知追加メッセージ６ */
     minyuttaddmsg7 ,         /* 未入通知追加メッセージ７ */
     minyuttaddmsg8 ,         /* 未入通知追加メッセージ８ */
     minyuttaddmsg9 ,         /* 未入通知追加メッセージ９ */
     minyuttaddmsg10 ,         /* 未入通知追加メッセージ１０ */
     minyuttaddmsg11 ,         /* 未入通知追加メッセージ１１ */
     minyuttaddmsg12 ,         /* 未入通知追加メッセージ１２ */
     minyuttaddmsg13 ,         /* 未入通知追加メッセージ１３ */
     minyuttaddmsg14 ,         /* 未入通知追加メッセージ１４ */
     minyuttaddmsg15 ,         /* 未入通知追加メッセージ１５ */
     minyuttaddmsg16 ,         /* 未入通知追加メッセージ１６ */
     minyuttaddmsg17 ,         /* 未入通知追加メッセージ１７ */
     minyuttaddmsg18 ,         /* 未入通知追加メッセージ１８ */
     minyuttaddmsg19 ,         /* 未入通知追加メッセージ１９ */
     minyuttaddmsg20 ,         /* 未入通知追加メッセージ２０ */
     minyuttaddmsg21 ,         /* 未入通知追加メッセージ２１ */
     tuutisyuruicd ,         /* 通知種類コード */
     saikokutuutizumiflg ,         /* 催告通知作成済フラグ */
     tyouhyoukigoukbn ,         /* 帳票記号区分 */
     hrkkeiro ,         /* 払込経路 */
     jkipjytym ,         /* 次回Ｐ充当年月 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_KouzahuriMinyuTuuti_Z;