CREATE VIEW ZT_KouzahuriMinyuTuutiTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztytyouhyouymdkj ,         /* （中継用）帳票作成日（漢字） */
     ztysyono ,         /* （中継用）証券番号 */
     ztyyobiv9 ,         /* （中継用）予備項目Ｖ９ */
     ztyansyuyouyobin10 ,         /* （中継用）案内収納用予備項目Ｎ１０ */
     ztyshskyno ,         /* （中継用）送付先郵便番号 */
     ztyshskadr1kj ,         /* （中継用）送付先住所１（漢字） */
     ztyshskadr2kj ,         /* （中継用）送付先住所２（漢字） */
     ztyshskadr3kj ,         /* （中継用）送付先住所３（漢字） */
     ztyshsnmkj ,         /* （中継用）送付先名（漢字） */
     ztyyobiv43 ,         /* （中継用）予備項目Ｖ４３ */
     ztyansyuyouyobin10x2 ,         /* （中継用）案内収納用予備項目Ｎ１０＿２ */
     ztytawsosikikj ,         /* （中継用）問合せ先組織名（漢字） */
     ztytawyno ,         /* （中継用）問合せ先郵便番号 */
     ztytawadr1kj ,         /* （中継用）問合せ先住所１（漢字） */
     ztytawadr2kj ,         /* （中継用）問合せ先住所２（漢字） */
     ztytawadr3kj ,         /* （中継用）問合せ先住所３（漢字） */
     ztytawtelnov14 ,         /* （中継用）問合せ先電話番号Ｖ１４ */
     ztytawteluktkkanou1 ,         /* （中継用）問合せ先電話受付可能時間１ */
     ztytawteluktkkanou2 ,         /* （中継用）問合せ先電話受付可能時間２ */
     ztydai2tawsosikinmkj ,         /* （中継用）第２問合せ先組織名（漢字） */
     ztydai2tawtelno ,         /* （中継用）第２問合せ先電話番号 */
     ztysclatosyono ,         /* （中継用）スクランブル後証券番号 */
     ztysakunm15keta ,         /* （中継用）作成番号（１５桁） */
     ztyyobiv61 ,         /* （中継用）予備項目Ｖ６１ */
     ztyansyuyouyobin10x3 ,         /* （中継用）案内収納用予備項目Ｎ１０＿３ */
     ztytuutinm30keta ,         /* （中継用）通知名称（３０桁） */
     ztyminyuttmsg1 ,         /* （中継用）未入通知メッセージ１ */
     ztyminyuttmsg2 ,         /* （中継用）未入通知メッセージ２ */
     ztyminyuttmsg3 ,         /* （中継用）未入通知メッセージ３ */
     ztyminyuttmsg4 ,         /* （中継用）未入通知メッセージ４ */
     ztyminyuttmsg5 ,         /* （中継用）未入通知メッセージ５ */
     ztyminyuttmsg6 ,         /* （中継用）未入通知メッセージ６ */
     ztyminyuttmsg7 ,         /* （中継用）未入通知メッセージ７ */
     ztyminyuttmsg8 ,         /* （中継用）未入通知メッセージ８ */
     ztyminyuttmsg9 ,         /* （中継用）未入通知メッセージ９ */
     ztyminyuttmsg10 ,         /* （中継用）未入通知メッセージ１０ */
     ztyminyuttmsg11 ,         /* （中継用）未入通知メッセージ１１ */
     ztyminyuttmsg12 ,         /* （中継用）未入通知メッセージ１２ */
     ztyyobiv174 ,         /* （中継用）予備項目Ｖ１７４ */
     ztyansyuyouyobin10x4 ,         /* （中継用）案内収納用予備項目Ｎ１０＿４ */
     ztypannainm ,         /* （中継用）保険料案内名称 */
     ztyhrkhou12keta ,         /* （中継用）払込方法（１２桁） */
     ztysyono2 ,         /* （中継用）証券番号２ */
     ztyhhknnmkj ,         /* （中継用）被保険者名（漢字） */
     ztynextkzhrnaiyou1 ,         /* （中継用）次回振替内容１ */
     ztynextkzhrnaiyou2 ,         /* （中継用）次回振替内容２ */
     ztynextkzhrnaiyou3 ,         /* （中継用）次回振替内容３ */
     ztysaikokuyykk1 ,         /* （中継用）催告月猶予期間１ */
     ztysaikokuyykk2 ,         /* （中継用）催告月猶予期間２ */
     ztyhrkmiraimsg1 ,         /* （中継用）振込依頼メッセージ１ */
     ztyhrkmiraimsg2 ,         /* （中継用）振込依頼メッセージ２ */
     ztyhrkmiraimsg3 ,         /* （中継用）振込依頼メッセージ３ */
     ztyzenhurinaiyou1 ,         /* （中継用）前回振替内容１ */
     ztyzenhurinaiyou2 ,         /* （中継用）前回振替内容２ */
     ztyzenhurinaiyou3 ,         /* （中継用）前回振替内容３ */
     ztyzenhurinaiyou4 ,         /* （中継用）前回振替内容４ */
     ztyyobiv196 ,         /* （中継用）予備項目Ｖ１９６ */
     ztyansyuyouyobin10x5 ,         /* （中継用）案内収納用予備項目Ｎ１０＿５ */
     ztyhurikaekz37keta1 ,         /* （中継用）振替口座（３７桁）１ */
     ztyhurikaekz37keta2 ,         /* （中継用）振替口座（３７桁）２ */
     ztyhurikaekz37keta3 ,         /* （中継用）振替口座（３７桁）３ */
     ztyhurikaekz37keta4 ,         /* （中継用）振替口座（３７桁）４ */
     ztyhurikaekz37keta5 ,         /* （中継用）振替口座（３７桁）５ */
     ztyhurikaekz37keta6 ,         /* （中継用）振替口座（３７桁）６ */
     ztyyobiv88 ,         /* （中継用）予備項目Ｖ８８ */
     ztyansyuyouyobin10x6 ,         /* （中継用）案内収納用予備項目Ｎ１０＿６ */
     ztyminyuttaddmsg1 ,         /* （中継用）未入通知追加メッセージ１ */
     ztyminyuttaddmsg2 ,         /* （中継用）未入通知追加メッセージ２ */
     ztyminyuttaddmsg3 ,         /* （中継用）未入通知追加メッセージ３ */
     ztyminyuttaddmsg4 ,         /* （中継用）未入通知追加メッセージ４ */
     ztyminyuttaddmsg5 ,         /* （中継用）未入通知追加メッセージ５ */
     ztyminyuttaddmsg6 ,         /* （中継用）未入通知追加メッセージ６ */
     ztyminyuttaddmsg7 ,         /* （中継用）未入通知追加メッセージ７ */
     ztyminyuttaddmsg8 ,         /* （中継用）未入通知追加メッセージ８ */
     ztyminyuttaddmsg9 ,         /* （中継用）未入通知追加メッセージ９ */
     ztyminyuttaddmsg10 ,         /* （中継用）未入通知追加メッセージ１０ */
     ztyminyuttaddmsg11 ,         /* （中継用）未入通知追加メッセージ１１ */
     ztyminyuttaddmsg12 ,         /* （中継用）未入通知追加メッセージ１２ */
     ztyminyuttaddmsg13 ,         /* （中継用）未入通知追加メッセージ１３ */
     ztyminyuttaddmsg14 ,         /* （中継用）未入通知追加メッセージ１４ */
     ztyminyuttaddmsg15 ,         /* （中継用）未入通知追加メッセージ１５ */
     ztyminyuttaddmsg16 ,         /* （中継用）未入通知追加メッセージ１６ */
     ztyminyuttaddmsg17 ,         /* （中継用）未入通知追加メッセージ１７ */
     ztyminyuttaddmsg18 ,         /* （中継用）未入通知追加メッセージ１８ */
     ztyminyuttaddmsg19 ,         /* （中継用）未入通知追加メッセージ１９ */
     ztyminyuttaddmsg20 ,         /* （中継用）未入通知追加メッセージ２０ */
     ztyminyuttaddmsg21 ,         /* （中継用）未入通知追加メッセージ２１ */
     ztyyobiv250 ,         /* （中継用）予備項目Ｖ２５０ */
     ztyyobiv60 ,         /* （中継用）予備項目Ｖ６０ */
     ztyansyuyouyobin10x7 ,         /* （中継用）案内収納用予備項目Ｎ１０＿７ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_KouzahuriMinyuTuutiTy_Z;