CREATE VIEW IT_KhBikinkanri AS SELECT
     syono ,         /* 証券番号 */
     kessankijyunymd ,         /* 決算基準日 */
     bkncdkbn ,         /* 備金コード区分 */
     bknkktymd ,         /* 備金確定日 */
     renno ,         /* 連番 */
     bknrigikbn ,         /* 備金例外区分 */
     henkousikibetukey ,         /* 変更識別キー */
     calckijyunymd ,         /* 計算基準日 */
     sisyacd ,         /* 支社コード */
     kbnkeirisegcd ,         /* 区分経理用セグメントコード */
     syouhncd ,         /* 商品コード */
     bknsyutkkbn ,         /* 備金主契約特約区分 */
     bkngk ,         /* 備金額 */
     bkngk$ ,         /* 備金額(通貨型) */
     kihons ,         /* 基本Ｓ */
     kihons$ ,         /* 基本Ｓ(通貨型) */
     gngkkiykumukbn ,         /* 減額特約解約有無区分 */
     shrumu ,         /* 支払有無区分 */
     sinsaumukbn ,         /* 診査有無区分 */
     bknjkukbn ,         /* 備金時効区分 */
     shrsyoriymd ,         /* 支払処理日 */
     tyakkinymd ,         /* 着金日 */
     kyktuukasyu ,         /* 契約通貨種類 */
     shrtuukasyu ,         /* 支払通貨種類 */
     shrgk ,         /* 支払金額 */
     shrgk$ ,         /* 支払金額(通貨型) */
     shrkwsratekjnymd ,         /* 支払時為替レート基準日 */
     shrkwsrate ,         /* 支払時為替レート */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     gaikashrkwsratekjnymd ,         /* 外貨支払時為替レート基準日 */
     gaikashrkwsrate ,         /* 外貨支払時為替レート */
     yenkazennouseisankgk ,         /* 円貨前納精算金額 */
     yenkazennouseisankgk$ ,         /* 円貨前納精算金額(通貨型) */
     gaikazennouseisankgk ,         /* 外貨前納精算金額 */
     gaikazennouseisankgk$ ,         /* 外貨前納精算金額(通貨型) */
     zennouseisankgk ,         /* 前納精算金額 */
     zennouseisankgk$ ,         /* 前納精算金額(通貨型) */
     yenkamikeikap ,         /* 円貨未経過保険料 */
     yenkamikeikap$ ,         /* 円貨未経過保険料(通貨型) */
     gaikamikeikap ,         /* 外貨未経過保険料 */
     gaikamikeikap$ ,         /* 外貨未経過保険料(通貨型) */
     mikeikap ,         /* 未経過保険料 */
     mikeikap$           /* 未経過保険料(通貨型) */
FROM IT_KhBikinkanri_Z;