CREATE VIEW ZT_DrtenIpToukeiTy AS SELECT
     ztyeigyouhonbusisyacd ,         /* （中継用）営業本部支社コード */
     ztysosikicd ,         /* （中継用）組織コード */
     ztyatukaikojincd ,         /* （中継用）扱者個人コード */
     ztymosym ,         /* （中継用）申込月度 */
     ztymoskbn ,         /* （中継用）申込区分 */
     ztytansyukukjatukaisyanm ,         /* （中継用）短縮漢字扱者名 */
     ztymosno ,         /* （中継用）申込番号 */
     ztymossyoumetukbn ,         /* （中継用）申込消滅区分 */
     ztykurikosiriyuukbn ,         /* （中継用）繰越理由区分 */
     ztynyknzumihyouji ,         /* （中継用）入金済表示 */
     ztytoukeihknsyruikbn ,         /* （中継用）統計用保険種類区分 */
     ztyhjykktkbn ,         /* （中継用）報状告知区分 */
     ztykykktaikbn ,         /* （中継用）契約形態区分 */
     ztyjyunhsys ,         /* （中継用）純保障Ｓ */
     ztyhsys ,         /* （中継用）保障Ｓ */
     ztysoukensuu ,         /* （中継用）総件数 */
     ztyketjkkbn ,         /* （中継用）決定状況区分 */
     ztydakuhiktjyoutaikbn ,         /* （中継用）諾否決定状態区分 */
     ztykihonhubi ,         /* （中継用）基本不備 */
     ztysphubi ,         /* （中継用）ＳＰ不備 */
     ztysseigenhubi ,         /* （中継用）Ｓ制限不備 */
     ztynayosehumei ,         /* （中継用）名寄不明 */
     ztytuusangendoover ,         /* （中継用）通算限度オーバー */
     ztymosketteihoryuu ,         /* （中継用）申込決定保留 */
     ztykykkakjissityuu ,         /* （中継用）契約確認実施中 */
     ztykktketteihoryuu ,         /* （中継用）告知決定保留 */
     ztyhonsyakethoryuu ,         /* （中継用）本社決定保留 */
     ztyseiymdhubi ,         /* （中継用）生年月日不備 */
     ztyphusoku ,         /* （中継用）Ｐ不足 */
     ztysrhuketyu ,         /* （中継用）成立保留受付中 */
     ztypkakin ,         /* （中継用）Ｐ過金 */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztysakuseiymd ,         /* （中継用）作成日 */
     ztykydatkikbn ,         /* （中継用）共同扱区分 */
     ztytansyukukjhhknnm ,         /* （中継用）短縮漢字被保険者名 */
     ztyhhknsykgycd ,         /* （中継用）被保険者職業コード */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztymusymd ,         /* （中継用）申込年月日 */
     ztysyokaipryosyuymd ,         /* （中継用）初回Ｐ領収年月日 */
     ztykokutiymd ,         /* （中継用）告知年月日 */
     ztymosnyuuryokuymd ,         /* （中継用）申込入力年月日 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztysekininkaisiymd ,         /* （中継用）責任開始年月日 */
     ztyfstpnyknsyoriymd ,         /* （中継用）初回Ｐ入金処理年月日 */
     ztyfstpnyknnaiyoukbn ,         /* （中継用）初回Ｐ入金内容区分 */
     ztysisyaketsyoriymd ,         /* （中継用）支社決定処理年月日 */
     ztysyosakuseiymd ,         /* （中継用）証券作成年月日 */
     ztyseisekiym ,         /* （中継用）成績計上年月 */
     ztysyokaiharaikomip ,         /* （中継用）初回払込Ｐ */
     ztysyono ,         /* （中継用）証券番号 */
     ztytokusyujimutoriatukaikbn ,         /* （中継用）特殊事務取扱区分 */
     ztybsydrtencd ,         /* （中継用）募集代理店コード */
     ztybsydrtenkjnm ,         /* （中継用）募集代理店漢字名称 */
     ztyatkisyagyskkjsosikicd ,         /* （中継用）扱者業績計上先組織コード */
     ztyatkisyadrtenatkiwari ,         /* （中継用）扱者代理店扱割合 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztykinyuukikancd ,         /* （中継用）金融機関コード */
     ztyinfositencd ,         /* （中継用）（情報系）支店コード */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztykjkyknm10 ,         /* （中継用）漢字契約者名（１０文字） */
     ztykthhbhyouji ,         /* （中継用）決定保留不備表示 */
     ztysrhhbhyouji ,         /* （中継用）成立保留不備表示 */
     ztymossyumtkktymd ,         /* （中継用）申込消滅確定年月日 */
     ztydairitenjimusyocd ,         /* （中継用）代理店事務所コード */
     ztytsrybnwari ,         /* （中継用）手数料分割割合 */
     ztydrtenkeijyouym ,         /* （中継用）代理店計上年月 */
     ztykydatkidairitencd ,         /* （中継用）共同扱代理店コード */
     ztydaihyoubosyuunincd ,         /* （中継用）代表募集人コード */
     ztytansyukukjdhybosyuunm ,         /* （中継用）短縮漢字代表募集人名 */
     ztyknkyknm15 ,         /* （中継用）カナ契約者名（１５文字） */
     ztydakuhikettikekkacd ,         /* （中継用）諾否決定結果コード */
     ztydkhktiymd ,         /* （中継用）諾否決定年月日 */
     ztytoukeiyousinsakbn ,         /* （中継用）統計用診査区分 */
     ztyhonninkknnkbn ,         /* （中継用）本人確認区分 */
     ztynstkarihyj ,         /* （中継用）年金支払特約有表示 */
     ztynstknkkkn ,         /* （中継用）年金支払特約年金期間 */
     ztydrtentsryhushrkykhyouji ,         /* （中継用）代理店手数料不支払契約表示 */
     ztynyknkanskanouhyouji ,         /* （中継用）入金勧奨可能表示 */
     ztydshukahyouji ,         /* （中継用）ＤＳ付加表示 */
     ztystdairiseikyuutkykarihyj ,         /* （中継用）指定代理請求特約有表示 */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztykyksyaseikbn ,         /* （中継用）契約者性別区分 */
     ztyhhknseiymd ,         /* （中継用）被保険者生年月日 */
     ztydrtenpaperlessmoshyj ,         /* （中継用）代理店ペーパーレス申込表示 */
     ztydrtenmostousyaukeymd ,         /* （中継用）代理店申込書当社受付年月日 */
     ztykyktuuka ,         /* （中継用）契約通貨 */
     ztyhrktuuka ,         /* （中継用）払込通貨 */
     ztysykihrkpgaika ,         /* （中継用）初回払込Ｐ（外貨） */
     ztyyennykntkarihyouji ,         /* （中継用）円入金特約有表示 */
     ztygaikanykntkarihyouji ,         /* （中継用）外貨入金特約有表示 */
     ztykihonsgaika ,         /* （中継用）基本Ｓ（外貨） */
     ztytekiyoukawaserate ,         /* （中継用）適用為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztymkhyoutiyensysnikoukbn ,         /* （中継用）目標到達時円建終身保障移行区分 */
     ztysyksbyensitihsyutkykhyj ,         /* （中継用）初期死亡時円換算最低保証特約有表示 */
     ztyjyudkaigomehrtkarihyj ,         /* （中継用）重度介護前払特約有表示 */
     ztysykihrkpsiteituuka ,         /* （中継用）初回払込Ｐ（指定通貨） */
     ztyteirituhaibunwari ,         /* （中継用）定率部分配分割合 */
     ztysueokikknkbn ,         /* （中継用）据置期間区分 */
     ztynksyuruikbn1 ,         /* （中継用）年金種類区分（１文字） */
     ztydairitenkbtinfo1 ,         /* （中継用）代理店個別情報１ */
     ztydairitenkbtinfo2 ,         /* （中継用）代理店個別情報２ */
     ztydairitenkbtinfo3 ,         /* （中継用）代理店個別情報３ */
     ztyyohurimiryou ,         /* （中継用）預振未了 */
     ztykznyuuryokuymd ,         /* （中継用）口座入力年月日 */
     ztysetaitemosno ,         /* （中継用）セット相手申込番号 */
     ztyyakkanjyuryouhoukbn ,         /* （中継用）約款受領方法区分 */
     ztyyakkanbunsyono ,         /* （中継用）約款文書番号 */
     ztykzhuritourokuhoukbn ,         /* （中継用）口座振替登録方法区分 */
     ztydai1hknkkn ,         /* （中継用）第１保険期間 */
     ztycreditnyuuryokuymd ,         /* （中継用）クレジット入力年月日 */
     ztycreditmiryou ,         /* （中継用）クレカ未了 */
     ztycredittrkhoukbn ,         /* （中継用）クレジット登録方法区分 */
     ztycardbrandkbn ,         /* （中継用）カードブランド */
     ztycarddatasousinymd ,         /* （中継用）カードデータ送信日 */
     ztykykdrtkykarihyj ,         /* （中継用）契約者代理特約有表示 */
     ztykzktrkservicekbn ,         /* （中継用）ご家族登録サービス区分 */
     ztyteikisiharaiarihyj ,         /* （中継用）定期支払特約有表示 */
     ztyteikishrkinshrtuukakbn ,         /* （中継用）定期支払金支払通貨区分 */
     ztyteikisiharaikin ,         /* （中継用）定期支払金 */
     ztykoureikzksetumeihoukbn ,         /* （中継用）高齢者ご家族等説明方法区分 */
     ztykoureimndnhukusuukaikbn ,         /* （中継用）高齢者面談複数回実施区分 */
     ztykoureitratkisyaigidskkbn ,         /* （中継用）高齢者取扱者以外同席区分 */
     ztyyobiv53 ,         /* （中継用）予備項目Ｖ５３ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_DrtenIpToukeiTy_Z;