CREATE VIEW ZT_DrtenSkKykDtlSyokaiRn AS SELECT
     zrnsakuseiym ,         /* （連携用）作成年月 */
     zrnbsydrtencd ,         /* （連携用）募集代理店コード */
     zrntntusycd ,         /* （連携用）担当者コード */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnkykymwareki4keta ,         /* （連携用）契約年月（和暦）（４桁） */
     zrncifcd ,         /* （連携用）ＣＩＦコード */
     zrnatesakinm ,         /* （連携用）宛先名 */
     zrnhassinka ,         /* （連携用）発信課 */
     zrntelno15keta ,         /* （連携用）電話番号（１５桁） */
     zrnbsyymwareki4keta ,         /* （連携用）募集年月（和暦）（４桁） */
     zrntntusynm ,         /* （連携用）担当者名 */
     zrnkydatkikbnkj ,         /* （連携用）共同扱区分（漢字） */
     zrnkyknmkj20 ,         /* （連携用）契約者名（漢字）（２０桁） */
     zrnskymdwareki ,         /* （連携用）失効年月日（和暦） */
     zrnhrkkaisuukj ,         /* （連携用）払込回数（漢字） */
     zrnhrkkeirokj ,         /* （連携用）払込経路（漢字） */
     zrnp11keta ,         /* （連携用）保険料（１１桁） */
     zrnskhr ,         /* （連携用）失効時返戻金 */
     zrnjizensyoukaiyouhyj ,         /* （連携用）事前照会要表示 */
     zrntntusygyouhaiinfo ,         /* （連携用）担当者業廃情報 */
     zrnhrkkeirobtjhmidasi ,         /* （連携用）払込経路別情報見出し */
     zrnhrkkeirobtjh ,         /* （連携用）払込経路別情報 */
     zrnhknsyuruimei ,         /* （連携用）保険種類名 */
     zrnbkofccd ,         /* （連携用）バックオフィスコード */
     zrndbskyoteiymd ,         /* （連携用）ＤＢ削除予定年月 */
     zrnminyukaisuu ,         /* （連携用）未入回数 */
     zrnjikaipjyuutouym ,         /* （連携用）次回Ｐ充当年月 */
     zrnvitkaiinno ,         /* （連携用）Ｖｉｔ会員番号 */
     zrnvitkykym ,         /* （連携用）Ｖｉｔ契約年月 */
     zrnvitskymd ,         /* （連携用）Ｖｉｔ失効年月日 */
     zrnvithrkkaisuu ,         /* （連携用）Ｖｉｔ払込回数 */
     zrnvithrkkeiro ,         /* （連携用）Ｖｉｔ払込経路 */
     zrnzkomivitriyoury ,         /* （連携用）税込Ｖｉｔ利用料 */
     zrnvitnyknkaisuu ,         /* （連携用）Ｖｉｔ入金回数 */
     zrnvitbikou ,         /* （連携用）Ｖｉｔ備考 */
     zrnyobiv25           /* （連携用）予備項目Ｖ２５ */
FROM ZT_DrtenSkKykDtlSyokaiRn_Z;