CREATE VIEW ZT_SeirituInfoTy AS SELECT
     ztykijyunym ,         /* （中継用）基準年月 */
     ztyseisekiym ,         /* （中継用）成績計上年月 */
     ztysyono ,         /* （中継用）証券番号 */
     ztyhanbainm ,         /* （中継用）販売名称 */
     ztyatkisisya ,         /* （中継用）扱支社 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysdpdkbn ,         /* （中継用）Ｓ建Ｐ建区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztysinkykryouritukbn ,         /* （中継用）新契約用料率区分 */
     ztyduketorihouhoukbn ,         /* （中継用）Ｄ受取方法区分 */
     ztykihons9 ,         /* （中継用）基本Ｓ（９桁） */
     ztyhsys ,         /* （中継用）保障Ｓ */
     ztytkbriknsnhrkp ,         /* （中継用）月払換算払込Ｐ */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztykyksyaseikbn ,         /* （中継用）契約者性別区分 */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztysykgycd ,         /* （中継用）職業コード */
     ztykyksyakikykarihyj ,         /* （中継用）契約者既契約有表示 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztysyokaipnyuukinhouhoukbn ,         /* （中継用）初回Ｐ入金方法区分 */
     ztytoukeiyousinsakbn ,         /* （中継用）統計用診査区分 */
     ztyhhknsynensyuukbn ,         /* （中継用）被保険者年収区分 */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztystdairiseikyuutkykarihyj ,         /* （中継用）指定代理請求特約有表示 */
     ztymannenreihyj ,         /* （中継用）満年令表示 */
     ztynksyuruikbn1 ,         /* （中継用）年金種類区分（１文字） */
     ztynstkarihyj ,         /* （中継用）年金支払特約有表示 */
     ztyaatkioybsydrtencd ,         /* （中継用）Ａ扱者親募集代理店コード */
     ztybatkioybsydrtencd ,         /* （中継用）Ｂ扱者親募集代理店コード */
     ztysinkeiyakujiyoteiriritu ,         /* （中継用）新契約時予定利率 */
     ztysiteituukakihons ,         /* （中継用）指定通貨建基本Ｓ */
     ztyhrktuukakbn ,         /* （中継用）払込通貨区分 */
     ztysiteituukakbn ,         /* （中継用）指定通貨区分 */
     ztyhrktuukatukiknznhrkp ,         /* （中継用）払込通貨建月換算払込Ｐ */
     ztysiteituukatukiknznhrkp ,         /* （中継用）指定通貨建月換算払込Ｐ */
     ztyyennyknrate ,         /* （中継用）円入金レート */
     ztygaikanyknrate ,         /* （中継用）外貨入金レート */
     ztyjyudkaigomehrtkarihyj ,         /* （中継用）重度介護前払特約有表示 */
     ztysyksbyensitihsyutkykrate ,         /* （中継用）初期死亡時円換算最低保証特約用為替レート */
     ztysjkkktyouseiriritu ,         /* （中継用）市場価格調整用利率 */
     ztytargettkmkht ,         /* （中継用）ターゲット特約目標値 */
     ztyteirituhaibunwari ,         /* （中継用）定率部分配分割合 */
     ztyzenkizennouhyouji ,         /* （中継用）全期前納表示 */
     ztypwaribikikbn ,         /* （中継用）Ｐ割引区分 */
     ztypwaribikihanteigk ,         /* （中継用）Ｐ割引判定金額 */
     ztydai1hknkkn ,         /* （中継用）第１保険期間 */
     ztykykdrtkykarihyj ,         /* （中継用）契約者代理特約有表示 */
     ztykzktrkservicetrkninzuu ,         /* （中継用）ご家族登録サービス登録人数 */
     ztyteikisiharaiarihyj ,         /* （中継用）定期支払特約有表示 */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SeirituInfoTy_Z;