CREATE VIEW ZT_MosJkItiranSyoukaiRn AS SELECT
     zrnmosym ,         /* （連携用）申込月度 */
     zrnmoskbn ,         /* （連携用）申込区分 */
     zrnmosno ,         /* （連携用）申込番号 */
     zrnhknsyuruinm ,         /* （連携用）保険種類名称 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnmusymd ,         /* （連携用）申込年月日 */
     zrnmosnyuuryokuymd ,         /* （連携用）申込入力年月日 */
     zrnkydatkikbn ,         /* （連携用）共同扱区分 */
     zrnbsudirtnatkikeitaikbn ,         /* （連携用）募集代理店扱形態区分 */
     zrnbsydrtencd ,         /* （連携用）募集代理店コード */
     zrnbsydrtenkjnm ,         /* （連携用）募集代理店漢字名称 */
     zrnatukaikojincd ,         /* （連携用）扱者個人コード */
     zrntansyukukjatukaisyanm ,         /* （連携用）短縮漢字扱者名 */
     zrncifcd ,         /* （連携用）ＣＩＦコード */
     zrnkjkyknm10 ,         /* （連携用）漢字契約者名（１０文字） */
     zrntansyukukjhhknnm ,         /* （連携用）短縮漢字被保険者名 */
     zrnhhknnen2keta ,         /* （連携用）被保険者年令（２桁） */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnmossyoumetukbn ,         /* （連携用）申込消滅区分 */
     zrnkurikosiriyuukbn ,         /* （連携用）繰越理由区分 */
     zrnketjkkbn ,         /* （連携用）決定状況区分 */
     zrndakuhiktjyoutaikbn ,         /* （連携用）諾否決定状態区分 */
     zrnmosketkekkakbn ,         /* （連携用）申込決定結果区分 */
     zrnkihonhubi ,         /* （連携用）基本不備 */
     zrnkthhbhyouji ,         /* （連携用）決定保留不備表示 */
     zrnsrhhbhyouji ,         /* （連携用）成立保留不備表示 */
     zrnnyknzumihyouji ,         /* （連携用）入金済表示 */
     zrnsinsazumihyouji ,         /* （連携用）診査済表示 */
     zrntuukatanikbn ,         /* （連携用）通貨単位区分 */
     zrnsyokaihrkpmoji ,         /* （連携用）初回払込Ｐ（文字列） */
     zrnhjykktkbn ,         /* （連携用）報状告知区分 */
     zrnsyokaipryosyuymd ,         /* （連携用）初回Ｐ領収年月日 */
     zrnkokutiymd ,         /* （連携用）告知年月日 */
     zrnkariseirituymd ,         /* （連携用）仮成立年月日 */
     zrnfstpnyknnaiyoukbn ,         /* （連携用）初回Ｐ入金内容区分 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnsakuseiymd ,         /* （連携用）作成日 */
     zrnanniskcd ,         /* （連携用）案内先コード */
     zrnsyosakuseiymd ,         /* （連携用）証券作成年月日 */
     zrnbsydrtenkobetuinfo1 ,         /* （連携用）募集代理店個別情報１ */
     zrnbsydrtenkobetuinfo2 ,         /* （連携用）募集代理店個別情報２ */
     zrnbsydrtenkobetuinfo3 ,         /* （連携用）募集代理店個別情報３ */
     zrnbsydrtenkobetuinfo4 ,         /* （連携用）募集代理店個別情報４ */
     zrnbsydrtenkobetuinfo5 ,         /* （連携用）募集代理店個別情報５ */
     zrnbankkouincd ,         /* （連携用）銀行行員コード */
     zrnbosyuutourokuno ,         /* （連携用）募集人登録番号 */
     zrnmosjkkbn ,         /* （連携用）申込状況区分 */
     zrnkousinymd ,         /* （連携用）更新年月日 */
     zrnsinsayoteiymd ,         /* （連携用）診査予定年月日 */
     zrnhjnkykhyj ,         /* （連携用）法人契約表示 */
     zrnkjhjnnm ,         /* （連携用）漢字法人名 */
     zrnyobiv93           /* （連携用）予備項目Ｖ９３ */
FROM ZT_MosJkItiranSyoukaiRn_Z;