CREATE VIEW IT_KhTyousyo AS SELECT
     syono ,         /* 証券番号 */
     tyouhyouymd ,         /* 帳票作成日 */
     shrtysyrenno ,         /* 支払調書連番 */
     kacd ,         /* 課コード */
     tantocd ,         /* 担当コード */
     hknsyukigou ,         /* 保険種類記号 */
     hknkkn ,         /* 保険期間 */
     hrkkkn ,         /* 払込期間 */
     hhknnen ,         /* 被保険者年齢 */
     kyknen ,         /* 契約者年齢 */
     kykymd ,         /* 契約日 */
     hhknsei ,         /* 被保険者性別 */
     hrkkaisuu ,         /* 払込回数 */
     hrkkeiro ,         /* 払込経路 */
     annaihuyouriyuukbn ,         /* 案内不要理由区分 */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     kouryokuhasseiymd ,         /* 効力発生日 */
     mfadrsiyouhyouji ,         /* ＭＦ住所使用表示 */
     kihrpdmiseibidisp ,         /* 既払ＰＤ未整備表示 */
     kihrpseibiyoudisp ,         /* 既払込Ｐ整備要表示 */
     shrgk ,         /* 支払金額 */
     shrgk$ ,         /* 支払金額(通貨型) */
     warimsishrgkbizc ,         /* 割増支払金額（業務通貨型） */
     warimsishrgkbizc$ ,         /* 割増支払金額（業務通貨型）(通貨型) */
     znnphrbizc ,         /* 前納Ｐ等返戻金（業務通貨型） */
     znnphrbizc$ ,         /* 前納Ｐ等返戻金（業務通貨型）(通貨型) */
     ttkekstkganribizc ,         /* 立替貸付元利金（業務通貨型） */
     ttkekstkganribizc$ ,         /* 立替貸付元利金（業務通貨型）(通貨型) */
     sshkdbizc ,         /* 差引Ｄ（業務通貨型） */
     sshkdbizc$ ,         /* 差引Ｄ（業務通貨型）(通貨型) */
     sshkshrgk ,         /* 差引支払金額 */
     sshkshrgk$ ,         /* 差引支払金額(通貨型) */
     mihrkmpbizc ,         /* 未払込Ｐ（業務通貨型） */
     mihrkmpbizc$ ,         /* 未払込Ｐ（業務通貨型）(通貨型) */
     shrymd ,         /* 支払日 */
     syorisosikicd ,         /* 処理組織コード */
     syoritaisyoukbn ,         /* 処理対象区分 */
     shrtysytsinyno ,         /* 支払調書郵便番号 */
     shrtysyadr1kj ,         /* 支払調書住所１（漢字） */
     shrtysyadr2kj ,         /* 支払調書住所２（漢字） */
     shrtysyadr3kj ,         /* 支払調書住所３（漢字） */
     kyknmkj ,         /* 契約者名（漢字） */
     hhknnmkj ,         /* 被保険者名（漢字） */
     uktnmkj ,         /* 受取人名（漢字） */
     kjdaihyouuktnm ,         /* 漢字代表受取人名 */
     shrtienrsk ,         /* 支払遅延利息 */
     shrtienrsk$ ,         /* 支払遅延利息(通貨型) */
     kihons ,         /* 基本Ｓ */
     kihons$ ,         /* 基本Ｓ(通貨型) */
     shrtysysyuruicd ,         /* 支払調書種類コード */
     teknjikihrpseibidisp ,         /* 転換時既払込Ｐ未整備表示 */
     kihrkmp ,         /* 既払込保険料 */
     kihrkmp$ ,         /* 既払込保険料(通貨型) */
     onlinecentercutkbn ,         /* オンラインセンターカット区分 */
     shrhousiteikbn ,         /* 支払方法指定区分 */
     htykeihihnsyukbn ,         /* 必要経費編集区分 */
     syuseijtshrdbizc ,         /* 修正後実支払Ｄ（業務通貨型） */
     syuseijtshrdbizc$ ,         /* 修正後実支払Ｄ（業務通貨型）(通貨型) */
     touduketorihouhoukbn ,         /* 当Ｄ受取方法区分 */
     nenkinkkn ,         /* 年金期間 */
     bankcd ,         /* 銀行コード */
     banknmkn ,         /* 銀行名（カナ） */
     sitencd ,         /* 支店コード */
     sitennmkn ,         /* 支店名（カナ） */
     yokinkbn ,         /* 預金種目区分 */
     yokinknmkn ,         /* 預金口座種目名（カナ） */
     kouzano ,         /* 口座番号 */
     kzmeiginmkn ,         /* 口座名義人氏名（カナ） */
     sakuseiymd ,         /* 作成年月日 */
     kykmnmeigibangou ,         /* 契約者ＭＮ名義番号 */
     uktmnmeigibangou ,         /* 受取人ＭＮ名義番号 */
     jigyoukykmndantaicd ,         /* 事業契約用ＭＮ団体コード */
     mnsaiannaihnskakbn ,         /* ＭＮ再案内本社回送区分 */
     huho2kykdisp ,         /* 普保Ⅱ契約表示 */
     shrtysyhknsyukbn ,         /* 支払調書保険種類区分 */
     shrtysykurikosidisp ,         /* 支払調書繰越表示 */
     tsinyno ,         /* 通信先郵便番号 */
     tsinadr1kj ,         /* 通信先住所１（漢字） */
     tsinadr2kj ,         /* 通信先住所２（漢字） */
     tsinadr3kj ,         /* 通信先住所３（漢字） */
     synyhsjykykndisp ,         /* 収入保障年金受給権表示 */
     tblsakuseihunodisp ,         /* テープ作成不能表示 */
     daihyouktkbn ,         /* 代表受取人区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     oldtsinyno ,         /* （旧）通信先郵便番号 */
     oldtsinadr1kj ,         /* （旧）通信先住所１（漢字） */
     oldtsinadr2kj ,         /* （旧）通信先住所２（漢字） */
     oldtsinadr3kj ,         /* （旧）通信先住所３（漢字） */
     oldkyknmkj ,         /* （旧）契約者名（漢字） */
     kykhnkkaisuu ,         /* 契約者変更回数 */
     shrkykhtykeihiyouhyj ,         /* 支払時契約者必要経費要表示 */
     shrkykhtykeihi ,         /* 支払時契約者必要経費 */
     shrkykhtykeihi$           /* 支払時契約者必要経費(通貨型) */
FROM IT_KhTyousyo_Z;