CREATE VIEW HT_IjitoukeiMeisai AS SELECT
     syono ,         /* 証券番号 */
     renno8keta ,         /* 連番（８桁） */
     bosyuuym ,         /* 募集年月 */
     kykymd ,         /* 契約日 */
     sknnkaisiymd ,         /* 責任開始日 */
     syoumetuymd ,         /* 消滅日 */
     shrymd ,         /* 支払日 */
     idousyoriymd ,         /* 異動処理日 */
     sntkhoukbn ,         /* 選択方法区分 */
     kokutikbn ,         /* 告知区分 */
     skeijimukbn ,         /* 新契約事務区分 */
     sirajikykkbn ,         /* 白地契約区分 */
     hrkkaisuu ,         /* 払込回数 */
     haitoukinuketorihoukbn ,         /* 配当金受取方法区分 */
     oyadrtencd ,         /* 親代理店コード */
     aatsukaishasoshikicd ,         /* Ａ扱者組織コード */
     aatukaikojincd ,         /* Ａ扱者個人コード */
     tratkiagcd ,         /* 取扱代理店コード */
     bosyuudairitenatkikeitaikbn ,         /* 募集代理店扱形態区分 */
     hhknnen ,         /* 被保険者年齢 */
     hhknsei ,         /* 被保険者性別 */
     hhknyno ,         /* 被保険者郵便番号 */
     hhkntodouhukencd ,         /* 被保険者都道府県コード */
     hhknnensyuukbn ,         /* 被保険者年収区分 */
     hhknsykgycd ,         /* 被保険者職業コード */
     sintyou ,         /* 身長 */
     taijyuu ,         /* 体重 */
     kituenkbn ,         /* 喫煙区分 */
     kituenhon ,         /* 喫煙本数 */
     kyktuukasyu ,         /* 契約通貨種類 */
     hrktuukasyu ,         /* 払込通貨種類 */
     syouhncd ,         /* 商品コード */
     syouhnsdno ,         /* 商品世代番号 */
     seitoukihons ,         /* 正当基本Ｓ */
     seitoukihons$ ,         /* 正当基本Ｓ(通貨型) */
     seitoukihonsmanen ,         /* 正当基本Ｓ（万円） */
     seitoukihonsmanen$ ,         /* 正当基本Ｓ（万円）(通貨型) */
     syutkp ,         /* 主契約・特約Ｐ */
     syutkp$ ,         /* 主契約・特約Ｐ(通貨型) */
     syutkpmanen ,         /* 主契約・特約Ｐ（万円） */
     syutkpmanen$ ,         /* 主契約・特約Ｐ（万円）(通貨型) */
     imustiyusbus ,         /* 医務査定用死亡Ｓ */
     imustiyusbus$ ,         /* 医務査定用死亡Ｓ(通貨型) */
     imustiyusbusmanen ,         /* 医務査定用死亡Ｓ（万円） */
     imustiyusbusmanen$ ,         /* 医務査定用死亡Ｓ（万円）(通貨型) */
     yenkansantkykwsrate ,         /* 円換算適用為替レート */
     syoubyoucd1 ,         /* 傷病コード１ */
     syoubyoucd2 ,         /* 傷病コード２ */
     dakuhiktkekkacd ,         /* 諾否決定結果コード */
     dakuhiketsyacd ,         /* 諾否決定者コード */
     palketsyacd ,         /* ＰＡＬ決定者コード */
     syksbyensitihsyutkhkkbn ,         /* 初期死亡時円換算最低保証特約付加区分 */
     jyudkaigomehrtkhkkbn ,         /* 重度介護前払特約付加区分 */
     symtgenincd ,         /* 消滅原因コード */
     siincd ,         /* 死因コード */
     ijitoukeikaijyokbn ,         /* 医事統計解除区分 */
     sysnikoujiym ,         /* 終身移行時年月 */
     ijitoukeizennoukbn ,         /* 医事統計用前納区分 */
     hrkkeiro ,         /* 払込経路 */
     tikiktbrisyuruikbn ,         /* 定期一括払種類区分 */
     jissituhosyous ,         /* 実質保障Ｓ */
     jissituhosyous$ ,         /* 実質保障Ｓ(通貨型) */
     jissituhosyousmanen ,         /* 実質保障Ｓ（万円） */
     jissituhosyousmanen$ ,         /* 実質保障Ｓ（万円）(通貨型) */
     dai1hknkkn ,         /* 第１保険期間 */
     ijitoukeitikshrtkykkbn ,         /* 医事統計用定期支払特約区分 */
     teikisiharaikin ,         /* 定期支払金 */
     teikisiharaikin$ ,         /* 定期支払金(通貨型) */
     teikisiharaikinmanen ,         /* 定期支払金（万円） */
     teikisiharaikinmanen$ ,         /* 定期支払金（万円）(通貨型) */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM HT_IjitoukeiMeisai_Z;