CREATE VIEW ZT_EgsyokuinSysRendouTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyatukaikojincd ,         /* （中継用）扱者個人コード */
     ztysyono ,         /* （中継用）証券番号 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztysdpdkbn ,         /* （中継用）Ｓ建Ｐ建区分 */
     ztykihons ,         /* （中継用）基本Ｓ */
     ztyharaikomip ,         /* （中継用）払込Ｐ */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztygyousekiyouhosyous ,         /* （中継用）業績用保障Ｓ */
     ztykydatkikbn ,         /* （中継用）共同扱区分 */
     ztybsyym ,         /* （中継用）募集年月 */
     ztytsinkihontikucd ,         /* （中継用）通信先基本地区コード */
     ztyatukaisosikicd ,         /* （中継用）扱者組織コード */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztyhensyuukeiyakusyamei ,         /* （中継用）編集契約者名 */
     ztyhnsyuknjkyksynm ,         /* （中継用）編集漢字契約者名 */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztykurikosihyj ,         /* （中継用）繰越表示 */
     ztylivingneedstkykarihyj ,         /* （中継用）リビングニーズ特約有表示 */
     ztykyksyhhknsydouituhyouji ,         /* （中継用）契約者被保険者同一表示 */
     ztyhaitousiharaikbn ,         /* （中継用）配当支払区分 */
     ztydairitenatkikeitaikbn ,         /* （中継用）代理店扱形態区分 */
     ztydrtenegsyokuinatkiwari ,         /* （中継用）代理店営業職員扱割合 */
     ztykjsakisosikisetteihyj ,         /* （中継用）計上先組織設定表示 */
     ztybsydrtencd ,         /* （中継用）募集代理店コード */
     ztysimetyokuzenbosyuuhyj ,         /* （中継用）〆切直前募集表示 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztymosnyuuryokuymd ,         /* （中継用）申込入力年月日 */
     ztyhhknsakuinmeino ,         /* （中継用）被保険者索引名番号 */
     ztytokusyujimutoriatukaikbn ,         /* （中継用）特殊事務取扱区分 */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztyhokensyuruikigouyobi1x1 ,         /* （中継用）保険種類記号予備１＿１ */
     ztyhokensyuruikigouyobi1x2 ,         /* （中継用）保険種類記号予備１＿２ */
     ztyhokensyuruikigouyobi1x3 ,         /* （中継用）保険種類記号予備１＿３ */
     ztyhokensyuruikigouyobi1x4 ,         /* （中継用）保険種類記号予備１＿４ */
     ztyhokensyuruikigouyobi1x5 ,         /* （中継用）保険種類記号予備１＿５ */
     ztyhokensyuruikigouyobi1x6 ,         /* （中継用）保険種類記号予備１＿６ */
     ztyhokensyuruikigouyobi1x7 ,         /* （中継用）保険種類記号予備１＿７ */
     ztyhokensyuruikigouyobi1x8 ,         /* （中継用）保険種類記号予備１＿８ */
     ztyhokensyuruikigouyobi1x9 ,         /* （中継用）保険種類記号予備１＿９ */
     ztyhokensyuruikigouyobi1x10 ,         /* （中継用）保険種類記号予備１＿１０ */
     ztyhokensyuruikigouyobi1x11 ,         /* （中継用）保険種類記号予備１＿１１ */
     ztyhokensyuruikigouyobi1x12 ,         /* （中継用）保険種類記号予備１＿１２ */
     ztyhokensyuruikigouyobi1x13 ,         /* （中継用）保険種類記号予備１＿１３ */
     ztyhokensyuruikigouyobi1x14 ,         /* （中継用）保険種類記号予備１＿１４ */
     ztyhokensyuruikigouyobi1x15 ,         /* （中継用）保険種類記号予備１＿１５ */
     ztyhokensyuruikigouyobi2x1 ,         /* （中継用）保険種類記号予備２＿１ */
     ztyhokensyuruikigouyobi2x2 ,         /* （中継用）保険種類記号予備２＿２ */
     ztyhokensyuruikigouyobi2x3 ,         /* （中継用）保険種類記号予備２＿３ */
     ztyhokensyuruikigouyobi2x4 ,         /* （中継用）保険種類記号予備２＿４ */
     ztyhokensyuruikigouyobi2x5 ,         /* （中継用）保険種類記号予備２＿５ */
     ztyhokensyuruikigouyobi2x6 ,         /* （中継用）保険種類記号予備２＿６ */
     ztyhokensyuruikigouyobi2x7 ,         /* （中継用）保険種類記号予備２＿７ */
     ztyhokensyuruikigouyobi2x8 ,         /* （中継用）保険種類記号予備２＿８ */
     ztyhokensyuruikigouyobi2x9 ,         /* （中継用）保険種類記号予備２＿９ */
     ztyhokensyuruikigouyobi2x10 ,         /* （中継用）保険種類記号予備２＿１０ */
     ztyhokensyuruikigouyobi3x1 ,         /* （中継用）保険種類記号予備３＿１ */
     ztyhokensyuruikigouyobi3x2 ,         /* （中継用）保険種類記号予備３＿２ */
     ztyhokensyuruikigouyobi3x3 ,         /* （中継用）保険種類記号予備３＿３ */
     ztyhokensyuruikigouyobi3x4 ,         /* （中継用）保険種類記号予備３＿４ */
     ztyhokensyuruikigouyobi3x5 ,         /* （中継用）保険種類記号予備３＿５ */
     ztyhokensyuruikigouyobi3x6 ,         /* （中継用）保険種類記号予備３＿６ */
     ztyhokensyuruikigouyobi3x7 ,         /* （中継用）保険種類記号予備３＿７ */
     ztyhokensyuruikigouyobi3x8 ,         /* （中継用）保険種類記号予備３＿８ */
     ztyhokensyuruikigouyobi3x9 ,         /* （中継用）保険種類記号予備３＿９ */
     ztyhokensyuruikigouyobi3x10 ,         /* （中継用）保険種類記号予備３＿１０ */
     ztynstkarihyj ,         /* （中継用）年金支払特約有表示 */
     ztymosno ,         /* （中継用）申込番号 */
     ztystdairiseikyuutkykarihyj ,         /* （中継用）指定代理請求特約有表示 */
     ztynenkansanp ,         /* （中継用）年換算Ｐ */
     ztykyksyaskinmeino ,         /* （中継用）契約者索引名番号 */
     ztysibous ,         /* （中継用）死亡Ｓ */
     ztyjissyuup ,         /* （中継用）実収Ｐ */
     ztysekininkaisiymd ,         /* （中継用）責任開始年月日 */
     ztykokutiymd ,         /* （中継用）告知年月日 */
     ztysyokaipryosyuymd ,         /* （中継用）初回Ｐ領収年月日 */
     ztyseirituymd ,         /* （中継用）成立年月日 */
     ztybosdairitentsratkiwari ,         /* （中継用）募集代理店手数料扱割合 */
     ztybosyuunincd ,         /* （中継用）募集人コード */
     ztydrtentsryhushrkykhyouji ,         /* （中継用）代理店手数料不支払契約表示 */
     ztymdhnaisyoumeikbn ,         /* （中継用）窓販用愛称名区分 */
     ztydairitenkykkanrino ,         /* （中継用）代理店契約管理番号 */
     ztykanjitsinkaiadr ,         /* （中継用）漢字通信先下位住所 */
     ztytsintelno ,         /* （中継用）通信先電話番号 */
     ztyhensyuuyoukyksyaseikbn ,         /* （中継用）編集用契約者性別区分 */
     ztyhensyuuyoukyksyaseiymd ,         /* （中継用）編集用契約者生年月日 */
     ztyhhknmei ,         /* （中継用）被保険者名 */
     ztyknjhhknmei ,         /* （中継用）漢字被保険者名 */
     ztyhhknseiymd ,         /* （中継用）被保険者生年月日 */
     ztynksyuruikbn1 ,         /* （中継用）年金種類区分（１文字） */
     ztymusymd ,         /* （中継用）申込年月日 */
     ztymossyosakuseiymd ,         /* （中継用）申込書作成年月日 */
     ztyitijibaraipkyktuuka ,         /* （中継用）一時払Ｐ（契約通貨建） */
     ztykawaseraten5 ,         /* （中継用）為替レートＮ５ */
     ztyhrktuukakbn ,         /* （中継用）払込通貨区分 */
     ztysiteituukakbn ,         /* （中継用）指定通貨区分 */
     ztysyksbsitihsyutkykarihyj ,         /* （中継用）初期死亡時最低保証特約有表示 */
     ztyskkaigomaehrtkykarihyj ,         /* （中継用）（新契約）介護前払特約有表示 */
     ztykihonskyktuuka ,         /* （中継用）基本Ｓ（契約通貨建） */
     ztyzenkizennouhyouji ,         /* （中継用）全期前納表示 */
     ztynnknsnpssysyup ,         /* （中継用）年換算Ｐ算出用主契約Ｐ */
     ztynknsnpssyhrkkskbn ,         /* （中継用）年換算Ｐ算出用払込回数区分 */
     ztykykdrtkykarihyj ,         /* （中継用）契約者代理特約有表示 */
     ztykzktrkservicearihyj ,         /* （中継用）ご家族登録サービス有表示 */
     ztyyobiv250x1 ,         /* （中継用）予備項目Ｖ２５０＿１ */
     ztyyobiv250x2 ,         /* （中継用）予備項目Ｖ２５０＿２ */
     ztyyobiv250x3 ,         /* （中継用）予備項目Ｖ２５０＿３ */
     ztyyobiv250x4 ,         /* （中継用）予備項目Ｖ２５０＿４ */
     ztyyobiv250x5 ,         /* （中継用）予備項目Ｖ２５０＿５ */
     ztyyobiv118 ,         /* （中継用）予備項目Ｖ１１８ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_EgsyokuinSysRendouTy_Z;