CREATE VIEW IT_BAK_HokenKykIdouRireki AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     trkssikibetukey ,         /* 取消識別キー */
     henkousikibetukey ,         /* 変更識別キー */
     kyktuukasyu ,         /* 契約通貨種類 */
     idouymd ,         /* 異動日 */
     idoujiyuukbn ,         /* 異動事由区分 */
     ttdkrenno ,         /* 手続連番 */
     kykymd ,         /* 契約日 */
     hhknnen ,         /* 被保険者年齢 */
     hhknsei ,         /* 被保険者性別 */
     hknsyukigou ,         /* 保険種類記号 */
     aisyoumeikbn ,         /* 愛称名区分 */
     zougenkbn ,         /* 増減区分 */
     hokenkngk ,         /* 保険金額 */
     hokenkngk$ ,         /* 保険金額(通貨型) */
     hokenryou ,         /* 保険料 */
     hokenryou$ ,         /* 保険料(通貨型) */
     ptumitatekin ,         /* 保険料積立金 */
     ptumitatekin$ ,         /* 保険料積立金(通貨型) */
     kaiyakuhrgoukei ,         /* 解約返戻金合計 */
     kaiyakuhrgoukei$ ,         /* 解約返戻金合計(通貨型) */
     kaiyakuhr ,         /* 解約返戻金 */
     kaiyakuhr$ ,         /* 解約返戻金(通貨型) */
     mikeikap ,         /* 未経過保険料 */
     mikeikap$ ,         /* 未経過保険料(通貨型) */
     zennouseisankgk ,         /* 前納精算金額 */
     zennouseisankgk$ ,         /* 前納精算金額(通貨型) */
     idouhokenkngk ,         /* 異動保険金額 */
     idouhokenkngk$ ,         /* 異動保険金額(通貨型) */
     idoup ,         /* 異動保険料 */
     idoup$ ,         /* 異動保険料(通貨型) */
     idouptumitatekin ,         /* 異動保険料積立金 */
     idouptumitatekin$ ,         /* 異動保険料積立金(通貨型) */
     idoukiykhnrikn ,         /* 異動解約返戻金 */
     idoukiykhnrikn$ ,         /* 異動解約返戻金(通貨型) */
     hknkkn ,         /* 保険期間 */
     yoteiriritu ,         /* 予定利率 */
     tumitatekinkbn ,         /* 積立金区分 */
     kykidouharaikatakbn ,         /* 保険契約異動情報払方区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_BAK_HokenKykIdouRireki_Z;