CREATE VIEW ZT_DrtenIpToukeiRn AS SELECT
     zrneigyouhonbusisyacd ,         /* （連携用）営業本部支社コード */
     zrnsosikicd ,         /* （連携用）組織コード */
     zrnatukaikojincd ,         /* （連携用）扱者個人コード */
     zrnmosym ,         /* （連携用）申込月度 */
     zrnmoskbn ,         /* （連携用）申込区分 */
     zrntansyukukjatukaisyanm ,         /* （連携用）短縮漢字扱者名 */
     zrnmosno ,         /* （連携用）申込番号 */
     zrnmossyoumetukbn ,         /* （連携用）申込消滅区分 */
     zrnkurikosiriyuukbn ,         /* （連携用）繰越理由区分 */
     zrnnyknzumihyouji ,         /* （連携用）入金済表示 */
     zrntoukeihknsyruikbn ,         /* （連携用）統計用保険種類区分 */
     zrnhjykktkbn ,         /* （連携用）報状告知区分 */
     zrnkykktaikbn ,         /* （連携用）契約形態区分 */
     zrnjyunhsys ,         /* （連携用）純保障Ｓ */
     zrnhsys ,         /* （連携用）保障Ｓ */
     zrnsoukensuu ,         /* （連携用）総件数 */
     zrnketjkkbn ,         /* （連携用）決定状況区分 */
     zrndakuhiktjyoutaikbn ,         /* （連携用）諾否決定状態区分 */
     zrnkihonhubi ,         /* （連携用）基本不備 */
     zrnsphubi ,         /* （連携用）ＳＰ不備 */
     zrnsseigenhubi ,         /* （連携用）Ｓ制限不備 */
     zrnnayosehumei ,         /* （連携用）名寄不明 */
     zrntuusangendoover ,         /* （連携用）通算限度オーバー */
     zrnmosketteihoryuu ,         /* （連携用）申込決定保留 */
     zrnkykkakjissityuu ,         /* （連携用）契約確認実施中 */
     zrnkktketteihoryuu ,         /* （連携用）告知決定保留 */
     zrnhonsyakethoryuu ,         /* （連携用）本社決定保留 */
     zrnseiymdhubi ,         /* （連携用）生年月日不備 */
     zrnphusoku ,         /* （連携用）Ｐ不足 */
     zrnsrhuketyu ,         /* （連携用）成立保留受付中 */
     zrnpkakin ,         /* （連携用）Ｐ過金 */
     zrnbsudirtnatkikeitaikbn ,         /* （連携用）募集代理店扱形態区分 */
     zrnsakuseiymd ,         /* （連携用）作成日 */
     zrnkydatkikbn ,         /* （連携用）共同扱区分 */
     zrntansyukukjhhknnm ,         /* （連携用）短縮漢字被保険者名 */
     zrnhhknsykgycd ,         /* （連携用）被保険者職業コード */
     zrnhhknnen2keta ,         /* （連携用）被保険者年令（２桁） */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnmusymd ,         /* （連携用）申込年月日 */
     zrnsyokaipryosyuymd ,         /* （連携用）初回Ｐ領収年月日 */
     zrnkokutiymd ,         /* （連携用）告知年月日 */
     zrnmosnyuuryokuymd ,         /* （連携用）申込入力年月日 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnsekininkaisiymd ,         /* （連携用）責任開始年月日 */
     zrnfstpnyknsyoriymd ,         /* （連携用）初回Ｐ入金処理年月日 */
     zrnfstpnyknnaiyoukbn ,         /* （連携用）初回Ｐ入金内容区分 */
     zrnsisyaketsyoriymd ,         /* （連携用）支社決定処理年月日 */
     zrnsyosakuseiymd ,         /* （連携用）証券作成年月日 */
     zrnseisekiym ,         /* （連携用）成績計上年月 */
     zrnsyokaiharaikomip ,         /* （連携用）初回払込Ｐ */
     zrnsyono ,         /* （連携用）証券番号 */
     zrntokusyujimutoriatukaikbn ,         /* （連携用）特殊事務取扱区分 */
     zrnbsydrtencd ,         /* （連携用）募集代理店コード */
     zrnbsydrtenkjnm ,         /* （連携用）募集代理店漢字名称 */
     zrnatkisyagyskkjsosikicd ,         /* （連携用）扱者業績計上先組織コード */
     zrnatkisyadrtenatkiwari ,         /* （連携用）扱者代理店扱割合 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnkinyuukikancd ,         /* （連携用）金融機関コード */
     zrninfositencd ,         /* （連携用）（情報系）支店コード */
     zrncifcd ,         /* （連携用）ＣＩＦコード */
     zrnkjkyknm10 ,         /* （連携用）漢字契約者名（１０文字） */
     zrnkthhbhyouji ,         /* （連携用）決定保留不備表示 */
     zrnsrhhbhyouji ,         /* （連携用）成立保留不備表示 */
     zrnmossyumtkktymd ,         /* （連携用）申込消滅確定年月日 */
     zrndairitenjimusyocd ,         /* （連携用）代理店事務所コード */
     zrntsrybnwari ,         /* （連携用）手数料分割割合 */
     zrndrtenkeijyouym ,         /* （連携用）代理店計上年月 */
     zrnkydatkidairitencd ,         /* （連携用）共同扱代理店コード */
     zrndaihyoubosyuunincd ,         /* （連携用）代表募集人コード */
     zrntansyukukjdhybosyuunm ,         /* （連携用）短縮漢字代表募集人名 */
     zrnknkyknm15 ,         /* （連携用）カナ契約者名（１５文字） */
     zrndakuhikettikekkacd ,         /* （連携用）諾否決定結果コード */
     zrndkhktiymd ,         /* （連携用）諾否決定年月日 */
     zrntoukeiyousinsakbn ,         /* （連携用）統計用診査区分 */
     zrnhonninkknnkbn ,         /* （連携用）本人確認区分 */
     zrnnstkarihyj ,         /* （連携用）年金支払特約有表示 */
     zrnnstknkkkn ,         /* （連携用）年金支払特約年金期間 */
     zrndrtentsryhushrkykhyouji ,         /* （連携用）代理店手数料不支払契約表示 */
     zrnnyknkanskanouhyouji ,         /* （連携用）入金勧奨可能表示 */
     zrndshukahyouji ,         /* （連携用）ＤＳ付加表示 */
     zrnstdairiseikyuutkykarihyj ,         /* （連携用）指定代理請求特約有表示 */
     zrnkyksyanen ,         /* （連携用）契約者年令 */
     zrnkyksyaseikbn ,         /* （連携用）契約者性別区分 */
     zrnhhknseiymd ,         /* （連携用）被保険者生年月日 */
     zrndrtenpaperlessmoshyj ,         /* （連携用）代理店ペーパーレス申込表示 */
     zrndrtenmostousyaukeymd ,         /* （連携用）代理店申込書当社受付年月日 */
     zrnkyktuuka ,         /* （連携用）契約通貨 */
     zrnhrktuuka ,         /* （連携用）払込通貨 */
     zrnsykihrkpgaika ,         /* （連携用）初回払込Ｐ（外貨） */
     zrnyennykntkarihyouji ,         /* （連携用）円入金特約有表示 */
     zrngaikanykntkarihyouji ,         /* （連携用）外貨入金特約有表示 */
     zrnkihonsgaika ,         /* （連携用）基本Ｓ（外貨） */
     zrntekiyoukawaserate ,         /* （連携用）適用為替レート */
     zrnkawaseratetekiyouymd ,         /* （連携用）為替レート適用年月日 */
     zrnmkhyoutiyensysnikoukbn ,         /* （連携用）目標到達時円建終身保障移行区分 */
     zrnsyksbyensitihsyutkykhyj ,         /* （連携用）初期死亡時円換算最低保証特約有表示 */
     zrnjyudkaigomehrtkarihyj ,         /* （連携用）重度介護前払特約有表示 */
     zrnsykihrkpsiteituuka ,         /* （連携用）初回払込Ｐ（指定通貨） */
     zrnteirituhaibunwari ,         /* （連携用）定率部分配分割合 */
     zrnsueokikknkbn ,         /* （連携用）据置期間区分 */
     zrnnksyuruikbn1 ,         /* （連携用）年金種類区分（１文字） */
     zrndairitenkbtinfo1 ,         /* （連携用）代理店個別情報１ */
     zrndairitenkbtinfo2 ,         /* （連携用）代理店個別情報２ */
     zrndairitenkbtinfo3 ,         /* （連携用）代理店個別情報３ */
     zrnyohurimiryou ,         /* （連携用）預振未了 */
     zrnkznyuuryokuymd ,         /* （連携用）口座入力年月日 */
     zrnsetaitemosno ,         /* （連携用）セット相手申込番号 */
     zrnyakkanjyuryouhoukbn ,         /* （連携用）約款受領方法区分 */
     zrnyakkanbunsyono ,         /* （連携用）約款文書番号 */
     zrnkzhuritourokuhoukbn ,         /* （連携用）口座振替登録方法区分 */
     zrndai1hknkkn ,         /* （連携用）第１保険期間 */
     zrncreditnyuuryokuymd ,         /* （連携用）クレジット入力年月日 */
     zrncreditmiryou ,         /* （連携用）クレカ未了 */
     zrncredittrkhoukbn ,         /* （連携用）クレジット登録方法区分 */
     zrncardbrandkbn ,         /* （連携用）カードブランド */
     zrncarddatasousinymd ,         /* （連携用）カードデータ送信日 */
     zrnkykdrtkykarihyj ,         /* （連携用）契約者代理特約有表示 */
     zrnkzktrkservicekbn ,         /* （連携用）ご家族登録サービス区分 */
     zrnteikisiharaiarihyj ,         /* （連携用）定期支払特約有表示 */
     zrnteikishrkinshrtuukakbn ,         /* （連携用）定期支払金支払通貨区分 */
     zrnteikisiharaikin ,         /* （連携用）定期支払金 */
     zrnkoureikzksetumeihoukbn ,         /* （連携用）高齢者ご家族等説明方法区分 */
     zrnkoureimndnhukusuukaikbn ,         /* （連携用）高齢者面談複数回実施区分 */
     zrnkoureitratkisyaigidskkbn ,         /* （連携用）高齢者取扱者以外同席区分 */
     zrnyobiv53           /* （連携用）予備項目Ｖ５３ */
FROM ZT_DrtenIpToukeiRn_Z;