CREATE VIEW IW_KhKzktrkKykDrHnkWk AS SELECT
     kouteikanriid ,         /* 工程管理ＩＤ */
     syono ,         /* 証券番号 */
     skssakuseiymd ,         /* 請求書作成日 */
     mousideninkbn ,         /* 申出人区分 */
     teiseikbn ,         /* 訂正区分 */
     trkkzkttdkkbn1 ,         /* 登録家族手続区分１ */
     trkkzknmkn1 ,         /* 登録家族名（カナ）１ */
     trkkzknmkj1 ,         /* 登録家族名（漢字）１ */
     trkkzknmkjkhukakbn1 ,         /* 登録家族名漢字化不可区分１ */
     trkkzkseiymd1 ,         /* 登録家族生年月日１ */
     trkkzksei1 ,         /* 登録家族性別１ */
     trkkzkyno1 ,         /* 登録家族郵便番号１ */
     trkkzkadr1kj1 ,         /* 登録家族住所１（漢字）１ */
     trkkzkadr2kj1 ,         /* 登録家族住所２（漢字）１ */
     trkkzkadr3kj1 ,         /* 登録家族住所３（漢字）１ */
     trkkzktelno1 ,         /* 登録家族電話番号１ */
     trkkzktdk1 ,         /* 登録家族続柄１ */
     trkkzkttdkkbn2 ,         /* 登録家族手続区分２ */
     trkkzknmkn2 ,         /* 登録家族名（カナ）２ */
     trkkzknmkj2 ,         /* 登録家族名（漢字）２ */
     trkkzknmkjkhukakbn2 ,         /* 登録家族名漢字化不可区分２ */
     trkkzkseiymd2 ,         /* 登録家族生年月日２ */
     trkkzksei2 ,         /* 登録家族性別２ */
     trkkzktdk2 ,         /* 登録家族続柄２ */
     trkkzkyno2 ,         /* 登録家族郵便番号２ */
     trkkzkadr1kj2 ,         /* 登録家族住所１（漢字）２ */
     trkkzkadr2kj2 ,         /* 登録家族住所２（漢字）２ */
     trkkzkadr3kj2 ,         /* 登録家族住所３（漢字）２ */
     trkkzktelno2 ,         /* 登録家族電話番号２ */
     kykdrtkykttdkkbn ,         /* 契約者代理特約手続区分 */
     kykdrkbn ,         /* 契約者代理人区分 */
     kykdairinmkn ,         /* 契約者代理人名（カナ） */
     kykdairinmkj ,         /* 契約者代理人名（漢字） */
     kykdrnmkjkhukakbn ,         /* 契約者代理人名漢字化不可区分 */
     kykdrseiymd ,         /* 契約者代理人生年月日 */
     kykdryno ,         /* 契約者代理人郵便番号 */
     kykdradr1kj ,         /* 契約者代理人住所１（漢字） */
     kykdradr2kj ,         /* 契約者代理人住所２（漢字） */
     kykdradr3kj ,         /* 契約者代理人住所３（漢字） */
     shsnmkj ,         /* 送付先氏名（漢字） */
     shskyno ,         /* 送付先郵便番号 */
     shsadr1kj ,         /* 送付先住所１（漢字）（３０桁） */
     shsadr2kj ,         /* 送付先住所２（漢字）（３０桁） */
     shsadr3kj ,         /* 送付先住所３（漢字）（３０桁） */
     honninkakninkekkakbn ,         /* 本人確認結果区分 */
     tyhysakuseiyhkbn ,         /* 帳票作成要否区分 */
     hassoukbn ,         /* 発送区分 */
     zenkaisyorikekkakbn ,         /* 前回処理結果区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     trkkzktsindousiteikbn1 ,         /* 登録家族通信先同一指定区分１ */
     trkkzktsindousiteikbn2           /* 登録家族通信先同一指定区分２ */
FROM IW_KhKzktrkKykDrHnkWk_Z;