CREATE VIEW ZT_SinkeiyakuSyoukenSuii2Rn AS SELECT
     zrnsyono ,         /* （連携用）証券番号 */
     zrntyouhyouymd ,         /* （連携用）帳票作成日 */
     zrnsuiihyouptn ,         /* （連携用）推移表パターン */
     zrnsuiihyousykbn ,         /* （連携用）推移表種別区分 */
     zrnsuiihyousyono ,         /* （連携用）推移表証券番号 */
     zrnytirrtcalckijyunrrt ,         /* （連携用）予定利率計算基準利率 */
     zrnwkwsrateyendaka ,         /* （連携用）解約返戻金為替レート（円高） */
     zrnwkwsrateyenkijyun ,         /* （連携用）解約返戻金為替レート（中央値） */
     zrnwkwsrateyenyasu ,         /* （連携用）解約返戻金為替レート（円安） */
     zrnkyktuukatype ,         /* （連携用）契約通貨タイプ */
     zrnkeikanensuu01 ,         /* （連携用）経過年数０１ */
     zrnhrkkknmnryumukbn01 ,         /* （連携用）払込期間満了有無区分０１ */
     zrnzennouzndkyen01 ,         /* （連携用）前納残高（円貨）０１ */
     zrnyenhrkgkgoukei01 ,         /* （連携用）円貨払込額の合計（円貨）０１ */
     zrnkihrkmp01 ,         /* （連携用）既払込保険料０１ */
     zrnw01 ,         /* （連携用）解約返戻金０１ */
     zrnwyenyendaka01 ,         /* （連携用）解約返戻金（円貨）円高０１ */
     zrnwyenkijun01 ,         /* （連携用）解約返戻金（円貨）中央値０１ */
     zrnwyenyenyasu01 ,         /* （連携用）解約返戻金（円貨）円安０１ */
     zrnkeikanensuu02 ,         /* （連携用）経過年数０２ */
     zrnhrkkknmnryumukbn02 ,         /* （連携用）払込期間満了有無区分０２ */
     zrnzennouzndkyen02 ,         /* （連携用）前納残高（円貨）０２ */
     zrnyenhrkgkgoukei02 ,         /* （連携用）円貨払込額の合計（円貨）０２ */
     zrnkihrkmp02 ,         /* （連携用）既払込保険料０２ */
     zrnw02 ,         /* （連携用）解約返戻金０２ */
     zrnwyenyendaka02 ,         /* （連携用）解約返戻金（円貨）円高０２ */
     zrnwyenkijun02 ,         /* （連携用）解約返戻金（円貨）中央値０２ */
     zrnwyenyenyasu02 ,         /* （連携用）解約返戻金（円貨）円安０２ */
     zrnkeikanensuu03 ,         /* （連携用）経過年数０３ */
     zrnhrkkknmnryumukbn03 ,         /* （連携用）払込期間満了有無区分０３ */
     zrnzennouzndkyen03 ,         /* （連携用）前納残高（円貨）０３ */
     zrnyenhrkgkgoukei03 ,         /* （連携用）円貨払込額の合計（円貨）０３ */
     zrnkihrkmp03 ,         /* （連携用）既払込保険料０３ */
     zrnw03 ,         /* （連携用）解約返戻金０３ */
     zrnwyenyendaka03 ,         /* （連携用）解約返戻金（円貨）円高０３ */
     zrnwyenkijun03 ,         /* （連携用）解約返戻金（円貨）中央値０３ */
     zrnwyenyenyasu03 ,         /* （連携用）解約返戻金（円貨）円安０３ */
     zrnkeikanensuu04 ,         /* （連携用）経過年数０４ */
     zrnhrkkknmnryumukbn04 ,         /* （連携用）払込期間満了有無区分０４ */
     zrnzennouzndkyen04 ,         /* （連携用）前納残高（円貨）０４ */
     zrnyenhrkgkgoukei04 ,         /* （連携用）円貨払込額の合計（円貨）０４ */
     zrnkihrkmp04 ,         /* （連携用）既払込保険料０４ */
     zrnw04 ,         /* （連携用）解約返戻金０４ */
     zrnwyenyendaka04 ,         /* （連携用）解約返戻金（円貨）円高０４ */
     zrnwyenkijun04 ,         /* （連携用）解約返戻金（円貨）中央値０４ */
     zrnwyenyenyasu04 ,         /* （連携用）解約返戻金（円貨）円安０４ */
     zrnkeikanensuu05 ,         /* （連携用）経過年数０５ */
     zrnhrkkknmnryumukbn05 ,         /* （連携用）払込期間満了有無区分０５ */
     zrnzennouzndkyen05 ,         /* （連携用）前納残高（円貨）０５ */
     zrnyenhrkgkgoukei05 ,         /* （連携用）円貨払込額の合計（円貨）０５ */
     zrnkihrkmp05 ,         /* （連携用）既払込保険料０５ */
     zrnw05 ,         /* （連携用）解約返戻金０５ */
     zrnwyenyendaka05 ,         /* （連携用）解約返戻金（円貨）円高０５ */
     zrnwyenkijun05 ,         /* （連携用）解約返戻金（円貨）中央値０５ */
     zrnwyenyenyasu05 ,         /* （連携用）解約返戻金（円貨）円安０５ */
     zrnkeikanensuu06 ,         /* （連携用）経過年数０６ */
     zrnhrkkknmnryumukbn06 ,         /* （連携用）払込期間満了有無区分０６ */
     zrnzennouzndkyen06 ,         /* （連携用）前納残高（円貨）０６ */
     zrnyenhrkgkgoukei06 ,         /* （連携用）円貨払込額の合計（円貨）０６ */
     zrnkihrkmp06 ,         /* （連携用）既払込保険料０６ */
     zrnw06 ,         /* （連携用）解約返戻金０６ */
     zrnwyenyendaka06 ,         /* （連携用）解約返戻金（円貨）円高０６ */
     zrnwyenkijun06 ,         /* （連携用）解約返戻金（円貨）中央値０６ */
     zrnwyenyenyasu06 ,         /* （連携用）解約返戻金（円貨）円安０６ */
     zrnkeikanensuu07 ,         /* （連携用）経過年数０７ */
     zrnhrkkknmnryumukbn07 ,         /* （連携用）払込期間満了有無区分０７ */
     zrnzennouzndkyen07 ,         /* （連携用）前納残高（円貨）０７ */
     zrnyenhrkgkgoukei07 ,         /* （連携用）円貨払込額の合計（円貨）０７ */
     zrnkihrkmp07 ,         /* （連携用）既払込保険料０７ */
     zrnw07 ,         /* （連携用）解約返戻金０７ */
     zrnwyenyendaka07 ,         /* （連携用）解約返戻金（円貨）円高０７ */
     zrnwyenkijun07 ,         /* （連携用）解約返戻金（円貨）中央値０７ */
     zrnwyenyenyasu07 ,         /* （連携用）解約返戻金（円貨）円安０７ */
     zrnkeikanensuu08 ,         /* （連携用）経過年数０８ */
     zrnhrkkknmnryumukbn08 ,         /* （連携用）払込期間満了有無区分０８ */
     zrnzennouzndkyen08 ,         /* （連携用）前納残高（円貨）０８ */
     zrnyenhrkgkgoukei08 ,         /* （連携用）円貨払込額の合計（円貨）０８ */
     zrnkihrkmp08 ,         /* （連携用）既払込保険料０８ */
     zrnw08 ,         /* （連携用）解約返戻金０８ */
     zrnwyenyendaka08 ,         /* （連携用）解約返戻金（円貨）円高０８ */
     zrnwyenkijun08 ,         /* （連携用）解約返戻金（円貨）中央値０８ */
     zrnwyenyenyasu08 ,         /* （連携用）解約返戻金（円貨）円安０８ */
     zrnkeikanensuu09 ,         /* （連携用）経過年数０９ */
     zrnhrkkknmnryumukbn09 ,         /* （連携用）払込期間満了有無区分０９ */
     zrnzennouzndkyen09 ,         /* （連携用）前納残高（円貨）０９ */
     zrnyenhrkgkgoukei09 ,         /* （連携用）円貨払込額の合計（円貨）０９ */
     zrnkihrkmp09 ,         /* （連携用）既払込保険料０９ */
     zrnw09 ,         /* （連携用）解約返戻金０９ */
     zrnwyenyendaka09 ,         /* （連携用）解約返戻金（円貨）円高０９ */
     zrnwyenkijun09 ,         /* （連携用）解約返戻金（円貨）中央値０９ */
     zrnwyenyenyasu09 ,         /* （連携用）解約返戻金（円貨）円安０９ */
     zrnkeikanensuu10 ,         /* （連携用）経過年数１０ */
     zrnhrkkknmnryumukbn10 ,         /* （連携用）払込期間満了有無区分１０ */
     zrnzennouzndkyen10 ,         /* （連携用）前納残高（円貨）１０ */
     zrnyenhrkgkgoukei10 ,         /* （連携用）円貨払込額の合計（円貨）１０ */
     zrnkihrkmp10 ,         /* （連携用）既払込保険料１０ */
     zrnw10 ,         /* （連携用）解約返戻金１０ */
     zrnwyenyendaka10 ,         /* （連携用）解約返戻金（円貨）円高１０ */
     zrnwyenkijun10 ,         /* （連携用）解約返戻金（円貨）中央値１０ */
     zrnwyenyenyasu10 ,         /* （連携用）解約返戻金（円貨）円安１０ */
     zrnkeikanensuu11 ,         /* （連携用）経過年数１１ */
     zrnhrkkknmnryumukbn11 ,         /* （連携用）払込期間満了有無区分１１ */
     zrnzennouzndkyen11 ,         /* （連携用）前納残高（円貨）１１ */
     zrnyenhrkgkgoukei11 ,         /* （連携用）円貨払込額の合計（円貨）１１ */
     zrnkihrkmp11 ,         /* （連携用）既払込保険料１１ */
     zrnw11 ,         /* （連携用）解約返戻金１１ */
     zrnwyenyendaka11 ,         /* （連携用）解約返戻金（円貨）円高１１ */
     zrnwyenkijun11 ,         /* （連携用）解約返戻金（円貨）中央値１１ */
     zrnwyenyenyasu11 ,         /* （連携用）解約返戻金（円貨）円安１１ */
     zrnkeikanensuu12 ,         /* （連携用）経過年数１２ */
     zrnhrkkknmnryumukbn12 ,         /* （連携用）払込期間満了有無区分１２ */
     zrnzennouzndkyen12 ,         /* （連携用）前納残高（円貨）１２ */
     zrnyenhrkgkgoukei12 ,         /* （連携用）円貨払込額の合計（円貨）１２ */
     zrnkihrkmp12 ,         /* （連携用）既払込保険料１２ */
     zrnw12 ,         /* （連携用）解約返戻金１２ */
     zrnwyenyendaka12 ,         /* （連携用）解約返戻金（円貨）円高１２ */
     zrnwyenkijun12 ,         /* （連携用）解約返戻金（円貨）中央値１２ */
     zrnwyenyenyasu12 ,         /* （連携用）解約返戻金（円貨）円安１２ */
     zrnkeikanensuu13 ,         /* （連携用）経過年数１３ */
     zrnhrkkknmnryumukbn13 ,         /* （連携用）払込期間満了有無区分１３ */
     zrnzennouzndkyen13 ,         /* （連携用）前納残高（円貨）１３ */
     zrnyenhrkgkgoukei13 ,         /* （連携用）円貨払込額の合計（円貨）１３ */
     zrnkihrkmp13 ,         /* （連携用）既払込保険料１３ */
     zrnw13 ,         /* （連携用）解約返戻金１３ */
     zrnwyenyendaka13 ,         /* （連携用）解約返戻金（円貨）円高１３ */
     zrnwyenkijun13 ,         /* （連携用）解約返戻金（円貨）中央値１３ */
     zrnwyenyenyasu13 ,         /* （連携用）解約返戻金（円貨）円安１３ */
     zrnkeikanensuu14 ,         /* （連携用）経過年数１４ */
     zrnhrkkknmnryumukbn14 ,         /* （連携用）払込期間満了有無区分１４ */
     zrnzennouzndkyen14 ,         /* （連携用）前納残高（円貨）１４ */
     zrnyenhrkgkgoukei14 ,         /* （連携用）円貨払込額の合計（円貨）１４ */
     zrnkihrkmp14 ,         /* （連携用）既払込保険料１４ */
     zrnw14 ,         /* （連携用）解約返戻金１４ */
     zrnwyenyendaka14 ,         /* （連携用）解約返戻金（円貨）円高１４ */
     zrnwyenkijun14 ,         /* （連携用）解約返戻金（円貨）中央値１４ */
     zrnwyenyenyasu14 ,         /* （連携用）解約返戻金（円貨）円安１４ */
     zrnkeikanensuu15 ,         /* （連携用）経過年数１５ */
     zrnhrkkknmnryumukbn15 ,         /* （連携用）払込期間満了有無区分１５ */
     zrnzennouzndkyen15 ,         /* （連携用）前納残高（円貨）１５ */
     zrnyenhrkgkgoukei15 ,         /* （連携用）円貨払込額の合計（円貨）１５ */
     zrnkihrkmp15 ,         /* （連携用）既払込保険料１５ */
     zrnw15 ,         /* （連携用）解約返戻金１５ */
     zrnwyenyendaka15 ,         /* （連携用）解約返戻金（円貨）円高１５ */
     zrnwyenkijun15 ,         /* （連携用）解約返戻金（円貨）中央値１５ */
     zrnwyenyenyasu15 ,         /* （連携用）解約返戻金（円貨）円安１５ */
     zrnkeikanensuu16 ,         /* （連携用）経過年数１６ */
     zrnhrkkknmnryumukbn16 ,         /* （連携用）払込期間満了有無区分１６ */
     zrnzennouzndkyen16 ,         /* （連携用）前納残高（円貨）１６ */
     zrnyenhrkgkgoukei16 ,         /* （連携用）円貨払込額の合計（円貨）１６ */
     zrnkihrkmp16 ,         /* （連携用）既払込保険料１６ */
     zrnw16 ,         /* （連携用）解約返戻金１６ */
     zrnwyenyendaka16 ,         /* （連携用）解約返戻金（円貨）円高１６ */
     zrnwyenkijun16 ,         /* （連携用）解約返戻金（円貨）中央値１６ */
     zrnwyenyenyasu16 ,         /* （連携用）解約返戻金（円貨）円安１６ */
     zrnkeikanensuu17 ,         /* （連携用）経過年数１７ */
     zrnhrkkknmnryumukbn17 ,         /* （連携用）払込期間満了有無区分１７ */
     zrnzennouzndkyen17 ,         /* （連携用）前納残高（円貨）１７ */
     zrnyenhrkgkgoukei17 ,         /* （連携用）円貨払込額の合計（円貨）１７ */
     zrnkihrkmp17 ,         /* （連携用）既払込保険料１７ */
     zrnw17 ,         /* （連携用）解約返戻金１７ */
     zrnwyenyendaka17 ,         /* （連携用）解約返戻金（円貨）円高１７ */
     zrnwyenkijun17 ,         /* （連携用）解約返戻金（円貨）中央値１７ */
     zrnwyenyenyasu17 ,         /* （連携用）解約返戻金（円貨）円安１７ */
     zrnkeikanensuu18 ,         /* （連携用）経過年数１８ */
     zrnhrkkknmnryumukbn18 ,         /* （連携用）払込期間満了有無区分１８ */
     zrnzennouzndkyen18 ,         /* （連携用）前納残高（円貨）１８ */
     zrnyenhrkgkgoukei18 ,         /* （連携用）円貨払込額の合計（円貨）１８ */
     zrnkihrkmp18 ,         /* （連携用）既払込保険料１８ */
     zrnw18 ,         /* （連携用）解約返戻金１８ */
     zrnwyenyendaka18 ,         /* （連携用）解約返戻金（円貨）円高１８ */
     zrnwyenkijun18 ,         /* （連携用）解約返戻金（円貨）中央値１８ */
     zrnwyenyenyasu18 ,         /* （連携用）解約返戻金（円貨）円安１８ */
     zrnkeikanensuu19 ,         /* （連携用）経過年数１９ */
     zrnhrkkknmnryumukbn19 ,         /* （連携用）払込期間満了有無区分１９ */
     zrnzennouzndkyen19 ,         /* （連携用）前納残高（円貨）１９ */
     zrnyenhrkgkgoukei19 ,         /* （連携用）円貨払込額の合計（円貨）１９ */
     zrnkihrkmp19 ,         /* （連携用）既払込保険料１９ */
     zrnw19 ,         /* （連携用）解約返戻金１９ */
     zrnwyenyendaka19 ,         /* （連携用）解約返戻金（円貨）円高１９ */
     zrnwyenkijun19 ,         /* （連携用）解約返戻金（円貨）中央値１９ */
     zrnwyenyenyasu19 ,         /* （連携用）解約返戻金（円貨）円安１９ */
     zrnkeikanensuu20 ,         /* （連携用）経過年数２０ */
     zrnhrkkknmnryumukbn20 ,         /* （連携用）払込期間満了有無区分２０ */
     zrnzennouzndkyen20 ,         /* （連携用）前納残高（円貨）２０ */
     zrnyenhrkgkgoukei20 ,         /* （連携用）円貨払込額の合計（円貨）２０ */
     zrnkihrkmp20 ,         /* （連携用）既払込保険料２０ */
     zrnw20 ,         /* （連携用）解約返戻金２０ */
     zrnwyenyendaka20 ,         /* （連携用）解約返戻金（円貨）円高２０ */
     zrnwyenkijun20 ,         /* （連携用）解約返戻金（円貨）中央値２０ */
     zrnwyenyenyasu20 ,         /* （連携用）解約返戻金（円貨）円安２０ */
     zrnkeikanensuu21 ,         /* （連携用）経過年数２１ */
     zrnhrkkknmnryumukbn21 ,         /* （連携用）払込期間満了有無区分２１ */
     zrnzennouzndkyen21 ,         /* （連携用）前納残高（円貨）２１ */
     zrnyenhrkgkgoukei21 ,         /* （連携用）円貨払込額の合計（円貨）２１ */
     zrnkihrkmp21 ,         /* （連携用）既払込保険料２１ */
     zrnw21 ,         /* （連携用）解約返戻金２１ */
     zrnwyenyendaka21 ,         /* （連携用）解約返戻金（円貨）円高２１ */
     zrnwyenkijun21 ,         /* （連携用）解約返戻金（円貨）中央値２１ */
     zrnwyenyenyasu21 ,         /* （連携用）解約返戻金（円貨）円安２１ */
     zrnkeikanensuu22 ,         /* （連携用）経過年数２２ */
     zrnhrkkknmnryumukbn22 ,         /* （連携用）払込期間満了有無区分２２ */
     zrnzennouzndkyen22 ,         /* （連携用）前納残高（円貨）２２ */
     zrnyenhrkgkgoukei22 ,         /* （連携用）円貨払込額の合計（円貨）２２ */
     zrnkihrkmp22 ,         /* （連携用）既払込保険料２２ */
     zrnw22 ,         /* （連携用）解約返戻金２２ */
     zrnwyenyendaka22 ,         /* （連携用）解約返戻金（円貨）円高２２ */
     zrnwyenkijun22 ,         /* （連携用）解約返戻金（円貨）中央値２２ */
     zrnwyenyenyasu22 ,         /* （連携用）解約返戻金（円貨）円安２２ */
     zrnyobiv188 ,         /* （連携用）予備項目Ｖ１８８ */
     zrnyobiv2           /* （連携用）予備項目Ｖ２ */
FROM ZT_SinkeiyakuSyoukenSuii2Rn_Z;