CREATE VIEW IT_SeihowebMizuhoMinyuuDtl AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     drtencd ,         /* 代理店コード */
     bosyuucd ,         /* 募集人コード */
     syoriym ,         /* 処理年月 */
     minyusyoriymd ,         /* 未入処理日 */
     bosyuuym ,         /* 募集年月 */
     kydatkikbnkj ,         /* 共同扱区分（漢字） */
     kyknm35keta ,         /* 契約者名（３５桁） */
     cifcd ,         /* ＣＩＦコード */
     pjytym ,         /* 保険料充当年月 */
     atesakinm ,         /* 宛先名 */
     minyujytymdyofuri ,         /* 未入充当年月（預振） */
     minyujytymdyofuriigi ,         /* 未入充当年月（預振以外） */
     hassinka ,         /* 発信課 */
     telno ,         /* 電話番号 */
     tntnm10keta ,         /* 担当者名（１０桁） */
     hrkkaisuukj ,         /* 払込回数（漢字） */
     hrkkeirokj ,         /* 払込経路（漢字） */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     knkimnyuuryu ,         /* 今回未入理由 */
     jikaiminyuuji ,         /* 次回未入時 */
     tntusygyouhaiinfo ,         /* 担当者業廃情報 */
     hrkkeirobtjhmidasi ,         /* 払込経路別情報見出し */
     hrkkeirobtjh ,         /* 払込経路別情報 */
     hknsyuruinm30keta ,         /* 保険種類名（３０桁） */
     drtenkanrisosikicd ,         /* 代理店管理組織コード */
     dbskyoteiym ,         /* ＤＢ削除予定年月 */
     keiyakuymd ,         /* 契約年月日 */
     hhknnmkj ,         /* 被保険者名（漢字） */
     tsintelno ,         /* 通信先電話番号 */
     dai2tsintelno ,         /* 第２通信先電話番号 */
     bankcd ,         /* 銀行コード */
     sitencd ,         /* 支店コード */
     yokinkbn ,         /* 預金種目区分 */
     kouzano ,         /* 口座番号 */
     hrkkaisuu ,         /* 払込回数 */
     hukkatukanoukknmnryymd ,         /* 復活可能期間満了年月日 */
     hjnkykhyj ,         /* 法人契約表示 */
     kykjyutikbn ,         /* 契約状態区分 */
     tsinkihontikucd ,         /* 通信先基本地区コード */
     kanjitsinkaiadr ,         /* 漢字通信先下位住所 */
     kzmeiginmkn ,         /* 口座名義人氏名（カナ） */
     jkiannaikg ,         /* 次回案内金額 */
     jkiannaikg$ ,         /* 次回案内金額(通貨型) */
     yykknmnryymd ,         /* 猶予期間満了日 */
     skymd ,         /* 失効年月日 */
     jhurikstkkahikbn ,         /* 自動振替貸付可否区分 */
     hukkatumoskahikbn ,         /* 復活申込可否区分 */
     ttdkkigenymd ,         /* 手続き期限年月日 */
     keikamon3keta ,         /* 経過月数（３桁） */
     misyuuhasseiym ,         /* 未収発生年月 */
     misyuujiyuu ,         /* 未収事由 */
     nexthurikaeymd ,         /* 次回振替日 */
     ikkatubaraikbn ,         /* 一括払区分 */
     ikkatubaraikaisuu ,         /* 一括払回数 */
     bosyuudairitengyousyukbn ,         /* 募集代理店業種区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_SeihowebMizuhoMinyuuDtl_Z;