CREATE VIEW BM_RateD AS SELECT
     palhokensyuruikigou ,         /* ＰＡＬ保険種類記号 */
     palhokensyuruikigousdicode ,         /* ＰＡＬ保険種類記号世代コード */
     palyoteiriritu ,         /* ＰＡＬ予定利率 */
     palpmencode ,         /* ＰＡＬＰ免コード */
     palharaikomikaisuu ,         /* ＰＡＬ払込回数 */
     palhhknsei ,         /* ＰＡＬ被保険者性別 */
     palkeiyakujihhknnen ,         /* ＰＡＬ契約時被保険者年令 */
     palsaimankihyouji ,         /* ＰＡＬ才満期契約表示 */
     palhokenkikan ,         /* ＰＡＬ保険期間 */
     palpharaikomikikan ,         /* ＰＡＬＰ払込期間 */
     paldnendo ,         /* ＰＡＬＤ年度 */
     paldratenaikakucode ,         /* ＰＡＬＤレート内定確定コード */
     drate00 ,         /* Ｄレート００ */
     drate01 ,         /* Ｄレート０１ */
     drate02 ,         /* Ｄレート０２ */
     drate03 ,         /* Ｄレート０３ */
     drate04 ,         /* Ｄレート０４ */
     drate05 ,         /* Ｄレート０５ */
     drate06 ,         /* Ｄレート０６ */
     drate07 ,         /* Ｄレート０７ */
     drate08 ,         /* Ｄレート０８ */
     drate09 ,         /* Ｄレート０９ */
     drate10 ,         /* Ｄレート１０ */
     drate11 ,         /* Ｄレート１１ */
     drate12 ,         /* Ｄレート１２ */
     drate13 ,         /* Ｄレート１３ */
     drate14 ,         /* Ｄレート１４ */
     drate15 ,         /* Ｄレート１５ */
     drate16 ,         /* Ｄレート１６ */
     drate17 ,         /* Ｄレート１７ */
     drate18 ,         /* Ｄレート１８ */
     drate19 ,         /* Ｄレート１９ */
     drate20 ,         /* Ｄレート２０ */
     drate21 ,         /* Ｄレート２１ */
     drate22 ,         /* Ｄレート２２ */
     drate23 ,         /* Ｄレート２３ */
     drate24 ,         /* Ｄレート２４ */
     drate25 ,         /* Ｄレート２５ */
     drate26 ,         /* Ｄレート２６ */
     drate27 ,         /* Ｄレート２７ */
     drate28 ,         /* Ｄレート２８ */
     drate29 ,         /* Ｄレート２９ */
     drate30 ,         /* Ｄレート３０ */
     drate31 ,         /* Ｄレート３１ */
     drate32 ,         /* Ｄレート３２ */
     drate33 ,         /* Ｄレート３３ */
     drate34 ,         /* Ｄレート３４ */
     drate35 ,         /* Ｄレート３５ */
     drate36 ,         /* Ｄレート３６ */
     drate37 ,         /* Ｄレート３７ */
     drate38 ,         /* Ｄレート３８ */
     drate39 ,         /* Ｄレート３９ */
     drate40 ,         /* Ｄレート４０ */
     drate41 ,         /* Ｄレート４１ */
     drate42 ,         /* Ｄレート４２ */
     drate43 ,         /* Ｄレート４３ */
     drate44 ,         /* Ｄレート４４ */
     drate45 ,         /* Ｄレート４５ */
     drate46 ,         /* Ｄレート４６ */
     drate47 ,         /* Ｄレート４７ */
     drate48 ,         /* Ｄレート４８ */
     drate49 ,         /* Ｄレート４９ */
     drate50 ,         /* Ｄレート５０ */
     drate51 ,         /* Ｄレート５１ */
     drate52 ,         /* Ｄレート５２ */
     drate53 ,         /* Ｄレート５３ */
     drate54 ,         /* Ｄレート５４ */
     drate55 ,         /* Ｄレート５５ */
     drate56 ,         /* Ｄレート５６ */
     drate57 ,         /* Ｄレート５７ */
     drate58 ,         /* Ｄレート５８ */
     drate59 ,         /* Ｄレート５９ */
     drate60 ,         /* Ｄレート６０ */
     drate61 ,         /* Ｄレート６１ */
     drate62 ,         /* Ｄレート６２ */
     drate63 ,         /* Ｄレート６３ */
     drate64 ,         /* Ｄレート６４ */
     drate65 ,         /* Ｄレート６５ */
     drate66 ,         /* Ｄレート６６ */
     drate67 ,         /* Ｄレート６７ */
     drate68 ,         /* Ｄレート６８ */
     drate69 ,         /* Ｄレート６９ */
     drate70 ,         /* Ｄレート７０ */
     drate71 ,         /* Ｄレート７１ */
     drate72 ,         /* Ｄレート７２ */
     drate73 ,         /* Ｄレート７３ */
     drate74 ,         /* Ｄレート７４ */
     drate75 ,         /* Ｄレート７５ */
     drate76 ,         /* Ｄレート７６ */
     drate77 ,         /* Ｄレート７７ */
     drate78 ,         /* Ｄレート７８ */
     drate79 ,         /* Ｄレート７９ */
     drate80 ,         /* Ｄレート８０ */
     drate81 ,         /* Ｄレート８１ */
     drate82 ,         /* Ｄレート８２ */
     drate83 ,         /* Ｄレート８３ */
     drate84 ,         /* Ｄレート８４ */
     drate85 ,         /* Ｄレート８５ */
     drate86 ,         /* Ｄレート８６ */
     drate87 ,         /* Ｄレート８７ */
     drate88 ,         /* Ｄレート８８ */
     drate89 ,         /* Ｄレート８９ */
     drate90 ,         /* Ｄレート９０ */
     drate91 ,         /* Ｄレート９１ */
     drate92 ,         /* Ｄレート９２ */
     drate93 ,         /* Ｄレート９３ */
     drate94 ,         /* Ｄレート９４ */
     drate95 ,         /* Ｄレート９５ */
     drate96 ,         /* Ｄレート９６ */
     drate97 ,         /* Ｄレート９７ */
     drate98 ,         /* Ｄレート９８ */
     drate99 ,         /* Ｄレート９９ */
     sisadrate00 ,         /* 死差Ｄレート００ */
     sisadrate01 ,         /* 死差Ｄレート０１ */
     sisadrate02 ,         /* 死差Ｄレート０２ */
     sisadrate03 ,         /* 死差Ｄレート０３ */
     sisadrate04 ,         /* 死差Ｄレート０４ */
     sisadrate05 ,         /* 死差Ｄレート０５ */
     sisadrate06 ,         /* 死差Ｄレート０６ */
     sisadrate07 ,         /* 死差Ｄレート０７ */
     sisadrate08 ,         /* 死差Ｄレート０８ */
     sisadrate09 ,         /* 死差Ｄレート０９ */
     sisadrate10 ,         /* 死差Ｄレート１０ */
     sisadrate11 ,         /* 死差Ｄレート１１ */
     sisadrate12 ,         /* 死差Ｄレート１２ */
     sisadrate13 ,         /* 死差Ｄレート１３ */
     sisadrate14 ,         /* 死差Ｄレート１４ */
     sisadrate15 ,         /* 死差Ｄレート１５ */
     sisadrate16 ,         /* 死差Ｄレート１６ */
     sisadrate17 ,         /* 死差Ｄレート１７ */
     sisadrate18 ,         /* 死差Ｄレート１８ */
     sisadrate19 ,         /* 死差Ｄレート１９ */
     sisadrate20 ,         /* 死差Ｄレート２０ */
     sisadrate21 ,         /* 死差Ｄレート２１ */
     sisadrate22 ,         /* 死差Ｄレート２２ */
     sisadrate23 ,         /* 死差Ｄレート２３ */
     sisadrate24 ,         /* 死差Ｄレート２４ */
     sisadrate25 ,         /* 死差Ｄレート２５ */
     sisadrate26 ,         /* 死差Ｄレート２６ */
     sisadrate27 ,         /* 死差Ｄレート２７ */
     sisadrate28 ,         /* 死差Ｄレート２８ */
     sisadrate29 ,         /* 死差Ｄレート２９ */
     sisadrate30 ,         /* 死差Ｄレート３０ */
     sisadrate31 ,         /* 死差Ｄレート３１ */
     sisadrate32 ,         /* 死差Ｄレート３２ */
     sisadrate33 ,         /* 死差Ｄレート３３ */
     sisadrate34 ,         /* 死差Ｄレート３４ */
     sisadrate35 ,         /* 死差Ｄレート３５ */
     sisadrate36 ,         /* 死差Ｄレート３６ */
     sisadrate37 ,         /* 死差Ｄレート３７ */
     sisadrate38 ,         /* 死差Ｄレート３８ */
     sisadrate39 ,         /* 死差Ｄレート３９ */
     sisadrate40 ,         /* 死差Ｄレート４０ */
     sisadrate41 ,         /* 死差Ｄレート４１ */
     sisadrate42 ,         /* 死差Ｄレート４２ */
     sisadrate43 ,         /* 死差Ｄレート４３ */
     sisadrate44 ,         /* 死差Ｄレート４４ */
     sisadrate45 ,         /* 死差Ｄレート４５ */
     sisadrate46 ,         /* 死差Ｄレート４６ */
     sisadrate47 ,         /* 死差Ｄレート４７ */
     sisadrate48 ,         /* 死差Ｄレート４８ */
     sisadrate49 ,         /* 死差Ｄレート４９ */
     sisadrate50 ,         /* 死差Ｄレート５０ */
     sisadrate51 ,         /* 死差Ｄレート５１ */
     sisadrate52 ,         /* 死差Ｄレート５２ */
     sisadrate53 ,         /* 死差Ｄレート５３ */
     sisadrate54 ,         /* 死差Ｄレート５４ */
     sisadrate55 ,         /* 死差Ｄレート５５ */
     sisadrate56 ,         /* 死差Ｄレート５６ */
     sisadrate57 ,         /* 死差Ｄレート５７ */
     sisadrate58 ,         /* 死差Ｄレート５８ */
     sisadrate59 ,         /* 死差Ｄレート５９ */
     sisadrate60 ,         /* 死差Ｄレート６０ */
     sisadrate61 ,         /* 死差Ｄレート６１ */
     sisadrate62 ,         /* 死差Ｄレート６２ */
     sisadrate63 ,         /* 死差Ｄレート６３ */
     sisadrate64 ,         /* 死差Ｄレート６４ */
     sisadrate65 ,         /* 死差Ｄレート６５ */
     sisadrate66 ,         /* 死差Ｄレート６６ */
     sisadrate67 ,         /* 死差Ｄレート６７ */
     sisadrate68 ,         /* 死差Ｄレート６８ */
     sisadrate69 ,         /* 死差Ｄレート６９ */
     sisadrate70 ,         /* 死差Ｄレート７０ */
     sisadrate71 ,         /* 死差Ｄレート７１ */
     sisadrate72 ,         /* 死差Ｄレート７２ */
     sisadrate73 ,         /* 死差Ｄレート７３ */
     sisadrate74 ,         /* 死差Ｄレート７４ */
     sisadrate75 ,         /* 死差Ｄレート７５ */
     sisadrate76 ,         /* 死差Ｄレート７６ */
     sisadrate77 ,         /* 死差Ｄレート７７ */
     sisadrate78 ,         /* 死差Ｄレート７８ */
     sisadrate79 ,         /* 死差Ｄレート７９ */
     sisadrate80 ,         /* 死差Ｄレート８０ */
     sisadrate81 ,         /* 死差Ｄレート８１ */
     sisadrate82 ,         /* 死差Ｄレート８２ */
     sisadrate83 ,         /* 死差Ｄレート８３ */
     sisadrate84 ,         /* 死差Ｄレート８４ */
     sisadrate85 ,         /* 死差Ｄレート８５ */
     sisadrate86 ,         /* 死差Ｄレート８６ */
     sisadrate87 ,         /* 死差Ｄレート８７ */
     sisadrate88 ,         /* 死差Ｄレート８８ */
     sisadrate89 ,         /* 死差Ｄレート８９ */
     sisadrate90 ,         /* 死差Ｄレート９０ */
     sisadrate91 ,         /* 死差Ｄレート９１ */
     sisadrate92 ,         /* 死差Ｄレート９２ */
     sisadrate93 ,         /* 死差Ｄレート９３ */
     sisadrate94 ,         /* 死差Ｄレート９４ */
     sisadrate95 ,         /* 死差Ｄレート９５ */
     sisadrate96 ,         /* 死差Ｄレート９６ */
     sisadrate97 ,         /* 死差Ｄレート９７ */
     sisadrate98 ,         /* 死差Ｄレート９８ */
     sisadrate99 ,         /* 死差Ｄレート９９ */
     risadrate00 ,         /* 利差Ｄレート００ */
     risadrate01 ,         /* 利差Ｄレート０１ */
     risadrate02 ,         /* 利差Ｄレート０２ */
     risadrate03 ,         /* 利差Ｄレート０３ */
     risadrate04 ,         /* 利差Ｄレート０４ */
     risadrate05 ,         /* 利差Ｄレート０５ */
     risadrate06 ,         /* 利差Ｄレート０６ */
     risadrate07 ,         /* 利差Ｄレート０７ */
     risadrate08 ,         /* 利差Ｄレート０８ */
     risadrate09 ,         /* 利差Ｄレート０９ */
     risadrate10 ,         /* 利差Ｄレート１０ */
     risadrate11 ,         /* 利差Ｄレート１１ */
     risadrate12 ,         /* 利差Ｄレート１２ */
     risadrate13 ,         /* 利差Ｄレート１３ */
     risadrate14 ,         /* 利差Ｄレート１４ */
     risadrate15 ,         /* 利差Ｄレート１５ */
     risadrate16 ,         /* 利差Ｄレート１６ */
     risadrate17 ,         /* 利差Ｄレート１７ */
     risadrate18 ,         /* 利差Ｄレート１８ */
     risadrate19 ,         /* 利差Ｄレート１９ */
     risadrate20 ,         /* 利差Ｄレート２０ */
     risadrate21 ,         /* 利差Ｄレート２１ */
     risadrate22 ,         /* 利差Ｄレート２２ */
     risadrate23 ,         /* 利差Ｄレート２３ */
     risadrate24 ,         /* 利差Ｄレート２４ */
     risadrate25 ,         /* 利差Ｄレート２５ */
     risadrate26 ,         /* 利差Ｄレート２６ */
     risadrate27 ,         /* 利差Ｄレート２７ */
     risadrate28 ,         /* 利差Ｄレート２８ */
     risadrate29 ,         /* 利差Ｄレート２９ */
     risadrate30 ,         /* 利差Ｄレート３０ */
     risadrate31 ,         /* 利差Ｄレート３１ */
     risadrate32 ,         /* 利差Ｄレート３２ */
     risadrate33 ,         /* 利差Ｄレート３３ */
     risadrate34 ,         /* 利差Ｄレート３４ */
     risadrate35 ,         /* 利差Ｄレート３５ */
     risadrate36 ,         /* 利差Ｄレート３６ */
     risadrate37 ,         /* 利差Ｄレート３７ */
     risadrate38 ,         /* 利差Ｄレート３８ */
     risadrate39 ,         /* 利差Ｄレート３９ */
     risadrate40 ,         /* 利差Ｄレート４０ */
     risadrate41 ,         /* 利差Ｄレート４１ */
     risadrate42 ,         /* 利差Ｄレート４２ */
     risadrate43 ,         /* 利差Ｄレート４３ */
     risadrate44 ,         /* 利差Ｄレート４４ */
     risadrate45 ,         /* 利差Ｄレート４５ */
     risadrate46 ,         /* 利差Ｄレート４６ */
     risadrate47 ,         /* 利差Ｄレート４７ */
     risadrate48 ,         /* 利差Ｄレート４８ */
     risadrate49 ,         /* 利差Ｄレート４９ */
     risadrate50 ,         /* 利差Ｄレート５０ */
     risadrate51 ,         /* 利差Ｄレート５１ */
     risadrate52 ,         /* 利差Ｄレート５２ */
     risadrate53 ,         /* 利差Ｄレート５３ */
     risadrate54 ,         /* 利差Ｄレート５４ */
     risadrate55 ,         /* 利差Ｄレート５５ */
     risadrate56 ,         /* 利差Ｄレート５６ */
     risadrate57 ,         /* 利差Ｄレート５７ */
     risadrate58 ,         /* 利差Ｄレート５８ */
     risadrate59 ,         /* 利差Ｄレート５９ */
     risadrate60 ,         /* 利差Ｄレート６０ */
     risadrate61 ,         /* 利差Ｄレート６１ */
     risadrate62 ,         /* 利差Ｄレート６２ */
     risadrate63 ,         /* 利差Ｄレート６３ */
     risadrate64 ,         /* 利差Ｄレート６４ */
     risadrate65 ,         /* 利差Ｄレート６５ */
     risadrate66 ,         /* 利差Ｄレート６６ */
     risadrate67 ,         /* 利差Ｄレート６７ */
     risadrate68 ,         /* 利差Ｄレート６８ */
     risadrate69 ,         /* 利差Ｄレート６９ */
     risadrate70 ,         /* 利差Ｄレート７０ */
     risadrate71 ,         /* 利差Ｄレート７１ */
     risadrate72 ,         /* 利差Ｄレート７２ */
     risadrate73 ,         /* 利差Ｄレート７３ */
     risadrate74 ,         /* 利差Ｄレート７４ */
     risadrate75 ,         /* 利差Ｄレート７５ */
     risadrate76 ,         /* 利差Ｄレート７６ */
     risadrate77 ,         /* 利差Ｄレート７７ */
     risadrate78 ,         /* 利差Ｄレート７８ */
     risadrate79 ,         /* 利差Ｄレート７９ */
     risadrate80 ,         /* 利差Ｄレート８０ */
     risadrate81 ,         /* 利差Ｄレート８１ */
     risadrate82 ,         /* 利差Ｄレート８２ */
     risadrate83 ,         /* 利差Ｄレート８３ */
     risadrate84 ,         /* 利差Ｄレート８４ */
     risadrate85 ,         /* 利差Ｄレート８５ */
     risadrate86 ,         /* 利差Ｄレート８６ */
     risadrate87 ,         /* 利差Ｄレート８７ */
     risadrate88 ,         /* 利差Ｄレート８８ */
     risadrate89 ,         /* 利差Ｄレート８９ */
     risadrate90 ,         /* 利差Ｄレート９０ */
     risadrate91 ,         /* 利差Ｄレート９１ */
     risadrate92 ,         /* 利差Ｄレート９２ */
     risadrate93 ,         /* 利差Ｄレート９３ */
     risadrate94 ,         /* 利差Ｄレート９４ */
     risadrate95 ,         /* 利差Ｄレート９５ */
     risadrate96 ,         /* 利差Ｄレート９６ */
     risadrate97 ,         /* 利差Ｄレート９７ */
     risadrate98 ,         /* 利差Ｄレート９８ */
     risadrate99 ,         /* 利差Ｄレート９９ */
     hisadrate00 ,         /* 費差Ｄレート００ */
     hisadrate01 ,         /* 費差Ｄレート０１ */
     hisadrate02 ,         /* 費差Ｄレート０２ */
     hisadrate03 ,         /* 費差Ｄレート０３ */
     hisadrate04 ,         /* 費差Ｄレート０４ */
     hisadrate05 ,         /* 費差Ｄレート０５ */
     hisadrate06 ,         /* 費差Ｄレート０６ */
     hisadrate07 ,         /* 費差Ｄレート０７ */
     hisadrate08 ,         /* 費差Ｄレート０８ */
     hisadrate09 ,         /* 費差Ｄレート０９ */
     hisadrate10 ,         /* 費差Ｄレート１０ */
     hisadrate11 ,         /* 費差Ｄレート１１ */
     hisadrate12 ,         /* 費差Ｄレート１２ */
     hisadrate13 ,         /* 費差Ｄレート１３ */
     hisadrate14 ,         /* 費差Ｄレート１４ */
     hisadrate15 ,         /* 費差Ｄレート１５ */
     hisadrate16 ,         /* 費差Ｄレート１６ */
     hisadrate17 ,         /* 費差Ｄレート１７ */
     hisadrate18 ,         /* 費差Ｄレート１８ */
     hisadrate19 ,         /* 費差Ｄレート１９ */
     hisadrate20 ,         /* 費差Ｄレート２０ */
     hisadrate21 ,         /* 費差Ｄレート２１ */
     hisadrate22 ,         /* 費差Ｄレート２２ */
     hisadrate23 ,         /* 費差Ｄレート２３ */
     hisadrate24 ,         /* 費差Ｄレート２４ */
     hisadrate25 ,         /* 費差Ｄレート２５ */
     hisadrate26 ,         /* 費差Ｄレート２６ */
     hisadrate27 ,         /* 費差Ｄレート２７ */
     hisadrate28 ,         /* 費差Ｄレート２８ */
     hisadrate29 ,         /* 費差Ｄレート２９ */
     hisadrate30 ,         /* 費差Ｄレート３０ */
     hisadrate31 ,         /* 費差Ｄレート３１ */
     hisadrate32 ,         /* 費差Ｄレート３２ */
     hisadrate33 ,         /* 費差Ｄレート３３ */
     hisadrate34 ,         /* 費差Ｄレート３４ */
     hisadrate35 ,         /* 費差Ｄレート３５ */
     hisadrate36 ,         /* 費差Ｄレート３６ */
     hisadrate37 ,         /* 費差Ｄレート３７ */
     hisadrate38 ,         /* 費差Ｄレート３８ */
     hisadrate39 ,         /* 費差Ｄレート３９ */
     hisadrate40 ,         /* 費差Ｄレート４０ */
     hisadrate41 ,         /* 費差Ｄレート４１ */
     hisadrate42 ,         /* 費差Ｄレート４２ */
     hisadrate43 ,         /* 費差Ｄレート４３ */
     hisadrate44 ,         /* 費差Ｄレート４４ */
     hisadrate45 ,         /* 費差Ｄレート４５ */
     hisadrate46 ,         /* 費差Ｄレート４６ */
     hisadrate47 ,         /* 費差Ｄレート４７ */
     hisadrate48 ,         /* 費差Ｄレート４８ */
     hisadrate49 ,         /* 費差Ｄレート４９ */
     hisadrate50 ,         /* 費差Ｄレート５０ */
     hisadrate51 ,         /* 費差Ｄレート５１ */
     hisadrate52 ,         /* 費差Ｄレート５２ */
     hisadrate53 ,         /* 費差Ｄレート５３ */
     hisadrate54 ,         /* 費差Ｄレート５４ */
     hisadrate55 ,         /* 費差Ｄレート５５ */
     hisadrate56 ,         /* 費差Ｄレート５６ */
     hisadrate57 ,         /* 費差Ｄレート５７ */
     hisadrate58 ,         /* 費差Ｄレート５８ */
     hisadrate59 ,         /* 費差Ｄレート５９ */
     hisadrate60 ,         /* 費差Ｄレート６０ */
     hisadrate61 ,         /* 費差Ｄレート６１ */
     hisadrate62 ,         /* 費差Ｄレート６２ */
     hisadrate63 ,         /* 費差Ｄレート６３ */
     hisadrate64 ,         /* 費差Ｄレート６４ */
     hisadrate65 ,         /* 費差Ｄレート６５ */
     hisadrate66 ,         /* 費差Ｄレート６６ */
     hisadrate67 ,         /* 費差Ｄレート６７ */
     hisadrate68 ,         /* 費差Ｄレート６８ */
     hisadrate69 ,         /* 費差Ｄレート６９ */
     hisadrate70 ,         /* 費差Ｄレート７０ */
     hisadrate71 ,         /* 費差Ｄレート７１ */
     hisadrate72 ,         /* 費差Ｄレート７２ */
     hisadrate73 ,         /* 費差Ｄレート７３ */
     hisadrate74 ,         /* 費差Ｄレート７４ */
     hisadrate75 ,         /* 費差Ｄレート７５ */
     hisadrate76 ,         /* 費差Ｄレート７６ */
     hisadrate77 ,         /* 費差Ｄレート７７ */
     hisadrate78 ,         /* 費差Ｄレート７８ */
     hisadrate79 ,         /* 費差Ｄレート７９ */
     hisadrate80 ,         /* 費差Ｄレート８０ */
     hisadrate81 ,         /* 費差Ｄレート８１ */
     hisadrate82 ,         /* 費差Ｄレート８２ */
     hisadrate83 ,         /* 費差Ｄレート８３ */
     hisadrate84 ,         /* 費差Ｄレート８４ */
     hisadrate85 ,         /* 費差Ｄレート８５ */
     hisadrate86 ,         /* 費差Ｄレート８６ */
     hisadrate87 ,         /* 費差Ｄレート８７ */
     hisadrate88 ,         /* 費差Ｄレート８８ */
     hisadrate89 ,         /* 費差Ｄレート８９ */
     hisadrate90 ,         /* 費差Ｄレート９０ */
     hisadrate91 ,         /* 費差Ｄレート９１ */
     hisadrate92 ,         /* 費差Ｄレート９２ */
     hisadrate93 ,         /* 費差Ｄレート９３ */
     hisadrate94 ,         /* 費差Ｄレート９４ */
     hisadrate95 ,         /* 費差Ｄレート９５ */
     hisadrate96 ,         /* 費差Ｄレート９６ */
     hisadrate97 ,         /* 費差Ｄレート９７ */
     hisadrate98 ,         /* 費差Ｄレート９８ */
     hisadrate99 ,         /* 費差Ｄレート９９ */
     dyouvrate00 ,         /* Ｄ用Ｖレート００ */
     dyouvrate01 ,         /* Ｄ用Ｖレート０１ */
     dyouvrate02 ,         /* Ｄ用Ｖレート０２ */
     dyouvrate03 ,         /* Ｄ用Ｖレート０３ */
     dyouvrate04 ,         /* Ｄ用Ｖレート０４ */
     dyouvrate05 ,         /* Ｄ用Ｖレート０５ */
     dyouvrate06 ,         /* Ｄ用Ｖレート０６ */
     dyouvrate07 ,         /* Ｄ用Ｖレート０７ */
     dyouvrate08 ,         /* Ｄ用Ｖレート０８ */
     dyouvrate09 ,         /* Ｄ用Ｖレート０９ */
     dyouvrate10 ,         /* Ｄ用Ｖレート１０ */
     dyouvrate11 ,         /* Ｄ用Ｖレート１１ */
     dyouvrate12 ,         /* Ｄ用Ｖレート１２ */
     dyouvrate13 ,         /* Ｄ用Ｖレート１３ */
     dyouvrate14 ,         /* Ｄ用Ｖレート１４ */
     dyouvrate15 ,         /* Ｄ用Ｖレート１５ */
     dyouvrate16 ,         /* Ｄ用Ｖレート１６ */
     dyouvrate17 ,         /* Ｄ用Ｖレート１７ */
     dyouvrate18 ,         /* Ｄ用Ｖレート１８ */
     dyouvrate19 ,         /* Ｄ用Ｖレート１９ */
     dyouvrate20 ,         /* Ｄ用Ｖレート２０ */
     dyouvrate21 ,         /* Ｄ用Ｖレート２１ */
     dyouvrate22 ,         /* Ｄ用Ｖレート２２ */
     dyouvrate23 ,         /* Ｄ用Ｖレート２３ */
     dyouvrate24 ,         /* Ｄ用Ｖレート２４ */
     dyouvrate25 ,         /* Ｄ用Ｖレート２５ */
     dyouvrate26 ,         /* Ｄ用Ｖレート２６ */
     dyouvrate27 ,         /* Ｄ用Ｖレート２７ */
     dyouvrate28 ,         /* Ｄ用Ｖレート２８ */
     dyouvrate29 ,         /* Ｄ用Ｖレート２９ */
     dyouvrate30 ,         /* Ｄ用Ｖレート３０ */
     dyouvrate31 ,         /* Ｄ用Ｖレート３１ */
     dyouvrate32 ,         /* Ｄ用Ｖレート３２ */
     dyouvrate33 ,         /* Ｄ用Ｖレート３３ */
     dyouvrate34 ,         /* Ｄ用Ｖレート３４ */
     dyouvrate35 ,         /* Ｄ用Ｖレート３５ */
     dyouvrate36 ,         /* Ｄ用Ｖレート３６ */
     dyouvrate37 ,         /* Ｄ用Ｖレート３７ */
     dyouvrate38 ,         /* Ｄ用Ｖレート３８ */
     dyouvrate39 ,         /* Ｄ用Ｖレート３９ */
     dyouvrate40 ,         /* Ｄ用Ｖレート４０ */
     dyouvrate41 ,         /* Ｄ用Ｖレート４１ */
     dyouvrate42 ,         /* Ｄ用Ｖレート４２ */
     dyouvrate43 ,         /* Ｄ用Ｖレート４３ */
     dyouvrate44 ,         /* Ｄ用Ｖレート４４ */
     dyouvrate45 ,         /* Ｄ用Ｖレート４５ */
     dyouvrate46 ,         /* Ｄ用Ｖレート４６ */
     dyouvrate47 ,         /* Ｄ用Ｖレート４７ */
     dyouvrate48 ,         /* Ｄ用Ｖレート４８ */
     dyouvrate49 ,         /* Ｄ用Ｖレート４９ */
     dyouvrate50 ,         /* Ｄ用Ｖレート５０ */
     dyouvrate51 ,         /* Ｄ用Ｖレート５１ */
     dyouvrate52 ,         /* Ｄ用Ｖレート５２ */
     dyouvrate53 ,         /* Ｄ用Ｖレート５３ */
     dyouvrate54 ,         /* Ｄ用Ｖレート５４ */
     dyouvrate55 ,         /* Ｄ用Ｖレート５５ */
     dyouvrate56 ,         /* Ｄ用Ｖレート５６ */
     dyouvrate57 ,         /* Ｄ用Ｖレート５７ */
     dyouvrate58 ,         /* Ｄ用Ｖレート５８ */
     dyouvrate59 ,         /* Ｄ用Ｖレート５９ */
     dyouvrate60 ,         /* Ｄ用Ｖレート６０ */
     dyouvrate61 ,         /* Ｄ用Ｖレート６１ */
     dyouvrate62 ,         /* Ｄ用Ｖレート６２ */
     dyouvrate63 ,         /* Ｄ用Ｖレート６３ */
     dyouvrate64 ,         /* Ｄ用Ｖレート６４ */
     dyouvrate65 ,         /* Ｄ用Ｖレート６５ */
     dyouvrate66 ,         /* Ｄ用Ｖレート６６ */
     dyouvrate67 ,         /* Ｄ用Ｖレート６７ */
     dyouvrate68 ,         /* Ｄ用Ｖレート６８ */
     dyouvrate69 ,         /* Ｄ用Ｖレート６９ */
     dyouvrate70 ,         /* Ｄ用Ｖレート７０ */
     dyouvrate71 ,         /* Ｄ用Ｖレート７１ */
     dyouvrate72 ,         /* Ｄ用Ｖレート７２ */
     dyouvrate73 ,         /* Ｄ用Ｖレート７３ */
     dyouvrate74 ,         /* Ｄ用Ｖレート７４ */
     dyouvrate75 ,         /* Ｄ用Ｖレート７５ */
     dyouvrate76 ,         /* Ｄ用Ｖレート７６ */
     dyouvrate77 ,         /* Ｄ用Ｖレート７７ */
     dyouvrate78 ,         /* Ｄ用Ｖレート７８ */
     dyouvrate79 ,         /* Ｄ用Ｖレート７９ */
     dyouvrate80 ,         /* Ｄ用Ｖレート８０ */
     dyouvrate81 ,         /* Ｄ用Ｖレート８１ */
     dyouvrate82 ,         /* Ｄ用Ｖレート８２ */
     dyouvrate83 ,         /* Ｄ用Ｖレート８３ */
     dyouvrate84 ,         /* Ｄ用Ｖレート８４ */
     dyouvrate85 ,         /* Ｄ用Ｖレート８５ */
     dyouvrate86 ,         /* Ｄ用Ｖレート８６ */
     dyouvrate87 ,         /* Ｄ用Ｖレート８７ */
     dyouvrate88 ,         /* Ｄ用Ｖレート８８ */
     dyouvrate89 ,         /* Ｄ用Ｖレート８９ */
     dyouvrate90 ,         /* Ｄ用Ｖレート９０ */
     dyouvrate91 ,         /* Ｄ用Ｖレート９１ */
     dyouvrate92 ,         /* Ｄ用Ｖレート９２ */
     dyouvrate93 ,         /* Ｄ用Ｖレート９３ */
     dyouvrate94 ,         /* Ｄ用Ｖレート９４ */
     dyouvrate95 ,         /* Ｄ用Ｖレート９５ */
     dyouvrate96 ,         /* Ｄ用Ｖレート９６ */
     dyouvrate97 ,         /* Ｄ用Ｖレート９７ */
     dyouvrate98 ,         /* Ｄ用Ｖレート９８ */
     dyouvrate99 ,         /* Ｄ用Ｖレート９９ */
     kikensrate00 ,         /* 危険Ｓレート００ */
     kikensrate01 ,         /* 危険Ｓレート０１ */
     kikensrate02 ,         /* 危険Ｓレート０２ */
     kikensrate03 ,         /* 危険Ｓレート０３ */
     kikensrate04 ,         /* 危険Ｓレート０４ */
     kikensrate05 ,         /* 危険Ｓレート０５ */
     kikensrate06 ,         /* 危険Ｓレート０６ */
     kikensrate07 ,         /* 危険Ｓレート０７ */
     kikensrate08 ,         /* 危険Ｓレート０８ */
     kikensrate09 ,         /* 危険Ｓレート０９ */
     kikensrate10 ,         /* 危険Ｓレート１０ */
     kikensrate11 ,         /* 危険Ｓレート１１ */
     kikensrate12 ,         /* 危険Ｓレート１２ */
     kikensrate13 ,         /* 危険Ｓレート１３ */
     kikensrate14 ,         /* 危険Ｓレート１４ */
     kikensrate15 ,         /* 危険Ｓレート１５ */
     kikensrate16 ,         /* 危険Ｓレート１６ */
     kikensrate17 ,         /* 危険Ｓレート１７ */
     kikensrate18 ,         /* 危険Ｓレート１８ */
     kikensrate19 ,         /* 危険Ｓレート１９ */
     kikensrate20 ,         /* 危険Ｓレート２０ */
     kikensrate21 ,         /* 危険Ｓレート２１ */
     kikensrate22 ,         /* 危険Ｓレート２２ */
     kikensrate23 ,         /* 危険Ｓレート２３ */
     kikensrate24 ,         /* 危険Ｓレート２４ */
     kikensrate25 ,         /* 危険Ｓレート２５ */
     kikensrate26 ,         /* 危険Ｓレート２６ */
     kikensrate27 ,         /* 危険Ｓレート２７ */
     kikensrate28 ,         /* 危険Ｓレート２８ */
     kikensrate29 ,         /* 危険Ｓレート２９ */
     kikensrate30 ,         /* 危険Ｓレート３０ */
     kikensrate31 ,         /* 危険Ｓレート３１ */
     kikensrate32 ,         /* 危険Ｓレート３２ */
     kikensrate33 ,         /* 危険Ｓレート３３ */
     kikensrate34 ,         /* 危険Ｓレート３４ */
     kikensrate35 ,         /* 危険Ｓレート３５ */
     kikensrate36 ,         /* 危険Ｓレート３６ */
     kikensrate37 ,         /* 危険Ｓレート３７ */
     kikensrate38 ,         /* 危険Ｓレート３８ */
     kikensrate39 ,         /* 危険Ｓレート３９ */
     kikensrate40 ,         /* 危険Ｓレート４０ */
     kikensrate41 ,         /* 危険Ｓレート４１ */
     kikensrate42 ,         /* 危険Ｓレート４２ */
     kikensrate43 ,         /* 危険Ｓレート４３ */
     kikensrate44 ,         /* 危険Ｓレート４４ */
     kikensrate45 ,         /* 危険Ｓレート４５ */
     kikensrate46 ,         /* 危険Ｓレート４６ */
     kikensrate47 ,         /* 危険Ｓレート４７ */
     kikensrate48 ,         /* 危険Ｓレート４８ */
     kikensrate49 ,         /* 危険Ｓレート４９ */
     kikensrate50 ,         /* 危険Ｓレート５０ */
     kikensrate51 ,         /* 危険Ｓレート５１ */
     kikensrate52 ,         /* 危険Ｓレート５２ */
     kikensrate53 ,         /* 危険Ｓレート５３ */
     kikensrate54 ,         /* 危険Ｓレート５４ */
     kikensrate55 ,         /* 危険Ｓレート５５ */
     kikensrate56 ,         /* 危険Ｓレート５６ */
     kikensrate57 ,         /* 危険Ｓレート５７ */
     kikensrate58 ,         /* 危険Ｓレート５８ */
     kikensrate59 ,         /* 危険Ｓレート５９ */
     kikensrate60 ,         /* 危険Ｓレート６０ */
     kikensrate61 ,         /* 危険Ｓレート６１ */
     kikensrate62 ,         /* 危険Ｓレート６２ */
     kikensrate63 ,         /* 危険Ｓレート６３ */
     kikensrate64 ,         /* 危険Ｓレート６４ */
     kikensrate65 ,         /* 危険Ｓレート６５ */
     kikensrate66 ,         /* 危険Ｓレート６６ */
     kikensrate67 ,         /* 危険Ｓレート６７ */
     kikensrate68 ,         /* 危険Ｓレート６８ */
     kikensrate69 ,         /* 危険Ｓレート６９ */
     kikensrate70 ,         /* 危険Ｓレート７０ */
     kikensrate71 ,         /* 危険Ｓレート７１ */
     kikensrate72 ,         /* 危険Ｓレート７２ */
     kikensrate73 ,         /* 危険Ｓレート７３ */
     kikensrate74 ,         /* 危険Ｓレート７４ */
     kikensrate75 ,         /* 危険Ｓレート７５ */
     kikensrate76 ,         /* 危険Ｓレート７６ */
     kikensrate77 ,         /* 危険Ｓレート７７ */
     kikensrate78 ,         /* 危険Ｓレート７８ */
     kikensrate79 ,         /* 危険Ｓレート７９ */
     kikensrate80 ,         /* 危険Ｓレート８０ */
     kikensrate81 ,         /* 危険Ｓレート８１ */
     kikensrate82 ,         /* 危険Ｓレート８２ */
     kikensrate83 ,         /* 危険Ｓレート８３ */
     kikensrate84 ,         /* 危険Ｓレート８４ */
     kikensrate85 ,         /* 危険Ｓレート８５ */
     kikensrate86 ,         /* 危険Ｓレート８６ */
     kikensrate87 ,         /* 危険Ｓレート８７ */
     kikensrate88 ,         /* 危険Ｓレート８８ */
     kikensrate89 ,         /* 危険Ｓレート８９ */
     kikensrate90 ,         /* 危険Ｓレート９０ */
     kikensrate91 ,         /* 危険Ｓレート９１ */
     kikensrate92 ,         /* 危険Ｓレート９２ */
     kikensrate93 ,         /* 危険Ｓレート９３ */
     kikensrate94 ,         /* 危険Ｓレート９４ */
     kikensrate95 ,         /* 危険Ｓレート９５ */
     kikensrate96 ,         /* 危険Ｓレート９６ */
     kikensrate97 ,         /* 危険Ｓレート９７ */
     kikensrate98 ,         /* 危険Ｓレート９８ */
     kikensrate99 ,         /* 危険Ｓレート９９ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BM_RateD_Z;