CREATE VIEW BT_KrDenpyoSelectJk AS SELECT
     syoriYmd ,         /* 処理年月日 */
     syoriymdrenno ,         /* 処理日連番 */
     taisyoukknfrom ,         /* 対象期間（自） */
     taisyoukknto ,         /* 対象期間（至） */
     kanjyoukmkcd1 ,         /* 勘定科目コード１ */
     kanjyoukmkcd2 ,         /* 勘定科目コード２ */
     kanjyoukmkcd3 ,         /* 勘定科目コード３ */
     kanjyoukmkcd4 ,         /* 勘定科目コード４ */
     kanjyoukmkcd5 ,         /* 勘定科目コード５ */
     kanjyoukmkcd6 ,         /* 勘定科目コード６ */
     kanjyoukmkcd7 ,         /* 勘定科目コード７ */
     kanjyoukmkcd8 ,         /* 勘定科目コード８ */
     kanjyoukmkcd9 ,         /* 勘定科目コード９ */
     kanjyoukmkcd10 ,         /* 勘定科目コード１０ */
     kanjyoukmkcd11 ,         /* 勘定科目コード１１ */
     kanjyoukmkcd12 ,         /* 勘定科目コード１２ */
     kanjyoukmkcd13 ,         /* 勘定科目コード１３ */
     kanjyoukmkcd14 ,         /* 勘定科目コード１４ */
     kanjyoukmkcd15 ,         /* 勘定科目コード１５ */
     kanjyoukmkcd16 ,         /* 勘定科目コード１６ */
     kanjyoukmkcd17 ,         /* 勘定科目コード１７ */
     kanjyoukmkcd18 ,         /* 勘定科目コード１８ */
     kanjyoukmkcd19 ,         /* 勘定科目コード１９ */
     kanjyoukmkcd20 ,         /* 勘定科目コード２０ */
     kanjyoukmkcd21 ,         /* 勘定科目コード２１ */
     kanjyoukmkcd22 ,         /* 勘定科目コード２２ */
     kanjyoukmkcd23 ,         /* 勘定科目コード２３ */
     kanjyoukmkcd24 ,         /* 勘定科目コード２４ */
     kanjyoukmkcd25 ,         /* 勘定科目コード２５ */
     kanjyoukmkcd26 ,         /* 勘定科目コード２６ */
     kanjyoukmkcd27 ,         /* 勘定科目コード２７ */
     kanjyoukmkcd28 ,         /* 勘定科目コード２８ */
     kanjyoukmkcd29 ,         /* 勘定科目コード２９ */
     kanjyoukmkcd30 ,         /* 勘定科目コード３０ */
     kanjyoukmkcd31 ,         /* 勘定科目コード３１ */
     kanjyoukmkcd32 ,         /* 勘定科目コード３２ */
     kanjyoukmkcd33 ,         /* 勘定科目コード３３ */
     kanjyoukmkcd34 ,         /* 勘定科目コード３４ */
     kanjyoukmkcd35 ,         /* 勘定科目コード３５ */
     kanjyoukmkcd36 ,         /* 勘定科目コード３６ */
     kanjyoukmkcd37 ,         /* 勘定科目コード３７ */
     kanjyoukmkcd38 ,         /* 勘定科目コード３８ */
     kanjyoukmkcd39 ,         /* 勘定科目コード３９ */
     kanjyoukmkcd40 ,         /* 勘定科目コード４０ */
     kanjyoukmkcd41 ,         /* 勘定科目コード４１ */
     kanjyoukmkcd42 ,         /* 勘定科目コード４２ */
     kanjyoukmkcd43 ,         /* 勘定科目コード４３ */
     kanjyoukmkcd44 ,         /* 勘定科目コード４４ */
     kanjyoukmkcd45 ,         /* 勘定科目コード４５ */
     kanjyoukmkcd46 ,         /* 勘定科目コード４６ */
     kanjyoukmkcd47 ,         /* 勘定科目コード４７ */
     kanjyoukmkcd48 ,         /* 勘定科目コード４８ */
     kanjyoukmkcd49 ,         /* 勘定科目コード４９ */
     kanjyoukmkcd50 ,         /* 勘定科目コード５０ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BT_KrDenpyoSelectJk_Z;