CREATE VIEW IT_KessanYokukiP AS SELECT
     kbnkey ,         /* 区分キー */
     keijyouym ,         /* 計上年月 */
     syono ,         /* 証券番号 */
     hknsyukigou ,         /* 保険種類記号 */
     hknsyukigousdkbn1keta ,         /* 保険種類記号世代区分（１桁） */
     hokensyuruikigouyobi1x1 ,         /* 保険種類記号予備１＿１ */
     hokensyuruikigouyobi1x2 ,         /* 保険種類記号予備１＿２ */
     hokensyuruikigouyobi1x3 ,         /* 保険種類記号予備１＿３ */
     hokensyuruikigouyobi1x4 ,         /* 保険種類記号予備１＿４ */
     hokensyuruikigouyobi1x5 ,         /* 保険種類記号予備１＿５ */
     hokensyuruikigouyobi1x6 ,         /* 保険種類記号予備１＿６ */
     hokensyuruikigouyobi1x7 ,         /* 保険種類記号予備１＿７ */
     hokensyuruikigouyobi1x8 ,         /* 保険種類記号予備１＿８ */
     hokensyuruikigouyobi1x9 ,         /* 保険種類記号予備１＿９ */
     hokensyuruikigouyobi1x10 ,         /* 保険種類記号予備１＿１０ */
     hokensyuruikigouyobi1x11 ,         /* 保険種類記号予備１＿１１ */
     hokensyuruikigouyobi1x12 ,         /* 保険種類記号予備１＿１２ */
     hokensyuruikigouyobi1x13 ,         /* 保険種類記号予備１＿１３ */
     hokensyuruikigouyobi1x14 ,         /* 保険種類記号予備１＿１４ */
     hokensyuruikigouyobi1x15 ,         /* 保険種類記号予備１＿１５ */
     hokensyuruikigouyobi2x1 ,         /* 保険種類記号予備２＿１ */
     hokensyuruikigouyobi2x2 ,         /* 保険種類記号予備２＿２ */
     hokensyuruikigouyobi2x3 ,         /* 保険種類記号予備２＿３ */
     hokensyuruikigouyobi2x4 ,         /* 保険種類記号予備２＿４ */
     hokensyuruikigouyobi2x5 ,         /* 保険種類記号予備２＿５ */
     hokensyuruikigouyobi2x6 ,         /* 保険種類記号予備２＿６ */
     hokensyuruikigouyobi2x7 ,         /* 保険種類記号予備２＿７ */
     hokensyuruikigouyobi2x8 ,         /* 保険種類記号予備２＿８ */
     hokensyuruikigouyobi2x9 ,         /* 保険種類記号予備２＿９ */
     hokensyuruikigouyobi2x10 ,         /* 保険種類記号予備２＿１０ */
     hokensyuruikigouyobi3x1 ,         /* 保険種類記号予備３＿１ */
     hokensyuruikigouyobi3x2 ,         /* 保険種類記号予備３＿２ */
     hokensyuruikigouyobi3x3 ,         /* 保険種類記号予備３＿３ */
     hokensyuruikigouyobi3x4 ,         /* 保険種類記号予備３＿４ */
     hokensyuruikigouyobi3x5 ,         /* 保険種類記号予備３＿５ */
     hokensyuruikigouyobi3x6 ,         /* 保険種類記号予備３＿６ */
     hokensyuruikigouyobi3x7 ,         /* 保険種類記号予備３＿７ */
     hokensyuruikigouyobi3x8 ,         /* 保険種類記号予備３＿８ */
     hokensyuruikigouyobi3x9 ,         /* 保険種類記号予備３＿９ */
     hokensyuruikigouyobi3x10 ,         /* 保険種類記号予備３＿１０ */
     kykymd ,         /* 契約日 */
     annaihuyouriyuukbn ,         /* 案内不要理由区分 */
     syoumetucd ,         /* 消滅コード */
     jkipjytym ,         /* 次回Ｐ充当年月 */
     haraikomip ,         /* 払込Ｐ */
     haraikomip$ ,         /* 払込Ｐ(通貨型) */
     syukykp ,         /* 主契約Ｐ */
     syukykp$ ,         /* 主契約Ｐ(通貨型) */
     zennyknmonth ,         /* 前回入金月数 */
     zenyuukinymd ,         /* 前回入金年月日 */
     jidoukousinhyouji ,         /* 自動更新表示 */
     tenkanhyouji ,         /* 転換表示 */
     hosyouikkatumnoshyouji ,         /* 保障一括見直表示 */
     yobi01xv40 ,         /* 予備０１＿Ｖ４０ */
     tkkzkp ,         /* 特約継続Ｐ */
     tkkzkp$ ,         /* 特約継続Ｐ(通貨型) */
     keizokuphurikaekngk ,         /* 継続Ｐ振替金額 */
     keizokuphurikaekngk$ ,         /* 継続Ｐ振替金額(通貨型) */
     keizokuphurikaekaisiym ,         /* 継続Ｐ振替開始年月 */
     haraikomipannaisaikaiym ,         /* 払込Ｐ案内再開年月 */
     tkkzkkouryokukaisiymd ,         /* 特約継続効力開始年月日 */
     hrimngtkykpjyuutouhoukbn ,         /* 払満後特約Ｐ充当方法区分 */
     jkitkpjytym ,         /* 次回特約Ｐ充当年月 */
     itijibrzugktkp ,         /* 一時払増額特約Ｐ */
     pazukarikingk ,         /* Ｐ預り金額 */
     zennoukbn ,         /* 前納区分 */
     zennoukaisiymd ,         /* 前納開始年月日 */
     zennounyuukinymd ,         /* 前納入金年月日 */
     yokukipbunruicd ,         /* 翌期Ｐ分類コード */
     misyoricd1 ,         /* 未処理コード１ */
     misyoricd2 ,         /* 未処理コード２ */
     misyoricd3 ,         /* 未処理コード３ */
     misyoricd4 ,         /* 未処理コード４ */
     misyoricd5 ,         /* 未処理コード５ */
     misyoricd6 ,         /* 未処理コード６ */
     misyoricd7 ,         /* 未処理コード７ */
     misyoricd8 ,         /* 未処理コード８ */
     misyoricd9 ,         /* 未処理コード９ */
     misyoricd10 ,         /* 未処理コード１０ */
     yobi02xv39 ,         /* 予備０２＿Ｖ３９ */
     kbnkeiriyousegmentkbn ,         /* 区分経理用セグメント区分 */
     kbnkeiriyourgnbnskkbn ,         /* 区分経理用利源分析区分 */
     suurisyuruicd ,         /* 数理種類コード */
     hrkkaisuu ,         /* 払込回数 */
     kyknendo ,         /* 契約年度 */
     keiyakum ,         /* 契約月 */
     haraikatakbn ,         /* 払方区分 */
     iktyknndp ,         /* 一括払翌年度保険料 */
     iktyknndp$ ,         /* 一括払翌年度保険料(通貨型) */
     kigetumaenyknyknndp ,         /* 期月前入金翌年度保険料 */
     kigetumaenyknyknndp$ ,         /* 期月前入金翌年度保険料(通貨型) */
     yknndpkei ,         /* 翌年度保険料合計 */
     yknndpkei$ ,         /* 翌年度保険料合計(通貨型) */
     yobi03xn13 ,         /* 予備０３＿Ｎ１３ */
     yobi03xn13$ ,         /* 予備０３＿Ｎ１３(通貨型) */
     yobi04xv23 ,         /* 予備０４＿Ｖ２３ */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_KessanYokukiP_Z;