CREATE VIEW ZT_SbRituToukeiSeibiRenTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztysyorikbn ,         /* （中継用）処理区分 */
     ztysyoriymd ,         /* （中継用）処理年月日 */
     ztykykmfksnctr ,         /* （中継用）契約ＭＦ更新ＣＴＲ */
     ztysyorino ,         /* （中継用）処理ＮＯ */
     ztysyoricd ,         /* （中継用）処理コード */
     ztysyukgu ,         /* （中継用）種類記号 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztykykym ,         /* （中継用）契約年月 */
     ztytokujyouhyouji ,         /* （中継用）特条表示 */
     ztyviphyouji ,         /* （中継用）ＶＩＰ表示 */
     ztykisnkihons ,         /* （中継用）計算基本Ｓ */
     ztykeisansibous ,         /* （中継用）計算死亡Ｓ */
     ztyshrs ,         /* （中継用）支払Ｓ */
     ztyshrymd ,         /* （中継用）支払年月日 */
     ztysiharaisisyacd ,         /* （中継用）支払支社コード */
     ztysymtgenincd ,         /* （中継用）消滅原因コード */
     ztykeikaym ,         /* （中継用）経過年月 */
     ztysbugenincd ,         /* （中継用）死亡原因コード */
     ztybsyym ,         /* （中継用）募集年月 */
     ztydai2hhknnen ,         /* （中継用）第２被保険者年令 */
     ztydai2tokujyouhyouji ,         /* （中継用）第２特条表示 */
     ztytignmrtisyukgu ,         /* （中継用）逓減マル定種類記号 */
     ztyteigenmaruteikikan ,         /* （中継用）逓減マル定期間 */
     ztygoukeiteigenbubuns ,         /* （中継用）合計逓減部分Ｓ */
     ztyrenseimrtisyukgu ,         /* （中継用）連生マル定種類記号 */
     ztyyobiv1 ,         /* （中継用）予備項目Ｖ１ */
     ztylivingneedsshrarihyj ,         /* （中継用）リビングニーズ支払有表示 */
     ztylnkeikaym ,         /* （中継用）ＬＮ経過年月 */
     ztylnshrgenincd ,         /* （中継用）ＬＮ支払原因コード */
     ztykituenkbn ,         /* （中継用）喫煙区分 */
     ztykituenhonsuu ,         /* （中継用）喫煙本数 */
     ztydugktnknsntkhuhukbn ,         /* （中継用）同額転換選択方法区分 */
     ztykykjitokujyouarihyj ,         /* （中継用）契約時特条有表示 */
     ztytokuyakukousinkbn ,         /* （中継用）特約更新区分 */
     ztyteigenmaruteikisiym ,         /* （中継用）逓減マル定期始年月 */
     ztysyunyumrtisyukgu ,         /* （中継用）収入マル定種類記号 */
     ztysyuunyuumaruteikikan ,         /* （中継用）収入マル定期間 */
     ztysyuunyuumrtinknengkn7 ,         /* （中継用）収入マル定年金年額Ｎ７ */
     ztysyuunyuumaruteikisiym ,         /* （中継用）収入マル定期始年月 */
     ztysysnymd ,         /* （中継用）初診年月日 */
     ztysindanymd ,         /* （中継用）診断年月日 */
     ztybyoumeicd1 ,         /* （中継用）病名コード１ */
     ztybyoumeicd2 ,         /* （中継用）病名コード２ */
     ztyshrnaiyoukbn ,         /* （中継用）支払内容区分 */
     ztygituyuknkbn1 ,         /* （中継用）該当要件区分１ */
     ztygituyuknkbn2 ,         /* （中継用）該当要件区分２ */
     ztysyeiebnri1 ,         /* （中継用）シェイエ分類１ */
     ztysyeiebnri2 ,         /* （中継用）シェイエ分類２ */
     ztyminnesotacd1 ,         /* （中継用）ミネソタコード１ */
     ztyminnesotacd2 ,         /* （中継用）ミネソタコード２ */
     ztyminnesotacd3 ,         /* （中継用）ミネソタコード３ */
     ztyminnesotacd4 ,         /* （中継用）ミネソタコード４ */
     ztyminnesotacd5 ,         /* （中継用）ミネソタコード５ */
     ztymnsisiensindanjiyuu ,         /* （中継用）慢性膵炎診断事由 */
     ztyknkuhnsindanjiyuu ,         /* （中継用）肝硬変診断事由 */
     ztyhushrkbn ,         /* （中継用）不支払区分 */
     ztyhushrym ,         /* （中継用）不支払年月 */
     ztysyuunyuumrtinkshrkkn ,         /* （中継用）収入マル定年金支払期間 */
     ztytokujyousakugenkikan ,         /* （中継用）特条削減期間 */
     ztygengakutenkankykhyj ,         /* （中継用）減額転換契約表示 */
     ztyharaikomihouhou ,         /* （中継用）払込方法 */
     ztysinsahouhou ,         /* （中継用）診査方法 */
     ztykykniyutksytioukbn ,         /* （中継用）契約内容特殊対応区分 */
     ztyrnduyuryumshyutn ,         /* （中継用）連動用料増標点 */
     ztyhutanpobui1 ,         /* （中継用）不担保部位１ */
     ztyhtnpkkn1 ,         /* （中継用）不担保期間１ */
     ztyhutanpobui2 ,         /* （中継用）不担保部位２ */
     ztyhtnpkkn2 ,         /* （中継用）不担保期間２ */
     ztyhukasyuksyu ,         /* （中継用）付加主契約種類 */
     ztysuuriyoutokuyakukbn ,         /* （中継用）数理用特約区分 */
     ztytokuyakuno ,         /* （中継用）特約番号 */
     ztyhaitoukbn ,         /* （中継用）配当区分 */
     ztykusnmetkyksykipjyutuym ,         /* （中継用）更新前特約初回Ｐ充当年月 */
     ztysykikjgykbn ,         /* （中継用）職域事業区分 */
     ztysykgycd ,         /* （中継用）職業コード */
     ztyaatukaisosikicd ,         /* （中継用）Ａ扱者組織コード */
     ztyaatukaikojincd ,         /* （中継用）Ａ扱者個人コード */
     ztytenkanminaosikbn ,         /* （中継用）転換見直区分 */
     ztykaijyokbn ,         /* （中継用）解除区分 */
     ztysyuruihenkouarihyouji ,         /* （中継用）種類変更有表示 */
     ztydai2hihokensyasonzokuhyj ,         /* （中継用）第２被保険者存続表示 */
     ztysyukeiyakukigou ,         /* （中継用）主契約記号 */
     ztysymtymd ,         /* （中継用）消滅年月日 */
     ztytyuutohukatkhyj ,         /* （中継用）中途付加特約表示 */
     ztyyoukigjyutigituymd ,         /* （中継用）要介護状態該当年月日 */
     ztyyoukigjyutigeninkbn ,         /* （中継用）要介護状態原因区分 */
     ztysykmtssyukahikbn ,         /* （中継用）食物摂取可否区分 */
     ztyfktrsmtkahikbn ,         /* （中継用）拭き取り始末可否区分 */
     ztyhokoukahikbn ,         /* （中継用）歩行可否区分 */
     ztynyykkahikbn ,         /* （中継用）入浴可否区分 */
     ztyihukutyakudatukahikbn ,         /* （中継用）衣服着脱可否区分 */
     ztytihougeninkbn ,         /* （中継用）痴呆原因区分 */
     ztysyukgusdkbn ,         /* （中継用）種類記号世代区分 */
     ztytignmrtisyukgusdkbn ,         /* （中継用）逓減マル定種類記号世代区分 */
     ztyrenseimrtisyukgusdkbn ,         /* （中継用）連生マル定種類記号世代区分 */
     ztysyunyumrtisyukgusdkbn ,         /* （中継用）収入マル定種類記号世代区分 */
     ztysykyksyuruikgusdkbn ,         /* （中継用）主契約種類記号世代区分 */
     ztypmenhukakbn ,         /* （中継用）Ｐ免付加区分 */
     ztypmenkbnv2 ,         /* （中継用）Ｐ免区分Ｖ２ */
     ztypmenjikohasseiymd ,         /* （中継用）Ｐ免事故発生年月日 */
     ztybosyuukeirokbn ,         /* （中継用）募集経路区分 */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztysyorinov2 ,         /* （中継用）処理番号Ｖ２ */
     ztykigkyhsitihsyutkykhyj ,         /* （中継用）介護給付最低保証特約表示 */
     ztypmenhutanpobui1 ,         /* （中継用）Ｐ免不担保部位１ */
     ztypmenhutanpokikan1 ,         /* （中継用）Ｐ免不担保期間１ */
     ztypmenhutanpobui2 ,         /* （中継用）Ｐ免不担保部位２ */
     ztypmenhutanpokikan2 ,         /* （中継用）Ｐ免不担保期間２ */
     ztykanyujidatakanrino ,         /* （中継用）加入時データ管理番号 */
     ztybnktgsnzkkykdatakanrino ,         /* （中継用）分割後存続契約データ管理番号 */
     ztybnkttnknkbn ,         /* （中継用）分割転換区分 */
     ztykykjiqpackhyj ,         /* （中継用）契約時Ｑパック表示 */
     ztybnktjisisttkarihyj ,         /* （中継用）分割時災疾特約有表示 */
     ztysotodasipmenkbn ,         /* （中継用）外出Ｐ免区分 */
     ztystdssnskbn ,         /* （中継用）外出診査区分 */
     ztycareneedssiharaihyouji ,         /* （中継用）ケアニーズ支払表示 */
     ztybnktjitiktkarihyj ,         /* （中継用）分割時定期特約有表示 */
     ztykousinkbn ,         /* （中継用）更新区分 */
     ztyksnym ,         /* （中継用）更新年月 */
     ztyijitoukeiyuksnhyj ,         /* （中継用）医事統計用更新表示 */
     ztyikoujisnskbn ,         /* （中継用）移行時診査区分 */
     ztystdssytikbn ,         /* （中継用）外出集定区分 */
     ztysuuriyouyobin1 ,         /* （中継用）数理用予備項目Ｎ１ */
     ztyimustiyusbus ,         /* （中継用）医務査定用死亡Ｓ */
     ztykeisansykykbbnkhns ,         /* （中継用）計算主契約部分基本Ｓ */
     ztysuuriyoubosyuukeitaikbn ,         /* （中継用）数理用募集形態区分 */
     ztysysnikoujiym ,         /* （中継用）終身移行時年月 */
     ztygnspshrhyj ,         /* （中継用）がんサポ支払表示 */
     ztygnspshrkeikaym ,         /* （中継用）がんサポ支払経過年月 */
     ztygnspshrgenincd ,         /* （中継用）がんサポ支払原因コード */
     ztysotodasimanagehyouji ,         /* （中継用）外出満年令表示 */
     ztyhhknnentysihyj ,         /* （中継用）被保険者年令調整表示 */
     ztydai2hhknnentysihyj ,         /* （中継用）第２被保険者年令調整表示 */
     ztyngerkahikbn ,         /* （中継用）寝返り可否区分 */
     ztyhokenhoutekiyouhyouji ,         /* （中継用）保険法適用表示 */
     ztytokuteijyoutaihushrhyj ,         /* （中継用）特定状態不支払表示 */
     ztysotodasiphkbnmnoshyouji ,         /* （中継用）外出Ｐ不可分見直表示 */
     ztykeisansyukeiyakup ,         /* （中継用）計算主契約Ｐ */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztytokubetuhosyoukikan ,         /* （中継用）特別保障期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztykeisangoukeitenkans ,         /* （中継用）計算合計転換Ｓ */
     ztykeisangoukeitenkankakaku ,         /* （中継用）計算合計転換価格 */
     ztykisnwnsgukitnknkakaku ,         /* （中継用）計算Ｗなし合計転換価格 */
     ztytnknkhnbbnjyuturt ,         /* （中継用）転換基本部分充当率 */
     ztyharaizumiymd ,         /* （中継用）払済年月日 */
     ztystdsstkjytkyuhyj ,         /* （中継用）外出新特条適用表示 */
     ztykeisanyoteiriritu ,         /* （中継用）計算予定利率 */
     ztyseiketuseiyoukahikbn ,         /* （中継用）清潔整容可否区分 */
     ztysyuurouhunoukgjyoutaikbn ,         /* （中継用）就労不能介護状態区分 */
     ztysyuurouhunoujyoutaikbn ,         /* （中継用）就労不能状態区分 */
     ztysiznkyhsyoubyouhasseiymd ,         /* （中継用）生前給付傷病発生年月日 */
     ztykyusisnknkuskgitukbn ,         /* （中継用）急性心筋梗塞該当区分 */
     ztynousottyuugaitoukbn ,         /* （中継用）脳卒中該当区分 */
     ztyjinhuzengaitoukbn ,         /* （中継用）腎不全該当区分 */
     ztydoumyakusikkangaitoukbn ,         /* （中継用）動脈疾患該当区分 */
     ztydatakanrino2 ,         /* （中継用）データ管理番号２ */
     ztydatakanrino3 ,         /* （中継用）データ管理番号３ */
     ztysinkeiyakujivithkhyouji ,         /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztyknkuzusnzyrttekitkarihyj ,         /* （中継用）健康増進乗率適用特約有表示 */
     ztyknkuzusnzyrtsiyounendo ,         /* （中継用）健康増進乗率使用年度 */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyvittkykkaiyakuymd ,         /* （中継用）Ｖｉｔ特約解約年月日 */
     ztypwrbksidhitekiyouhyj ,         /* （中継用）保険料割引制度非適用表示 */
     ztynintisyougeninkbn ,         /* （中継用）認知症原因区分 */
     ztysuuriyouyobin1x2 ,         /* （中継用）数理用予備項目Ｎ１＿２ */
     ztysuuriyouyobin8x3 ,         /* （中継用）数理用予備項目Ｎ８＿３ */
     ztysuuriyouyobin8x4 ,         /* （中継用）数理用予備項目Ｎ８＿４ */
     ztysuuriyouyobin8x5 ,         /* （中継用）数理用予備項目Ｎ８＿５ */
     ztysuuriyouyobin8x6 ,         /* （中継用）数理用予備項目Ｎ８＿６ */
     ztysuuriyouyobin8x7 ,         /* （中継用）数理用予備項目Ｎ８＿７ */
     ztysuuriyouyobin8x8 ,         /* （中継用）数理用予備項目Ｎ８＿８ */
     ztysuuriyouyobin8x9 ,         /* （中継用）数理用予備項目Ｎ８＿９ */
     ztysuuriyouyobin8x10 ,         /* （中継用）数理用予備項目Ｎ８＿１０ */
     ztyyobin7 ,         /* （中継用）予備項目Ｎ７ */
     ztyyobin7x2 ,         /* （中継用）予備項目Ｎ７＿２ */
     ztyyobin7x3 ,         /* （中継用）予備項目Ｎ７＿３ */
     ztyyobin7x4 ,         /* （中継用）予備項目Ｎ７＿４ */
     ztyyobin7x5 ,         /* （中継用）予備項目Ｎ７＿５ */
     ztyzyrthntiyustatuskbn ,         /* （中継用）乗率判定用ステータス区分 */
     ztyyobiv59 ,         /* （中継用）予備項目Ｖ５９ */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztygaikadatekihons ,         /* （中継用）外貨建基本Ｓ */
     ztygaikadatesibous ,         /* （中継用）外貨建死亡Ｓ */
     ztykeiyakujiyoteiriritu ,         /* （中継用）契約時予定利率 */
     ztykawaserate ,         /* （中継用）為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztyenkdtsbujsitihsyukngk ,         /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10 ,         /* （中継用）数理用予備項目Ｎ１０ */
     ztysuuriyouyobin10x2 ,         /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobiv10x3 ,         /* （中継用）予備項目Ｖ１０＿３ */
     ztyyobin11 ,         /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2 ,         /* （中継用）予備項目Ｎ１１＿２ */
     ztyyobin11x3 ,         /* （中継用）予備項目Ｎ１１＿３ */
     ztyyobin11x4 ,         /* （中継用）予備項目Ｎ１１＿４ */
     ztyyobin11x5 ,         /* （中継用）予備項目Ｎ１１＿５ */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SbRituToukeiSeibiRenTy_Z;