CREATE VIEW ZT_TjtIdouNaiyouRn AS SELECT
     zrnhuho2kyknokbn ,         /* （連携用）普保Ⅱ契約番号区分 */
     zrnhuho2kykno ,         /* （連携用）普保Ⅱ契約番号 */
     zrnrecordsakujyohyouji ,         /* （連携用）レコード削除表示 */
     zrntjtidounaiyouyobi01 ,         /* （連携用）当日異動内容予備０１ */
     zrnkhsyouhncd ,         /* （連携用）（契約保全）商品コード */
     zrnkhkykjyoutai ,         /* （連携用）（契約保全）契約状態 */
     zrnkhkykymd ,         /* （連携用）（契約保全）契約年月日 */
     zrnkhyuukousyoumetukbn ,         /* （連携用）（契約保全）有効消滅区分 */
     zrnkhsyoumetujiyuu ,         /* （連携用）（契約保全）消滅事由 */
     zrnkhsyoumetuymd ,         /* （連携用）（契約保全）消滅年月日 */
     zrnkhtsntuukasyu ,         /* （連携用）（契約保全）通算用通貨種類 */
     zrnkhtsnyousibous ,         /* （連携用）（契約保全）通算用死亡Ｓ */
     zrnkhtsnyouitijip ,         /* （連携用）（契約保全）通算用一時払Ｐ */
     zrnkhtsnyounkgns ,         /* （連携用）（契約保全）通算用年金原資 */
     zrnkhhrkkkn ,         /* （連携用）（契約保全）払込期間 */
     zrnkhsntkhoukbn ,         /* （連携用）（契約保全）選択方法区分 */
     zrnkhbosyuuym ,         /* （連携用）（契約保全）募集年月 */
     zrnkhkykhhkndouhyouji ,         /* （連携用）（契約保全）契約者被保険者同一表示 */
     zrnkhttdktyuuikbn1 ,         /* （連携用）（契約保全）手続注意区分１ */
     zrnkhttdktyuuikbn2 ,         /* （連携用）（契約保全）手続注意区分２ */
     zrnkhttdktyuuikbn3 ,         /* （連携用）（契約保全）手続注意区分３ */
     zrnkhttdktyuuikbn4 ,         /* （連携用）（契約保全）手続注意区分４ */
     zrnkhttdktyuuikbn5 ,         /* （連携用）（契約保全）手続注意区分５ */
     zrnkhsyouhnsdno ,         /* （連携用）（契約保全）商品世代番号 */
     zrnkhkaigomaehrtkykarihyj ,         /* （連携用）（契約保全）介護前払特約有表示 */
     zrnkhpyennykntkykarihyj ,         /* （連携用）（契約保全）保険料円入金特約有表示 */
     zrnkhtsnyennyknkgk ,         /* （連携用）（契約保全）通算用円入金額 */
     zrnkhskmosno ,         /* （連携用）（契約保全）新契約時申込番号 */
     zrnkhhouteityotksyhnhyj ,         /* （連携用）（契約保全）法定貯蓄性商品表示 */
     zrnkhseiritujitrhkjikakkbn ,         /* （連携用）（契約保全）成立時取引時確認区分 */
     zrnkhhrkkeirokbn ,         /* （連携用）（契約保全）払込経路区分 */
     zrntjtidounaiyouyobi02 ,         /* （連携用）当日異動内容予備０２ */
     zrnsksyouhncd ,         /* （連携用）（新契約）商品コード */
     zrnskmosymd ,         /* （連携用）（新契約）申込年月日 */
     zrnskkykymd ,         /* （連携用）（新契約）契約年月日 */
     zrnsksknnkaisiymd ,         /* （連携用）（新契約）責任開始年月日 */
     zrnskseiritukbn ,         /* （連携用）（新契約）成立区分 */
     zrnsksrsyoriymd ,         /* （連携用）（新契約）成立処理年月日 */
     zrnskmfrenflg ,         /* （連携用）（新契約）ＭＦ連動済フラグ */
     zrnsksyono ,         /* （連携用）（新契約）証券番号 */
     zrnsktsntuukasyu ,         /* （連携用）（新契約）通算用通貨種類 */
     zrnsktsnyousibous ,         /* （連携用）（新契約）通算用死亡Ｓ */
     zrnsktsnyouitijip ,         /* （連携用）（新契約）通算用一時払Ｐ */
     zrnsktsnyounkgns ,         /* （連携用）（新契約）通算用年金原資 */
     zrnskhrkkkn ,         /* （連携用）（新契約）払込期間 */
     zrnsksntkhoukbn ,         /* （連携用）（新契約）選択方法区分 */
     zrnskbosyuuym ,         /* （連携用）（新契約）募集年月 */
     zrnskkykhhkndouhyouji ,         /* （連携用）（新契約）契約者被保険者同一表示 */
     zrnskmossyoumetukbn ,         /* （連携用）（新契約）申込消滅区分 */
     zrnsksyouhnsdno ,         /* （連携用）（新契約）商品世代番号 */
     zrnskkaigomaehrtkykarihyj ,         /* （連携用）（新契約）介護前払特約有表示 */
     zrnskpyennykntkykarihyj ,         /* （連携用）（新契約）保険料円入金特約有表示 */
     zrnsktsnyennyknkgk ,         /* （連携用）（新契約）通算用円入金額 */
     zrnskhrkkeirokbn ,         /* （連携用）（新契約）払込経路区分 */
     zrntjtidounaiyouyobi03 ,         /* （連携用）当日異動内容予備０３ */
     zrnnksyouhncd ,         /* （連携用）（年金支払）商品コード */
     zrnnknkshrstartymd ,         /* （連携用）（年金支払）年金支払開始年月日 */
     zrnnkkykymd ,         /* （連携用）（年金支払）契約年月日 */
     zrnnknksyoumetucd ,         /* （連携用）（年金支払）年金消滅コード */
     zrnnksyoumtymd ,         /* （連携用）（年金支払）消滅年月日 */
     zrnnkshrtuukasyu ,         /* （連携用）（年金支払）支払通貨種類 */
     zrnnkteinksyu ,         /* （連携用）（年金支払）定額年金年金種類 */
     zrnnktsnnkgns ,         /* （連携用）（年金支払）通算用年金原資 */
     zrnnknkukthhkndouhyouji ,         /* （連携用）（年金支払）年金受取人被保険者同一表示 */
     zrnnksyouhnsdno ,         /* （連携用）（年金支払）商品世代番号 */
     zrntjtidounaiyouyobi04 ,         /* （連携用）当日異動内容予備０４ */
     zrnhhknmei ,         /* （連携用）被保険者名 */
     zrnknjhhknmei ,         /* （連携用）漢字被保険者名 */
     zrnhhknseiymd ,         /* （連携用）被保険者生年月日 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhhknnewyno ,         /* （連携用）被保険者新郵便番号 */
     zrnhhknadr ,         /* （連携用）被保険者住所 */
     zrnhhkntelno ,         /* （連携用）被保険者電話番号 */
     zrnhhknsykgycd ,         /* （連携用）被保険者職業コード */
     zrntjtidounaiyouyobi05 ,         /* （連携用）当日異動内容予備０５ */
     zrnkyknm ,         /* （連携用）契約者名 */
     zrnkjkyknm ,         /* （連携用）漢字契約者名 */
     zrnkyksyaseiymd ,         /* （連携用）契約者生年月日 */
     zrntjtidounaiyouyobi06 ,         /* （連携用）当日異動内容予備０６ */
     zrnnkuktnm ,         /* （連携用）年金受取人名 */
     zrnkjnkuktnm ,         /* （連携用）漢字年金受取人名 */
     zrnnenkinuktseiymd ,         /* （連携用）年金受取人生年月日 */
     zrntjtidounaiyouyobi07 ,         /* （連携用）当日異動内容予備０７ */
     zrntsnsknewyno ,         /* （連携用）通信先新郵便番号 */
     zrntsinadr ,         /* （連携用）通信先住所 */
     zrntsintelno ,         /* （連携用）通信先電話番号 */
     zrntjtidounaiyouyobi08 ,         /* （連携用）当日異動内容予備０８ */
     zrnsbuktnm1 ,         /* （連携用）死亡受取人名１ */
     zrnkjsbuktnm1 ,         /* （連携用）漢字死亡受取人名１ */
     zrnsbuktnm2 ,         /* （連携用）死亡受取人名２ */
     zrnkjsbuktnm2 ,         /* （連携用）漢字死亡受取人名２ */
     zrnsbuktnm3 ,         /* （連携用）死亡受取人名３ */
     zrnkjsbuktnm3 ,         /* （連携用）漢字死亡受取人名３ */
     zrnsbuktnm4 ,         /* （連携用）死亡受取人名４ */
     zrnkjsbuktnm4 ,         /* （連携用）漢字死亡受取人名４ */
     zrntjtidounaiyouyobi09 ,         /* （連携用）当日異動内容予備０９ */
     zrnstdrsknm ,         /* （連携用）指定代理請求人名 */
     zrnkjstdrsknm ,         /* （連携用）漢字指定代理請求人名 */
     zrnkykdairinm ,         /* （連携用）契約者代理人名 */
     zrnkjkykdairinm ,         /* （連携用）漢字契約者代理人名 */
     zrntjtidounaiyouyobi10 ,         /* （連携用）当日異動内容予備１０ */
     zrnbankcd ,         /* （連携用）銀行番号 */
     zrnshitencd ,         /* （連携用）支店番号 */
     zrnyokinkbn ,         /* （連携用）預金種目区分 */
     zrnkouzano7keta ,         /* （連携用）口座番号（７桁） */
     zrnkzmeiginmei ,         /* （連携用）口座名義人名 */
     zrnkzkykdouhyouji ,         /* （連携用）口座名義契約者同一表示 */
     zrntjtidounaiyouyobi12 ,         /* （連携用）当日異動内容予備１２ */
     zrnkzktourokunm1 ,         /* （連携用）家族登録名１ */
     zrnkjkzktourokunm1 ,         /* （連携用）漢字家族登録名１ */
     zrnkzktourokunm2 ,         /* （連携用）家族登録名２ */
     zrnkjkzktourokunm2 ,         /* （連携用）漢字家族登録名２ */
     zrntjtidounaiyouyobi13 ,         /* （連携用）当日異動内容予備１３ */
     zrndairitencd1 ,         /* （連携用）代理店コード（１） */
     zrnbunwari1 ,         /* （連携用）分担割合１ */
     zrndairitencd2 ,         /* （連携用）代理店コード（２） */
     zrnbunwari2 ,         /* （連携用）分担割合２ */
     zrnaatukaisosikicd ,         /* （連携用）Ａ扱者組織コード */
     zrnbatukaisosikicd ,         /* （連携用）Ｂ扱者組織コード */
     zrntjtidounaiyouyobi11           /* （連携用）当日異動内容予備１１ */
FROM ZT_TjtIdouNaiyouRn_Z;