CREATE VIEW ZT_JigyounndsikiTkHoyuuTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztysuuriyoutokuyakukbn ,         /* （中継用）数理用特約区分 */
     ztytokuyakugatakbn ,         /* （中継用）特約型区分 */
     ztytokuyakukisi ,         /* （中継用）特約期始 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztysisyacd ,         /* （中継用）支社コード */
     ztysibucd ,         /* （中継用）支部コード */
     ztybsyym ,         /* （中継用）募集年月 */
     ztyhhknhnsktodouhukencd ,         /* （中継用）被保険者本籍都道府県コード */
     ztytokuyakus ,         /* （中継用）特約Ｓ */
     ztysinkeityuutokbn ,         /* （中継用）新契中途区分 */
     ztysyukeiyakusrank ,         /* （中継用）主契約Ｓランク */
     ztysyukeiyakuprank ,         /* （中継用）主契約Ｐランク */
     ztysyukeiyakukykjigyouy ,         /* （中継用）主契約契約事業年 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztyryouritukbn ,         /* （中継用）料率区分 */
     ztytksyuannaikykkbn ,         /* （中継用）特殊案内契約区分 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztymaruteiskeijihukahyj ,         /* （中継用）マル定新契約時付加表示 */
     ztytenkankaisuu ,         /* （中継用）転換回数 */
     ztytokuyakutokujyoukbn ,         /* （中継用）特約特条区分 */
     ztydai2maruhihyj ,         /* （中継用）第２マル被表示 */
     ztytokuteijyuusitusetkbn ,         /* （中継用）特定重疾セット区分 */
     ztydugktnknsntkhuhukbn ,         /* （中継用）同額転換選択方法区分 */
     ztygengakutenkankykhyj ,         /* （中継用）減額転換契約表示 */
     ztyhaitoukbn ,         /* （中継用）配当区分 */
     ztykusnmesyokaipjyuutouym ,         /* （中継用）更新前初回Ｐ充当年月 */
     ztysaigaitkyksyokusyucd ,         /* （中継用）災害特約職種コード */
     ztysykgycd ,         /* （中継用）職業コード */
     ztytoukeiyousinsakbn ,         /* （中継用）統計用診査区分 */
     ztygassansrank ,         /* （中継用）合算Ｓランク */
     ztytoliplhyj ,         /* （中継用）ＴＯＬＩＰＬ表示 */
     ztypmenhukakbn ,         /* （中継用）Ｐ免付加区分 */
     ztypmenkbnv2 ,         /* （中継用）Ｐ免区分Ｖ２ */
     ztyketteikijyunkanwakbn ,         /* （中継用）決定基準緩和区分 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztytokuyakusedaikbn ,         /* （中継用）特約世代区分 */
     ztysiharainissuukbn ,         /* （中継用）支払日数区分 */
     ztykakuseikatakbn ,         /* （中継用）カク成型区分 */
     ztybosyuukeirokbn ,         /* （中継用）募集経路区分 */
     ztydantaicd ,         /* （中継用）団体コード */
     ztypmenhutanpohyj ,         /* （中継用）Ｐ免不担保表示 */
     ztytenkanhosyouminaosikbn ,         /* （中継用）転換保障見直区分 */
     ztyhosyouminaosikaisuu ,         /* （中継用）保障見直回数 */
     ztyqpackhyj ,         /* （中継用）Ｑパック表示 */
     ztybunkatukbn ,         /* （中継用）分割区分 */
     ztystdssnskbn ,         /* （中継用）外出診査区分 */
     ztystdssytikbn ,         /* （中継用）外出集定区分 */
     ztyhosyoukikankbn ,         /* （中継用）保障期間区分 */
     ztykeijyouym ,         /* （中継用）計上年月 */
     ztybosyuukeitaikbn ,         /* （中継用）募集形態区分 */
     ztydakuhikettisyacd ,         /* （中継用）諾否決定者コード */
     ztytokuyakukikan ,         /* （中継用）特約期間 */
     ztymannenreihyj ,         /* （中継用）満年令表示 */
     ztyhhknnentysihyj ,         /* （中継用）被保険者年令調整表示 */
     ztykousinkbn ,         /* （中継用）更新区分 */
     ztyhokenhoutekiyouhyouji ,         /* （中継用）保険法適用表示 */
     ztysotodasiphkbnmnoshyouji ,         /* （中継用）外出Ｐ不可分見直表示 */
     ztytokuteijyoutaihushrhyj ,         /* （中継用）特定状態不支払表示 */
     ztyrendouyousntkjyubbnhyj ,         /* （中継用）連動用新特条部分表示 */
     ztymusentakukeiyakukbn ,         /* （中継用）無選択契約区分 */
     ztyknkuzusnzyrttekitkarihyj ,         /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekeizokuhyouji ,         /* （中継用）Ｂｌｕｅ継続表示 */
     ztyzyrthntiyustatuskbn ,         /* （中継用）乗率判定用ステータス区分 */
     ztyzyrthntiyustatuskbnx2 ,         /* （中継用）乗率判定用ステータス区分＿２ */
     ztyzyrthntiyustatuskbnx3 ,         /* （中継用）乗率判定用ステータス区分＿３ */
     ztyzyrthntiyustatuskbnx4 ,         /* （中継用）乗率判定用ステータス区分＿４ */
     ztyzyrthntiyustatuskbnx5 ,         /* （中継用）乗率判定用ステータス区分＿５ */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyknkuzusnzyrtx2 ,         /* （中継用）健康増進乗率＿２ */
     ztypwrbksidhitekiyouhyj ,         /* （中継用）保険料割引制度非適用表示 */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     ztydatakanrino2 ,         /* （中継用）データ管理番号２ */
     ztydatakanrino3 ,         /* （中継用）データ管理番号３ */
     ztysinkeiyakujivithkhyouji ,         /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztysuuriyouyobin4 ,         /* （中継用）数理用予備項目Ｎ４ */
     ztyyobin11x3 ,         /* （中継用）予備項目Ｎ１１＿３ */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztykawaserate ,         /* （中継用）為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztykeiyakujiyoteiriritu ,         /* （中継用）契約時予定利率 */
     ztygaikadatetokuyakus ,         /* （中継用）外貨建特約Ｓ */
     ztygaikadatesyukeiyakus ,         /* （中継用）外貨建主契約Ｓ */
     ztygaikadatesyukeiyakup ,         /* （中継用）外貨建主契約Ｐ */
     ztyenkdtsbujsitihsyukngk ,         /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10x2 ,         /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobiv10x3 ,         /* （中継用）予備項目Ｖ１０＿３ */
     ztymvatyouseigow ,         /* （中継用）ＭＶＡ調整後Ｗ */
     ztymvakeisanjisknnjynbkn ,         /* （中継用）ＭＶＡ計算時責任準備金 */
     ztyyobin11x6 ,         /* （中継用）予備項目Ｎ１１＿６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_JigyounndsikiTkHoyuuTy_Z;