CREATE VIEW ZT_SbRituRendouTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyobiv12x7 ,         /* （中継用）予備項目Ｖ１２＿７ */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztyrendouyoukikan ,         /* （中継用）連動用期間 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyrendouyoukeiyakunengetu ,         /* （中継用）連動用契約年月 */
     ztyrendouyoukihons ,         /* （中継用）連動用基本Ｓ */
     ztyrendouyousibous ,         /* （中継用）連動用死亡Ｓ */
     ztytnknitjbrigisbus ,         /* （中継用）転換一時払以外死亡Ｓ */
     ztytenkanminaosikbn ,         /* （中継用）転換見直区分 */
     ztyrendouyouhrkhouhoukbn ,         /* （中継用）連動用払込方法区分 */
     ztyrendouyoujyuusyokbn ,         /* （中継用）連動用住所区分 */
     ztyaatukaisosikicd ,         /* （中継用）Ａ扱者組織コード */
     ztyrendouyousakugenkikan ,         /* （中継用）連動用削減期間 */
     ztyrnduyuryumshyutn ,         /* （中継用）連動用料増標点 */
     ztyrendouyoubosyuuym ,         /* （中継用）連動用募集年月 */
     ztysuuriyouyobin1 ,         /* （中継用）数理用予備項目Ｎ１ */
     ztysykgycd ,         /* （中継用）職業コード */
     ztydakuhikettisyacd ,         /* （中継用）諾否決定者コード */
     ztydai2hihokensyahyouji ,         /* （中継用）第２被保険者表示 */
     ztyrenseimusntkknyuhyj ,         /* （中継用）連生無選択加入表示 */
     ztytokubetumaruteiarihyj ,         /* （中継用）特別マル定有表示 */
     ztydougakutenkanhyouji ,         /* （中継用）同額転換表示 */
     ztytenkansentakuhouhoukbn ,         /* （中継用）転換選択方法区分 */
     ztytokubetusentakuarikbn ,         /* （中継用）特別選択有区分 */
     ztyketteikekkakbn ,         /* （中継用）決定結果区分 */
     ztykeiyakukakuninsyuruikbn ,         /* （中継用）契約確認種類区分 */
     ztykeiyakukakuninriyuukbn ,         /* （中継用）契約確認理由区分 */
     ztyrendouyoukekkancdx1 ,         /* （中継用）連動用欠陥コード＿１ */
     ztykeikanensuux1 ,         /* （中継用）経過年数＿１ */
     ztysyujyutuarihyoujix1 ,         /* （中継用）手術有表示＿１ */
     ztyrendouyoukekkancdx2 ,         /* （中継用）連動用欠陥コード＿２ */
     ztykeikanensuux2 ,         /* （中継用）経過年数＿２ */
     ztysyujyutuarihyoujix2 ,         /* （中継用）手術有表示＿２ */
     ztysaihokenhyouji ,         /* （中継用）再保険表示 */
     ztyrnduyusysnhujyusnssyacd ,         /* （中継用）連動用初診報状診査者コード */
     ztyrndyusysnhujyusnshuhukbn ,         /* （中継用）連動用初診報状診査方法区分 */
     ztysaisinriyuukbn ,         /* （中継用）再診理由区分 */
     ztynyoutousaisinarihyouji ,         /* （中継用）尿糖再診有表示 */
     ztynyoutanpakusaisinarihyj ,         /* （中継用）尿蛋白再診有表示 */
     ztyhemasaisinarihyouji ,         /* （中継用）ヘマ再診有表示 */
     ztykettousaisinarihyouji ,         /* （中継用）血糖再診有表示 */
     ztysintyousaisinarihyouji ,         /* （中継用）身長再診有表示 */
     ztykyouisaisinarihyouji ,         /* （中継用）胸囲再診有表示 */
     ztyhukuisaisinarihyouji ,         /* （中継用）腹囲再診有表示 */
     ztytaijyuusaisinarihyouji ,         /* （中継用）体重再診有表示 */
     ztyketuatusaisinarihyouji ,         /* （中継用）血圧再診有表示 */
     ztyrndyusisnhujyusnssyacd ,         /* （中継用）連動用再診報状診査者コード */
     ztyrndyusisnhujyusnshuhukbn ,         /* （中継用）連動用再診報状診査方法区分 */
     ztynyoutoukbn ,         /* （中継用）尿糖区分 */
     ztyyobiv1x2 ,         /* （中継用）予備項目Ｖ１＿２ */
     ztynyoutanpakukbn ,         /* （中継用）尿蛋白区分 */
     ztyhemakbn ,         /* （中継用）ヘマ区分 */
     ztykettoutikeikajikan ,         /* （中継用）血糖値経過時間 */
     ztykettouti ,         /* （中継用）血糖値 */
     ztysintyou ,         /* （中継用）身長 */
     ztykyoui ,         /* （中継用）胸囲 */
     ztyhukui ,         /* （中継用）腹囲 */
     ztytaijyuu ,         /* （中継用）体重 */
     ztysaikouketuatu ,         /* （中継用）最高血圧 */
     ztysaiteiketuatu ,         /* （中継用）最低血圧 */
     ztyxsensyokencd ,         /* （中継用）Ｘ線所見コード */
     ztysindenzusyokencd ,         /* （中継用）心電図所見コード */
     ztyrnduyuganteisysnsyokencd ,         /* （中継用）連動用眼底写真所見コード */
     ztysinsahouhousiyoukbn ,         /* （中継用）診査方法使用区分 */
     ztyvipteikihyouji ,         /* （中継用）ＶＩＰ定期表示 */
     ztyhoujyounomihyouji ,         /* （中継用）報状のみ表示 */
     ztyketuekikensajissikbn ,         /* （中継用）血液検査実施区分 */
     ztymaruteisyuruikigou ,         /* （中継用）マル定種類記号 */
     ztyseizonmrtisyuruikgu ,         /* （中継用）生存マル定種類記号 */
     ztyketusikisoryou ,         /* （中継用）血色素量 */
     ztygot ,         /* （中継用）ＧＯＴ */
     ztygpt ,         /* （中継用）ＧＰＴ */
     ztyganmagtp ,         /* （中継用）ガンマＧＴＰ */
     ztysyumisyatkisindenzukbn ,         /* （中継用）証明書扱心電図区分 */
     ztykituenkbn ,         /* （中継用）喫煙区分 */
     ztytignmrtisyukgu ,         /* （中継用）逓減マル定種類記号 */
     ztyteigenmaruteikikan ,         /* （中継用）逓減マル定期間 */
     ztykituenhonsuu ,         /* （中継用）喫煙本数 */
     ztyyobiv2 ,         /* （中継用）予備項目Ｖ２ */
     ztysuuriyouyobin1x2 ,         /* （中継用）数理用予備項目Ｎ１＿２ */
     ztyrnduyusppinyuintkykntgk ,         /* （中継用）連動用疾病入院特約日額 */
     ztysuuriyouyobin12 ,         /* （中継用）数理用予備項目Ｎ１２ */
     ztyyobiv2x2 ,         /* （中継用）予備項目Ｖ２＿２ */
     ztysuuriyouyobin1x3 ,         /* （中継用）数理用予備項目Ｎ１＿３ */
     ztyyobin3 ,         /* （中継用）予備項目Ｎ３ */
     ztysuuriyouyobin12x2 ,         /* （中継用）数理用予備項目Ｎ１２＿２ */
     ztygoukeiteigenteikitkyks ,         /* （中継用）合計逓減定期特約Ｓ */
     ztytigntikbbntnknitjbrs ,         /* （中継用）逓減定期部分転換一時払Ｓ */
     ztytokuteisippeisetkbn ,         /* （中継用）特定疾病セット区分 */
     ztysuuriyouyobin2 ,         /* （中継用）数理用予備項目Ｎ２ */
     ztytaikakukijyunkanwahyouji ,         /* （中継用）体格基準緩和表示 */
     ztyhaitoukbn ,         /* （中継用）配当区分 */
     ztysnsykrketkbtsntkarihyj ,         /* （中継用）新種切替特別選択有表示 */
     ztyaatukaikojincd ,         /* （中継用）Ａ扱者個人コード */
     ztyyobiv1x5 ,         /* （中継用）予備項目Ｖ１＿５ */
     ztymanseisikkansetkbn ,         /* （中継用）慢性疾患セット区分 */
     ztygengakutenkankykhyj ,         /* （中継用）減額転換契約表示 */
     ztyyobiv2x4 ,         /* （中継用）予備項目Ｖ２＿４ */
     ztyfilekbn ,         /* （中継用）ファイル区分 */
     ztyyobiv2x5 ,         /* （中継用）予備項目Ｖ２＿５ */
     ztysuuriyouyobin1x4 ,         /* （中継用）数理用予備項目Ｎ１＿４ */
     ztyyobin3x2 ,         /* （中継用）予備項目Ｎ３＿２ */
     ztysuuriyouyobin12x3 ,         /* （中継用）数理用予備項目Ｎ１２＿３ */
     ztyyobiv2x6 ,         /* （中継用）予備項目Ｖ２＿６ */
     ztysuuriyouyobin1x5 ,         /* （中継用）数理用予備項目Ｎ１＿５ */
     ztyyobin3x3 ,         /* （中継用）予備項目Ｎ３＿３ */
     ztysuuriyouyobin12x4 ,         /* （中継用）数理用予備項目Ｎ１２＿４ */
     ztyyobiv2x7 ,         /* （中継用）予備項目Ｖ２＿７ */
     ztysuuriyouyobin1x6 ,         /* （中継用）数理用予備項目Ｎ１＿６ */
     ztyyobin3x4 ,         /* （中継用）予備項目Ｎ３＿４ */
     ztysuuriyouyobin12x5 ,         /* （中継用）数理用予備項目Ｎ１２＿５ */
     ztytaikakuhyouten ,         /* （中継用）体格標点 */
     ztynyoutousykykhyutn ,         /* （中継用）尿糖主契約標点 */
     ztynyoutanpakusykykhyutn ,         /* （中継用）尿蛋白主契約標点 */
     ztyketuatutandokuhyouten ,         /* （中継用）血圧単独標点 */
     ztyyobin5 ,         /* （中継用）予備項目Ｎ５ */
     ztysuuriyouyobin9 ,         /* （中継用）数理用予備項目Ｎ９ */
     ztyyobin5x2 ,         /* （中継用）予備項目Ｎ５＿２ */
     ztysuuriyouyobin9x2 ,         /* （中継用）数理用予備項目Ｎ９＿２ */
     ztyyobin5x3 ,         /* （中継用）予備項目Ｎ５＿３ */
     ztysuuriyouyobin9x3 ,         /* （中継用）数理用予備項目Ｎ９＿３ */
     ztysyunyumrtisyukgu ,         /* （中継用）収入マル定種類記号 */
     ztysyuunyuumaruteikikan ,         /* （中継用）収入マル定期間 */
     ztysyuunyuumrtinknengkn5 ,         /* （中継用）収入マル定年金年額Ｎ５ */
     ztysyuunyuumrtinkshrkkn ,         /* （中継用）収入マル定年金支払期間 */
     ztysuuriyouyobin12x6 ,         /* （中継用）数理用予備項目Ｎ１２＿６ */
     ztyhutanpobui1 ,         /* （中継用）不担保部位１ */
     ztyhtnpkkn1 ,         /* （中継用）不担保期間１ */
     ztyhutanpobui2 ,         /* （中継用）不担保部位２ */
     ztyhtnpkkn2 ,         /* （中継用）不担保期間２ */
     ztysyosinnyoutou ,         /* （中継用）初診尿糖 */
     ztysyosinnyoutanpaku ,         /* （中継用）初診尿蛋白 */
     ztysyosinnyousenketu ,         /* （中継用）初診尿潜血 */
     ztysyosinsaikouketuatu ,         /* （中継用）初診最高血圧 */
     ztysyosinsaiteiketuatu ,         /* （中継用）初診最低血圧 */
     ztysaisinnyoutou ,         /* （中継用）再診尿糖 */
     ztysaisinnyoutanpaku ,         /* （中継用）再診尿蛋白 */
     ztysaisinnyousenketu ,         /* （中継用）再診尿潜血 */
     ztysaisinsaikouketuatu ,         /* （中継用）再診最高血圧 */
     ztysaisinsaiteiketuatu ,         /* （中継用）再診最低血圧 */
     ztyketuekikensaijyou1 ,         /* （中継用）血液検査異常１ */
     ztyketuekikensaijyou2 ,         /* （中継用）血液検査異常２ */
     ztyketuekikensaijyou3 ,         /* （中継用）血液検査異常３ */
     ztyketuekikensaijyou4 ,         /* （中継用）血液検査異常４ */
     ztyketuekikensaijyou5 ,         /* （中継用）血液検査異常５ */
     ztyhukasyukeiyakukigou ,         /* （中継用）付加主契約記号 */
     ztysekininkaisiymd ,         /* （中継用）責任開始年月日 */
     ztysyosinmyakuhakusuu ,         /* （中継用）初診脈拍数 */
     ztysyosinhuseimyakusuu ,         /* （中継用）初診不整脈数 */
     ztysaisinmyakuhakusuu ,         /* （中継用）再診脈拍数 */
     ztysaisinhuseimyakusuu ,         /* （中継用）再診不整脈数 */
     ztysuuriyouyobin2x2 ,         /* （中継用）数理用予備項目Ｎ２＿２ */
     ztysouhyouten ,         /* （中継用）総標点 */
     ztytoukeiyukykymd ,         /* （中継用）統計用契約年月日 */
     ztydakuhiketteiriyuucdx1 ,         /* （中継用）諾否決定理由コード＿１ */
     ztydakuhiketteiriyuucdx2 ,         /* （中継用）諾否決定理由コード＿２ */
     ztydakuhiketteiriyuucdx3 ,         /* （中継用）諾否決定理由コード＿３ */
     ztydakuhiketteiriyuucdx4 ,         /* （中継用）諾否決定理由コード＿４ */
     ztykanwamaeryouzouhyouten ,         /* （中継用）緩和前料増標点 */
     ztyryoumasitokujyoukanwahyj ,         /* （中継用）料増特条緩和表示 */
     ztyhtnptokujyoukanwahyj ,         /* （中継用）不担保特条緩和表示 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztymaruteikigousedaikbn ,         /* （中継用）マル定記号世代区分 */
     ztyseizonmrtikgusdkbn ,         /* （中継用）生存マル定記号世代区分 */
     ztyteigenmrtikgusdkbn ,         /* （中継用）逓減マル定記号世代区分 */
     ztysyuunyuumrtikgusdkbn ,         /* （中継用）収入マル定記号世代区分 */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     ztyhksykykkgusdkbn ,         /* （中継用）付加主契約記号世代区分 */
     ztyhhknsynensyuukbn ,         /* （中継用）被保険者年収区分 */
     ztypmentokuyakukbn ,         /* （中継用）Ｐ免特約区分 */
     ztypmennenkansanp ,         /* （中継用）Ｐ免年換算Ｐ */
     ztyyobiv1x9 ,         /* （中継用）予備項目Ｖ１＿９ */
     ztysyosinsouchol ,         /* （中継用）初診総コレステロール */
     ztysyosinhdlchol ,         /* （中継用）初診ＨＤＬコレステロール */
     ztysyosintyuuseisibou ,         /* （中継用）初診中性脂肪 */
     ztysysnsyumisyatkikettouti ,         /* （中継用）初診証明書扱血糖値 */
     ztysyosintoukahemogurobin ,         /* （中継用）初診糖化ヘモグロビン */
     ztysyosinnyousan ,         /* （中継用）初診尿酸 */
     ztysyosinkureatinin ,         /* （中継用）初診クレアチニン */
     ztybosyuukeirokbn ,         /* （中継用）募集経路区分 */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztykigkyhsitihsyutkykarihyj ,         /* （中継用）介護給付最低保証特約有表示 */
     ztypmenhutanpobui1 ,         /* （中継用）Ｐ免不担保部位１ */
     ztypmenhutanpokikan1 ,         /* （中継用）Ｐ免不担保期間１ */
     ztypmenhutanpobui2 ,         /* （中継用）Ｐ免不担保部位２ */
     ztypmenhutanpokikan2 ,         /* （中継用）Ｐ免不担保期間２ */
     ztykanyujidatakanrino ,         /* （中継用）加入時データ管理番号 */
     ztybnktgsnzkkykdatakanrino ,         /* （中継用）分割後存続契約データ管理番号 */
     ztykykjiqpackhyj ,         /* （中継用）契約時Ｑパック表示 */
     ztyhokensyuruikigouyobi1x1 ,         /* （中継用）保険種類記号予備１＿１ */
     ztyhokensyuruikigouyobi1x2 ,         /* （中継用）保険種類記号予備１＿２ */
     ztyhokensyuruikigouyobi1x3 ,         /* （中継用）保険種類記号予備１＿３ */
     ztyhokensyuruikigouyobi1x4 ,         /* （中継用）保険種類記号予備１＿４ */
     ztyhokensyuruikigouyobi1x5 ,         /* （中継用）保険種類記号予備１＿５ */
     ztyhokensyuruikigouyobi1x6 ,         /* （中継用）保険種類記号予備１＿６ */
     ztyhokensyuruikigouyobi1x7 ,         /* （中継用）保険種類記号予備１＿７ */
     ztyhokensyuruikigouyobi1x8 ,         /* （中継用）保険種類記号予備１＿８ */
     ztyhokensyuruikigouyobi1x9 ,         /* （中継用）保険種類記号予備１＿９ */
     ztyhokensyuruikigouyobi1x10 ,         /* （中継用）保険種類記号予備１＿１０ */
     ztyhokensyuruikigouyobi1x11 ,         /* （中継用）保険種類記号予備１＿１１ */
     ztyhokensyuruikigouyobi1x12 ,         /* （中継用）保険種類記号予備１＿１２ */
     ztyhokensyuruikigouyobi1x13 ,         /* （中継用）保険種類記号予備１＿１３ */
     ztyhokensyuruikigouyobi1x14 ,         /* （中継用）保険種類記号予備１＿１４ */
     ztyhokensyuruikigouyobi1x15 ,         /* （中継用）保険種類記号予備１＿１５ */
     ztyhokensyuruikigouyobi2x1 ,         /* （中継用）保険種類記号予備２＿１ */
     ztyhokensyuruikigouyobi2x2 ,         /* （中継用）保険種類記号予備２＿２ */
     ztyhokensyuruikigouyobi2x3 ,         /* （中継用）保険種類記号予備２＿３ */
     ztyhokensyuruikigouyobi2x4 ,         /* （中継用）保険種類記号予備２＿４ */
     ztyhokensyuruikigouyobi2x5 ,         /* （中継用）保険種類記号予備２＿５ */
     ztyhokensyuruikigouyobi2x6 ,         /* （中継用）保険種類記号予備２＿６ */
     ztyhokensyuruikigouyobi2x7 ,         /* （中継用）保険種類記号予備２＿７ */
     ztyhokensyuruikigouyobi2x8 ,         /* （中継用）保険種類記号予備２＿８ */
     ztyhokensyuruikigouyobi2x9 ,         /* （中継用）保険種類記号予備２＿９ */
     ztyhokensyuruikigouyobi2x10 ,         /* （中継用）保険種類記号予備２＿１０ */
     ztyhokensyuruikigouyobi3x1 ,         /* （中継用）保険種類記号予備３＿１ */
     ztyhokensyuruikigouyobi3x2 ,         /* （中継用）保険種類記号予備３＿２ */
     ztyhokensyuruikigouyobi3x3 ,         /* （中継用）保険種類記号予備３＿３ */
     ztyhokensyuruikigouyobi3x4 ,         /* （中継用）保険種類記号予備３＿４ */
     ztyhokensyuruikigouyobi3x5 ,         /* （中継用）保険種類記号予備３＿５ */
     ztyhokensyuruikigouyobi3x6 ,         /* （中継用）保険種類記号予備３＿６ */
     ztyhokensyuruikigouyobi3x7 ,         /* （中継用）保険種類記号予備３＿７ */
     ztyhokensyuruikigouyobi3x8 ,         /* （中継用）保険種類記号予備３＿８ */
     ztyhokensyuruikigouyobi3x9 ,         /* （中継用）保険種類記号予備３＿９ */
     ztyhokensyuruikigouyobi3x10 ,         /* （中継用）保険種類記号予備３＿１０ */
     ztytokuyakukigouyobix1 ,         /* （中継用）特約記号予備＿１ */
     ztytokuyakukigouyobix2 ,         /* （中継用）特約記号予備＿２ */
     ztytokuyakukigouyobix3 ,         /* （中継用）特約記号予備＿３ */
     ztytokuyakukigouyobix4 ,         /* （中継用）特約記号予備＿４ */
     ztytokuyakukigouyobix5 ,         /* （中継用）特約記号予備＿５ */
     ztymaruteikigouyobix1 ,         /* （中継用）マル定記号予備＿１ */
     ztymaruteikigouyobix2 ,         /* （中継用）マル定記号予備＿２ */
     ztymaruteikigouyobix3 ,         /* （中継用）マル定記号予備＿３ */
     ztymaruteikigouyobix4 ,         /* （中継用）マル定記号予備＿４ */
     ztymaruteikigouyobix5 ,         /* （中継用）マル定記号予備＿５ */
     ztysiznmrtikguybx1 ,         /* （中継用）生存マル定記号予備＿１ */
     ztysiznmrtikguybx2 ,         /* （中継用）生存マル定記号予備＿２ */
     ztysiznmrtikguybx3 ,         /* （中継用）生存マル定記号予備＿３ */
     ztysiznmrtikguybx4 ,         /* （中継用）生存マル定記号予備＿４ */
     ztysiznmrtikguybx5 ,         /* （中継用）生存マル定記号予備＿５ */
     ztyteigenmaruteikigouyobix1 ,         /* （中継用）逓減マル定記号予備＿１ */
     ztyteigenmaruteikigouyobix2 ,         /* （中継用）逓減マル定記号予備＿２ */
     ztyteigenmaruteikigouyobix3 ,         /* （中継用）逓減マル定記号予備＿３ */
     ztyteigenmaruteikigouyobix4 ,         /* （中継用）逓減マル定記号予備＿４ */
     ztyteigenmaruteikigouyobix5 ,         /* （中継用）逓減マル定記号予備＿５ */
     ztysyuunyuumrtikguybx1 ,         /* （中継用）収入マル定記号予備＿１ */
     ztysyuunyuumrtikguybx2 ,         /* （中継用）収入マル定記号予備＿２ */
     ztysyuunyuumrtikguybx3 ,         /* （中継用）収入マル定記号予備＿３ */
     ztysyuunyuumrtikguybx4 ,         /* （中継用）収入マル定記号予備＿４ */
     ztysyuunyuumrtikguybx5 ,         /* （中継用）収入マル定記号予備＿５ */
     ztysuuriyouyobin5 ,         /* （中継用）数理用予備項目Ｎ５ */
     ztysuuriyouyobin5x2 ,         /* （中継用）数理用予備項目Ｎ５＿２ */
     ztysuuriyouyobin5x3 ,         /* （中継用）数理用予備項目Ｎ５＿３ */
     ztysuuriyouyobin5x4 ,         /* （中継用）数理用予備項目Ｎ５＿４ */
     ztysuuriyouyobin5x5 ,         /* （中継用）数理用予備項目Ｎ５＿５ */
     ztyyobiv2x9 ,         /* （中継用）予備項目Ｖ２＿９ */
     ztyyobin3x5 ,         /* （中継用）予備項目Ｎ３＿５ */
     ztysuuriyouyobin1x7 ,         /* （中継用）数理用予備項目Ｎ１＿７ */
     ztyyobiv1x11 ,         /* （中継用）予備項目Ｖ１＿１１ */
     ztysuuriyouyobin5x6 ,         /* （中継用）数理用予備項目Ｎ５＿６ */
     ztydakuhikettikjynsyrikbnx1 ,         /* （中継用）諾否決定基準種類区分＿１ */
     ztydakuhikettikjynsyrikbnx2 ,         /* （中継用）諾否決定基準種類区分＿２ */
     ztydakuhikettikjynsyrikbnx3 ,         /* （中継用）諾否決定基準種類区分＿３ */
     ztydakuhikettikjynsyrikbnx4 ,         /* （中継用）諾否決定基準種類区分＿４ */
     ztydakuhikettikjynsyrikbnx5 ,         /* （中継用）諾否決定基準種類区分＿５ */
     ztyhtnknkykdatakanrinox1 ,         /* （中継用）被転換契約データ管理番号＿１ */
     ztyhtnknkykdatakanrinox2 ,         /* （中継用）被転換契約データ管理番号＿２ */
     ztyhtnknkykdatakanrinox3 ,         /* （中継用）被転換契約データ管理番号＿３ */
     ztyhtnknkykdatakanrinox4 ,         /* （中継用）被転換契約データ管理番号＿４ */
     ztyhtnknkykdatakanrinox5 ,         /* （中継用）被転換契約データ管理番号＿５ */
     ztyhtnknkykdatakanrinox6 ,         /* （中継用）被転換契約データ管理番号＿６ */
     ztykeiyakusyahoujinkbn ,         /* （中継用）契約者法人区分 */
     ztysuuriyouyobin2x3 ,         /* （中継用）数理用予備項目Ｎ２＿３ */
     ztyhyujynkttidkhkttikekkacd ,         /* （中継用）標準決定諾否決定結果コード */
     ztyhyujynkttidkhkttiryucdx1 ,         /* （中継用）標準決定諾否決定理由コード＿１ */
     ztyhyujynkttidkhkttiryucdx2 ,         /* （中継用）標準決定諾否決定理由コード＿２ */
     ztyhyujynkttidkhkttiryucdx3 ,         /* （中継用）標準決定諾否決定理由コード＿３ */
     ztyhyujynkttidkhkttiryucdx4 ,         /* （中継用）標準決定諾否決定理由コード＿４ */
     ztyhyujynkttiryumshyutn ,         /* （中継用）標準決定料増標点 */
     ztyhyujynkttisakugenkkn ,         /* （中継用）標準決定削減期間 */
     ztysppitkykryumshyutn ,         /* （中継用）疾病特約料増標点 */
     ztyhyujynkttitktbuicdx1 ,         /* （中継用）標準決定特定部位コード＿１ */
     ztyhyujynkttihutanpokknx1 ,         /* （中継用）標準決定不担保期間＿１ */
     ztyhyujynkttitktbuicdx2 ,         /* （中継用）標準決定特定部位コード＿２ */
     ztyhyujynkttihutanpokknx2 ,         /* （中継用）標準決定不担保期間＿２ */
     ztyjyoukentukitaisyoukbnx1 ,         /* （中継用）条件付対象区分＿１ */
     ztyjyukntksseigenhyjx1 ,         /* （中継用）条件付Ｓ制限表示＿１ */
     ztyjyukntktkyknozokihyjx1 ,         /* （中継用）条件付特約除き表示＿１ */
     ztysuuriyouyobin1x8 ,         /* （中継用）数理用予備項目Ｎ１＿８ */
     ztyjyoukentukiseigensx1 ,         /* （中継用）条件付制限Ｓ＿１ */
     ztyjyoukentukitaisyoukbnx2 ,         /* （中継用）条件付対象区分＿２ */
     ztyjyukntksseigenhyjx2 ,         /* （中継用）条件付Ｓ制限表示＿２ */
     ztyjyukntktkyknozokihyjx2 ,         /* （中継用）条件付特約除き表示＿２ */
     ztysuuriyouyobin1x9 ,         /* （中継用）数理用予備項目Ｎ１＿９ */
     ztyjyoukentukiseigensx2 ,         /* （中継用）条件付制限Ｓ＿２ */
     ztyjyoukentukitaisyoukbnx3 ,         /* （中継用）条件付対象区分＿３ */
     ztyjyukntksseigenhyjx3 ,         /* （中継用）条件付Ｓ制限表示＿３ */
     ztyjyukntktkyknozokihyjx3 ,         /* （中継用）条件付特約除き表示＿３ */
     ztysuuriyouyobin1x10 ,         /* （中継用）数理用予備項目Ｎ１＿１０ */
     ztyjyoukentukiseigensx3 ,         /* （中継用）条件付制限Ｓ＿３ */
     ztyjyoukentukitaisyoukbnx4 ,         /* （中継用）条件付対象区分＿４ */
     ztyjyukntksseigenhyjx4 ,         /* （中継用）条件付Ｓ制限表示＿４ */
     ztyjyukntktkyknozokihyjx4 ,         /* （中継用）条件付特約除き表示＿４ */
     ztysuuriyouyobin1x11 ,         /* （中継用）数理用予備項目Ｎ１＿１１ */
     ztyjyoukentukiseigensx4 ,         /* （中継用）条件付制限Ｓ＿４ */
     ztyjyukntkkigtiksyrihnkuhyj ,         /* （中継用）条件付介護定期種類変更表示 */
     ztypmensyuruihenkoukbn ,         /* （中継用）Ｐ免種類変更区分 */
     ztyjyoukentukitaisyoukbn2x1 ,         /* （中継用）条件付対象区分２＿１ */
     ztyjyukntksseigenhyj2x1 ,         /* （中継用）条件付Ｓ制限表示２＿１ */
     ztyjyukntktkyknozokihyj2x1 ,         /* （中継用）条件付特約除き表示２＿１ */
     ztysuuriyouyobin1x12 ,         /* （中継用）数理用予備項目Ｎ１＿１２ */
     ztyjyoukentukiseigens2x1 ,         /* （中継用）条件付制限Ｓ２＿１ */
     ztyjyoukentukitaisyoukbn2x2 ,         /* （中継用）条件付対象区分２＿２ */
     ztyjyukntksseigenhyj2x2 ,         /* （中継用）条件付Ｓ制限表示２＿２ */
     ztyjyukntktkyknozokihyj2x2 ,         /* （中継用）条件付特約除き表示２＿２ */
     ztysuuriyouyobin1x13 ,         /* （中継用）数理用予備項目Ｎ１＿１３ */
     ztyjyoukentukiseigens2x2 ,         /* （中継用）条件付制限Ｓ２＿２ */
     ztyjyoukentukitaisyoukbn2x3 ,         /* （中継用）条件付対象区分２＿３ */
     ztyjyukntksseigenhyj2x3 ,         /* （中継用）条件付Ｓ制限表示２＿３ */
     ztyjyukntktkyknozokihyj2x3 ,         /* （中継用）条件付特約除き表示２＿３ */
     ztysuuriyouyobin1x14 ,         /* （中継用）数理用予備項目Ｎ１＿１４ */
     ztyjyoukentukiseigens2x3 ,         /* （中継用）条件付制限Ｓ２＿３ */
     ztyjyoukentukitaisyoukbn2x4 ,         /* （中継用）条件付対象区分２＿４ */
     ztyjyukntksseigenhyj2x4 ,         /* （中継用）条件付Ｓ制限表示２＿４ */
     ztyjyukntktkyknozokihyj2x4 ,         /* （中継用）条件付特約除き表示２＿４ */
     ztysuuriyouyobin1x15 ,         /* （中継用）数理用予備項目Ｎ１＿１５ */
     ztyjyoukentukiseigens2x4 ,         /* （中継用）条件付制限Ｓ２＿４ */
     ztytktsppiryumshyutn ,         /* （中継用）特定疾病料増標点 */
     ztytktsppiskgnkkn ,         /* （中継用）特定疾病削減期間 */
     ztymnsiskknryumshyutn ,         /* （中継用）慢性疾患料増標点 */
     ztymanseisikkansakugenkikan ,         /* （中継用）慢性疾患削減期間 */
     ztymanseisikkantokuteibuicd ,         /* （中継用）慢性疾患特定部位コード */
     ztymanseisikkanhutanpokikan ,         /* （中継用）慢性疾患不担保期間 */
     ztysaihokenkbn ,         /* （中継用）再保険区分 */
     ztyimustiyusbus ,         /* （中継用）医務査定用死亡Ｓ */
     ztyimusateiyoujissituhsyus ,         /* （中継用）医務査定用実質保障Ｓ */
     ztyisahtnkngukijissituhsyus ,         /* （中継用）医査被転換合計実質保障Ｓ */
     ztyimusateiyoutenkansagakus ,         /* （中継用）医務査定用転換差額Ｓ */
     ztyimusateiyouhanbaikirkbn ,         /* （中継用）医務査定用販売経路区分 */
     ztyoyabosyuudairitencd ,         /* （中継用）親募集代理店コード */
     ztysuuriyoubosyuukeitaikbn ,         /* （中継用）数理用募集形態区分 */
     ztyhihokensyahokenage ,         /* （中継用）被保険者保険年令 */
     ztyrendouyoumusntkkykhyj ,         /* （中継用）連動用無選択契約表示 */
     ztyyobiv2x11 ,         /* （中継用）予備項目Ｖ２＿１１ */
     ztyyobin3x6 ,         /* （中継用）予備項目Ｎ３＿６ */
     ztysuuriyouyobin9x4 ,         /* （中継用）数理用予備項目Ｎ９＿４ */
     ztyyobiv1x20 ,         /* （中継用）予備項目Ｖ１＿２０ */
     ztysuuriyouyobin5x7 ,         /* （中継用）数理用予備項目Ｎ５＿７ */
     ztyhhknnentysihyj ,         /* （中継用）被保険者年令調整表示 */
     ztysindenzusyokensyousaicd ,         /* （中継用）心電図所見詳細コード */
     ztyimstiyuktekknsjsshyj ,         /* （中継用）医務査定用血液検査実施表示 */
     ztyketuekikensasekkekkyuusu ,         /* （中継用）血液検査赤血球数 */
     ztyktekknsskkkkyususykncd ,         /* （中継用）血液検査赤血球数所見コード */
     ztyketuekikensahakkekkyuusu ,         /* （中継用）血液検査白血球数 */
     ztyktekknshkkkkyususykncd ,         /* （中継用）血液検査白血球数所見コード */
     ztyktekknsketusikisoryou ,         /* （中継用）血液検査血色素量 */
     ztyktekknsktsksryusyokencd ,         /* （中継用）血液検査血色素量所見コード */
     ztyktekknshematokuritto ,         /* （中継用）血液検査ヘマトクリット */
     ztyktekhmtkrttsykncd ,         /* （中継用）血液ヘマトクリット所見コード */
     ztyketuekikensakessyoubansu ,         /* （中継用）血液検査血小板数 */
     ztyktekknskssyubnsusyokencd ,         /* （中継用）血液検査血小板数所見コード */
     ztyktekknskssisutnpkryu ,         /* （中継用）血液検査血清総蛋白量 */
     ztyktekkssisutnpkryusykncd ,         /* （中継用）血液血清総蛋白量所見コード */
     ztyketuekikensaarubumin ,         /* （中継用）血液検査アルブミン */
     ztyktekknsarubuminsyokencd ,         /* （中継用）血液検査アルブミン所見コード */
     ztyketuekikensaztt ,         /* （中継用）血液検査ＺＴＴ */
     ztyketuekikensazttsyokencd ,         /* （中継用）血液検査ＺＴＴ所見コード */
     ztyketuekikensagot ,         /* （中継用）血液検査ＧＯＴ */
     ztyketuekikensagotsyokencd ,         /* （中継用）血液検査ＧＯＴ所見コード */
     ztyketuekikensagpt ,         /* （中継用）血液検査ＧＰＴ */
     ztyketuekikensagptsyokencd ,         /* （中継用）血液検査ＧＰＴ所見コード */
     ztyketuekikensaganmagtp ,         /* （中継用）血液検査ガンマＧＴＰ */
     ztyketuekiganmagtpsyokencd ,         /* （中継用）血液ガンマＧＴＰ所見コード */
     ztyketuekikensasouchol ,         /* （中継用）血液検査総コレステロール */
     ztyketuekicholsyokencd ,         /* （中継用）血液コレステロール所見コード */
     ztyketuekikensahdlchol ,         /* （中継用）血液検査ＨＤＬコレステロール */
     ztyketuekikensahdlsyokencd ,         /* （中継用）血液検査ＨＤＬ所見コード */
     ztyktekknstukhmgrbn ,         /* （中継用）血液検査糖化ヘモグロビン */
     ztyktekhmgrbnsykncd ,         /* （中継用）血液ヘモグロビン所見コード */
     ztyktekknskorinesuterrze ,         /* （中継用）血液検査コリンエステラーゼ */
     ztykorinesuterrzesyokencd ,         /* （中継用）コリンエステラーゼ所見コード */
     ztyketuekikensamcv ,         /* （中継用）血液検査ＭＣＶ */
     ztyketuekikensamcvsyokencd ,         /* （中継用）血液検査ＭＣＶ所見コード */
     ztyketuekikensamch ,         /* （中継用）血液検査ＭＣＨ */
     ztyketuekikensamchsyokencd ,         /* （中継用）血液検査ＭＣＨ所見コード */
     ztyketuekikensamchc ,         /* （中継用）血液検査ＭＣＨＣ */
     ztyketuekikensamchcsyokencd ,         /* （中継用）血液検査ＭＣＨＣ所見コード */
     ztyketuekikensacea ,         /* （中継用）血液検査ＣＥＡ */
     ztyketuekikensaceasyokencd ,         /* （中継用）血液検査ＣＥＡ所見コード */
     ztyketuekikensaafp ,         /* （中継用）血液検査ＡＦＰ */
     ztyketuekikensaafpsyokencd ,         /* （中継用）血液検査ＡＦＰ所見コード */
     ztyketuekikensahbskbn ,         /* （中継用）血液検査ＨＢＳ区分 */
     ztyketuekikensahbssyokencd ,         /* （中継用）血液検査ＨＢＳ所見コード */
     ztyketuekikensahcvkbn ,         /* （中継用）血液検査ＨＣＶ区分 */
     ztyketuekikensahcvsyokencd ,         /* （中継用）血液検査ＨＣＶ所見コード */
     ztyimusateiyouknsnsytryskbn ,         /* （中継用）医務査定用健診書取寄区分 */
     ztysyosinldlchol ,         /* （中継用）初診ＬＤＬコレステロール */
     ztytokuteijyoutaihushrhyj ,         /* （中継用）特定状態不支払表示 */
     ztyrendouyouosyukeiyakup ,         /* （中継用）連動用主契約Ｐ */
     ztytokubetuhosyoukikan ,         /* （中継用）特別保障期間 */
     ztyrendouyougoukeitenkans ,         /* （中継用）連動用合計転換Ｓ */
     ztyrnduyugukitnknkakaku ,         /* （中継用）連動用合計転換価格 */
     ztyrnduyuwnsgukitnknkakaku ,         /* （中継用）連動用Ｗなし合計転換価格 */
     ztymostnknkhnbbnjyuturt ,         /* （中継用）申込転換基本部分充当率 */
     ztyrnduyusykykbbnkhns ,         /* （中継用）連動用主契約部分基本Ｓ */
     ztyrendouyouyoteiriritu ,         /* （中継用）連動用予定利率 */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyyobiv121 ,         /* （中継用）予備項目Ｖ１２１ */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztygaikadatekihons ,         /* （中継用）外貨建基本Ｓ */
     ztygaikadatesibous ,         /* （中継用）外貨建死亡Ｓ */
     ztykeiyakujiyoteiriritu ,         /* （中継用）契約時予定利率 */
     ztykawaserate ,         /* （中継用）為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztyenkdtsbujsitihsyukngk ,         /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10 ,         /* （中継用）数理用予備項目Ｎ１０ */
     ztysuuriyouyobin10x2 ,         /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobiv10x3 ,         /* （中継用）予備項目Ｖ１０＿３ */
     ztyyobiv10x4 ,         /* （中継用）予備項目Ｖ１０＿４ */
     ztyyobin7 ,         /* （中継用）予備項目Ｎ７ */
     ztyyobin7x2 ,         /* （中継用）予備項目Ｎ７＿２ */
     ztyyobin7x3 ,         /* （中継用）予備項目Ｎ７＿３ */
     ztyyobin7x4 ,         /* （中継用）予備項目Ｎ７＿４ */
     ztyyobin7x5 ,         /* （中継用）予備項目Ｎ７＿５ */
     ztyyobiv4x2 ,         /* （中継用）予備項目Ｖ４＿２ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SbRituRendouTy_Z;