CREATE VIEW ZT_HrhnTtdkKanTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztytyouhyouymdkj ,         /* （中継用）帳票作成日（漢字） */
     ztysyono ,         /* （中継用）証券番号 */
     ztysikibetuno ,         /* （中継用）識別番号 */
     ztyyobiv7 ,         /* （中継用）予備項目Ｖ７ */
     ztyansyuyouyobin10 ,         /* （中継用）案内収納用予備項目Ｎ１０ */
     ztyshskyno ,         /* （中継用）送付先郵便番号 */
     ztyshskadr1kj ,         /* （中継用）送付先住所１（漢字） */
     ztyshskadr2kj ,         /* （中継用）送付先住所２（漢字） */
     ztyshskadr3kj ,         /* （中継用）送付先住所３（漢字） */
     ztyshsnmkj ,         /* （中継用）送付先名（漢字） */
     ztyyobiv43 ,         /* （中継用）予備項目Ｖ４３ */
     ztyansyuyouyobin10x2 ,         /* （中継用）案内収納用予備項目Ｎ１０＿２ */
     ztytawsosikikj ,         /* （中継用）問合せ先組織名（漢字） */
     ztytawyno ,         /* （中継用）問合せ先郵便番号 */
     ztytawadr1kj ,         /* （中継用）問合せ先住所１（漢字） */
     ztytawadr2kj ,         /* （中継用）問合せ先住所２（漢字） */
     ztytawadr3kj ,         /* （中継用）問合せ先住所３（漢字） */
     ztytawtelnov14 ,         /* （中継用）問合せ先電話番号Ｖ１４ */
     ztytawteluktkkanou1 ,         /* （中継用）問合せ先電話受付可能時間１ */
     ztytawteluktkkanou2 ,         /* （中継用）問合せ先電話受付可能時間２ */
     ztydai2tawsosikinmkj ,         /* （中継用）第２問合せ先組織名（漢字） */
     ztydai2tawtelno ,         /* （中継用）第２問合せ先電話番号 */
     ztysclatosyono ,         /* （中継用）スクランブル後証券番号 */
     ztysakunm15keta ,         /* （中継用）作成番号（１５桁） */
     ztyyobiv63 ,         /* （中継用）予備項目Ｖ６３ */
     ztyansyuyouyobin10x3 ,         /* （中継用）案内収納用予備項目Ｎ１０＿３ */
     ztykouzamaskingmsg ,         /* （中継用）口座マスキングＭＳＧ */
     ztyhrkkaisuutkiktbrisyu ,         /* （中継用）払込回数・定期一括払種類 */
     ztyhrkkeiro ,         /* （中継用）払込経路 */
     ztyhrkp ,         /* （中継用）払込保険料 */
     ztykouryokuhasseiymmsg ,         /* （中継用）効力発生年月ＭＳＧ */
     ztysakuseijitenmsg ,         /* （中継用）作成時点メッセージ */
     ztykingakumidasi1 ,         /* （中継用）金額見出し１ */
     ztykingaku1 ,         /* （中継用）金額１ */
     ztykingakumidasi2 ,         /* （中継用）金額見出し２ */
     ztykingaku2 ,         /* （中継用）金額２ */
     ztykingakumidasi3 ,         /* （中継用）金額見出し３ */
     ztykingaku3 ,         /* （中継用）金額３ */
     ztyyobiv64 ,         /* （中継用）予備項目Ｖ６４ */
     ztyansyuyouyobin10x4 ,         /* （中継用）案内収納用予備項目Ｎ１０＿４ */
     ztymsgarea34keta1 ,         /* （中継用）メッセージエリア（３４桁）１ */
     ztymsgarea34keta2 ,         /* （中継用）メッセージエリア（３４桁）２ */
     ztymsgarea34keta3 ,         /* （中継用）メッセージエリア（３４桁）３ */
     ztymsgarea34keta4 ,         /* （中継用）メッセージエリア（３４桁）４ */
     ztymsgarea34keta5 ,         /* （中継用）メッセージエリア（３４桁）５ */
     ztymsgarea34keta6 ,         /* （中継用）メッセージエリア（３４桁）６ */
     ztymsgarea34keta7 ,         /* （中継用）メッセージエリア（３４桁）７ */
     ztyyobiv95 ,         /* （中継用）予備項目Ｖ９５ */
     ztyansyuyouyobin10x5 ,         /* （中継用）案内収納用予備項目Ｎ１０＿５ */
     ztyhurikaeyokokumsg34keta1 ,         /* （中継用）振替予告メッセージ（３４桁）１ */
     ztyhurikaeyokokumsg34keta2 ,         /* （中継用）振替予告メッセージ（３４桁）２ */
     ztyhurikaeyokokumsg34keta3 ,         /* （中継用）振替予告メッセージ（３４桁）３ */
     ztyhurikaeyokokumsg34keta4 ,         /* （中継用）振替予告メッセージ（３４桁）４ */
     ztyhurikaeyokokumsg34keta5 ,         /* （中継用）振替予告メッセージ（３４桁）５ */
     ztyhurikaeyokokumsg34keta6 ,         /* （中継用）振替予告メッセージ（３４桁）６ */
     ztyhurikaeyokokumsg34keta7 ,         /* （中継用）振替予告メッセージ（３４桁）７ */
     ztyhurikaeyokokumsg34keta8 ,         /* （中継用）振替予告メッセージ（３４桁）８ */
     ztyhurikaeyokokumsg34keta9 ,         /* （中継用）振替予告メッセージ（３４桁）９ */
     ztyhurikaeyokokumsg34keta10 ,         /* （中継用）振替予告メッセージ（３４桁）１０ */
     ztyhurikaeyokokumsg34keta11 ,         /* （中継用）振替予告メッセージ（３４桁）１１ */
     ztyhurikaeyokokumsg34keta12 ,         /* （中継用）振替予告メッセージ（３４桁）１２ */
     ztyhurikaeyokokumsg34keta13 ,         /* （中継用）振替予告メッセージ（３４桁）１３ */
     ztyhurikaeyokokumsg34keta14 ,         /* （中継用）振替予告メッセージ（３４桁）１４ */
     ztyhurikaeyokokumsg34keta15 ,         /* （中継用）振替予告メッセージ（３４桁）１５ */
     ztyhurikaeyokokumsg34keta16 ,         /* （中継用）振替予告メッセージ（３４桁）１６ */
     ztyhurikaeyokokumsg34keta17 ,         /* （中継用）振替予告メッセージ（３４桁）１７ */
     ztyhurikaeyokokumsg34keta18 ,         /* （中継用）振替予告メッセージ（３４桁）１８ */
     ztyhurikaeyokokumsg34keta19 ,         /* （中継用）振替予告メッセージ（３４桁）１９ */
     ztyhurikaeyokokumsg34keta20 ,         /* （中継用）振替予告メッセージ（３４桁）２０ */
     ztyhurikaeyokokumsg34keta21 ,         /* （中継用）振替予告メッセージ（３４桁）２１ */
     ztyhurikaeyokokumsg34keta22 ,         /* （中継用）振替予告メッセージ（３４桁）２２ */
     ztyhurikaeyokokumsg34keta23 ,         /* （中継用）振替予告メッセージ（３４桁）２３ */
     ztyhurikaeyokokumsg34keta24 ,         /* （中継用）振替予告メッセージ（３４桁）２４ */
     ztyhurikaeyokokumsg34keta25 ,         /* （中継用）振替予告メッセージ（３４桁）２５ */
     ztyhurikaeyokokumsg34keta26 ,         /* （中継用）振替予告メッセージ（３４桁）２６ */
     ztyhurikaeyokokumsg34keta27 ,         /* （中継用）振替予告メッセージ（３４桁）２７ */
     ztyhurikaeyokokumsg34keta28 ,         /* （中継用）振替予告メッセージ（３４桁）２８ */
     ztyyobiv131 ,         /* （中継用）予備項目Ｖ１３１ */
     ztyyobiv250 ,         /* （中継用）予備項目Ｖ２５０ */
     ztyansyuyouyobin10x6 ,         /* （中継用）案内収納用予備項目Ｎ１０＿６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_HrhnTtdkKanTy_Z;