CREATE VIEW JT_SiBikinkanri AS SELECT
     skno ,         /* 請求番号 */
     syono ,         /* 証券番号 */
     kessankijyunymd ,         /* 決算基準日 */
     bkncdkbn ,         /* 備金コード区分 */
     bknkktymd ,         /* 備金確定日 */
     kyuuhucd ,         /* 給付コード */
     bknrigikbn ,         /* 備金例外区分 */
     seikyuusyubetu ,         /* 請求種別 */
     calckijyunymd ,         /* 計算基準日 */
     syoruiukeymd ,         /* 書類受付日 */
     hubikanryouymd ,         /* 不備完了日 */
     syouhnsyuruikbn ,         /* 商品種類区分 */
     syutkkbn ,         /* 主契約特約区分 */
     sisyacd ,         /* 支社コード */
     kbnkeirisegcd ,         /* 区分経理用セグメントコード */
     syouhncd ,         /* 商品コード */
     kyuuhuname ,         /* 給付名 */
     bkngk ,         /* 備金額 */
     bkngk$ ,         /* 備金額(通貨型) */
     kihons ,         /* 基本Ｓ */
     kihons$ ,         /* 基本Ｓ(通貨型) */
     shrumu ,         /* 支払有無区分 */
     sinsaumukbn ,         /* 診査有無区分 */
     soukiumukbn ,         /* 早期有無区分 */
     syoumetuumukbn ,         /* 消滅有無区分 */
     hubijyoukyoukbn ,         /* 不備状況区分 */
     bknjkukbn ,         /* 備金時効区分 */
     shrsyoriymd ,         /* 支払処理日 */
     tyakkinymd ,         /* 着金日 */
     kyktuukasyu ,         /* 契約通貨種類 */
     shrtuukasyu ,         /* 支払通貨種類 */
     shrgk ,         /* 支払金額 */
     shrgk$ ,         /* 支払金額(通貨型) */
     shrkwsratekjnymd ,         /* 支払時為替レート基準日 */
     shrkwsrate ,         /* 支払時為替レート */
     sitihsyutkyumaeyenhknkngk ,         /* 最低保証適用前円換算保険金額 */
     sitihsyutkyumaeyenhknkngk$ ,         /* 最低保証適用前円換算保険金額(通貨型) */
     initsbjiyenkasaiteihsygk ,         /* 初期死亡時円換算最低保証額 */
     initsbjiyenkasaiteihsygk$ ,         /* 初期死亡時円換算最低保証額(通貨型) */
     siboukaritrkymd ,         /* 死亡仮受付登録日 */
     shrkekkakbn ,         /* 支払結果区分 */
     hushrgeninkbn ,         /* 不支払原因区分 */
     siinkbn ,         /* 死因区分 */
     kinoussnm ,         /* 機能詳細名 */
     suketorihouhoukbn ,         /* 保険金受取方法区分 */
     tutakngk ,         /* 積立金額 */
     tutakngk$ ,         /* 積立金額(通貨型) */
     yentutakngk ,         /* 円換算積立金額 */
     yentutakngk$ ,         /* 円換算積立金額(通貨型) */
     kaiyakuhr ,         /* 解約返戻金 */
     kaiyakuhr$ ,         /* 解約返戻金(通貨型) */
     yenkaiyakuhr ,         /* 円換算解約返戻金 */
     yenkaiyakuhr$ ,         /* 円換算解約返戻金(通貨型) */
     gengkumukbn ,         /* 減額有無区分 */
     gengkymd ,         /* 減額日 */
     jisatumensekiumukbn ,         /* 自殺免責有無区分 */
     syuukeiyoubkncdkbn ,         /* 集計用備金コード区分 */
     hokenkinsyuruikbn ,         /* 保険金種類区分 */
     bkntyousafsyorikbn ,         /* 備金調査ファイル処理区分 */
     bknkktinnd ,         /* 備金確定年度 */
     bknkktiym ,         /* 備金確定年月 */
     kykymd ,         /* 契約日 */
     zennouseisankinumukbn ,         /* 前納精算金有無区分 */
     zennouseisankgk ,         /* 前納精算金額 */
     zennouseisankgk$ ,         /* 前納精算金額(通貨型) */
     yenkazennouseisankgk ,         /* 円貨前納精算金額 */
     yenkazennouseisankgk$ ,         /* 円貨前納精算金額(通貨型) */
     mikeikapumukbn ,         /* 未経過保険料有無区分 */
     mikeikap ,         /* 未経過保険料 */
     mikeikap$ ,         /* 未経過保険料(通貨型) */
     yenkamikeikap ,         /* 円貨未経過保険料 */
     yenkamikeikap$ ,         /* 円貨未経過保険料(通貨型) */
     misyuupumukbn ,         /* 未収保険料有無区分 */
     misyuupjyuutouym ,         /* 未収保険料充当年月 */
     hrkp ,         /* 払込保険料 */
     hrkp$ ,         /* 払込保険料(通貨型) */
     misyuup ,         /* 未収保険料 */
     misyuup$ ,         /* 未収保険料(通貨型) */
     yenkamisyuup ,         /* 円貨未収保険料 */
     yenkamisyuup$ ,         /* 円貨未収保険料(通貨型) */
     hrkkaisuu ,         /* 払込回数 */
     syonendojikaiikoup ,         /* 初年度次回以降Ｐ */
     syonendojikaiikoup$ ,         /* 初年度次回以降Ｐ(通貨型) */
     yenkasyonendojikaiikoup ,         /* 円貨初年度次回以降Ｐ */
     yenkasyonendojikaiikoup$ ,         /* 円貨初年度次回以降Ｐ(通貨型) */
     jinendoikoup ,         /* 次年度以降Ｐ */
     jinendoikoup$ ,         /* 次年度以降Ｐ(通貨型) */
     yenkajinendoikoup ,         /* 円貨次年度以降Ｐ */
     yenkajinendoikoup$ ,         /* 円貨次年度以降Ｐ(通貨型) */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM JT_SiBikinkanri_Z;