CREATE VIEW ZT_SaihakkouHokensyoukenRn AS SELECT
     zrnsyoruicd ,         /* （連携用）書類コード */
     zrntyouhyouymd ,         /* （連携用）帳票作成日 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnhassoukbn ,         /* （連携用）発送区分 */
     zrnkanryoutuutidouhuukbn ,         /* （連携用）完了通知同封区分 */
     zrnsikibetuno ,         /* （連携用）識別番号 */
     zrnstdrsktirasidouhuukbn ,         /* （連携用）指定代理請求チラシ同封区分 */
     zrnaisyoumeikbn ,         /* （連携用）愛称名区分 */
     zrnsagyoukbn ,         /* （連携用）作業区分 */
     zrnyakkanbunsyono ,         /* （連携用）約款文書番号 */
     zrnyobiv23x2 ,         /* （連携用）予備項目Ｖ２３＿２ */
     zrnhyoujiranhidarimsgcd1 ,         /* （連携用）表示欄左メッセージコード１ */
     zrnhyoujiranhidarimsgcd2 ,         /* （連携用）表示欄左メッセージコード２ */
     zrnhyoujiranhidarimsgcd3 ,         /* （連携用）表示欄左メッセージコード３ */
     zrnhyoujiranhidarimsgcd4 ,         /* （連携用）表示欄左メッセージコード４ */
     zrnhyoujiranhidarimsgcd5 ,         /* （連携用）表示欄左メッセージコード５ */
     zrnhyoujiranhidarimsgcd6 ,         /* （連携用）表示欄左メッセージコード６ */
     zrnhyoujiranhidarimsgcd7 ,         /* （連携用）表示欄左メッセージコード７ */
     zrnhyoujiranhidarimsgcd8 ,         /* （連携用）表示欄左メッセージコード８ */
     zrnhyoujiranhidarimsgcd9 ,         /* （連携用）表示欄左メッセージコード９ */
     zrnhyoujiranhidarimsgcd10 ,         /* （連携用）表示欄左メッセージコード１０ */
     zrnhyoujiranhidarimsgcd11 ,         /* （連携用）表示欄左メッセージコード１１ */
     zrnhyoujiranhidarimsgcd12 ,         /* （連携用）表示欄左メッセージコード１２ */
     zrnhyoujiranhidarimsgcd13 ,         /* （連携用）表示欄左メッセージコード１３ */
     zrnhyoujiranhidarimsgcd14 ,         /* （連携用）表示欄左メッセージコード１４ */
     zrnhyoujiranhidarimsgcd15 ,         /* （連携用）表示欄左メッセージコード１５ */
     zrnhyoujiranhidarimsgcd16 ,         /* （連携用）表示欄左メッセージコード１６ */
     zrnhyoujiranhidarimsgcd17 ,         /* （連携用）表示欄左メッセージコード１７ */
     zrnhyoujiranhidarimsgcd18 ,         /* （連携用）表示欄左メッセージコード１８ */
     zrnhyoujiranhidarimsgcd19 ,         /* （連携用）表示欄左メッセージコード１９ */
     zrnhyoujiranhidarimsgcd20 ,         /* （連携用）表示欄左メッセージコード２０ */
     zrnhyoujiranmigimsgcd1 ,         /* （連携用）表示欄右メッセージコード１ */
     zrnhyoujiranmigimsgcd2 ,         /* （連携用）表示欄右メッセージコード２ */
     zrnhyoujiranmigimsgcd3 ,         /* （連携用）表示欄右メッセージコード３ */
     zrnhyoujiranmigimsgcd4 ,         /* （連携用）表示欄右メッセージコード４ */
     zrnhyoujiranmigimsgcd5 ,         /* （連携用）表示欄右メッセージコード５ */
     zrnhyoujiranmigimsgcd6 ,         /* （連携用）表示欄右メッセージコード６ */
     zrnhyoujiranmigimsgcd7 ,         /* （連携用）表示欄右メッセージコード７ */
     zrnhyoujiranmigimsgcd8 ,         /* （連携用）表示欄右メッセージコード８ */
     zrnhyoujiranmigimsgcd9 ,         /* （連携用）表示欄右メッセージコード９ */
     zrnhyoujiranmigimsgcd10 ,         /* （連携用）表示欄右メッセージコード１０ */
     zrnhyoujiranmigimsgcd11 ,         /* （連携用）表示欄右メッセージコード１１ */
     zrnhyoujiranmigimsgcd12 ,         /* （連携用）表示欄右メッセージコード１２ */
     zrnhyoujiranmigimsgcd13 ,         /* （連携用）表示欄右メッセージコード１３ */
     zrnhyoujiranmigimsgcd14 ,         /* （連携用）表示欄右メッセージコード１４ */
     zrnhyoujiranmigimsgcd15 ,         /* （連携用）表示欄右メッセージコード１５ */
     zrnhyoujiranmigimsgcd16 ,         /* （連携用）表示欄右メッセージコード１６ */
     zrnhyoujiranmigimsgcd17 ,         /* （連携用）表示欄右メッセージコード１７ */
     zrnhyoujiranmigimsgcd18 ,         /* （連携用）表示欄右メッセージコード１８ */
     zrnhyoujiranmigimsgcd19 ,         /* （連携用）表示欄右メッセージコード１９ */
     zrnhyoujiranmigimsgcd20 ,         /* （連携用）表示欄右メッセージコード２０ */
     zrnsknnkaisiymdseireki ,         /* （連携用）責任開始日（西暦） */
     zrnhyoujiranytirrt ,         /* （連携用）表示欄予定利率 */
     zrnhyoujiransjkkktusirrt ,         /* （連携用）表示欄市場価格調整用利率 */
     zrnhyoujirantumitateriritu ,         /* （連携用）表示欄積立利率 */
     zrnhyoujirantmttknzkrtjygn ,         /* （連携用）表示欄積立金増加率の上限 */
     zrnhyoujiransetteibairitu ,         /* （連携用）表示欄設定倍率 */
     zrnyobiv30x2 ,         /* （連携用）予備項目Ｖ３０＿２ */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnsyoukenhakkouymd ,         /* （連携用）証券発行年月日 */
     zrnkouryokukaisimsg ,         /* （連携用）効力開始メッセージ */
     zrnseisikihknnmsyouken ,         /* （連携用）正式保険名称（証券） */
     zrnnksyuruinmsyouken ,         /* （連携用）年金種類名称（証券用） */
     zrnyobiv116 ,         /* （連携用）予備項目Ｖ１１６ */
     zrnkyknmkj ,         /* （連携用）契約者名（漢字） */
     zrnhhknnmkj ,         /* （連携用）被保険者名（漢字） */
     zrnhihknsyaseiymdwareki ,         /* （連携用）被保険者生年月日（和暦） */
     zrnhhknsei ,         /* （連携用）被保険者性別 */
     zrnhhknnen2 ,         /* （連携用）被保険者年齢Ｃ２ */
     zrnuktmidasikbn1 ,         /* （連携用）受取人見出し区分１ */
     zrnuktkbn1 ,         /* （連携用）受取人区分１ */
     zrnuktnm1 ,         /* （連携用）受取人名１ */
     zrnuktbnwari1 ,         /* （連携用）受取人分割割合１ */
     zrnuktmidasikbn2 ,         /* （連携用）受取人見出し区分２ */
     zrnuktkbn2 ,         /* （連携用）受取人区分２ */
     zrnuktnm2 ,         /* （連携用）受取人名２ */
     zrnuktbnwari2 ,         /* （連携用）受取人分割割合２ */
     zrnuktmidasikbn3 ,         /* （連携用）受取人見出し区分３ */
     zrnuktkbn3 ,         /* （連携用）受取人区分３ */
     zrnuktnm3 ,         /* （連携用）受取人名３ */
     zrnuktbnwari3 ,         /* （連携用）受取人分割割合３ */
     zrnuktmidasikbn4 ,         /* （連携用）受取人見出し区分４ */
     zrnuktkbn4 ,         /* （連携用）受取人区分４ */
     zrnuktnm4 ,         /* （連携用）受取人名４ */
     zrnuktbnwari4 ,         /* （連携用）受取人分割割合４ */
     zrnuktmidasikbn5 ,         /* （連携用）受取人見出し区分５ */
     zrnuktkbn5 ,         /* （連携用）受取人区分５ */
     zrnuktnm5 ,         /* （連携用）受取人名５ */
     zrnuktbnwari5 ,         /* （連携用）受取人分割割合５ */
     zrnuktmidasikbn6 ,         /* （連携用）受取人見出し区分６ */
     zrnuktkbn6 ,         /* （連携用）受取人区分６ */
     zrnuktnm6 ,         /* （連携用）受取人名６ */
     zrnuktbnwari6 ,         /* （連携用）受取人分割割合６ */
     zrnuktmidasikbn7 ,         /* （連携用）受取人見出し区分７ */
     zrnuktkbn7 ,         /* （連携用）受取人区分７ */
     zrnuktnm7 ,         /* （連携用）受取人名７ */
     zrnuktbnwari7 ,         /* （連携用）受取人分割割合７ */
     zrnuktmidasikbn8 ,         /* （連携用）受取人見出し区分８ */
     zrnuktkbn8 ,         /* （連携用）受取人区分８ */
     zrnuktnm8 ,         /* （連携用）受取人名８ */
     zrnuktbnwari8 ,         /* （連携用）受取人分割割合８ */
     zrnuktmidasikbn9 ,         /* （連携用）受取人見出し区分９ */
     zrnuktkbn9 ,         /* （連携用）受取人区分９ */
     zrnuktnm9 ,         /* （連携用）受取人名９ */
     zrnuktbnwari9 ,         /* （連携用）受取人分割割合９ */
     zrnuktmidasikbn10 ,         /* （連携用）受取人見出し区分１０ */
     zrnuktkbn10 ,         /* （連携用）受取人区分１０ */
     zrnuktnm10 ,         /* （連携用）受取人名１０ */
     zrnuktbnwari10 ,         /* （連携用）受取人分割割合１０ */
     zrnyobiv45 ,         /* （連携用）予備項目Ｖ４５ */
     zrnpmsgcd1 ,         /* （連携用）保険料メッセージコード１ */
     zrnpmsgcd2 ,         /* （連携用）保険料メッセージコード２ */
     zrnpmsgcd3 ,         /* （連携用）保険料メッセージコード３ */
     zrnyobiv10 ,         /* （連携用）予備項目Ｖ１０ */
     zrnptuukatype ,         /* （連携用）保険料金額通貨タイプ */
     zrnteikiikkatubaraitukisuu ,         /* （連携用）定期一括払月数 */
     zrnztikiktbriyhrkgktuktype ,         /* （連携用）前納定期一括払円貨払込額通貨タイプ */
     zrnznntikiktbriyenhrkgk ,         /* （連携用）前納定期一括払円貨払込額 */
     zrnznnkai ,         /* （連携用）前納回数 */
     zrnpkngk ,         /* （連携用）保険料金額 */
     zrnpkngktuuka ,         /* （連携用）保険料金額通貨 */
     zrnptokuyakumsgcd ,         /* （連携用）保険料特約メッセージコード */
     zrnyobiv48 ,         /* （連携用）予備項目Ｖ４８ */
     zrnkykymdseireki ,         /* （連携用）契約年月日（西暦） */
     zrnphrkkknmidasikbn ,         /* （連携用）保険料払込期間見出し区分 */
     zrnhrkkknmsgkbn ,         /* （連携用）払込期間メッセージ区分 */
     zrnhrkkaisuumsgkbn ,         /* （連携用）払込回数メッセージ区分 */
     zrnphrkktuki ,         /* （連携用）保険料払込期月 */
     zrnhrkhouhoumsgkbn ,         /* （連携用）払込方法メッセージ区分 */
     zrnyobiv18 ,         /* （連携用）予備項目Ｖ１８ */
     zrnsyukyktkykrenban1 ,         /* （連携用）主契約特約連番１ */
     zrnsyukyktkykmsgkbn1 ,         /* （連携用）主契約特約メッセージ区分１ */
     zrnsyukyktkyksmsgkbn1 ,         /* （連携用）主契約特約保険金額メッセージ区分１ */
     zrnsyukyktkykhknkknmsgkbn1 ,         /* （連携用）主契約特約保険期間メッセージ区分１ */
     zrnsyukyktkykstuukatype1 ,         /* （連携用）主契約特約保険金額通貨タイプ１ */
     zrnsyukyktkykhknkngk1 ,         /* （連携用）主契約特約保険金額１ */
     zrnsyutkdai1hknkknymdto1 ,         /* （連携用）主契約特約第１保険期間年月日（至）１ */
     zrnsyutkdai2hknkknymdto1 ,         /* （連携用）主契約特約第２保険期間年月日（至）１ */
     zrnyobiv22 ,         /* （連携用）予備項目Ｖ２２ */
     zrnsyukyktkykrenban2 ,         /* （連携用）主契約特約連番２ */
     zrnsyukyktkykmsgkbn2 ,         /* （連携用）主契約特約メッセージ区分２ */
     zrnsyukyktkyksmsgkbn2 ,         /* （連携用）主契約特約保険金額メッセージ区分２ */
     zrnsyukyktkykhknkknmsgkbn2 ,         /* （連携用）主契約特約保険期間メッセージ区分２ */
     zrnsyukyktkykstuukatype2 ,         /* （連携用）主契約特約保険金額通貨タイプ２ */
     zrnsyukyktkykhknkngk2 ,         /* （連携用）主契約特約保険金額２ */
     zrnsyutkdai1hknkknymdto2 ,         /* （連携用）主契約特約第１保険期間年月日（至）２ */
     zrnsyutkdai2hknkknymdto2 ,         /* （連携用）主契約特約第２保険期間年月日（至）２ */
     zrnyobiv22x2 ,         /* （連携用）予備項目Ｖ２２＿２ */
     zrnsyukyktkykrenban3 ,         /* （連携用）主契約特約連番３ */
     zrnsyukyktkykmsgkbn3 ,         /* （連携用）主契約特約メッセージ区分３ */
     zrnsyukyktkyksmsgkbn3 ,         /* （連携用）主契約特約保険金額メッセージ区分３ */
     zrnsyukyktkykhknkknmsgkbn3 ,         /* （連携用）主契約特約保険期間メッセージ区分３ */
     zrnsyukyktkykstuukatype3 ,         /* （連携用）主契約特約保険金額通貨タイプ３ */
     zrnsyukyktkykhknkngk3 ,         /* （連携用）主契約特約保険金額３ */
     zrnsyutkdai1hknkknymdto3 ,         /* （連携用）主契約特約第１保険期間年月日（至）３ */
     zrnsyutkdai2hknkknymdto3 ,         /* （連携用）主契約特約第２保険期間年月日（至）３ */
     zrnyobiv22x3 ,         /* （連携用）予備項目Ｖ２２＿３ */
     zrnsyukyktkykrenban4 ,         /* （連携用）主契約特約連番４ */
     zrnsyukyktkykmsgkbn4 ,         /* （連携用）主契約特約メッセージ区分４ */
     zrnsyukyktkyksmsgkbn4 ,         /* （連携用）主契約特約保険金額メッセージ区分４ */
     zrnsyukyktkykhknkknmsgkbn4 ,         /* （連携用）主契約特約保険期間メッセージ区分４ */
     zrnsyukyktkykstuukatype4 ,         /* （連携用）主契約特約保険金額通貨タイプ４ */
     zrnsyukyktkykhknkngk4 ,         /* （連携用）主契約特約保険金額４ */
     zrnsyutkdai1hknkknymdto4 ,         /* （連携用）主契約特約第１保険期間年月日（至）４ */
     zrnsyutkdai2hknkknymdto4 ,         /* （連携用）主契約特約第２保険期間年月日（至）４ */
     zrnyobiv22x4 ,         /* （連携用）予備項目Ｖ２２＿４ */
     zrnsyukyktkykrenban5 ,         /* （連携用）主契約特約連番５ */
     zrnsyukyktkykmsgkbn5 ,         /* （連携用）主契約特約メッセージ区分５ */
     zrnsyukyktkyksmsgkbn5 ,         /* （連携用）主契約特約保険金額メッセージ区分５ */
     zrnsyukyktkykhknkknmsgkbn5 ,         /* （連携用）主契約特約保険期間メッセージ区分５ */
     zrnsyukyktkykstuukatype5 ,         /* （連携用）主契約特約保険金額通貨タイプ５ */
     zrnsyukyktkykhknkngk5 ,         /* （連携用）主契約特約保険金額５ */
     zrnsyutkdai1hknkknymdto5 ,         /* （連携用）主契約特約第１保険期間年月日（至）５ */
     zrnsyutkdai2hknkknymdto5 ,         /* （連携用）主契約特約第２保険期間年月日（至）５ */
     zrnyobiv22x5 ,         /* （連携用）予備項目Ｖ２２＿５ */
     zrnsyukyktkykrenban6 ,         /* （連携用）主契約特約連番６ */
     zrnsyukyktkykmsgkbn6 ,         /* （連携用）主契約特約メッセージ区分６ */
     zrnsyukyktkyksmsgkbn6 ,         /* （連携用）主契約特約保険金額メッセージ区分６ */
     zrnsyukyktkykhknkknmsgkbn6 ,         /* （連携用）主契約特約保険期間メッセージ区分６ */
     zrnsyukyktkykstuukatype6 ,         /* （連携用）主契約特約保険金額通貨タイプ６ */
     zrnsyukyktkykhknkngk6 ,         /* （連携用）主契約特約保険金額６ */
     zrnsyutkdai1hknkknymdto6 ,         /* （連携用）主契約特約第１保険期間年月日（至）６ */
     zrnsyutkdai2hknkknymdto6 ,         /* （連携用）主契約特約第２保険期間年月日（至）６ */
     zrnyobiv22x6 ,         /* （連携用）予備項目Ｖ２２＿６ */
     zrnsyukyktkykrenban7 ,         /* （連携用）主契約特約連番７ */
     zrnsyukyktkykmsgkbn7 ,         /* （連携用）主契約特約メッセージ区分７ */
     zrnsyukyktkyksmsgkbn7 ,         /* （連携用）主契約特約保険金額メッセージ区分７ */
     zrnsyukyktkykhknkknmsgkbn7 ,         /* （連携用）主契約特約保険期間メッセージ区分７ */
     zrnsyukyktkykstuukatype7 ,         /* （連携用）主契約特約保険金額通貨タイプ７ */
     zrnsyukyktkykhknkngk7 ,         /* （連携用）主契約特約保険金額７ */
     zrnsyutkdai1hknkknymdto7 ,         /* （連携用）主契約特約第１保険期間年月日（至）７ */
     zrnsyutkdai2hknkknymdto7 ,         /* （連携用）主契約特約第２保険期間年月日（至）７ */
     zrnyobiv22x7 ,         /* （連携用）予備項目Ｖ２２＿７ */
     zrnsyukyktkykrenban8 ,         /* （連携用）主契約特約連番８ */
     zrnsyukyktkykmsgkbn8 ,         /* （連携用）主契約特約メッセージ区分８ */
     zrnsyukyktkyksmsgkbn8 ,         /* （連携用）主契約特約保険金額メッセージ区分８ */
     zrnsyukyktkykhknkknmsgkbn8 ,         /* （連携用）主契約特約保険期間メッセージ区分８ */
     zrnsyukyktkykstuukatype8 ,         /* （連携用）主契約特約保険金額通貨タイプ８ */
     zrnsyukyktkykhknkngk8 ,         /* （連携用）主契約特約保険金額８ */
     zrnsyutkdai1hknkknymdto8 ,         /* （連携用）主契約特約第１保険期間年月日（至）８ */
     zrnsyutkdai2hknkknymdto8 ,         /* （連携用）主契約特約第２保険期間年月日（至）８ */
     zrnyobiv22x8 ,         /* （連携用）予備項目Ｖ２２＿８ */
     zrnsyukyktkykrenban9 ,         /* （連携用）主契約特約連番９ */
     zrnsyukyktkykmsgkbn9 ,         /* （連携用）主契約特約メッセージ区分９ */
     zrnsyukyktkyksmsgkbn9 ,         /* （連携用）主契約特約保険金額メッセージ区分９ */
     zrnsyukyktkykhknkknmsgkbn9 ,         /* （連携用）主契約特約保険期間メッセージ区分９ */
     zrnsyukyktkykstuukatype9 ,         /* （連携用）主契約特約保険金額通貨タイプ９ */
     zrnsyukyktkykhknkngk9 ,         /* （連携用）主契約特約保険金額９ */
     zrnsyutkdai1hknkknymdto9 ,         /* （連携用）主契約特約第１保険期間年月日（至）９ */
     zrnsyutkdai2hknkknymdto9 ,         /* （連携用）主契約特約第２保険期間年月日（至）９ */
     zrnyobiv22x9 ,         /* （連携用）予備項目Ｖ２２＿９ */
     zrnsyukyktkykrenban10 ,         /* （連携用）主契約特約連番１０ */
     zrnsyukyktkykmsgkbn10 ,         /* （連携用）主契約特約メッセージ区分１０ */
     zrnsyukyktkyksmsgkbn10 ,         /* （連携用）主契約特約保険金額メッセージ区分１０ */
     zrnsyukyktkykhknkknmsgkbn10 ,         /* （連携用）主契約特約保険期間メッセージ区分１０ */
     zrnsyukyktkykstuukatype10 ,         /* （連携用）主契約特約保険金額通貨タイプ１０ */
     zrnsyukyktkykhknkngk10 ,         /* （連携用）主契約特約保険金額１０ */
     zrnsyutkdai1hknkknymdto10 ,         /* （連携用）主契約特約第１保険期間年月日（至）１０ */
     zrnsyutkdai2hknkknymdto10 ,         /* （連携用）主契約特約第２保険期間年月日（至）１０ */
     zrnyobiv22x10 ,         /* （連携用）予備項目Ｖ２２＿１０ */
     zrnyobiv50 ,         /* （連携用）予備項目Ｖ５０ */
     zrnkykniyustmsgcd1 ,         /* （連携用）契約内容欄下メッセージコード１ */
     zrnkykniyustmsgcd2 ,         /* （連携用）契約内容欄下メッセージコード２ */
     zrnkykniyustmsgcd3 ,         /* （連携用）契約内容欄下メッセージコード３ */
     zrnkykniyustmsgcd4 ,         /* （連携用）契約内容欄下メッセージコード４ */
     zrnkykniyustmsgcd5 ,         /* （連携用）契約内容欄下メッセージコード５ */
     zrnkykniyustmsgcd6 ,         /* （連携用）契約内容欄下メッセージコード６ */
     zrnkykniyustmsgcd7 ,         /* （連携用）契約内容欄下メッセージコード７ */
     zrnkykniyustmsgcd8 ,         /* （連携用）契約内容欄下メッセージコード８ */
     zrnkykniyustmsgcd9 ,         /* （連携用）契約内容欄下メッセージコード９ */
     zrnkykniyustmsgcd10 ,         /* （連携用）契約内容欄下メッセージコード１０ */
     zrnkykniyustmsgcd11 ,         /* （連携用）契約内容欄下メッセージコード１１ */
     zrnkykniyustmsgcd12 ,         /* （連携用）契約内容欄下メッセージコード１２ */
     zrnkykniyustmsgcd13 ,         /* （連携用）契約内容欄下メッセージコード１３ */
     zrnkykniyustmsgcd14 ,         /* （連携用）契約内容欄下メッセージコード１４ */
     zrnkykniyustmsgcd15 ,         /* （連携用）契約内容欄下メッセージコード１５ */
     zrnkykniyustitjbrptuuktype ,         /* （連携用）契約内容欄下一時払保険料通貨タイプ */
     zrnkykniyustitjbrp ,         /* （連携用）契約内容欄下一時払保険料 */
     zrnyobiv49 ,         /* （連携用）予備項目Ｖ４９ */
     zrnsonotanyranmsgcd1 ,         /* （連携用）その他内容欄メッセージコード１ */
     zrnsonotanyranmsgcd2 ,         /* （連携用）その他内容欄メッセージコード２ */
     zrnsonotanyranmsgcd3 ,         /* （連携用）その他内容欄メッセージコード３ */
     zrnsonotanyranmsgcd4 ,         /* （連携用）その他内容欄メッセージコード４ */
     zrnsonotanyranmsgcd5 ,         /* （連携用）その他内容欄メッセージコード５ */
     zrnsonotanyranmsgcd6 ,         /* （連携用）その他内容欄メッセージコード６ */
     zrnsonotanyranmsgcd7 ,         /* （連携用）その他内容欄メッセージコード７ */
     zrnsonotanyranmsgcd8 ,         /* （連携用）その他内容欄メッセージコード８ */
     zrnsonotanyranmsgcd9 ,         /* （連携用）その他内容欄メッセージコード９ */
     zrnsonotanyranmsgcd10 ,         /* （連携用）その他内容欄メッセージコード１０ */
     zrnsonotanyranmsgcd11 ,         /* （連携用）その他内容欄メッセージコード１１ */
     zrnsonotanyranmsgcd12 ,         /* （連携用）その他内容欄メッセージコード１２ */
     zrnsonotanyranmsgcd13 ,         /* （連携用）その他内容欄メッセージコード１３ */
     zrnsonotanyranmsgcd14 ,         /* （連携用）その他内容欄メッセージコード１４ */
     zrnsonotanyranmsgcd15 ,         /* （連携用）その他内容欄メッセージコード１５ */
     zrnsonotanyranmsgcd16 ,         /* （連携用）その他内容欄メッセージコード１６ */
     zrnsonotanyranmsgcd17 ,         /* （連携用）その他内容欄メッセージコード１７ */
     zrnsonotanyranmsgcd18 ,         /* （連携用）その他内容欄メッセージコード１８ */
     zrnsonotanyranmsgcd19 ,         /* （連携用）その他内容欄メッセージコード１９ */
     zrnsonotanyranmsgcd20 ,         /* （連携用）その他内容欄メッセージコード２０ */
     zrnsonotanyransiteituuka ,         /* （連携用）その他内容欄指定通貨 */
     zrnsonotanyrannykntuktype ,         /* （連携用）その他内容欄入金通貨タイプ */
     zrnsonotanyrannykntuukap ,         /* （連携用）その他内容欄入金通貨保険料 */
     zrnsonotanyrannykntuukasyu ,         /* （連携用）その他内容欄入金通貨種類 */
     zrnsonotanyranenkhrikmrate ,         /* （連携用）その他内容欄円貨払込特約レート */
     zrnsonotanyranstigikwsrate ,         /* （連携用）その他内容欄指定外通貨払込特約レート */
     zrnsonotanykjnkngktuktype ,         /* （連携用）その他内容欄基準金額通貨タイプ */
     zrnsonotanykjnkngk ,         /* （連携用）その他内容欄基準金額 */
     zrnsonotanykjnkngkrate ,         /* （連携用）その他内容欄基準金額換算レート */
     zrnsonotanykjnkngktuuka ,         /* （連携用）その他内容欄基準金額通貨 */
     zrnsonotanyranpentuktype ,         /* （連携用）その他内容欄保険料円換算通貨タイプ */
     zrnsonotanyranpenknsngk ,         /* （連携用）その他内容欄保険料円換算額 */
     zrnpmkhtoutatuwariai ,         /* （連携用）その他内容欄目標到達割合 */
     zrnsonotanyrannkshrstartymd ,         /* （連携用）その他内容欄年金支払開始日 */
     zrnsonotanyrannkkkn ,         /* （連携用）その他内容欄年金期間 */
     zrnsonotanyyensysnhkhnkymd ,         /* （連携用）その他内容欄円建終身保険変更日 */
     zrnsonotanytmttkngktuktype ,         /* （連携用）その他内容欄積立金額通貨タイプ */
     zrnsonotanyteiritutmttkngk ,         /* （連携用）その他内容欄定率積立金額 */
     zrnsonotanyransisuutmttkngk ,         /* （連携用）その他内容欄指数積立金額 */
     zrnsonotanyransisuunm ,         /* （連携用）その他内容欄指数名 */
     zrnsonotanyrangaimsgcd ,         /* （連携用）その他内容欄外メッセージコード */
     zrnyobiv19 ,         /* （連携用）予備項目Ｖ１９ */
     zrnhosyounymsgcd ,         /* （連携用）保障内容メッセージコード */
     zrnyobiv15 ,         /* （連携用）予備項目Ｖ１５ */
     zrnhosyounyhihknsyanmkanji ,         /* （連携用）保障内容被保険者名（漢字） */
     zrnyobiv24 ,         /* （連携用）予備項目Ｖ２４ */
     zrnsiboumidasimsgcd ,         /* （連携用）死亡保障見出しメッセージコード */
     zrnsiboumidasimsgcd2 ,         /* （連携用）死亡保障見出しメッセージコード２ */
     zrnsiboudai1hknkknmsgcd1 ,         /* （連携用）死亡保障第１保険期間メッセージコード１ */
     zrnsiboudai1hknkknmsgcd2 ,         /* （連携用）死亡保障第１保険期間メッセージコード２ */
     zrnsiboudai1hknkknigimsgcd ,         /* （連携用）死亡保障第１保険期間不慮の事故以外Ｓ表メッセージコード */
     zrnsiboudai1hknkknigimsgcd2 ,         /* （連携用）死亡保障第１保険期間不慮の事故以外Ｓ表メッセージコード２ */
     zrnsiboudai1hknkknhrsmsgcd ,         /* （連携用）死亡保障第１保険期間不慮の事故Ｓ表メッセージコード */
     zrnsiboudai1hknkknhrsmsgcd2 ,         /* （連携用）死亡保障第１保険期間不慮の事故Ｓ表メッセージコード２ */
     zrnsiboudai1hknkknsmrmsgcd ,         /* （連携用）死亡保障第１保険期間Ｓ表丸印メッセージコード */
     zrnsiboudai2hknkknmsgcd1 ,         /* （連携用）死亡保障第２保険期間メッセージコード１ */
     zrnsiboudai2hknkknmsgcd2 ,         /* （連携用）死亡保障第２保険期間メッセージコード２ */
     zrnsiboudai2hknkknsmsgcd ,         /* （連携用）死亡保障第２保険期間Ｓ表メッセージコード */
     zrnsiboudai2hknkknsmsgcd2 ,         /* （連携用）死亡保障第２保険期間Ｓ表メッセージコード２ */
     zrnsiboudai3hknkknmsgcd1 ,         /* （連携用）死亡保障第３保険期間メッセージコード１ */
     zrnsiboudai3hknkknmsgcd2 ,         /* （連携用）死亡保障第３保険期間メッセージコード２ */
     zrnyobiv15x2 ,         /* （連携用）予備項目Ｖ１５＿２ */
     zrnsiboudai1hknkknymdto ,         /* （連携用）死亡保障第１保険期間年月日（至） */
     zrnsibouitjbrpyentuuktype ,         /* （連携用）死亡保障一時払保険料相当円換算額通貨タイプ */
     zrnsibouitjbrpyentuukgk ,         /* （連携用）死亡保障一時払保険料相当円換算額 */
     zrnsiboudai1kjnkngktuktype ,         /* （連携用）死亡保障第１基準金額通貨タイプ */
     zrnsiboudai1kjnkngk ,         /* （連携用）死亡保障第１基準金額 */
     zrnsiboudai2hknkknymdto ,         /* （連携用）死亡保障第２保険期間年月日（至） */
     zrnsiboudai2kjnkngktuktype ,         /* （連携用）死亡保障第２基準金額通貨タイプ */
     zrnsiboudai2kjnkngk ,         /* （連携用）死亡保障第２基準金額 */
     zrnsiboudai3kjnkngktuktype ,         /* （連携用）死亡保障第３基準金額通貨タイプ */
     zrnsiboudai3kjnkngk ,         /* （連携用）死亡保障第３基準金額 */
     zrnyobiv23 ,         /* （連携用）予備項目Ｖ２３ */
     zrndai1skwsrateyendaka ,         /* （連携用）第１死亡保険金額為替レート（円高） */
     zrndai1skwsrateyenkijyun ,         /* （連携用）第１死亡保険金額為替レート（中央値） */
     zrndai1skwsrateyenyasu ,         /* （連携用）第１死亡保険金額為替レート（円安） */
     zrndai1sibousnenoutouymd1 ,         /* （連携用）第１死亡保険金額年単位応当年月日０１ */
     zrndai1stuuktype01 ,         /* （連携用）第１死亡保険金額通貨タイプ０１ */
     zrndai1s01 ,         /* （連携用）第１死亡保険金額０１ */
     zrndai1syenyendakaumu01 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０１ */
     zrndai1syenyenkijyunumu01 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０１ */
     zrndai1syenyenyasuumu01 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０１ */
     zrndai1syentuuktype01 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０１ */
     zrndai1syenyendaka01 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０１ */
     zrndai1syenyenkijyun01 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０１ */
     zrndai1syenyenyasu01 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０１ */
     zrndai1sibousnenoutouymd2 ,         /* （連携用）第１死亡保険金額年単位応当年月日０２ */
     zrndai1stuuktype02 ,         /* （連携用）第１死亡保険金額通貨タイプ０２ */
     zrndai1s02 ,         /* （連携用）第１死亡保険金額０２ */
     zrndai1syenyendakaumu02 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０２ */
     zrndai1syenyenkijyunumu02 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０２ */
     zrndai1syenyenyasuumu02 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０２ */
     zrndai1syentuuktype02 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０２ */
     zrndai1syenyendaka02 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０２ */
     zrndai1syenyenkijyun02 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０２ */
     zrndai1syenyenyasu02 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０２ */
     zrndai1sibousnenoutouymd3 ,         /* （連携用）第１死亡保険金額年単位応当年月日０３ */
     zrndai1stuuktype03 ,         /* （連携用）第１死亡保険金額通貨タイプ０３ */
     zrndai1s03 ,         /* （連携用）第１死亡保険金額０３ */
     zrndai1syenyendakaumu03 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０３ */
     zrndai1syenyenkijyunumu03 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０３ */
     zrndai1syenyenyasuumu03 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０３ */
     zrndai1syentuuktype03 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０３ */
     zrndai1syenyendaka03 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０３ */
     zrndai1syenyenkijyun03 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０３ */
     zrndai1syenyenyasu03 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０３ */
     zrndai1sibousnenoutouymd4 ,         /* （連携用）第１死亡保険金額年単位応当年月日０４ */
     zrndai1stuuktype04 ,         /* （連携用）第１死亡保険金額通貨タイプ０４ */
     zrndai1s04 ,         /* （連携用）第１死亡保険金額０４ */
     zrndai1syenyendakaumu04 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０４ */
     zrndai1syenyenkijyunumu04 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０４ */
     zrndai1syenyenyasuumu04 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０４ */
     zrndai1syentuuktype04 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０４ */
     zrndai1syenyendaka04 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０４ */
     zrndai1syenyenkijyun04 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０４ */
     zrndai1syenyenyasu04 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０４ */
     zrndai1sibousnenoutouymd5 ,         /* （連携用）第１死亡保険金額年単位応当年月日０５ */
     zrndai1stuuktype05 ,         /* （連携用）第１死亡保険金額通貨タイプ０５ */
     zrndai1s05 ,         /* （連携用）第１死亡保険金額０５ */
     zrndai1syenyendakaumu05 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０５ */
     zrndai1syenyenkijyunumu05 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０５ */
     zrndai1syenyenyasuumu05 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０５ */
     zrndai1syentuuktype05 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０５ */
     zrndai1syenyendaka05 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０５ */
     zrndai1syenyenkijyun05 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０５ */
     zrndai1syenyenyasu05 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０５ */
     zrndai1sibousnenoutouymd6 ,         /* （連携用）第１死亡保険金額年単位応当年月日０６ */
     zrndai1stuuktype06 ,         /* （連携用）第１死亡保険金額通貨タイプ０６ */
     zrndai1s06 ,         /* （連携用）第１死亡保険金額０６ */
     zrndai1syenyendakaumu06 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０６ */
     zrndai1syenyenkijyunumu06 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０６ */
     zrndai1syenyenyasuumu06 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０６ */
     zrndai1syentuuktype06 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０６ */
     zrndai1syenyendaka06 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０６ */
     zrndai1syenyenkijyun06 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０６ */
     zrndai1syenyenyasu06 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０６ */
     zrndai1sibousnenoutouymd7 ,         /* （連携用）第１死亡保険金額年単位応当年月日０７ */
     zrndai1stuuktype07 ,         /* （連携用）第１死亡保険金額通貨タイプ０７ */
     zrndai1s07 ,         /* （連携用）第１死亡保険金額０７ */
     zrndai1syenyendakaumu07 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０７ */
     zrndai1syenyenkijyunumu07 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０７ */
     zrndai1syenyenyasuumu07 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０７ */
     zrndai1syentuuktype07 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０７ */
     zrndai1syenyendaka07 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０７ */
     zrndai1syenyenkijyun07 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０７ */
     zrndai1syenyenyasu07 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０７ */
     zrndai1sibousnenoutouymd8 ,         /* （連携用）第１死亡保険金額年単位応当年月日０８ */
     zrndai1stuuktype08 ,         /* （連携用）第１死亡保険金額通貨タイプ０８ */
     zrndai1s08 ,         /* （連携用）第１死亡保険金額０８ */
     zrndai1syenyendakaumu08 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０８ */
     zrndai1syenyenkijyunumu08 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０８ */
     zrndai1syenyenyasuumu08 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０８ */
     zrndai1syentuuktype08 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０８ */
     zrndai1syenyendaka08 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０８ */
     zrndai1syenyenkijyun08 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０８ */
     zrndai1syenyenyasu08 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０８ */
     zrndai1sibousnenoutouymd9 ,         /* （連携用）第１死亡保険金額年単位応当年月日０９ */
     zrndai1stuuktype09 ,         /* （連携用）第１死亡保険金額通貨タイプ０９ */
     zrndai1s09 ,         /* （連携用）第１死亡保険金額０９ */
     zrndai1syenyendakaumu09 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無０９ */
     zrndai1syenyenkijyunumu09 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無０９ */
     zrndai1syenyenyasuumu09 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無０９ */
     zrndai1syentuuktype09 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ０９ */
     zrndai1syenyendaka09 ,         /* （連携用）第１死亡保険金額（円貨）（円高）０９ */
     zrndai1syenyenkijyun09 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）０９ */
     zrndai1syenyenyasu09 ,         /* （連携用）第１死亡保険金額（円貨）（円安）０９ */
     zrndai1sibousnenoutouymd10 ,         /* （連携用）第１死亡保険金額年単位応当年月日１０ */
     zrndai1stuuktype10 ,         /* （連携用）第１死亡保険金額通貨タイプ１０ */
     zrndai1s10 ,         /* （連携用）第１死亡保険金額１０ */
     zrndai1syenyendakaumu10 ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無１０ */
     zrndai1syenyenkijyunumu10 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無１０ */
     zrndai1syenyenyasuumu10 ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無１０ */
     zrndai1syentuuktype10 ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ１０ */
     zrndai1syenyendaka10 ,         /* （連携用）第１死亡保険金額（円貨）（円高）１０ */
     zrndai1syenyenkijyun10 ,         /* （連携用）第１死亡保険金額（円貨）（中央値）１０ */
     zrndai1syenyenyasu10 ,         /* （連携用）第１死亡保険金額（円貨）（円安）１０ */
     zrndai1stuuktypehuryo ,         /* （連携用）第１死亡保険金額通貨タイプ（不慮） */
     zrndai1shuryo ,         /* （連携用）第１死亡保険金額（不慮） */
     zrndai1syenyendakaumuhuryo ,         /* （連携用）第１死亡保険金額（円貨）（円高）丸印有無（不慮） */
     zrndai1syenyenkjnumuhuryo ,         /* （連携用）第１死亡保険金額（円貨）（中央値）丸印有無（不慮） */
     zrndai1syenyenyasuumuhuryo ,         /* （連携用）第１死亡保険金額（円貨）（円安）丸印有無（不慮） */
     zrndai1syentuuktypehuryo ,         /* （連携用）第１死亡保険金額（円貨）通貨タイプ（不慮） */
     zrndai1syenyendakahuryo ,         /* （連携用）第１死亡保険金額（円貨）（円高）（不慮） */
     zrndai1syenyenkijyunhuryo ,         /* （連携用）第１死亡保険金額（円貨）（中央値）（不慮） */
     zrndai1syenyenyasuhuryo ,         /* （連携用）第１死亡保険金額（円貨）（円安）（不慮） */
     zrndai2stuuktype ,         /* （連携用）第２死亡保険金額通貨タイプ */
     zrndai2s ,         /* （連携用）第２死亡保険金額 */
     zrndai2syentuuktype ,         /* （連携用）第２死亡保険金額（円貨）通貨タイプ */
     zrndai2syenyendaka ,         /* （連携用）第２死亡保険金額（円貨）（円高） */
     zrndai2syenyenkijyun ,         /* （連携用）第２死亡保険金額（円貨）（中央値） */
     zrndai2syenyenyasu ,         /* （連携用）第２死亡保険金額（円貨）（円安） */
     zrndai3stuuktype ,         /* （連携用）第３死亡保険金額通貨タイプ */
     zrndai3s ,         /* （連携用）第３死亡保険金額 */
     zrndai3syentuuktype ,         /* （連携用）第３死亡保険金額（円貨）通貨タイプ */
     zrndai3syenyendaka ,         /* （連携用）第３死亡保険金額（円貨）（円高） */
     zrndai3syenyenkijyun ,         /* （連携用）第３死亡保険金額（円貨）（中央値） */
     zrndai3syenyenyasu ,         /* （連携用）第３死亡保険金額（円貨）（円安） */
     zrnsibouinjiptnkbn ,         /* （連携用）死亡保障印字パターン */
     zrnyobiv25 ,         /* （連携用）予備項目Ｖ２５ */
     zrnmkhyouyensysnikoumsgcd ,         /* （連携用）目標到達時円建終身保険移行特約メッセージコード */
     zrnmkhyouyensysnikoumsgcd2 ,         /* （連携用）目標到達時円建終身保険移行特約メッセージコード２ */
     zrnmkhyouyensysnikoumsgcd3 ,         /* （連携用）目標到達時円建終身保険移行特約メッセージコード３ */
     zrnmkhyouyensysnikougktype ,         /* （連携用）目標到達時円建終身保険移行特約目標額通貨タイプ */
     zrnmkhyouyensysnikougk ,         /* （連携用）目標到達時円建終身保険移行特約目標額 */
     zrnmkhyouyensysnikouwra ,         /* （連携用）目標到達時円建終身保険移行特約目標割合 */
     zrnyobiv12 ,         /* （連携用）予備項目Ｖ１２ */
     zrnkaigomaehrtkykmsgcd1 ,         /* （連携用）介護前払特約メッセージコード１ */
     zrnkaigomaehrtkykmsgcd2 ,         /* （連携用）介護前払特約メッセージコード２ */
     zrnkaigomaehrtkykmsgcdst1 ,         /* （連携用）介護前払特約メッセージコード表下１ */
     zrnkaigomaehrtkykmsgcdst2 ,         /* （連携用）介護前払特約メッセージコード表下２ */
     zrnkgmaehrtkhknkkn1mnryymd ,         /* （連携用）介護前払特約第１保険期間満了日 */
     zrnkaigomaehrtkykitrnumu ,         /* （連携用）介護前払特約受取額一覧有無 */
     zrnkaigomaehrtkykkyktuuka ,         /* （連携用）介護前払特約契約通貨 */
     zrnkaigomaehrtkykstdmsgcd ,         /* （連携用）介護前払特約指定代理メッセージコード */
     zrnyobiv13 ,         /* （連携用）予備項目Ｖ１３ */
     zrnkaigomaehrjrugktype ,         /* （連携用）介護前払受領額通貨タイプ */
     zrnkaigomaehrsikuhhknnen01 ,         /* （連携用）介護前払請求日時点被保険者年齢０１ */
     zrnkaigomaehrstikkn01 ,         /* （連携用）介護前払所定期間０１ */
     zrnkaigomaehrjrugk01 ,         /* （連携用）介護前払受領額０１ */
     zrnkaigomaehrsikuhhknnen02 ,         /* （連携用）介護前払請求日時点被保険者年齢０２ */
     zrnkaigomaehrstikkn02 ,         /* （連携用）介護前払所定期間０２ */
     zrnkaigomaehrjrugk02 ,         /* （連携用）介護前払受領額０２ */
     zrnkaigomaehrsikuhhknnen03 ,         /* （連携用）介護前払請求日時点被保険者年齢０３ */
     zrnkaigomaehrstikkn03 ,         /* （連携用）介護前払所定期間０３ */
     zrnkaigomaehrjrugk03 ,         /* （連携用）介護前払受領額０３ */
     zrnkaigomaehrsikuhhknnen04 ,         /* （連携用）介護前払請求日時点被保険者年齢０４ */
     zrnkaigomaehrstikkn04 ,         /* （連携用）介護前払所定期間０４ */
     zrnkaigomaehrjrugk04 ,         /* （連携用）介護前払受領額０４ */
     zrnkaigomaehrsikuhhknnen05 ,         /* （連携用）介護前払請求日時点被保険者年齢０５ */
     zrnkaigomaehrstikkn05 ,         /* （連携用）介護前払所定期間０５ */
     zrnkaigomaehrjrugk05 ,         /* （連携用）介護前払受領額０５ */
     zrnkaigomaehrsikuhhknnen06 ,         /* （連携用）介護前払請求日時点被保険者年齢０６ */
     zrnkaigomaehrstikkn06 ,         /* （連携用）介護前払所定期間０６ */
     zrnkaigomaehrjrugk06 ,         /* （連携用）介護前払受領額０６ */
     zrnkaigomaehrsikuhhknnen07 ,         /* （連携用）介護前払請求日時点被保険者年齢０７ */
     zrnkaigomaehrstikkn07 ,         /* （連携用）介護前払所定期間０７ */
     zrnkaigomaehrjrugk07 ,         /* （連携用）介護前払受領額０７ */
     zrnkaigomaehrsikuhhknnen08 ,         /* （連携用）介護前払請求日時点被保険者年齢０８ */
     zrnkaigomaehrstikkn08 ,         /* （連携用）介護前払所定期間０８ */
     zrnkaigomaehrjrugk08 ,         /* （連携用）介護前払受領額０８ */
     zrnkaigomaehrsikuhhknnen09 ,         /* （連携用）介護前払請求日時点被保険者年齢０９ */
     zrnkaigomaehrstikkn09 ,         /* （連携用）介護前払所定期間０９ */
     zrnkaigomaehrjrugk09 ,         /* （連携用）介護前払受領額０９ */
     zrnkaigomaehrsikuhhknnen10 ,         /* （連携用）介護前払請求日時点被保険者年齢１０ */
     zrnkaigomaehrstikkn10 ,         /* （連携用）介護前払所定期間１０ */
     zrnkaigomaehrjrugk10 ,         /* （連携用）介護前払受領額１０ */
     zrnnkmsgcd1 ,         /* （連携用）年金メッセージコード１ */
     zrnnkmsgcd2 ,         /* （連携用）年金メッセージコード２ */
     zrnnkmsgcd3 ,         /* （連携用）年金メッセージコード３ */
     zrnnkmsgcd4 ,         /* （連携用）年金メッセージコード４ */
     zrnnkmsgcd5 ,         /* （連携用）年金メッセージコード５ */
     zrnnkmsgcd6 ,         /* （連携用）年金メッセージコード６ */
     zrnnkmsgcd7 ,         /* （連携用）年金メッセージコード７ */
     zrnnkmsgcd8 ,         /* （連携用）年金メッセージコード８ */
     zrnnkmsgcd9 ,         /* （連携用）年金メッセージコード９ */
     zrnnkmsgcd10 ,         /* （連携用）年金メッセージコード１０ */
     zrnsiboukyuuhukinmsgcd1 ,         /* （連携用）死亡給付金メッセージコード１ */
     zrnsiboukyuuhukinmsgcd2 ,         /* （連携用）死亡給付金メッセージコード２ */
     zrnsiboukyuuhukinmsgcd3 ,         /* （連携用）死亡給付金メッセージコード３ */
     zrnsiboukyuuhukinmsgcd4 ,         /* （連携用）死亡給付金メッセージコード４ */
     zrnsiboukyuuhukinmsgcd5 ,         /* （連携用）死亡給付金メッセージコード５ */
     zrnsiboukyuuhukinmsgcd6 ,         /* （連携用）死亡給付金メッセージコード６ */
     zrnsiboukyuuhukinmsgcd7 ,         /* （連携用）死亡給付金メッセージコード７ */
     zrnsiboukyuuhukinmsgcd8 ,         /* （連携用）死亡給付金メッセージコード８ */
     zrnsiboukyuuhukinmsgcd9 ,         /* （連携用）死亡給付金メッセージコード９ */
     zrnsiboukyuuhukinmsgcd10 ,         /* （連携用）死亡給付金メッセージコード１０ */
     zrnnkshrstartzenymd ,         /* （連携用）年金支払開始日前日 */
     zrnmkhyouyennkhknhentktype ,         /* （連携用）目標到達時円建年金保険変更特約目標額通貨タイプ */
     zrnmkhyouyennkhknhentkmkhgk ,         /* （連携用）目標到達時円建年金保険変更特約目標額 */
     zrnmkhyennkhknhentkmkhwari ,         /* （連携用）目標到達時円建年金保険変更特約目標割合 */
     zrnhaibunwarimsgcd1 ,         /* （連携用）配分割合メッセージコード１ */
     zrnhaibunwarimsgcd2 ,         /* （連携用）配分割合メッセージコード２ */
     zrnhaibunwarimsgcd3 ,         /* （連携用）配分割合メッセージコード３ */
     zrnteiritutmtthbnwr ,         /* （連携用）定率積立部分配分割合 */
     zrnsisuutmtthbnwr ,         /* （連携用）指数積立部分配分割合 */
     zrnsisuuannaimsg1 ,         /* （連携用）指数案内メッセージコード１ */
     zrnsisuuannaimsg2 ,         /* （連携用）指数案内メッセージコード２ */
     zrnsisuuannaimsg3 ,         /* （連携用）指数案内メッセージコード３ */
     zrnhutanhiyustmmsgcdue01 ,         /* （連携用）ご負担費用説明欄メッセージコード表上１ */
     zrnhutanhiyustmmsgcdue02 ,         /* （連携用）ご負担費用説明欄メッセージコード表上２ */
     zrnhutanhiyustmmsgcdue03 ,         /* （連携用）ご負担費用説明欄メッセージコード表上３ */
     zrnhutanhiyustmmsgcdue04 ,         /* （連携用）ご負担費用説明欄メッセージコード表上４ */
     zrnhutanhiyustmknsnhyuptn ,         /* （連携用）ご負担費用説明欄換算費用パターン */
     zrnhutanhiyustmmsgcdst01 ,         /* （連携用）ご負担費用説明欄メッセージコード表下１ */
     zrnhutanhiyustmmsgcdst02 ,         /* （連携用）ご負担費用説明欄メッセージコード表下２ */
     zrnhutanhiyustmmsgcdst03 ,         /* （連携用）ご負担費用説明欄メッセージコード表下３ */
     zrnhutanhiyustmytijihiritu ,         /* （連携用）ご負担費用説明欄予定維持費率 */
     zrnhutanhiyustmkyakkjrtmin ,         /* （連携用）ご負担費用説明欄解約控除率最小 */
     zrnhutanhiyustmkyakkjrtmax ,         /* （連携用）ご負担費用説明欄解約控除率最大 */
     zrnyobiv7x2 ,         /* （連携用）予備項目Ｖ７＿２ */
     zrnstdstmmsgcd ,         /* （連携用）指定代理請求特約説明欄メッセージコード */
     zrnyobiv15x4 ,         /* （連携用）予備項目Ｖ１５＿４ */
     zrnyobiv52 ,         /* （連携用）予備項目Ｖ５２ */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrnyobiv4           /* （連携用）予備項目Ｖ４ */
FROM ZT_SaihakkouHokensyoukenRn_Z;