CREATE VIEW ZT_KaiykHrSoutougakuTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztykeisankijyunym ,         /* （中継用）計算基準年月 */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztysyutkkbn ,         /* （中継用）主契約特約区分 */
     ztysuurisyuruicd ,         /* （中継用）数理種類コード */
     ztykbnkeiriyousegmentkbn ,         /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn ,         /* （中継用）区分経理用利源分析区分 */
     ztyharaikatakbn ,         /* （中継用）払方区分 */
     ztytenkanitijibaraikbn ,         /* （中継用）転換一時払区分 */
     ztytyuutohukahyouji ,         /* （中継用）中途付加表示 */
     ztysuuriyouyobin6 ,         /* （中継用）数理用予備項目Ｎ６ */
     ztyyobiv6x2 ,         /* （中継用）予備項目Ｖ６＿２ */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztysotodasipmenkbn ,         /* （中継用）外出Ｐ免区分 */
     ztysotodasikousinkbn ,         /* （中継用）外出更新区分 */
     ztysotodasimanagehyouji ,         /* （中継用）外出満年令表示 */
     ztysotodasiphkbnmnoshyouji ,         /* （中継用）外出Ｐ不可分見直表示 */
     ztyknkuzusnzyrttekitkarihyj ,         /* （中継用）健康増進乗率適用特約有表示 */
     ztyhokensyuruikigouyobi ,         /* （中継用）保険種類記号予備 */
     ztytokuyakugatakbn ,         /* （中継用）特約型区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyryouritukbn ,         /* （中継用）料率区分 */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztytkbthsyumnryuhyouji ,         /* （中継用）特別保障満了表示 */
     ztynknshry ,         /* （中継用）年金支払期間 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztykykjyoutai ,         /* （中継用）契約状態 */
     ztyharaizumientyoujiage ,         /* （中継用）払済延長時年令 */
     ztyentyoukikan ,         /* （中継用）延長期間 */
     ztysiteimpbairitu ,         /* （中継用）指定月Ｐ倍率 */
     ztypwarimasisiteim1 ,         /* （中継用）Ｐ割増指定月１ */
     ztypwarimasisiteim2 ,         /* （中継用）Ｐ割増指定月２ */
     ztysaisyuusiteiym ,         /* （中継用）最終指定年月 */
     ztyseizonkyuuhukinshrmd ,         /* （中継用）生存給付支払月日 */
     ztykeikanensuu ,         /* （中継用）経過年数 */
     ztykeikatukisuu ,         /* （中継用）経過月数 */
     ztyjikaipjyuutouym ,         /* （中継用）次回Ｐ充当年月 */
     ztytnknhktgkujyarhyouji ,         /* （中継用）転換引継控除有表示 */
     ztytokuyakukbn ,         /* （中継用）特約区分 */
     ztytokuyakuno ,         /* （中継用）特約番号 */
     ztydi2hknkknikoujihisyaage ,         /* （中継用）第２保険期間移行時被者年令 */
     ztyrecordno ,         /* （中継用）レコード番号 */
     ztymfkuriagekurisagekbn ,         /* （中継用）ＭＦ繰上げ繰下げ区分 */
     ztymfannaihuyouriyuukbn ,         /* （中継用）ＭＦ案内不要理由区分 */
     ztyhrizmjhknsyukigousdkbn ,         /* （中継用）払済時保険種類記号世代区分 */
     ztyhokenhoutekiyouhyouji ,         /* （中継用）保険法適用表示 */
     ztytokubetuhosyoukikan ,         /* （中継用）特別保障期間 */
     ztysintokujyouhyouji ,         /* （中継用）新特条表示 */
     ztytkjykbn ,         /* （中継用）特条区分 */
     ztyryoumasihyouten ,         /* （中継用）料増標点 */
     ztydai2tokujyoukbn ,         /* （中継用）第２特条区分 */
     ztydai2ryoumasihyouten ,         /* （中継用）第２料増標点 */
     ztyytirrthndsysnmnskaisuu ,         /* （中継用）予定利率変動終身見直回数 */
     ztykousinmanryouage ,         /* （中継用）更新満了年令 */
     ztysuuriyouyobin9 ,         /* （中継用）数理用予備項目Ｎ９ */
     ztykrsgjhknsyukigousdkbn ,         /* （中継用）繰下げ時保険種類記号世代区分 */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyzyrthntiyustatuskbn ,         /* （中継用）乗率判定用ステータス区分 */
     ztyyobiv15 ,         /* （中継用）予備項目Ｖ１５ */
     ztyerrtokuteikoumoku ,         /* （中継用）エラー特定項目 */
     ztykihons ,         /* （中継用）基本Ｓ */
     ztyhenkougokihons ,         /* （中継用）変更後基本Ｓ */
     ztyhenkougosibous ,         /* （中継用）変更後死亡Ｓ */
     ztygyousekihyoujis ,         /* （中継用）業績表示Ｓ */
     ztygoukeitenkankakaku ,         /* （中継用）合計転換価格 */
     ztywnasigoukeitenkanteikis ,         /* （中継用）Ｗなし合計転換定期Ｓ */
     ztyyobin11 ,         /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2 ,         /* （中継用）予備項目Ｎ１１＿２ */
     ztykaiyakuhr ,         /* （中継用）解約返戻金 */
     ztyryumsbbnkaiyakuhr ,         /* （中継用）料増部分解約返戻金 */
     ztyyobin11x3 ,         /* （中継用）予備項目Ｎ１１＿３ */
     ztyyobin11x4 ,         /* （中継用）予備項目Ｎ１１＿４ */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztykawaserate ,         /* （中継用）為替レート */
     ztykawaseratetekiyouymd ,         /* （中継用）為替レート適用年月日 */
     ztysaisinyoteiriritu ,         /* （中継用）最新予定利率 */
     ztysrkaiyakusjkkktyouseirrt ,         /* （中継用）数理用解約時市場価格調整用利率 */
     ztysrkyksjkkktyouseiriritu ,         /* （中継用）数理用契約時市場価格調整用利率 */
     ztymvakeisankijyunymd ,         /* （中継用）ＭＶＡ計算基準年月日 */
     ztymvatyouseikou ,         /* （中継用）ＭＶＡ調整項 */
     ztykeiyakujiyoteiriritu ,         /* （中継用）契約時予定利率 */
     ztysuuriyouyobin10 ,         /* （中継用）数理用予備項目Ｎ１０ */
     ztysuuriyouyobin10x2 ,         /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobin11x5 ,         /* （中継用）予備項目Ｎ１１＿５ */
     ztyyobin11x6 ,         /* （中継用）予備項目Ｎ１１＿６ */
     ztyyobin11x7 ,         /* （中継用）予備項目Ｎ１１＿７ */
     ztyyobin11x8 ,         /* （中継用）予備項目Ｎ１１＿８ */
     ztyyobin11x9 ,         /* （中継用）予備項目Ｎ１１＿９ */
     ztyyobiv12x2 ,         /* （中継用）予備項目Ｖ１２＿２ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_KaiykHrSoutougakuTy_Z;