CREATE VIEW ZT_Sp2RnduyuSouseiritu1Rn AS SELECT
     zrnktgysyrymd ,         /* （連携用）結合用処理日 */
     zrnktgysyono ,         /* （連携用）結合用証券番号 */
     zrnktgyfilerenno ,         /* （連携用）結合用ファイル連番 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnaatukaisyasisyacd ,         /* （連携用）Ａ扱者支社コード */
     zrnmosno ,         /* （連携用）申込番号 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnsibous ,         /* （連携用）死亡Ｓ */
     zrngyousekihyoukayouhosyous ,         /* （連携用）業績評価用保障Ｓ */
     zrngukitnknitjbrkhns ,         /* （連携用）合計転換一時払基本Ｓ */
     zrngukitnknitjbrsbus ,         /* （連携用）合計転換一時払死亡Ｓ */
     zrnkktijgukitnknitjbrkhns ,         /* （連携用）確定時合計転換一時払基本Ｓ */
     zrnkktijgukitnknitjbrsbus ,         /* （連携用）確定時合計転換一時払死亡Ｓ */
     zrnsyokaiharaikomip ,         /* （連携用）初回払込Ｐ */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnryouritukbn ,         /* （連携用）料率区分 */
     zrntksyuannaikykkbn ,         /* （連携用）特殊案内契約区分 */
     zrnsdpdkbn ,         /* （連携用）Ｓ建Ｐ建区分 */
     zrnanniskcd ,         /* （連携用）案内先コード */
     zrnduketorihouhoukbn ,         /* （連携用）Ｄ受取方法区分 */
     zrnkyksyhhknsydouituhyouji ,         /* （連携用）契約者被保険者同一表示 */
     zrnkyksyakikykarihyj ,         /* （連携用）契約者既契約有表示 */
     zrntenkankeiyakuhyouji ,         /* （連携用）転換契約表示 */
     zrnjigyoukeiyakuhyouji ,         /* （連携用）事業契約表示 */
     zrnnenkinzeiseitokuyakukbn ,         /* （連携用）年金税制特約区分 */
     zrnsyusseimaekanyuukykkbn ,         /* （連携用）出生前加入契約区分 */
     zrnkazokukeiyakuhyouji ,         /* （連携用）家族契約表示 */
     zrnjikokykhyj ,         /* （連携用）自己契約表示 */
     zrntuusyoumeisiyouhyouji ,         /* （連携用）通称名使用表示 */
     zrnsethokenkbn ,         /* （連携用）セット保険区分 */
     zrnteikeisyouhinkbn ,         /* （連携用）提携商品区分 */
     zrnsykgycd ,         /* （連携用）職業コード */
     zrntokuninbosyuuteate ,         /* （連携用）特認募集手当 */
     zrnseisekiym ,         /* （連携用）成績計上年月 */
     zrnseisekikeijyousyuuseis ,         /* （連携用）成績計上修正Ｓ */
     zrnsyuuseissakugenhyouji ,         /* （連携用）修正Ｓ削減表示 */
     zrnaatukaisisyatodouhukencd ,         /* （連携用）Ａ扱支社都道府県コード */
     zrnaatukaisosikicd ,         /* （連携用）Ａ扱者組織コード */
     zrnaatukaikojincd ,         /* （連携用）Ａ扱者個人コード */
     zrnbatukaisosikicd ,         /* （連携用）Ｂ扱者組織コード */
     zrnbatukaisyakojincd ,         /* （連携用）Ｂ扱者個人コード */
     zrnmarutokukbn ,         /* （連携用）マル特区分 */
     zrngyoumujyouhyouji ,         /* （連携用）業務上表示 */
     zrntuikakeijyoukbn ,         /* （連携用）追加計上区分 */
     zrnseisekinomikeijyoukbn ,         /* （連携用）成績のみ計上区分 */
     zrnteikikeijyoukbn ,         /* （連携用）定期計上区分 */
     zrnhngkmskkatkisykbn ,         /* （連携用）変額無資格扱者区分 */
     zrntnknkyuuyosakugenhyj ,         /* （連携用）転換給与削減表示 */
     zrntenkankaisuu ,         /* （連携用）転換回数 */
     zrnhiyubrigssnsikkijyunkbn ,         /* （連携用）併用払合算正規基準区分 */
     zrnsekininkaisiymd ,         /* （連携用）責任開始年月日 */
     zrnkigetusmkrgkykhyj ,         /* （連携用）期月締切後契約表示 */
     zrnhensyuusyoriymd ,         /* （連携用）編集処理年月日 */
     zrnjisisyaatukaihyouji ,         /* （連携用）自支社扱表示 */
     zrnaatkisytktntusy1atkihyj ,         /* （連携用）Ａ扱者地区担当者１扱表示 */
     zrnaatkisytktntusy2atkihyj ,         /* （連携用）Ａ扱者地区担当者２扱表示 */
     zrnaatkisyasyokan1atkihyj ,         /* （連携用）Ａ扱者所管１扱表示 */
     zrnaatkisyasyokan2atkihyj ,         /* （連携用）Ａ扱者所管２扱表示 */
     zrnbatkisytktntusy1atkihyj ,         /* （連携用）Ｂ扱者地区担当者１扱表示 */
     zrnbatkisytktntusy2atkihyj ,         /* （連携用）Ｂ扱者地区担当者２扱表示 */
     zrnbatkisyasyokan1atkihyj ,         /* （連携用）Ｂ扱者所管１扱表示 */
     zrnbatkisyasyokan2atkihyj ,         /* （連携用）Ｂ扱者所管２扱表示 */
     zrnkeizokutyuuihyouji ,         /* （連携用）継続注意表示 */
     zrnkeiyakubisiteihyouji ,         /* （連携用）契約日指定表示 */
     zrnjyoukentukihyouji ,         /* （連携用）条件付表示 */
     zrntokuninhyouji ,         /* （連携用）特認表示 */
     zrnkessantyouseikbn ,         /* （連携用）決算調整区分 */
     zrnhaneihyouji ,         /* （連携用）繁栄表示 */
     zrnsyukinkbn ,         /* （連携用）集金区分 */
     zrnkeiyakusyasyokugyoucd ,         /* （連携用）契約者職業コード */
     zrnseikeikeirokbn ,         /* （連携用）成契経路区分 */
     zrndai2seikeikeirokbn ,         /* （連携用）第２成契経路区分 */
     zrnteigentokuteisyuruikigou ,         /* （連携用）逓減トク定種類記号 */
     zrnteigentokuteikikan ,         /* （連携用）逓減トク定期間 */
     zrnteigentokuteis ,         /* （連携用）逓減トク定Ｓ */
     zrnteigentokuteip ,         /* （連携用）逓減トク定Ｐ */
     zrntigntktisdtpdtkbn ,         /* （連携用）逓減トク定Ｓ建Ｐ建区分 */
     zrnteigentokuteisyuuseis ,         /* （連携用）逓減トク定修正Ｓ */
     zrnteigentktimodssakugenhyj ,         /* （連携用）逓減トク定修正Ｓ削減表示 */
     zrnteigentktikgusdkbn ,         /* （連携用）逓減トク定記号世代区分 */
     zrnyobiv9 ,         /* （連携用）予備項目Ｖ９ */
     zrntokuteibuicdx1 ,         /* （連携用）特定部位コード＿１ */
     zrnhtnpkknx1 ,         /* （連携用）不担保期間＿１ */
     zrntokuteibuicdx2 ,         /* （連携用）特定部位コード＿２ */
     zrnhtnpkknx2 ,         /* （連携用）不担保期間＿２ */
     zrnhhknmei ,         /* （連携用）被保険者名 */
     zrnknjhhknmei ,         /* （連携用）漢字被保険者名 */
     zrnhhknseiymd ,         /* （連携用）被保険者生年月日 */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhhknhnsktodouhukencd ,         /* （連携用）被保険者本籍都道府県コード */
     zrnhihokensyaagev2 ,         /* （連携用）被保険者年令Ｖ２ */
     zrnhihokensyakikykarihyj ,         /* （連携用）被保険者既契約有表示 */
     zrnnobikkosaimankikbn ,         /* （連携用）のびっこ才満期区分 */
     zrnhhknsysysnhonninkknnkbn ,         /* （連携用）被保険者初診本人確認区分 */
     zrnhhknsysisnhonninkknnkbn ,         /* （連携用）被保険者再診本人確認区分 */
     zrnkzktourokuservicearihyj ,         /* （連携用）家族登録サービス有表示 */
     zrnyobiv4x12 ,         /* （連携用）予備項目Ｖ４＿１２ */
     zrnhensyuukeiyakusyamei ,         /* （連携用）編集契約者名 */
     zrnhnsyuknjkyksynm ,         /* （連携用）編集漢字契約者名 */
     zrnkyksyaseiymd ,         /* （連携用）契約者生年月日 */
     zrnkyksyaseikbn ,         /* （連携用）契約者性別区分 */
     zrnkyksyanen ,         /* （連携用）契約者年令 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnknkuzusnzyrt ,         /* （連携用）健康増進乗率 */
     zrnvitdoujimos2kenmeikouhyj ,         /* （連携用）Ｖｉｔ同時申込２件目以降表示 */
     zrnkikykvitarituikamoshyj ,         /* （連携用）既契約Ｖｉｔ有追加申込表示 */
     zrnhtnknkykvithokenkbn ,         /* （連携用）被転換契約Ｖｉｔ保険区分 */
     zrnkikykvithokenhoyuujkkbn ,         /* （連携用）既契約Ｖｉｔ保険保有状況区分 */
     zrnyobiv2x2 ,         /* （連携用）予備項目Ｖ２＿２ */
     zrntsnsknewyno ,         /* （連携用）通信先新郵便番号 */
     zrntsnsknewtikucd ,         /* （連携用）通信先新地区コード */
     zrnmossyumtkktymd ,         /* （連携用）申込消滅確定年月日 */
     zrnkituenkbn ,         /* （連携用）喫煙区分 */
     zrntuusinsakijyuusyokbn ,         /* （連携用）通信先住所区分 */
     zrnmaruteisyuruikigou ,         /* （連携用）マル定種類記号 */
     zrnmaruteikikan ,         /* （連携用）マル定期間 */
     zrnmaruteiphrkkkn ,         /* （連携用）マル定Ｐ払込期間 */
     zrnmaruteis ,         /* （連携用）マル定Ｓ */
     zrnmaruteip ,         /* （連携用）マル定Ｐ */
     zrnmaruteisyuuseis ,         /* （連携用）マル定修正Ｓ */
     zrnmaruteisyuuseisskgnhyj ,         /* （連携用）マル定修正Ｓ削減表示 */
     zrnmaruteitokujyoukbn ,         /* （連携用）マル定特条区分 */
     zrnmrtitkjyuskgnkkn ,         /* （連携用）マル定特条削減期間 */
     zrnmrtitkjyuryumshyutn ,         /* （連携用）マル定特条料増標点 */
     zrnmaruteitokujyoup ,         /* （連携用）マル定特条Ｐ */
     zrnsuryumrtipwrbkkbn ,         /* （連携用）数理用マル定Ｐ割引区分 */
     zrnmaruteipwaribikikbn ,         /* （連携用）マル定Ｐ割引区分 */
     zrnmrtitnknyugukbn ,         /* （連携用）マル定転換優遇区分 */
     zrnmaruteikigousedaikbn ,         /* （連携用）マル定記号世代区分 */
     zrnmaruteikikousnmnryoage ,         /* （連携用）マル定更新満了年令 */
     zrnyobiv2 ,         /* （連携用）予備項目Ｖ２ */
     zrnmaruyousyuruikigou ,         /* （連携用）マル養種類記号 */
     zrnmaruyoukikan ,         /* （連携用）マル養期間 */
     zrnmaruyous ,         /* （連携用）マル養Ｓ */
     zrnmaruyoup ,         /* （連携用）マル養Ｐ */
     zrnmaruyousdatepdatekbn ,         /* （連携用）マル養Ｓ建Ｐ建区分 */
     zrnmaruyousyuuseis ,         /* （連携用）マル養修正Ｓ */
     zrnmaruyousyuuseisskgnhyj ,         /* （連携用）マル養修正Ｓ削減表示 */
     zrnmaruyoukigousedaikbn ,         /* （連携用）マル養記号世代区分 */
     zrnyobiv9x3 ,         /* （連携用）予備項目Ｖ９＿３ */
     zrnmarusyuusyuruikigou ,         /* （連携用）マル終種類記号 */
     zrnmarusyuukikan ,         /* （連携用）マル終期間 */
     zrnmarusyuus ,         /* （連携用）マル終Ｓ */
     zrnmarusyuup ,         /* （連携用）マル終Ｐ */
     zrnmarusyuusdatepdatekbn ,         /* （連携用）マル終Ｓ建Ｐ建区分 */
     zrnmarusyuusyuuseis ,         /* （連携用）マル終修正Ｓ */
     zrnmarusyuusyuuseisskgnhyj ,         /* （連携用）マル終修正Ｓ削減表示 */
     zrnmarusyuukigousedaikbn ,         /* （連携用）マル終記号世代区分 */
     zrnyobiv9x4 ,         /* （連携用）予備項目Ｖ９＿４ */
     zrntokuteisyuruikigou ,         /* （連携用）トク定種類記号 */
     zrntokuteikikan ,         /* （連携用）トク定期間 */
     zrntokuteis ,         /* （連携用）トク定Ｓ */
     zrntokuteip ,         /* （連携用）トク定Ｐ */
     zrntokuteisdatepdatekbn ,         /* （連携用）トク定Ｓ建Ｐ建区分 */
     zrntokuteisyuuseis ,         /* （連携用）トク定修正Ｓ */
     zrntokuteisyuuseisskgnhyj ,         /* （連携用）トク定修正Ｓ削減表示 */
     zrntokuteikigousedaikbn ,         /* （連携用）トク定記号世代区分 */
     zrnyobiv9x5 ,         /* （連携用）予備項目Ｖ９＿５ */
     zrnkzkmrtitkyknox1 ,         /* （連携用）家族マル定特約番号＿１ */
     zrnkazokumrtisyuruikgux1 ,         /* （連携用）家族マル定種類記号＿１ */
     zrnkazokumaruteikikanx1 ,         /* （連携用）家族マル定期間＿１ */
     zrnkazokumrtiphrkkknx1 ,         /* （連携用）家族マル定Ｐ払込期間＿１ */
     zrnkazokumaruteisx1 ,         /* （連携用）家族マル定Ｓ＿１ */
     zrnkazokumaruteipx1 ,         /* （連携用）家族マル定Ｐ＿１ */
     zrnkzkmrtihihknsyanmx1 ,         /* （連携用）家族マル定被保険者名＿１ */
     zrnkzkmrtihihknsyseiymdx1 ,         /* （連携用）家族マル定被保険者生年月日＿１ */
     zrnkzkmrtihihknsysibtkbnx1 ,         /* （連携用）家族マル定被保険者性別区分＿１ */
     zrnkazokumrtihihknsyaagex1 ,         /* （連携用）家族マル定被保険者年令＿１ */
     zrnkzkmrtimodsx1 ,         /* （連携用）家族マル定修正Ｓ＿１ */
     zrnkazokumrtimodsskgnhyjx1 ,         /* （連携用）家族マル定修正Ｓ削減表示＿１ */
     zrnkzkmrtitnknyugukbnx1 ,         /* （連携用）家族マル定転換優遇区分＿１ */
     zrnkazokumrtikgusdkbnx1 ,         /* （連携用）家族マル定記号世代区分＿１ */
     zrnkazokumrtiagetyusihyjx1 ,         /* （連携用）家族マル定年令調整表示＿１ */
     zrnkzkmrtikusnmnryoagex1 ,         /* （連携用）家族マル定更新満了年令＿１ */
     zrnyobiv4 ,         /* （連携用）予備項目Ｖ４ */
     zrnkzkmrtitkyknox2 ,         /* （連携用）家族マル定特約番号＿２ */
     zrnkazokumrtisyuruikgux2 ,         /* （連携用）家族マル定種類記号＿２ */
     zrnkazokumaruteikikanx2 ,         /* （連携用）家族マル定期間＿２ */
     zrnkazokumrtiphrkkknx2 ,         /* （連携用）家族マル定Ｐ払込期間＿２ */
     zrnkazokumaruteisx2 ,         /* （連携用）家族マル定Ｓ＿２ */
     zrnkazokumaruteipx2 ,         /* （連携用）家族マル定Ｐ＿２ */
     zrnkzkmrtihihknsyanmx2 ,         /* （連携用）家族マル定被保険者名＿２ */
     zrnkzkmrtihihknsyseiymdx2 ,         /* （連携用）家族マル定被保険者生年月日＿２ */
     zrnkzkmrtihihknsysibtkbnx2 ,         /* （連携用）家族マル定被保険者性別区分＿２ */
     zrnkazokumrtihihknsyaagex2 ,         /* （連携用）家族マル定被保険者年令＿２ */
     zrnkzkmrtimodsx2 ,         /* （連携用）家族マル定修正Ｓ＿２ */
     zrnkazokumrtimodsskgnhyjx2 ,         /* （連携用）家族マル定修正Ｓ削減表示＿２ */
     zrnkzkmrtitnknyugukbnx2 ,         /* （連携用）家族マル定転換優遇区分＿２ */
     zrnkazokumrtikgusdkbnx2 ,         /* （連携用）家族マル定記号世代区分＿２ */
     zrnkazokumrtiagetyusihyjx2 ,         /* （連携用）家族マル定年令調整表示＿２ */
     zrnkzkmrtikusnmnryoagex2 ,         /* （連携用）家族マル定更新満了年令＿２ */
     zrnyobiv4x2 ,         /* （連携用）予備項目Ｖ４＿２ */
     zrnkzkmrtitkyknox3 ,         /* （連携用）家族マル定特約番号＿３ */
     zrnkazokumrtisyuruikgux3 ,         /* （連携用）家族マル定種類記号＿３ */
     zrnkazokumaruteikikanx3 ,         /* （連携用）家族マル定期間＿３ */
     zrnkazokumrtiphrkkknx3 ,         /* （連携用）家族マル定Ｐ払込期間＿３ */
     zrnkazokumaruteisx3 ,         /* （連携用）家族マル定Ｓ＿３ */
     zrnkazokumaruteipx3 ,         /* （連携用）家族マル定Ｐ＿３ */
     zrnkzkmrtihihknsyanmx3 ,         /* （連携用）家族マル定被保険者名＿３ */
     zrnkzkmrtihihknsyseiymdx3 ,         /* （連携用）家族マル定被保険者生年月日＿３ */
     zrnkzkmrtihihknsysibtkbnx3 ,         /* （連携用）家族マル定被保険者性別区分＿３ */
     zrnkazokumrtihihknsyaagex3 ,         /* （連携用）家族マル定被保険者年令＿３ */
     zrnkzkmrtimodsx3 ,         /* （連携用）家族マル定修正Ｓ＿３ */
     zrnkazokumrtimodsskgnhyjx3 ,         /* （連携用）家族マル定修正Ｓ削減表示＿３ */
     zrnkzkmrtitnknyugukbnx3 ,         /* （連携用）家族マル定転換優遇区分＿３ */
     zrnkazokumrtikgusdkbnx3 ,         /* （連携用）家族マル定記号世代区分＿３ */
     zrnkazokumrtiagetyusihyjx3 ,         /* （連携用）家族マル定年令調整表示＿３ */
     zrnkzkmrtikusnmnryoagex3 ,         /* （連携用）家族マル定更新満了年令＿３ */
     zrnyobiv4x3 ,         /* （連携用）予備項目Ｖ４＿３ */
     zrnkzkmrtitkyknox4 ,         /* （連携用）家族マル定特約番号＿４ */
     zrnkazokumrtisyuruikgux4 ,         /* （連携用）家族マル定種類記号＿４ */
     zrnkazokumaruteikikanx4 ,         /* （連携用）家族マル定期間＿４ */
     zrnkazokumrtiphrkkknx4 ,         /* （連携用）家族マル定Ｐ払込期間＿４ */
     zrnkazokumaruteisx4 ,         /* （連携用）家族マル定Ｓ＿４ */
     zrnkazokumaruteipx4 ,         /* （連携用）家族マル定Ｐ＿４ */
     zrnkzkmrtihihknsyanmx4 ,         /* （連携用）家族マル定被保険者名＿４ */
     zrnkzkmrtihihknsyseiymdx4 ,         /* （連携用）家族マル定被保険者生年月日＿４ */
     zrnkzkmrtihihknsysibtkbnx4 ,         /* （連携用）家族マル定被保険者性別区分＿４ */
     zrnkazokumrtihihknsyaagex4 ,         /* （連携用）家族マル定被保険者年令＿４ */
     zrnkzkmrtimodsx4 ,         /* （連携用）家族マル定修正Ｓ＿４ */
     zrnkazokumrtimodsskgnhyjx4 ,         /* （連携用）家族マル定修正Ｓ削減表示＿４ */
     zrnkzkmrtitnknyugukbnx4 ,         /* （連携用）家族マル定転換優遇区分＿４ */
     zrnkazokumrtikgusdkbnx4 ,         /* （連携用）家族マル定記号世代区分＿４ */
     zrnkazokumrtiagetyusihyjx4 ,         /* （連携用）家族マル定年令調整表示＿４ */
     zrnkzkmrtikusnmnryoagex4 ,         /* （連携用）家族マル定更新満了年令＿４ */
     zrnyobiv4x4 ,         /* （連携用）予備項目Ｖ４＿４ */
     zrnkzkmrtitkyknox5 ,         /* （連携用）家族マル定特約番号＿５ */
     zrnkazokumrtisyuruikgux5 ,         /* （連携用）家族マル定種類記号＿５ */
     zrnkazokumaruteikikanx5 ,         /* （連携用）家族マル定期間＿５ */
     zrnkazokumrtiphrkkknx5 ,         /* （連携用）家族マル定Ｐ払込期間＿５ */
     zrnkazokumaruteisx5 ,         /* （連携用）家族マル定Ｓ＿５ */
     zrnkazokumaruteipx5 ,         /* （連携用）家族マル定Ｐ＿５ */
     zrnkzkmrtihihknsyanmx5 ,         /* （連携用）家族マル定被保険者名＿５ */
     zrnkzkmrtihihknsyseiymdx5 ,         /* （連携用）家族マル定被保険者生年月日＿５ */
     zrnkzkmrtihihknsysibtkbnx5 ,         /* （連携用）家族マル定被保険者性別区分＿５ */
     zrnkazokumrtihihknsyaagex5 ,         /* （連携用）家族マル定被保険者年令＿５ */
     zrnkzkmrtimodsx5 ,         /* （連携用）家族マル定修正Ｓ＿５ */
     zrnkazokumrtimodsskgnhyjx5 ,         /* （連携用）家族マル定修正Ｓ削減表示＿５ */
     zrnkzkmrtitnknyugukbnx5 ,         /* （連携用）家族マル定転換優遇区分＿５ */
     zrnkazokumrtikgusdkbnx5 ,         /* （連携用）家族マル定記号世代区分＿５ */
     zrnkazokumrtiagetyusihyjx5 ,         /* （連携用）家族マル定年令調整表示＿５ */
     zrnkzkmrtikusnmnryoagex5 ,         /* （連携用）家族マル定更新満了年令＿５ */
     zrnyobiv4x5 ,         /* （連携用）予備項目Ｖ４＿５ */
     zrnkzkmrtitkyknox6 ,         /* （連携用）家族マル定特約番号＿６ */
     zrnkazokumrtisyuruikgux6 ,         /* （連携用）家族マル定種類記号＿６ */
     zrnkazokumaruteikikanx6 ,         /* （連携用）家族マル定期間＿６ */
     zrnkazokumrtiphrkkknx6 ,         /* （連携用）家族マル定Ｐ払込期間＿６ */
     zrnkazokumaruteisx6 ,         /* （連携用）家族マル定Ｓ＿６ */
     zrnkazokumaruteipx6 ,         /* （連携用）家族マル定Ｐ＿６ */
     zrnkzkmrtihihknsyanmx6 ,         /* （連携用）家族マル定被保険者名＿６ */
     zrnkzkmrtihihknsyseiymdx6 ,         /* （連携用）家族マル定被保険者生年月日＿６ */
     zrnkzkmrtihihknsysibtkbnx6 ,         /* （連携用）家族マル定被保険者性別区分＿６ */
     zrnkazokumrtihihknsyaagex6 ,         /* （連携用）家族マル定被保険者年令＿６ */
     zrnkzkmrtimodsx6 ,         /* （連携用）家族マル定修正Ｓ＿６ */
     zrnkazokumrtimodsskgnhyjx6 ,         /* （連携用）家族マル定修正Ｓ削減表示＿６ */
     zrnkzkmrtitnknyugukbnx6 ,         /* （連携用）家族マル定転換優遇区分＿６ */
     zrnkazokumrtikgusdkbnx6 ,         /* （連携用）家族マル定記号世代区分＿６ */
     zrnkazokumrtiagetyusihyjx6 ,         /* （連携用）家族マル定年令調整表示＿６ */
     zrnkzkmrtikusnmnryoagex6 ,         /* （連携用）家族マル定更新満了年令＿６ */
     zrnyobiv4x6 ,         /* （連携用）予備項目Ｖ４＿６ */
     zrnkzkmrtitkyknox7 ,         /* （連携用）家族マル定特約番号＿７ */
     zrnkazokumrtisyuruikgux7 ,         /* （連携用）家族マル定種類記号＿７ */
     zrnkazokumaruteikikanx7 ,         /* （連携用）家族マル定期間＿７ */
     zrnkazokumrtiphrkkknx7 ,         /* （連携用）家族マル定Ｐ払込期間＿７ */
     zrnkazokumaruteisx7 ,         /* （連携用）家族マル定Ｓ＿７ */
     zrnkazokumaruteipx7 ,         /* （連携用）家族マル定Ｐ＿７ */
     zrnkzkmrtihihknsyanmx7 ,         /* （連携用）家族マル定被保険者名＿７ */
     zrnkzkmrtihihknsyseiymdx7 ,         /* （連携用）家族マル定被保険者生年月日＿７ */
     zrnkzkmrtihihknsysibtkbnx7 ,         /* （連携用）家族マル定被保険者性別区分＿７ */
     zrnkazokumrtihihknsyaagex7 ,         /* （連携用）家族マル定被保険者年令＿７ */
     zrnkzkmrtimodsx7 ,         /* （連携用）家族マル定修正Ｓ＿７ */
     zrnkazokumrtimodsskgnhyjx7 ,         /* （連携用）家族マル定修正Ｓ削減表示＿７ */
     zrnkzkmrtitnknyugukbnx7 ,         /* （連携用）家族マル定転換優遇区分＿７ */
     zrnkazokumrtikgusdkbnx7 ,         /* （連携用）家族マル定記号世代区分＿７ */
     zrnkazokumrtiagetyusihyjx7 ,         /* （連携用）家族マル定年令調整表示＿７ */
     zrnkzkmrtikusnmnryoagex7 ,         /* （連携用）家族マル定更新満了年令＿７ */
     zrnyobiv4x7 ,         /* （連携用）予備項目Ｖ４＿７ */
     zrnkzkmrtitkyknox8 ,         /* （連携用）家族マル定特約番号＿８ */
     zrnkazokumrtisyuruikgux8 ,         /* （連携用）家族マル定種類記号＿８ */
     zrnkazokumaruteikikanx8 ,         /* （連携用）家族マル定期間＿８ */
     zrnkazokumrtiphrkkknx8 ,         /* （連携用）家族マル定Ｐ払込期間＿８ */
     zrnkazokumaruteisx8 ,         /* （連携用）家族マル定Ｓ＿８ */
     zrnkazokumaruteipx8 ,         /* （連携用）家族マル定Ｐ＿８ */
     zrnkzkmrtihihknsyanmx8 ,         /* （連携用）家族マル定被保険者名＿８ */
     zrnkzkmrtihihknsyseiymdx8 ,         /* （連携用）家族マル定被保険者生年月日＿８ */
     zrnkzkmrtihihknsysibtkbnx8 ,         /* （連携用）家族マル定被保険者性別区分＿８ */
     zrnkazokumrtihihknsyaagex8 ,         /* （連携用）家族マル定被保険者年令＿８ */
     zrnkzkmrtimodsx8 ,         /* （連携用）家族マル定修正Ｓ＿８ */
     zrnkazokumrtimodsskgnhyjx8 ,         /* （連携用）家族マル定修正Ｓ削減表示＿８ */
     zrnkzkmrtitnknyugukbnx8 ,         /* （連携用）家族マル定転換優遇区分＿８ */
     zrnkazokumrtikgusdkbnx8 ,         /* （連携用）家族マル定記号世代区分＿８ */
     zrnkazokumrtiagetyusihyjx8 ,         /* （連携用）家族マル定年令調整表示＿８ */
     zrnkzkmrtikusnmnryoagex8 ,         /* （連携用）家族マル定更新満了年令＿８ */
     zrnyobiv4x8 ,         /* （連携用）予備項目Ｖ４＿８ */
     zrnkzkmrtitkyknox9 ,         /* （連携用）家族マル定特約番号＿９ */
     zrnkazokumrtisyuruikgux9 ,         /* （連携用）家族マル定種類記号＿９ */
     zrnkazokumaruteikikanx9 ,         /* （連携用）家族マル定期間＿９ */
     zrnkazokumrtiphrkkknx9 ,         /* （連携用）家族マル定Ｐ払込期間＿９ */
     zrnkazokumaruteisx9 ,         /* （連携用）家族マル定Ｓ＿９ */
     zrnkazokumaruteipx9 ,         /* （連携用）家族マル定Ｐ＿９ */
     zrnkzkmrtihihknsyanmx9 ,         /* （連携用）家族マル定被保険者名＿９ */
     zrnkzkmrtihihknsyseiymdx9 ,         /* （連携用）家族マル定被保険者生年月日＿９ */
     zrnkzkmrtihihknsysibtkbnx9 ,         /* （連携用）家族マル定被保険者性別区分＿９ */
     zrnkazokumrtihihknsyaagex9 ,         /* （連携用）家族マル定被保険者年令＿９ */
     zrnkzkmrtimodsx9 ,         /* （連携用）家族マル定修正Ｓ＿９ */
     zrnkazokumrtimodsskgnhyjx9 ,         /* （連携用）家族マル定修正Ｓ削減表示＿９ */
     zrnkzkmrtitnknyugukbnx9 ,         /* （連携用）家族マル定転換優遇区分＿９ */
     zrnkazokumrtikgusdkbnx9 ,         /* （連携用）家族マル定記号世代区分＿９ */
     zrnkazokumrtiagetyusihyjx9 ,         /* （連携用）家族マル定年令調整表示＿９ */
     zrnkzkmrtikusnmnryoagex9 ,         /* （連携用）家族マル定更新満了年令＿９ */
     zrnyobiv4x9 ,         /* （連携用）予備項目Ｖ４＿９ */
     zrnkzkmrtitkyknox10 ,         /* （連携用）家族マル定特約番号＿１０ */
     zrnkazokumrtisyuruikgux10 ,         /* （連携用）家族マル定種類記号＿１０ */
     zrnkazokumaruteikikanx10 ,         /* （連携用）家族マル定期間＿１０ */
     zrnkazokumrtiphrkkknx10 ,         /* （連携用）家族マル定Ｐ払込期間＿１０ */
     zrnkazokumaruteisx10 ,         /* （連携用）家族マル定Ｓ＿１０ */
     zrnkazokumaruteipx10 ,         /* （連携用）家族マル定Ｐ＿１０ */
     zrnkzkmrtihihknsyanmx10 ,         /* （連携用）家族マル定被保険者名＿１０ */
     zrnkzkmrtihihknsyseiymdx10 ,         /* （連携用）家族マル定被保険者生年月日＿１０ */
     zrnkzkmrtihihknsysibtkbnx10 ,         /* （連携用）家族マル定被保険者性別区分＿１０ */
     zrnkazokumrtihihknsyaagex10 ,         /* （連携用）家族マル定被保険者年令＿１０ */
     zrnkzkmrtimodsx10 ,         /* （連携用）家族マル定修正Ｓ＿１０ */
     zrnkazokumrtimodsskgnhyjx10 ,         /* （連携用）家族マル定修正Ｓ削減表示＿１０ */
     zrnkzkmrtitnknyugukbnx10 ,         /* （連携用）家族マル定転換優遇区分＿１０ */
     zrnkazokumrtikgusdkbnx10 ,         /* （連携用）家族マル定記号世代区分＿１０ */
     zrnkazokumrtiagetyusihyjx10 ,         /* （連携用）家族マル定年令調整表示＿１０ */
     zrnkzkmrtikusnmnryoagex10 ,         /* （連携用）家族マル定更新満了年令＿１０ */
     zrnyobiv4x10 ,         /* （連携用）予備項目Ｖ４＿１０ */
     zrnnkshrtkykhuhokbnx1 ,         /* （連携用）年金支払特約付保区分＿１ */
     zrnnkshrtkyknksyuruikbnx1 ,         /* （連携用）年金支払特約年金種類区分＿１ */
     zrnnkshrtkyknkkknx1 ,         /* （連携用）年金支払特約年金期間＿１ */
     zrnnkshrtkyknknengkx1 ,         /* （連携用）年金支払特約年金年額＿１ */
     zrnnkshrtkykduketorihhkbnx1 ,         /* （連携用）年金支払特約Ｄ受取方法区分＿１ */
     zrnyobiv10 ,         /* （連携用）予備項目Ｖ１０ */
     zrnnkshrtkykhuhokbnx2 ,         /* （連携用）年金支払特約付保区分＿２ */
     zrnnkshrtkyknksyuruikbnx2 ,         /* （連携用）年金支払特約年金種類区分＿２ */
     zrnnkshrtkyknkkknx2 ,         /* （連携用）年金支払特約年金期間＿２ */
     zrnnkshrtkyknknengkx2 ,         /* （連携用）年金支払特約年金年額＿２ */
     zrnnkshrtkykduketorihhkbnx2 ,         /* （連携用）年金支払特約Ｄ受取方法区分＿２ */
     zrnyobiv10x2 ,         /* （連携用）予備項目Ｖ１０＿２ */
     zrnsyougaitkyksyuruikgu ,         /* （連携用）傷害特約種類記号 */
     zrnsyougaitokuyakukikan ,         /* （連携用）傷害特約期間 */
     zrnsyougaitkykphrkkkn ,         /* （連携用）傷害特約Ｐ払込期間 */
     zrnsyougaitokuyakus ,         /* （連携用）傷害特約Ｓ */
     zrnsyougaitokuyakup ,         /* （連携用）傷害特約Ｐ */
     zrnsyougaitkkatakbn ,         /* （連携用）傷害特約型区分 */
     zrnsyougaitkykkgusdkbn ,         /* （連携用）傷害特約記号世代区分 */
     zrnsyugitkykpwrbkkbn ,         /* （連携用）傷害特約Ｐ割引区分 */
     zrnsyougaitkykkusnmnryoage ,         /* （連携用）傷害特約更新満了年令 */
     zrnyobiv5x2 ,         /* （連携用）予備項目Ｖ５＿２ */
     zrnsigiwrmstkyksyuruikgu ,         /* （連携用）災害割増特約種類記号 */
     zrnsigiwrmstkykkkn ,         /* （連携用）災害割増特約期間 */
     zrnsaigaiwrmstkykphrkkkn ,         /* （連携用）災害割増特約Ｐ払込期間 */
     zrnsaigaiwarimasitokuyakus ,         /* （連携用）災害割増特約Ｓ */
     zrnsaigaiwarimasitokuyakup ,         /* （連携用）災害割増特約Ｐ */
     zrnsaigaiwrmstkykkgusdkbn ,         /* （連携用）災害割増特約記号世代区分 */
     zrnsigiwrmstkykpwrbkkbn ,         /* （連携用）災害割増特約Ｐ割引区分 */
     zrnsigiwrmstkykkusnmnryoage ,         /* （連携用）災害割増特約更新満了年令 */
     zrnyobiv5x3 ,         /* （連携用）予備項目Ｖ５＿３ */
     zrnsiginyuintkyksyuruikgu ,         /* （連携用）災害入院特約種類記号 */
     zrnsiginyuintkykkkn ,         /* （連携用）災害入院特約期間 */
     zrnsaigainyuintkykphrkkkn ,         /* （連携用）災害入院特約Ｐ払込期間 */
     zrnsiginyuintkykntgk ,         /* （連携用）災害入院特約日額 */
     zrnsiginyuintkykgtkbn ,         /* （連携用）災害入院特約型区分 */
     zrnsaigainyuuintokuyakup ,         /* （連携用）災害入院特約Ｐ */
     zrnsaigainyuintkykkgusdkbn ,         /* （連携用）災害入院特約記号世代区分 */
     zrnsiginyuintkykpwrbkkbn ,         /* （連携用）災害入院特約Ｐ割引区分 */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrnsppinyuintkyksyuruikgu ,         /* （連携用）疾病入院特約種類記号 */
     zrnsppinyuintkykkkn ,         /* （連携用）疾病入院特約期間 */
     zrnsppinyuuintkykphrkkkn ,         /* （連携用）疾病入院特約Ｐ払込期間 */
     zrnsppinyuintkykntgk ,         /* （連携用）疾病入院特約日額 */
     zrnsppinyuintkykgtkbn ,         /* （連携用）疾病入院特約型区分 */
     zrnsippeinyuuintokuyakup ,         /* （連携用）疾病入院特約Ｐ */
     zrnsppinyuintkjyuryumshyutn ,         /* （連携用）疾病入院特条料増標点 */
     zrnsippeinyuuintokujyoup ,         /* （連携用）疾病入院特条Ｐ */
     zrnsppinyuintktbicdx1 ,         /* （連携用）疾病入院特定部位コード＿１ */
     zrnsppinyuinhtnpkknx1 ,         /* （連携用）疾病入院不担保期間＿１ */
     zrnsppinyuintktbicdx2 ,         /* （連携用）疾病入院特定部位コード＿２ */
     zrnsppinyuinhtnpkknx2 ,         /* （連携用）疾病入院不担保期間＿２ */
     zrnsppinyuuintkykkgusdkbn ,         /* （連携用）疾病入院特約記号世代区分 */
     zrnsppinyuintkykpwrbkkbn ,         /* （連携用）疾病入院特約Ｐ割引区分 */
     zrnyobiv7x2 ,         /* （連携用）予備項目Ｖ７＿２ */
     zrnsijnbyutkyksyuruikgu ,         /* （連携用）成人病特約種類記号 */
     zrnseijinbyoutokuyakukikan ,         /* （連携用）成人病特約期間 */
     zrnseijinbyoutkykphrkkkn ,         /* （連携用）成人病特約Ｐ払込期間 */
     zrnseijinbyoutokuyakuntgk ,         /* （連携用）成人病特約日額 */
     zrnseijinbyoutokuyakup ,         /* （連携用）成人病特約Ｐ */
     zrnsijnbyutkjyuryumshyutn ,         /* （連携用）成人病特条料増標点 */
     zrnseijinbyoutokujyoup ,         /* （連携用）成人病特条Ｐ */
     zrnseijinbyoutokuteibuicdx1 ,         /* （連携用）成人病特定部位コード＿１ */
     zrnseijinbyouhutanpokikanx1 ,         /* （連携用）成人病不担保期間＿１ */
     zrnseijinbyoutokuteibuicdx2 ,         /* （連携用）成人病特定部位コード＿２ */
     zrnseijinbyouhutanpokikanx2 ,         /* （連携用）成人病不担保期間＿２ */
     zrnseijinbyoutkykkgusdkbn ,         /* （連携用）成人病特約記号世代区分 */
     zrnsijnbyutkykgankyuhgtkbn ,         /* （連携用）成人病特約ガン給付型区分 */
     zrnsijnbyutkykpwrbkkbn ,         /* （連携用）成人病特約Ｐ割引区分 */
     zrnsijnbyutkykkusnmnryoage ,         /* （連携用）成人病特約更新満了年令 */
     zrnyobiv4x11 ,         /* （連携用）予備項目Ｖ４＿１１ */
     zrnheiyoubaraikbn ,         /* （連携用）併用払区分 */
     zrnhiyubriaitsyono ,         /* （連携用）併用払相手証券番号 */
     zrnhiyubriaithrkkeirokbn ,         /* （連携用）併用払相手払込経路区分 */
     zrnheiyoubaraiaitekihons ,         /* （連携用）併用払相手基本Ｓ */
     zrnhiyubrigukitnknitjbrkhns ,         /* （連携用）併用払合計転換一時払基本Ｓ */
     zrnheiyoubaraiaitesibous ,         /* （連携用）併用払相手死亡Ｓ */
     zrnhiyubrigukitnknitjbrsbus ,         /* （連携用）併用払合計転換一時払死亡Ｓ */
     zrnheiyoubaraiaitesyuuseis ,         /* （連携用）併用払相手修正Ｓ */
     zrnheiyoubaraiaitehrkp ,         /* （連携用）併用払相手払込Ｐ */
     zrnhiyubriaitsykykp ,         /* （連携用）併用払相手主契約Ｐ */
     zrnheiyoubaraiaitemrtis ,         /* （連携用）併用払相手マル定Ｓ */
     zrnhiyubrigukiaitkzkmrtis ,         /* （連携用）併用払合計相手家族マル定Ｓ */
     zrntukibaraikyktenkanhyj ,         /* （連携用）月払契約転換表示 */
     zrnbonusharaihrkkigetu1 ,         /* （連携用）ボーナス払払込期月１ */
     zrnbonusharaihrkkigetu2 ,         /* （連携用）ボーナス払払込期月２ */
     zrnhiyubriaitsiznmrtis ,         /* （連携用）併用払相手生存マル定Ｓ */
     zrnhiyubriaittignmrtis ,         /* （連携用）併用払相手逓減マル定Ｓ */
     zrntkjykbn ,         /* （連携用）特条区分 */
     zrnsakugenkikan ,         /* （連携用）削減期間 */
     zrnryoumasihyouten ,         /* （連携用）料増標点 */
     zrntokujyoup ,         /* （連携用）特条Ｐ */
     zrnhjncd ,         /* （連携用）法人コード */
     zrnhjnjigyosyocd ,         /* （連携用）法人事業所コード */
     zrnjyuugyouinsuu ,         /* （連携用）従業員数 */
     zrniktkaisuu ,         /* （連携用）一括回数 */
     zrnznnkai ,         /* （連携用）前納回数 */
     zrnkyktsnatkitkykkbn ,         /* （連携用）契約通算扱特約区分 */
     zrnkyktsnatkitkykstagekbn ,         /* （連携用）契約通算扱特約ステージ区分 */
     zrnpmentokuyakukbn ,         /* （連携用）Ｐ免特約区分 */
     zrnyobiv3 ,         /* （連携用）予備項目Ｖ３ */
     zrntkykznnunyukngk ,         /* （連携用）特約前納入金額 */
     zrnsyokaipnyuukinhouhoukbn ,         /* （連携用）初回Ｐ入金方法区分 */
     zrnhtnknkyksyonox1 ,         /* （連携用）被転換契約証券番号＿１ */
     zrnhtnknkykhknsyuruikgux1 ,         /* （連携用）被転換契約保険種類記号＿１ */
     zrntenkanuketukeymdx1 ,         /* （連携用）転換受付年月日＿１ */
     zrnhtnknkykkykymdx1 ,         /* （連携用）被転換契約契約年月日＿１ */
     zrnhtnknkykhknkknx1 ,         /* （連携用）被転換契約保険期間＿１ */
     zrnhtnknkykphrkkknx1 ,         /* （連携用）被転換契約Ｐ払込期間＿１ */
     zrnhtnknkykhrkkaisuukbnx1 ,         /* （連携用）被転換契約払込回数区分＿１ */
     zrnhtnknkykhrkkeirokbnx1 ,         /* （連携用）被転換契約払込経路区分＿１ */
     zrntnknuktkzngtkijyuhyjx1 ,         /* （連携用）転換受付前月計上表示＿１ */
     zrnhtnknkykmrtisyuruikgux1 ,         /* （連携用）被転換契約マル定種類記号＿１ */
     zrnhtnknkyksyonox2 ,         /* （連携用）被転換契約証券番号＿２ */
     zrnhtnknkykhknsyuruikgux2 ,         /* （連携用）被転換契約保険種類記号＿２ */
     zrntenkanuketukeymdx2 ,         /* （連携用）転換受付年月日＿２ */
     zrnhtnknkykkykymdx2 ,         /* （連携用）被転換契約契約年月日＿２ */
     zrnhtnknkykhknkknx2 ,         /* （連携用）被転換契約保険期間＿２ */
     zrnhtnknkykphrkkknx2 ,         /* （連携用）被転換契約Ｐ払込期間＿２ */
     zrnhtnknkykhrkkaisuukbnx2 ,         /* （連携用）被転換契約払込回数区分＿２ */
     zrnhtnknkykhrkkeirokbnx2 ,         /* （連携用）被転換契約払込経路区分＿２ */
     zrntnknuktkzngtkijyuhyjx2 ,         /* （連携用）転換受付前月計上表示＿２ */
     zrnhtnknkykmrtisyuruikgux2 ,         /* （連携用）被転換契約マル定種類記号＿２ */
     zrnhtnknkyksyonox3 ,         /* （連携用）被転換契約証券番号＿３ */
     zrnhtnknkykhknsyuruikgux3 ,         /* （連携用）被転換契約保険種類記号＿３ */
     zrntenkanuketukeymdx3 ,         /* （連携用）転換受付年月日＿３ */
     zrnhtnknkykkykymdx3 ,         /* （連携用）被転換契約契約年月日＿３ */
     zrnhtnknkykhknkknx3 ,         /* （連携用）被転換契約保険期間＿３ */
     zrnhtnknkykphrkkknx3 ,         /* （連携用）被転換契約Ｐ払込期間＿３ */
     zrnhtnknkykhrkkaisuukbnx3 ,         /* （連携用）被転換契約払込回数区分＿３ */
     zrnhtnknkykhrkkeirokbnx3 ,         /* （連携用）被転換契約払込経路区分＿３ */
     zrntnknuktkzngtkijyuhyjx3 ,         /* （連携用）転換受付前月計上表示＿３ */
     zrnhtnknkykmrtisyuruikgux3 ,         /* （連携用）被転換契約マル定種類記号＿３ */
     zrnhtnknkyksyonox4 ,         /* （連携用）被転換契約証券番号＿４ */
     zrnhtnknkykhknsyuruikgux4 ,         /* （連携用）被転換契約保険種類記号＿４ */
     zrntenkanuketukeymdx4 ,         /* （連携用）転換受付年月日＿４ */
     zrnhtnknkykkykymdx4 ,         /* （連携用）被転換契約契約年月日＿４ */
     zrnhtnknkykhknkknx4 ,         /* （連携用）被転換契約保険期間＿４ */
     zrnhtnknkykphrkkknx4 ,         /* （連携用）被転換契約Ｐ払込期間＿４ */
     zrnhtnknkykhrkkaisuukbnx4 ,         /* （連携用）被転換契約払込回数区分＿４ */
     zrnhtnknkykhrkkeirokbnx4 ,         /* （連携用）被転換契約払込経路区分＿４ */
     zrntnknuktkzngtkijyuhyjx4 ,         /* （連携用）転換受付前月計上表示＿４ */
     zrnhtnknkykmrtisyuruikgux4 ,         /* （連携用）被転換契約マル定種類記号＿４ */
     zrnhtnknkyksyonox5 ,         /* （連携用）被転換契約証券番号＿５ */
     zrnhtnknkykhknsyuruikgux5 ,         /* （連携用）被転換契約保険種類記号＿５ */
     zrntenkanuketukeymdx5 ,         /* （連携用）転換受付年月日＿５ */
     zrnhtnknkykkykymdx5 ,         /* （連携用）被転換契約契約年月日＿５ */
     zrnhtnknkykhknkknx5 ,         /* （連携用）被転換契約保険期間＿５ */
     zrnhtnknkykphrkkknx5 ,         /* （連携用）被転換契約Ｐ払込期間＿５ */
     zrnhtnknkykhrkkaisuukbnx5 ,         /* （連携用）被転換契約払込回数区分＿５ */
     zrnhtnknkykhrkkeirokbnx5 ,         /* （連携用）被転換契約払込経路区分＿５ */
     zrntnknuktkzngtkijyuhyjx5 ,         /* （連携用）転換受付前月計上表示＿５ */
     zrnhtnknkykmrtisyuruikgux5 ,         /* （連携用）被転換契約マル定種類記号＿５ */
     zrnhtnknkyksyonox6 ,         /* （連携用）被転換契約証券番号＿６ */
     zrnhtnknkykhknsyuruikgux6 ,         /* （連携用）被転換契約保険種類記号＿６ */
     zrntenkanuketukeymdx6 ,         /* （連携用）転換受付年月日＿６ */
     zrnhtnknkykkykymdx6 ,         /* （連携用）被転換契約契約年月日＿６ */
     zrnhtnknkykhknkknx6 ,         /* （連携用）被転換契約保険期間＿６ */
     zrnhtnknkykphrkkknx6 ,         /* （連携用）被転換契約Ｐ払込期間＿６ */
     zrnhtnknkykhrkkaisuukbnx6 ,         /* （連携用）被転換契約払込回数区分＿６ */
     zrnhtnknkykhrkkeirokbnx6 ,         /* （連携用）被転換契約払込経路区分＿６ */
     zrntnknuktkzngtkijyuhyjx6 ,         /* （連携用）転換受付前月計上表示＿６ */
     zrnhtnknkykmrtisyuruikgux6 ,         /* （連携用）被転換契約マル定種類記号＿６ */
     zrngukihtnknkykkhns ,         /* （連携用）合計被転換契約基本Ｓ */
     zrngukihtnknkyksbus ,         /* （連携用）合計被転換契約死亡Ｓ */
     zrngukihtnknkykhntiyup ,         /* （連携用）合計被転換契約判定用Ｐ */
     zrngukihtnknkyksigwrmstkyks ,         /* （連携用）合計被転換契約災害割増特約Ｓ */
     zrngukihtnknkyksyugitkyks ,         /* （連携用）合計被転換契約傷害特約Ｓ */
     zrngukihtnknsignyintkykntgk ,         /* （連携用）合計被転換災害入院特約日額 */
     zrngukihtnknknkutkykntgk ,         /* （連携用）合計被転換健康特約日額 */
     zrngukihtnknkykmods ,         /* （連携用）合計被転換契約修正Ｓ */
     zrngoukeitenkankakaku ,         /* （連携用）合計転換価格 */
     zrngukitnknjsknnjynbkn ,         /* （連携用）合計転換時責任準備金 */
     zrngukitnknsisnkstkkngk ,         /* （連携用）合計転換精算貸付金額 */
     zrngukitnknsisnttkekngk ,         /* （連携用）合計転換精算立替金額 */
     zrngoukeitenkanseisand ,         /* （連携用）合計転換精算Ｄ */
     zrngukitnknsisnmkikp ,         /* （連携用）合計転換精算未経過Ｐ */
     zrngukitnknsisnsntkngk ,         /* （連携用）合計転換精算その他金額 */
     zrngukitnknkhnbbnkiykkujygk ,         /* （連携用）合計転換基本部分解約控除額 */
     zrngukitnkntikbbnkiykkujygk ,         /* （連携用）合計転換定期部分解約控除額 */
     zrngukitnknitjbrtiks ,         /* （連携用）合計転換一時払定期Ｓ */
     zrnsethokenno ,         /* （連携用）セット保険番号 */
     zrnsckbn ,         /* （連携用）ＳＣ区分 */
     zrnenjyosyacd ,         /* （連携用）援助者コード */
     zrnnaibuwarimodosigaku ,         /* （連携用）内部割戻額 */
     zrnkeiyakukakuninsyuruikbn ,         /* （連携用）契約確認種類区分 */
     zrnsoujikeitenkanhyouji ,         /* （連携用）相似形転換表示 */
     zrntenkanjisketteihouhoukbn ,         /* （連携用）転換時Ｓ決定方法区分 */
     zrnkeikanensuukbn ,         /* （連携用）経過年数区分 */
     zrnhtnknkykhhknsytisyukbnx1 ,         /* （連携用）被転換契約被保険者対象区分＿１ */
     zrnhtnknkykhhknsytisyukbnx2 ,         /* （連携用）被転換契約被保険者対象区分＿２ */
     zrnhtnknkykhhknsytisyukbnx3 ,         /* （連携用）被転換契約被保険者対象区分＿３ */
     zrnhtnknkykhhknsytisyukbnx4 ,         /* （連携用）被転換契約被保険者対象区分＿４ */
     zrnhtnknkykhhknsytisyukbnx5 ,         /* （連携用）被転換契約被保険者対象区分＿５ */
     zrnhtnknkykhhknsytisyukbnx6 ,         /* （連携用）被転換契約被保険者対象区分＿６ */
     zrnkktijgukipbbntnkns ,         /* （連携用）確定時合計Ｐ部分転換Ｓ */
     zrnsyonendosyokaip ,         /* （連携用）初年度初回Ｐ */
     zrnsyonendo2kaimeikoup ,         /* （連携用）初年度２回目以降Ｐ */
     zrnjinendoikoup ,         /* （連携用）次年度以降Ｐ */
     zrnsyukeiyakusikyuukisogaku ,         /* （連携用）主契約支給基礎額 */
     zrnsykyknenhantatskyuksgk ,         /* （連携用）主契約年半手当支給基礎額 */
     zrnmaruteisikyuukisogaku ,         /* （連携用）マル定支給基礎額 */
     zrnitjbrzugkskyuksgkx1 ,         /* （連携用）一時払増額支給基礎額＿１ */
     zrnitjbrzugkskyuksgkx2 ,         /* （連携用）一時払増額支給基礎額＿２ */
     zrnitjbrzgknnhntatskyksgkx1 ,         /* （連携用）一時払増額年半手当支給基礎額＿１ */
     zrnitjbrzgknnhntatskyksgkx2 ,         /* （連携用）一時払増額年半手当支給基礎額＿２ */
     zrnkzkmrtiskyuksgk ,         /* （連携用）家族マル定支給基礎額 */
     zrnitibitjbrskyuksgk ,         /* （連携用）一部一時払支給基礎額 */
     zrnitbitjbrnnhntatskyuksgk ,         /* （連携用）一部一時払年半手当支給基礎額 */
     zrnsykykksnbsyutat ,         /* （連携用）主契約加算募集手当 */
     zrnitjbrzugkksnbsyutatx1 ,         /* （連携用）一時払増額加算募集手当＿１ */
     zrnitjbrzugkksnbsyutatx2 ,         /* （連携用）一時払増額加算募集手当＿２ */
     zrnitibitjbrksnbsyutat ,         /* （連携用）一部一時払加算募集手当 */
     zrnjyunkensuu ,         /* （連携用）純件数 */
     zrnkansankensuu ,         /* （連携用）換算件数 */
     zrnitibuitijibaraikikan ,         /* （連携用）一部一時払期間 */
     zrnitibuitijibarais ,         /* （連携用）一部一時払Ｓ */
     zrnitibuitijibaraip ,         /* （連携用）一部一時払Ｐ */
     zrnitibitjbrsdtpdtkbn ,         /* （連携用）一部一時払Ｓ建Ｐ建区分 */
     zrnitibuitijibaraisyuuseis ,         /* （連携用）一部一時払修正Ｓ */
     zrnitibitjbrmodsskgnhyj ,         /* （連携用）一部一時払修正Ｓ削減表示 */
     zrnsuuriyousyoriym ,         /* （連携用）数理用処理年月 */
     zrnsyosinsinsahouhoukbn ,         /* （連携用）初診診査方法区分 */
     zrnsaisinsinsahouhoukbn ,         /* （連携用）再診診査方法区分 */
     zrnseizonmrtisyuruikgu ,         /* （連携用）生存マル定種類記号 */
     zrnseizonmaruteikikan ,         /* （連携用）生存マル定期間 */
     zrnseizonmrtiphrkkkn ,         /* （連携用）生存マル定Ｐ払込期間 */
     zrnseizonmaruteis ,         /* （連携用）生存マル定Ｓ */
     zrnseizonmaruteip ,         /* （連携用）生存マル定Ｐ */
     zrnseizonmaruteisyuuseis ,         /* （連携用）生存マル定修正Ｓ */
     zrnseizonmrtimodsskgnhyj ,         /* （連携用）生存マル定修正Ｓ削減表示 */
     zrnsiznmrtitkjyukbn ,         /* （連携用）生存マル定特条区分 */
     zrnsiznmrtitkjyuskgnkkn ,         /* （連携用）生存マル定特条削減期間 */
     zrnsiznmrtitkjyuryumshyutn ,         /* （連携用）生存マル定特条料増標点 */
     zrnsiznmrtitkjyup ,         /* （連携用）生存マル定特条Ｐ */
     zrnsiznmrtiskyuksgk ,         /* （連携用）生存マル定支給基礎額 */
     zrnhtnknkyksiznmrtsyrikgux1 ,         /* （連携用）被転換契約生存マル定種類記号＿１ */
     zrnhtnknkyksiznmrtsyrikgux2 ,         /* （連携用）被転換契約生存マル定種類記号＿２ */
     zrnhtnknkyksiznmrtsyrikgux3 ,         /* （連携用）被転換契約生存マル定種類記号＿３ */
     zrnhtnknkyksiznmrtsyrikgux4 ,         /* （連携用）被転換契約生存マル定種類記号＿４ */
     zrnhtnknkyksiznmrtsyrikgux5 ,         /* （連携用）被転換契約生存マル定種類記号＿５ */
     zrnhtnknkyksiznmrtsyrikgux6 ,         /* （連携用）被転換契約生存マル定種類記号＿６ */
     zrnsuryusiznmrtipwrbkkbn ,         /* （連携用）数理用生存マル定Ｐ割引区分 */
     zrnsiznmrtipwrbkkbn ,         /* （連携用）生存マル定Ｐ割引区分 */
     zrnsiznmrtitnknyugukbn ,         /* （連携用）生存マル定転換優遇区分 */
     zrnseizonmrtikgusdkbn ,         /* （連携用）生存マル定記号世代区分 */
     zrnyobiv1 ,         /* （連携用）予備項目Ｖ１ */
     zrndai2hihokensyamei ,         /* （連携用）第２被保険者名 */
     zrndai2kanjihihokensyamei ,         /* （連携用）第２漢字被保険者名 */
     zrndai2hihokensyaseiymd ,         /* （連携用）第２被保険者生年月日 */
     zrndai2hihokensyaseibetukbn ,         /* （連携用）第２被保険者性別区分 */
     zrndai2hihknsyahnskhkncd ,         /* （連携用）第２被保険者本籍府県コード */
     zrndai2hhknnen ,         /* （連携用）第２被保険者年令 */
     zrndai2hihknsyakikykarihyj ,         /* （連携用）第２被保険者既契約有表示 */
     zrnkyksydi2hihknsyaduithyj ,         /* （連携用）契約者第２被保険者同一表示 */
     zrndai2syosinsinsahouhoukbn ,         /* （連携用）第２初診診査方法区分 */
     zrndai2saisinsinsahouhoukbn ,         /* （連携用）第２再診診査方法区分 */
     zrndai2syokugyoucd ,         /* （連携用）第２職業コード */
     zrndai2sakugenkikan ,         /* （連携用）第２削減期間 */
     zrndai2ryoumasihyouten ,         /* （連携用）第２料増標点 */
     zrnmrtidi2skgnkkn ,         /* （連携用）マル定第２削減期間 */
     zrnmrtidi2ryumshyutn ,         /* （連携用）マル定第２料増標点 */
     zrndi2kykkknnsyrikbn ,         /* （連携用）第２契約確認種類区分 */
     zrntignmrtidi2skgnkkn ,         /* （連携用）逓減マル定第２削減期間 */
     zrntignmrtidi2ryumshyutn ,         /* （連携用）逓減マル定第２料増標点 */
     zrndai2syosinhonninkknnkbn ,         /* （連携用）第２初診本人確認区分 */
     zrndi2sisnhonninkknnkbn ,         /* （連携用）第２再診本人確認区分 */
     zrnyobiv9x6 ,         /* （連携用）予備項目Ｖ９＿６ */
     zrndi2syugitkyksyrikgu ,         /* （連携用）第２傷害特約種類記号 */
     zrndai2syougaitokuyakukikan ,         /* （連携用）第２傷害特約期間 */
     zrndi2syugitkykphrkkkn ,         /* （連携用）第２傷害特約Ｐ払込期間 */
     zrndai2syougaitokuyakus ,         /* （連携用）第２傷害特約Ｓ */
     zrndai2syougaitokuyakup ,         /* （連携用）第２傷害特約Ｐ */
     zrndi2syugitkykgtkbn ,         /* （連携用）第２傷害特約型区分 */
     zrndi2syugitkykkgusdkbn ,         /* （連携用）第２傷害特約記号世代区分 */
     zrndi2syugitkykpwrbkkbn ,         /* （連携用）第２傷害特約Ｐ割引区分 */
     zrnyobiv8 ,         /* （連携用）予備項目Ｖ８ */
     zrndi2sigiwrmstkyksyrikgu ,         /* （連携用）第２災害割増特約種類記号 */
     zrndi2sigiwrmstkykkkn ,         /* （連携用）第２災害割増特約期間 */
     zrndi2sigiwrmstkykphrkkkn ,         /* （連携用）第２災害割増特約Ｐ払込期間 */
     zrndi2sigiwrmstkyks ,         /* （連携用）第２災害割増特約Ｓ */
     zrndi2sigiwrmstkykp ,         /* （連携用）第２災害割増特約Ｐ */
     zrndi2sigiwrmstkykkgusdkbn ,         /* （連携用）第２災害割増特約記号世代区分 */
     zrndi2sigiwrmstkykpwrbkkbn ,         /* （連携用）第２災害割増特約Ｐ割引区分 */
     zrnyobiv9x7 ,         /* （連携用）予備項目Ｖ９＿７ */
     zrndi2siginyuintkyksyrikgu ,         /* （連携用）第２災害入院特約種類記号 */
     zrndi2siginyuintkykkkn ,         /* （連携用）第２災害入院特約期間 */
     zrndi2siginyuintkykphrkkkn ,         /* （連携用）第２災害入院特約Ｐ払込期間 */
     zrndi2siginyuintkykntgk ,         /* （連携用）第２災害入院特約日額 */
     zrndi2siginyuintkykp ,         /* （連携用）第２災害入院特約Ｐ */
     zrndi2siginyuintkykgtkbn ,         /* （連携用）第２災害入院特約型区分 */
     zrndi2siginyintkykkgusdkbn ,         /* （連携用）第２災害入院特約記号世代区分 */
     zrndi2siginyuintkykpwrbkkbn ,         /* （連携用）第２災害入院特約Ｐ割引区分 */
     zrnyobiv10x3 ,         /* （連携用）予備項目Ｖ１０＿３ */
     zrndi2sppinyuintkyksyrikgu ,         /* （連携用）第２疾病入院特約種類記号 */
     zrndi2sppinyuintkykkkn ,         /* （連携用）第２疾病入院特約期間 */
     zrndi2sppinyuintkykphrkkkn ,         /* （連携用）第２疾病入院特約Ｐ払込期間 */
     zrndi2sppinyuintkykntgk ,         /* （連携用）第２疾病入院特約日額 */
     zrndi2sppinyuintkykp ,         /* （連携用）第２疾病入院特約Ｐ */
     zrndi2sppinyuintkykgtkbn ,         /* （連携用）第２疾病入院特約型区分 */
     zrndi2sppinyintkjyryumshytn ,         /* （連携用）第２疾病入院特条料増標点 */
     zrndi2sppinyuintkjyup ,         /* （連携用）第２疾病入院特条Ｐ */
     zrndi2sppinyuintktbicdx1 ,         /* （連携用）第２疾病入院特定部位コード＿１ */
     zrndi2sppinyuinhtnpkknx1 ,         /* （連携用）第２疾病入院不担保期間＿１ */
     zrndi2sppinyuintktbicdx2 ,         /* （連携用）第２疾病入院特定部位コード＿２ */
     zrndi2sppinyuinhtnpkknx2 ,         /* （連携用）第２疾病入院不担保期間＿２ */
     zrndi2sppinyintkykkgusdkbn ,         /* （連携用）第２疾病入院特約記号世代区分 */
     zrndi2sppinyuintkykpwrbkkbn ,         /* （連携用）第２疾病入院特約Ｐ割引区分 */
     zrnyobiv3x2 ,         /* （連携用）予備項目Ｖ３＿２ */
     zrndi2sijnbyutkyksyrikgu ,         /* （連携用）第２成人病特約種類記号 */
     zrndi2sijnbyutkykkkn ,         /* （連携用）第２成人病特約期間 */
     zrndi2sijnbyutkykphrkkkn ,         /* （連携用）第２成人病特約Ｐ払込期間 */
     zrndi2sijnbyutkykntgk ,         /* （連携用）第２成人病特約日額 */
     zrndai2seijinbyoutokuyakup ,         /* （連携用）第２成人病特約Ｐ */
     zrndi2sijnbyutkjyurymshytn ,         /* （連携用）第２成人病特条料増標点 */
     zrndai2seijinbyoutokujyoup ,         /* （連携用）第２成人病特条Ｐ */
     zrndi2sijnbyutktbicdx1 ,         /* （連携用）第２成人病特定部位コード＿１ */
     zrndi2sijnbyuhtnpkknx1 ,         /* （連携用）第２成人病不担保期間＿１ */
     zrndi2sijnbyutktbicdx2 ,         /* （連携用）第２成人病特定部位コード＿２ */
     zrndi2sijnbyuhtnpkknx2 ,         /* （連携用）第２成人病不担保期間＿２ */
     zrndi2sijnbyutkykkgusdkbn ,         /* （連携用）第２成人病特約記号世代区分 */
     zrndi2sijnbytkykgankyhgtkbn ,         /* （連携用）第２成人病特約ガン給付型区分 */
     zrndi2sijnbyutkykpwrbkkbn ,         /* （連携用）第２成人病特約Ｐ割引区分 */
     zrnyobiv3x3 ,         /* （連携用）予備項目Ｖ３＿３ */
     zrndai2jyoukentukihyouji ,         /* （連携用）第２条件付表示 */
     zrntignmrtisyukgu ,         /* （連携用）逓減マル定種類記号 */
     zrnteigenmaruteikikan ,         /* （連携用）逓減マル定期間 */
     zrnteigenmrtiphrkkkn ,         /* （連携用）逓減マル定Ｐ払込期間 */
     zrnteigenmaruteis ,         /* （連携用）逓減マル定Ｓ */
     zrnteigenmaruteip ,         /* （連携用）逓減マル定Ｐ */
     zrnteigenmaruteisyuuseis ,         /* （連携用）逓減マル定修正Ｓ */
     zrnteigenmrtimodssakugenhyj ,         /* （連携用）逓減マル定修正Ｓ削減表示 */
     zrntignmrtitkjyukbn ,         /* （連携用）逓減マル定特条区分 */
     zrntignmrtitkjyuskgnkkn ,         /* （連携用）逓減マル定特条削減期間 */
     zrntignmrtitkjyuryumshyutn ,         /* （連携用）逓減マル定特条料増標点 */
     zrntignmrtitkjyup ,         /* （連携用）逓減マル定特条Ｐ */
     zrntignmrtiskyuksgk ,         /* （連携用）逓減マル定支給基礎額 */
     zrnhtnknkyktignmrtsyrikgux1 ,         /* （連携用）被転換契約逓減マル定種類記号＿１ */
     zrnhtnknkyktignmrtsyrikgux2 ,         /* （連携用）被転換契約逓減マル定種類記号＿２ */
     zrnhtnknkyktignmrtsyrikgux3 ,         /* （連携用）被転換契約逓減マル定種類記号＿３ */
     zrnhtnknkyktignmrtsyrikgux4 ,         /* （連携用）被転換契約逓減マル定種類記号＿４ */
     zrnhtnknkyktignmrtsyrikgux5 ,         /* （連携用）被転換契約逓減マル定種類記号＿５ */
     zrnhtnknkyktignmrtsyrikgux6 ,         /* （連携用）被転換契約逓減マル定種類記号＿６ */
     zrnsuryutignmrtipwrbkkbn ,         /* （連携用）数理用逓減マル定Ｐ割引区分 */
     zrntignmrtipwrbkkbn ,         /* （連携用）逓減マル定Ｐ割引区分 */
     zrntignmrtitnknyugukbn ,         /* （連携用）逓減マル定転換優遇区分 */
     zrnteigenmrtikgusdkbn ,         /* （連携用）逓減マル定記号世代区分 */
     zrnyobiv1x2 ,         /* （連携用）予備項目Ｖ１＿２ */
     zrntktsppisetkykkbn ,         /* （連携用）特定疾病セット契約区分 */
     zrnjyudmnsiskknsetkykkbn ,         /* （連携用）重度慢性疾患セット契約区分 */
     zrnyobiv8x2 ,         /* （連携用）予備項目Ｖ８＿２ */
     zrnsetaitesyono1 ,         /* （連携用）セット相手証券番号１ */
     zrnsetaitehokensyuruikigou1 ,         /* （連携用）セット相手保険種類記号１ */
     zrnsetaitemrtisyuruikgu1 ,         /* （連携用）セット相手マル定種類記号１ */
     zrnsetaitesiznmrtisyurui1 ,         /* （連携用）セット相手生存マル定種類１ */
     zrnsetaitetignmrtisyurui1 ,         /* （連携用）セット相手逓減マル定種類１ */
     zrnsetaitekihonbubuns1 ,         /* （連携用）セット相手基本部分Ｓ１ */
     zrnsetgukitnknitjbrkhns1 ,         /* （連携用）セット合計転換一時払基本Ｓ１ */
     zrnsetaitesibous1 ,         /* （連携用）セット相手死亡Ｓ１ */
     zrnsetgukitnknitjbrsbus1 ,         /* （連携用）セット合計転換一時払死亡Ｓ１ */
     zrnsetaitesyuuseis1 ,         /* （連携用）セット相手修正Ｓ１ */
     zrnsetaiteharaikomip1 ,         /* （連携用）セット相手払込Ｐ１ */
     zrnsetaitesyukeiyakububunp1 ,         /* （連携用）セット相手主契約部分Ｐ１ */
     zrnsetaitgukikzkmrtis1 ,         /* （連携用）セット相手合計家族マル定Ｓ１ */
     zrnsetaitetenkankykhyj1 ,         /* （連携用）セット相手転換契約表示１ */
     zrnsetaitesiteimhrkp1 ,         /* （連携用）セット相手指定月払込Ｐ１ */
     zrnsetaitesiteimsykykp1 ,         /* （連携用）セット相手指定月主契約Ｐ１ */
     zrnsetaitenkmrtisyurui1 ,         /* （連携用）セット相手年金マル定種類１ */
     zrnyobiv18           /* （連携用）予備項目Ｖ１８ */
FROM ZT_Sp2RnduyuSouseiritu1Rn_Z;