CREATE VIEW ZT_YuukouseiNgTuutiRn AS SELECT
     zrnsyoruicd ,         /* （連携用）書類コード */
     zrnhassoukbn ,         /* （連携用）発送区分 */
     zrntyouhyouymd ,         /* （連携用）帳票作成日 */
     zrntyouhyouymdkj ,         /* （連携用）帳票作成日（漢字） */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnyobiv9 ,         /* （連携用）予備項目Ｖ９ */
     zrnansyuyouyobin10 ,         /* （連携用）案内収納用予備項目Ｎ１０ */
     zrnshskyno ,         /* （連携用）送付先郵便番号 */
     zrnshskadr1kj ,         /* （連携用）送付先住所１（漢字） */
     zrnshskadr2kj ,         /* （連携用）送付先住所２（漢字） */
     zrnshskadr3kj ,         /* （連携用）送付先住所３（漢字） */
     zrnshsnmkj ,         /* （連携用）送付先名（漢字） */
     zrnyobiv43 ,         /* （連携用）予備項目Ｖ４３ */
     zrnansyuyouyobin10x2 ,         /* （連携用）案内収納用予備項目Ｎ１０＿２ */
     zrntawsosikikj ,         /* （連携用）問合せ先組織名（漢字） */
     zrntawyno ,         /* （連携用）問合せ先郵便番号 */
     zrntawadr1kj ,         /* （連携用）問合せ先住所１（漢字） */
     zrntawadr2kj ,         /* （連携用）問合せ先住所２（漢字） */
     zrntawadr3kj ,         /* （連携用）問合せ先住所３（漢字） */
     zrntawtelnov14 ,         /* （連携用）問合せ先電話番号Ｖ１４ */
     zrntawteluktkkanou1 ,         /* （連携用）問合せ先電話受付可能時間１ */
     zrntawteluktkkanou2 ,         /* （連携用）問合せ先電話受付可能時間２ */
     zrndai2tawsosikinmkj ,         /* （連携用）第２問合せ先組織名（漢字） */
     zrndai2tawtelno ,         /* （連携用）第２問合せ先電話番号 */
     zrnyobiv62 ,         /* （連携用）予備項目Ｖ６２ */
     zrnansyuyouyobin10x3 ,         /* （連携用）案内収納用予備項目Ｎ１０＿３ */
     zrnosirasemongon46keta1 ,         /* （連携用）お知らせ文言（４６桁）１ */
     zrnosirasemongon46keta2 ,         /* （連携用）お知らせ文言（４６桁）２ */
     zrnosirasemongon46keta3 ,         /* （連携用）お知らせ文言（４６桁）３ */
     zrnosirasemongon46keta4 ,         /* （連携用）お知らせ文言（４６桁）４ */
     zrnosirasemongon46keta5 ,         /* （連携用）お知らせ文言（４６桁）５ */
     zrnosirasemongon46keta6 ,         /* （連携用）お知らせ文言（４６桁）６ */
     zrnosirasemongon46keta7 ,         /* （連携用）お知らせ文言（４６桁）７ */
     zrnosirasemongon46keta8 ,         /* （連携用）お知らせ文言（４６桁）８ */
     zrnosirasemongon46keta9 ,         /* （連携用）お知らせ文言（４６桁）９ */
     zrnosirasemongon46keta10 ,         /* （連携用）お知らせ文言（４６桁）１０ */
     zrnyobiv184 ,         /* （連携用）予備項目Ｖ１８４ */
     zrnansyuyouyobin10x4 ,         /* （連携用）案内収納用予備項目Ｎ１０＿４ */
     zrnkyknmkj ,         /* （連携用）契約者名（漢字） */
     zrnpkngk ,         /* （連携用）保険料金額 */
     zrncreditcardinfo1 ,         /* （連携用）クレジットカード情報１ */
     zrncreditcardinfo2 ,         /* （連携用）クレジットカード情報２ */
     zrncreditcardinfo3 ,         /* （連携用）クレジットカード情報３ */
     zrncreditcardmaskingmsg ,         /* （連携用）クレジットカードマスキングＭＳＧ */
     zrngoiraijikoutoumongon1 ,         /* （連携用）ご依頼事項等文言１ */
     zrngoiraijikoutoumongon2 ,         /* （連携用）ご依頼事項等文言２ */
     zrngoiraijikoutoumongon3 ,         /* （連携用）ご依頼事項等文言３ */
     zrnphrkmongon1 ,         /* （連携用）保険料のお払込み文言１ */
     zrnphrkmongon2 ,         /* （連携用）保険料のお払込み文言２ */
     zrnphrkmongon3 ,         /* （連携用）保険料のお払込み文言３ */
     zrnphrkmongon4 ,         /* （連携用）保険料のお払込み文言４ */
     zrnphrkmongon5 ,         /* （連携用）保険料のお払込み文言５ */
     zrnphrkmongon6 ,         /* （連携用）保険料のお払込み文言６ */
     zrnphrkmongon7 ,         /* （連携用）保険料のお払込み文言７ */
     zrnphrkmongon8 ,         /* （連携用）保険料のお払込み文言８ */
     zrnphrkmongon9 ,         /* （連携用）保険料のお払込み文言９ */
     zrnyobiv17 ,         /* （連携用）予備項目Ｖ１７ */
     zrnyobiv250 ,         /* （連携用）予備項目Ｖ２５０ */
     zrnansyuyouyobin10x5           /* （連携用）案内収納用予備項目Ｎ１０＿５ */
FROM ZT_YuukouseiNgTuutiRn_Z;