CREATE VIEW ZT_RisaHitSyouhnyouRatedRn AS SELECT
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnyoteiriritu ,         /* （連携用）予定利率 */
     zrnpmenkbn ,         /* （連携用）Ｐ免区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhhknsei ,         /* （連携用）被保険者性別 */
     zrnkeiyakujihhknnen ,         /* （連携用）契約時被保険者年令 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrndnendo ,         /* （連携用）Ｄ年度 */
     zrnnaiteikakuteikbn ,         /* （連携用）Ｄレート内定確定区分 */
     zrndrate00 ,         /* （連携用）Ｄレート００ */
     zrndrate01 ,         /* （連携用）Ｄレート０１ */
     zrndrate02 ,         /* （連携用）Ｄレート０２ */
     zrndrate03 ,         /* （連携用）Ｄレート０３ */
     zrndrate04 ,         /* （連携用）Ｄレート０４ */
     zrndrate05 ,         /* （連携用）Ｄレート０５ */
     zrndrate06 ,         /* （連携用）Ｄレート０６ */
     zrndrate07 ,         /* （連携用）Ｄレート０７ */
     zrndrate08 ,         /* （連携用）Ｄレート０８ */
     zrndrate09 ,         /* （連携用）Ｄレート０９ */
     zrndrate10 ,         /* （連携用）Ｄレート１０ */
     zrndrate11 ,         /* （連携用）Ｄレート１１ */
     zrndrate12 ,         /* （連携用）Ｄレート１２ */
     zrndrate13 ,         /* （連携用）Ｄレート１３ */
     zrndrate14 ,         /* （連携用）Ｄレート１４ */
     zrndrate15 ,         /* （連携用）Ｄレート１５ */
     zrndrate16 ,         /* （連携用）Ｄレート１６ */
     zrndrate17 ,         /* （連携用）Ｄレート１７ */
     zrndrate18 ,         /* （連携用）Ｄレート１８ */
     zrndrate19 ,         /* （連携用）Ｄレート１９ */
     zrndrate20 ,         /* （連携用）Ｄレート２０ */
     zrndrate21 ,         /* （連携用）Ｄレート２１ */
     zrndrate22 ,         /* （連携用）Ｄレート２２ */
     zrndrate23 ,         /* （連携用）Ｄレート２３ */
     zrndrate24 ,         /* （連携用）Ｄレート２４ */
     zrndrate25 ,         /* （連携用）Ｄレート２５ */
     zrndrate26 ,         /* （連携用）Ｄレート２６ */
     zrndrate27 ,         /* （連携用）Ｄレート２７ */
     zrndrate28 ,         /* （連携用）Ｄレート２８ */
     zrndrate29 ,         /* （連携用）Ｄレート２９ */
     zrndrate30 ,         /* （連携用）Ｄレート３０ */
     zrndrate31 ,         /* （連携用）Ｄレート３１ */
     zrndrate32 ,         /* （連携用）Ｄレート３２ */
     zrndrate33 ,         /* （連携用）Ｄレート３３ */
     zrndrate34 ,         /* （連携用）Ｄレート３４ */
     zrndrate35 ,         /* （連携用）Ｄレート３５ */
     zrndrate36 ,         /* （連携用）Ｄレート３６ */
     zrndrate37 ,         /* （連携用）Ｄレート３７ */
     zrndrate38 ,         /* （連携用）Ｄレート３８ */
     zrndrate39 ,         /* （連携用）Ｄレート３９ */
     zrndrate40 ,         /* （連携用）Ｄレート４０ */
     zrndrate41 ,         /* （連携用）Ｄレート４１ */
     zrndrate42 ,         /* （連携用）Ｄレート４２ */
     zrndrate43 ,         /* （連携用）Ｄレート４３ */
     zrndrate44 ,         /* （連携用）Ｄレート４４ */
     zrndrate45 ,         /* （連携用）Ｄレート４５ */
     zrndrate46 ,         /* （連携用）Ｄレート４６ */
     zrndrate47 ,         /* （連携用）Ｄレート４７ */
     zrndrate48 ,         /* （連携用）Ｄレート４８ */
     zrndrate49 ,         /* （連携用）Ｄレート４９ */
     zrndrate50 ,         /* （連携用）Ｄレート５０ */
     zrndrate51 ,         /* （連携用）Ｄレート５１ */
     zrndrate52 ,         /* （連携用）Ｄレート５２ */
     zrndrate53 ,         /* （連携用）Ｄレート５３ */
     zrndrate54 ,         /* （連携用）Ｄレート５４ */
     zrndrate55 ,         /* （連携用）Ｄレート５５ */
     zrndrate56 ,         /* （連携用）Ｄレート５６ */
     zrndrate57 ,         /* （連携用）Ｄレート５７ */
     zrndrate58 ,         /* （連携用）Ｄレート５８ */
     zrndrate59 ,         /* （連携用）Ｄレート５９ */
     zrndrate60 ,         /* （連携用）Ｄレート６０ */
     zrndrate61 ,         /* （連携用）Ｄレート６１ */
     zrndrate62 ,         /* （連携用）Ｄレート６２ */
     zrndrate63 ,         /* （連携用）Ｄレート６３ */
     zrndrate64 ,         /* （連携用）Ｄレート６４ */
     zrndrate65 ,         /* （連携用）Ｄレート６５ */
     zrndrate66 ,         /* （連携用）Ｄレート６６ */
     zrndrate67 ,         /* （連携用）Ｄレート６７ */
     zrndrate68 ,         /* （連携用）Ｄレート６８ */
     zrndrate69 ,         /* （連携用）Ｄレート６９ */
     zrndrate70 ,         /* （連携用）Ｄレート７０ */
     zrndrate71 ,         /* （連携用）Ｄレート７１ */
     zrndrate72 ,         /* （連携用）Ｄレート７２ */
     zrndrate73 ,         /* （連携用）Ｄレート７３ */
     zrndrate74 ,         /* （連携用）Ｄレート７４ */
     zrndrate75 ,         /* （連携用）Ｄレート７５ */
     zrndrate76 ,         /* （連携用）Ｄレート７６ */
     zrndrate77 ,         /* （連携用）Ｄレート７７ */
     zrndrate78 ,         /* （連携用）Ｄレート７８ */
     zrndrate79 ,         /* （連携用）Ｄレート７９ */
     zrndrate80 ,         /* （連携用）Ｄレート８０ */
     zrndrate81 ,         /* （連携用）Ｄレート８１ */
     zrndrate82 ,         /* （連携用）Ｄレート８２ */
     zrndrate83 ,         /* （連携用）Ｄレート８３ */
     zrndrate84 ,         /* （連携用）Ｄレート８４ */
     zrndrate85 ,         /* （連携用）Ｄレート８５ */
     zrndrate86 ,         /* （連携用）Ｄレート８６ */
     zrndrate87 ,         /* （連携用）Ｄレート８７ */
     zrndrate88 ,         /* （連携用）Ｄレート８８ */
     zrndrate89 ,         /* （連携用）Ｄレート８９ */
     zrndrate90 ,         /* （連携用）Ｄレート９０ */
     zrndrate91 ,         /* （連携用）Ｄレート９１ */
     zrndrate92 ,         /* （連携用）Ｄレート９２ */
     zrndrate93 ,         /* （連携用）Ｄレート９３ */
     zrndrate94 ,         /* （連携用）Ｄレート９４ */
     zrndrate95 ,         /* （連携用）Ｄレート９５ */
     zrndrate96 ,         /* （連携用）Ｄレート９６ */
     zrndrate97 ,         /* （連携用）Ｄレート９７ */
     zrndrate98 ,         /* （連携用）Ｄレート９８ */
     zrndrate99 ,         /* （連携用）Ｄレート９９ */
     zrndyouvrate00 ,         /* （連携用）Ｄ用Ｖレート００ */
     zrndyouvrate01 ,         /* （連携用）Ｄ用Ｖレート０１ */
     zrndyouvrate02 ,         /* （連携用）Ｄ用Ｖレート０２ */
     zrndyouvrate03 ,         /* （連携用）Ｄ用Ｖレート０３ */
     zrndyouvrate04 ,         /* （連携用）Ｄ用Ｖレート０４ */
     zrndyouvrate05 ,         /* （連携用）Ｄ用Ｖレート０５ */
     zrndyouvrate06 ,         /* （連携用）Ｄ用Ｖレート０６ */
     zrndyouvrate07 ,         /* （連携用）Ｄ用Ｖレート０７ */
     zrndyouvrate08 ,         /* （連携用）Ｄ用Ｖレート０８ */
     zrndyouvrate09 ,         /* （連携用）Ｄ用Ｖレート０９ */
     zrndyouvrate10 ,         /* （連携用）Ｄ用Ｖレート１０ */
     zrndyouvrate11 ,         /* （連携用）Ｄ用Ｖレート１１ */
     zrndyouvrate12 ,         /* （連携用）Ｄ用Ｖレート１２ */
     zrndyouvrate13 ,         /* （連携用）Ｄ用Ｖレート１３ */
     zrndyouvrate14 ,         /* （連携用）Ｄ用Ｖレート１４ */
     zrndyouvrate15 ,         /* （連携用）Ｄ用Ｖレート１５ */
     zrndyouvrate16 ,         /* （連携用）Ｄ用Ｖレート１６ */
     zrndyouvrate17 ,         /* （連携用）Ｄ用Ｖレート１７ */
     zrndyouvrate18 ,         /* （連携用）Ｄ用Ｖレート１８ */
     zrndyouvrate19 ,         /* （連携用）Ｄ用Ｖレート１９ */
     zrndyouvrate20 ,         /* （連携用）Ｄ用Ｖレート２０ */
     zrndyouvrate21 ,         /* （連携用）Ｄ用Ｖレート２１ */
     zrndyouvrate22 ,         /* （連携用）Ｄ用Ｖレート２２ */
     zrndyouvrate23 ,         /* （連携用）Ｄ用Ｖレート２３ */
     zrndyouvrate24 ,         /* （連携用）Ｄ用Ｖレート２４ */
     zrndyouvrate25 ,         /* （連携用）Ｄ用Ｖレート２５ */
     zrndyouvrate26 ,         /* （連携用）Ｄ用Ｖレート２６ */
     zrndyouvrate27 ,         /* （連携用）Ｄ用Ｖレート２７ */
     zrndyouvrate28 ,         /* （連携用）Ｄ用Ｖレート２８ */
     zrndyouvrate29 ,         /* （連携用）Ｄ用Ｖレート２９ */
     zrndyouvrate30 ,         /* （連携用）Ｄ用Ｖレート３０ */
     zrndyouvrate31 ,         /* （連携用）Ｄ用Ｖレート３１ */
     zrndyouvrate32 ,         /* （連携用）Ｄ用Ｖレート３２ */
     zrndyouvrate33 ,         /* （連携用）Ｄ用Ｖレート３３ */
     zrndyouvrate34 ,         /* （連携用）Ｄ用Ｖレート３４ */
     zrndyouvrate35 ,         /* （連携用）Ｄ用Ｖレート３５ */
     zrndyouvrate36 ,         /* （連携用）Ｄ用Ｖレート３６ */
     zrndyouvrate37 ,         /* （連携用）Ｄ用Ｖレート３７ */
     zrndyouvrate38 ,         /* （連携用）Ｄ用Ｖレート３８ */
     zrndyouvrate39 ,         /* （連携用）Ｄ用Ｖレート３９ */
     zrndyouvrate40 ,         /* （連携用）Ｄ用Ｖレート４０ */
     zrndyouvrate41 ,         /* （連携用）Ｄ用Ｖレート４１ */
     zrndyouvrate42 ,         /* （連携用）Ｄ用Ｖレート４２ */
     zrndyouvrate43 ,         /* （連携用）Ｄ用Ｖレート４３ */
     zrndyouvrate44 ,         /* （連携用）Ｄ用Ｖレート４４ */
     zrndyouvrate45 ,         /* （連携用）Ｄ用Ｖレート４５ */
     zrndyouvrate46 ,         /* （連携用）Ｄ用Ｖレート４６ */
     zrndyouvrate47 ,         /* （連携用）Ｄ用Ｖレート４７ */
     zrndyouvrate48 ,         /* （連携用）Ｄ用Ｖレート４８ */
     zrndyouvrate49 ,         /* （連携用）Ｄ用Ｖレート４９ */
     zrndyouvrate50 ,         /* （連携用）Ｄ用Ｖレート５０ */
     zrndyouvrate51 ,         /* （連携用）Ｄ用Ｖレート５１ */
     zrndyouvrate52 ,         /* （連携用）Ｄ用Ｖレート５２ */
     zrndyouvrate53 ,         /* （連携用）Ｄ用Ｖレート５３ */
     zrndyouvrate54 ,         /* （連携用）Ｄ用Ｖレート５４ */
     zrndyouvrate55 ,         /* （連携用）Ｄ用Ｖレート５５ */
     zrndyouvrate56 ,         /* （連携用）Ｄ用Ｖレート５６ */
     zrndyouvrate57 ,         /* （連携用）Ｄ用Ｖレート５７ */
     zrndyouvrate58 ,         /* （連携用）Ｄ用Ｖレート５８ */
     zrndyouvrate59 ,         /* （連携用）Ｄ用Ｖレート５９ */
     zrndyouvrate60 ,         /* （連携用）Ｄ用Ｖレート６０ */
     zrndyouvrate61 ,         /* （連携用）Ｄ用Ｖレート６１ */
     zrndyouvrate62 ,         /* （連携用）Ｄ用Ｖレート６２ */
     zrndyouvrate63 ,         /* （連携用）Ｄ用Ｖレート６３ */
     zrndyouvrate64 ,         /* （連携用）Ｄ用Ｖレート６４ */
     zrndyouvrate65 ,         /* （連携用）Ｄ用Ｖレート６５ */
     zrndyouvrate66 ,         /* （連携用）Ｄ用Ｖレート６６ */
     zrndyouvrate67 ,         /* （連携用）Ｄ用Ｖレート６７ */
     zrndyouvrate68 ,         /* （連携用）Ｄ用Ｖレート６８ */
     zrndyouvrate69 ,         /* （連携用）Ｄ用Ｖレート６９ */
     zrndyouvrate70 ,         /* （連携用）Ｄ用Ｖレート７０ */
     zrndyouvrate71 ,         /* （連携用）Ｄ用Ｖレート７１ */
     zrndyouvrate72 ,         /* （連携用）Ｄ用Ｖレート７２ */
     zrndyouvrate73 ,         /* （連携用）Ｄ用Ｖレート７３ */
     zrndyouvrate74 ,         /* （連携用）Ｄ用Ｖレート７４ */
     zrndyouvrate75 ,         /* （連携用）Ｄ用Ｖレート７５ */
     zrndyouvrate76 ,         /* （連携用）Ｄ用Ｖレート７６ */
     zrndyouvrate77 ,         /* （連携用）Ｄ用Ｖレート７７ */
     zrndyouvrate78 ,         /* （連携用）Ｄ用Ｖレート７８ */
     zrndyouvrate79 ,         /* （連携用）Ｄ用Ｖレート７９ */
     zrndyouvrate80 ,         /* （連携用）Ｄ用Ｖレート８０ */
     zrndyouvrate81 ,         /* （連携用）Ｄ用Ｖレート８１ */
     zrndyouvrate82 ,         /* （連携用）Ｄ用Ｖレート８２ */
     zrndyouvrate83 ,         /* （連携用）Ｄ用Ｖレート８３ */
     zrndyouvrate84 ,         /* （連携用）Ｄ用Ｖレート８４ */
     zrndyouvrate85 ,         /* （連携用）Ｄ用Ｖレート８５ */
     zrndyouvrate86 ,         /* （連携用）Ｄ用Ｖレート８６ */
     zrndyouvrate87 ,         /* （連携用）Ｄ用Ｖレート８７ */
     zrndyouvrate88 ,         /* （連携用）Ｄ用Ｖレート８８ */
     zrndyouvrate89 ,         /* （連携用）Ｄ用Ｖレート８９ */
     zrndyouvrate90 ,         /* （連携用）Ｄ用Ｖレート９０ */
     zrndyouvrate91 ,         /* （連携用）Ｄ用Ｖレート９１ */
     zrndyouvrate92 ,         /* （連携用）Ｄ用Ｖレート９２ */
     zrndyouvrate93 ,         /* （連携用）Ｄ用Ｖレート９３ */
     zrndyouvrate94 ,         /* （連携用）Ｄ用Ｖレート９４ */
     zrndyouvrate95 ,         /* （連携用）Ｄ用Ｖレート９５ */
     zrndyouvrate96 ,         /* （連携用）Ｄ用Ｖレート９６ */
     zrndyouvrate97 ,         /* （連携用）Ｄ用Ｖレート９７ */
     zrndyouvrate98 ,         /* （連携用）Ｄ用Ｖレート９８ */
     zrndyouvrate99           /* （連携用）Ｄ用Ｖレート９９ */
FROM ZT_RisaHitSyouhnyouRatedRn_Z;