CREATE VIEW ZT_SmbcPaperlessMos1Tr AS SELECT
     ztrseihowebidkbn ,         /* （取込用）生保ＷｅｂＩＤ区分 */
     ztrseihowebkojincd ,         /* （取込用）生保Ｗｅｂ個人コード */
     ztrseihowebitijihozonhyouji ,         /* （取込用）生保Ｗｅｂ一時保存表示 */
     ztrseihowebseknoc ,         /* （取込用）生保Ｗｅｂ設計書番号Ｃ */
     ztrseihowebcalckijyunymdc ,         /* （取込用）生保Ｗｅｂ計算基準年月日Ｃ */
     ztrseihowebhhknknnm ,         /* （取込用）生保Ｗｅｂ被保険者カナ氏名 */
     ztrseihowebhhknseiymdc ,         /* （取込用）生保Ｗｅｂ被保険者生年月日Ｃ */
     ztrseihowebhhknseikbn ,         /* （取込用）生保Ｗｅｂ被保険者性別区分 */
     ztrseihowebkykknnm ,         /* （取込用）生保Ｗｅｂ契約者カナ氏名 */
     ztrseihowebkyksyaseiymdc ,         /* （取込用）生保Ｗｅｂ契約者生年月日Ｃ */
     ztrseihowebkyksyaseikbn ,         /* （取込用）生保Ｗｅｂ契約者性別区分 */
     ztrseihowebhknsyuruinoc ,         /* （取込用）生保Ｗｅｂ保険種類番号Ｃ */
     ztrseihowebhknkknc ,         /* （取込用）生保Ｗｅｂ保険期間Ｃ */
     ztrseihowebphrkkiknc ,         /* （取込用）生保ＷｅｂＰ払込期間Ｃ */
     ztrseihowebhrkkaisuukbn ,         /* （取込用）生保Ｗｅｂ払込回数区分 */
     ztrseihowebsdpdkbn ,         /* （取込用）生保ＷｅｂＳ建Ｐ建区分 */
     ztrseihowebkihonsc ,         /* （取込用）生保Ｗｅｂ基本ＳＣ */
     ztrseihowebnksyuruikbn ,         /* （取込用）生保Ｗｅｂ年金種類区分 */
     ztrseihoweblntkkbn ,         /* （取込用）生保ＷｅｂＬＮ特約区分 */
     ztrseihowebnkshrarihyj ,         /* （取込用）生保Ｗｅｂ年金支払特約有表示 */
     ztrseihowebmosnoc ,         /* （取込用）生保Ｗｅｂ申込番号Ｃ */
     ztrseihowebsekykkigenymdc ,         /* （取込用）生保Ｗｅｂ設計書有効期限年月日Ｃ */
     ztrseihowebsksjsitencd ,         /* （取込用）生保Ｗｅｂ作成時支店コード */
     ztrseihowebfstmossksymdc ,         /* （取込用）生保Ｗｅｂ初回申込書作成年月日Ｃ */
     ztrseihowebhnsyukyktdkkbn ,         /* （取込用）生保Ｗｅｂ編集後契約者続柄区分 */
     ztrseihowebhjnkitikbn ,         /* （取込用）生保Ｗｅｂ法人形態区分 */
     ztrseihowebhjnkykhyj ,         /* （取込用）生保Ｗｅｂ法人契約表示 */
     ztrseihowebtksykmcd1 ,         /* （取込用）生保Ｗｅｂ特殊項目コード１ */
     ztrseihowebtksykmcd2 ,         /* （取込用）生保Ｗｅｂ特殊項目コード２ */
     ztrseihowebtksykmcd3 ,         /* （取込用）生保Ｗｅｂ特殊項目コード３ */
     ztrseihowebtksykmcd4 ,         /* （取込用）生保Ｗｅｂ特殊項目コード４ */
     ztrseihowebtksykmcd5 ,         /* （取込用）生保Ｗｅｂ特殊項目コード５　 */
     ztrseihowebteiwkknc ,         /* （取込用）生保Ｗｅｂ低Ｗ期間Ｃ */
     ztrseihowebknhjnnm ,         /* （取込用）生保Ｗｅｂカナ法人名 */
     ztrseihowebkjhjnnm ,         /* （取込用）生保Ｗｅｂ漢字法人名 */
     ztrseihowebkndaihyounm ,         /* （取込用）生保Ｗｅｂカナ代表者名 */
     ztrseihowebkjdaihyounm ,         /* （取込用）生保Ｗｅｂ漢字代表者名 */
     ztrseihowebdaihyouktgkkbn ,         /* （取込用）生保Ｗｅｂ代表者肩書区分 */
     ztrseihowebsykihrkp1c ,         /* （取込用）生保Ｗｅｂ初回払込Ｐ１Ｃ */
     ztrseihowebmosp1c ,         /* （取込用）生保Ｗｅｂ申込Ｐ１Ｃ */
     ztrseihowebtkiyougyoutaikbn ,         /* （取込用）生保Ｗｅｂ統計用業態区分 */
     ztrseihowebzennoukknc ,         /* （取込用）生保Ｗｅｂ前納期間Ｃ */
     ztrseihowebpaperlessmoshyj ,         /* （取込用）生保Ｗｅｂペーパーレス申込表示 */
     ztrseihowebdatasousinzmhyj ,         /* （取込用）生保Ｗｅｂデータ送信済表示 */
     ztrseihowebkknmskhjnkitikbn ,         /* （取込用）生保Ｗｅｂ契勤務先法人形態区分 */
     ztrseihowebkykottmsk ,         /* （取込用）生保Ｗｅｂ契約者お勤め先 */
     ztrseihowebhhknsykgycd ,         /* （取込用）生保Ｗｅｂ被保険者職業コード */
     ztrseihowebhknmskhjnkitikbn ,         /* （取込用）生保Ｗｅｂ被勤務先法人形態区分 */
     ztrseihowebhhknottmsk ,         /* （取込用）生保Ｗｅｂ被保険者お勤め先 */
     ztrseihowebhhknnensyuukbn ,         /* （取込用）生保Ｗｅｂ被保険者年収区分 */
     ztrseihowebsbukthksuninzuuc ,         /* （取込用）生保Ｗｅｂ死亡受取人複数人数Ｃ */
     ztrseihowebsbuktbnwari1c ,         /* （取込用）生保Ｗｅｂ死亡受取人分割割合１Ｃ */
     ztrseihowebsbukttdkkbn2 ,         /* （取込用）生保Ｗｅｂ死亡受取人続柄区分２ */
     ztrseihowebsbuktknnm2 ,         /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名２ */
     ztrseihowebsbuktkjnm2 ,         /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名２ */
     ztrseihowebsbuktseiymd2c ,         /* （取込用）生保Ｗｅｂ死亡受取人生年月日２Ｃ */
     ztrseihowebsbuktbnwari2c ,         /* （取込用）生保Ｗｅｂ死亡受取人分割割合２Ｃ */
     ztrseihowebsbukttdkkbn3 ,         /* （取込用）生保Ｗｅｂ死亡受取人続柄区分３ */
     ztrseihowebsbuktknnm3 ,         /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名３ */
     ztrseihowebsbuktkjnm3 ,         /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名３ */
     ztrseihowebsbuktseiymd3c ,         /* （取込用）生保Ｗｅｂ死亡受取人生年月日３Ｃ */
     ztrseihowebsbuktbnwari3c ,         /* （取込用）生保Ｗｅｂ死亡受取人分割割合３Ｃ */
     ztrseihowebsbukttdkkbn4 ,         /* （取込用）生保Ｗｅｂ死亡受取人続柄区分４ */
     ztrseihowebsbuktknnm4 ,         /* （取込用）生保Ｗｅｂ死亡受取人カナ氏名４ */
     ztrseihowebsbuktkjnm4 ,         /* （取込用）生保Ｗｅｂ死亡受取人漢字氏名４ */
     ztrseihowebsbuktseiymd4c ,         /* （取込用）生保Ｗｅｂ死亡受取人生年月日４Ｃ */
     ztrseihowebsbuktbnwari4c ,         /* （取込用）生保Ｗｅｂ死亡受取人分割割合４Ｃ */
     ztrseihowebnkuktmrhhyj ,         /* （取込用）生保Ｗｅｂ年金受取人マル被表示 */
     ztrseihowebsbnkkknc ,         /* （取込用）生保Ｗｅｂ死亡年金期間Ｃ */
     ztrseihowebikokakkjarihyj ,         /* （取込用）生保Ｗｅｂ意向確認記事有表示 */
     ztrseihowebfatcasnsiarihyj ,         /* （取込用）生保ＷｅｂＦＡＴＣＡ宣誓有表示 */
     ztrseihowebkouhurisitencd ,         /* （取込用）生保Ｗｅｂ口振支店コード */
     ztrseihowebkouhuriyokinkbn ,         /* （取込用）生保Ｗｅｂ口振預金種目区分 */
     ztrseihowebkouhurikouzano ,         /* （取込用）生保Ｗｅｂ口振口座番号 */
     ztrseihowebkuhrshmnttdkhyj ,         /* （取込用）生保Ｗｅｂ口振書面手続表示 */
     ztrseihowebmosymdc ,         /* （取込用）生保Ｗｅｂ申込年月日Ｃ */
     ztrseihowebsyokugyoukktymdc ,         /* （取込用）生保Ｗｅｂ職業告知年月日Ｃ */
     ztrseihowebhhknsintyouc ,         /* （取込用）生保Ｗｅｂ被保険者身長Ｃ */
     ztrseihowebhhkntaijyuuc ,         /* （取込用）生保Ｗｅｂ被保険者体重Ｃ */
     ztrseihowebkktymdc ,         /* （取込用）生保Ｗｅｂ告知年月日Ｃ */
     ztrseihowebhukusuustskskbn ,         /* （取込用）生保Ｗｅｂ複数指定書作成区分 */
     ztrseihowebhnnkaksyoruikbn ,         /* （取込用）生保Ｗｅｂ本人確認書類区分 */
     ztrseihowebhsktkjikou ,         /* （取込用）生保Ｗｅｂ補足特定事項 */
     ztrseihowebskskaksyoruikbn ,         /* （取込用）生保Ｗｅｂ親権者確認書類区分 */
     ztrseihowebskshsktkjikou ,         /* （取込用）生保Ｗｅｂ親権者補足特定事項 */
     ztrseihowebbikkjnssinfoari ,         /* （取込用）生保Ｗｅｂ米国人示唆情報有表示 */
     ztrseihowebplbsyutrkno ,         /* （取込用）生保ＷｅｂＰＬ募集人登録番号 */
     ztrseihowebplbsyukouincd ,         /* （取込用）生保ＷｅｂＰＬ募集人行員コード */
     ztrseihowebnrkbsyutrkno ,         /* （取込用）生保Ｗｅｂ入力募集人登録番号 */
     ztrseihowebuktkid ,         /* （取込用）生保Ｗｅｂ受付管理ＩＤ */
     ztrseihowebdatasousinymdc ,         /* （取込用）生保Ｗｅｂデータ送信年月日Ｃ */
     ztrseihowebdatasousinhmsc ,         /* （取込用）生保Ｗｅｂデータ送信時分秒Ｃ */
     ztrseihowebmosuktkymdc ,         /* （取込用）生保Ｗｅｂ申込書受付年月日Ｃ */
     ztrseihowebhnnkakhskjk1 ,         /* （取込用）生保Ｗｅｂ本人確認補足事項欄１ */
     ztrseihowebhnnkakhskjk2 ,         /* （取込用）生保Ｗｅｂ本人確認補足事項欄２ */
     ztrseihowebhnnkakhskjk3 ,         /* （取込用）生保Ｗｅｂ本人確認補足事項欄３ */
     ztrseihowebhnnkakhskjk4 ,         /* （取込用）生保Ｗｅｂ本人確認補足事項欄４ */
     ztrseihowebhnnkakhskjk5 ,         /* （取込用）生保Ｗｅｂ本人確認補足事項欄５ */
     ztrseihowebtorihoutkjk1 ,         /* （取込用）生保Ｗｅｂ取報特記事項欄１ */
     ztrseihowebtorihoutkjk2 ,         /* （取込用）生保Ｗｅｂ取報特記事項欄２ */
     ztrseihowebtorihoutkjk3 ,         /* （取込用）生保Ｗｅｂ取報特記事項欄３ */
     ztrseihowebtorihoutkjk4 ,         /* （取込用）生保Ｗｅｂ取報特記事項欄４ */
     ztrseihowebtorihoutkjk5 ,         /* （取込用）生保Ｗｅｂ取報特記事項欄５ */
     ztrseihowebdrtnskno ,         /* （取込用）生保Ｗｅｂ代理店設計書番号 */
     ztrseihowebsbnksyukbn ,         /* （取込用）生保Ｗｅｂ死亡年金種類区分 */
     ztrseihowebaatkisyaknyuucd ,         /* （取込用）生保ＷｅｂＡ扱者金融機関コード */
     ztrseihowebkktttykknrhyj ,         /* （取込用）生保Ｗｅｂ告知書到着管理表示 */
     ztrseihowebdtlkktarihyj ,         /* （取込用）生保Ｗｅｂ詳細告知書有表示 */
     ztrseihowebfatcasyoruiari ,         /* （取込用）生保ＷｅｂＦＡＴＣＡ書類有表示 */
     ztrseihowebkzhurikaebankcd ,         /* （取込用）生保Ｗｅｂ口座振替銀行番号 */
     ztrseihowebkzkakiraikbn ,         /* （取込用）生保Ｗｅｂ口座確認依頼区分 */
     ztrseihowebbmierrorhyj ,         /* （取込用）生保ＷｅｂＢＭＩエラー表示 */
     ztrseihowebkktkmgituarihyj ,         /* （取込用）生保Ｗｅｂ告知項目該当有表示 */
     ztrseihowebsnshuhukbn ,         /* （取込用）生保Ｗｅｂ診査方法区分 */
     ztrseihowebkeihidouituhyj ,         /* （取込用）生保Ｗｅｂ契被同一表示 */
     ztrseihowebaeoisnsiarihyj ,         /* （取込用）生保ＷｅｂＡＥＯＩ宣誓有表示 */
     ztrseihowebsiteituukakbn ,         /* （取込用）生保Ｗｅｂ指定通貨区分 */
     ztrseihowebnykntuukakbn ,         /* （取込用）生保Ｗｅｂ入金通貨区分 */
     ztrseihowebtargettkarihyj ,         /* （取込用）生保Ｗｅｂターゲット特約有表示 */
     ztrseihowebtargettkkbn ,         /* （取込用）生保Ｗｅｂターゲット特約区分 */
     ztrseihowebtargettkmkhtc ,         /* （取込用）生保Ｗｅｂターゲット特約目標値Ｃ */
     ztrseihowebnykntuukanykngkc ,         /* （取込用）生保Ｗｅｂ入金通貨入金額Ｃ */
     ztrseihowebnykntukfsthrkpc ,         /* （取込用）生保Ｗｅｂ入金通貨初回払込ＰＣ */
     ztrseihowebnykntuknexthrkpc ,         /* （取込用）生保Ｗｅｂ入金通貨次回払込ＰＣ */
     ztrseihowebtargetyenknsnpc ,         /* （取込用）生保Ｗｅｂターゲット円換算ＰＣ */
     ztrseihowebtargetmkhgkc ,         /* （取込用）生保Ｗｅｂターゲット目標額Ｃ */
     ztrseihowebsaimankihyj ,         /* （取込用）生保Ｗｅｂ才満期表示 */
     ztrseihowebrayhyj ,         /* （取込用）生保ＷｅｂＲＡＹ表示 */
     ztryobiv156 ,         /* （取込用）予備項目Ｖ１５６ */
     ztrseihowebpsyouhyj ,         /* （取込用）生保ＷｅｂＰＳ要表示 */
     ztrseihowebplhhknkjnm ,         /* （取込用）生保ＷｅｂＰＬ被保険者漢字氏名 */
     ztryobiv1 ,         /* （取込用）予備項目Ｖ１ */
     ztrseihowebplkykkjnm ,         /* （取込用）生保ＷｅｂＰＬ契約者漢字氏名 */
     ztrseihowebplhjkktkbn ,         /* （取込用）生保ＷｅｂＰＬ報状告知区分 */
     ztrseihowebplhrkkeirokbn ,         /* （取込用）生保ＷｅｂＰＬ払込経路区分 */
     ztrseihowebplnkshrarihyj ,         /* （取込用）生保ＷｅｂＰＬ年金支払有表示 */
     ztryobiv2 ,         /* （取込用）予備項目Ｖ２ */
     ztrseihowebplmosnoc ,         /* （取込用）生保ＷｅｂＰＬ申込番号Ｃ */
     ztrseihowebplsbuktnrkkbn ,         /* （取込用）生保ＷｅｂＰＬ死亡受入力区分 */
     ztrseihowebplsbukttdkkbn ,         /* （取込用）生保ＷｅｂＰＬ死亡受続柄区分 */
     ztrseihowebplsbuktknnm ,         /* （取込用）生保ＷｅｂＰＬ死亡受カナ氏名 */
     ztrseihowebplsbuktkjnm ,         /* （取込用）生保ＷｅｂＰＬ死亡受漢字氏名 */
     ztryobiv3 ,         /* （取込用）予備項目Ｖ３ */
     ztrseihowebplsbuktseiymdc ,         /* （取込用）生保ＷｅｂＰＬ死亡受生年月日Ｃ */
     ztrseihowebpltksykmcd1 ,         /* （取込用）生保ＷｅｂＰＬ特殊項目コード１ */
     ztrseihowebpltksykmcd2 ,         /* （取込用）生保ＷｅｂＰＬ特殊項目コード２ */
     ztrseihowebpltksykmcd3 ,         /* （取込用）生保ＷｅｂＰＬ特殊項目コード３ */
     ztrseihowebpltksykmcd4 ,         /* （取込用）生保ＷｅｂＰＬ特殊項目コード４ */
     ztrseihowebpltksykmcd5 ,         /* （取込用）生保ＷｅｂＰＬ特殊項目コード５ */
     ztrseihowebplkyktelno ,         /* （取込用）生保ＷｅｂＰＬ契約者電話番号 */
     ztrseihowebplhhkntelno ,         /* （取込用）生保ＷｅｂＰＬ被保険者電話番号 */
     ztryobiv3x2 ,         /* （取込用）予備項目Ｖ３＿２ */
     ztrseihowebplkihontikucd ,         /* （取込用）生保ＷｅｂＰＬ基本地区コード */
     ztrseihowebpltsinadrkai ,         /* （取込用）生保ＷｅｂＰＬ通信先住所下位 */
     ztrseihowebplhiikihontikucd ,         /* （取込用）生保ＷｅｂＰＬ被基本地区コード */
     ztrseihowebplhhknadr ,         /* （取込用）生保ＷｅｂＰＬ被保険者住所 */
     ztrseihowebgnykntuknykngkc ,         /* （取込用）生保Ｗｅｂ外貨入金通貨入金額Ｃ */
     ztrseihowebgnykntukfsthrkpc ,         /* （取込用）生保Ｗｅｂ外貨入金通貨初回ＰＣ */
     ztrseihowebgnykntuknxthrkpc ,         /* （取込用）生保Ｗｅｂ外貨入金通貨次回ＰＣ */
     ztrseihowebgaikakihonpc ,         /* （取込用）生保Ｗｅｂ外貨基本ＰＣ */
     ztrseihowebkaigmehrtkarihyj ,         /* （取込用）生保Ｗｅｂ介護前払特約有表示 */
     ztrseihowebyenhsyutkarihyj ,         /* （取込用）生保Ｗｅｂ円最低保証特約有表示 */
     ztrseihowebgaikakihonsc ,         /* （取込用）生保Ｗｅｂ外貨基本ＳＣ */
     ztrseihowebdai1hknkknc ,         /* （取込用）生保Ｗｅｂ第１保険期間Ｃ */
     ztrseihowebdsmoshyj ,         /* （取込用）生保ＷｅｂＤＳ申込有表示 */
     ztrseihowebdsmailaddress ,         /* （取込用）生保ＷｅｂＤＳメールアドレス */
     ztrseihowebankenkanrino ,         /* （取込用）生保Ｗｅｂ案件管理番号 */
     ztrseihowebkydbosyuukjncd ,         /* （取込用）生保Ｗｅｂ共同募集個人コード */
     ztrseihowebhnyppltzmhyj ,         /* （取込用）生保Ｗｅｂ汎用ＰＰＬ対応済表示 */
     ztrseihowebssrndhbnwrc ,         /* （取込用）生保Ｗｅｂ指数連動部分配分割合Ｃ */
     ztrseihowebtrtrndhbnwrc ,         /* （取込用）生保Ｗｅｂ定率積立部分配分割合Ｃ */
     ztrseihowebsueokikknc ,         /* （取込用）生保Ｗｅｂ据置期間Ｃ */
     ztrseihowebmnkuktnrkkbn ,         /* （取込用）生保Ｗｅｂ満期受取人入力区分 */
     ztrseihowebmnkukttdkkbn ,         /* （取込用）生保Ｗｅｂ満期受取人続柄区分 */
     ztrseihowebmnkuktknnm ,         /* （取込用）生保Ｗｅｂ満期受取人カナ氏名 */
     ztrseihowebmnkuktkjnm ,         /* （取込用）生保Ｗｅｂ満期受取人漢字氏名 */
     ztrseihowebmnkuktseiymdc ,         /* （取込用）生保Ｗｅｂ満期受取人生年月日Ｃ */
     ztrseihowebdsknkzmeigi ,         /* （取込用）生保ＷｅｂＤＳカナ口座名義 */
     ztrseihowebdskzsyuruikbn ,         /* （取込用）生保ＷｅｂＤＳ口座種類区分 */
     ztrseihowebdskinyuucd ,         /* （取込用）生保ＷｅｂＤＳ金融機関コード */
     ztrseihowebdssitencd ,         /* （取込用）生保ＷｅｂＤＳ支店コード */
     ztrseihowebdsyokinkbn ,         /* （取込用）生保ＷｅｂＤＳ預金種目区分 */
     ztrseihowebdskouzano ,         /* （取込用）生保ＷｅｂＤＳ口座番号 */
     ztrseihowebdsansyono ,         /* （取込用）生保ＷｅｂＤＳ暗証番号 */
     ztrseihowebdssymnttdkhyj ,         /* （取込用）生保ＷｅｂＤＳ書面手続表示 */
     ztrseihowebikkatupc ,         /* （取込用）生保Ｗｅｂ一括払ＰＣ */
     ztrseihowebikkatubaraikbn ,         /* （取込用）生保Ｗｅｂ一括払区分 */
     ztrseihowebiktbrikaisuuc ,         /* （取込用）生保Ｗｅｂ一括払回数Ｃ */
     ztrseihowebzennoupc ,         /* （取込用）生保Ｗｅｂ前納ＰＣ */
     ztrseihowebgaikazennoupc ,         /* （取込用）生保Ｗｅｂ外貨前納ＰＣ */
     ztrseihowebzennouhyj ,         /* （取込用）生保Ｗｅｂ前納表示 */
     ztrseihowebyakkankbn ,         /* （取込用）生保Ｗｅｂ約款区分 */
     ztrseihowebnetkhrzmhyj ,         /* （取込用）生保Ｗｅｂネット口振対応済表示 */
     ztrseihowebkzktrkmoskbn ,         /* （取込用）生保Ｗｅｂご家族登録申込区分 */
     ztrseihowebkzktdkkbn1 ,         /* （取込用）生保Ｗｅｂご家族続柄区分１ */
     ztrseihowebkzkknnm1 ,         /* （取込用）生保Ｗｅｂご家族カナ氏名１ */
     ztrseihowebkzkkjnm1 ,         /* （取込用）生保Ｗｅｂご家族漢字氏名１ */
     ztrseihowebkzkseikbn1 ,         /* （取込用）生保Ｗｅｂご家族性別区分１ */
     ztrseihowebkzkseiymd1c ,         /* （取込用）生保Ｗｅｂご家族生年月日１Ｃ */
     ztrseihowebkzkkykdoukyohyj1 ,         /* （取込用）生保Ｗｅｂご家族契同居表示１ */
     ztrseihowebkzkyno1 ,         /* （取込用）生保Ｗｅｂご家族郵便番号１ */
     ztrseihowebkzkadr1 ,         /* （取込用）生保Ｗｅｂご家族住所１ */
     ztrseihowebkzktelno1 ,         /* （取込用）生保Ｗｅｂご家族電話番号１ */
     ztrseihowebkykdrtkkanouhyj ,         /* （取込用）生保Ｗｅｂ契代理特約可能表示 */
     ztrseihowebhhkndrtkkanouhyj ,         /* （取込用）生保Ｗｅｂ被代理特約可能表示 */
     ztrseihowebdrtkkbn ,         /* （取込用）生保Ｗｅｂ代理特約区分 */
     ztrseihowebkykdrnrkkbn ,         /* （取込用）生保Ｗｅｂ契代理入力区分 */
     ztrseihowebhhkndrnrkkbn ,         /* （取込用）生保Ｗｅｂ被代理入力区分 */
     ztrseihowebhhkndrtdkkbn ,         /* （取込用）生保Ｗｅｂ被代理続柄区分 */
     ztrseihowebhhkndrknnm ,         /* （取込用）生保Ｗｅｂ被代理カナ氏名 */
     ztrseihowebhhkndrkjnm ,         /* （取込用）生保Ｗｅｂ被代理漢字氏名 */
     ztrseihowebhhkndrseiymdc ,         /* （取込用）生保Ｗｅｂ被代理生年月日Ｃ */
     ztrseihowebdaihituarihyj ,         /* （取込用）生保Ｗｅｂ代筆有表示 */
     ztrseihowebkoureisyakakkbn1 ,         /* （取込用）生保Ｗｅｂ高齢者確認区分１ */
     ztrseihowebkoureisyakakkbn2 ,         /* （取込用）生保Ｗｅｂ高齢者確認区分２ */
     ztrseihowebkoureisyakakkbn3 ,         /* （取込用）生保Ｗｅｂ高齢者確認区分３ */
     ztrseihowebptuutihyj ,         /* （取込用）生保Ｗｅｂ保険料通知有表示 */
     ztryobiv1546 ,         /* （取込用）予備項目Ｖ１５４６ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SmbcPaperlessMos1Tr_Z;