CREATE VIEW ZT_IsaToukeiDataRn AS SELECT
     zrnmosno ,         /* （連携用）申込番号 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnhjykktkbn ,         /* （連携用）報状告知区分 */
     zrnhknsyuruicd ,         /* （連携用）保険種類コード */
     zrnhrkhuhukbn ,         /* （連携用）払込方法区分 */
     zrnmossyoumetukbn ,         /* （連携用）申込消滅区分 */
     zrnmusymd ,         /* （連携用）申込年月日 */
     zrnmosym ,         /* （連携用）申込月度 */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrnaatukaisosikicd ,         /* （連携用）Ａ扱者組織コード */
     zrnaatukaikojincd ,         /* （連携用）Ａ扱者個人コード */
     zrnhhknnen3 ,         /* （連携用）被保険者年令（３文字） */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnkyktuuka ,         /* （連携用）契約通貨 */
     zrnsibous7 ,         /* （連携用）死亡Ｓ（７桁） */
     zrndakuhikettisyacd ,         /* （連携用）諾否決定者コード */
     zrndkhktiymd ,         /* （連携用）諾否決定年月日 */
     zrndakuhikettikekkacd ,         /* （連携用）諾否決定結果コード */
     zrndakuhiketteiriyuucdx1 ,         /* （連携用）諾否決定理由コード＿１ */
     zrndakuhiketteiriyuucdx2 ,         /* （連携用）諾否決定理由コード＿２ */
     zrndakuhiketteiriyuucdx3 ,         /* （連携用）諾否決定理由コード＿３ */
     zrndakuhiketteiriyuucdx4 ,         /* （連携用）諾否決定理由コード＿４ */
     zrnsyukykktkekkacd ,         /* （連携用）主契約決定結果コード */
     zrnsntyo3 ,         /* （連携用）身長（３文字） */
     zrntijyuu3 ,         /* （連携用）体重（３文字） */
     zrnbmi ,         /* （連携用）ＢＭＩ */
     zrnsinsahouhou ,         /* （連携用）診査方法 */
     zrnsyoubyoucd1 ,         /* （連携用）傷病コード１ */
     zrnkeikanensuux1 ,         /* （連携用）経過年数＿１ */
     zrnsyoubyoucd2 ,         /* （連携用）傷病コード２ */
     zrnkeikanensuux2 ,         /* （連携用）経過年数＿２ */
     zrnsyokaiktisinsahouhou ,         /* （連携用）初回決定時診査方法 */
     zrnsyokaiktidkhktikekkacd ,         /* （連携用）初回決定時諾否決定結果コード */
     zrnsyokaiktsyukykktkekkacd ,         /* （連携用）初回決定主契約決定結果コード */
     zrnhanbaikeirokbn ,         /* （連携用）販売経路区分 */
     zrnjissituhosyous ,         /* （連携用）実質保障Ｓ */
     zrnoyadairitencd ,         /* （連携用）親代理店コード */
     zrnnensyuukbn ,         /* （連携用）年収区分 */
     zrnsykgycd ,         /* （連携用）職業コード */
     zrnsyksbyensitihsyutyhkumu ,         /* （連携用）初期死亡時円換算最低保証特約付加有無 */
     zrnjyudkaigomehrtkhkumu ,         /* （連携用）重度介護前払特約付加有無 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnijitoukeizennoukbn ,         /* （連携用）医事統計用前納区分 */
     zrndai1hknkkn ,         /* （連携用）第１保険期間 */
     zrnijitoukeitikshrtkykkbn ,         /* （連携用）医事統計用定期支払特約区分 */
     zrnteikisiharaikinmanen ,         /* （連携用）定期支払金（万円） */
     zrnyobiv45           /* （連携用）予備項目Ｖ４５ */
FROM ZT_IsaToukeiDataRn_Z;