CREATE VIEW ZT_HoyuuJyunzouZougenFRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrntantoukojincd ,         /* （連携用）担当者個人コード */
     zrntantousyasetteiym ,         /* （連携用）担当者設定年月 */
     zrnkeijyousakikbn ,         /* （連携用）計上先区分 */
     zrnkeijyousakisosiki ,         /* （連携用）計上先組織 */
     zrnkeijyouym ,         /* （連携用）計上年月 */
     zrndenymd ,         /* （連携用）伝票日付 */
     zrnutiwakekbn ,         /* （連携用）内訳区分 */
     zrntantoukeiyakukbn ,         /* （連携用）担当契約区分 */
     zrnkydatkikbn ,         /* （連携用）共同扱区分 */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnsaisinbsyym ,         /* （連携用）最新募集年月 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnmaruteisyuruikigou ,         /* （連携用）マル定種類記号 */
     zrnyobin3 ,         /* （連携用）予備項目Ｎ３ */
     zrnyobiv1 ,         /* （連携用）予備項目Ｖ１ */
     zrnyobiv1x2 ,         /* （連携用）予備項目Ｖ１＿２ */
     zrnkykniyutksytioukbn ,         /* （連携用）契約内容特殊対応区分 */
     zrnyobiv1x3 ,         /* （連携用）予備項目Ｖ１＿３ */
     zrnteisyuuhyj ,         /* （連携用）定終表示 */
     zrnitijibryourouhyj ,         /* （連携用）一時払養老表示 */
     zrnmrtihukahyj ,         /* （連携用）マル定付加表示 */
     zrnseizonmrtihukahyj ,         /* （連携用）生存マル定付加表示 */
     zrnteigenmrtihukahyj ,         /* （連携用）逓減マル定付加表示 */
     zrnsynymrtihukahyj ,         /* （連携用）収入マル定付加表示 */
     zrnlivingneedstkykarihyj ,         /* （連携用）リビングニーズ特約有表示 */
     zrnreguardmrtihukahyj ,         /* （連携用）リガードマル定付加表示 */
     zrnreguardmrsyuhukahyj ,         /* （連携用）リガードマル終付加表示 */
     zrnvguardmrtihukahyj ,         /* （連携用）Ｖガードマル定付加表示 */
     zrnkaigonktkykhukahyj ,         /* （連携用）介護年金特約付加表示 */
     zrngoukeisisttkyktkknsnp ,         /* （連携用）合計災疾特約月換算Ｐ */
     zrnhsys ,         /* （連携用）保障Ｓ */
     zrnkensuun3 ,         /* （連携用）件数Ｎ３ */
     zrnhenkougohosyous ,         /* （連携用）変更後保障Ｓ */
     zrnhtns ,         /* （連携用）被転換Ｓ */
     zrnharaikomip ,         /* （連携用）払込Ｐ */
     zrnkaiyakusiharaikngk ,         /* （連携用）解約支払金額 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnanniskcd ,         /* （連携用）案内先コード */
     zrntenkankaisuu ,         /* （連携用）転換回数 */
     zrnsikkounyknkaisuu ,         /* （連携用）失効入金回数 */
     zrnyobiv2 ,         /* （連携用）予備項目Ｖ２ */
     zrnhhknnen2keta ,         /* （連携用）被保険者年令（２桁） */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnkjkyknm ,         /* （連携用）漢字契約者名 */
     zrntsinkihontikucd ,         /* （連携用）通信先基本地区コード */
     zrnhjnkykhyj ,         /* （連携用）法人契約表示 */
     zrnhjncd ,         /* （連携用）法人コード */
     zrnhjnjigyosyocd ,         /* （連携用）法人事業所コード */
     zrnsyorisosikicd ,         /* （連携用）処理組織コード */
     zrntikusyokansisyakijyhyj ,         /* （連携用）地区所管支社計上表示 */
     zrnkeizokutyuuihyouji ,         /* （連携用）継続注意表示 */
     zrntyohkkeiyakutyuuikbn ,         /* （連携用）重複契約注意区分 */
     zrnyobiv1x4 ,         /* （連携用）予備項目Ｖ１＿４ */
     zrndantaisyozokucd ,         /* （連携用）団体所属コード */
     zrnsuperknkuseikatupackhyj ,         /* （連携用）スーパー健康生活パック表示 */
     zrnjikokykhyj ,         /* （連携用）自己契約表示 */
     zrnkikeiyakutyuuihyouji ,         /* （連携用）既契約注意表示 */
     zrnsyuuseis ,         /* （連携用）修正Ｓ */
     zrnclubsumiseikaiinkykkbn ,         /* （連携用）クラブスミセイ会員契約区分 */
     zrngatkihmkknrkmaekykhyj ,         /* （連携用）Ｇ扱者訪問結果入力前契約表示 */
     zrngatkisetteikouhokykhyj ,         /* （連携用）Ｇ扱者設定候補契約表示 */
     zrnbosyuu25keikahyj ,         /* （連携用）募集２５カ月経過表示 */
     zrntokuteidaisyokudanhyj ,         /* （連携用）特定大職団表示 */
     zrnhoyuuikantsgkykhyj ,         /* （連携用）保有移管対象外契約表示 */
     zrntokubeturuletikuhyj ,         /* （連携用）特別ルール地区表示 */
     zrnfieldtantousyaarihyj ,         /* （連携用）フィールド担当者有表示 */
     zrnyobiv1x5 ,         /* （連携用）予備項目Ｖ１＿５ */
     zrncatkihmkknrkmaekykhyj ,         /* （連携用）Ｃ扱者訪問結果入力前契約表示 */
     zrncatkisetteikouhokykhyj ,         /* （連携用）Ｃ扱者設定候補契約表示 */
     zrnseppankeijyoukbn ,         /* （連携用）折半計上区分 */
     zrnyobiv6 ,         /* （連携用）予備項目Ｖ６ */
     zrnfollowtantousyakbn ,         /* （連携用）フォロー担当者区分 */
     zrnyobiv7 ,         /* （連携用）予備項目Ｖ７ */
     zrnhosyouminaosikaisuuv2 ,         /* （連携用）保障見直回数Ｖ２ */
     zrnbnkttnknkbn ,         /* （連携用）分割転換区分 */
     zrntenkangosyono ,         /* （連携用）転換後証券番号 */
     zrnqpackhyj ,         /* （連携用）Ｑパック表示 */
     zrntenkangoqpackhyj ,         /* （連携用）転換後Ｑパック表示 */
     zrnsyuruihnkutkbttrtkhyj ,         /* （連携用）種類変更特別取扱表示 */
     zrntnkngsyuhnkutkbttrtkhyj ,         /* （連携用）転換後種類変更特別取扱表示 */
     zrnyobin11 ,         /* （連携用）予備項目Ｎ１１ */
     zrnkibanhikitugikbn ,         /* （連携用）基盤引継加算区分 */
     zrnyobiv1x6 ,         /* （連携用）予備項目Ｖ１＿６ */
     zrnsyoumetucd ,         /* （連携用）消滅コード */
     zrnjikaipjyuutouym ,         /* （連携用）次回Ｐ充当年月 */
     zrnkaigomarusyuuhukahyj ,         /* （連携用）介護マル終付加表示 */
     zrnyobiv1x7 ,         /* （連携用）予備項目Ｖ１＿７ */
     zrnsyoritorikesihyj ,         /* （連携用）処理取消表示 */
     zrnmrtikousinkatakbn ,         /* （連携用）マル定更新型区分 */
     zrnpmenkbnv1 ,         /* （連携用）Ｐ免区分Ｖ１ */
     zrnsyukeiyakutkknsnp ,         /* （連携用）主契約月換算Ｐ */
     zrnnenkansanp ,         /* （連携用）年換算Ｐ */
     zrndai3bunyanenkansanp ,         /* （連携用）第３分野年換算Ｐ */
     zrnnyuuintkykhukahyj ,         /* （連携用）入院特約付加表示 */
     zrnnyuuintkykhukahyj20ijyou ,         /* （連携用）２０日以上入院特約付加表示 */
     zrnnyuuintkykhukahyj5ijyou ,         /* （連携用）５日以上入院特約付加表示 */
     zrnmarusyotkykhukahyj ,         /* （連携用）マル初特約付加表示 */
     zrnmarujyuutkykhukahyj ,         /* （連携用）マル重特約付加表示 */
     zrnkakudaimaruitkykhukahyj ,         /* （連携用）拡大マル医系特約付加表示 */
     zrnkakunyuutkykhukahyj ,         /* （連携用）カク入特約付加表示 */
     zrnmaruitkykhukahyj ,         /* （連携用）マル医特約付加表示 */
     zrnstdairiseikyuutkykarihyj ,         /* （連携用）指定代理請求特約有表示 */
     zrnkensuuyuuguukbn ,         /* （連携用）件数優遇区分 */
     zrnkaigosynyteikikbn ,         /* （連携用）（介護）収入定期区分 */
     zrnkaigosynyteikishrkskbn ,         /* （連携用）（介護）収入定期支払回数区分 */
     zrngyousekibosyujisikakucd ,         /* （連携用）業績用募集時資格コード */
     zrngyskboshtnsineiyksnkbn ,         /* （連携用）業績用募集時発展新鋭躍進区分 */
     zrnsiktsynymrtihukahyj ,         /* （連携用）生活収入マル定付加表示 */
     zrnsiktsynyteikikbn ,         /* （連携用）生活収入定期区分 */
     zrnseikatusyuunyuumrtis ,         /* （連携用）生活収入マル定Ｓ */
     zrnlivguardhukahyj ,         /* （連携用）ＬＩＶガード付加表示 */
     zrnlivguards ,         /* （連携用）ＬＩＶガードＳ */
     zrnknkuzusnzyrttekitkarihyj ,         /* （連携用）健康増進乗率適用特約有表示 */
     zrnbluekzjtkaisiymd ,         /* （連携用）Ｂｌｕｅ継続状態開始年月日　 */
     zrnknkuzusnzyrtstkbn ,         /* （連携用）健康増進乗率用ステータス区分 */
     zrnkykdrtkykarihyj ,         /* （連携用）契約者代理特約有表示 */
     zrnkzktourokuservicearihyj ,         /* （連携用）家族登録サービス有表示 */
     zrnyobiv1x11           /* （連携用）予備項目Ｖ１＿１１ */
FROM ZT_HoyuuJyunzouZougenFRn_Z;