CREATE VIEW ZT_IjiToukeiIdouInfoTr AS SELECT
     ztrsyono ,         /* （取込用）証券番号 */
     ztrsyoriymd ,         /* （取込用）処理年月日 */
     ztrkykmfksnctr ,         /* （取込用）契約ＭＦ更新ＣＴＲ */
     ztrsyukgu ,         /* （取込用）種類記号 */
     ztrhhknnen2keta ,         /* （取込用）被保険者年令（２桁） */
     ztrhhknseikbn ,         /* （取込用）被保険者性別区分 */
     ztrkykym ,         /* （取込用）契約年月 */
     ztrkisnkihons ,         /* （取込用）計算基本Ｓ */
     ztrimustiyusbus ,         /* （取込用）医務査定用死亡Ｓ */
     ztrshrs ,         /* （取込用）支払Ｓ */
     ztrshrymd ,         /* （取込用）支払年月日 */
     ztrsymtgenincd ,         /* （取込用）消滅原因コード */
     ztrkeikaym ,         /* （取込用）経過年月 */
     ztrsbugenincd ,         /* （取込用）死亡原因コード */
     ztrbsyym ,         /* （取込用）募集年月 */
     ztrdai2hhknnen ,         /* （取込用）第２被保険者年令 */
     ztrmannenreihyj ,         /* （取込用）満年令表示 */
     ztrtignmrtisyukgu ,         /* （取込用）逓減マル定種類記号 */
     ztrhhknnentysihyj ,         /* （取込用）被保険者年令調整表示 */
     ztrdai2hhknnentysihyj ,         /* （取込用）第２被保険者年令調整表示 */
     ztrrenseimrtisyukgu ,         /* （取込用）連生マル定種類記号 */
     ztrbnktjitiktkarihyj ,         /* （取込用）分割時定期特約有表示 */
     ztrlivingneedsshrarihyj ,         /* （取込用）リビングニーズ支払有表示 */
     ztrlnkeikaym ,         /* （取込用）ＬＮ経過年月 */
     ztrlnshrgenincd ,         /* （取込用）ＬＮ支払原因コード */
     ztrkituenkbn ,         /* （取込用）喫煙区分 */
     ztrkituenhonsuu ,         /* （取込用）喫煙本数 */
     ztrgnspshrhyj ,         /* （取込用）がんサポ支払表示 */
     ztrgnspshrkeikaym ,         /* （取込用）がんサポ支払経過年月 */
     ztrgnspshrgenincd ,         /* （取込用）がんサポ支払原因コード */
     ztrsyunyumrtisyukgu ,         /* （取込用）収入マル定種類記号 */
     ztrsysnymd ,         /* （取込用）初診年月日 */
     ztrsindanymd ,         /* （取込用）診断年月日 */
     ztrbyoumeicd1 ,         /* （取込用）病名コード１ */
     ztrbyoumeicd2 ,         /* （取込用）病名コード２ */
     ztrshrnaiyoukbn ,         /* （取込用）支払内容区分 */
     ztrgituyuknkbn1 ,         /* （取込用）該当要件区分１ */
     ztrgituyuknkbn2 ,         /* （取込用）該当要件区分２ */
     ztrsyeiebnri1 ,         /* （取込用）シェイエ分類１ */
     ztrsyeiebnri2 ,         /* （取込用）シェイエ分類２ */
     ztrminnesotacd1 ,         /* （取込用）ミネソタコード１ */
     ztrminnesotacd2 ,         /* （取込用）ミネソタコード２ */
     ztrminnesotacd3 ,         /* （取込用）ミネソタコード３ */
     ztrminnesotacd4 ,         /* （取込用）ミネソタコード４ */
     ztrminnesotacd5 ,         /* （取込用）ミネソタコード５ */
     ztrmnsisiensindanjiyuu ,         /* （取込用）慢性膵炎診断事由 */
     ztrknkuhnsindanjiyuu ,         /* （取込用）肝硬変診断事由 */
     ztrhushrkbn ,         /* （取込用）不支払区分 */
     ztrhushrym ,         /* （取込用）不支払年月 */
     ztrsyuurouhunoukghasseiymd ,         /* （取込用）就労不能介護傷病発生年月日 */
     ztrsyuurouhunoukgjyoutaikbn ,         /* （取込用）就労不能介護状態区分 */
     ztrhokoukahikbn ,         /* （取込用）歩行可否区分 */
     ztrngerkahikbn ,         /* （取込用）寝返り可否区分 */
     ztrihukutyakudatukahikbn ,         /* （取込用）衣服着脱可否区分 */
     ztrnyykkahikbn ,         /* （取込用）入浴可否区分 */
     ztrsykmtssyukahikbn ,         /* （取込用）食物摂取可否区分 */
     ztrfktrsmtkahikbn ,         /* （取込用）拭き取り始末可否区分 */
     ztrseiketuseiyoukahikbn ,         /* （取込用）清潔整容可否区分 */
     ztrsyuurouhunoujyoutaikbn ,         /* （取込用）就労不能状態区分 */
     ztrkyuuseisinkinkousokukbn ,         /* （取込用）急性心筋梗塞区分 */
     ztrnousottyuukbn ,         /* （取込用）脳卒中区分 */
     ztrjinhuzenkbn ,         /* （取込用）腎不全区分 */
     ztrhukasyuksyu ,         /* （取込用）付加主契約種類 */
     ztrtkkbn2 ,         /* （取込用）特約区分（２文字） */
     ztrdoumyakusikkankbn ,         /* （取込用）動脈疾患区分 */
     ztrsykikjgykbn ,         /* （取込用）職域事業区分 */
     ztrkaijyokbn ,         /* （取込用）解除区分 */
     ztrsymtymd ,         /* （取込用）消滅年月日 */
     ztrtyuutohukatkhyj ,         /* （取込用）中途付加特約表示 */
     ztryoukigjyutigituymd ,         /* （取込用）要介護状態該当年月日 */
     ztryoukigjyutigeninkbn ,         /* （取込用）要介護状態原因区分 */
     ztrtihougeninkbn ,         /* （取込用）痴呆原因区分 */
     ztrsyukgusdkbn ,         /* （取込用）種類記号世代区分 */
     ztrtignmrtisyukgusdkbn ,         /* （取込用）逓減マル定種類記号世代区分 */
     ztrrenseimrtisyukgusdkbn ,         /* （取込用）連生マル定種類記号世代区分 */
     ztrsyunyumrtisyukgusdkbn ,         /* （取込用）収入マル定種類記号世代区分 */
     ztrsbtoukeiidouinfopmenkbn ,         /* （取込用）死亡統計異動情報Ｐ免区分 */
     ztrpmenjikohasseiymd ,         /* （取込用）Ｐ免事故発生年月日 */
     ztrsyorino2moji ,         /* （取込用）処理番号（２文字） */
     ztrksnym ,         /* （取込用）更新年月 */
     ztrikoujisnskbn ,         /* （取込用）移行時診査区分 */
     ztrsysnikoujiym ,         /* （取込用）終身移行時年月 */
     ztrijitoukeiyuksnhyj ,         /* （取込用）医事統計用更新表示 */
     ztrsotodasiphkbnmnoshyouji ,         /* （取込用）外出Ｐ不可分見直表示 */
     ztrstdsstkjytkyuhyj ,         /* （取込用）外出新特条適用表示 */
     ztrstdssytikbn ,         /* （取込用）外出集定区分 */
     ztrbnktgosnzkkyksyono ,         /* （取込用）分割後存続契約証券番号 */
     ztrbnkttnknkbn ,         /* （取込用）分割転換区分 */
     ztrkykjiqpackhyj ,         /* （取込用）契約時Ｑパック表示 */
     ztrbnktjisisttkarihyj ,         /* （取込用）分割時災疾特約有表示 */
     ztrsotodasipmenkbn ,         /* （取込用）外出Ｐ免区分 */
     ztrstdssnskbn ,         /* （取込用）外出診査区分 */
     ztryobisuuti7x1 ,         /* （取込用）予備数値７＿１ */
     ztryobisuuti7x2 ,         /* （取込用）予備数値７＿２ */
     ztryobimojihan15 ,         /* （取込用）予備文字半角１５ */
     ztryobimojihan51 ,         /* （取込用）予備文字半角５１ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_IjiToukeiIdouInfoTr_Z;