CREATE VIEW ZT_Skeiksnbsgetujisr1Ty AS SELECT
     ztyktgysyrymd ,         /* （中継用）結合用処理日 */
     ztyktgysyono ,         /* （中継用）結合用証券番号 */
     ztyktgyfilerenno ,         /* （中継用）結合用ファイル連番 */
     ztysyono ,         /* （中継用）証券番号 */
     ztyaatukaisyasisyacd ,         /* （中継用）Ａ扱者支社コード */
     ztymosno ,         /* （中継用）申込番号 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztykihons ,         /* （中継用）基本Ｓ */
     ztysibous ,         /* （中継用）死亡Ｓ */
     ztygyousekihyoukayouhosyous ,         /* （中継用）業績評価用保障Ｓ */
     ztygukitnknitjbrkhns ,         /* （中継用）合計転換一時払基本Ｓ */
     ztygukitnknitjbrsbus ,         /* （中継用）合計転換一時払死亡Ｓ */
     ztykktijgukitnknitjbrkhns ,         /* （中継用）確定時合計転換一時払基本Ｓ */
     ztykktijgukitnknitjbrsbus ,         /* （中継用）確定時合計転換一時払死亡Ｓ */
     ztysyokaiharaikomip ,         /* （中継用）初回払込Ｐ */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztyryouritukbn ,         /* （中継用）料率区分 */
     ztytksyuannaikykkbn ,         /* （中継用）特殊案内契約区分 */
     ztysdpdkbn ,         /* （中継用）Ｓ建Ｐ建区分 */
     ztyanniskcd ,         /* （中継用）案内先コード */
     ztyduketorihouhoukbn ,         /* （中継用）Ｄ受取方法区分 */
     ztykyksyhhknsydouituhyouji ,         /* （中継用）契約者被保険者同一表示 */
     ztykyksyakikykarihyj ,         /* （中継用）契約者既契約有表示 */
     ztytenkankeiyakuhyouji ,         /* （中継用）転換契約表示 */
     ztyjigyoukeiyakuhyouji ,         /* （中継用）事業契約表示 */
     ztynenkinzeiseitokuyakukbn ,         /* （中継用）年金税制特約区分 */
     ztysyusseimaekanyuukykkbn ,         /* （中継用）出生前加入契約区分 */
     ztykazokukeiyakuhyouji ,         /* （中継用）家族契約表示 */
     ztyjikokykhyj ,         /* （中継用）自己契約表示 */
     ztytuusyoumeisiyouhyouji ,         /* （中継用）通称名使用表示 */
     ztysethokenkbn ,         /* （中継用）セット保険区分 */
     ztyteikeisyouhinkbn ,         /* （中継用）提携商品区分 */
     ztysykgycd ,         /* （中継用）職業コード */
     ztytokuninbosyuuteate ,         /* （中継用）特認募集手当 */
     ztyseisekiym ,         /* （中継用）成績計上年月 */
     ztyseisekikeijyousyuuseis ,         /* （中継用）成績計上修正Ｓ */
     ztysyuuseissakugenhyouji ,         /* （中継用）修正Ｓ削減表示 */
     ztyaatukaisisyatodouhukencd ,         /* （中継用）Ａ扱支社都道府県コード */
     ztyaatukaisosikicd ,         /* （中継用）Ａ扱者組織コード */
     ztyaatukaikojincd ,         /* （中継用）Ａ扱者個人コード */
     ztybatukaisosikicd ,         /* （中継用）Ｂ扱者組織コード */
     ztybatukaisyakojincd ,         /* （中継用）Ｂ扱者個人コード */
     ztymarutokukbn ,         /* （中継用）マル特区分 */
     ztygyoumujyouhyouji ,         /* （中継用）業務上表示 */
     ztytuikakeijyoukbn ,         /* （中継用）追加計上区分 */
     ztyseisekinomikeijyoukbn ,         /* （中継用）成績のみ計上区分 */
     ztyteikikeijyoukbn ,         /* （中継用）定期計上区分 */
     ztyhngkmskkatkisykbn ,         /* （中継用）変額無資格扱者区分 */
     ztytnknkyuuyosakugenhyj ,         /* （中継用）転換給与削減表示 */
     ztytenkankaisuu ,         /* （中継用）転換回数 */
     ztyhiyubrigssnsikkijyunkbn ,         /* （中継用）併用払合算正規基準区分 */
     ztysekininkaisiymd ,         /* （中継用）責任開始年月日 */
     ztykigetusmkrgkykhyj ,         /* （中継用）期月締切後契約表示 */
     ztyhensyuusyoriymd ,         /* （中継用）編集処理年月日 */
     ztyjisisyaatukaihyouji ,         /* （中継用）自支社扱表示 */
     ztyaatkisytktntusy1atkihyj ,         /* （中継用）Ａ扱者地区担当者１扱表示 */
     ztyaatkisytktntusy2atkihyj ,         /* （中継用）Ａ扱者地区担当者２扱表示 */
     ztyaatkisyasyokan1atkihyj ,         /* （中継用）Ａ扱者所管１扱表示 */
     ztyaatkisyasyokan2atkihyj ,         /* （中継用）Ａ扱者所管２扱表示 */
     ztybatkisytktntusy1atkihyj ,         /* （中継用）Ｂ扱者地区担当者１扱表示 */
     ztybatkisytktntusy2atkihyj ,         /* （中継用）Ｂ扱者地区担当者２扱表示 */
     ztybatkisyasyokan1atkihyj ,         /* （中継用）Ｂ扱者所管１扱表示 */
     ztybatkisyasyokan2atkihyj ,         /* （中継用）Ｂ扱者所管２扱表示 */
     ztykeizokutyuuihyouji ,         /* （中継用）継続注意表示 */
     ztykeiyakubisiteihyouji ,         /* （中継用）契約日指定表示 */
     ztyjyoukentukihyouji ,         /* （中継用）条件付表示 */
     ztytokuninhyouji ,         /* （中継用）特認表示 */
     ztykessantyouseikbn ,         /* （中継用）決算調整区分 */
     ztyhaneihyouji ,         /* （中継用）繁栄表示 */
     ztysyukinkbn ,         /* （中継用）集金区分 */
     ztykeiyakusyasyokugyoucd ,         /* （中継用）契約者職業コード */
     ztyseikeikeirokbn ,         /* （中継用）成契経路区分 */
     ztydai2seikeikeirokbn ,         /* （中継用）第２成契経路区分 */
     ztyteigentokuteisyuruikigou ,         /* （中継用）逓減トク定種類記号 */
     ztyteigentokuteikikan ,         /* （中継用）逓減トク定期間 */
     ztyteigentokuteis ,         /* （中継用）逓減トク定Ｓ */
     ztyteigentokuteip ,         /* （中継用）逓減トク定Ｐ */
     ztytigntktisdtpdtkbn ,         /* （中継用）逓減トク定Ｓ建Ｐ建区分 */
     ztyteigentokuteisyuuseis ,         /* （中継用）逓減トク定修正Ｓ */
     ztyteigentktimodssakugenhyj ,         /* （中継用）逓減トク定修正Ｓ削減表示 */
     ztyteigentktikgusdkbn ,         /* （中継用）逓減トク定記号世代区分 */
     ztyyobiv9 ,         /* （中継用）予備項目Ｖ９ */
     ztytokuteibuicdx1 ,         /* （中継用）特定部位コード＿１ */
     ztyhtnpkknx1 ,         /* （中継用）不担保期間＿１ */
     ztytokuteibuicdx2 ,         /* （中継用）特定部位コード＿２ */
     ztyhtnpkknx2 ,         /* （中継用）不担保期間＿２ */
     ztyhhknmei ,         /* （中継用）被保険者名 */
     ztyknjhhknmei ,         /* （中継用）漢字被保険者名 */
     ztyhhknseiymd ,         /* （中継用）被保険者生年月日 */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhhknhnsktodouhukencd ,         /* （中継用）被保険者本籍都道府県コード */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztyhihokensyakikykarihyj ,         /* （中継用）被保険者既契約有表示 */
     ztynobikkosaimankikbn ,         /* （中継用）のびっこ才満期区分 */
     ztyhhknsysysnhonninkknnkbn ,         /* （中継用）被保険者初診本人確認区分 */
     ztyhhknsysisnhonninkknnkbn ,         /* （中継用）被保険者再診本人確認区分 */
     ztykzktourokuservicearihyj ,         /* （中継用）家族登録サービス有表示 */
     ztyyobiv4x12 ,         /* （中継用）予備項目Ｖ４＿１２ */
     ztyhensyuukeiyakusyamei ,         /* （中継用）編集契約者名 */
     ztyhnsyuknjkyksynm ,         /* （中継用）編集漢字契約者名 */
     ztykyksyaseiymd ,         /* （中継用）契約者生年月日 */
     ztykyksyaseikbn ,         /* （中継用）契約者性別区分 */
     ztykyksyanen ,         /* （中継用）契約者年令 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztyknkuzusnzyrt ,         /* （中継用）健康増進乗率 */
     ztyvitdoujimos2kenmeikouhyj ,         /* （中継用）Ｖｉｔ同時申込２件目以降表示 */
     ztykikykvitarituikamoshyj ,         /* （中継用）既契約Ｖｉｔ有追加申込表示 */
     ztyhtnknkykvithokenkbn ,         /* （中継用）被転換契約Ｖｉｔ保険区分 */
     ztykikykvithokenhoyuujkkbn ,         /* （中継用）既契約Ｖｉｔ保険保有状況区分 */
     ztyyobiv2x2 ,         /* （中継用）予備項目Ｖ２＿２ */
     ztytsnsknewyno ,         /* （中継用）通信先新郵便番号 */
     ztytsnsknewtikucd ,         /* （中継用）通信先新地区コード */
     ztymossyumtkktymd ,         /* （中継用）申込消滅確定年月日 */
     ztykituenkbn ,         /* （中継用）喫煙区分 */
     ztytuusinsakijyuusyokbn ,         /* （中継用）通信先住所区分 */
     ztymaruteisyuruikigou ,         /* （中継用）マル定種類記号 */
     ztymaruteikikan ,         /* （中継用）マル定期間 */
     ztymaruteiphrkkkn ,         /* （中継用）マル定Ｐ払込期間 */
     ztymaruteis ,         /* （中継用）マル定Ｓ */
     ztymaruteip ,         /* （中継用）マル定Ｐ */
     ztymaruteisyuuseis ,         /* （中継用）マル定修正Ｓ */
     ztymaruteisyuuseisskgnhyj ,         /* （中継用）マル定修正Ｓ削減表示 */
     ztymaruteitokujyoukbn ,         /* （中継用）マル定特条区分 */
     ztymrtitkjyuskgnkkn ,         /* （中継用）マル定特条削減期間 */
     ztymrtitkjyuryumshyutn ,         /* （中継用）マル定特条料増標点 */
     ztymaruteitokujyoup ,         /* （中継用）マル定特条Ｐ */
     ztysuryumrtipwrbkkbn ,         /* （中継用）数理用マル定Ｐ割引区分 */
     ztymaruteipwaribikikbn ,         /* （中継用）マル定Ｐ割引区分 */
     ztymrtitnknyugukbn ,         /* （中継用）マル定転換優遇区分 */
     ztymaruteikigousedaikbn ,         /* （中継用）マル定記号世代区分 */
     ztymaruteikikousnmnryoage ,         /* （中継用）マル定更新満了年令 */
     ztyyobiv2 ,         /* （中継用）予備項目Ｖ２ */
     ztymaruyousyuruikigou ,         /* （中継用）マル養種類記号 */
     ztymaruyoukikan ,         /* （中継用）マル養期間 */
     ztymaruyous ,         /* （中継用）マル養Ｓ */
     ztymaruyoup ,         /* （中継用）マル養Ｐ */
     ztymaruyousdatepdatekbn ,         /* （中継用）マル養Ｓ建Ｐ建区分 */
     ztymaruyousyuuseis ,         /* （中継用）マル養修正Ｓ */
     ztymaruyousyuuseisskgnhyj ,         /* （中継用）マル養修正Ｓ削減表示 */
     ztymaruyoukigousedaikbn ,         /* （中継用）マル養記号世代区分 */
     ztyyobiv9x3 ,         /* （中継用）予備項目Ｖ９＿３ */
     ztymarusyuusyuruikigou ,         /* （中継用）マル終種類記号 */
     ztymarusyuukikan ,         /* （中継用）マル終期間 */
     ztymarusyuus ,         /* （中継用）マル終Ｓ */
     ztymarusyuup ,         /* （中継用）マル終Ｐ */
     ztymarusyuusdatepdatekbn ,         /* （中継用）マル終Ｓ建Ｐ建区分 */
     ztymarusyuusyuuseis ,         /* （中継用）マル終修正Ｓ */
     ztymarusyuusyuuseisskgnhyj ,         /* （中継用）マル終修正Ｓ削減表示 */
     ztymarusyuukigousedaikbn ,         /* （中継用）マル終記号世代区分 */
     ztyyobiv9x4 ,         /* （中継用）予備項目Ｖ９＿４ */
     ztytokuteisyuruikigou ,         /* （中継用）トク定種類記号 */
     ztytokuteikikan ,         /* （中継用）トク定期間 */
     ztytokuteis ,         /* （中継用）トク定Ｓ */
     ztytokuteip ,         /* （中継用）トク定Ｐ */
     ztytokuteisdatepdatekbn ,         /* （中継用）トク定Ｓ建Ｐ建区分 */
     ztytokuteisyuuseis ,         /* （中継用）トク定修正Ｓ */
     ztytokuteisyuuseisskgnhyj ,         /* （中継用）トク定修正Ｓ削減表示 */
     ztytokuteikigousedaikbn ,         /* （中継用）トク定記号世代区分 */
     ztyyobiv9x5 ,         /* （中継用）予備項目Ｖ９＿５ */
     ztykzkmrtitkyknox1 ,         /* （中継用）家族マル定特約番号＿１ */
     ztykazokumrtisyuruikgux1 ,         /* （中継用）家族マル定種類記号＿１ */
     ztykazokumaruteikikanx1 ,         /* （中継用）家族マル定期間＿１ */
     ztykazokumrtiphrkkknx1 ,         /* （中継用）家族マル定Ｐ払込期間＿１ */
     ztykazokumaruteisx1 ,         /* （中継用）家族マル定Ｓ＿１ */
     ztykazokumaruteipx1 ,         /* （中継用）家族マル定Ｐ＿１ */
     ztykzkmrtihihknsyanmx1 ,         /* （中継用）家族マル定被保険者名＿１ */
     ztykzkmrtihihknsyseiymdx1 ,         /* （中継用）家族マル定被保険者生年月日＿１ */
     ztykzkmrtihihknsysibtkbnx1 ,         /* （中継用）家族マル定被保険者性別区分＿１ */
     ztykazokumrtihihknsyaagex1 ,         /* （中継用）家族マル定被保険者年令＿１ */
     ztykzkmrtimodsx1 ,         /* （中継用）家族マル定修正Ｓ＿１ */
     ztykazokumrtimodsskgnhyjx1 ,         /* （中継用）家族マル定修正Ｓ削減表示＿１ */
     ztykzkmrtitnknyugukbnx1 ,         /* （中継用）家族マル定転換優遇区分＿１ */
     ztykazokumrtikgusdkbnx1 ,         /* （中継用）家族マル定記号世代区分＿１ */
     ztykazokumrtiagetyusihyjx1 ,         /* （中継用）家族マル定年令調整表示＿１ */
     ztykzkmrtikusnmnryoagex1 ,         /* （中継用）家族マル定更新満了年令＿１ */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     ztykzkmrtitkyknox2 ,         /* （中継用）家族マル定特約番号＿２ */
     ztykazokumrtisyuruikgux2 ,         /* （中継用）家族マル定種類記号＿２ */
     ztykazokumaruteikikanx2 ,         /* （中継用）家族マル定期間＿２ */
     ztykazokumrtiphrkkknx2 ,         /* （中継用）家族マル定Ｐ払込期間＿２ */
     ztykazokumaruteisx2 ,         /* （中継用）家族マル定Ｓ＿２ */
     ztykazokumaruteipx2 ,         /* （中継用）家族マル定Ｐ＿２ */
     ztykzkmrtihihknsyanmx2 ,         /* （中継用）家族マル定被保険者名＿２ */
     ztykzkmrtihihknsyseiymdx2 ,         /* （中継用）家族マル定被保険者生年月日＿２ */
     ztykzkmrtihihknsysibtkbnx2 ,         /* （中継用）家族マル定被保険者性別区分＿２ */
     ztykazokumrtihihknsyaagex2 ,         /* （中継用）家族マル定被保険者年令＿２ */
     ztykzkmrtimodsx2 ,         /* （中継用）家族マル定修正Ｓ＿２ */
     ztykazokumrtimodsskgnhyjx2 ,         /* （中継用）家族マル定修正Ｓ削減表示＿２ */
     ztykzkmrtitnknyugukbnx2 ,         /* （中継用）家族マル定転換優遇区分＿２ */
     ztykazokumrtikgusdkbnx2 ,         /* （中継用）家族マル定記号世代区分＿２ */
     ztykazokumrtiagetyusihyjx2 ,         /* （中継用）家族マル定年令調整表示＿２ */
     ztykzkmrtikusnmnryoagex2 ,         /* （中継用）家族マル定更新満了年令＿２ */
     ztyyobiv4x2 ,         /* （中継用）予備項目Ｖ４＿２ */
     ztykzkmrtitkyknox3 ,         /* （中継用）家族マル定特約番号＿３ */
     ztykazokumrtisyuruikgux3 ,         /* （中継用）家族マル定種類記号＿３ */
     ztykazokumaruteikikanx3 ,         /* （中継用）家族マル定期間＿３ */
     ztykazokumrtiphrkkknx3 ,         /* （中継用）家族マル定Ｐ払込期間＿３ */
     ztykazokumaruteisx3 ,         /* （中継用）家族マル定Ｓ＿３ */
     ztykazokumaruteipx3 ,         /* （中継用）家族マル定Ｐ＿３ */
     ztykzkmrtihihknsyanmx3 ,         /* （中継用）家族マル定被保険者名＿３ */
     ztykzkmrtihihknsyseiymdx3 ,         /* （中継用）家族マル定被保険者生年月日＿３ */
     ztykzkmrtihihknsysibtkbnx3 ,         /* （中継用）家族マル定被保険者性別区分＿３ */
     ztykazokumrtihihknsyaagex3 ,         /* （中継用）家族マル定被保険者年令＿３ */
     ztykzkmrtimodsx3 ,         /* （中継用）家族マル定修正Ｓ＿３ */
     ztykazokumrtimodsskgnhyjx3 ,         /* （中継用）家族マル定修正Ｓ削減表示＿３ */
     ztykzkmrtitnknyugukbnx3 ,         /* （中継用）家族マル定転換優遇区分＿３ */
     ztykazokumrtikgusdkbnx3 ,         /* （中継用）家族マル定記号世代区分＿３ */
     ztykazokumrtiagetyusihyjx3 ,         /* （中継用）家族マル定年令調整表示＿３ */
     ztykzkmrtikusnmnryoagex3 ,         /* （中継用）家族マル定更新満了年令＿３ */
     ztyyobiv4x3 ,         /* （中継用）予備項目Ｖ４＿３ */
     ztykzkmrtitkyknox4 ,         /* （中継用）家族マル定特約番号＿４ */
     ztykazokumrtisyuruikgux4 ,         /* （中継用）家族マル定種類記号＿４ */
     ztykazokumaruteikikanx4 ,         /* （中継用）家族マル定期間＿４ */
     ztykazokumrtiphrkkknx4 ,         /* （中継用）家族マル定Ｐ払込期間＿４ */
     ztykazokumaruteisx4 ,         /* （中継用）家族マル定Ｓ＿４ */
     ztykazokumaruteipx4 ,         /* （中継用）家族マル定Ｐ＿４ */
     ztykzkmrtihihknsyanmx4 ,         /* （中継用）家族マル定被保険者名＿４ */
     ztykzkmrtihihknsyseiymdx4 ,         /* （中継用）家族マル定被保険者生年月日＿４ */
     ztykzkmrtihihknsysibtkbnx4 ,         /* （中継用）家族マル定被保険者性別区分＿４ */
     ztykazokumrtihihknsyaagex4 ,         /* （中継用）家族マル定被保険者年令＿４ */
     ztykzkmrtimodsx4 ,         /* （中継用）家族マル定修正Ｓ＿４ */
     ztykazokumrtimodsskgnhyjx4 ,         /* （中継用）家族マル定修正Ｓ削減表示＿４ */
     ztykzkmrtitnknyugukbnx4 ,         /* （中継用）家族マル定転換優遇区分＿４ */
     ztykazokumrtikgusdkbnx4 ,         /* （中継用）家族マル定記号世代区分＿４ */
     ztykazokumrtiagetyusihyjx4 ,         /* （中継用）家族マル定年令調整表示＿４ */
     ztykzkmrtikusnmnryoagex4 ,         /* （中継用）家族マル定更新満了年令＿４ */
     ztyyobiv4x4 ,         /* （中継用）予備項目Ｖ４＿４ */
     ztykzkmrtitkyknox5 ,         /* （中継用）家族マル定特約番号＿５ */
     ztykazokumrtisyuruikgux5 ,         /* （中継用）家族マル定種類記号＿５ */
     ztykazokumaruteikikanx5 ,         /* （中継用）家族マル定期間＿５ */
     ztykazokumrtiphrkkknx5 ,         /* （中継用）家族マル定Ｐ払込期間＿５ */
     ztykazokumaruteisx5 ,         /* （中継用）家族マル定Ｓ＿５ */
     ztykazokumaruteipx5 ,         /* （中継用）家族マル定Ｐ＿５ */
     ztykzkmrtihihknsyanmx5 ,         /* （中継用）家族マル定被保険者名＿５ */
     ztykzkmrtihihknsyseiymdx5 ,         /* （中継用）家族マル定被保険者生年月日＿５ */
     ztykzkmrtihihknsysibtkbnx5 ,         /* （中継用）家族マル定被保険者性別区分＿５ */
     ztykazokumrtihihknsyaagex5 ,         /* （中継用）家族マル定被保険者年令＿５ */
     ztykzkmrtimodsx5 ,         /* （中継用）家族マル定修正Ｓ＿５ */
     ztykazokumrtimodsskgnhyjx5 ,         /* （中継用）家族マル定修正Ｓ削減表示＿５ */
     ztykzkmrtitnknyugukbnx5 ,         /* （中継用）家族マル定転換優遇区分＿５ */
     ztykazokumrtikgusdkbnx5 ,         /* （中継用）家族マル定記号世代区分＿５ */
     ztykazokumrtiagetyusihyjx5 ,         /* （中継用）家族マル定年令調整表示＿５ */
     ztykzkmrtikusnmnryoagex5 ,         /* （中継用）家族マル定更新満了年令＿５ */
     ztyyobiv4x5 ,         /* （中継用）予備項目Ｖ４＿５ */
     ztykzkmrtitkyknox6 ,         /* （中継用）家族マル定特約番号＿６ */
     ztykazokumrtisyuruikgux6 ,         /* （中継用）家族マル定種類記号＿６ */
     ztykazokumaruteikikanx6 ,         /* （中継用）家族マル定期間＿６ */
     ztykazokumrtiphrkkknx6 ,         /* （中継用）家族マル定Ｐ払込期間＿６ */
     ztykazokumaruteisx6 ,         /* （中継用）家族マル定Ｓ＿６ */
     ztykazokumaruteipx6 ,         /* （中継用）家族マル定Ｐ＿６ */
     ztykzkmrtihihknsyanmx6 ,         /* （中継用）家族マル定被保険者名＿６ */
     ztykzkmrtihihknsyseiymdx6 ,         /* （中継用）家族マル定被保険者生年月日＿６ */
     ztykzkmrtihihknsysibtkbnx6 ,         /* （中継用）家族マル定被保険者性別区分＿６ */
     ztykazokumrtihihknsyaagex6 ,         /* （中継用）家族マル定被保険者年令＿６ */
     ztykzkmrtimodsx6 ,         /* （中継用）家族マル定修正Ｓ＿６ */
     ztykazokumrtimodsskgnhyjx6 ,         /* （中継用）家族マル定修正Ｓ削減表示＿６ */
     ztykzkmrtitnknyugukbnx6 ,         /* （中継用）家族マル定転換優遇区分＿６ */
     ztykazokumrtikgusdkbnx6 ,         /* （中継用）家族マル定記号世代区分＿６ */
     ztykazokumrtiagetyusihyjx6 ,         /* （中継用）家族マル定年令調整表示＿６ */
     ztykzkmrtikusnmnryoagex6 ,         /* （中継用）家族マル定更新満了年令＿６ */
     ztyyobiv4x6 ,         /* （中継用）予備項目Ｖ４＿６ */
     ztykzkmrtitkyknox7 ,         /* （中継用）家族マル定特約番号＿７ */
     ztykazokumrtisyuruikgux7 ,         /* （中継用）家族マル定種類記号＿７ */
     ztykazokumaruteikikanx7 ,         /* （中継用）家族マル定期間＿７ */
     ztykazokumrtiphrkkknx7 ,         /* （中継用）家族マル定Ｐ払込期間＿７ */
     ztykazokumaruteisx7 ,         /* （中継用）家族マル定Ｓ＿７ */
     ztykazokumaruteipx7 ,         /* （中継用）家族マル定Ｐ＿７ */
     ztykzkmrtihihknsyanmx7 ,         /* （中継用）家族マル定被保険者名＿７ */
     ztykzkmrtihihknsyseiymdx7 ,         /* （中継用）家族マル定被保険者生年月日＿７ */
     ztykzkmrtihihknsysibtkbnx7 ,         /* （中継用）家族マル定被保険者性別区分＿７ */
     ztykazokumrtihihknsyaagex7 ,         /* （中継用）家族マル定被保険者年令＿７ */
     ztykzkmrtimodsx7 ,         /* （中継用）家族マル定修正Ｓ＿７ */
     ztykazokumrtimodsskgnhyjx7 ,         /* （中継用）家族マル定修正Ｓ削減表示＿７ */
     ztykzkmrtitnknyugukbnx7 ,         /* （中継用）家族マル定転換優遇区分＿７ */
     ztykazokumrtikgusdkbnx7 ,         /* （中継用）家族マル定記号世代区分＿７ */
     ztykazokumrtiagetyusihyjx7 ,         /* （中継用）家族マル定年令調整表示＿７ */
     ztykzkmrtikusnmnryoagex7 ,         /* （中継用）家族マル定更新満了年令＿７ */
     ztyyobiv4x7 ,         /* （中継用）予備項目Ｖ４＿７ */
     ztykzkmrtitkyknox8 ,         /* （中継用）家族マル定特約番号＿８ */
     ztykazokumrtisyuruikgux8 ,         /* （中継用）家族マル定種類記号＿８ */
     ztykazokumaruteikikanx8 ,         /* （中継用）家族マル定期間＿８ */
     ztykazokumrtiphrkkknx8 ,         /* （中継用）家族マル定Ｐ払込期間＿８ */
     ztykazokumaruteisx8 ,         /* （中継用）家族マル定Ｓ＿８ */
     ztykazokumaruteipx8 ,         /* （中継用）家族マル定Ｐ＿８ */
     ztykzkmrtihihknsyanmx8 ,         /* （中継用）家族マル定被保険者名＿８ */
     ztykzkmrtihihknsyseiymdx8 ,         /* （中継用）家族マル定被保険者生年月日＿８ */
     ztykzkmrtihihknsysibtkbnx8 ,         /* （中継用）家族マル定被保険者性別区分＿８ */
     ztykazokumrtihihknsyaagex8 ,         /* （中継用）家族マル定被保険者年令＿８ */
     ztykzkmrtimodsx8 ,         /* （中継用）家族マル定修正Ｓ＿８ */
     ztykazokumrtimodsskgnhyjx8 ,         /* （中継用）家族マル定修正Ｓ削減表示＿８ */
     ztykzkmrtitnknyugukbnx8 ,         /* （中継用）家族マル定転換優遇区分＿８ */
     ztykazokumrtikgusdkbnx8 ,         /* （中継用）家族マル定記号世代区分＿８ */
     ztykazokumrtiagetyusihyjx8 ,         /* （中継用）家族マル定年令調整表示＿８ */
     ztykzkmrtikusnmnryoagex8 ,         /* （中継用）家族マル定更新満了年令＿８ */
     ztyyobiv4x8 ,         /* （中継用）予備項目Ｖ４＿８ */
     ztykzkmrtitkyknox9 ,         /* （中継用）家族マル定特約番号＿９ */
     ztykazokumrtisyuruikgux9 ,         /* （中継用）家族マル定種類記号＿９ */
     ztykazokumaruteikikanx9 ,         /* （中継用）家族マル定期間＿９ */
     ztykazokumrtiphrkkknx9 ,         /* （中継用）家族マル定Ｐ払込期間＿９ */
     ztykazokumaruteisx9 ,         /* （中継用）家族マル定Ｓ＿９ */
     ztykazokumaruteipx9 ,         /* （中継用）家族マル定Ｐ＿９ */
     ztykzkmrtihihknsyanmx9 ,         /* （中継用）家族マル定被保険者名＿９ */
     ztykzkmrtihihknsyseiymdx9 ,         /* （中継用）家族マル定被保険者生年月日＿９ */
     ztykzkmrtihihknsysibtkbnx9 ,         /* （中継用）家族マル定被保険者性別区分＿９ */
     ztykazokumrtihihknsyaagex9 ,         /* （中継用）家族マル定被保険者年令＿９ */
     ztykzkmrtimodsx9 ,         /* （中継用）家族マル定修正Ｓ＿９ */
     ztykazokumrtimodsskgnhyjx9 ,         /* （中継用）家族マル定修正Ｓ削減表示＿９ */
     ztykzkmrtitnknyugukbnx9 ,         /* （中継用）家族マル定転換優遇区分＿９ */
     ztykazokumrtikgusdkbnx9 ,         /* （中継用）家族マル定記号世代区分＿９ */
     ztykazokumrtiagetyusihyjx9 ,         /* （中継用）家族マル定年令調整表示＿９ */
     ztykzkmrtikusnmnryoagex9 ,         /* （中継用）家族マル定更新満了年令＿９ */
     ztyyobiv4x9 ,         /* （中継用）予備項目Ｖ４＿９ */
     ztykzkmrtitkyknox10 ,         /* （中継用）家族マル定特約番号＿１０ */
     ztykazokumrtisyuruikgux10 ,         /* （中継用）家族マル定種類記号＿１０ */
     ztykazokumaruteikikanx10 ,         /* （中継用）家族マル定期間＿１０ */
     ztykazokumrtiphrkkknx10 ,         /* （中継用）家族マル定Ｐ払込期間＿１０ */
     ztykazokumaruteisx10 ,         /* （中継用）家族マル定Ｓ＿１０ */
     ztykazokumaruteipx10 ,         /* （中継用）家族マル定Ｐ＿１０ */
     ztykzkmrtihihknsyanmx10 ,         /* （中継用）家族マル定被保険者名＿１０ */
     ztykzkmrtihihknsyseiymdx10 ,         /* （中継用）家族マル定被保険者生年月日＿１０ */
     ztykzkmrtihihknsysibtkbnx10 ,         /* （中継用）家族マル定被保険者性別区分＿１０ */
     ztykazokumrtihihknsyaagex10 ,         /* （中継用）家族マル定被保険者年令＿１０ */
     ztykzkmrtimodsx10 ,         /* （中継用）家族マル定修正Ｓ＿１０ */
     ztykazokumrtimodsskgnhyjx10 ,         /* （中継用）家族マル定修正Ｓ削減表示＿１０ */
     ztykzkmrtitnknyugukbnx10 ,         /* （中継用）家族マル定転換優遇区分＿１０ */
     ztykazokumrtikgusdkbnx10 ,         /* （中継用）家族マル定記号世代区分＿１０ */
     ztykazokumrtiagetyusihyjx10 ,         /* （中継用）家族マル定年令調整表示＿１０ */
     ztykzkmrtikusnmnryoagex10 ,         /* （中継用）家族マル定更新満了年令＿１０ */
     ztyyobiv4x10 ,         /* （中継用）予備項目Ｖ４＿１０ */
     ztynkshrtkykhuhokbnx1 ,         /* （中継用）年金支払特約付保区分＿１ */
     ztynkshrtkyknksyuruikbnx1 ,         /* （中継用）年金支払特約年金種類区分＿１ */
     ztynkshrtkyknkkknx1 ,         /* （中継用）年金支払特約年金期間＿１ */
     ztynkshrtkyknknengkx1 ,         /* （中継用）年金支払特約年金年額＿１ */
     ztynkshrtkykduketorihhkbnx1 ,         /* （中継用）年金支払特約Ｄ受取方法区分＿１ */
     ztyyobiv10 ,         /* （中継用）予備項目Ｖ１０ */
     ztynkshrtkykhuhokbnx2 ,         /* （中継用）年金支払特約付保区分＿２ */
     ztynkshrtkyknksyuruikbnx2 ,         /* （中継用）年金支払特約年金種類区分＿２ */
     ztynkshrtkyknkkknx2 ,         /* （中継用）年金支払特約年金期間＿２ */
     ztynkshrtkyknknengkx2 ,         /* （中継用）年金支払特約年金年額＿２ */
     ztynkshrtkykduketorihhkbnx2 ,         /* （中継用）年金支払特約Ｄ受取方法区分＿２ */
     ztyyobiv10x2 ,         /* （中継用）予備項目Ｖ１０＿２ */
     ztysyougaitkyksyuruikgu ,         /* （中継用）傷害特約種類記号 */
     ztysyougaitokuyakukikan ,         /* （中継用）傷害特約期間 */
     ztysyougaitkykphrkkkn ,         /* （中継用）傷害特約Ｐ払込期間 */
     ztysyougaitokuyakus ,         /* （中継用）傷害特約Ｓ */
     ztysyougaitokuyakup ,         /* （中継用）傷害特約Ｐ */
     ztysyougaitkkatakbn ,         /* （中継用）傷害特約型区分 */
     ztysyougaitkykkgusdkbn ,         /* （中継用）傷害特約記号世代区分 */
     ztysyugitkykpwrbkkbn ,         /* （中継用）傷害特約Ｐ割引区分 */
     ztysyougaitkykkusnmnryoage ,         /* （中継用）傷害特約更新満了年令 */
     ztyyobiv5x2 ,         /* （中継用）予備項目Ｖ５＿２ */
     ztysigiwrmstkyksyuruikgu ,         /* （中継用）災害割増特約種類記号 */
     ztysigiwrmstkykkkn ,         /* （中継用）災害割増特約期間 */
     ztysaigaiwrmstkykphrkkkn ,         /* （中継用）災害割増特約Ｐ払込期間 */
     ztysaigaiwarimasitokuyakus ,         /* （中継用）災害割増特約Ｓ */
     ztysaigaiwarimasitokuyakup ,         /* （中継用）災害割増特約Ｐ */
     ztysaigaiwrmstkykkgusdkbn ,         /* （中継用）災害割増特約記号世代区分 */
     ztysigiwrmstkykpwrbkkbn ,         /* （中継用）災害割増特約Ｐ割引区分 */
     ztysigiwrmstkykkusnmnryoage ,         /* （中継用）災害割増特約更新満了年令 */
     ztyyobiv5x3 ,         /* （中継用）予備項目Ｖ５＿３ */
     ztysiginyuintkyksyuruikgu ,         /* （中継用）災害入院特約種類記号 */
     ztysiginyuintkykkkn ,         /* （中継用）災害入院特約期間 */
     ztysaigainyuintkykphrkkkn ,         /* （中継用）災害入院特約Ｐ払込期間 */
     ztysiginyuintkykntgk ,         /* （中継用）災害入院特約日額 */
     ztysiginyuintkykgtkbn ,         /* （中継用）災害入院特約型区分 */
     ztysaigainyuuintokuyakup ,         /* （中継用）災害入院特約Ｐ */
     ztysaigainyuintkykkgusdkbn ,         /* （中継用）災害入院特約記号世代区分 */
     ztysiginyuintkykpwrbkkbn ,         /* （中継用）災害入院特約Ｐ割引区分 */
     ztyyobiv7 ,         /* （中継用）予備項目Ｖ７ */
     ztysppinyuintkyksyuruikgu ,         /* （中継用）疾病入院特約種類記号 */
     ztysppinyuintkykkkn ,         /* （中継用）疾病入院特約期間 */
     ztysppinyuuintkykphrkkkn ,         /* （中継用）疾病入院特約Ｐ払込期間 */
     ztysppinyuintkykntgk ,         /* （中継用）疾病入院特約日額 */
     ztysppinyuintkykgtkbn ,         /* （中継用）疾病入院特約型区分 */
     ztysippeinyuuintokuyakup ,         /* （中継用）疾病入院特約Ｐ */
     ztysppinyuintkjyuryumshyutn ,         /* （中継用）疾病入院特条料増標点 */
     ztysippeinyuuintokujyoup ,         /* （中継用）疾病入院特条Ｐ */
     ztysppinyuintktbicdx1 ,         /* （中継用）疾病入院特定部位コード＿１ */
     ztysppinyuinhtnpkknx1 ,         /* （中継用）疾病入院不担保期間＿１ */
     ztysppinyuintktbicdx2 ,         /* （中継用）疾病入院特定部位コード＿２ */
     ztysppinyuinhtnpkknx2 ,         /* （中継用）疾病入院不担保期間＿２ */
     ztysppinyuuintkykkgusdkbn ,         /* （中継用）疾病入院特約記号世代区分 */
     ztysppinyuintkykpwrbkkbn ,         /* （中継用）疾病入院特約Ｐ割引区分 */
     ztyyobiv7x2 ,         /* （中継用）予備項目Ｖ７＿２ */
     ztysijnbyutkyksyuruikgu ,         /* （中継用）成人病特約種類記号 */
     ztyseijinbyoutokuyakukikan ,         /* （中継用）成人病特約期間 */
     ztyseijinbyoutkykphrkkkn ,         /* （中継用）成人病特約Ｐ払込期間 */
     ztyseijinbyoutokuyakuntgk ,         /* （中継用）成人病特約日額 */
     ztyseijinbyoutokuyakup ,         /* （中継用）成人病特約Ｐ */
     ztysijnbyutkjyuryumshyutn ,         /* （中継用）成人病特条料増標点 */
     ztyseijinbyoutokujyoup ,         /* （中継用）成人病特条Ｐ */
     ztyseijinbyoutokuteibuicdx1 ,         /* （中継用）成人病特定部位コード＿１ */
     ztyseijinbyouhutanpokikanx1 ,         /* （中継用）成人病不担保期間＿１ */
     ztyseijinbyoutokuteibuicdx2 ,         /* （中継用）成人病特定部位コード＿２ */
     ztyseijinbyouhutanpokikanx2 ,         /* （中継用）成人病不担保期間＿２ */
     ztyseijinbyoutkykkgusdkbn ,         /* （中継用）成人病特約記号世代区分 */
     ztysijnbyutkykgankyuhgtkbn ,         /* （中継用）成人病特約ガン給付型区分 */
     ztysijnbyutkykpwrbkkbn ,         /* （中継用）成人病特約Ｐ割引区分 */
     ztysijnbyutkykkusnmnryoage ,         /* （中継用）成人病特約更新満了年令 */
     ztyyobiv4x11 ,         /* （中継用）予備項目Ｖ４＿１１ */
     ztyheiyoubaraikbn ,         /* （中継用）併用払区分 */
     ztyhiyubriaitsyono ,         /* （中継用）併用払相手証券番号 */
     ztyhiyubriaithrkkeirokbn ,         /* （中継用）併用払相手払込経路区分 */
     ztyheiyoubaraiaitekihons ,         /* （中継用）併用払相手基本Ｓ */
     ztyhiyubrigukitnknitjbrkhns ,         /* （中継用）併用払合計転換一時払基本Ｓ */
     ztyheiyoubaraiaitesibous ,         /* （中継用）併用払相手死亡Ｓ */
     ztyhiyubrigukitnknitjbrsbus ,         /* （中継用）併用払合計転換一時払死亡Ｓ */
     ztyheiyoubaraiaitesyuuseis ,         /* （中継用）併用払相手修正Ｓ */
     ztyheiyoubaraiaitehrkp ,         /* （中継用）併用払相手払込Ｐ */
     ztyhiyubriaitsykykp ,         /* （中継用）併用払相手主契約Ｐ */
     ztyheiyoubaraiaitemrtis ,         /* （中継用）併用払相手マル定Ｓ */
     ztyhiyubrigukiaitkzkmrtis ,         /* （中継用）併用払合計相手家族マル定Ｓ */
     ztytukibaraikyktenkanhyj ,         /* （中継用）月払契約転換表示 */
     ztybonusharaihrkkigetu1 ,         /* （中継用）ボーナス払払込期月１ */
     ztybonusharaihrkkigetu2 ,         /* （中継用）ボーナス払払込期月２ */
     ztyhiyubriaitsiznmrtis ,         /* （中継用）併用払相手生存マル定Ｓ */
     ztyhiyubriaittignmrtis ,         /* （中継用）併用払相手逓減マル定Ｓ */
     ztytkjykbn ,         /* （中継用）特条区分 */
     ztysakugenkikan ,         /* （中継用）削減期間 */
     ztyryoumasihyouten ,         /* （中継用）料増標点 */
     ztytokujyoup ,         /* （中継用）特条Ｐ */
     ztyhjncd ,         /* （中継用）法人コード */
     ztyhjnjigyosyocd ,         /* （中継用）法人事業所コード */
     ztyjyuugyouinsuu ,         /* （中継用）従業員数 */
     ztyiktkaisuu ,         /* （中継用）一括回数 */
     ztyznnkai ,         /* （中継用）前納回数 */
     ztykyktsnatkitkykkbn ,         /* （中継用）契約通算扱特約区分 */
     ztykyktsnatkitkykstagekbn ,         /* （中継用）契約通算扱特約ステージ区分 */
     ztypmentokuyakukbn ,         /* （中継用）Ｐ免特約区分 */
     ztyyobiv3 ,         /* （中継用）予備項目Ｖ３ */
     ztytkykznnunyukngk ,         /* （中継用）特約前納入金額 */
     ztysyokaipnyuukinhouhoukbn ,         /* （中継用）初回Ｐ入金方法区分 */
     ztyhtnknkyksyonox1 ,         /* （中継用）被転換契約証券番号＿１ */
     ztyhtnknkykhknsyuruikgux1 ,         /* （中継用）被転換契約保険種類記号＿１ */
     ztytenkanuketukeymdx1 ,         /* （中継用）転換受付年月日＿１ */
     ztyhtnknkykkykymdx1 ,         /* （中継用）被転換契約契約年月日＿１ */
     ztyhtnknkykhknkknx1 ,         /* （中継用）被転換契約保険期間＿１ */
     ztyhtnknkykphrkkknx1 ,         /* （中継用）被転換契約Ｐ払込期間＿１ */
     ztyhtnknkykhrkkaisuukbnx1 ,         /* （中継用）被転換契約払込回数区分＿１ */
     ztyhtnknkykhrkkeirokbnx1 ,         /* （中継用）被転換契約払込経路区分＿１ */
     ztytnknuktkzngtkijyuhyjx1 ,         /* （中継用）転換受付前月計上表示＿１ */
     ztyhtnknkykmrtisyuruikgux1 ,         /* （中継用）被転換契約マル定種類記号＿１ */
     ztyhtnknkyksyonox2 ,         /* （中継用）被転換契約証券番号＿２ */
     ztyhtnknkykhknsyuruikgux2 ,         /* （中継用）被転換契約保険種類記号＿２ */
     ztytenkanuketukeymdx2 ,         /* （中継用）転換受付年月日＿２ */
     ztyhtnknkykkykymdx2 ,         /* （中継用）被転換契約契約年月日＿２ */
     ztyhtnknkykhknkknx2 ,         /* （中継用）被転換契約保険期間＿２ */
     ztyhtnknkykphrkkknx2 ,         /* （中継用）被転換契約Ｐ払込期間＿２ */
     ztyhtnknkykhrkkaisuukbnx2 ,         /* （中継用）被転換契約払込回数区分＿２ */
     ztyhtnknkykhrkkeirokbnx2 ,         /* （中継用）被転換契約払込経路区分＿２ */
     ztytnknuktkzngtkijyuhyjx2 ,         /* （中継用）転換受付前月計上表示＿２ */
     ztyhtnknkykmrtisyuruikgux2 ,         /* （中継用）被転換契約マル定種類記号＿２ */
     ztyhtnknkyksyonox3 ,         /* （中継用）被転換契約証券番号＿３ */
     ztyhtnknkykhknsyuruikgux3 ,         /* （中継用）被転換契約保険種類記号＿３ */
     ztytenkanuketukeymdx3 ,         /* （中継用）転換受付年月日＿３ */
     ztyhtnknkykkykymdx3 ,         /* （中継用）被転換契約契約年月日＿３ */
     ztyhtnknkykhknkknx3 ,         /* （中継用）被転換契約保険期間＿３ */
     ztyhtnknkykphrkkknx3 ,         /* （中継用）被転換契約Ｐ払込期間＿３ */
     ztyhtnknkykhrkkaisuukbnx3 ,         /* （中継用）被転換契約払込回数区分＿３ */
     ztyhtnknkykhrkkeirokbnx3 ,         /* （中継用）被転換契約払込経路区分＿３ */
     ztytnknuktkzngtkijyuhyjx3 ,         /* （中継用）転換受付前月計上表示＿３ */
     ztyhtnknkykmrtisyuruikgux3 ,         /* （中継用）被転換契約マル定種類記号＿３ */
     ztyhtnknkyksyonox4 ,         /* （中継用）被転換契約証券番号＿４ */
     ztyhtnknkykhknsyuruikgux4 ,         /* （中継用）被転換契約保険種類記号＿４ */
     ztytenkanuketukeymdx4 ,         /* （中継用）転換受付年月日＿４ */
     ztyhtnknkykkykymdx4 ,         /* （中継用）被転換契約契約年月日＿４ */
     ztyhtnknkykhknkknx4 ,         /* （中継用）被転換契約保険期間＿４ */
     ztyhtnknkykphrkkknx4 ,         /* （中継用）被転換契約Ｐ払込期間＿４ */
     ztyhtnknkykhrkkaisuukbnx4 ,         /* （中継用）被転換契約払込回数区分＿４ */
     ztyhtnknkykhrkkeirokbnx4 ,         /* （中継用）被転換契約払込経路区分＿４ */
     ztytnknuktkzngtkijyuhyjx4 ,         /* （中継用）転換受付前月計上表示＿４ */
     ztyhtnknkykmrtisyuruikgux4 ,         /* （中継用）被転換契約マル定種類記号＿４ */
     ztyhtnknkyksyonox5 ,         /* （中継用）被転換契約証券番号＿５ */
     ztyhtnknkykhknsyuruikgux5 ,         /* （中継用）被転換契約保険種類記号＿５ */
     ztytenkanuketukeymdx5 ,         /* （中継用）転換受付年月日＿５ */
     ztyhtnknkykkykymdx5 ,         /* （中継用）被転換契約契約年月日＿５ */
     ztyhtnknkykhknkknx5 ,         /* （中継用）被転換契約保険期間＿５ */
     ztyhtnknkykphrkkknx5 ,         /* （中継用）被転換契約Ｐ払込期間＿５ */
     ztyhtnknkykhrkkaisuukbnx5 ,         /* （中継用）被転換契約払込回数区分＿５ */
     ztyhtnknkykhrkkeirokbnx5 ,         /* （中継用）被転換契約払込経路区分＿５ */
     ztytnknuktkzngtkijyuhyjx5 ,         /* （中継用）転換受付前月計上表示＿５ */
     ztyhtnknkykmrtisyuruikgux5 ,         /* （中継用）被転換契約マル定種類記号＿５ */
     ztyhtnknkyksyonox6 ,         /* （中継用）被転換契約証券番号＿６ */
     ztyhtnknkykhknsyuruikgux6 ,         /* （中継用）被転換契約保険種類記号＿６ */
     ztytenkanuketukeymdx6 ,         /* （中継用）転換受付年月日＿６ */
     ztyhtnknkykkykymdx6 ,         /* （中継用）被転換契約契約年月日＿６ */
     ztyhtnknkykhknkknx6 ,         /* （中継用）被転換契約保険期間＿６ */
     ztyhtnknkykphrkkknx6 ,         /* （中継用）被転換契約Ｐ払込期間＿６ */
     ztyhtnknkykhrkkaisuukbnx6 ,         /* （中継用）被転換契約払込回数区分＿６ */
     ztyhtnknkykhrkkeirokbnx6 ,         /* （中継用）被転換契約払込経路区分＿６ */
     ztytnknuktkzngtkijyuhyjx6 ,         /* （中継用）転換受付前月計上表示＿６ */
     ztyhtnknkykmrtisyuruikgux6 ,         /* （中継用）被転換契約マル定種類記号＿６ */
     ztygukihtnknkykkhns ,         /* （中継用）合計被転換契約基本Ｓ */
     ztygukihtnknkyksbus ,         /* （中継用）合計被転換契約死亡Ｓ */
     ztygukihtnknkykhntiyup ,         /* （中継用）合計被転換契約判定用Ｐ */
     ztygukihtnknkyksigwrmstkyks ,         /* （中継用）合計被転換契約災害割増特約Ｓ */
     ztygukihtnknkyksyugitkyks ,         /* （中継用）合計被転換契約傷害特約Ｓ */
     ztygukihtnknsignyintkykntgk ,         /* （中継用）合計被転換災害入院特約日額 */
     ztygukihtnknknkutkykntgk ,         /* （中継用）合計被転換健康特約日額 */
     ztygukihtnknkykmods ,         /* （中継用）合計被転換契約修正Ｓ */
     ztygoukeitenkankakaku ,         /* （中継用）合計転換価格 */
     ztygukitnknjsknnjynbkn ,         /* （中継用）合計転換時責任準備金 */
     ztygukitnknsisnkstkkngk ,         /* （中継用）合計転換精算貸付金額 */
     ztygukitnknsisnttkekngk ,         /* （中継用）合計転換精算立替金額 */
     ztygoukeitenkanseisand ,         /* （中継用）合計転換精算Ｄ */
     ztygukitnknsisnmkikp ,         /* （中継用）合計転換精算未経過Ｐ */
     ztygukitnknsisnsntkngk ,         /* （中継用）合計転換精算その他金額 */
     ztygukitnknkhnbbnkiykkujygk ,         /* （中継用）合計転換基本部分解約控除額 */
     ztygukitnkntikbbnkiykkujygk ,         /* （中継用）合計転換定期部分解約控除額 */
     ztygukitnknitjbrtiks ,         /* （中継用）合計転換一時払定期Ｓ */
     ztysethokenno ,         /* （中継用）セット保険番号 */
     ztysckbn ,         /* （中継用）ＳＣ区分 */
     ztyenjyosyacd ,         /* （中継用）援助者コード */
     ztynaibuwarimodosigaku ,         /* （中継用）内部割戻額 */
     ztykeiyakukakuninsyuruikbn ,         /* （中継用）契約確認種類区分 */
     ztysoujikeitenkanhyouji ,         /* （中継用）相似形転換表示 */
     ztytenkanjisketteihouhoukbn ,         /* （中継用）転換時Ｓ決定方法区分 */
     ztykeikanensuukbn ,         /* （中継用）経過年数区分 */
     ztyhtnknkykhhknsytisyukbnx1 ,         /* （中継用）被転換契約被保険者対象区分＿１ */
     ztyhtnknkykhhknsytisyukbnx2 ,         /* （中継用）被転換契約被保険者対象区分＿２ */
     ztyhtnknkykhhknsytisyukbnx3 ,         /* （中継用）被転換契約被保険者対象区分＿３ */
     ztyhtnknkykhhknsytisyukbnx4 ,         /* （中継用）被転換契約被保険者対象区分＿４ */
     ztyhtnknkykhhknsytisyukbnx5 ,         /* （中継用）被転換契約被保険者対象区分＿５ */
     ztyhtnknkykhhknsytisyukbnx6 ,         /* （中継用）被転換契約被保険者対象区分＿６ */
     ztykktijgukipbbntnkns ,         /* （中継用）確定時合計Ｐ部分転換Ｓ */
     ztysyonendosyokaip ,         /* （中継用）初年度初回Ｐ */
     ztysyonendo2kaimeikoup ,         /* （中継用）初年度２回目以降Ｐ */
     ztyjinendoikoup ,         /* （中継用）次年度以降Ｐ */
     ztysyukeiyakusikyuukisogaku ,         /* （中継用）主契約支給基礎額 */
     ztysykyknenhantatskyuksgk ,         /* （中継用）主契約年半手当支給基礎額 */
     ztymaruteisikyuukisogaku ,         /* （中継用）マル定支給基礎額 */
     ztyitjbrzugkskyuksgkx1 ,         /* （中継用）一時払増額支給基礎額＿１ */
     ztyitjbrzugkskyuksgkx2 ,         /* （中継用）一時払増額支給基礎額＿２ */
     ztyitjbrzgknnhntatskyksgkx1 ,         /* （中継用）一時払増額年半手当支給基礎額＿１ */
     ztyitjbrzgknnhntatskyksgkx2 ,         /* （中継用）一時払増額年半手当支給基礎額＿２ */
     ztykzkmrtiskyuksgk ,         /* （中継用）家族マル定支給基礎額 */
     ztyitibitjbrskyuksgk ,         /* （中継用）一部一時払支給基礎額 */
     ztyitbitjbrnnhntatskyuksgk ,         /* （中継用）一部一時払年半手当支給基礎額 */
     ztysykykksnbsyutat ,         /* （中継用）主契約加算募集手当 */
     ztyitjbrzugkksnbsyutatx1 ,         /* （中継用）一時払増額加算募集手当＿１ */
     ztyitjbrzugkksnbsyutatx2 ,         /* （中継用）一時払増額加算募集手当＿２ */
     ztyitibitjbrksnbsyutat ,         /* （中継用）一部一時払加算募集手当 */
     ztyjyunkensuu ,         /* （中継用）純件数 */
     ztykansankensuu ,         /* （中継用）換算件数 */
     ztyitibuitijibaraikikan ,         /* （中継用）一部一時払期間 */
     ztyitibuitijibarais ,         /* （中継用）一部一時払Ｓ */
     ztyitibuitijibaraip ,         /* （中継用）一部一時払Ｐ */
     ztyitibitjbrsdtpdtkbn ,         /* （中継用）一部一時払Ｓ建Ｐ建区分 */
     ztyitibuitijibaraisyuuseis ,         /* （中継用）一部一時払修正Ｓ */
     ztyitibitjbrmodsskgnhyj ,         /* （中継用）一部一時払修正Ｓ削減表示 */
     ztysuuriyousyoriym ,         /* （中継用）数理用処理年月 */
     ztysyosinsinsahouhoukbn ,         /* （中継用）初診診査方法区分 */
     ztysaisinsinsahouhoukbn ,         /* （中継用）再診診査方法区分 */
     ztyseizonmrtisyuruikgu ,         /* （中継用）生存マル定種類記号 */
     ztyseizonmaruteikikan ,         /* （中継用）生存マル定期間 */
     ztyseizonmrtiphrkkkn ,         /* （中継用）生存マル定Ｐ払込期間 */
     ztyseizonmaruteis ,         /* （中継用）生存マル定Ｓ */
     ztyseizonmaruteip ,         /* （中継用）生存マル定Ｐ */
     ztyseizonmaruteisyuuseis ,         /* （中継用）生存マル定修正Ｓ */
     ztyseizonmrtimodsskgnhyj ,         /* （中継用）生存マル定修正Ｓ削減表示 */
     ztysiznmrtitkjyukbn ,         /* （中継用）生存マル定特条区分 */
     ztysiznmrtitkjyuskgnkkn ,         /* （中継用）生存マル定特条削減期間 */
     ztysiznmrtitkjyuryumshyutn ,         /* （中継用）生存マル定特条料増標点 */
     ztysiznmrtitkjyup ,         /* （中継用）生存マル定特条Ｐ */
     ztysiznmrtiskyuksgk ,         /* （中継用）生存マル定支給基礎額 */
     ztyhtnknkyksiznmrtsyrikgux1 ,         /* （中継用）被転換契約生存マル定種類記号＿１ */
     ztyhtnknkyksiznmrtsyrikgux2 ,         /* （中継用）被転換契約生存マル定種類記号＿２ */
     ztyhtnknkyksiznmrtsyrikgux3 ,         /* （中継用）被転換契約生存マル定種類記号＿３ */
     ztyhtnknkyksiznmrtsyrikgux4 ,         /* （中継用）被転換契約生存マル定種類記号＿４ */
     ztyhtnknkyksiznmrtsyrikgux5 ,         /* （中継用）被転換契約生存マル定種類記号＿５ */
     ztyhtnknkyksiznmrtsyrikgux6 ,         /* （中継用）被転換契約生存マル定種類記号＿６ */
     ztysuryusiznmrtipwrbkkbn ,         /* （中継用）数理用生存マル定Ｐ割引区分 */
     ztysiznmrtipwrbkkbn ,         /* （中継用）生存マル定Ｐ割引区分 */
     ztysiznmrtitnknyugukbn ,         /* （中継用）生存マル定転換優遇区分 */
     ztyseizonmrtikgusdkbn ,         /* （中継用）生存マル定記号世代区分 */
     ztyyobiv1 ,         /* （中継用）予備項目Ｖ１ */
     ztydai2hihokensyamei ,         /* （中継用）第２被保険者名 */
     ztydai2kanjihihokensyamei ,         /* （中継用）第２漢字被保険者名 */
     ztydai2hihokensyaseiymd ,         /* （中継用）第２被保険者生年月日 */
     ztydai2hihokensyaseibetukbn ,         /* （中継用）第２被保険者性別区分 */
     ztydai2hihknsyahnskhkncd ,         /* （中継用）第２被保険者本籍府県コード */
     ztydai2hhknnen ,         /* （中継用）第２被保険者年令 */
     ztydai2hihknsyakikykarihyj ,         /* （中継用）第２被保険者既契約有表示 */
     ztykyksydi2hihknsyaduithyj ,         /* （中継用）契約者第２被保険者同一表示 */
     ztydai2syosinsinsahouhoukbn ,         /* （中継用）第２初診診査方法区分 */
     ztydai2saisinsinsahouhoukbn ,         /* （中継用）第２再診診査方法区分 */
     ztydai2syokugyoucd ,         /* （中継用）第２職業コード */
     ztydai2sakugenkikan ,         /* （中継用）第２削減期間 */
     ztydai2ryoumasihyouten ,         /* （中継用）第２料増標点 */
     ztymrtidi2skgnkkn ,         /* （中継用）マル定第２削減期間 */
     ztymrtidi2ryumshyutn ,         /* （中継用）マル定第２料増標点 */
     ztydi2kykkknnsyrikbn ,         /* （中継用）第２契約確認種類区分 */
     ztytignmrtidi2skgnkkn ,         /* （中継用）逓減マル定第２削減期間 */
     ztytignmrtidi2ryumshyutn ,         /* （中継用）逓減マル定第２料増標点 */
     ztydai2syosinhonninkknnkbn ,         /* （中継用）第２初診本人確認区分 */
     ztydi2sisnhonninkknnkbn ,         /* （中継用）第２再診本人確認区分 */
     ztyyobiv9x6 ,         /* （中継用）予備項目Ｖ９＿６ */
     ztydi2syugitkyksyrikgu ,         /* （中継用）第２傷害特約種類記号 */
     ztydai2syougaitokuyakukikan ,         /* （中継用）第２傷害特約期間 */
     ztydi2syugitkykphrkkkn ,         /* （中継用）第２傷害特約Ｐ払込期間 */
     ztydai2syougaitokuyakus ,         /* （中継用）第２傷害特約Ｓ */
     ztydai2syougaitokuyakup ,         /* （中継用）第２傷害特約Ｐ */
     ztydi2syugitkykgtkbn ,         /* （中継用）第２傷害特約型区分 */
     ztydi2syugitkykkgusdkbn ,         /* （中継用）第２傷害特約記号世代区分 */
     ztydi2syugitkykpwrbkkbn ,         /* （中継用）第２傷害特約Ｐ割引区分 */
     ztyyobiv8 ,         /* （中継用）予備項目Ｖ８ */
     ztydi2sigiwrmstkyksyrikgu ,         /* （中継用）第２災害割増特約種類記号 */
     ztydi2sigiwrmstkykkkn ,         /* （中継用）第２災害割増特約期間 */
     ztydi2sigiwrmstkykphrkkkn ,         /* （中継用）第２災害割増特約Ｐ払込期間 */
     ztydi2sigiwrmstkyks ,         /* （中継用）第２災害割増特約Ｓ */
     ztydi2sigiwrmstkykp ,         /* （中継用）第２災害割増特約Ｐ */
     ztydi2sigiwrmstkykkgusdkbn ,         /* （中継用）第２災害割増特約記号世代区分 */
     ztydi2sigiwrmstkykpwrbkkbn ,         /* （中継用）第２災害割増特約Ｐ割引区分 */
     ztyyobiv9x7 ,         /* （中継用）予備項目Ｖ９＿７ */
     ztydi2siginyuintkyksyrikgu ,         /* （中継用）第２災害入院特約種類記号 */
     ztydi2siginyuintkykkkn ,         /* （中継用）第２災害入院特約期間 */
     ztydi2siginyuintkykphrkkkn ,         /* （中継用）第２災害入院特約Ｐ払込期間 */
     ztydi2siginyuintkykntgk ,         /* （中継用）第２災害入院特約日額 */
     ztydi2siginyuintkykp ,         /* （中継用）第２災害入院特約Ｐ */
     ztydi2siginyuintkykgtkbn ,         /* （中継用）第２災害入院特約型区分 */
     ztydi2siginyintkykkgusdkbn ,         /* （中継用）第２災害入院特約記号世代区分 */
     ztydi2siginyuintkykpwrbkkbn ,         /* （中継用）第２災害入院特約Ｐ割引区分 */
     ztyyobiv10x3 ,         /* （中継用）予備項目Ｖ１０＿３ */
     ztydi2sppinyuintkyksyrikgu ,         /* （中継用）第２疾病入院特約種類記号 */
     ztydi2sppinyuintkykkkn ,         /* （中継用）第２疾病入院特約期間 */
     ztydi2sppinyuintkykphrkkkn ,         /* （中継用）第２疾病入院特約Ｐ払込期間 */
     ztydi2sppinyuintkykntgk ,         /* （中継用）第２疾病入院特約日額 */
     ztydi2sppinyuintkykp ,         /* （中継用）第２疾病入院特約Ｐ */
     ztydi2sppinyuintkykgtkbn ,         /* （中継用）第２疾病入院特約型区分 */
     ztydi2sppinyintkjyryumshytn ,         /* （中継用）第２疾病入院特条料増標点 */
     ztydi2sppinyuintkjyup ,         /* （中継用）第２疾病入院特条Ｐ */
     ztydi2sppinyuintktbicdx1 ,         /* （中継用）第２疾病入院特定部位コード＿１ */
     ztydi2sppinyuinhtnpkknx1 ,         /* （中継用）第２疾病入院不担保期間＿１ */
     ztydi2sppinyuintktbicdx2 ,         /* （中継用）第２疾病入院特定部位コード＿２ */
     ztydi2sppinyuinhtnpkknx2 ,         /* （中継用）第２疾病入院不担保期間＿２ */
     ztydi2sppinyintkykkgusdkbn ,         /* （中継用）第２疾病入院特約記号世代区分 */
     ztydi2sppinyuintkykpwrbkkbn ,         /* （中継用）第２疾病入院特約Ｐ割引区分 */
     ztyyobiv3x2 ,         /* （中継用）予備項目Ｖ３＿２ */
     ztydi2sijnbyutkyksyrikgu ,         /* （中継用）第２成人病特約種類記号 */
     ztydi2sijnbyutkykkkn ,         /* （中継用）第２成人病特約期間 */
     ztydi2sijnbyutkykphrkkkn ,         /* （中継用）第２成人病特約Ｐ払込期間 */
     ztydi2sijnbyutkykntgk ,         /* （中継用）第２成人病特約日額 */
     ztydai2seijinbyoutokuyakup ,         /* （中継用）第２成人病特約Ｐ */
     ztydi2sijnbyutkjyurymshytn ,         /* （中継用）第２成人病特条料増標点 */
     ztydai2seijinbyoutokujyoup ,         /* （中継用）第２成人病特条Ｐ */
     ztydi2sijnbyutktbicdx1 ,         /* （中継用）第２成人病特定部位コード＿１ */
     ztydi2sijnbyuhtnpkknx1 ,         /* （中継用）第２成人病不担保期間＿１ */
     ztydi2sijnbyutktbicdx2 ,         /* （中継用）第２成人病特定部位コード＿２ */
     ztydi2sijnbyuhtnpkknx2 ,         /* （中継用）第２成人病不担保期間＿２ */
     ztydi2sijnbyutkykkgusdkbn ,         /* （中継用）第２成人病特約記号世代区分 */
     ztydi2sijnbytkykgankyhgtkbn ,         /* （中継用）第２成人病特約ガン給付型区分 */
     ztydi2sijnbyutkykpwrbkkbn ,         /* （中継用）第２成人病特約Ｐ割引区分 */
     ztyyobiv3x3 ,         /* （中継用）予備項目Ｖ３＿３ */
     ztydai2jyoukentukihyouji ,         /* （中継用）第２条件付表示 */
     ztytignmrtisyukgu ,         /* （中継用）逓減マル定種類記号 */
     ztyteigenmaruteikikan ,         /* （中継用）逓減マル定期間 */
     ztyteigenmrtiphrkkkn ,         /* （中継用）逓減マル定Ｐ払込期間 */
     ztyteigenmaruteis ,         /* （中継用）逓減マル定Ｓ */
     ztyteigenmaruteip ,         /* （中継用）逓減マル定Ｐ */
     ztyteigenmaruteisyuuseis ,         /* （中継用）逓減マル定修正Ｓ */
     ztyteigenmrtimodssakugenhyj ,         /* （中継用）逓減マル定修正Ｓ削減表示 */
     ztytignmrtitkjyukbn ,         /* （中継用）逓減マル定特条区分 */
     ztytignmrtitkjyuskgnkkn ,         /* （中継用）逓減マル定特条削減期間 */
     ztytignmrtitkjyuryumshyutn ,         /* （中継用）逓減マル定特条料増標点 */
     ztytignmrtitkjyup ,         /* （中継用）逓減マル定特条Ｐ */
     ztytignmrtiskyuksgk ,         /* （中継用）逓減マル定支給基礎額 */
     ztyhtnknkyktignmrtsyrikgux1 ,         /* （中継用）被転換契約逓減マル定種類記号＿１ */
     ztyhtnknkyktignmrtsyrikgux2 ,         /* （中継用）被転換契約逓減マル定種類記号＿２ */
     ztyhtnknkyktignmrtsyrikgux3 ,         /* （中継用）被転換契約逓減マル定種類記号＿３ */
     ztyhtnknkyktignmrtsyrikgux4 ,         /* （中継用）被転換契約逓減マル定種類記号＿４ */
     ztyhtnknkyktignmrtsyrikgux5 ,         /* （中継用）被転換契約逓減マル定種類記号＿５ */
     ztyhtnknkyktignmrtsyrikgux6 ,         /* （中継用）被転換契約逓減マル定種類記号＿６ */
     ztysuryutignmrtipwrbkkbn ,         /* （中継用）数理用逓減マル定Ｐ割引区分 */
     ztytignmrtipwrbkkbn ,         /* （中継用）逓減マル定Ｐ割引区分 */
     ztytignmrtitnknyugukbn ,         /* （中継用）逓減マル定転換優遇区分 */
     ztyteigenmrtikgusdkbn ,         /* （中継用）逓減マル定記号世代区分 */
     ztyyobiv1x2 ,         /* （中継用）予備項目Ｖ１＿２ */
     ztytktsppisetkykkbn ,         /* （中継用）特定疾病セット契約区分 */
     ztyjyudmnsiskknsetkykkbn ,         /* （中継用）重度慢性疾患セット契約区分 */
     ztyyobiv8x2 ,         /* （中継用）予備項目Ｖ８＿２ */
     ztysetaitesyono1 ,         /* （中継用）セット相手証券番号１ */
     ztysetaitehokensyuruikigou1 ,         /* （中継用）セット相手保険種類記号１ */
     ztysetaitemrtisyuruikgu1 ,         /* （中継用）セット相手マル定種類記号１ */
     ztysetaitesiznmrtisyurui1 ,         /* （中継用）セット相手生存マル定種類１ */
     ztysetaitetignmrtisyurui1 ,         /* （中継用）セット相手逓減マル定種類１ */
     ztysetaitekihonbubuns1 ,         /* （中継用）セット相手基本部分Ｓ１ */
     ztysetgukitnknitjbrkhns1 ,         /* （中継用）セット合計転換一時払基本Ｓ１ */
     ztysetaitesibous1 ,         /* （中継用）セット相手死亡Ｓ１ */
     ztysetgukitnknitjbrsbus1 ,         /* （中継用）セット合計転換一時払死亡Ｓ１ */
     ztysetaitesyuuseis1 ,         /* （中継用）セット相手修正Ｓ１ */
     ztysetaiteharaikomip1 ,         /* （中継用）セット相手払込Ｐ１ */
     ztysetaitesyukeiyakububunp1 ,         /* （中継用）セット相手主契約部分Ｐ１ */
     ztysetaitgukikzkmrtis1 ,         /* （中継用）セット相手合計家族マル定Ｓ１ */
     ztysetaitetenkankykhyj1 ,         /* （中継用）セット相手転換契約表示１ */
     ztysetaitesiteimhrkp1 ,         /* （中継用）セット相手指定月払込Ｐ１ */
     ztysetaitesiteimsykykp1 ,         /* （中継用）セット相手指定月主契約Ｐ１ */
     ztysetaitenkmrtisyurui1 ,         /* （中継用）セット相手年金マル定種類１ */
     ztyyobiv18 ,         /* （中継用）予備項目Ｖ１８ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_Skeiksnbsgetujisr1Ty_Z;