CREATE VIEW ZT_EgsyokuinSysRendouRn AS SELECT
     zrnsequenceno ,         /* （連携用）シーケンス番号 */
     zrnatukaikojincd ,         /* （連携用）扱者個人コード */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnkykymd ,         /* （連携用）契約年月日 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhrkkeirokbn ,         /* （連携用）払込経路区分 */
     zrnsdpdkbn ,         /* （連携用）Ｓ建Ｐ建区分 */
     zrnkihons ,         /* （連携用）基本Ｓ */
     zrnharaikomip ,         /* （連携用）払込Ｐ */
     zrnsyukeiyakup ,         /* （連携用）主契約Ｐ */
     zrngyousekiyouhosyous ,         /* （連携用）業績用保障Ｓ */
     zrnkydatkikbn ,         /* （連携用）共同扱区分 */
     zrnbsyym ,         /* （連携用）募集年月 */
     zrntsinkihontikucd ,         /* （連携用）通信先基本地区コード */
     zrnatukaisosikicd ,         /* （連携用）扱者組織コード */
     zrnhhknseikbn ,         /* （連携用）被保険者性別区分 */
     zrnhhknnen2keta ,         /* （連携用）被保険者年令（２桁） */
     zrnhensyuukeiyakusyamei ,         /* （連携用）編集契約者名 */
     zrnhnsyuknjkyksynm ,         /* （連携用）編集漢字契約者名 */
     zrnkyksyanen ,         /* （連携用）契約者年令 */
     zrnkurikosihyj ,         /* （連携用）繰越表示 */
     zrnlivingneedstkykarihyj ,         /* （連携用）リビングニーズ特約有表示 */
     zrnkyksyhhknsydouituhyouji ,         /* （連携用）契約者被保険者同一表示 */
     zrnhaitousiharaikbn ,         /* （連携用）配当支払区分 */
     zrndairitenatkikeitaikbn ,         /* （連携用）代理店扱形態区分 */
     zrndrtenegsyokuinatkiwari ,         /* （連携用）代理店営業職員扱割合 */
     zrnkjsakisosikisetteihyj ,         /* （連携用）計上先組織設定表示 */
     zrnbsydrtencd ,         /* （連携用）募集代理店コード */
     zrnsimetyokuzenbosyuuhyj ,         /* （連携用）〆切直前募集表示 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnmosnyuuryokuymd ,         /* （連携用）申込入力年月日 */
     zrnhhknsakuinmeino ,         /* （連携用）被保険者索引名番号 */
     zrntokusyujimutoriatukaikbn ,         /* （連携用）特殊事務取扱区分 */
     zrncifcd ,         /* （連携用）ＣＩＦコード */
     zrnhokensyuruikigouyobi1x1 ,         /* （連携用）保険種類記号予備１＿１ */
     zrnhokensyuruikigouyobi1x2 ,         /* （連携用）保険種類記号予備１＿２ */
     zrnhokensyuruikigouyobi1x3 ,         /* （連携用）保険種類記号予備１＿３ */
     zrnhokensyuruikigouyobi1x4 ,         /* （連携用）保険種類記号予備１＿４ */
     zrnhokensyuruikigouyobi1x5 ,         /* （連携用）保険種類記号予備１＿５ */
     zrnhokensyuruikigouyobi1x6 ,         /* （連携用）保険種類記号予備１＿６ */
     zrnhokensyuruikigouyobi1x7 ,         /* （連携用）保険種類記号予備１＿７ */
     zrnhokensyuruikigouyobi1x8 ,         /* （連携用）保険種類記号予備１＿８ */
     zrnhokensyuruikigouyobi1x9 ,         /* （連携用）保険種類記号予備１＿９ */
     zrnhokensyuruikigouyobi1x10 ,         /* （連携用）保険種類記号予備１＿１０ */
     zrnhokensyuruikigouyobi1x11 ,         /* （連携用）保険種類記号予備１＿１１ */
     zrnhokensyuruikigouyobi1x12 ,         /* （連携用）保険種類記号予備１＿１２ */
     zrnhokensyuruikigouyobi1x13 ,         /* （連携用）保険種類記号予備１＿１３ */
     zrnhokensyuruikigouyobi1x14 ,         /* （連携用）保険種類記号予備１＿１４ */
     zrnhokensyuruikigouyobi1x15 ,         /* （連携用）保険種類記号予備１＿１５ */
     zrnhokensyuruikigouyobi2x1 ,         /* （連携用）保険種類記号予備２＿１ */
     zrnhokensyuruikigouyobi2x2 ,         /* （連携用）保険種類記号予備２＿２ */
     zrnhokensyuruikigouyobi2x3 ,         /* （連携用）保険種類記号予備２＿３ */
     zrnhokensyuruikigouyobi2x4 ,         /* （連携用）保険種類記号予備２＿４ */
     zrnhokensyuruikigouyobi2x5 ,         /* （連携用）保険種類記号予備２＿５ */
     zrnhokensyuruikigouyobi2x6 ,         /* （連携用）保険種類記号予備２＿６ */
     zrnhokensyuruikigouyobi2x7 ,         /* （連携用）保険種類記号予備２＿７ */
     zrnhokensyuruikigouyobi2x8 ,         /* （連携用）保険種類記号予備２＿８ */
     zrnhokensyuruikigouyobi2x9 ,         /* （連携用）保険種類記号予備２＿９ */
     zrnhokensyuruikigouyobi2x10 ,         /* （連携用）保険種類記号予備２＿１０ */
     zrnhokensyuruikigouyobi3x1 ,         /* （連携用）保険種類記号予備３＿１ */
     zrnhokensyuruikigouyobi3x2 ,         /* （連携用）保険種類記号予備３＿２ */
     zrnhokensyuruikigouyobi3x3 ,         /* （連携用）保険種類記号予備３＿３ */
     zrnhokensyuruikigouyobi3x4 ,         /* （連携用）保険種類記号予備３＿４ */
     zrnhokensyuruikigouyobi3x5 ,         /* （連携用）保険種類記号予備３＿５ */
     zrnhokensyuruikigouyobi3x6 ,         /* （連携用）保険種類記号予備３＿６ */
     zrnhokensyuruikigouyobi3x7 ,         /* （連携用）保険種類記号予備３＿７ */
     zrnhokensyuruikigouyobi3x8 ,         /* （連携用）保険種類記号予備３＿８ */
     zrnhokensyuruikigouyobi3x9 ,         /* （連携用）保険種類記号予備３＿９ */
     zrnhokensyuruikigouyobi3x10 ,         /* （連携用）保険種類記号予備３＿１０ */
     zrnnstkarihyj ,         /* （連携用）年金支払特約有表示 */
     zrnmosno ,         /* （連携用）申込番号 */
     zrnstdairiseikyuutkykarihyj ,         /* （連携用）指定代理請求特約有表示 */
     zrnnenkansanp ,         /* （連携用）年換算Ｐ */
     zrnkyksyaskinmeino ,         /* （連携用）契約者索引名番号 */
     zrnsibous ,         /* （連携用）死亡Ｓ */
     zrnjissyuup ,         /* （連携用）実収Ｐ */
     zrnsekininkaisiymd ,         /* （連携用）責任開始年月日 */
     zrnkokutiymd ,         /* （連携用）告知年月日 */
     zrnsyokaipryosyuymd ,         /* （連携用）初回Ｐ領収年月日 */
     zrnseirituymd ,         /* （連携用）成立年月日 */
     zrnbosdairitentsratkiwari ,         /* （連携用）募集代理店手数料扱割合 */
     zrnbosyuunincd ,         /* （連携用）募集人コード */
     zrndrtentsryhushrkykhyouji ,         /* （連携用）代理店手数料不支払契約表示 */
     zrnmdhnaisyoumeikbn ,         /* （連携用）窓販用愛称名区分 */
     zrndairitenkykkanrino ,         /* （連携用）代理店契約管理番号 */
     zrnkanjitsinkaiadr ,         /* （連携用）漢字通信先下位住所 */
     zrntsintelno ,         /* （連携用）通信先電話番号 */
     zrnhensyuuyoukyksyaseikbn ,         /* （連携用）編集用契約者性別区分 */
     zrnhensyuuyoukyksyaseiymd ,         /* （連携用）編集用契約者生年月日 */
     zrnhhknmei ,         /* （連携用）被保険者名 */
     zrnknjhhknmei ,         /* （連携用）漢字被保険者名 */
     zrnhhknseiymd ,         /* （連携用）被保険者生年月日 */
     zrnnksyuruikbn1 ,         /* （連携用）年金種類区分（１文字） */
     zrnmusymd ,         /* （連携用）申込年月日 */
     zrnmossyosakuseiymd ,         /* （連携用）申込書作成年月日 */
     zrnitijibaraipkyktuuka ,         /* （連携用）一時払Ｐ（契約通貨建） */
     zrnkawaseraten5 ,         /* （連携用）為替レートＮ５ */
     zrnhrktuukakbn ,         /* （連携用）払込通貨区分 */
     zrnsiteituukakbn ,         /* （連携用）指定通貨区分 */
     zrnsyksbsitihsyutkykarihyj ,         /* （連携用）初期死亡時最低保証特約有表示 */
     zrnskkaigomaehrtkykarihyj ,         /* （連携用）（新契約）介護前払特約有表示 */
     zrnkihonskyktuuka ,         /* （連携用）基本Ｓ（契約通貨建） */
     zrnzenkizennouhyouji ,         /* （連携用）全期前納表示 */
     zrnnnknsnpssysyup ,         /* （連携用）年換算Ｐ算出用主契約Ｐ */
     zrnnknsnpssyhrkkskbn ,         /* （連携用）年換算Ｐ算出用払込回数区分 */
     zrnkykdrtkykarihyj ,         /* （連携用）契約者代理特約有表示 */
     zrnkzktrkservicearihyj ,         /* （連携用）ご家族登録サービス有表示 */
     zrnyobiv250x1 ,         /* （連携用）予備項目Ｖ２５０＿１ */
     zrnyobiv250x2 ,         /* （連携用）予備項目Ｖ２５０＿２ */
     zrnyobiv250x3 ,         /* （連携用）予備項目Ｖ２５０＿３ */
     zrnyobiv250x4 ,         /* （連携用）予備項目Ｖ２５０＿４ */
     zrnyobiv250x5 ,         /* （連携用）予備項目Ｖ２５０＿５ */
     zrnyobiv118           /* （連携用）予備項目Ｖ１１８ */
FROM ZT_EgsyokuinSysRendouRn_Z;