CREATE VIEW ZT_KijituTouraiAnnaiRn AS SELECT
     zrnsyoruicd ,         /* （連携用）書類コード */
     zrnhassoukbn ,         /* （連携用）発送区分 */
     zrntyouhyouymd ,         /* （連携用）帳票作成日 */
     zrntyouhyouymdkj ,         /* （連携用）帳票作成日（漢字） */
     zrnsyono ,         /* （連携用）証券番号 */
     zrnyobiv9 ,         /* （連携用）予備項目Ｖ９ */
     zrnansyuyouyobin10 ,         /* （連携用）案内収納用予備項目Ｎ１０ */
     zrnshskyno ,         /* （連携用）送付先郵便番号 */
     zrnshskadr1kj ,         /* （連携用）送付先住所１（漢字） */
     zrnshskadr2kj ,         /* （連携用）送付先住所２（漢字） */
     zrnshskadr3kj ,         /* （連携用）送付先住所３（漢字） */
     zrnshsnmkj ,         /* （連携用）送付先名（漢字） */
     zrnyobiv43 ,         /* （連携用）予備項目Ｖ４３ */
     zrnansyuyouyobin10x2 ,         /* （連携用）案内収納用予備項目Ｎ１０＿２ */
     zrntawsosikikj ,         /* （連携用）問合せ先組織名（漢字） */
     zrntawyno ,         /* （連携用）問合せ先郵便番号 */
     zrntawadr1kj ,         /* （連携用）問合せ先住所１（漢字） */
     zrntawadr2kj ,         /* （連携用）問合せ先住所２（漢字） */
     zrntawadr3kj ,         /* （連携用）問合せ先住所３（漢字） */
     zrntawtelnov14 ,         /* （連携用）問合せ先電話番号Ｖ１４ */
     zrntawteluktkkanou1 ,         /* （連携用）問合せ先電話受付可能時間１ */
     zrntawteluktkkanou2 ,         /* （連携用）問合せ先電話受付可能時間２ */
     zrndai2tawsosikinmkj ,         /* （連携用）第２問合せ先組織名（漢字） */
     zrndai2tawtelno ,         /* （連携用）第２問合せ先電話番号 */
     zrnsclatosyono ,         /* （連携用）スクランブル後証券番号 */
     zrnsakunm15keta ,         /* （連携用）作成番号（１５桁） */
     zrnyobiv60 ,         /* （連携用）予備項目Ｖ６０ */
     zrnansyuyouyobin10x3 ,         /* （連携用）案内収納用予備項目Ｎ１０＿３ */
     zrntuutinm ,         /* （連携用）通知名称 */
     zrnhurikaeyokokumsg32keta1 ,         /* （連携用）振替予告メッセージ（３２桁）１ */
     zrnhurikaeyokokumsg32keta2 ,         /* （連携用）振替予告メッセージ（３２桁）２ */
     zrnhurikaeyokokumsg32keta3 ,         /* （連携用）振替予告メッセージ（３２桁）３ */
     zrnhurikaeyokokumsg32keta4 ,         /* （連携用）振替予告メッセージ（３２桁）４ */
     zrnhurikaeyokokumsg32keta5 ,         /* （連携用）振替予告メッセージ（３２桁）５ */
     zrnhurikaeyokokumsg32keta6 ,         /* （連携用）振替予告メッセージ（３２桁）６ */
     zrnhurikaeyokokumsg32keta7 ,         /* （連携用）振替予告メッセージ（３２桁）７ */
     zrnhurikaeyokokumsg32keta8 ,         /* （連携用）振替予告メッセージ（３２桁）８ */
     zrnyobiv110 ,         /* （連携用）予備項目Ｖ１１０ */
     zrnansyuyouyobin10x4 ,         /* （連携用）案内収納用予備項目Ｎ１０＿４ */
     zrnhrkkeiro ,         /* （連携用）払込経路 */
     zrnsyono2 ,         /* （連携用）証券番号２ */
     zrnsyouhnnm ,         /* （連携用）商品名 */
     zrnkykymdseireki ,         /* （連携用）契約年月日（西暦） */
     zrnhhknnmkj ,         /* （連携用）被保険者名（漢字） */
     zrnyobiv30 ,         /* （連携用）予備項目Ｖ３０ */
     zrnansyuyouyobin10x5 ,         /* （連携用）案内収納用予備項目Ｎ１０＿５ */
     zrnkjttrnnfreearea1 ,         /* （連携用）期日到来案内フリーエリア１ */
     zrnkjttrnnfreearea2 ,         /* （連携用）期日到来案内フリーエリア２ */
     zrnkjttrnnfreearea3 ,         /* （連携用）期日到来案内フリーエリア３ */
     zrnkjttrnnfreearea4 ,         /* （連携用）期日到来案内フリーエリア４ */
     zrnkjttrnnfreearea5 ,         /* （連携用）期日到来案内フリーエリア５ */
     zrnkjttrnnfreearea6 ,         /* （連携用）期日到来案内フリーエリア６ */
     zrnkjttrnnfreearea7 ,         /* （連携用）期日到来案内フリーエリア７ */
     zrnyobiv99 ,         /* （連携用）予備項目Ｖ９９ */
     zrnansyuyouyobin10x6 ,         /* （連携用）案内収納用予備項目Ｎ１０＿６ */
     zrntuutisakuseiymdseireki ,         /* （連携用）通知作成年月日（西暦） */
     zrnkzhurikaeymdseireki ,         /* （連携用）口座振替日（西暦） */
     zrnkzinfo1 ,         /* （連携用）口座情報１ */
     zrnkzinfo2 ,         /* （連携用）口座情報２ */
     zrnkzinfo3 ,         /* （連携用）口座情報３ */
     zrnkzinfo4 ,         /* （連携用）口座情報４ */
     zrnkzinfo5 ,         /* （連携用）口座情報５ */
     zrnkzinfo6 ,         /* （連携用）口座情報６ */
     zrnkzinfo7 ,         /* （連携用）口座情報７ */
     zrnkzinfo8 ,         /* （連携用）口座情報８ */
     zrnhknjytukikan ,         /* （連携用）保険料充当期間 */
     zrnhrkgk1 ,         /* （連携用）払込金額１ */
     zrnhrkgk2 ,         /* （連携用）払込金額２ */
     zrnhrkgk3 ,         /* （連携用）払込金額３ */
     zrnhrkgk4 ,         /* （連携用）払込金額４ */
     zrnyobiv146 ,         /* （連携用）予備項目Ｖ１４６ */
     zrnansyuyouyobin10x7 ,         /* （連携用）案内収納用予備項目Ｎ１０＿７ */
     zrnkjttrnnfreearea8 ,         /* （連携用）期日到来案内フリーエリア８ */
     zrnkjttrnnfreearea9 ,         /* （連携用）期日到来案内フリーエリア９ */
     zrnkjttrnnfreearea10 ,         /* （連携用）期日到来案内フリーエリア１０ */
     zrnkjttrnnfreearea11 ,         /* （連携用）期日到来案内フリーエリア１１ */
     zrnkjttrnnfreearea12 ,         /* （連携用）期日到来案内フリーエリア１２ */
     zrnkjttrnnfreearea13 ,         /* （連携用）期日到来案内フリーエリア１３ */
     zrnyobiv84 ,         /* （連携用）予備項目Ｖ８４ */
     zrnansyuyouyobin10x8           /* （連携用）案内収納用予備項目Ｎ１０＿８ */
FROM ZT_KijituTouraiAnnaiRn_Z;