CREATE VIEW ZT_MosJkItiranSyoukaiTy AS SELECT
     ztymosym ,         /* （中継用）申込月度 */
     ztymoskbn ,         /* （中継用）申込区分 */
     ztymosno ,         /* （中継用）申込番号 */
     ztyhknsyuruinm ,         /* （中継用）保険種類名称 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztymusymd ,         /* （中継用）申込年月日 */
     ztymosnyuuryokuymd ,         /* （中継用）申込入力年月日 */
     ztykydatkikbn ,         /* （中継用）共同扱区分 */
     ztybsudirtnatkikeitaikbn ,         /* （中継用）募集代理店扱形態区分 */
     ztybsydrtencd ,         /* （中継用）募集代理店コード */
     ztybsydrtenkjnm ,         /* （中継用）募集代理店漢字名称 */
     ztyatukaikojincd ,         /* （中継用）扱者個人コード */
     ztytansyukukjatukaisyanm ,         /* （中継用）短縮漢字扱者名 */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztykjkyknm10 ,         /* （中継用）漢字契約者名（１０文字） */
     ztytansyukukjhhknnm ,         /* （中継用）短縮漢字被保険者名 */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztymossyoumetukbn ,         /* （中継用）申込消滅区分 */
     ztykurikosiriyuukbn ,         /* （中継用）繰越理由区分 */
     ztyketjkkbn ,         /* （中継用）決定状況区分 */
     ztydakuhiktjyoutaikbn ,         /* （中継用）諾否決定状態区分 */
     ztymosketkekkakbn ,         /* （中継用）申込決定結果区分 */
     ztykihonhubi ,         /* （中継用）基本不備 */
     ztykthhbhyouji ,         /* （中継用）決定保留不備表示 */
     ztysrhhbhyouji ,         /* （中継用）成立保留不備表示 */
     ztynyknzumihyouji ,         /* （中継用）入金済表示 */
     ztysinsazumihyouji ,         /* （中継用）診査済表示 */
     ztytuukatanikbn ,         /* （中継用）通貨単位区分 */
     ztysyokaihrkpmoji ,         /* （中継用）初回払込Ｐ（文字列） */
     ztyhjykktkbn ,         /* （中継用）報状告知区分 */
     ztysyokaipryosyuymd ,         /* （中継用）初回Ｐ領収年月日 */
     ztykokutiymd ,         /* （中継用）告知年月日 */
     ztykariseirituymd ,         /* （中継用）仮成立年月日 */
     ztyfstpnyknnaiyoukbn ,         /* （中継用）初回Ｐ入金内容区分 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztysakuseiymd ,         /* （中継用）作成日 */
     ztyanniskcd ,         /* （中継用）案内先コード */
     ztysyosakuseiymd ,         /* （中継用）証券作成年月日 */
     ztybsydrtenkobetuinfo1 ,         /* （中継用）募集代理店個別情報１ */
     ztybsydrtenkobetuinfo2 ,         /* （中継用）募集代理店個別情報２ */
     ztybsydrtenkobetuinfo3 ,         /* （中継用）募集代理店個別情報３ */
     ztybsydrtenkobetuinfo4 ,         /* （中継用）募集代理店個別情報４ */
     ztybsydrtenkobetuinfo5 ,         /* （中継用）募集代理店個別情報５ */
     ztybankkouincd ,         /* （中継用）銀行行員コード */
     ztybosyuutourokuno ,         /* （中継用）募集人登録番号 */
     ztymosjkkbn ,         /* （中継用）申込状況区分 */
     ztykousinymd ,         /* （中継用）更新年月日 */
     ztysinsayoteiymd ,         /* （中継用）診査予定年月日 */
     ztyhjnkykhyj ,         /* （中継用）法人契約表示 */
     ztykjhjnnm ,         /* （中継用）漢字法人名 */
     ztyyobiv93 ,         /* （中継用）予備項目Ｖ９３ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_MosJkItiranSyoukaiTy_Z;