CREATE VIEW ZT_RrtHndugtHknKsnJigyohiTy AS SELECT
     ztysequenceno ,         /* （中継用）シーケンス番号 */
     ztyyuukourecordlength ,         /* （中継用）有効レコード長 */
     ztyrdwarea ,         /* （中継用）ＲＤＷ領域 */
     ztykeijyouym ,         /* （中継用）計上年月 */
     ztysuuriyoupjytouym ,         /* （中継用）数理用Ｐ充当年月 */
     ztysihankibikinkbn ,         /* （中継用）四半期備金区分 */
     ztyhenkousyoriymd ,         /* （中継用）変更処理年月日 */
     ztydenymd ,         /* （中継用）伝票日付 */
     ztysyoricd ,         /* （中継用）処理コード */
     ztykykymdmaekykhyj ,         /* （中継用）契約日前契約表示 */
     ztykarikasikbn ,         /* （中継用）借方貸方区分 */
     ztysuuriyouyobin8 ,         /* （中継用）数理用予備項目Ｎ８ */
     ztyyobiv7 ,         /* （中継用）予備項目Ｖ７ */
     ztydatakanrino ,         /* （中継用）データ管理番号 */
     ztyraysystemhyj ,         /* （中継用）ＲＡＹシステム表示 */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztysotodasipmenkbn ,         /* （中継用）外出Ｐ免区分 */
     ztystdssytikbn ,         /* （中継用）外出集定区分 */
     ztystdssnskbn ,         /* （中継用）外出診査区分 */
     ztysotodasimanagehyouji ,         /* （中継用）外出満年令表示 */
     ztysotodasiphkbnmnoshyouji ,         /* （中継用）外出Ｐ不可分見直表示 */
     ztystdsstkjytkyuhyj ,         /* （中継用）外出新特条適用表示 */
     ztysuuriyouyobin5 ,         /* （中継用）数理用予備項目Ｎ５ */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     ztykbnkeiriyousegmentkbn ,         /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn ,         /* （中継用）区分経理用利源分析区分 */
     ztysuurisyuruicd ,         /* （中継用）数理種類コード */
     ztyhosyoukinoukbn ,         /* （中継用）保障機能区分 */
     ztydaikbn ,         /* （中継用）大区分 */
     ztytyuukbn ,         /* （中継用）中区分 */
     ztysyoukbn ,         /* （中継用）小区分 */
     ztysedaikbn ,         /* （中継用）世代区分 */
     ztyharaikatakbn ,         /* （中継用）払方区分 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztysdpdkbn ,         /* （中継用）Ｓ建Ｐ建区分 */
     ztyryouritukbn ,         /* （中継用）料率区分 */
     ztyhhknseikbn ,         /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2 ,         /* （中継用）被保険者年令Ｖ２ */
     ztyhhknnentysihyj ,         /* （中継用）被保険者年令調整表示 */
     ztysyukeiyakupwaribikikbn ,         /* （中継用）主契約Ｐ割引区分 */
     ztykuriagekurisagekbn ,         /* （中継用）繰上げ繰下げ区分 */
     ztysuuriyouyobin11 ,         /* （中継用）数理用予備項目Ｎ１１ */
     ztyyobiv10 ,         /* （中継用）予備項目Ｖ１０ */
     ztyalmyousohutomeisyoukbn ,         /* （中継用）ＡＬＭ用ソフト名称区分 */
     ztysnkyksoftmeisyoukbn ,         /* （中継用）新契約ソフト名称区分 */
     ztysoftmeisyoukbn ,         /* （中継用）ソフト名称区分 */
     ztynenkinkaisinendo ,         /* （中継用）年金開始年度 */
     ztynenkingatakbn ,         /* （中継用）年金型区分 */
     ztynknshry ,         /* （中継用）年金支払期間 */
     ztybosyuukeitaikbn ,         /* （中継用）募集形態区分 */
     ztygaikakbn ,         /* （中継用）外貨区分 */
     ztysuuriyouyobin8x2 ,         /* （中継用）数理用予備項目Ｎ８＿２ */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztykihons ,         /* （中継用）基本Ｓ */
     ztypjuutoujikawaserate ,         /* （中継用）保険料充当時為替レート */
     ztypjuutoujikawasekijyunymd ,         /* （中継用）保険料充当時為替基準年月日 */
     ztygessitumitatekin ,         /* （中継用）月始積立金 */
     ztyyoteiriritun5 ,         /* （中継用）予定利率Ｎ５ */
     ztytumitateriritu ,         /* （中継用）積立利率 */
     ztygaikadatetougetujuutoup ,         /* （中継用）外貨建当月充当Ｐ */
     ztykiharaikomip ,         /* （中継用）既払込Ｐ */
     ztykeisanhanteiyoutmttkn ,         /* （中継用）計算判定用積立金 */
     ztyzettaisibouritu ,         /* （中継用）絶対死亡率 */
     ztysoutaisibouritu ,         /* （中継用）相対死亡率 */
     ztysoutaikaiyakuritu ,         /* （中継用）相対解約率 */
     ztyvhireilritu ,         /* （中継用）Ｖ比例Ｌ率 */
     ztyyobin13 ,         /* （中継用）予備項目Ｎ１３ */
     ztyphireilwrbkritu ,         /* （中継用）Ｐ比例Ｌ割引率 */
     ztygetumatutumitatekin ,         /* （中継用）月末積立金 */
     ztyzennoujiikkatubaraijytgk ,         /* （中継用）前納時一括払充当額 */
     ztygaikadatenkgns ,         /* （中継用）外貨建年金原資 */
     ztyphireialpha ,         /* （中継用）Ｐ比例α */
     ztyphireibeta ,         /* （中継用）Ｐ比例β */
     ztyphireiganma ,         /* （中継用）Ｐ比例γ */
     ztykykjikawaserate ,         /* （中継用）契約時為替レート */
     ztykykjikawaseratetkyuymd ,         /* （中継用）契約時為替レート適用年月日 */
     ztyyobiv11 ,         /* （中継用）予備項目Ｖ１１ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_RrtHndugtHknKsnJigyohiTy_Z;