CREATE VIEW HT_BAK_SyoriCTL AS SELECT
     mosno ,         /* 申込番号 */
     trkssikibetukey ,         /* 取消識別キー */
     syono ,         /* 証券番号 */
     kaisyacd ,         /* 会社コード */
     mosuketukekbn ,         /* 申込受付区分 */
     mosuktkerrkbn ,         /* 申込受付エラー区分 */
     skeijimukbn ,         /* 新契約事務区分 */
     mosnrkumu ,         /* 申込書入力有無 */
     mosnrkvrfjkkbn ,         /* 申込書入力ベリファイ状況区分 */
     mosnrkymd ,         /* 申込書入力日 */
     kznrkumu ,         /* 口座情報入力有無 */
     kznrkhbumu ,         /* 口座情報入力不備有無 */
     kznrkvrfjkkbn ,         /* 口座情報入力ベリファイ状況区分 */
     dntnrkumu ,         /* 団体承認書入力有無 */
     sdnnrkumu ,         /* 集団扱加入申込書入力有無 */
     kktnrkumu ,         /* 告知書入力有無 */
     kktnrkhbumu ,         /* 告知書入力不備有無 */
     kktnrkvrfjkkbn ,         /* 告知書入力ベリファイ状況区分 */
     kktymd ,         /* 告知日 */
     hjynrkumu ,         /* 報状入力有無 */
     hjynrkhbumu ,         /* 報状入力不備有無 */
     nyknnrkumu ,         /* 入金入力有無 */
     nyuukinjoutaikbn ,         /* 入金状態区分 */
     ryosyuymd ,         /* 領収日 */
     nyknkwsratekijyunymd ,         /* 入金用為替レート基準日 */
     nyknkwsrate ,         /* 入金用為替レート */
     authorikakymd ,         /* オーソリ確認日 */
     uriagesousinkbn ,         /* 売上送信区分 */
     credittrkjkkbn ,         /* クレジットカード登録状況区分 */
     credityuukoukakkbn ,         /* クレジットカード有効確認区分 */
     mostenken1jiyhkbn ,         /* 申込点検（１次）要否区分 */
     mostenken2jiyhkbn ,         /* 申込点検（２次）要否区分 */
     mostenken3jiyhkbn ,         /* 申込点検（３次）要否区分 */
     mostenkenrrkumu ,         /* 申込点検履歴有無 */
     mostenkenjoukbn ,         /* 申込点検状態区分 */
     knkysatei1jiyhkbn ,         /* 環境査定（１次）要否区分 */
     knkysatei2jiyhkbn ,         /* 環境査定（２次）要否区分 */
     knkysateirrkumu ,         /* 環境査定履歴有無 */
     knkysateijyoukbn ,         /* 環境査定状態区分 */
     imusateikaniyhkbn ,         /* 医務査定（簡易）要否区分 */
     imusateirrkumu ,         /* 医務査定履歴有無 */
     imusateijyoukbn ,         /* 医務査定状態区分 */
     mihassinhubiumu ,         /* 未発信不備有無 */
     hubikaisyoujoutaikbn ,         /* 不備解消状態区分 */
     kthhbkbn ,         /* 決定保留不備区分 */
     srhhbkbn ,         /* 成立保留不備区分 */
     khnhbkbn ,         /* 基本不備区分 */
     kykkakjkkbn ,         /* 契約確認状況区分 */
     ketteikbn ,         /* 決定状態区分 */
     sateijtkbn ,         /* 査定状態区分 */
     sateizumiymd ,         /* 査定済日 */
     doujimosumu ,         /* 同時申込有無 */
     paldoujimosumu ,         /* ＰＡＬ同時申込有無 */
     raydoujimosumu ,         /* ＲＡＹ同時申込有無 */
     lincgthtkekkbn ,         /* ＬＩＮＣ該当判定結果区分 */
     lincjkkbn ,         /* ＬＩＮＣ状況区分 */
     lincsousinflg ,         /* ＬＩＮＣ送信済フラグ */
     linckknnjkkbn ,         /* ＬＩＮＣ確認状況区分 */
     lincdatasousinkbn ,         /* ＬＩＮＣデータ送信区分 */
     uktkakkbn ,         /* 受取人確認区分 */
     tkhjnkbn ,         /* 特定関係法人区分 */
     tktkhjnkakuninyouhikbn ,         /* 特定関係法人確認要否区分 */
     kouseiinkykkbn ,         /* 構成員契約区分 */
     koukankykkbn ,         /* 交換契約区分 */
     fatcakakkekkakbn ,         /* ＦＡＴＣＡ確認結果区分 */
     aeoikekkakbn ,         /* ＡＥＯＩ結果区分 */
     tkhsyouryakuumukbn ,         /* 通計保留省略有無区分 */
     kykksktkankbn ,         /* 契約者強制決定判定完了区分 */
     hhknksktkankbn ,         /* 被保険者強制決定判定完了区分 */
     seiritukbn ,         /* 成立区分 */
     srsyoriymd ,         /* 成立処理日 */
     minyknkurikosiumu ,         /* 未入金繰越有無 */
     kettienkurikosiumu ,         /* 決定遅延繰越有無 */
     srhkurikosiumu ,         /* 成立保留繰越有無 */
     daimosno ,         /* 代表申込番号 */
     mfrenflg ,         /* ＭＦ連動済フラグ */
     mfrenymd ,         /* ＭＦ連動日 */
     jimusrhkbn ,         /* 事務成立保留区分 */
     syssrhkbn ,         /* システム成立保留区分 */
     annaisakuseikbn ,         /* 送付案内作成状況区分 */
     annaikaisuu ,         /* 案内回数 */
     tkbtkktumu ,         /* 特別告知有無 */
     kansyoutuutiyhkbn ,         /* 勧奨通知作成要否区分 */
     lastkossyoricd ,         /* 最終更新処理コード */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version ,         /* バージョン */
     yoteirirituhenkourenrakuymd           /* 予定利率変更連絡日 */
FROM HT_BAK_SyoriCTL_Z;