CREATE VIEW ZT_DrtenTsryInfoTy AS SELECT
     ztydairitencd ,         /* （中継用）代理店コード */
     ztybosyuunincd ,         /* （中継用）募集人コード */
     ztysyono ,         /* （中継用）証券番号 */
     ztykeiyakukbn ,         /* （中継用）契約区分 */
     ztytokuyakuno ,         /* （中継用）特約番号 */
     ztybsyym ,         /* （中継用）募集年月 */
     ztykykymd ,         /* （中継用）契約年月日 */
     ztykydatkibosyuucd ,         /* （中継用）共同扱募集人コード */
     ztyseiritujibumoncd ,         /* （中継用）成立時部門コード */
     ztyseiritujiagutiknrcd ,         /* （中継用）成立時代理店内管理扱者コード */
     ztyyobiv1 ,         /* （中継用）予備項目Ｖ１ */
     ztykydeigyouakojincd ,         /* （中継用）共同扱営業員Ａ扱者個人コード */
     ztykydeigyoubkojincd ,         /* （中継用）共同扱営業員Ｂ扱者個人コード */
     ztyskeihyj ,         /* （中継用）新契約表示 */
     ztydenymd ,         /* （中継用）伝票日付 */
     ztykikaisyoriymd ,         /* （中継用）機械処理年月日 */
     ztysyoricd ,         /* （中継用）処理コード */
     ztytyouseijiyuu ,         /* （中継用）調整事由 */
     ztynyknmonth ,         /* （中継用）入金月数 */
     ztysikibetujyunjyo ,         /* （中継用）識別順序 */
     ztytnsmacezugkukbn ,         /* （中継用）たのしみＡｃｅ増額区分 */
     ztyacezugkkrykkaisiymd ,         /* （中継用）Ａｃｅ増額効力開始年月日 */
     ztyyobiv4 ,         /* （中継用）予備項目Ｖ４ */
     ztykykmfksnctrlkh ,         /* （中継用）契約ＭＦ更新ＣＴＲ（保全） */
     ztydairitenatkikeitaikbn ,         /* （中継用）代理店扱形態区分 */
     ztyatkiwari ,         /* （中継用）扱割合 */
     ztydairitenatkinin ,         /* （中継用）代理店扱人数 */
     ztytsrkeisansyukykhsyos ,         /* （中継用）手数料計算用主契約保障Ｓ */
     ztyhtns ,         /* （中継用）被転換Ｓ */
     ztykijymods ,         /* （中継用）計上修正Ｓ */
     ztyksnbubunmods ,         /* （中継用）加算部分修正Ｓ */
     ztybfrkijymods ,         /* （中継用）変更前計上修正Ｓ */
     ztybfrksnbubunmods ,         /* （中継用）変更前加算部分修正Ｓ */
     ztyhknsyukigou ,         /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn ,         /* （中継用）保険種類記号世代区分 */
     ztytksyukgu ,         /* （中継用）特約種類記号 */
     ztytksyukgusedaikbn ,         /* （中継用）特約種類記号世代区分 */
     ztyhrkkaisuukbn ,         /* （中継用）払込回数区分 */
     ztyannaifuyouriyuukbn ,         /* （中継用）案内不要理由区分 */
     ztyhhknnen2keta ,         /* （中継用）被保険者年令（２桁） */
     ztyhknkkn ,         /* （中継用）保険期間 */
     ztyfstkeijyouhtkm ,         /* （中継用）初回計上判定項目 */
     ztytsrytsryhushrkbn ,         /* （中継用）手数料不支払区分 */
     ztybfritijibrzugkp ,         /* （中継用）変更前一時払増額Ｐ */
     ztymaruteisyuruikigou ,         /* （中継用）マル定種類記号 */
     ztymrtihukakbn ,         /* （中継用）マル定付加区分 */
     ztysznmrtihukakbn ,         /* （中継用）生存マル定付加区分 */
     ztyteigenmrtihukakbn ,         /* （中継用）逓減マル定付加区分 */
     ztysyunyumrtihukakbn ,         /* （中継用）収入マル定付加区分 */
     ztykzkmrtihukakbn ,         /* （中継用）家族マル定付加区分 */
     ztytoksipmrtihukakbn ,         /* （中継用）特定疾病マル定付加区分 */
     ztytoksipmrsyhukakbn ,         /* （中継用）特定疾病マル終付加区分 */
     ztymanskknmrtihukakbn ,         /* （中継用）慢性疾患マル定付加区分 */
     ztykigsyunyumrtihukakbn ,         /* （中継用）介護収入マル定付加区分 */
     ztykigteigenmrtihukakbn ,         /* （中継用）介護逓減マル定付加区分 */
     ztykignktkhukakbn ,         /* （中継用）介護年金特約付加区分 */
     ztykigmrtihukakbn ,         /* （中継用）介護マル定付加区分 */
     ztymrtisyukguyobiv1 ,         /* （中継用）マル定種類記号予備項目Ｖ１ */
     ztymrtisyukguyobiv1x2 ,         /* （中継用）マル定種類記号予備項目Ｖ１＿２ */
     ztymrtisyukguyobiv1x3 ,         /* （中継用）マル定種類記号予備項目Ｖ１＿３ */
     ztymrtisyukguyobiv1x4 ,         /* （中継用）マル定種類記号予備項目Ｖ１＿４ */
     ztymrtisyukguyobiv1x5 ,         /* （中継用）マル定種類記号予備項目Ｖ１＿５ */
     ztyyobiv1x2 ,         /* （中継用）予備項目Ｖ１＿２ */
     ztykyknm ,         /* （中継用）契約者名 */
     ztykjkyknm ,         /* （中継用）漢字契約者名 */
     ztyhhknmei ,         /* （中継用）被保険者名 */
     ztyknjhhknmei ,         /* （中継用）漢字被保険者名 */
     ztyhrkkeirokbn ,         /* （中継用）払込経路区分 */
     ztyanniskcd ,         /* （中継用）案内先コード */
     ztykarikeijyoukbn ,         /* （中継用）仮計上区分 */
     ztytuikakeijyouhyj ,         /* （中継用）追加計上表示 */
     ztyksnhyj ,         /* （中継用）更新表示 */
     ztydai2ksnbubunmods ,         /* （中継用）第２加算部分修正Ｓ */
     ztydai2bfrksnbubunmods ,         /* （中継用）第２変更前加算部分修正Ｓ */
     ztyphrkkikn ,         /* （中継用）Ｐ払込期間 */
     ztyjissyuup ,         /* （中継用）実収Ｐ */
     ztygntikktgtiryoutkp ,         /* （中継用）限定告知型医療特約Ｐ */
     ztybfrgntikktgtiryoutkp ,         /* （中継用）変更前限定告知型医療特約Ｐ */
     ztydairitenkbtinfo1 ,         /* （中継用）代理店個別情報１ */
     ztydairitenkbtinfo2 ,         /* （中継用）代理店個別情報２ */
     ztydairitenkbtinfo3 ,         /* （中継用）代理店個別情報３ */
     ztysisttkp ,         /* （中継用）災疾特約Ｐ */
     ztyreguardtkp ,         /* （中継用）リガード特約Ｐ */
     ztyvguardtkp ,         /* （中継用）Ｖガード特約Ｐ */
     ztybfrsisttkp ,         /* （中継用）変更前災疾特約Ｐ */
     ztybfrreguardtkp ,         /* （中継用）変更前リガード特約Ｐ */
     ztybfrvguardtkp ,         /* （中継用）変更前Ｖガード特約Ｐ */
     ztygtmtv ,         /* （中継用）月末Ｖ */
     ztysyukeiyakup ,         /* （中継用）主契約Ｐ */
     ztybfrsyup ,         /* （中継用）変更前主契約Ｐ */
     ztydairitentsratkiwari ,         /* （中継用）代理店手数料扱割合 */
     ztyseirituymd ,         /* （中継用）成立年月日 */
     ztysekininkaisiymd ,         /* （中継用）責任開始年月日 */
     ztycifcd ,         /* （中継用）ＣＩＦコード */
     ztybankboskykkbn ,         /* （中継用）銀行募集契約区分 */
     ztykykjiqpackhyj ,         /* （中継用）契約時Ｑパック表示 */
     ztyitijibrzugkp ,         /* （中継用）一時払増額Ｐ */
     ztytuuintokuyakup ,         /* （中継用）通院特約Ｐ */
     ztybfrtuuintkp ,         /* （中継用）変更前通院特約Ｐ */
     ztysougousonsyoutokuyakup ,         /* （中継用）総合損傷特約Ｐ */
     ztybfrsugusnsyutkp ,         /* （中継用）変更前総合損傷特約Ｐ */
     ztyyoteiriritun5 ,         /* （中継用）予定利率Ｎ５ */
     ztyyouikunenkintokuyakup ,         /* （中継用）養育年金特約Ｐ */
     ztybfryoiknktkp ,         /* （中継用）変更前養育年金特約Ｐ */
     ztygntikktgtiryoutkntgk ,         /* （中継用）限定告知型医療特約日額 */
     ztykyksyaskinmeino ,         /* （中継用）契約者索引名番号 */
     ztyhhknsakuinmeino ,         /* （中継用）被保険者索引名番号 */
     ztysinkykbosyuoyadrtencd ,         /* （中継用）新契約募集時親代理店コード */
     ztysyouhizeiritu ,         /* （中継用）消費税率 */
     ztymdhnaisyoumeicd ,         /* （中継用）窓販用愛称名コード */
     ztycoolingofhyj ,         /* （中継用）クーリングオフ表示 */
     ztysaimnkkykhyj ,         /* （中継用）才満期契約表示 */
     ztypjytoym ,         /* （中継用）Ｐ充当年月 */
     ztysskhntihrkkisukbn ,         /* （中継用）成績判定用払込回数区分 */
     ztyphenkanarihyj ,         /* （中継用）Ｐ返還あり表示 */
     ztyhjnkykhyj ,         /* （中継用）法人契約表示 */
     ztybktgomeisaicalcjyun ,         /* （中継用）分割後明細計算順 */
     ztyikkatubaraikbn ,         /* （中継用）一括払区分 */
     ztyikkatubaraikaisuu ,         /* （中継用）一括払回数 */
     ztyuktkid ,         /* （中継用）受付管理ＩＤ */
     ztykigmrsytkp ,         /* （中継用）介護マル終特約Ｐ */
     ztybfrkigmrsytkp ,         /* （中継用）変更前介護マル終特約Ｐ */
     ztykigmrsytkphrkkkn ,         /* （中継用）介護マル終特約Ｐ払込期間 */
     ztyyobiv5 ,         /* （中継用）予備項目Ｖ５ */
     ztyphenkanbfrsyup ,         /* （中継用）Ｐ返還用変更前主契約Ｐ */
     ztyyobin3 ,         /* （中継用）予備項目Ｎ３ */
     ztytousyokykjikawaserate ,         /* （中継用）当初契約時為替レート */
     ztyyobin11 ,         /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2 ,         /* （中継用）予備項目Ｎ１１＿２ */
     ztyyobin11x3 ,         /* （中継用）予備項目Ｎ１１＿３ */
     ztyyobin11x4 ,         /* （中継用）予備項目Ｎ１１＿４ */
     ztyyobin11x5 ,         /* （中継用）予備項目Ｎ１１＿５ */
     ztyyobin11x6 ,         /* （中継用）予備項目Ｎ１１＿６ */
     ztyyobin11x7 ,         /* （中継用）予備項目Ｎ１１＿７ */
     ztyyobin11x8 ,         /* （中継用）予備項目Ｎ１１＿８ */
     ztyshzirtstkjynymd ,         /* （中継用）消費税率設定基準年月日 */
     ztykyksyaseiymd ,         /* （中継用）契約者生年月日 */
     ztytuukacd ,         /* （中継用）通貨コード */
     ztysyukeiyakupkyktuuka ,         /* （中継用）主契約Ｐ（契約通貨） */
     ztybfrsyupkyktuuka ,         /* （中継用）変更前主契約Ｐ（契約通貨） */
     ztytekiyoukawaserate7keta ,         /* （中継用）適用為替レート（７桁） */
     ztyyobiv22 ,         /* （中継用）予備項目Ｖ２２ */
     ztyyobiv83 ,         /* （中継用）予備項目Ｖ８３ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_DrtenTsryInfoTy_Z;