CREATE VIEW BM_SyouhnZokusei AS SELECT
     syouhncd ,         /* 商品コード */
     syouhnsdno ,         /* 商品世代番号 */
     ryouritusdno ,         /* 料率世代番号 */
     syohnsortno ,         /* 商品ソート番号 */
     mossyohnsortno ,         /* 申込書商品ソート番号 */
     syouhnnm ,         /* 商品名 */
     syouhnnmryaku ,         /* 商品名（略称） */
     syouhnnmryaku5 ,         /* 商品名（略称）_5 */
     syouhnnmsyouken ,         /* 商品名（証券用） */
     syouhnnmworklist ,         /* 商品名（ワークリスト用） */
     kykfromymd ,         /* 契約日自 */
     kyktoymd ,         /* 契約日至 */
     hyoujifromymd ,         /* 表示日自 */
     hyoujitoymd ,         /* 表示日至 */
     syutkkbn ,         /* 主契約特約区分 */
     hknsyuruino ,         /* 保険種類番号 */
     toukeiyouhokensyuruikbn ,         /* 統計用保険種類区分 */
     ijitoukeihokensyuruikbn ,         /* 医事統計用保険種類区分 */
     isatoukeihokensyuruicd ,         /* 医査統計用保険種類コード */
     yoteirirituhendoukbn ,         /* 予定利率変動区分 */
     yoteirirituhosyoukkn ,         /* 予定利率保証期間 */
     yoteirirituminhosyouritu ,         /* 予定利率最低保証率 */
     nkgnshosyouritu ,         /* 年金原資最低保証率 */
     dai1hknkkn ,         /* 第１保険期間 */
     drtsyouhinsikibetukbn ,         /* 代理店商品識別区分 */
     drthrkhouhoukbn ,         /* 代理店払込方法区分 */
     drtplannmkbn ,         /* 代理店プラン名区分 */
     tuukasyu ,         /* 通貨種類 */
     jikounensuu ,         /* 時効年数 */
     ntgksbairitu ,         /* 日額Ｓ倍率 */
     sbhkuktumu ,         /* 死亡保険金受取有無 */
     sbkyuuhukinuktumu ,         /* 死亡給付金受取有無 */
     sbhnknuktumu ,         /* 死亡返還金受取有無 */
     sbuktumu ,         /* 死亡受取有無 */
     mnkuktumu ,         /* 満期受取有無 */
     siteidairiumu ,         /* 指定代理人有無 */
     kktumu ,         /* 告知有無 */
     hjyumu ,         /* 報状有無 */
     musenumu ,         /* 無選択有無 */
     syokugyoukktumu ,         /* 職業告知有無 */
     kokutikbn ,         /* 告知区分 */
     sdumu ,         /* Ｓ建有無 */
     pdumu ,         /* Ｐ建有無 */
     gijipdumu ,         /* 擬似Ｐ建有無 */
     hokenkngkyakujyouumu ,         /* 保険金額約定有無 */
     haitoukbn ,         /* 配当区分 */
     teikisiharaikinumu ,         /* 定期支払金有無 */
     kyhkataumu ,         /* 給付型有無 */
     syukyhkinkataumu ,         /* 手術給付金型有無 */
     rokudaildumu ,         /* ６大生活習慣病追加給付型有無 */
     khnkyhkgbairituumu ,         /* 基本給付金額倍率有無 */
     itijibrumu ,         /* 一時払有無 */
     heijyunbaraiumu ,         /* 平準払有無 */
     zennouumu ,         /* 前納有無 */
     itibuzennoutekiumu ,         /* 一部前納適用有無 */
     zenkizennoutekiumu ,         /* 全期前納適用有無 */
     ikkatubaraiumu ,         /* 一括払有無 */
     teikiikkatubaraiumu ,         /* 定期一括払有無 */
     pwaribikikbn ,         /* 保険料割引区分 */
     tkjyrmtekiumu ,         /* 特条料増適用有無 */
     tkjyskgntekiumu ,         /* 特条削減適用有無 */
     htnpbuitekiumu ,         /* 不担保部位適用有無 */
     tokkoudosghtnptekiumu ,         /* 特定高度障害不担保適用有無 */
     jkntekiumu ,         /* 条件付適用有無 */
     livtkumu ,         /* リビングニーズ特約有無 */
     kzktourokuserviceumu ,         /* 家族登録サービス有無 */
     stdrsktkumu ,         /* 被保険者代理特約有無 */
     kykdrtkykumu ,         /* 契約者代理特約有無 */
     pmnjtkumu ,         /* 保険料免除特約有無 */
     sknnkaisikitkumu ,         /* 責任開始期特約有無 */
     gaikatatkiumu ,         /* 外貨取扱有無 */
     hengakuumu ,         /* 変額保険有無 */
     targettkumu ,         /* ターゲット特約有無 */
     nsikoutkumu ,         /* 年金支払移行特約有無 */
     nstkumu ,         /* 年金支払特約有無 */
     syksbyensitihsyutktekiumu ,         /* 初期死亡時円換算最低保証特約適用有無 */
     jyudkaigomehrtktekiumu ,         /* 重度介護前払特約適用有無 */
     yensysnikoutekiumu ,         /* 円建終身保険移行適用有無 */
     stknumu ,         /* 質権有無 */
     apltekiumu ,         /* ＡＰＬ適用有無 */
     jgyiktumu ,         /* 事業一括有無 */
     hutuusbhsyumu ,         /* 普通死亡保障有無 */
     sgsbhsyumu ,         /* 災害死亡保障有無 */
     sougouiryhsyumu ,         /* 総合医療保障有無 */
     syuusinhknumu ,         /* 終身保険有無 */
     yrhknumu ,         /* 養老保険有無 */
     nkhknumu ,         /* 年金保険有無 */
     sipnyukyhumu ,         /* 疾病入院給付有無 */
     sgnyukyhumu ,         /* 災害入院給付有無 */
     sjnyukyhumu ,         /* 成人病入院給付有無 */
     gannyukyhumu ,         /* がん入院給付有無 */
     kihonsntgkumu ,         /* 基本Ｓ日額有無 */
     gansdkyhumu ,         /* がん診断給付有無 */
     ganhsyngumu ,         /* がん保障日額有無 */
     eightysaimnrytkumu ,         /* ８０歳満了特約有無 */
     saiteisknwtkumu ,         /* 最低Ｓ緩和特約有無 */
     dountgkchkumu ,         /* 同一日額チェック有無 */
     doukknchkumu ,         /* 同一期間チェック有無 */
     doukatachkumu ,         /* 同一型チェック有無 */
     tyouhukuknyumu ,         /* 重複加入チェック有無 */
     stsnumu ,         /* Ｓ通算有無 */
     nkgnstuusanumu ,         /* 年金原資通算有無 */
     nenbtsousbustuusanumu ,         /* 年齢別総死亡Ｓ通算有無 */
     soukktjituhsgktuusanumu ,         /* 総告知書実質保障額通算有無 */
     msnynenbtsbustuusanumu ,         /* 未成年用年齢別死亡Ｓ通算有無 */
     kktjituhsgk1tuusanumu ,         /* 告知書実保障額１通算有無 */
     kktjituhsgk2tuusanumu ,         /* 告知書実保障額２通算有無 */
     itijibrptsnumu ,         /* 一時払Ｐ通算有無 */
     yenhrkgktuusansiyouumu ,         /* 円貨払込金額通算使用有無 */
     kykdrtentuusanumu ,         /* 契約者同一代理店通算有無 */
     pyennykntktekiumu ,         /* 保険料円入金特約適用有無 */
     yenshrtktekiumu ,         /* 円支払特約適用有無 */
     gaikanyuukintktekiumu ,         /* 外貨入金特約適用有無 */
     knrrenkatasyouhnumu ,         /* 金利連動型商品有無 */
     gstsumu ,         /* 源泉徴収対象有無 */
     nenmnryumu ,         /* 年満了取扱有無 */
     kaiyakuhrtype ,         /* 解約返戻金支払タイプ */
     kaiyakuhrbairitu ,         /* 解約返戻金倍率 */
     hukkatukanouy ,         /* 復活可能年数 */
     hukkatukanoum ,         /* 復活可能月数 */
     pratetani ,         /* Ｐレート単位 */
     vratetani ,         /* Ｖレート単位 */
     wratetani ,         /* Ｗレート単位 */
     kihonssyuruikbn ,         /* 基本Ｓ種類区分 */
     gengakukahikbn ,         /* 基本Ｓ減額可否区分 */
     pgengakukahikbn ,         /* 保険料減額可否区分 */
     hjnkykumukbn ,         /* 法人契約有無区分 */
     creditcardhrtekiumu ,         /* クレジットカード払適用有無 */
     kouzahurikaebaraitekiumu ,         /* 口座振替払適用有無 */
     tsnshrgndgkhyoujiumu ,         /* 通算支払限度額表示有無 */
     tsnshrgndgk ,         /* 通算支払限度額 */
     tsnshrgndgk$ ,         /* 通算支払限度額(通貨型) */
     itjsytkkziumu ,         /* 一時所得課税有無 */
     gansknnkaisiymdumu ,         /* がん責任開始日有無 */
     gansknnkaisikeikanisuu ,         /* がん責任開始経過日数 */
     gantkhktctrlumu ,         /* がん特約復活制御有無 */
     iktpcalcssketasuu ,         /* 一括払Ｐ計算小数桁数 */
     tratkikanousinsahou ,         /* 取扱可能診査方法 */
     kostratkiumu ,         /* 更新取扱有無 */
     kosmnrynen ,         /* 更新満了年齢 */
     shrtysysksumu ,         /* 支払調書作成有無 */
     shrtysyhknsyukbn ,         /* 支払調書保険種類区分 */
     synndkyfknshrskgnumu ,         /* 初年度給付金支払削減有無 */
     dai1hknkknsbsyokuseiumu ,         /* 第１保険期間中死亡保険金額抑制有無 */
     hknkknbunruikbn ,         /* 保険期間分類区分 */
     mvatekiumu ,         /* ＭＶＡ適用有無 */
     mvatekikkn ,         /* ＭＶＡ適用期間 */
     mvatyouseijikou ,         /* ＭＶＡ調整項 */
     kaiyakukoujyoritutekiumu ,         /* 解約控除率適用有無 */
     kaiyakukoujyoritutekikkn ,         /* 解約控除率適用期間 */
     tkbripfgk ,         /* 月払Ｐｆ金額 */
     tkbripfgk$ ,         /* 月払Ｐｆ金額(通貨型) */
     hnnnbripfgk ,         /* 半年払Ｐｆ金額 */
     hnnnbripfgk$ ,         /* 半年払Ｐｆ金額(通貨型) */
     nnbripfgk ,         /* 年払Ｐｆ金額 */
     nnbripfgk$ ,         /* 年払Ｐｆ金額(通貨型) */
     gwhensyuuoutjyuni ,         /* ＧＷ編集出力順位 */
     koujyosyoumeipkbn ,         /* 控除証明保険料区分 */
     zeiseitekikakuumu ,         /* 税制適格有無 */
     fatcataisyouumu ,         /* ＦＡＴＣＡ対象有無 */
     aeoitaisyouumu ,         /* ＡＥＯＩ対象有無 */
     houteityotkseiumu ,         /* 法定貯蓄性有無 */
     seg1cd ,         /* セグメント１コード */
     seg2cd ,         /* セグメント２コード */
     gwhknsyurui ,         /* ＧＷ＿保険種類 */
     gwhosyucd ,         /* ＧＷ＿保種コード */
     gwsyouhncd ,         /* ＧＷ＿商品コード */
     gwsyouhnnm ,         /* ＧＷ＿商品名称 */
     hknsyuruikoujyosyoumei ,         /* 保険種類（控除証明書） */
     sknenkinsyu ,         /* 新契約年金種類 */
     nkuktumu ,         /* 年金受取有無 */
     tmttknhaibunwarisiteiumu ,         /* 積立金配分割合指定有無 */
     targettkhukakanoukbn ,         /* ターゲット特約付加可能区分 */
     mousideikoukbn ,         /* 申出移行区分 */
     yendthnksyouhncd ,         /* 円建変更後商品コード */
     sisuukbn ,         /* 指数区分 */
     tyksenhokanhoukbn ,         /* 直線補間方法区分 */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM BM_SyouhnZokusei_Z;