CREATE VIEW ZT_SinkeiyakuSyoukenSuii2Ty AS SELECT
     ztysyono ,         /* （中継用）証券番号 */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztysuiihyouptn ,         /* （中継用）推移表パターン */
     ztysuiihyousykbn ,         /* （中継用）推移表種別区分 */
     ztysuiihyousyono ,         /* （中継用）推移表証券番号 */
     ztyytirrtcalckijyunrrt ,         /* （中継用）予定利率計算基準利率 */
     ztywkwsrateyendaka ,         /* （中継用）解約返戻金為替レート（円高） */
     ztywkwsrateyenkijyun ,         /* （中継用）解約返戻金為替レート（中央値） */
     ztywkwsrateyenyasu ,         /* （中継用）解約返戻金為替レート（円安） */
     ztykyktuukatype ,         /* （中継用）契約通貨タイプ */
     ztykeikanensuu01 ,         /* （中継用）経過年数０１ */
     ztyhrkkknmnryumukbn01 ,         /* （中継用）払込期間満了有無区分０１ */
     ztyzennouzndkyen01 ,         /* （中継用）前納残高（円貨）０１ */
     ztyyenhrkgkgoukei01 ,         /* （中継用）円貨払込額の合計（円貨）０１ */
     ztykihrkmp01 ,         /* （中継用）既払込保険料０１ */
     ztyw01 ,         /* （中継用）解約返戻金０１ */
     ztywyenyendaka01 ,         /* （中継用）解約返戻金（円貨）円高０１ */
     ztywyenkijun01 ,         /* （中継用）解約返戻金（円貨）中央値０１ */
     ztywyenyenyasu01 ,         /* （中継用）解約返戻金（円貨）円安０１ */
     ztykeikanensuu02 ,         /* （中継用）経過年数０２ */
     ztyhrkkknmnryumukbn02 ,         /* （中継用）払込期間満了有無区分０２ */
     ztyzennouzndkyen02 ,         /* （中継用）前納残高（円貨）０２ */
     ztyyenhrkgkgoukei02 ,         /* （中継用）円貨払込額の合計（円貨）０２ */
     ztykihrkmp02 ,         /* （中継用）既払込保険料０２ */
     ztyw02 ,         /* （中継用）解約返戻金０２ */
     ztywyenyendaka02 ,         /* （中継用）解約返戻金（円貨）円高０２ */
     ztywyenkijun02 ,         /* （中継用）解約返戻金（円貨）中央値０２ */
     ztywyenyenyasu02 ,         /* （中継用）解約返戻金（円貨）円安０２ */
     ztykeikanensuu03 ,         /* （中継用）経過年数０３ */
     ztyhrkkknmnryumukbn03 ,         /* （中継用）払込期間満了有無区分０３ */
     ztyzennouzndkyen03 ,         /* （中継用）前納残高（円貨）０３ */
     ztyyenhrkgkgoukei03 ,         /* （中継用）円貨払込額の合計（円貨）０３ */
     ztykihrkmp03 ,         /* （中継用）既払込保険料０３ */
     ztyw03 ,         /* （中継用）解約返戻金０３ */
     ztywyenyendaka03 ,         /* （中継用）解約返戻金（円貨）円高０３ */
     ztywyenkijun03 ,         /* （中継用）解約返戻金（円貨）中央値０３ */
     ztywyenyenyasu03 ,         /* （中継用）解約返戻金（円貨）円安０３ */
     ztykeikanensuu04 ,         /* （中継用）経過年数０４ */
     ztyhrkkknmnryumukbn04 ,         /* （中継用）払込期間満了有無区分０４ */
     ztyzennouzndkyen04 ,         /* （中継用）前納残高（円貨）０４ */
     ztyyenhrkgkgoukei04 ,         /* （中継用）円貨払込額の合計（円貨）０４ */
     ztykihrkmp04 ,         /* （中継用）既払込保険料０４ */
     ztyw04 ,         /* （中継用）解約返戻金０４ */
     ztywyenyendaka04 ,         /* （中継用）解約返戻金（円貨）円高０４ */
     ztywyenkijun04 ,         /* （中継用）解約返戻金（円貨）中央値０４ */
     ztywyenyenyasu04 ,         /* （中継用）解約返戻金（円貨）円安０４ */
     ztykeikanensuu05 ,         /* （中継用）経過年数０５ */
     ztyhrkkknmnryumukbn05 ,         /* （中継用）払込期間満了有無区分０５ */
     ztyzennouzndkyen05 ,         /* （中継用）前納残高（円貨）０５ */
     ztyyenhrkgkgoukei05 ,         /* （中継用）円貨払込額の合計（円貨）０５ */
     ztykihrkmp05 ,         /* （中継用）既払込保険料０５ */
     ztyw05 ,         /* （中継用）解約返戻金０５ */
     ztywyenyendaka05 ,         /* （中継用）解約返戻金（円貨）円高０５ */
     ztywyenkijun05 ,         /* （中継用）解約返戻金（円貨）中央値０５ */
     ztywyenyenyasu05 ,         /* （中継用）解約返戻金（円貨）円安０５ */
     ztykeikanensuu06 ,         /* （中継用）経過年数０６ */
     ztyhrkkknmnryumukbn06 ,         /* （中継用）払込期間満了有無区分０６ */
     ztyzennouzndkyen06 ,         /* （中継用）前納残高（円貨）０６ */
     ztyyenhrkgkgoukei06 ,         /* （中継用）円貨払込額の合計（円貨）０６ */
     ztykihrkmp06 ,         /* （中継用）既払込保険料０６ */
     ztyw06 ,         /* （中継用）解約返戻金０６ */
     ztywyenyendaka06 ,         /* （中継用）解約返戻金（円貨）円高０６ */
     ztywyenkijun06 ,         /* （中継用）解約返戻金（円貨）中央値０６ */
     ztywyenyenyasu06 ,         /* （中継用）解約返戻金（円貨）円安０６ */
     ztykeikanensuu07 ,         /* （中継用）経過年数０７ */
     ztyhrkkknmnryumukbn07 ,         /* （中継用）払込期間満了有無区分０７ */
     ztyzennouzndkyen07 ,         /* （中継用）前納残高（円貨）０７ */
     ztyyenhrkgkgoukei07 ,         /* （中継用）円貨払込額の合計（円貨）０７ */
     ztykihrkmp07 ,         /* （中継用）既払込保険料０７ */
     ztyw07 ,         /* （中継用）解約返戻金０７ */
     ztywyenyendaka07 ,         /* （中継用）解約返戻金（円貨）円高０７ */
     ztywyenkijun07 ,         /* （中継用）解約返戻金（円貨）中央値０７ */
     ztywyenyenyasu07 ,         /* （中継用）解約返戻金（円貨）円安０７ */
     ztykeikanensuu08 ,         /* （中継用）経過年数０８ */
     ztyhrkkknmnryumukbn08 ,         /* （中継用）払込期間満了有無区分０８ */
     ztyzennouzndkyen08 ,         /* （中継用）前納残高（円貨）０８ */
     ztyyenhrkgkgoukei08 ,         /* （中継用）円貨払込額の合計（円貨）０８ */
     ztykihrkmp08 ,         /* （中継用）既払込保険料０８ */
     ztyw08 ,         /* （中継用）解約返戻金０８ */
     ztywyenyendaka08 ,         /* （中継用）解約返戻金（円貨）円高０８ */
     ztywyenkijun08 ,         /* （中継用）解約返戻金（円貨）中央値０８ */
     ztywyenyenyasu08 ,         /* （中継用）解約返戻金（円貨）円安０８ */
     ztykeikanensuu09 ,         /* （中継用）経過年数０９ */
     ztyhrkkknmnryumukbn09 ,         /* （中継用）払込期間満了有無区分０９ */
     ztyzennouzndkyen09 ,         /* （中継用）前納残高（円貨）０９ */
     ztyyenhrkgkgoukei09 ,         /* （中継用）円貨払込額の合計（円貨）０９ */
     ztykihrkmp09 ,         /* （中継用）既払込保険料０９ */
     ztyw09 ,         /* （中継用）解約返戻金０９ */
     ztywyenyendaka09 ,         /* （中継用）解約返戻金（円貨）円高０９ */
     ztywyenkijun09 ,         /* （中継用）解約返戻金（円貨）中央値０９ */
     ztywyenyenyasu09 ,         /* （中継用）解約返戻金（円貨）円安０９ */
     ztykeikanensuu10 ,         /* （中継用）経過年数１０ */
     ztyhrkkknmnryumukbn10 ,         /* （中継用）払込期間満了有無区分１０ */
     ztyzennouzndkyen10 ,         /* （中継用）前納残高（円貨）１０ */
     ztyyenhrkgkgoukei10 ,         /* （中継用）円貨払込額の合計（円貨）１０ */
     ztykihrkmp10 ,         /* （中継用）既払込保険料１０ */
     ztyw10 ,         /* （中継用）解約返戻金１０ */
     ztywyenyendaka10 ,         /* （中継用）解約返戻金（円貨）円高１０ */
     ztywyenkijun10 ,         /* （中継用）解約返戻金（円貨）中央値１０ */
     ztywyenyenyasu10 ,         /* （中継用）解約返戻金（円貨）円安１０ */
     ztykeikanensuu11 ,         /* （中継用）経過年数１１ */
     ztyhrkkknmnryumukbn11 ,         /* （中継用）払込期間満了有無区分１１ */
     ztyzennouzndkyen11 ,         /* （中継用）前納残高（円貨）１１ */
     ztyyenhrkgkgoukei11 ,         /* （中継用）円貨払込額の合計（円貨）１１ */
     ztykihrkmp11 ,         /* （中継用）既払込保険料１１ */
     ztyw11 ,         /* （中継用）解約返戻金１１ */
     ztywyenyendaka11 ,         /* （中継用）解約返戻金（円貨）円高１１ */
     ztywyenkijun11 ,         /* （中継用）解約返戻金（円貨）中央値１１ */
     ztywyenyenyasu11 ,         /* （中継用）解約返戻金（円貨）円安１１ */
     ztykeikanensuu12 ,         /* （中継用）経過年数１２ */
     ztyhrkkknmnryumukbn12 ,         /* （中継用）払込期間満了有無区分１２ */
     ztyzennouzndkyen12 ,         /* （中継用）前納残高（円貨）１２ */
     ztyyenhrkgkgoukei12 ,         /* （中継用）円貨払込額の合計（円貨）１２ */
     ztykihrkmp12 ,         /* （中継用）既払込保険料１２ */
     ztyw12 ,         /* （中継用）解約返戻金１２ */
     ztywyenyendaka12 ,         /* （中継用）解約返戻金（円貨）円高１２ */
     ztywyenkijun12 ,         /* （中継用）解約返戻金（円貨）中央値１２ */
     ztywyenyenyasu12 ,         /* （中継用）解約返戻金（円貨）円安１２ */
     ztykeikanensuu13 ,         /* （中継用）経過年数１３ */
     ztyhrkkknmnryumukbn13 ,         /* （中継用）払込期間満了有無区分１３ */
     ztyzennouzndkyen13 ,         /* （中継用）前納残高（円貨）１３ */
     ztyyenhrkgkgoukei13 ,         /* （中継用）円貨払込額の合計（円貨）１３ */
     ztykihrkmp13 ,         /* （中継用）既払込保険料１３ */
     ztyw13 ,         /* （中継用）解約返戻金１３ */
     ztywyenyendaka13 ,         /* （中継用）解約返戻金（円貨）円高１３ */
     ztywyenkijun13 ,         /* （中継用）解約返戻金（円貨）中央値１３ */
     ztywyenyenyasu13 ,         /* （中継用）解約返戻金（円貨）円安１３ */
     ztykeikanensuu14 ,         /* （中継用）経過年数１４ */
     ztyhrkkknmnryumukbn14 ,         /* （中継用）払込期間満了有無区分１４ */
     ztyzennouzndkyen14 ,         /* （中継用）前納残高（円貨）１４ */
     ztyyenhrkgkgoukei14 ,         /* （中継用）円貨払込額の合計（円貨）１４ */
     ztykihrkmp14 ,         /* （中継用）既払込保険料１４ */
     ztyw14 ,         /* （中継用）解約返戻金１４ */
     ztywyenyendaka14 ,         /* （中継用）解約返戻金（円貨）円高１４ */
     ztywyenkijun14 ,         /* （中継用）解約返戻金（円貨）中央値１４ */
     ztywyenyenyasu14 ,         /* （中継用）解約返戻金（円貨）円安１４ */
     ztykeikanensuu15 ,         /* （中継用）経過年数１５ */
     ztyhrkkknmnryumukbn15 ,         /* （中継用）払込期間満了有無区分１５ */
     ztyzennouzndkyen15 ,         /* （中継用）前納残高（円貨）１５ */
     ztyyenhrkgkgoukei15 ,         /* （中継用）円貨払込額の合計（円貨）１５ */
     ztykihrkmp15 ,         /* （中継用）既払込保険料１５ */
     ztyw15 ,         /* （中継用）解約返戻金１５ */
     ztywyenyendaka15 ,         /* （中継用）解約返戻金（円貨）円高１５ */
     ztywyenkijun15 ,         /* （中継用）解約返戻金（円貨）中央値１５ */
     ztywyenyenyasu15 ,         /* （中継用）解約返戻金（円貨）円安１５ */
     ztykeikanensuu16 ,         /* （中継用）経過年数１６ */
     ztyhrkkknmnryumukbn16 ,         /* （中継用）払込期間満了有無区分１６ */
     ztyzennouzndkyen16 ,         /* （中継用）前納残高（円貨）１６ */
     ztyyenhrkgkgoukei16 ,         /* （中継用）円貨払込額の合計（円貨）１６ */
     ztykihrkmp16 ,         /* （中継用）既払込保険料１６ */
     ztyw16 ,         /* （中継用）解約返戻金１６ */
     ztywyenyendaka16 ,         /* （中継用）解約返戻金（円貨）円高１６ */
     ztywyenkijun16 ,         /* （中継用）解約返戻金（円貨）中央値１６ */
     ztywyenyenyasu16 ,         /* （中継用）解約返戻金（円貨）円安１６ */
     ztykeikanensuu17 ,         /* （中継用）経過年数１７ */
     ztyhrkkknmnryumukbn17 ,         /* （中継用）払込期間満了有無区分１７ */
     ztyzennouzndkyen17 ,         /* （中継用）前納残高（円貨）１７ */
     ztyyenhrkgkgoukei17 ,         /* （中継用）円貨払込額の合計（円貨）１７ */
     ztykihrkmp17 ,         /* （中継用）既払込保険料１７ */
     ztyw17 ,         /* （中継用）解約返戻金１７ */
     ztywyenyendaka17 ,         /* （中継用）解約返戻金（円貨）円高１７ */
     ztywyenkijun17 ,         /* （中継用）解約返戻金（円貨）中央値１７ */
     ztywyenyenyasu17 ,         /* （中継用）解約返戻金（円貨）円安１７ */
     ztykeikanensuu18 ,         /* （中継用）経過年数１８ */
     ztyhrkkknmnryumukbn18 ,         /* （中継用）払込期間満了有無区分１８ */
     ztyzennouzndkyen18 ,         /* （中継用）前納残高（円貨）１８ */
     ztyyenhrkgkgoukei18 ,         /* （中継用）円貨払込額の合計（円貨）１８ */
     ztykihrkmp18 ,         /* （中継用）既払込保険料１８ */
     ztyw18 ,         /* （中継用）解約返戻金１８ */
     ztywyenyendaka18 ,         /* （中継用）解約返戻金（円貨）円高１８ */
     ztywyenkijun18 ,         /* （中継用）解約返戻金（円貨）中央値１８ */
     ztywyenyenyasu18 ,         /* （中継用）解約返戻金（円貨）円安１８ */
     ztykeikanensuu19 ,         /* （中継用）経過年数１９ */
     ztyhrkkknmnryumukbn19 ,         /* （中継用）払込期間満了有無区分１９ */
     ztyzennouzndkyen19 ,         /* （中継用）前納残高（円貨）１９ */
     ztyyenhrkgkgoukei19 ,         /* （中継用）円貨払込額の合計（円貨）１９ */
     ztykihrkmp19 ,         /* （中継用）既払込保険料１９ */
     ztyw19 ,         /* （中継用）解約返戻金１９ */
     ztywyenyendaka19 ,         /* （中継用）解約返戻金（円貨）円高１９ */
     ztywyenkijun19 ,         /* （中継用）解約返戻金（円貨）中央値１９ */
     ztywyenyenyasu19 ,         /* （中継用）解約返戻金（円貨）円安１９ */
     ztykeikanensuu20 ,         /* （中継用）経過年数２０ */
     ztyhrkkknmnryumukbn20 ,         /* （中継用）払込期間満了有無区分２０ */
     ztyzennouzndkyen20 ,         /* （中継用）前納残高（円貨）２０ */
     ztyyenhrkgkgoukei20 ,         /* （中継用）円貨払込額の合計（円貨）２０ */
     ztykihrkmp20 ,         /* （中継用）既払込保険料２０ */
     ztyw20 ,         /* （中継用）解約返戻金２０ */
     ztywyenyendaka20 ,         /* （中継用）解約返戻金（円貨）円高２０ */
     ztywyenkijun20 ,         /* （中継用）解約返戻金（円貨）中央値２０ */
     ztywyenyenyasu20 ,         /* （中継用）解約返戻金（円貨）円安２０ */
     ztykeikanensuu21 ,         /* （中継用）経過年数２１ */
     ztyhrkkknmnryumukbn21 ,         /* （中継用）払込期間満了有無区分２１ */
     ztyzennouzndkyen21 ,         /* （中継用）前納残高（円貨）２１ */
     ztyyenhrkgkgoukei21 ,         /* （中継用）円貨払込額の合計（円貨）２１ */
     ztykihrkmp21 ,         /* （中継用）既払込保険料２１ */
     ztyw21 ,         /* （中継用）解約返戻金２１ */
     ztywyenyendaka21 ,         /* （中継用）解約返戻金（円貨）円高２１ */
     ztywyenkijun21 ,         /* （中継用）解約返戻金（円貨）中央値２１ */
     ztywyenyenyasu21 ,         /* （中継用）解約返戻金（円貨）円安２１ */
     ztykeikanensuu22 ,         /* （中継用）経過年数２２ */
     ztyhrkkknmnryumukbn22 ,         /* （中継用）払込期間満了有無区分２２ */
     ztyzennouzndkyen22 ,         /* （中継用）前納残高（円貨）２２ */
     ztyyenhrkgkgoukei22 ,         /* （中継用）円貨払込額の合計（円貨）２２ */
     ztykihrkmp22 ,         /* （中継用）既払込保険料２２ */
     ztyw22 ,         /* （中継用）解約返戻金２２ */
     ztywyenyendaka22 ,         /* （中継用）解約返戻金（円貨）円高２２ */
     ztywyenkijun22 ,         /* （中継用）解約返戻金（円貨）中央値２２ */
     ztywyenyenyasu22 ,         /* （中継用）解約返戻金（円貨）円安２２ */
     ztyyobiv188 ,         /* （中継用）予備項目Ｖ１８８ */
     ztyyobiv2 ,         /* （中継用）予備項目Ｖ２ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_SinkeiyakuSyoukenSuii2Ty_Z;