CREATE VIEW IT_BAK_TtdkKan AS SELECT
     kbnkey ,         /* 区分キー */
     syono ,         /* 証券番号 */
     trkssikibetukey ,         /* 取消識別キー */
     henkousikibetukey ,         /* 変更識別キー */
     syoruiCd ,         /* 書類コード */
     tyouhyouymd ,         /* 帳票作成日 */
     hassoukbn ,         /* 発送区分 */
     tantousitukbn ,         /* 担当室区分 */
     syoukendhumukbn ,         /* 証券同封有無区分 */
     shskyno ,         /* 送付先郵便番号 */
     shsadr1kj ,         /* 送付先住所１（漢字）（３０桁） */
     shsadr2kj ,         /* 送付先住所２（漢字）（３０桁） */
     shsadr3kj ,         /* 送付先住所３（漢字）（３０桁） */
     shsnmkj ,         /* 送付先氏名（漢字） */
     shsnmkj2 ,         /* 送付先氏名（漢字）２ */
     toiawasesosikinmkj ,         /* 問合せ先組織名（漢字） */
     toiawaseyno ,         /* 問合せ先郵便番号 */
     toiawaseadr1kj ,         /* 問合せ先住所１（漢字） */
     toiawaseadr2kj ,         /* 問合せ先住所２（漢字） */
     toiawaseadr3kj ,         /* 問合せ先住所３（漢字） */
     toiawasekaisyanmkj ,         /* 問合せ先会社名（漢字） */
     toiawasetelno ,         /* 問合せ先電話番号 */
     toiawaseteluktkkanou1 ,         /* 問合せ先電話受付可能時間１ */
     toiawaseteluktkkanou2 ,         /* 問合せ先電話受付可能時間２ */
     tetudukisyukbn ,         /* 手続種類区分 */
     shrumu ,         /* 支払有無区分 */
     syorikbn ,         /* 処理区分 */
     kyknmkj ,         /* 契約者名（漢字） */
     kykymd ,         /* 契約日 */
     syouhnnm ,         /* 商品名 */
     hhknnmkj ,         /* 被保険者名（漢字） */
     yenshrtktekiumu ,         /* 円支払特約適用有無 */
     ttdknaiyouumukbn ,         /* 手続内容有無区分 */
     ttdknaiyou1 ,         /* 手続内容１ */
     ttdknaiyou2 ,         /* 手続内容２ */
     ttdknaiyou3 ,         /* 手続内容３ */
     ttdknaiyou4 ,         /* 手続内容４ */
     ttdknaiyou5 ,         /* 手続内容５ */
     ttdknaiyou6 ,         /* 手続内容６ */
     ttdknaiyou7 ,         /* 手続内容７ */
     ttdknaiyou8 ,         /* 手続内容８ */
     ttdknaiyou9 ,         /* 手続内容９ */
     ttdknaiyou10 ,         /* 手続内容１０ */
     shrymd ,         /* 支払日 */
     calckijyunymd ,         /* 計算基準日 */
     kaiykymd ,         /* 解約日 */
     shrtuukasyu ,         /* 支払通貨種類 */
     shrtuukasyuryk ,         /* 支払通貨種類略称 */
     shrgkkei ,         /* 支払額合計 */
     shrgkkei$ ,         /* 支払額合計(通貨型) */
     hnkngk ,         /* 返金額 */
     hnkngk$ ,         /* 返金額(通貨型) */
     hnkntuukasyu ,         /* 返金通貨種類 */
     hnknymd ,         /* 返金日 */
     shrtienrsk ,         /* 支払遅延利息 */
     shrtienrsk$ ,         /* 支払遅延利息(通貨型) */
     tekiyou1 ,         /* 摘要１ */
     tekiyou2 ,         /* 摘要２ */
     tekiyou3 ,         /* 摘要３ */
     tekiyou4 ,         /* 摘要４ */
     tekiyou5 ,         /* 摘要５ */
     tekiyou6 ,         /* 摘要６ */
     tekiyou7 ,         /* 摘要７ */
     tekiyou8 ,         /* 摘要８ */
     tekiyou9 ,         /* 摘要９ */
     tekiyou10 ,         /* 摘要１０ */
     kngkmeisai1 ,         /* 金額明細１ */
     kngkmeisai1$ ,         /* 金額明細１(通貨型) */
     kngkmeisai2 ,         /* 金額明細２ */
     kngkmeisai2$ ,         /* 金額明細２(通貨型) */
     kngkmeisai3 ,         /* 金額明細３ */
     kngkmeisai3$ ,         /* 金額明細３(通貨型) */
     kngkmeisai4 ,         /* 金額明細４ */
     kngkmeisai4$ ,         /* 金額明細４(通貨型) */
     kngkmeisai5 ,         /* 金額明細５ */
     kngkmeisai5$ ,         /* 金額明細５(通貨型) */
     kngkmeisai6 ,         /* 金額明細６ */
     kngkmeisai6$ ,         /* 金額明細６(通貨型) */
     kngkmeisai7 ,         /* 金額明細７ */
     kngkmeisai7$ ,         /* 金額明細７(通貨型) */
     kngkmeisai8 ,         /* 金額明細８ */
     kngkmeisai8$ ,         /* 金額明細８(通貨型) */
     kngkmeisai9 ,         /* 金額明細９ */
     kngkmeisai9$ ,         /* 金額明細９(通貨型) */
     kngkmeisai10 ,         /* 金額明細１０ */
     kngkmeisai10$ ,         /* 金額明細１０(通貨型) */
     kngkmisituukasyu1 ,         /* 金額明細通貨種類１ */
     kngkmisituukasyu2 ,         /* 金額明細通貨種類２ */
     kngkmisituukasyu3 ,         /* 金額明細通貨種類３ */
     kngkmisituukasyu4 ,         /* 金額明細通貨種類４ */
     kngkmisituukasyu5 ,         /* 金額明細通貨種類５ */
     kngkmisituukasyu6 ,         /* 金額明細通貨種類６ */
     kngkmisituukasyu7 ,         /* 金額明細通貨種類７ */
     kngkmisituukasyu8 ,         /* 金額明細通貨種類８ */
     kngkmisituukasyu9 ,         /* 金額明細通貨種類９ */
     kngkmisituukasyu10 ,         /* 金額明細通貨種類１０ */
     bikou1 ,         /* 備考１ */
     bikou2 ,         /* 備考２ */
     bikou3 ,         /* 備考３ */
     bikou4 ,         /* 備考４ */
     bikou5 ,         /* 備考５ */
     bikou6 ,         /* 備考６ */
     bikou7 ,         /* 備考７ */
     bikou8 ,         /* 備考８ */
     bikou9 ,         /* 備考９ */
     bikou10 ,         /* 備考１０ */
     bankcd ,         /* 銀行コード */
     sitencd ,         /* 支店コード */
     banknmkj ,         /* 銀行名（漢字） */
     sitennmkj ,         /* 支店名（漢字） */
     yokinkbn ,         /* 預金種目区分 */
     kouzano ,         /* 口座番号 */
     kzsyuruikbn ,         /* 口座種類区分 */
     kzmeiginmkn ,         /* 口座名義人氏名（カナ） */
     soukinsakisiteikbn ,         /* 送金先指定区分 */
     htsiryosyukbn ,         /* 法定資料種類区分 */
     synykngk ,         /* 収入金額 */
     synykngk$ ,         /* 収入金額(通貨型) */
     htykeihi ,         /* 必要経費 */
     htykeihi$ ,         /* 必要経費(通貨型) */
     kaiyakujiyuu ,         /* 解約事由 */
     zeimumongonoutkbn ,         /* 税務文言出力区分 */
     zeimumongon1 ,         /* 税務文言１ */
     zeimumongon2 ,         /* 税務文言２ */
     zeimumongon3 ,         /* 税務文言３ */
     zeimumongon4 ,         /* 税務文言４ */
     zeimumongon5 ,         /* 税務文言５ */
     osirasemongonhyoudai ,         /* お知らせ文言表題 */
     osirasemongon1 ,         /* お知らせ文言１ */
     osirasemongon2 ,         /* お知らせ文言２ */
     osirasemongon3 ,         /* お知らせ文言３ */
     osirasemongon4 ,         /* お知らせ文言４ */
     osirasemongon5 ,         /* お知らせ文言５ */
     osirasemongon6 ,         /* お知らせ文言６ */
     osirasemongon7 ,         /* お知らせ文言７ */
     osirasemongon8 ,         /* お知らせ文言８ */
     osirasemongon9 ,         /* お知らせ文言９ */
     osirasemongon10 ,         /* お知らせ文言１０ */
     osirasemongon11 ,         /* お知らせ文言１１ */
     osirasemongon12 ,         /* お知らせ文言１２ */
     osirasemongon13 ,         /* お知らせ文言１３ */
     osirasemongon14 ,         /* お知らせ文言１４ */
     osirasemongon15 ,         /* お知らせ文言１５ */
     osirasemongon16 ,         /* お知らせ文言１６ */
     osirasemongon17 ,         /* お知らせ文言１７ */
     osirasemongon18 ,         /* お知らせ文言１８ */
     osirasemongon19 ,         /* お知らせ文言１９ */
     osirasemongon20 ,         /* お知らせ文言２０ */
     osirasemongon21 ,         /* お知らせ文言２１ */
     osirasemongon22 ,         /* お知らせ文言２２ */
     osirasemongon23 ,         /* お知らせ文言２３ */
     osirasemongon24 ,         /* お知らせ文言２４ */
     osirasemongon25 ,         /* お知らせ文言２５ */
     osirasemongon26 ,         /* お知らせ文言２６ */
     osirasemongon27 ,         /* お知らせ文言２７ */
     osirasemongon28 ,         /* お知らせ文言２８ */
     osirasemongon29 ,         /* お知らせ文言２９ */
     osirasemongon30 ,         /* お知らせ文言３０ */
     osirasemongon31 ,         /* お知らせ文言３１ */
     osirasemongon32 ,         /* お知らせ文言３２ */
     osirasemongon33 ,         /* お知らせ文言３３ */
     osirasemongon34 ,         /* お知らせ文言３４ */
     osirasemongon35 ,         /* お知らせ文言３５ */
     osirasemongon36 ,         /* お知らせ文言３６ */
     osirasemongon37 ,         /* お知らせ文言３７ */
     osirasemongon38 ,         /* お知らせ文言３８ */
     osirasemongon39 ,         /* お知らせ文言３９ */
     osirasemongon40 ,         /* お知らせ文言４０ */
     osirasemongon41 ,         /* お知らせ文言４１ */
     osirasemongon42 ,         /* お知らせ文言４２ */
     osirasemongon43 ,         /* お知らせ文言４３ */
     osirasemongon44 ,         /* お知らせ文言４４ */
     osirasemongon45 ,         /* お知らせ文言４５ */
     osirasemongon46 ,         /* お知らせ文言４６ */
     osirasemongon47 ,         /* お知らせ文言４７ */
     osirasemongon48 ,         /* お知らせ文言４８ */
     osirasemongon49 ,         /* お知らせ文言４９ */
     osirasemongon50 ,         /* お知らせ文言５０ */
     gyoumuKousinKinou ,         /* 業務用更新機能ＩＤ */
     gyoumuKousinsyaId ,         /* 業務用更新者ＩＤ */
     gyoumuKousinTime ,         /* 業務用更新時間 */
     shrkykhtykeihi ,         /* 支払時契約者必要経費 */
     shrkykhtykeihi$ ,         /* 支払時契約者必要経費(通貨型) */
     kykhnkkaisuu ,         /* 契約者変更回数 */
     zeimunaiyouhensyuctrlkbn ,         /* 税務内容編集制御区分 */
     kykniyuhnkkbn ,         /* 契約内容変更区分 */
     kykniyuhnkymd ,         /* 契約内容変更日 */
     kykniyuhnkinfo ,         /* 契約内容変更情報 */
     kykniyuhnkgkhugou1 ,         /* 契約内容変更金額明細符号１ */
     kykniyuhnkkngk1 ,         /* 契約内容変更金額１ */
     kykniyuhnkkngk1$ ,         /* 契約内容変更金額１(通貨型) */
     kykniyuhnkkngktuksyu1 ,         /* 契約内容変更金額通貨種類１ */
     kykniyuhnkkngkhugou2 ,         /* 契約内容変更金額明細符号２ */
     kykniyuhnkkngk2 ,         /* 契約内容変更金額２ */
     kykniyuhnkkngk2$ ,         /* 契約内容変更金額２(通貨型) */
     kykniyuhnkkngktuksyu2 ,         /* 契約内容変更金額通貨種類２ */
     gsbnrkztsaeki ,         /* 源泉分離課税対象差益 */
     gsbnrkztsaeki$ ,         /* 源泉分離課税対象差益(通貨型) */
     shrkngkmeisaihugou1 ,         /* 支払金額明細符号１ */
     shrkngkmeisaihugou2 ,         /* 支払金額明細符号２ */
     shrkngkmeisaihugou3 ,         /* 支払金額明細符号３ */
     shrkngkmeisaihugou4 ,         /* 支払金額明細符号４ */
     shrkngkmeisaihugou5 ,         /* 支払金額明細符号５ */
     shrkngkmeisaihugou6 ,         /* 支払金額明細符号６ */
     shrkngkmeisaihugou7 ,         /* 支払金額明細符号７ */
     shrkngkmeisaihugou8 ,         /* 支払金額明細符号８ */
     shrkngkmeisaihugou9 ,         /* 支払金額明細符号９ */
     shrkngkmeisaihugou10 ,         /* 支払金額明細符号１０ */
     documentid ,         /* ドキュメントＩＤ */
     sksmongonkbn1 ,         /* 請求書文言区分１ */
     sksmongonkbn2 ,         /* 請求書文言区分２ */
     toritugisyasyozokunm ,         /* 取次者所属名 */
     toritugisyakjncd ,         /* 取次者個人コード */
     toritugisyanm ,         /* 取次者氏名 */
     hozonKikan ,         /* 保存期間 */
     shrnaiyouhskmongon1 ,         /* 支払内容補足文言１ */
     shrnaiyouhskmongon2 ,         /* 支払内容補足文言２ */
     yendthnkzeimuinfohskkbn ,         /* 円建変更時税務情報補足区分 */
     yuuyokkntyoukaumu ,         /* 猶予期間超過有無 */
     tsintelno ,         /* 通信先電話番号 */
     dseisanshrttdknm ,         /* Ｄ精算支払手続名 */
     trkkzkkbn1 ,         /* 登録家族区分１ */
     trkkzknmkj1 ,         /* 登録家族名（漢字）１ */
     trkkzksei1 ,         /* 登録家族性別１ */
     trkkzkseiymd1 ,         /* 登録家族生年月日１ */
     trkkzkyno1 ,         /* 登録家族郵便番号１ */
     trkkzkadr1kj1 ,         /* 登録家族住所１（漢字）１ */
     trkkzkadr2kj1 ,         /* 登録家族住所２（漢字）１ */
     trkkzkadr3kj1 ,         /* 登録家族住所３（漢字）１ */
     trkkzktelno1 ,         /* 登録家族電話番号１ */
     trkkzktelnomtrkhyouji1 ,         /* 登録家族電話番号未登録表示１ */
     trkkzktdk1 ,         /* 登録家族続柄１ */
     trkkzkkbn2 ,         /* 登録家族区分２ */
     trkkzknmkj2 ,         /* 登録家族名（漢字）２ */
     trkkzksei2 ,         /* 登録家族性別２ */
     trkkzkseiymd2 ,         /* 登録家族生年月日２ */
     trkkzkyno2 ,         /* 登録家族郵便番号２ */
     trkkzkadr1kj2 ,         /* 登録家族住所１（漢字）２ */
     trkkzkadr2kj2 ,         /* 登録家族住所２（漢字）２ */
     trkkzkadr3kj2 ,         /* 登録家族住所３（漢字）２ */
     trkkzktelno2 ,         /* 登録家族電話番号２ */
     trkkzktdk2 ,         /* 登録家族続柄２ */
     kykdairinmkj ,         /* 契約者代理人名（漢字） */
     kykomttutkbn ,         /* 契約者用表通知区分 */
     kzkomttutkbn1 ,         /* 家族１用表通知区分 */
     kzkomttutkbn2 ,         /* 家族２用表通知区分 */
     hhkomttutkbn ,         /* 被保険者用表通知区分 */
     hhkdromttutkbn ,         /* 被保険者代理人用表通知区分 */
     kykdairiomttutkbn ,         /* 契約者代理人用表通知区分 */
     kykurtutkbn ,         /* 契約者用裏通知区分 */
     kzkurtutkbn1 ,         /* 家族１用裏通知区分 */
     kzkurtutkbn2 ,         /* 家族２用裏通知区分 */
     hhkdrurtutkbn ,         /* 被保険者代理人用裏通知区分 */
     kykdairiurtutkbn ,         /* 契約者代理人用裏通知区分 */
     kykaistmsgkbn ,         /* 契約者用挨拶ＭＳＧ区分 */
     kzkaistmsgkbn1 ,         /* 家族１用挨拶ＭＳＧ区分 */
     kzkaistmsgkbn2 ,         /* 家族２用挨拶ＭＳＧ区分 */
     hhkaistmsgkbn ,         /* 被保険者用挨拶ＭＳＧ区分 */
     hhkdraistmsgkbn ,         /* 被保険者代理人用挨拶ＭＳＧ区分 */
     kykdairiaistmsgkbn ,         /* 契約者代理人用挨拶ＭＳＧ区分 */
     sakujyokzknmkj ,         /* 削除家族名 */
     ttdknaiyoukbn ,         /* 手続内容区分 */
     kzktaisyoukykkbn ,         /* 家族用対象契約区分 */
     hhkdrtaisyoukykkbn ,         /* 被保険者代理人用対象契約区分 */
     kykdairitaisyoukykkbn ,         /* 契約者代理人用対象契約区分 */
     moshnkniymsgkbn1 ,         /* 申込変更内容ＭＳＧ区分１ */
     kykmoshnkniymsg2 ,         /* 契約者用申込変更内容ＭＳＧ区分２ */
     kzkmoshnkniymsg21 ,         /* 家族１用申込変更内容ＭＳＧ区分２ */
     kzkmoshnkniymsg22 ,         /* 家族２用申込変更内容ＭＳＧ区分２ */
     hhkdrmoshnkniymsg2 ,         /* 被保険者代理人用申込変更内容ＭＳＧ区分２ */
     kykdairimoshnkniymsg2 ,         /* 契約者代理人用申込変更内容ＭＳＧ区分２ */
     kykdrmsgkbn ,         /* 契約者代理ＭＳＧ区分 */
     kykhhkdrmsg ,         /* 契約者用被保険者代理ＭＳＧ区分 */
     kzkhhkdrmsg1 ,         /* 家族１用被保険者代理ＭＳＧ区分 */
     kzkhhkdrmsg2 ,         /* 家族２用被保険者代理ＭＳＧ区分 */
     hhkdrnmkj ,         /* 被保険者代理人名（漢字） */
     duhubutumsg ,         /* 同封物ＭＳＧ区分 */
     duhubutumsg1 ,         /* 同封物ＭＳＧ区分１ */
     duhubutumsg2 ,         /* 同封物ＭＳＧ区分２ */
     duhubutumsg3 ,         /* 同封物ＭＳＧ区分３ */
     duhubutumsg4 ,         /* 同封物ＭＳＧ区分４ */
     duhubutumsg5 ,         /* 同封物ＭＳＧ区分５ */
     duhubutumsg6 ,         /* 同封物ＭＳＧ区分６ */
     duhubutumsg7 ,         /* 同封物ＭＳＧ区分７ */
     kykigaidhbtmsg1 ,         /* 契約者以外用同封物ＭＳＧ区分１ */
     kykigaidhbtmsg2 ,         /* 契約者以外用同封物ＭＳＧ区分２ */
     kykigaidhbtmsg3 ,         /* 契約者以外用同封物ＭＳＧ区分３ */
     kykigaidhbtmsg4 ,         /* 契約者以外用同封物ＭＳＧ区分４ */
     kiyakuhunyuuhyouji ,         /* 規約封入表示 */
     yakkankiyakuhunyuuhyouji ,         /* 約款規約封入表示 */
     kyktrktrshuunyuuhyouji ,         /* 登録チラシ封入表示（契） */
     kzktrktrshuunyuuhyouji1 ,         /* 登録チラシ封入表示（家族１） */
     kzktrktrshuunyuuhyouji2 ,         /* 登録チラシ封入表示（家族２） */
     kykdrhuunyuuhyouji ,         /* 契約者代理封入表示 */
     hhkdrhuunyuuhyouji ,         /* 被保険者代理封入表示 */
     kykdairinmkj2 ,         /* 契約者代理人名（漢字）２ */
     kykdrseiymd ,         /* 契約者代理人生年月日 */
     kykdryno ,         /* 契約者代理人郵便番号 */
     kykdradr1kj ,         /* 契約者代理人住所１（漢字） */
     kykdradr2kj ,         /* 契約者代理人住所２（漢字） */
     kykdradr3kj ,         /* 契約者代理人住所３（漢字） */
     kykdrtelno ,         /* 契約者代理人電話番号 */
     hhkdrnmkj2 ,         /* 被保険者代理人名（漢字）２ */
     hhkdrseiymd ,         /* 被保険者代理人生年月日 */
     hhkdryno ,         /* 被保険者代理人郵便番号 */
     hhkdradr1kj ,         /* 被保険者代理人住所１（漢字） */
     hhkdradr2kj ,         /* 被保険者代理人住所２（漢字） */
     hhkdradr3kj ,         /* 被保険者代理人住所３（漢字） */
     hhkdrtelno ,         /* 被保険者代理人電話番号 */
     hhkdrtelnomtrkhyouji ,         /* 被保険者代理人電話番号未登録表示 */
     khsyono2 ,         /* （契約保全）証券番号２ */
     khsyono3 ,         /* （契約保全）証券番号３ */
     khsyono4 ,         /* （契約保全）証券番号４ */
     khsyono5 ,         /* （契約保全）証券番号５ */
     khsyono6 ,         /* （契約保全）証券番号６ */
     khsyono7 ,         /* （契約保全）証券番号７ */
     khsyono8 ,         /* （契約保全）証券番号８ */
     khsyono9 ,         /* （契約保全）証券番号９ */
     khsyono10 ,         /* （契約保全）証券番号１０ */
     khmosno1 ,         /* （契約保全）申込番号１ */
     khmosno2 ,         /* （契約保全）申込番号２ */
     khmosno3 ,         /* （契約保全）申込番号３ */
     khmosno4 ,         /* （契約保全）申込番号４ */
     khmosno5 ,         /* （契約保全）申込番号５ */
     khmosno6 ,         /* （契約保全）申込番号６ */
     khmosno7 ,         /* （契約保全）申込番号７ */
     khmosno8 ,         /* （契約保全）申込番号８ */
     khmosno9 ,         /* （契約保全）申込番号９ */
     khmosno10 ,         /* （契約保全）申込番号１０ */
     hnsnhutouhuunyuuhyouji ,         /* 返信用封筒封入表示 */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM IT_BAK_TtdkKan_Z;