CREATE VIEW ZT_RatewRn AS SELECT
     zrnhknsyukigou ,         /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn ,         /* （連携用）保険種類記号世代区分 */
     zrnyoteiriritu ,         /* （連携用）予定利率 */
     zrnpmenkbn ,         /* （連携用）Ｐ免区分 */
     zrnhrkkaisuukbn ,         /* （連携用）払込回数区分 */
     zrnhhknsei ,         /* （連携用）被保険者性別 */
     zrnkeiyakujihhknnen ,         /* （連携用）契約時被保険者年令 */
     zrnsaimnkkykhyj ,         /* （連携用）才満期契約表示 */
     zrnhknkkn ,         /* （連携用）保険期間 */
     zrnphrkkikn ,         /* （連携用）Ｐ払込期間 */
     zrnannaifuyouriyuukbn ,         /* （連携用）案内不要理由区分 */
     zrntuukasyukbn ,         /* （連携用）通貨種類区分 */
     zrndai1hknkkn ,         /* （連携用）第１保険期間 */
     zrnwrate00 ,         /* （連携用）Ｗレート００ */
     zrnwrate01 ,         /* （連携用）Ｗレート０１ */
     zrnwrate02 ,         /* （連携用）Ｗレート０２ */
     zrnwrate03 ,         /* （連携用）Ｗレート０３ */
     zrnwrate04 ,         /* （連携用）Ｗレート０４ */
     zrnwrate05 ,         /* （連携用）Ｗレート０５ */
     zrnwrate06 ,         /* （連携用）Ｗレート０６ */
     zrnwrate07 ,         /* （連携用）Ｗレート０７ */
     zrnwrate08 ,         /* （連携用）Ｗレート０８ */
     zrnwrate09 ,         /* （連携用）Ｗレート０９ */
     zrnwrate10 ,         /* （連携用）Ｗレート１０ */
     zrnwrate11 ,         /* （連携用）Ｗレート１１ */
     zrnwrate12 ,         /* （連携用）Ｗレート１２ */
     zrnwrate13 ,         /* （連携用）Ｗレート１３ */
     zrnwrate14 ,         /* （連携用）Ｗレート１４ */
     zrnwrate15 ,         /* （連携用）Ｗレート１５ */
     zrnwrate16 ,         /* （連携用）Ｗレート１６ */
     zrnwrate17 ,         /* （連携用）Ｗレート１７ */
     zrnwrate18 ,         /* （連携用）Ｗレート１８ */
     zrnwrate19 ,         /* （連携用）Ｗレート１９ */
     zrnwrate20 ,         /* （連携用）Ｗレート２０ */
     zrnwrate21 ,         /* （連携用）Ｗレート２１ */
     zrnwrate22 ,         /* （連携用）Ｗレート２２ */
     zrnwrate23 ,         /* （連携用）Ｗレート２３ */
     zrnwrate24 ,         /* （連携用）Ｗレート２４ */
     zrnwrate25 ,         /* （連携用）Ｗレート２５ */
     zrnwrate26 ,         /* （連携用）Ｗレート２６ */
     zrnwrate27 ,         /* （連携用）Ｗレート２７ */
     zrnwrate28 ,         /* （連携用）Ｗレート２８ */
     zrnwrate29 ,         /* （連携用）Ｗレート２９ */
     zrnwrate30 ,         /* （連携用）Ｗレート３０ */
     zrnwrate31 ,         /* （連携用）Ｗレート３１ */
     zrnwrate32 ,         /* （連携用）Ｗレート３２ */
     zrnwrate33 ,         /* （連携用）Ｗレート３３ */
     zrnwrate34 ,         /* （連携用）Ｗレート３４ */
     zrnwrate35 ,         /* （連携用）Ｗレート３５ */
     zrnwrate36 ,         /* （連携用）Ｗレート３６ */
     zrnwrate37 ,         /* （連携用）Ｗレート３７ */
     zrnwrate38 ,         /* （連携用）Ｗレート３８ */
     zrnwrate39 ,         /* （連携用）Ｗレート３９ */
     zrnwrate40 ,         /* （連携用）Ｗレート４０ */
     zrnwrate41 ,         /* （連携用）Ｗレート４１ */
     zrnwrate42 ,         /* （連携用）Ｗレート４２ */
     zrnwrate43 ,         /* （連携用）Ｗレート４３ */
     zrnwrate44 ,         /* （連携用）Ｗレート４４ */
     zrnwrate45 ,         /* （連携用）Ｗレート４５ */
     zrnwrate46 ,         /* （連携用）Ｗレート４６ */
     zrnwrate47 ,         /* （連携用）Ｗレート４７ */
     zrnwrate48 ,         /* （連携用）Ｗレート４８ */
     zrnwrate49 ,         /* （連携用）Ｗレート４９ */
     zrnwrate50 ,         /* （連携用）Ｗレート５０ */
     zrnwrate51 ,         /* （連携用）Ｗレート５１ */
     zrnwrate52 ,         /* （連携用）Ｗレート５２ */
     zrnwrate53 ,         /* （連携用）Ｗレート５３ */
     zrnwrate54 ,         /* （連携用）Ｗレート５４ */
     zrnwrate55 ,         /* （連携用）Ｗレート５５ */
     zrnwrate56 ,         /* （連携用）Ｗレート５６ */
     zrnwrate57 ,         /* （連携用）Ｗレート５７ */
     zrnwrate58 ,         /* （連携用）Ｗレート５８ */
     zrnwrate59 ,         /* （連携用）Ｗレート５９ */
     zrnwrate60 ,         /* （連携用）Ｗレート６０ */
     zrnwrate61 ,         /* （連携用）Ｗレート６１ */
     zrnwrate62 ,         /* （連携用）Ｗレート６２ */
     zrnwrate63 ,         /* （連携用）Ｗレート６３ */
     zrnwrate64 ,         /* （連携用）Ｗレート６４ */
     zrnwrate65 ,         /* （連携用）Ｗレート６５ */
     zrnwrate66 ,         /* （連携用）Ｗレート６６ */
     zrnwrate67 ,         /* （連携用）Ｗレート６７ */
     zrnwrate68 ,         /* （連携用）Ｗレート６８ */
     zrnwrate69 ,         /* （連携用）Ｗレート６９ */
     zrnwrate70 ,         /* （連携用）Ｗレート７０ */
     zrnwrate71 ,         /* （連携用）Ｗレート７１ */
     zrnwrate72 ,         /* （連携用）Ｗレート７２ */
     zrnwrate73 ,         /* （連携用）Ｗレート７３ */
     zrnwrate74 ,         /* （連携用）Ｗレート７４ */
     zrnwrate75 ,         /* （連携用）Ｗレート７５ */
     zrnwrate76 ,         /* （連携用）Ｗレート７６ */
     zrnwrate77 ,         /* （連携用）Ｗレート７７ */
     zrnwrate78 ,         /* （連携用）Ｗレート７８ */
     zrnwrate79 ,         /* （連携用）Ｗレート７９ */
     zrnwrate80 ,         /* （連携用）Ｗレート８０ */
     zrnwrate81 ,         /* （連携用）Ｗレート８１ */
     zrnwrate82 ,         /* （連携用）Ｗレート８２ */
     zrnwrate83 ,         /* （連携用）Ｗレート８３ */
     zrnwrate84 ,         /* （連携用）Ｗレート８４ */
     zrnwrate85 ,         /* （連携用）Ｗレート８５ */
     zrnwrate86 ,         /* （連携用）Ｗレート８６ */
     zrnwrate87 ,         /* （連携用）Ｗレート８７ */
     zrnwrate88 ,         /* （連携用）Ｗレート８８ */
     zrnwrate89 ,         /* （連携用）Ｗレート８９ */
     zrnwrate90 ,         /* （連携用）Ｗレート９０ */
     zrnwrate91 ,         /* （連携用）Ｗレート９１ */
     zrnwrate92 ,         /* （連携用）Ｗレート９２ */
     zrnwrate93 ,         /* （連携用）Ｗレート９３ */
     zrnwrate94 ,         /* （連携用）Ｗレート９４ */
     zrnwrate95 ,         /* （連携用）Ｗレート９５ */
     zrnwrate96 ,         /* （連携用）Ｗレート９６ */
     zrnwrate97 ,         /* （連携用）Ｗレート９７ */
     zrnwrate98 ,         /* （連携用）Ｗレート９８ */
     zrnwrate99           /* （連携用）Ｗレート９９ */
FROM ZT_RatewRn_Z;