CREATE VIEW ZT_KoujyoSyoumeiTy AS SELECT
     ztysyoruicd ,         /* （中継用）書類コード */
     ztytyouhyouymd ,         /* （中継用）帳票作成日 */
     ztysyono ,         /* （中継用）証券番号 */
     ztyhassoukbn ,         /* （中継用）発送区分 */
     ztysyodouhuukbn ,         /* （中継用）証券同封区分 */
     ztysikibetuno ,         /* （中継用）識別番号 */
     ztykoujyosyoumeisentakukbn ,         /* （中継用）控除証明選択区分 */
     ztyyobiv43 ,         /* （中継用）予備項目Ｖ４３ */
     ztyshskyno ,         /* （中継用）送付先郵便番号 */
     ztyshskadr1kj ,         /* （中継用）送付先住所１（漢字） */
     ztyshskadr2kj ,         /* （中継用）送付先住所２（漢字） */
     ztyshskadr3kj ,         /* （中継用）送付先住所３（漢字） */
     ztyshsnmkj ,         /* （中継用）送付先名（漢字） */
     ztyyobiv1 ,         /* （中継用）予備項目Ｖ１ */
     ztykyknmkn ,         /* （中継用）契約者名（カナ） */
     ztyuktnmkn ,         /* （中継用）受取人名（カナ） */
     ztytawsosikikj ,         /* （中継用）問合せ先組織名（漢字） */
     ztytawyno ,         /* （中継用）問合せ先郵便番号 */
     ztytawadr1kj ,         /* （中継用）問合せ先住所１（漢字） */
     ztytawadr2kj ,         /* （中継用）問合せ先住所２（漢字） */
     ztytawadr3kj ,         /* （中継用）問合せ先住所３（漢字） */
     ztytawtelnov14 ,         /* （中継用）問合せ先電話番号Ｖ１４ */
     ztytawteluktkkanou1 ,         /* （中継用）問合せ先電話受付可能時間１ */
     ztytawteluktkkanou2 ,         /* （中継用）問合せ先電話受付可能時間２ */
     ztydai2tawsosikinmkj ,         /* （中継用）第２問合せ先組織名（漢字） */
     ztydai2tawtelno ,         /* （中継用）第２問合せ先電話番号 */
     ztysclatosyono ,         /* （中継用）スクランブル後証券番号 */
     ztysakunm ,         /* （中継用）作成番号 */
     ztyyobiv56 ,         /* （中継用）予備項目Ｖ５６ */
     ztykyknmkj ,         /* （中継用）契約者名（漢字） */
     ztysyoumeinndwa ,         /* （中継用）証明年度（和暦） */
     ztyuktnmknmeikj ,         /* （中継用）受取人名（漢字） */
     ztynenkinuktseiymdwa ,         /* （中継用）年金受取人生年月日（和暦） */
     ztysyono3 ,         /* （中継用）証券番号３ */
     ztyhknsyurui ,         /* （中継用）保険種類 */
     ztynknshrynnm ,         /* （中継用）年金支払期間（数） */
     ztykykymdwa ,         /* （中継用）契約年月日（和暦） */
     ztyhtkinuthoukbn ,         /* （中継用）配当金受取方法区分 */
     ztyhknkknnm ,         /* （中継用）保険期間（数） */
     ztynkshrstartymdwa ,         /* （中継用）年金支払開始日（和暦） */
     ztyphrkkkn ,         /* （中継用）保険料払込期間 */
     ztyhrkkaisuunm ,         /* （中継用）払込回数（数） */
     ztykjnnkkoujyum ,         /* （中継用）個人年金控除有無 */
     ztyyobiv49 ,         /* （中継用）予備項目Ｖ４９ */
     ztyippanseimeip ,         /* （中継用）一般生命保険料（新制度） */
     ztyippanhaitoukin ,         /* （中継用）一般配当金（新制度） */
     ztyippansyoumeigk ,         /* （中継用）一般証明額（新制度） */
     ztykaigoiryoup ,         /* （中継用）介護医療保険料（新制度） */
     ztykaigoiryoud ,         /* （中継用）介護医療配当金（新制度） */
     ztykaigoiryousmgk ,         /* （中継用）介護医療証明額（新制度） */
     ztynenkinp ,         /* （中継用）年金保険料（新制度） */
     ztynenkind ,         /* （中継用）年金配当金（新制度） */
     ztynenkinsmgk ,         /* （中継用）年金証明額（新制度） */
     ztynewhknjytukikan ,         /* （中継用）新制度保険充当期間 */
     ztyphrkkknjyoutai ,         /* （中継用）保険料払込状態 */
     ztysyoumeiymdwa ,         /* （中継用）証明日（和暦） */
     ztynenippanseimeip ,         /* （中継用）年間一般生命保険料（新制度） */
     ztynenippand ,         /* （中継用）年間一般配当金（新制度） */
     ztynenippansymgk ,         /* （中継用）年間一般証明額（新制度） */
     ztynenkaigoiryoup ,         /* （中継用）年間介護医療保険料（新制度） */
     ztynenkaigoiryoud ,         /* （中継用）年間介護医療配当金（新制度） */
     ztyneniryousymgk ,         /* （中継用）年間介護医療証明額（新制度） */
     ztynennenkinp ,         /* （中継用）年間年金保険料（新制度） */
     ztynennenkind ,         /* （中継用）年間年金配当金（新制度） */
     ztynennenkinsmgk ,         /* （中継用）年間年金証明額（新制度） */
     ztyyobiv42 ,         /* （中継用）予備項目Ｖ４２ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_KoujyoSyoumeiTy_Z;