CREATE VIEW ZT_Sp2RnduyuSouseiritu2Ty AS SELECT
     ztyktgysyrymd ,         /* （中継用）結合用処理日 */
     ztyktgysyono ,         /* （中継用）結合用証券番号 */
     ztyktgyfilerenno ,         /* （中継用）結合用ファイル連番 */
     ztysiteidairininkbn ,         /* （中継用）指定代理人区分 */
     ztystdairiseikyuutkykarihyj ,         /* （中継用）指定代理請求特約有表示 */
     ztysrkykdrkbn ,         /* （中継用）数理用契約者代理人区分 */
     ztykykdrtkykarihyj ,         /* （中継用）契約者代理特約有表示 */
     ztyyobiv6x3 ,         /* （中継用）予備項目Ｖ６＿３ */
     ztylivingneedstkykarihyj ,         /* （中継用）リビングニーズ特約有表示 */
     ztyyobiv4x12 ,         /* （中継用）予備項目Ｖ４＿１２ */
     ztygansupporttkykarihyj ,         /* （中継用）がんサポート特約有表示 */
     ztyyobiv4x13 ,         /* （中継用）予備項目Ｖ４＿１３ */
     ztytuuintokuyakusyuruikigou ,         /* （中継用）通院特約種類記号 */
     ztytuuintokuyakukikan ,         /* （中継用）通院特約期間 */
     ztytuintkykphrkkkn ,         /* （中継用）通院特約Ｐ払込期間 */
     ztytuuintokuyakunitigaku ,         /* （中継用）通院特約日額 */
     ztytuuintokuyakup ,         /* （中継用）通院特約Ｐ */
     ztytuuintokuyakugatakbn ,         /* （中継用）通院特約型区分 */
     ztytuintkjyuryumshyutn ,         /* （中継用）通院特条料増標点 */
     ztytuuintokujyoup ,         /* （中継用）通院特条Ｐ */
     ztytuuintokuteibuicdx1 ,         /* （中継用）通院特定部位コード＿１ */
     ztytuuinhutanpokikanx1 ,         /* （中継用）通院不担保期間＿１ */
     ztytuuintokuteibuicdx2 ,         /* （中継用）通院特定部位コード＿２ */
     ztytuuinhutanpokikanx2 ,         /* （中継用）通院不担保期間＿２ */
     ztytuintkykkgusdkbn ,         /* （中継用）通院特約記号世代区分 */
     ztytuintkykpwrbkkbn ,         /* （中継用）通院特約Ｐ割引区分 */
     ztyyobiv3x4 ,         /* （中継用）予備項目Ｖ３＿４ */
     ztydi2tuintkyksyrikgu ,         /* （中継用）第２通院特約種類記号 */
     ztydai2tuuintokuyakukikan ,         /* （中継用）第２通院特約期間 */
     ztydai2tuintkykphrkkkn ,         /* （中継用）第２通院特約Ｐ払込期間 */
     ztydai2tuuintokuyakuntgk ,         /* （中継用）第２通院特約日額 */
     ztydai2tuuintokuyakup ,         /* （中継用）第２通院特約Ｐ */
     ztydai2tuuintokuyakugatakbn ,         /* （中継用）第２通院特約型区分 */
     ztydi2tuintkjyuryumshyutn ,         /* （中継用）第２通院特条料増標点 */
     ztydai2tuuintokujyoup ,         /* （中継用）第２通院特条Ｐ */
     ztydai2tuuintokuteibuicdx1 ,         /* （中継用）第２通院特定部位コード＿１ */
     ztydai2tuuinhutanpokikanx1 ,         /* （中継用）第２通院不担保期間＿１ */
     ztydai2tuuintokuteibuicdx2 ,         /* （中継用）第２通院特定部位コード＿２ */
     ztydai2tuuinhutanpokikanx2 ,         /* （中継用）第２通院不担保期間＿２ */
     ztydi2tuintkykkgusdkbn ,         /* （中継用）第２通院特約記号世代区分 */
     ztydi2tuintkykpwrbkkbn ,         /* （中継用）第２通院特約Ｐ割引区分 */
     ztyyobiv3x5 ,         /* （中継用）予備項目Ｖ３＿５ */
     ztykangotokuyakusyuruikigou ,         /* （中継用）看護特約種類記号 */
     ztykangotokuyakukikan ,         /* （中継用）看護特約期間 */
     ztykangotkykphrkkkn ,         /* （中継用）看護特約Ｐ払込期間 */
     ztykangotokuyakunitigaku ,         /* （中継用）看護特約日額 */
     ztykangotokuyakup ,         /* （中継用）看護特約Ｐ */
     ztykangotokuyakugatakbn ,         /* （中継用）看護特約型区分 */
     ztykngtkjyuryumshyutn ,         /* （中継用）看護特条料増標点 */
     ztykangotokujyoup ,         /* （中継用）看護特条Ｐ */
     ztykangotokuteibuicdx1 ,         /* （中継用）看護特定部位コード＿１ */
     ztykangohutanpokikanx1 ,         /* （中継用）看護不担保期間＿１ */
     ztykangotokuteibuicdx2 ,         /* （中継用）看護特定部位コード＿２ */
     ztykangohutanpokikanx2 ,         /* （中継用）看護不担保期間＿２ */
     ztyyobiv6 ,         /* （中継用）予備項目Ｖ６ */
     ztydi2kngtkyksyrikgu ,         /* （中継用）第２看護特約種類記号 */
     ztydai2kangotokuyakukikan ,         /* （中継用）第２看護特約期間 */
     ztydai2kngtkykphrkkkn ,         /* （中継用）第２看護特約Ｐ払込期間 */
     ztydai2kangotokuyakuntgk ,         /* （中継用）第２看護特約日額 */
     ztydai2kangotokuyakup ,         /* （中継用）第２看護特約Ｐ */
     ztydai2kangotokuyakugatakbn ,         /* （中継用）第２看護特約型区分 */
     ztydi2kngtkjyuryumshyutn ,         /* （中継用）第２看護特条料増標点 */
     ztydai2kangotokujyoup ,         /* （中継用）第２看護特条Ｐ */
     ztydai2kangotokuteibuicdx1 ,         /* （中継用）第２看護特定部位コード＿１ */
     ztydai2kangohutanpokikanx1 ,         /* （中継用）第２看護不担保期間＿１ */
     ztydai2kangotokuteibuicdx2 ,         /* （中継用）第２看護特定部位コード＿２ */
     ztydai2kangohutanpokikanx2 ,         /* （中継用）第２看護不担保期間＿２ */
     ztyyobiv6x2 ,         /* （中継用）予備項目Ｖ６＿２ */
     ztyjysisppitkyksyuruikgu ,         /* （中継用）女性疾病特約種類記号 */
     ztyjysisppitkykkkn ,         /* （中継用）女性疾病特約期間 */
     ztyjysisppitkykphrkkkn ,         /* （中継用）女性疾病特約Ｐ払込期間 */
     ztyjysisppitkykntgk ,         /* （中継用）女性疾病特約日額 */
     ztyjyoseisippeitokuyakup ,         /* （中継用）女性疾病特約Ｐ */
     ztyjysisppitkjyuryumshyutn ,         /* （中継用）女性疾病特条料増標点 */
     ztyjyoseisippeitokujyoup ,         /* （中継用）女性疾病特条Ｐ */
     ztyjysisppitktbicdx1 ,         /* （中継用）女性疾病特定部位コード＿１ */
     ztyjysisppihtnpkknx1 ,         /* （中継用）女性疾病不担保期間＿１ */
     ztyjysisppitktbicdx2 ,         /* （中継用）女性疾病特定部位コード＿２ */
     ztyjysisppihtnpkknx2 ,         /* （中継用）女性疾病不担保期間＿２ */
     ztyjysisppitkykkgusdkbn ,         /* （中継用）女性疾病特約記号世代区分 */
     ztyjysisppitkykpwrbkkbn ,         /* （中継用）女性疾病特約Ｐ割引区分 */
     ztyjysisppitkykkusnmnryoage ,         /* （中継用）女性疾病特約更新満了年令 */
     ztyyobiv2x2 ,         /* （中継用）予備項目Ｖ２＿２ */
     ztydi2jysisppitkyksyrikgu ,         /* （中継用）第２女性疾病特約種類記号 */
     ztydi2jysisppitkykkkn ,         /* （中継用）第２女性疾病特約期間 */
     ztydi2jysisppitkykphrkkkn ,         /* （中継用）第２女性疾病特約Ｐ払込期間 */
     ztydi2jysisppitkykntgk ,         /* （中継用）第２女性疾病特約日額 */
     ztydi2jysisppitkykp ,         /* （中継用）第２女性疾病特約Ｐ */
     ztydi2jysisppitkjyurymshytn ,         /* （中継用）第２女性疾病特条料増標点 */
     ztydi2jysisppitkjyup ,         /* （中継用）第２女性疾病特条Ｐ */
     ztydi2jysisppitktbicdx1 ,         /* （中継用）第２女性疾病特定部位コード＿１ */
     ztydi2jysisppihtnpkknx1 ,         /* （中継用）第２女性疾病不担保期間＿１ */
     ztydi2jysisppitktbicdx2 ,         /* （中継用）第２女性疾病特定部位コード＿２ */
     ztydi2jysisppihtnpkknx2 ,         /* （中継用）第２女性疾病不担保期間＿２ */
     ztydi2jysisppitkykkgusdkbn ,         /* （中継用）第２女性疾病特約記号世代区分 */
     ztydi2jysisppitkykpwrbkkbn ,         /* （中継用）第２女性疾病特約Ｐ割引区分 */
     ztyyobiv4x14 ,         /* （中継用）予備項目Ｖ４＿１４ */
     ztywinninglifehyouji ,         /* （中継用）ウィニングライフ表示 */
     ztystyouikusikinuktrininkbn ,         /* （中継用）指定養育資金受取人区分 */
     ztyjyudthumeharaitkykarihyj ,         /* （中継用）重度痴呆前払特約有表示 */
     ztysinkenkouseikatupackhyj ,         /* （中継用）新健康生活パック表示 */
     ztysyukeiyakupwaribikikbn ,         /* （中継用）主契約Ｐ割引区分 */
     ztysykyktnknyugukbn ,         /* （中継用）主契約転換優遇区分 */
     ztymosjihonninkknnkbn ,         /* （中継用）申込時本人確認区分 */
     ztykituenhonsuu ,         /* （中継用）喫煙本数 */
     ztykousinmaetenkannensuukbn ,         /* （中継用）更新前転換年数区分 */
     ztymankimaetenkannensuukbn ,         /* （中継用）満期前転換年数区分 */
     ztyseikitenkanhyouji ,         /* （中継用）正規転換表示 */
     ztygengakutenkankykhyj ,         /* （中継用）減額転換契約表示 */
     ztyyobiv2x3 ,         /* （中継用）予備項目Ｖ２＿３ */
     ztykousin3nenmaetnknhyj ,         /* （中継用）更新３年前転換表示 */
     ztydugktnknsntkhuhukbn ,         /* （中継用）同額転換選択方法区分 */
     ztytnknsnstkbttrtkkbn ,         /* （中継用）転換診査特別取扱区分 */
     ztyhtnknsiginyuintkykgkntgk ,         /* （中継用）被転換災害入院特約合計日額 */
     ztyhtnknsiginyuintkykkykymd ,         /* （中継用）被転換災害入院特約契約年月日 */
     ztyhtnknsiginyuintkyksnskbn ,         /* （中継用）被転換災害入院特約診査区分 */
     ztyhtnknsppinyuintkykgkntgk ,         /* （中継用）被転換疾病入院特約合計日額 */
     ztyhtnknsppinyuintkykkykymd ,         /* （中継用）被転換疾病入院特約契約年月日 */
     ztyhtnknsppinyuintkyksnskbn ,         /* （中継用）被転換疾病入院特約診査区分 */
     ztyhtnknsijnbyutkykgukintgk ,         /* （中継用）被転換成人病特約合計日額 */
     ztyhtnknsijnbyutkykkykymd ,         /* （中継用）被転換成人病特約契約年月日 */
     ztyhtnknsijnbyutkyksnskbn ,         /* （中継用）被転換成人病特約診査区分 */
     ztyhtnknjysisppitkykgkintgk ,         /* （中継用）被転換女性疾病特約合計日額 */
     ztyhtnknjysisppitkykkykymd ,         /* （中継用）被転換女性疾病特約契約年月日 */
     ztyhtnknjysisppitkyksnskbn ,         /* （中継用）被転換女性疾病特約診査区分 */
     ztysiteizukipwarimasihyouji ,         /* （中継用）指定月Ｐ割増表示 */
     ztypwarimasisiteim1 ,         /* （中継用）Ｐ割増指定月１ */
     ztypwarimasisiteim2 ,         /* （中継用）Ｐ割増指定月２ */
     ztysiteimsykykpbairitu ,         /* （中継用）指定月主契約Ｐ倍率 */
     ztysiteizukisyukeiyakup ,         /* （中継用）指定月主契約Ｐ */
     ztytuujyoutukiharaikomip ,         /* （中継用）通常月払込Ｐ */
     ztysiteizukiharaikomip ,         /* （中継用）指定月払込Ｐ */
     ztymaruteikisiteizukip ,         /* （中継用）マル定指定月Ｐ */
     ztyseizonmaruteisiteimp ,         /* （中継用）生存マル定指定月Ｐ */
     ztymaruteipsiteibairitu ,         /* （中継用）マル定Ｐ指定倍率 */
     ztyseizonmaruteipstbairitu ,         /* （中継用）生存マル定Ｐ指定倍率 */
     ztynkdtmrtisyuruikgu ,         /* （中継用）年金建マル定種類記号 */
     ztynenkindatemaruteikikan ,         /* （中継用）年金建マル定期間 */
     ztynkdatemaruteiphrkkkn ,         /* （中継用）年金建マル定Ｐ払込期間 */
     ztynkdatemaruteinenkinnengk ,         /* （中継用）年金建マル定年金年額 */
     ztynenkindatemaruteis ,         /* （中継用）年金建マル定Ｓ */
     ztynenkindatemaruteip ,         /* （中継用）年金建マル定Ｐ */
     ztynkdatemaruteimods ,         /* （中継用）年金建マル定修正Ｓ */
     ztynkdtmrtimodsskgnhyj ,         /* （中継用）年金建マル定修正Ｓ削減表示 */
     ztynkdatemaruteitkjyoukbn ,         /* （中継用）年金建マル定特条区分 */
     ztynkdtmrtitkjyouskgnkkn ,         /* （中継用）年金建マル定特条削減期間 */
     ztynkdtmrtitkjyouryumshytn ,         /* （中継用）年金建マル定特条料増標点 */
     ztynkdatemaruteitkjyoup ,         /* （中継用）年金建マル定特条Ｐ */
     ztyhtnknnkdtmrtisyuruikgux1 ,         /* （中継用）被転換年金建マル定種類記号＿１ */
     ztyhtnknnkdtmrtisyuruikgux2 ,         /* （中継用）被転換年金建マル定種類記号＿２ */
     ztyhtnknnkdtmrtisyuruikgux3 ,         /* （中継用）被転換年金建マル定種類記号＿３ */
     ztyhtnknnkdtmrtisyuruikgux4 ,         /* （中継用）被転換年金建マル定種類記号＿４ */
     ztyhtnknnkdtmrtisyuruikgux5 ,         /* （中継用）被転換年金建マル定種類記号＿５ */
     ztyhtnknnkdtmrtisyuruikgux6 ,         /* （中継用）被転換年金建マル定種類記号＿６ */
     ztynkdatemaruteishrkkn ,         /* （中継用）年金建マル定支払期間 */
     ztysuriyounkdtmrtipwrbkkbn ,         /* （中継用）数理用年金建マル定Ｐ割引区分 */
     ztynkdatemaruteipwrbkkbn ,         /* （中継用）年金建マル定Ｐ割引区分 */
     ztyhtnknkyksiteimhyjx1 ,         /* （中継用）被転換契約指定月表示＿１ */
     ztyhtnknkyksiteimhyjx2 ,         /* （中継用）被転換契約指定月表示＿２ */
     ztyhtnknkyksiteimhyjx3 ,         /* （中継用）被転換契約指定月表示＿３ */
     ztyhtnknkyksiteimhyjx4 ,         /* （中継用）被転換契約指定月表示＿４ */
     ztyhtnknkyksiteimhyjx5 ,         /* （中継用）被転換契約指定月表示＿５ */
     ztyhtnknkyksiteimhyjx6 ,         /* （中継用）被転換契約指定月表示＿６ */
     ztytyohkreinyutkbttrtkhyj ,         /* （中継用）重複戻入特別取扱表示 */
     ztykazokumrtinknengk ,         /* （中継用）家族マル定年金年額 */
     ztyalmyoukijyunym ,         /* （中継用）ＡＬＭ用基準年月 */
     ztysetaitesyono2 ,         /* （中継用）セット相手証券番号２ */
     ztysetaitehokensyuruikigou2 ,         /* （中継用）セット相手保険種類記号２ */
     ztysetaitemrtisyuruikgu2 ,         /* （中継用）セット相手マル定種類記号２ */
     ztysetaitesiznmrtisyurui2 ,         /* （中継用）セット相手生存マル定種類２ */
     ztysetaitetignmrtisyurui2 ,         /* （中継用）セット相手逓減マル定種類２ */
     ztysetaitekihonbubuns2 ,         /* （中継用）セット相手基本部分Ｓ２ */
     ztysetgukitnknitjbrkhns2 ,         /* （中継用）セット合計転換一時払基本Ｓ２ */
     ztysetaitesibous2 ,         /* （中継用）セット相手死亡Ｓ２ */
     ztysetgukitnknitjbrsbus2 ,         /* （中継用）セット合計転換一時払死亡Ｓ２ */
     ztysetaitesyuuseis2 ,         /* （中継用）セット相手修正Ｓ２ */
     ztysetaiteharaikomip2 ,         /* （中継用）セット相手払込Ｐ２ */
     ztysetaitesyukeiyakububunp2 ,         /* （中継用）セット相手主契約部分Ｐ２ */
     ztysetaitgukikzkmrtis2 ,         /* （中継用）セット相手合計家族マル定Ｓ２ */
     ztysetaitetenkankykhyj2 ,         /* （中継用）セット相手転換契約表示２ */
     ztysetaitesiteimhrkp2 ,         /* （中継用）セット相手指定月払込Ｐ２ */
     ztysetaitesiteimsykykp2 ,         /* （中継用）セット相手指定月主契約Ｐ２ */
     ztysetaitenkmrtisyurui2 ,         /* （中継用）セット相手年金マル定種類２ */
     ztysetaitehknkgusdkbn2 ,         /* （中継用）セット相手保険記号世代区分２ */
     ztyyobiv17 ,         /* （中継用）予備項目Ｖ１７ */
     ztydujmossitismodsyuguhyj ,         /* （中継用）同時申込最低Ｓ修正Ｓ優遇表示 */
     ztyrnsijhiyubrijdujmoskbn ,         /* （中継用）連生時併用払時同時申込区分 */
     ztytktsppisykyktikknbbns ,         /* （中継用）特定疾病主契約待期間部分Ｓ */
     ztytksttkyksyuruikgu ,         /* （中継用）特疾特約種類記号 */
     ztytokusitutokuyakukikan ,         /* （中継用）特疾特約期間 */
     ztytksttkykphrkkkn ,         /* （中継用）特疾特約Ｐ払込期間 */
     ztytokusitutokuyakus ,         /* （中継用）特疾特約Ｓ */
     ztytokusitutokuyakup ,         /* （中継用）特疾特約Ｐ */
     ztytokusitutokuyakusyuuseis ,         /* （中継用）特疾特約修正Ｓ */
     ztytksttkykmodssakugenhyj ,         /* （中継用）特疾特約修正Ｓ削減表示 */
     ztytksttkyktkjyukbn ,         /* （中継用）特疾特約特条区分 */
     ztytksttkyktkjyuskgnkkn ,         /* （中継用）特疾特約特条削減期間 */
     ztytksttkyktkjyuryumshyutn ,         /* （中継用）特疾特約特条料増標点 */
     ztytksttkyktkjyup ,         /* （中継用）特疾特約特条Ｐ */
     ztytksttkyktikknbbns ,         /* （中継用）特疾特約待期間部分Ｓ */
     ztyhtnkntktsppitkykkgux1 ,         /* （中継用）被転換特定疾病特約記号＿１ */
     ztyhtnkntktsppitkykkgux2 ,         /* （中継用）被転換特定疾病特約記号＿２ */
     ztyhtnkntktsppitkykkgux3 ,         /* （中継用）被転換特定疾病特約記号＿３ */
     ztyhtnkntktsppitkykkgux4 ,         /* （中継用）被転換特定疾病特約記号＿４ */
     ztyhtnkntktsppitkykkgux5 ,         /* （中継用）被転換特定疾病特約記号＿５ */
     ztyhtnkntktsppitkykkgux6 ,         /* （中継用）被転換特定疾病特約記号＿６ */
     ztysuryutksttkykpwrbkkbn ,         /* （中継用）数理用特疾特約Ｐ割引区分 */
     ztytksttkykpwrbkkbn ,         /* （中継用）特疾特約Ｐ割引区分 */
     ztytksttkyktnknyugukbn ,         /* （中継用）特疾特約転換優遇区分 */
     ztytksttkykkgusdkbn ,         /* （中継用）特疾特約記号世代区分 */
     ztyyobiv9x8 ,         /* （中継用）予備項目Ｖ９＿８ */
     ztydi2tksttkyksyrikgu ,         /* （中継用）第２特疾特約種類記号 */
     ztydai2tokusitutokuyakukkn ,         /* （中継用）第２特疾特約期間 */
     ztydai2tksttkykphrkkkn ,         /* （中継用）第２特疾特約Ｐ払込期間 */
     ztydai2tokusitutokuyakus ,         /* （中継用）第２特疾特約Ｓ */
     ztydai2tokusitutokuyakup ,         /* （中継用）第２特疾特約Ｐ */
     ztydi2tksttkyksyuuseis ,         /* （中継用）第２特疾特約修正Ｓ */
     ztydi2tksttkykmodsskgnhyj ,         /* （中継用）第２特疾特約修正Ｓ削減表示 */
     ztydi2tksttkyktkjyukbn ,         /* （中継用）第２特疾特約特条区分 */
     ztydi2tksttkyktkjyuskgnkkn ,         /* （中継用）第２特疾特約特条削減期間 */
     ztydi2tksttkyktkjyurymshytn ,         /* （中継用）第２特疾特約特条料増標点 */
     ztydi2tksttkyktkjyup ,         /* （中継用）第２特疾特約特条Ｐ */
     ztydi2tksttkyktaikknbbns ,         /* （中継用）第２特疾特約待期間部分Ｓ */
     ztyhtnkndi2tktsppitkykkgux1 ,         /* （中継用）被転換第２特定疾病特約記号＿１ */
     ztyhtnkndi2tktsppitkykkgux2 ,         /* （中継用）被転換第２特定疾病特約記号＿２ */
     ztyhtnkndi2tktsppitkykkgux3 ,         /* （中継用）被転換第２特定疾病特約記号＿３ */
     ztyhtnkndi2tktsppitkykkgux4 ,         /* （中継用）被転換第２特定疾病特約記号＿４ */
     ztyhtnkndi2tktsppitkykkgux5 ,         /* （中継用）被転換第２特定疾病特約記号＿５ */
     ztyhtnkndi2tktsppitkykkgux6 ,         /* （中継用）被転換第２特定疾病特約記号＿６ */
     ztysuryudi2tksttkykpwrbkkbn ,         /* （中継用）数理用第２特疾特約Ｐ割引区分 */
     ztydi2tksttkykpwrbkkbn ,         /* （中継用）第２特疾特約Ｐ割引区分 */
     ztydi2tksttkyktnknyugukbn ,         /* （中継用）第２特疾特約転換優遇区分 */
     ztydi2tksttkykkgusdkbn ,         /* （中継用）第２特疾特約記号世代区分 */
     ztyyobiv9x9 ,         /* （中継用）予備項目Ｖ９＿９ */
     ztyjyuusitutkyksyuruikgu ,         /* （中継用）重疾特約種類記号 */
     ztyjyuusitutokuyakukikan ,         /* （中継用）重疾特約期間 */
     ztyjyuusitutkykphrkkkn ,         /* （中継用）重疾特約Ｐ払込期間 */
     ztyjyuusitutokuyakus ,         /* （中継用）重疾特約Ｓ */
     ztyjyuusitutokuyakup ,         /* （中継用）重疾特約Ｐ */
     ztyjyuusitutokuyakusyuuseis ,         /* （中継用）重疾特約修正Ｓ */
     ztyjyuusitutkykmodsskgnhyj ,         /* （中継用）重疾特約修正Ｓ削減表示 */
     ztyjyuusitutkyktkjyukbn ,         /* （中継用）重疾特約特条区分 */
     ztyjyuusitutkyktkjyuskgnkkn ,         /* （中継用）重疾特約特条削減期間 */
     ztyjyusttkyktkjyuryumshyutn ,         /* （中継用）重疾特約特条料増標点 */
     ztyjyuusitutkyktkjyup ,         /* （中継用）重疾特約特条Ｐ */
     ztyjyuusitutkyktktbicdx1 ,         /* （中継用）重疾特約特定部位コード＿１ */
     ztyjyuusitutkykhtnpkknx1 ,         /* （中継用）重疾特約不担保期間＿１ */
     ztyjyuusitutkyktktbicdx2 ,         /* （中継用）重疾特約特定部位コード＿２ */
     ztyjyuusitutkykhtnpkknx2 ,         /* （中継用）重疾特約不担保期間＿２ */
     ztyhtnknmnsiskkntkykkgux1 ,         /* （中継用）被転換慢性疾患特約記号＿１ */
     ztyhtnknmnsiskkntkykkgux2 ,         /* （中継用）被転換慢性疾患特約記号＿２ */
     ztyhtnknmnsiskkntkykkgux3 ,         /* （中継用）被転換慢性疾患特約記号＿３ */
     ztyhtnknmnsiskkntkykkgux4 ,         /* （中継用）被転換慢性疾患特約記号＿４ */
     ztyhtnknmnsiskkntkykkgux5 ,         /* （中継用）被転換慢性疾患特約記号＿５ */
     ztyhtnknmnsiskkntkykkgux6 ,         /* （中継用）被転換慢性疾患特約記号＿６ */
     ztysuryujyusttkykpwrbkkbn ,         /* （中継用）数理用重疾特約Ｐ割引区分 */
     ztyjyuusitutkykpwrbkkbn ,         /* （中継用）重疾特約Ｐ割引区分 */
     ztyjyuusitutkyktnknyugukbn ,         /* （中継用）重疾特約転換優遇区分 */
     ztyjyuusitutkykkgusdkbn ,         /* （中継用）重疾特約記号世代区分 */
     ztyyobiv7x3 ,         /* （中継用）予備項目Ｖ７＿３ */
     ztydi2jyuusitutkyksyrikgu ,         /* （中継用）第２重疾特約種類記号 */
     ztydi2jyuusitutkykkkn ,         /* （中継用）第２重疾特約期間 */
     ztydi2jyuusitutkykphrkkkn ,         /* （中継用）第２重疾特約Ｐ払込期間 */
     ztydai2jyuusitutokuyakus ,         /* （中継用）第２重疾特約Ｓ */
     ztydai2jyuusitutokuyakup ,         /* （中継用）第２重疾特約Ｐ */
     ztydi2jyuusitutkyksyuuseis ,         /* （中継用）第２重疾特約修正Ｓ */
     ztydi2jyusttkykmodsskgnhyj ,         /* （中継用）第２重疾特約修正Ｓ削減表示 */
     ztydi2jyuusitutkyktkjyukbn ,         /* （中継用）第２重疾特約特条区分 */
     ztydi2jyusttkyktkjyuskgnkkn ,         /* （中継用）第２重疾特約特条削減期間 */
     ztydi2jyusttkyktkjyrymshytn ,         /* （中継用）第２重疾特約特条料増標点 */
     ztydi2jyuusitutkyktkjyup ,         /* （中継用）第２重疾特約特条Ｐ */
     ztydi2jyuusitutkyktktbicdx1 ,         /* （中継用）第２重疾特約特定部位コード＿１ */
     ztydi2jyuusitutkykhtnpkknx1 ,         /* （中継用）第２重疾特約不担保期間＿１ */
     ztydi2jyuusitutkyktktbicdx2 ,         /* （中継用）第２重疾特約特定部位コード＿２ */
     ztydi2jyuusitutkykhtnpkknx2 ,         /* （中継用）第２重疾特約不担保期間＿２ */
     ztyhtnkndi2mnsiskkntkykkgx1 ,         /* （中継用）被転換第２慢性疾患特約記号＿１ */
     ztyhtnkndi2mnsiskkntkykkgx2 ,         /* （中継用）被転換第２慢性疾患特約記号＿２ */
     ztyhtnkndi2mnsiskkntkykkgx3 ,         /* （中継用）被転換第２慢性疾患特約記号＿３ */
     ztyhtnkndi2mnsiskkntkykkgx4 ,         /* （中継用）被転換第２慢性疾患特約記号＿４ */
     ztyhtnkndi2mnsiskkntkykkgx5 ,         /* （中継用）被転換第２慢性疾患特約記号＿５ */
     ztyhtnkndi2mnsiskkntkykkgx6 ,         /* （中継用）被転換第２慢性疾患特約記号＿６ */
     ztysuryud2jyusttkykpwrbkkbn ,         /* （中継用）数理用第２重疾特約Ｐ割引区分 */
     ztydi2jyuusitutkykpwrbkkbn ,         /* （中継用）第２重疾特約Ｐ割引区分 */
     ztydi2jyusttkyktnknyugukbn ,         /* （中継用）第２重疾特約転換優遇区分 */
     ztydi2jyuusitutkykkgusdkbn ,         /* （中継用）第２重疾特約記号世代区分 */
     ztyyobiv7x4 ,         /* （中継用）予備項目Ｖ７＿４ */
     ztyhaitousiharaikbn ,         /* （中継用）配当支払区分 */
     ztysuryusykykpwrbkkbn ,         /* （中継用）数理用主契約Ｐ割引区分 */
     ztynkdatetokuteisyuruikgu ,         /* （中継用）年金建トク定種類記号 */
     ztynenkindatetokuteikikan ,         /* （中継用）年金建トク定期間 */
     ztynkdatetokuteinkgk ,         /* （中継用）年金建トク定年金額 */
     ztynenkindatetokuteis ,         /* （中継用）年金建トク定Ｓ */
     ztynenkindatetokuteip ,         /* （中継用）年金建トク定Ｐ */
     ztynkdatetokuteisdtpdtkbn ,         /* （中継用）年金建トク定Ｓ建Ｐ建区分 */
     ztynkdatetokuteimods ,         /* （中継用）年金建トク定修正Ｓ */
     ztynkdatetokuteimodsskgnhyj ,         /* （中継用）年金建トク定修正Ｓ削減表示 */
     ztynkdatetokuteishrkkn ,         /* （中継用）年金建トク定支払期間 */
     ztykykniyutksytioukbn ,         /* （中継用）契約内容特殊対応区分 */
     ztykeika2nenmimantenkanhyj ,         /* （中継用）経過２年未満転換表示 */
     ztytukiyuhtnknkusnmennsukbn ,         /* （中継用）統計用被転換更新前年数区分 */
     ztynkdatetokuteikgusdkbn ,         /* （中継用）年金建トク定記号世代区分 */
     ztynenkindatetokuteikatakbn ,         /* （中継用）年金建トク定型区分 */
     ztyyobiv2x4 ,         /* （中継用）予備項目Ｖ２＿４ */
     ztysugusnsyutkyksyuruikgu ,         /* （中継用）総合損傷特約種類記号 */
     ztysugusnsyutkykkkn ,         /* （中継用）総合損傷特約期間 */
     ztysugusnsyutkykphrkkkn ,         /* （中継用）総合損傷特約Ｐ払込期間 */
     ztysougousonsyoutokuyakus ,         /* （中継用）総合損傷特約Ｓ */
     ztysougousonsyoutokuyakup ,         /* （中継用）総合損傷特約Ｐ */
     ztysugusnsyutkykkgusdkbn ,         /* （中継用）総合損傷特約記号世代区分 */
     ztysugusnsyutkykpwrbkkbn ,         /* （中継用）総合損傷特約Ｐ割引区分 */
     ztysugusnsyutkykkusnmnryage ,         /* （中継用）総合損傷特約更新満了年令 */
     ztyyobiv7x5 ,         /* （中継用）予備項目Ｖ７＿５ */
     ztydi2sugusnsyutkyksyrikgu ,         /* （中継用）第２総合損傷特約種類記号 */
     ztydi2sugusnsyutkykkkn ,         /* （中継用）第２総合損傷特約期間 */
     ztydi2sugusnsyutkykphrkkkn ,         /* （中継用）第２総合損傷特約Ｐ払込期間 */
     ztydi2sugusnsyutkyks ,         /* （中継用）第２総合損傷特約Ｓ */
     ztydi2sugusnsyutkykp ,         /* （中継用）第２総合損傷特約Ｐ */
     ztydi2sugusnsytkykkgusdkbn ,         /* （中継用）第２総合損傷特約記号世代区分 */
     ztydi2sugusnsyutkykpwrbkkbn ,         /* （中継用）第２総合損傷特約Ｐ割引区分 */
     ztyyobiv9x10 ,         /* （中継用）予備項目Ｖ９＿１０ */
     ztytenkankeitaikbn ,         /* （中継用）転換形態区分 */
     ztygukitnknitjbrtiknknengk ,         /* （中継用）合計転換一時払定期年金年額 */
     ztygukihtnknsugusnsyutkyks ,         /* （中継用）合計被転換総合損傷特約Ｓ */
     ztytenkanitijibaraip ,         /* （中継用）転換一時払Ｐ */
     ztyyobiv24 ,         /* （中継用）予備項目Ｖ２４ */
     ztygoukeinenbaraikansanpx1 ,         /* （中継用）合計年払換算Ｐ＿１ */
     ztyhktgtikkikkknx1 ,         /* （中継用）引継定期経過期間＿１ */
     ztyhtnknkykkigmrsysyrikgux1 ,         /* （中継用）被転換契約介護マル終種類記号＿１ */
     ztygoukeinenbaraikansanpx2 ,         /* （中継用）合計年払換算Ｐ＿２ */
     ztyhktgtikkikkknx2 ,         /* （中継用）引継定期経過期間＿２ */
     ztyhtnknkykkigmrsysyrikgux2 ,         /* （中継用）被転換契約介護マル終種類記号＿２ */
     ztygoukeinenbaraikansanpx3 ,         /* （中継用）合計年払換算Ｐ＿３ */
     ztyhktgtikkikkknx3 ,         /* （中継用）引継定期経過期間＿３ */
     ztyhtnknkykkigmrsysyrikgux3 ,         /* （中継用）被転換契約介護マル終種類記号＿３ */
     ztygoukeinenbaraikansanpx4 ,         /* （中継用）合計年払換算Ｐ＿４ */
     ztyhktgtikkikkknx4 ,         /* （中継用）引継定期経過期間＿４ */
     ztyhtnknkykkigmrsysyrikgux4 ,         /* （中継用）被転換契約介護マル終種類記号＿４ */
     ztygoukeinenbaraikansanpx5 ,         /* （中継用）合計年払換算Ｐ＿５ */
     ztyhktgtikkikkknx5 ,         /* （中継用）引継定期経過期間＿５ */
     ztyhtnknkykkigmrsysyrikgux5 ,         /* （中継用）被転換契約介護マル終種類記号＿５ */
     ztygoukeinenbaraikansanpx6 ,         /* （中継用）合計年払換算Ｐ＿６ */
     ztyhktgtikkikkknx6 ,         /* （中継用）引継定期経過期間＿６ */
     ztyhtnknkykkigmrsysyrikgux6 ,         /* （中継用）被転換契約介護マル終種類記号＿６ */
     ztyniceonplanhyj ,         /* （中継用）ナイスオンプラン表示 */
     ztysyokaipryosyuymd ,         /* （中継用）初回Ｐ領収年月日 */
     ztyldownmaetenkannensuukbn ,         /* （中継用）Ｌダウン前転換年数区分 */
     ztyldownmaesaiteismitatuhyj ,         /* （中継用）Ｌダウン前最低Ｓ未達表示 */
     ztydntitikgtkbttrtkhyj ,         /* （中継用）団体定期後特別取扱表示 */
     ztyreformkbn ,         /* （中継用）リフォーム区分 */
     ztykikeiyakutyuuihyouji ,         /* （中継用）既契約注意表示 */
     ztykbnkeiriyousegcd ,         /* （中継用）区分経理用ＳＥＧコード */
     ztysyuuseiskiteitekiyoukbn ,         /* （中継用）修正Ｓ規程適用区分 */
     ztygukihtnknkzkmrtimods ,         /* （中継用）合計被転換家族マル定修正Ｓ */
     ztytnknkijyntkyuhtnknsbus ,         /* （中継用）転換基準適用被転換死亡Ｓ */
     ztysrjsnyusyouhinhyj ,         /* （中継用）白地専用商品表示 */
     ztysirajikakuninzumihyouji ,         /* （中継用）白地確認済表示 */
     ztysrjsnyusyouhintknnhyj ,         /* （中継用）白地専用商品特認表示 */
     ztysinsakbn ,         /* （中継用）診査区分 */
     ztydai2sinsakbn ,         /* （中継用）第２診査区分 */
     ztytoukeiyousinsakbn ,         /* （中継用）統計用診査区分 */
     ztydai2toukeiyousinsakbn ,         /* （中継用）第２統計用診査区分 */
     ztyseizonkyuhknshrsiteimd ,         /* （中継用）生存給付金支払指定月日 */
     ztyyoteiriritun5 ,         /* （中継用）予定利率Ｎ５ */
     ztysaiteihosyouriritu ,         /* （中継用）最低保障利率 */
     ztynkgnsritu ,         /* （中継用）年金原資率 */
     ztyjigyounendomatuv ,         /* （中継用）事業年度末Ｖ */
     ztyyobin11 ,         /* （中継用）予備項目Ｎ１１ */
     ztygukihtnkn5nnmeksnyumods ,         /* （中継用）合計被転換５年前加算用修正Ｓ */
     ztyrenseiteikitksyusnksnhyj ,         /* （中継用）連生定期付終身加算表示 */
     ztygoukeinenbaraikansanp2x1 ,         /* （中継用）合計年払換算Ｐ２＿１ */
     ztygukinenbaraiknsnp2kbnx1 ,         /* （中継用）合計年払換算Ｐ２区分＿１ */
     ztyhktgtikkikkkn2x1 ,         /* （中継用）引継定期経過期間２＿１ */
     ztygoukeinenbaraikansanp2x2 ,         /* （中継用）合計年払換算Ｐ２＿２ */
     ztygukinenbaraiknsnp2kbnx2 ,         /* （中継用）合計年払換算Ｐ２区分＿２ */
     ztyhktgtikkikkkn2x2 ,         /* （中継用）引継定期経過期間２＿２ */
     ztygoukeinenbaraikansanp2x3 ,         /* （中継用）合計年払換算Ｐ２＿３ */
     ztygukinenbaraiknsnp2kbnx3 ,         /* （中継用）合計年払換算Ｐ２区分＿３ */
     ztyhktgtikkikkkn2x3 ,         /* （中継用）引継定期経過期間２＿３ */
     ztygoukeinenbaraikansanp2x4 ,         /* （中継用）合計年払換算Ｐ２＿４ */
     ztygukinenbaraiknsnp2kbnx4 ,         /* （中継用）合計年払換算Ｐ２区分＿４ */
     ztyhktgtikkikkkn2x4 ,         /* （中継用）引継定期経過期間２＿４ */
     ztygoukeinenbaraikansanp2x5 ,         /* （中継用）合計年払換算Ｐ２＿５ */
     ztygukinenbaraiknsnp2kbnx5 ,         /* （中継用）合計年払換算Ｐ２区分＿５ */
     ztyhktgtikkikkkn2x5 ,         /* （中継用）引継定期経過期間２＿５ */
     ztygoukeinenbaraikansanp2x6 ,         /* （中継用）合計年払換算Ｐ２＿６ */
     ztygukinenbaraiknsnp2kbnx6 ,         /* （中継用）合計年払換算Ｐ２区分＿６ */
     ztyhktgtikkikkkn2x6 ,         /* （中継用）引継定期経過期間２＿６ */
     ztykokutituusantaisyous ,         /* （中継用）告知通算対象Ｓ */
     ztytokusyuyouroumankis ,         /* （中継用）特殊養老満期Ｓ */
     ztynkdtmrtitnknyuuguukbn ,         /* （中継用）年金建マル定転換優遇区分 */
     ztynkdtmrtikgusdkbn ,         /* （中継用）年金建マル定記号世代区分 */
     ztynenkindatemaruteikatakbn ,         /* （中継用）年金建マル定型区分 */
     ztynkdtmrtikusnmnryoage ,         /* （中継用）年金建マル定更新満了年令 */
     ztykaigonkdtmrtisyuruikgu ,         /* （中継用）介護年金建マル定種類記号 */
     ztykaigonkdtmrtikkan ,         /* （中継用）介護年金建マル定期間 */
     ztykaigonkdtmrtiphrkkkn ,         /* （中継用）介護年金建マル定Ｐ払込期間 */
     ztykaigonkdtmrtinnknnengk ,         /* （中継用）介護年金建マル定年金年額 */
     ztykaigonkdtmrtis ,         /* （中継用）介護年金建マル定Ｓ */
     ztykaigonkdtmrtip ,         /* （中継用）介護年金建マル定Ｐ */
     ztykaigonkdtmrtimods ,         /* （中継用）介護年金建マル定修正Ｓ */
     ztykaigonkdtmrtitkjyukbn ,         /* （中継用）介護年金建マル定特条区分 */
     ztykaigonkdtmrtitkjyskgnkkn ,         /* （中継用）介護年金建マル定特条削減期間 */
     ztykaigonkdtmrttkjyrymshytn ,         /* （中継用）介護年金建マル定特条料増標点 */
     ztykaigonkdtmrtitkjyup ,         /* （中継用）介護年金建マル定特条Ｐ */
     ztyhtnknkaigonkmrtsyrikgux1 ,         /* （中継用）被転換介護年金マル定種類記号＿１ */
     ztyhtnknkaigonkmrtsyrikgux2 ,         /* （中継用）被転換介護年金マル定種類記号＿２ */
     ztyhtnknkaigonkmrtsyrikgux3 ,         /* （中継用）被転換介護年金マル定種類記号＿３ */
     ztyhtnknkaigonkmrtsyrikgux4 ,         /* （中継用）被転換介護年金マル定種類記号＿４ */
     ztyhtnknkaigonkmrtsyrikgux5 ,         /* （中継用）被転換介護年金マル定種類記号＿５ */
     ztyhtnknkaigonkmrtsyrikgux6 ,         /* （中継用）被転換介護年金マル定種類記号＿６ */
     ztykaigonkdtmrtishrkkn ,         /* （中継用）介護年金建マル定支払期間 */
     ztysurikaigonkmrtipwrbkkbn ,         /* （中継用）数理介護年金マル定Ｐ割引区分 */
     ztykaigonkdtmrtipwrbkkbn ,         /* （中継用）介護年金建マル定Ｐ割引区分 */
     ztykaigonkdtmrtitnknyugukbn ,         /* （中継用）介護年金建マル定転換優遇区分 */
     ztykaigonkdtmrtikgusdkbn ,         /* （中継用）介護年金建マル定記号世代区分 */
     ztykaigonkdtmrtiktkbn ,         /* （中継用）介護年金建マル定型区分 */
     ztykignkdtmrtikusnmnryoage ,         /* （中継用）介護年金建マル定更新満了年令 */
     ztykaigonkdttktisyuruikgu ,         /* （中継用）介護年金建トク定種類記号 */
     ztykaigonkdttktikkn ,         /* （中継用）介護年金建トク定期間 */
     ztykaigonkdttkteinenkngk ,         /* （中継用）介護年金建トク定年金額 */
     ztykaigonenkindatetokuteis ,         /* （中継用）介護年金建トク定Ｓ */
     ztykaigonenkindatetokuteip ,         /* （中継用）介護年金建トク定Ｐ */
     ztykaigonkdttktisdtpdtkbn ,         /* （中継用）介護年金建トク定Ｓ建Ｐ建区分 */
     ztykaigonkdttktimods ,         /* （中継用）介護年金建トク定修正Ｓ */
     ztykaigonkdttktishrkkn ,         /* （中継用）介護年金建トク定支払期間 */
     ztykaigonkdttktikgusdkbn ,         /* （中継用）介護年金建トク定記号世代区分 */
     ztykaigonkdttktiktkbn ,         /* （中継用）介護年金建トク定型区分 */
     ztykignkdttktikusnmnryoage ,         /* （中継用）介護年金建トク定更新満了年令 */
     ztyyobiv2x5 ,         /* （中継用）予備項目Ｖ２＿５ */
     ztykaigoteigenmrtisyuruikgu ,         /* （中継用）介護逓減マル定種類記号 */
     ztykaigoteigenmaruteikikan ,         /* （中継用）介護逓減マル定期間 */
     ztykaigotignmrtiphrkkkn ,         /* （中継用）介護逓減マル定Ｐ払込期間 */
     ztykaigoteigenmaruteis ,         /* （中継用）介護逓減マル定Ｓ */
     ztykaigoteigenmaruteip ,         /* （中継用）介護逓減マル定Ｐ */
     ztykigtignmrtimods ,         /* （中継用）介護逓減マル定修正Ｓ */
     ztykigtignmrtitkjyukbn ,         /* （中継用）介護逓減マル定特条区分 */
     ztykigtignmrtitkjyuskgnkkn ,         /* （中継用）介護逓減マル定特条削減期間 */
     ztykigtignmrtitkjyurymshytn ,         /* （中継用）介護逓減マル定特条料増標点 */
     ztykigtignmrtitkjyup ,         /* （中継用）介護逓減マル定特条Ｐ */
     ztyhtnknkigtignmrtsyrikgux1 ,         /* （中継用）被転換介護逓減マル定種類記号＿１ */
     ztyhtnknkigtignmrtsyrikgux2 ,         /* （中継用）被転換介護逓減マル定種類記号＿２ */
     ztyhtnknkigtignmrtsyrikgux3 ,         /* （中継用）被転換介護逓減マル定種類記号＿３ */
     ztyhtnknkigtignmrtsyrikgux4 ,         /* （中継用）被転換介護逓減マル定種類記号＿４ */
     ztyhtnknkigtignmrtsyrikgux5 ,         /* （中継用）被転換介護逓減マル定種類記号＿５ */
     ztyhtnknkigtignmrtsyrikgux6 ,         /* （中継用）被転換介護逓減マル定種類記号＿６ */
     ztysurkigtignmrtipwrbkkbn ,         /* （中継用）数理介護逓減マル定Ｐ割引区分 */
     ztykigtignmrtipwrbkkbn ,         /* （中継用）介護逓減マル定Ｐ割引区分 */
     ztykigtignmrtitnknyugukbn ,         /* （中継用）介護逓減マル定転換優遇区分 */
     ztykaigotignmrtikgusdkbn ,         /* （中継用）介護逓減マル定記号世代区分 */
     ztykigtignmrtikusnmnryoage ,         /* （中継用）介護逓減マル定更新満了年令 */
     ztyyobiv4x15 ,         /* （中継用）予備項目Ｖ４＿１５ */
     ztykaigoteigentktisyuruikgu ,         /* （中継用）介護逓減トク定種類記号 */
     ztykaigoteigentokuteikikan ,         /* （中継用）介護逓減トク定期間 */
     ztykaigoteigentokuteis ,         /* （中継用）介護逓減トク定Ｓ */
     ztykaigoteigentokuteip ,         /* （中継用）介護逓減トク定Ｐ */
     ztykigtigntktisdtpdtkbn ,         /* （中継用）介護逓減トク定Ｓ建Ｐ建区分 */
     ztykigtigntktimods ,         /* （中継用）介護逓減トク定修正Ｓ */
     ztykaigotigntktikgusdkbn ,         /* （中継用）介護逓減トク定記号世代区分 */
     ztykigtigntktikusnmnryoage ,         /* （中継用）介護逓減トク定更新満了年令 */
     ztyyobiv2x6 ,         /* （中継用）予備項目Ｖ２＿６ */
     ztyhikitugikaimasis ,         /* （中継用）引継買増Ｓ */
     ztycbkyhtisyukykumkbn ,         /* （中継用）ＣＢ給付対象契約有無区分 */
     ztytukiyucbkyhtisyus ,         /* （中継用）統計用ＣＢ給付対象Ｓ */
     ztycbhanteituusans ,         /* （中継用）ＣＢ判定通算Ｓ */
     ztytukiyusnkykcbhntis ,         /* （中継用）統計用新契約ＣＢ判定Ｓ */
     ztycbstagekbn ,         /* （中継用）ＣＢステージ区分 */
     ztytoukeiyoucbhanteituusans ,         /* （中継用）統計用ＣＢ判定通算Ｓ */
     ztycbtuusankensuu ,         /* （中継用）ＣＢ通算件数 */
     ztycbhanteitaisyoutsnkensuu ,         /* （中継用）ＣＢ判定対象通算件数 */
     ztytyokuzentuusanhanteisx1 ,         /* （中継用）直前通算判定Ｓ＿１ */
     ztytyokuzenkyuuhutaisyousx1 ,         /* （中継用）直前給付対象Ｓ＿１ */
     ztytyokuzencbgakux1 ,         /* （中継用）直前ＣＢ額＿１ */
     ztytyokugotuusanhanteisx1 ,         /* （中継用）直後通算判定Ｓ＿１ */
     ztytyokugokyuuhutaisyousx1 ,         /* （中継用）直後給付対象Ｓ＿１ */
     ztytyokugocbgakux1 ,         /* （中継用）直後ＣＢ額＿１ */
     ztyyobiv12 ,         /* （中継用）予備項目Ｖ１２ */
     ztytyokuzentuusanhanteisx2 ,         /* （中継用）直前通算判定Ｓ＿２ */
     ztytyokuzenkyuuhutaisyousx2 ,         /* （中継用）直前給付対象Ｓ＿２ */
     ztytyokuzencbgakux2 ,         /* （中継用）直前ＣＢ額＿２ */
     ztytyokugotuusanhanteisx2 ,         /* （中継用）直後通算判定Ｓ＿２ */
     ztytyokugokyuuhutaisyousx2 ,         /* （中継用）直後給付対象Ｓ＿２ */
     ztytyokugocbgakux2 ,         /* （中継用）直後ＣＢ額＿２ */
     ztyyobiv12x2 ,         /* （中継用）予備項目Ｖ１２＿２ */
     ztytyokuzentuusanhanteisx3 ,         /* （中継用）直前通算判定Ｓ＿３ */
     ztytyokuzenkyuuhutaisyousx3 ,         /* （中継用）直前給付対象Ｓ＿３ */
     ztytyokuzencbgakux3 ,         /* （中継用）直前ＣＢ額＿３ */
     ztytyokugotuusanhanteisx3 ,         /* （中継用）直後通算判定Ｓ＿３ */
     ztytyokugokyuuhutaisyousx3 ,         /* （中継用）直後給付対象Ｓ＿３ */
     ztytyokugocbgakux3 ,         /* （中継用）直後ＣＢ額＿３ */
     ztyyobiv12x3 ,         /* （中継用）予備項目Ｖ１２＿３ */
     ztytyokuzentuusanhanteisx4 ,         /* （中継用）直前通算判定Ｓ＿４ */
     ztytyokuzenkyuuhutaisyousx4 ,         /* （中継用）直前給付対象Ｓ＿４ */
     ztytyokuzencbgakux4 ,         /* （中継用）直前ＣＢ額＿４ */
     ztytyokugotuusanhanteisx4 ,         /* （中継用）直後通算判定Ｓ＿４ */
     ztytyokugokyuuhutaisyousx4 ,         /* （中継用）直後給付対象Ｓ＿４ */
     ztytyokugocbgakux4 ,         /* （中継用）直後ＣＢ額＿４ */
     ztyyobiv12x4 ,         /* （中継用）予備項目Ｖ１２＿４ */
     ztytyokuzentuusanhanteisx5 ,         /* （中継用）直前通算判定Ｓ＿５ */
     ztytyokuzenkyuuhutaisyousx5 ,         /* （中継用）直前給付対象Ｓ＿５ */
     ztytyokuzencbgakux5 ,         /* （中継用）直前ＣＢ額＿５ */
     ztytyokugotuusanhanteisx5 ,         /* （中継用）直後通算判定Ｓ＿５ */
     ztytyokugokyuuhutaisyousx5 ,         /* （中継用）直後給付対象Ｓ＿５ */
     ztytyokugocbgakux5 ,         /* （中継用）直後ＣＢ額＿５ */
     ztyyobiv12x5 ,         /* （中継用）予備項目Ｖ１２＿５ */
     ztytyokuzentuusanhanteisx6 ,         /* （中継用）直前通算判定Ｓ＿６ */
     ztytyokuzenkyuuhutaisyousx6 ,         /* （中継用）直前給付対象Ｓ＿６ */
     ztytyokuzencbgakux6 ,         /* （中継用）直前ＣＢ額＿６ */
     ztytyokugotuusanhanteisx6 ,         /* （中継用）直後通算判定Ｓ＿６ */
     ztytyokugokyuuhutaisyousx6 ,         /* （中継用）直後給付対象Ｓ＿６ */
     ztytyokugocbgakux6 ,         /* （中継用）直後ＣＢ額＿６ */
     ztyyobiv12x6 ,         /* （中継用）予備項目Ｖ１２＿６ */
     ztycbkikyksyonox1 ,         /* （中継用）ＣＢ既契約証券番号＿１ */
     ztycbkikykhknsyruikbnx1 ,         /* （中継用）ＣＢ既契約保険種類区分＿１ */
     ztycbkikeiyakukeiyakuymdx1 ,         /* （中継用）ＣＢ既契約契約年月日＿１ */
     ztycbkikykkyhtisyukbnx1 ,         /* （中継用）ＣＢ既契約給付対象区分＿１ */
     ztycbkikykhntitaisyoukbnx1 ,         /* （中継用）ＣＢ既契約判定対象区分＿１ */
     ztykikeiyakucbgakux1x1 ,         /* （中継用）既契約ＣＢ額＿１＿１ */
     ztykikeiyakucbgakux2x1 ,         /* （中継用）既契約ＣＢ額＿２＿１ */
     ztycbkikykhanteitsnsx1x1 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿１＿１ */
     ztycbkikykhanteitsnsx2x1 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿２＿１ */
     ztyyobiv12x7 ,         /* （中継用）予備項目Ｖ１２＿７ */
     ztycbkikyksyonox2 ,         /* （中継用）ＣＢ既契約証券番号＿２ */
     ztycbkikykhknsyruikbnx2 ,         /* （中継用）ＣＢ既契約保険種類区分＿２ */
     ztycbkikeiyakukeiyakuymdx2 ,         /* （中継用）ＣＢ既契約契約年月日＿２ */
     ztycbkikykkyhtisyukbnx2 ,         /* （中継用）ＣＢ既契約給付対象区分＿２ */
     ztycbkikykhntitaisyoukbnx2 ,         /* （中継用）ＣＢ既契約判定対象区分＿２ */
     ztykikeiyakucbgakux1x2 ,         /* （中継用）既契約ＣＢ額＿１＿２ */
     ztykikeiyakucbgakux2x2 ,         /* （中継用）既契約ＣＢ額＿２＿２ */
     ztycbkikykhanteitsnsx1x2 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿１＿２ */
     ztycbkikykhanteitsnsx2x2 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿２＿２ */
     ztyyobiv12x8 ,         /* （中継用）予備項目Ｖ１２＿８ */
     ztycbkikyksyonox3 ,         /* （中継用）ＣＢ既契約証券番号＿３ */
     ztycbkikykhknsyruikbnx3 ,         /* （中継用）ＣＢ既契約保険種類区分＿３ */
     ztycbkikeiyakukeiyakuymdx3 ,         /* （中継用）ＣＢ既契約契約年月日＿３ */
     ztycbkikykkyhtisyukbnx3 ,         /* （中継用）ＣＢ既契約給付対象区分＿３ */
     ztycbkikykhntitaisyoukbnx3 ,         /* （中継用）ＣＢ既契約判定対象区分＿３ */
     ztykikeiyakucbgakux1x3 ,         /* （中継用）既契約ＣＢ額＿１＿３ */
     ztykikeiyakucbgakux2x3 ,         /* （中継用）既契約ＣＢ額＿２＿３ */
     ztycbkikykhanteitsnsx1x3 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿１＿３ */
     ztycbkikykhanteitsnsx2x3 ,         /* （中継用）ＣＢ既契約判定通算Ｓ＿２＿３ */
     ztyyobiv12x9 ,         /* （中継用）予備項目Ｖ１２＿９ */
     ztyhtnknhknsyrikgusdkbnx1 ,         /* （中継用）被転換保険種類記号世代区分＿１ */
     ztyhtnknmrtikgusdkbnx1 ,         /* （中継用）被転換マル定記号世代区分＿１ */
     ztyhtnknsiznmrtikgusdkbnx1 ,         /* （中継用）被転換生存マル定記号世代区分＿１ */
     ztyhtnkntignmrtikgusdkbnx1 ,         /* （中継用）被転換逓減マル定記号世代区分＿１ */
     ztyhtnknnkmrtikgusdkbnx1 ,         /* （中継用）被転換年金マル定記号世代区分＿１ */
     ztyhtnkntkstkgusdkbnx1 ,         /* （中継用）被転換特疾記号世代区分＿１ */
     ztyhtnkndi2tkstkgusdkbnx1 ,         /* （中継用）被転換第２特疾記号世代区分＿１ */
     ztyhtnknjyustkgusdkbnx1 ,         /* （中継用）被転換重疾記号世代区分＿１ */
     ztyhtnkndi2jysitkgusdkbnx1 ,         /* （中継用）被転換第２重疾記号世代区分＿１ */
     ztyhtnknkaigonkmrtisdkbnx1 ,         /* （中継用）被転換介護年金マル定世代区分＿１ */
     ztyhtnknkigtignmrtisdkbnx1 ,         /* （中継用）被転換介護逓減マル定世代区分＿１ */
     ztyhtnknkaigomrsykgusdkbnx1 ,         /* （中継用）被転換介護マル終記号世代区分＿１ */
     ztysuuriyouyobiv8x2 ,         /* （中継用）数理用予備項目Ｖ８＿２ */
     ztyhtnknhknsyrikgusdkbnx2 ,         /* （中継用）被転換保険種類記号世代区分＿２ */
     ztyhtnknmrtikgusdkbnx2 ,         /* （中継用）被転換マル定記号世代区分＿２ */
     ztyhtnknsiznmrtikgusdkbnx2 ,         /* （中継用）被転換生存マル定記号世代区分＿２ */
     ztyhtnkntignmrtikgusdkbnx2 ,         /* （中継用）被転換逓減マル定記号世代区分＿２ */
     ztyhtnknnkmrtikgusdkbnx2 ,         /* （中継用）被転換年金マル定記号世代区分＿２ */
     ztyhtnkntkstkgusdkbnx2 ,         /* （中継用）被転換特疾記号世代区分＿２ */
     ztyhtnkndi2tkstkgusdkbnx2 ,         /* （中継用）被転換第２特疾記号世代区分＿２ */
     ztyhtnknjyustkgusdkbnx2 ,         /* （中継用）被転換重疾記号世代区分＿２ */
     ztyhtnkndi2jysitkgusdkbnx2 ,         /* （中継用）被転換第２重疾記号世代区分＿２ */
     ztyhtnknkaigonkmrtisdkbnx2 ,         /* （中継用）被転換介護年金マル定世代区分＿２ */
     ztyhtnknkigtignmrtisdkbnx2 ,         /* （中継用）被転換介護逓減マル定世代区分＿２ */
     ztyhtnknkaigomrsykgusdkbnx2 ,         /* （中継用）被転換介護マル終記号世代区分＿２ */
     ztyyobiv8x5 ,         /* （中継用）予備項目Ｖ８＿５ */
     ztyhtnknhknsyrikgusdkbnx3 ,         /* （中継用）被転換保険種類記号世代区分＿３ */
     ztyhtnknmrtikgusdkbnx3 ,         /* （中継用）被転換マル定記号世代区分＿３ */
     ztyhtnknsiznmrtikgusdkbnx3 ,         /* （中継用）被転換生存マル定記号世代区分＿３ */
     ztyhtnkntignmrtikgusdkbnx3 ,         /* （中継用）被転換逓減マル定記号世代区分＿３ */
     ztyhtnknnkmrtikgusdkbnx3 ,         /* （中継用）被転換年金マル定記号世代区分＿３ */
     ztyhtnkntkstkgusdkbnx3 ,         /* （中継用）被転換特疾記号世代区分＿３ */
     ztyhtnkndi2tkstkgusdkbnx3 ,         /* （中継用）被転換第２特疾記号世代区分＿３ */
     ztyhtnknjyustkgusdkbnx3 ,         /* （中継用）被転換重疾記号世代区分＿３ */
     ztyhtnkndi2jysitkgusdkbnx3 ,         /* （中継用）被転換第２重疾記号世代区分＿３ */
     ztyhtnknkaigonkmrtisdkbnx3 ,         /* （中継用）被転換介護年金マル定世代区分＿３ */
     ztyhtnknkigtignmrtisdkbnx3 ,         /* （中継用）被転換介護逓減マル定世代区分＿３ */
     ztyhtnknkaigomrsykgusdkbnx3 ,         /* （中継用）被転換介護マル終記号世代区分＿３ */
     ztyyobiv8x6 ,         /* （中継用）予備項目Ｖ８＿６ */
     ztyhtnknhknsyrikgusdkbnx4 ,         /* （中継用）被転換保険種類記号世代区分＿４ */
     ztyhtnknmrtikgusdkbnx4 ,         /* （中継用）被転換マル定記号世代区分＿４ */
     ztyhtnknsiznmrtikgusdkbnx4 ,         /* （中継用）被転換生存マル定記号世代区分＿４ */
     ztyhtnkntignmrtikgusdkbnx4 ,         /* （中継用）被転換逓減マル定記号世代区分＿４ */
     ztyhtnknnkmrtikgusdkbnx4 ,         /* （中継用）被転換年金マル定記号世代区分＿４ */
     ztyhtnkntkstkgusdkbnx4 ,         /* （中継用）被転換特疾記号世代区分＿４ */
     ztyhtnkndi2tkstkgusdkbnx4 ,         /* （中継用）被転換第２特疾記号世代区分＿４ */
     ztyhtnknjyustkgusdkbnx4 ,         /* （中継用）被転換重疾記号世代区分＿４ */
     ztyhtnkndi2jysitkgusdkbnx4 ,         /* （中継用）被転換第２重疾記号世代区分＿４ */
     ztyhtnknkaigonkmrtisdkbnx4 ,         /* （中継用）被転換介護年金マル定世代区分＿４ */
     ztyhtnknkigtignmrtisdkbnx4 ,         /* （中継用）被転換介護逓減マル定世代区分＿４ */
     ztyhtnknkaigomrsykgusdkbnx4 ,         /* （中継用）被転換介護マル終記号世代区分＿４ */
     ztyyobiv8x7 ,         /* （中継用）予備項目Ｖ８＿７ */
     ztyhtnknhknsyrikgusdkbnx5 ,         /* （中継用）被転換保険種類記号世代区分＿５ */
     ztyhtnknmrtikgusdkbnx5 ,         /* （中継用）被転換マル定記号世代区分＿５ */
     ztyhtnknsiznmrtikgusdkbnx5 ,         /* （中継用）被転換生存マル定記号世代区分＿５ */
     ztyhtnkntignmrtikgusdkbnx5 ,         /* （中継用）被転換逓減マル定記号世代区分＿５ */
     ztyhtnknnkmrtikgusdkbnx5 ,         /* （中継用）被転換年金マル定記号世代区分＿５ */
     ztyhtnkntkstkgusdkbnx5 ,         /* （中継用）被転換特疾記号世代区分＿５ */
     ztyhtnkndi2tkstkgusdkbnx5 ,         /* （中継用）被転換第２特疾記号世代区分＿５ */
     ztyhtnknjyustkgusdkbnx5 ,         /* （中継用）被転換重疾記号世代区分＿５ */
     ztyhtnkndi2jysitkgusdkbnx5 ,         /* （中継用）被転換第２重疾記号世代区分＿５ */
     ztyhtnknkaigonkmrtisdkbnx5 ,         /* （中継用）被転換介護年金マル定世代区分＿５ */
     ztyhtnknkigtignmrtisdkbnx5 ,         /* （中継用）被転換介護逓減マル定世代区分＿５ */
     ztyhtnknkaigomrsykgusdkbnx5 ,         /* （中継用）被転換介護マル終記号世代区分＿５ */
     ztyyobiv8x8 ,         /* （中継用）予備項目Ｖ８＿８ */
     ztyhtnknhknsyrikgusdkbnx6 ,         /* （中継用）被転換保険種類記号世代区分＿６ */
     ztyhtnknmrtikgusdkbnx6 ,         /* （中継用）被転換マル定記号世代区分＿６ */
     ztyhtnknsiznmrtikgusdkbnx6 ,         /* （中継用）被転換生存マル定記号世代区分＿６ */
     ztyhtnkntignmrtikgusdkbnx6 ,         /* （中継用）被転換逓減マル定記号世代区分＿６ */
     ztyhtnknnkmrtikgusdkbnx6 ,         /* （中継用）被転換年金マル定記号世代区分＿６ */
     ztyhtnkntkstkgusdkbnx6 ,         /* （中継用）被転換特疾記号世代区分＿６ */
     ztyhtnkndi2tkstkgusdkbnx6 ,         /* （中継用）被転換第２特疾記号世代区分＿６ */
     ztyhtnknjyustkgusdkbnx6 ,         /* （中継用）被転換重疾記号世代区分＿６ */
     ztyhtnkndi2jysitkgusdkbnx6 ,         /* （中継用）被転換第２重疾記号世代区分＿６ */
     ztyhtnknkaigonkmrtisdkbnx6 ,         /* （中継用）被転換介護年金マル定世代区分＿６ */
     ztyhtnknkigtignmrtisdkbnx6 ,         /* （中継用）被転換介護逓減マル定世代区分＿６ */
     ztyhtnknkaigomrsykgusdkbnx6 ,         /* （中継用）被転換介護マル終記号世代区分＿６ */
     ztyyobiv8x9 ,         /* （中継用）予備項目Ｖ８＿９ */
     ztykaigonktkyksyuruikgu ,         /* （中継用）介護年金特約種類記号 */
     ztykaigonktkykkgusdkbn ,         /* （中継用）介護年金特約記号世代区分 */
     ztykaigonenkintokuyakukikan ,         /* （中継用）介護年金特約期間 */
     ztykaigonktkykphrkkkn ,         /* （中継用）介護年金特約Ｐ払込期間 */
     ztykaigonktkyknkgk ,         /* （中継用）介護年金特約年金額 */
     ztykaigonenkintokuyakus ,         /* （中継用）介護年金特約Ｓ */
     ztykaigonenkintokuyakup ,         /* （中継用）介護年金特約Ｐ */
     ztykaigonktkykmods ,         /* （中継用）介護年金特約修正Ｓ */
     ztykaigonktkyknkshrkkn ,         /* （中継用）介護年金特約年金支払期間 */
     ztyhtnknkaigonktkykkgux1 ,         /* （中継用）被転換介護年金特約記号＿１ */
     ztyhtnknkaigonktkykkgux2 ,         /* （中継用）被転換介護年金特約記号＿２ */
     ztyhtnknkaigonktkykkgux3 ,         /* （中継用）被転換介護年金特約記号＿３ */
     ztyhtnknkaigonktkykkgux4 ,         /* （中継用）被転換介護年金特約記号＿４ */
     ztyhtnknkaigonktkykkgux5 ,         /* （中継用）被転換介護年金特約記号＿５ */
     ztyhtnknkaigonktkykkgux6 ,         /* （中継用）被転換介護年金特約記号＿６ */
     ztyhtnknkaigonktkyksdkbnx1 ,         /* （中継用）被転換介護年金特約世代区分＿１ */
     ztyhtnknkaigonktkyksdkbnx2 ,         /* （中継用）被転換介護年金特約世代区分＿２ */
     ztyhtnknkaigonktkyksdkbnx3 ,         /* （中継用）被転換介護年金特約世代区分＿３ */
     ztyhtnknkaigonktkyksdkbnx4 ,         /* （中継用）被転換介護年金特約世代区分＿４ */
     ztyhtnknkaigonktkyksdkbnx5 ,         /* （中継用）被転換介護年金特約世代区分＿５ */
     ztyhtnknkaigonktkyksdkbnx6 ,         /* （中継用）被転換介護年金特約世代区分＿６ */
     ztysurikaigonktkykpwrbkkbn ,         /* （中継用）数理介護年金特約Ｐ割引区分 */
     ztykaigonktkykpwrbkkbn ,         /* （中継用）介護年金特約Ｐ割引区分 */
     ztykaigonktkyktnknyugukbn ,         /* （中継用）介護年金特約転換優遇区分 */
     ztyyobiv14 ,         /* （中継用）予備項目Ｖ１４ */
     ztyitjbrkignktkyksyrikgu ,         /* （中継用）一時払介護年金特約種類記号 */
     ztyitjbrkignktkyksdkbn ,         /* （中継用）一時払介護年金特約世代区分 */
     ztyitjbrkignktkykkkn ,         /* （中継用）一時払介護年金特約期間 */
     ztyitjbrkignktkyknnkngk ,         /* （中継用）一時払介護年金特約年金額 */
     ztyitjbrkignktkyks ,         /* （中継用）一時払介護年金特約Ｓ */
     ztyitjbrkignktkykp ,         /* （中継用）一時払介護年金特約Ｐ */
     ztyitjbrkignktkykspdtkbn ,         /* （中継用）一時払介護年金特約ＳＰ建区分 */
     ztyitjbrkignktkykmods ,         /* （中継用）一時払介護年金特約修正Ｓ */
     ztyitjbrkignktkykshrkkn ,         /* （中継用）一時払介護年金特約支払期間 */
     ztyyobiv8x10 ,         /* （中継用）予備項目Ｖ８＿１０ */
     ztynyuuinnissuugatakbn ,         /* （中継用）入院日数型区分 */
     ztytenkankeikanensuu ,         /* （中継用）転換経過年数 */
     ztysykkyuhtkyksyuruikgu ,         /* （中継用）初期給付特約種類記号 */
     ztysyokikyuuhutokuyakukikan ,         /* （中継用）初期給付特約期間 */
     ztysyokikyuuhutkykphrkkkn ,         /* （中継用）初期給付特約Ｐ払込期間 */
     ztysykkyuhtkykntgk ,         /* （中継用）初期給付特約日額 */
     ztysyokikyuuhutokuyakup ,         /* （中継用）初期給付特約Ｐ */
     ztysykkyuhtkykgtkbn ,         /* （中継用）初期給付特約型区分 */
     ztysyokikyuuhutkykkgusdkbn ,         /* （中継用）初期給付特約記号世代区分 */
     ztysykkyuhtkjyuryumshyutn ,         /* （中継用）初期給付特条料増標点 */
     ztysyokikyuuhutokujyoup ,         /* （中継用）初期給付特条Ｐ */
     ztysykkyuhtktbicdx1 ,         /* （中継用）初期給付特定部位コード＿１ */
     ztysykkyuhhtnpkknx1 ,         /* （中継用）初期給付不担保期間＿１ */
     ztysykkyuhtktbicdx2 ,         /* （中継用）初期給付特定部位コード＿２ */
     ztysykkyuhhtnpkknx2 ,         /* （中継用）初期給付不担保期間＿２ */
     ztysykkyuhtkykpwrbkkbn ,         /* （中継用）初期給付特約Ｐ割引区分 */
     ztyyobiv3x6 ,         /* （中継用）予備項目Ｖ３＿６ */
     ztydi2sykkyuhtkyksyrikgu ,         /* （中継用）第２初期給付特約種類記号 */
     ztydi2sykkyuhtkykkkn ,         /* （中継用）第２初期給付特約期間 */
     ztydi2sykkyuhtkykphrkkkn ,         /* （中継用）第２初期給付特約Ｐ払込期間 */
     ztydi2sykkyuhtkykntgk ,         /* （中継用）第２初期給付特約日額 */
     ztydai2syokikyuuhutokuyakup ,         /* （中継用）第２初期給付特約Ｐ */
     ztydi2sykkyuhtkykgtkbn ,         /* （中継用）第２初期給付特約型区分 */
     ztydi2sykkyuhtkykkgusdkbn ,         /* （中継用）第２初期給付特約記号世代区分 */
     ztydi2sykkyuhtkjyuryumshytn ,         /* （中継用）第２初期給付特条料増標点 */
     ztydai2syokikyuuhutokujyoup ,         /* （中継用）第２初期給付特条Ｐ */
     ztydi2sykkyuhtktbicdx1 ,         /* （中継用）第２初期給付特定部位コード＿１ */
     ztydi2sykkyuhhtnpkknx1 ,         /* （中継用）第２初期給付不担保期間＿１ */
     ztydi2sykkyuhtktbicdx2 ,         /* （中継用）第２初期給付特定部位コード＿２ */
     ztydi2sykkyuhhtnpkknx2 ,         /* （中継用）第２初期給付不担保期間＿２ */
     ztydi2sykkyuhtkykpwrbkkbn ,         /* （中継用）第２初期給付特約Ｐ割引区分 */
     ztyyobiv3x7 ,         /* （中継用）予備項目Ｖ３＿７ */
     ztydfitijibaraip ,         /* （中継用）ＤＦ一時払Ｐ */
     ztydfgoukeitenkankakaku ,         /* （中継用）ＤＦ合計転換価格 */
     ztydfuktkjivbbntnknkakaku ,         /* （中継用）ＤＦ受付時Ｖ部分転換価格 */
     ztydfuktkjipbbntnknkakaku ,         /* （中継用）ＤＦ受付時Ｐ部分転換価格 */
     ztydftnkngvbbntnknkakaku ,         /* （中継用）ＤＦ転換後Ｖ部分転換価格 */
     ztydftnkngpbbntnknkakaku ,         /* （中継用）ＤＦ転換後Ｐ部分転換価格 */
     ztyyobiv18x2 ,         /* （中継用）予備項目Ｖ１８＿２ */
     ztykaigomrtisyuruikgu ,         /* （中継用）介護マル定種類記号 */
     ztykaigomaruteikigousdkbn ,         /* （中継用）介護マル定記号世代区分 */
     ztykaigomaruteikikan ,         /* （中継用）介護マル定期間 */
     ztykaigomaruteiphrkkkn ,         /* （中継用）介護マル定Ｐ払込期間 */
     ztykaigomaruteis ,         /* （中継用）介護マル定Ｓ */
     ztykaigomaruteip ,         /* （中継用）介護マル定Ｐ */
     ztykaigomaruteisyuuseis ,         /* （中継用）介護マル定修正Ｓ */
     ztykaigomaruteimodsskgnhyj ,         /* （中継用）介護マル定修正Ｓ削減表示 */
     ztykigmrtitkjyukbn ,         /* （中継用）介護マル定特条区分 */
     ztykigmrtitkjyuskgnkkn ,         /* （中継用）介護マル定特条削減期間 */
     ztykigmrtitkjyuryumshyutn ,         /* （中継用）介護マル定特条料増標点 */
     ztykaigomaruteitokujyoup ,         /* （中継用）介護マル定特条Ｐ */
     ztyhtnknkigmrtisyrikgux1 ,         /* （中継用）被転換介護マル定種類記号＿１ */
     ztyhtnknkigmrtisyrikgux2 ,         /* （中継用）被転換介護マル定種類記号＿２ */
     ztyhtnknkigmrtisyrikgux3 ,         /* （中継用）被転換介護マル定種類記号＿３ */
     ztyhtnknkigmrtisyrikgux4 ,         /* （中継用）被転換介護マル定種類記号＿４ */
     ztyhtnknkigmrtisyrikgux5 ,         /* （中継用）被転換介護マル定種類記号＿５ */
     ztyhtnknkigmrtisyrikgux6 ,         /* （中継用）被転換介護マル定種類記号＿６ */
     ztyhtnknkaigomrtisdkbnx1 ,         /* （中継用）被転換介護マル定世代区分＿１ */
     ztyhtnknkaigomrtisdkbnx2 ,         /* （中継用）被転換介護マル定世代区分＿２ */
     ztyhtnknkaigomrtisdkbnx3 ,         /* （中継用）被転換介護マル定世代区分＿３ */
     ztyhtnknkaigomrtisdkbnx4 ,         /* （中継用）被転換介護マル定世代区分＿４ */
     ztyhtnknkaigomrtisdkbnx5 ,         /* （中継用）被転換介護マル定世代区分＿５ */
     ztyhtnknkaigomrtisdkbnx6 ,         /* （中継用）被転換介護マル定世代区分＿６ */
     ztysurkigmrtipwrbkkbn ,         /* （中継用）数理介護マル定Ｐ割引区分 */
     ztykigmrtipwrbkkbn ,         /* （中継用）介護マル定Ｐ割引区分 */
     ztykigmrtitnknyugukbn ,         /* （中継用）介護マル定転換優遇区分 */
     ztykigmrtikusnmnryoage ,         /* （中継用）介護マル定更新満了年令 */
     ztyyobiv2x7 ,         /* （中継用）予備項目Ｖ２＿７ */
     ztykaigotokuteisyuruikigou ,         /* （中継用）介護トク定種類記号 */
     ztykaigotktikgusdkbn ,         /* （中継用）介護トク定記号世代区分 */
     ztykaigotokuteikikan ,         /* （中継用）介護トク定期間 */
     ztykaigotokuteis ,         /* （中継用）介護トク定Ｓ */
     ztykaigotokuteip ,         /* （中継用）介護トク定Ｐ */
     ztykigtktisdtpdtkbn ,         /* （中継用）介護トク定Ｓ建Ｐ建区分 */
     ztykaigotokuteisyuuseis ,         /* （中継用）介護トク定修正Ｓ */
     ztykaigotktimodsskgnhyj ,         /* （中継用）介護トク定修正Ｓ削減表示 */
     ztykaigotktikusnmnryoage ,         /* （中継用）介護トク定更新満了年令 */
     ztyyobiv8x11 ,         /* （中継用）予備項目Ｖ８＿１１ */
     ztykazokuiryoutkyksyuruikgu ,         /* （中継用）家族医療特約種類記号 */
     ztykazokuiryoutokuyakukikan ,         /* （中継用）家族医療特約期間 */
     ztykazokuiryoutkykphrkkkn ,         /* （中継用）家族医療特約Ｐ払込期間 */
     ztykzkiryoutkykntgk ,         /* （中継用）家族医療特約日額 */
     ztykazokuiryoutokuyakup ,         /* （中継用）家族医療特約Ｐ */
     ztykzkiryoutkykgtkbn ,         /* （中継用）家族医療特約型区分 */
     ztykazokuiryoutkykkgusdkbn ,         /* （中継用）家族医療特約記号世代区分 */
     ztykzkiryoutktbicdx1 ,         /* （中継用）家族医療特定部位コード＿１ */
     ztykzkiryouhtnpkknx1 ,         /* （中継用）家族医療不担保期間＿１ */
     ztykzkiryoutktbicdx2 ,         /* （中継用）家族医療特定部位コード＿２ */
     ztykzkiryouhtnpkknx2 ,         /* （中継用）家族医療不担保期間＿２ */
     ztyyobiv12x10 ,         /* （中継用）予備項目Ｖ１２＿１０ */
     kousinsyaId ,         /* 更新者ＩＤ */
     kousinTime ,         /* 更新時間 */
     kousinKinou ,         /* 更新機能 */
     version           /* バージョン */
FROM ZT_Sp2RnduyuSouseiritu2Ty_Z;