CREATE TABLE JT_Sk (
     skno                                               VARCHAR     (18)                                                      NOT NULL  ,  /* 請求番号 */
     syono                                              VARCHAR     (20)                                                      NOT NULL  ,  /* 証券番号 */
     seikyuurirekino                                    NUMBER      (3)                                                       NOT NULL  ,  /* 請求履歴番号 */
     syoruiukeymd                                       VARCHAR     (8)                                                                 ,  /* 書類受付日 */
     hubikanryouymd                                     VARCHAR     (8)                                                                 ,  /* 不備完了日 */
     seikyuusyakbn                                      VARCHAR     (1)                                                                 ,  /* 請求者区分 */
     syuhiyouhi                                         VARCHAR     (1)                                                                 ,  /* 守秘要否 */
     seikyuusyanmkn                                     VARCHAR     (18)                                                                ,  /* 請求者（カナ） */
     seikyuusyanmkj                                     VARCHAR     (15)                                                                ,  /* 請求者（漢字） */
     seikyuusyaseiymd                                   VARCHAR     (8)                                                                 ,  /* 請求者生年月日 */
     seikyuusyasei                                      VARCHAR     (1)                                                                 ,  /* 請求者性別 */
     sihonninkakninkbn                                  VARCHAR     (1)                                                                 ,  /* 保険金本人確認結果区分 */
     seikyuusyatdk                                      VARCHAR     (2)                                                                 ,  /* 請求者続柄 */
     sbjishrkbn                                         VARCHAR     (1)                                                                 ,  /* 死亡時支払区分 */
     uktkyksyatdk                                       VARCHAR     (1)                                                                 ,  /* 受取人契約者続柄 */
     souhusakikbn                                       VARCHAR     (1)                                                                 ,  /* 送付先区分 */
     tsinyno                                            VARCHAR     (7)                                                                 ,  /* 通信先郵便番号 */
     tsinadr1kj                                         VARCHAR     (30)                                                                ,  /* 通信先住所１（漢字） */
     tsinadr2kj                                         VARCHAR     (30)                                                                ,  /* 通信先住所２（漢字） */
     tsinadr3kj                                         VARCHAR     (30)                                                                ,  /* 通信先住所３（漢字） */
     tsintelno                                          VARCHAR     (14)                                                                ,  /* 通信先電話番号 */
     saikennmkj                                         VARCHAR     (30)                                                                ,  /* 債権者氏名（漢字） */
     saikennyno                                         VARCHAR     (7)                                                                 ,  /* 債権者郵便番号 */
     saikenadr1kj                                       VARCHAR     (30)                                                                ,  /* 債権者住所１（漢字） */
     saikenadr2kj                                       VARCHAR     (30)                                                                ,  /* 債権者住所２（漢字） */
     saikenadr3kj                                       VARCHAR     (30)                                                                ,  /* 債権者住所３（漢字） */
     skskknnmkn                                         VARCHAR     (18)                                                                ,  /* 親権者後見人名（カナ） */
     skskknnmkj                                         VARCHAR     (15)                                                                ,  /* 親権者後見人名（漢字） */
     skskknsyubetu                                      VARCHAR     (1)                                                                 ,  /* 親権者後見人種別 */
     soukinsakikbn                                      VARCHAR     (1)                                                                 ,  /* 送金先区分 */
     inputshrhousiteikbn                                VARCHAR     (1)                                                                 ,  /* 入力用支払方法指定区分 */
     bankcd                                             VARCHAR     (4)                                                                 ,  /* 銀行コード */
     sitencd                                            VARCHAR     (3)                                                                 ,  /* 支店コード */
     yokinkbn                                           VARCHAR     (1)                                                                 ,  /* 預金種目区分 */
     kouzano                                            VARCHAR     (12)                                                                ,  /* 口座番号 */
     kzdoukbn                                           VARCHAR     (1)                                                                 ,  /* 口座名義人同一区分 */
     kzmeiginmkn                                        VARCHAR     (30)                                                                ,  /* 口座名義人氏名（カナ） */
     suketorihouhoukbn                                  VARCHAR     (1)                                                                 ,  /* 保険金受取方法区分 */
     siharaituukakbn                                    VARCHAR     (1)                                                                 ,  /* 支払通貨区分 */
     nstkhukaumukbn                                     VARCHAR     (1)                                                                 ,  /* 年金支払特約付加有無区分 */
     nkkknjyutougk                                      NUMBER      (13)                                                                ,  /* 年金基金充当金額 */
     nkkknjyutougk$                                     VARCHAR     (10)                                                                ,  /* 年金基金充当金額(通貨型) */
     sateikaksaigaikanouseikbn                          VARCHAR     (1)                                                                 ,  /* 査定回送要否確認（災害可能性）区分 */
     sateikakmeigihnkkbn                                VARCHAR     (1)                                                                 ,  /* 査定回送要否確認（名義変更査定）区分 */
     sateikakkaigaisbkbn                                VARCHAR     (1)                                                                 ,  /* 査定回送要否確認（海外死亡）区分 */
     sateikakhusyousikbn                                VARCHAR     (1)                                                                 ,  /* 査定回送要否確認（不詳の死）区分 */
     sateikakkaigaikbn                                  VARCHAR     (1)                                                                 ,  /* 査定回送要否確認（海外）区分 */
     shrdtlsyooutkbn                                    VARCHAR     (1)                                                                 ,  /* 支払明細書出力区分 */
     hassoukbn                                          VARCHAR     (1)                                                                 ,  /* 発送区分 */
     uktmnmeigibangou                                   VARCHAR     (3)                                                                 ,  /* 受取人ＭＮ名義番号 */
     kykmnmeigibangou                                   VARCHAR     (3)                                                                 ,  /* 契約者ＭＮ名義番号 */
     siinkbn                                            VARCHAR     (1)                                                                 ,  /* 死因区分 */
     misyuupjyuutouym                                   VARCHAR     (6)                                                                 ,  /* 未収保険料充当年月 */
     misyuupjyuutoukaisuuy                              NUMBER      (2)                                                                 ,  /* 未収保険料充当回数（年） */
     misyuupjyuutoukaisuum                              NUMBER      (2)                                                                 ,  /* 未収保険料充当回数（月） */
     saigaimousideumukbn                                VARCHAR     (1)                                                                 ,  /* 災害申出有無区分 */
     sindansyoryoushryouhikbn                           VARCHAR     (1)                                                                 ,  /* 診断書料支払要否区分 */
     sindansyomaisuu                                    NUMBER      (2)                                                                 ,  /* 診断書枚数 */
     sinsagendokknkbn                                   VARCHAR     (3)                                                                 ,  /* 審査限度期間区分 */
     rikoukityuutuudannissuu                            NUMBER      (3)                                                                 ,  /* 履行期中断日数 */
     tienrisokukisanymd                                 VARCHAR     (8)                                                                 ,  /* 遅延利息起算日 */
     tienrsknissuu                                      NUMBER      (5)                                                                 ,  /* 遅延利息日数 */
     kyktuukasyu                                        VARCHAR     (3)                                                                 ,  /* 契約通貨種類 */
     shrtuukasyu                                        VARCHAR     (3)                                                                 ,  /* 支払通貨種類 */
     shrkwsratekjnymd                                   VARCHAR     (8)                                                                 ,  /* 支払時為替レート基準日 */
     shrkwsrate                                         NUMBER      (7,4)                                                               ,  /* 支払時為替レート */
     zeimukwsratekjnymd                                 VARCHAR     (8)                                                                 ,  /* 税務用為替レート基準日 */
     zeimukwsrate                                       NUMBER      (7,4)                                                               ,  /* 税務用為替レート */
     gaikaknsnkwsratekjymd                              VARCHAR     (8)                                                                 ,  /* 外貨換算為替レート基準日 */
     gaikaknsnkwsrate                                   NUMBER      (7,4)                                                               ,  /* 外貨換算為替レート */
     shrgk                                              NUMBER      (13)                                                                ,  /* 支払金額 */
     shrgk$                                             VARCHAR     (10)                                                                ,  /* 支払金額(通貨型) */
     kyhkngkgoukei                                      NUMBER      (13)                                                                ,  /* 給付金額合計 */
     kyhkngkgoukei$                                     VARCHAR     (10)                                                                ,  /* 給付金額合計(通貨型) */
     hokenkngkgoukei                                    NUMBER      (13)                                                                ,  /* 保険金額合計 */
     hokenkngkgoukei$                                   VARCHAR     (10)                                                                ,  /* 保険金額合計(通貨型) */
     haitoukin                                          NUMBER      (13)                                                                ,  /* 配当金 */
     haitoukin$                                         VARCHAR     (10)                                                                ,  /* 配当金(通貨型) */
     sonotahaitoukin                                    NUMBER      (13)                                                                ,  /* その他配当金 */
     sonotahaitoukin$                                   VARCHAR     (10)                                                                ,  /* その他配当金(通貨型) */
     misyuup                                            NUMBER      (13)                                                                ,  /* 未収保険料 */
     misyuup$                                           VARCHAR     (10)                                                                ,  /* 未収保険料(通貨型) */
     mikeikap                                           NUMBER      (13)                                                                ,  /* 未経過保険料 */
     mikeikap$                                          VARCHAR     (10)                                                                ,  /* 未経過保険料(通貨型) */
     zennouseisankgk                                    NUMBER      (13)                                                                ,  /* 前納精算金額 */
     zennouseisankgk$                                   VARCHAR     (10)                                                                ,  /* 前納精算金額(通貨型) */
     azukarikingk                                       NUMBER      (13)                                                                ,  /* 預り金額 */
     azukarikingk$                                      VARCHAR     (10)                                                                ,  /* 預り金額(通貨型) */
     sonotaseisangk                                     NUMBER      (13)                                                                ,  /* その他精算額 */
     sonotaseisangk$                                    VARCHAR     (10)                                                                ,  /* その他精算額(通貨型) */
     krkgk                                              NUMBER      (13)                                                                ,  /* 仮受金額 */
     krkgk$                                             VARCHAR     (10)                                                                ,  /* 仮受金額(通貨型) */
     shrtienrsk                                         NUMBER      (13)                                                                ,  /* 支払遅延利息 */
     shrtienrsk$                                        VARCHAR     (10)                                                                ,  /* 支払遅延利息(通貨型) */
     yenshrgk                                           NUMBER      (13)                                                                ,  /* 円換算支払金額 */
     yenshrgk$                                          VARCHAR     (10)                                                                ,  /* 円換算支払金額(通貨型) */
     yenkyhgkgoukei                                     NUMBER      (13)                                                                ,  /* 円換算給付金額合計 */
     yenkyhgkgoukei$                                    VARCHAR     (10)                                                                ,  /* 円換算給付金額合計(通貨型) */
     yenhkgkgoukei                                      NUMBER      (13)                                                                ,  /* 円換算保険金額合計 */
     yenhkgkgoukei$                                     VARCHAR     (10)                                                                ,  /* 円換算保険金額合計(通貨型) */
     yenkahaitoukin                                     NUMBER      (13)                                                                ,  /* 円貨配当金 */
     yenkahaitoukin$                                    VARCHAR     (10)                                                                ,  /* 円貨配当金(通貨型) */
     yenkasonotahaitoukin                               NUMBER      (13)                                                                ,  /* 円貨その他配当金 */
     yenkasonotahaitoukin$                              VARCHAR     (10)                                                                ,  /* 円貨その他配当金(通貨型) */
     yenkamisyuup                                       NUMBER      (13)                                                                ,  /* 円貨未収保険料 */
     yenkamisyuup$                                      VARCHAR     (10)                                                                ,  /* 円貨未収保険料(通貨型) */
     yenkamikeikap                                      NUMBER      (13)                                                                ,  /* 円貨未経過保険料 */
     yenkamikeikap$                                     VARCHAR     (10)                                                                ,  /* 円貨未経過保険料(通貨型) */
     yenkazennouseisankgk                               NUMBER      (13)                                                                ,  /* 円貨前納精算金額 */
     yenkazennouseisankgk$                              VARCHAR     (10)                                                                ,  /* 円貨前納精算金額(通貨型) */
     yenkaazukarikingk                                  NUMBER      (13)                                                                ,  /* 円貨預り金額 */
     yenkaazukarikingk$                                 VARCHAR     (10)                                                                ,  /* 円貨預り金額(通貨型) */
     yenkasonotaseisangk                                NUMBER      (13)                                                                ,  /* 円貨その他精算額 */
     yenkasonotaseisangk$                               VARCHAR     (10)                                                                ,  /* 円貨その他精算額(通貨型) */
     yenkakrkgk                                         NUMBER      (13)                                                                ,  /* 円貨仮受金額 */
     yenkakrkgk$                                        VARCHAR     (10)                                                                ,  /* 円貨仮受金額(通貨型) */
     yenshrtienrsk                                      NUMBER      (13)                                                                ,  /* 円換算支払遅延利息 */
     yenshrtienrsk$                                     VARCHAR     (10)                                                                ,  /* 円換算支払遅延利息(通貨型) */
     zitkazukarikingksiteituuka                         NUMBER      (13)                                                                ,  /* 税適預り金額（指定通貨） */
     zitkazukarikingksiteituuka$                        VARCHAR     (10)                                                                ,  /* 税適預り金額（指定通貨）(通貨型) */
     zitkazukarikingkyen                                NUMBER      (13)                                                                ,  /* 税適預り金額（円貨） */
     zitkazukarikingkyen$                               VARCHAR     (10)                                                                ,  /* 税適預り金額（円貨）(通貨型) */
     gaikaknsntkgk                                      NUMBER      (13)                                                                ,  /* 外貨換算対象金額 */
     gaikaknsntkgk$                                     VARCHAR     (10)                                                                ,  /* 外貨換算対象金額(通貨型) */
     gaikaknsnkekkakgk                                  NUMBER      (13)                                                                ,  /* 外貨換算結果金額 */
     gaikaknsnkekkakgk$                                 VARCHAR     (10)                                                                ,  /* 外貨換算結果金額(通貨型) */
     yenkaknsntkgk                                      NUMBER      (13)                                                                ,  /* 円貨換算対象金額 */
     yenkaknsntkgk$                                     VARCHAR     (10)                                                                ,  /* 円貨換算対象金額(通貨型) */
     yenkaknsnkekkakgk                                  NUMBER      (13)                                                                ,  /* 円貨換算結果金額 */
     yenkaknsnkekkakgk$                                 VARCHAR     (10)                                                                ,  /* 円貨換算結果金額(通貨型) */
     misyuusyonendojikaiikoup                           NUMBER      (13)                                                                ,  /* 未収初年度次回以降Ｐ */
     misyuusyonendojikaiikoup$                          VARCHAR     (10)                                                                ,  /* 未収初年度次回以降Ｐ(通貨型) */
     misyuujinendoikoup                                 NUMBER      (13)                                                                ,  /* 未収次年度以降Ｐ */
     misyuujinendoikoup$                                VARCHAR     (10)                                                                ,  /* 未収次年度以降Ｐ(通貨型) */
     pmkouryokuhasseiymd                                VARCHAR     (8)                                                                 ,  /* Ｐ免効力発生日 */
     mikeikapjyuutouym                                  VARCHAR     (6)                                                                 ,  /* 未経過保険料充当年月 */
     mikeikapjyuutoukaisuuy                             NUMBER      (2)                                                                 ,  /* 未経過保険料充当回数（年） */
     mikeikapjyuutoukaisuum                             NUMBER      (2)                                                                 ,  /* 未経過保険料充当回数（月） */
     tokusyushrkbn                                      VARCHAR     (1)                                                                 ,  /* 特殊支払区分 */
     firstgansindankyhkbn                               VARCHAR     (1)                                                                 ,  /* 初回がん診断給付区分 */
     goukeihituyoukeihi                                 NUMBER      (13)                                                                ,  /* 合計必要経費 */
     goukeihituyoukeihi$                                VARCHAR     (10)                                                                ,  /* 合計必要経費(通貨型) */
     kykhnkkaisuu                                       NUMBER      (2)                                                                 ,  /* 契約者変更回数 */
     shrkykhtykeihi                                     NUMBER      (13)                                                                ,  /* 支払時契約者必要経費 */
     shrkykhtykeihi$                                    VARCHAR     (10)                                                                ,  /* 支払時契約者必要経費(通貨型) */
     kijitumitouraimikeikap                             NUMBER      (13)                                                                ,  /* 期日未到来未経過保険料 */
     kijitumitouraimikeikap$                            VARCHAR     (10)                                                                ,  /* 期日未到来未経過保険料(通貨型) */
     kyhknshrtyousyomisyuup                             NUMBER      (13)                                                                ,  /* 給付金支払調書未収保険料 */
     kyhknshrtyousyomisyuup$                            VARCHAR     (10)                                                                ,  /* 給付金支払調書未収保険料(通貨型) */
     kyhknshrtyousyomikeikap                            NUMBER      (13)                                                                ,  /* 給付金支払調書未経過保険料 */
     kyhknshrtyousyomikeikap$                           VARCHAR     (10)                                                                ,  /* 給付金支払調書未経過保険料(通貨型) */
     kyhknshrtysykjtmitrmikeikap                        NUMBER      (13)                                                                ,  /* 給付金支払調書期日未到来未経過保険料 */
     kyhknshrtysykjtmitrmikeikap$                       VARCHAR     (10)                                                                ,  /* 給付金支払調書期日未到来未経過保険料(通貨型) */
     vhtnaiteikakuteikbn                                VARCHAR     (1)                                                                 ,  /* （配当金情報）内定確定区分 */
     kossyoricd                                         VARCHAR     (50)                                                                ,  /* 更新処理コード */
     kossyorisscd                                       VARCHAR     (50)                                                                ,  /* 更新処理詳細コード */
     gyoumuKousinsyaId                                  VARCHAR     (15)                                                                ,  /* 業務用更新者ＩＤ */
     gyoumuKousinTime                                   VARCHAR     (17)                                                                ,  /* 業務用更新時間 */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE JT_Sk ADD CONSTRAINT PK_Sk PRIMARY KEY (
     skno                                                     , /* 請求番号 */
     syono                                                    , /* 証券番号 */
     seikyuurirekino                                            /* 請求履歴番号 */
) ;
