CREATE TABLE ZT_BikinIdouMeisaiRn (
     zrnsequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnyuukourecordlength                              NUMBER      (7)                                                       NOT NULL  ,  /* （連携用）有効レコード長 */
     zrnrdwarea                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ＲＤＷ領域 */
     zrnrecordkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）レコード区分 */
     zrnnenkinkaisigohyouji                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金開始後表示 */
     zrnnksgokurikosidhyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金開始後繰越Ｄ表示 */
     zrnkeijyouym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）計上年月 */
     zrnidojiyukbn                                      CHAR        (2)                                                       NOT NULL  ,  /* （連携用）異動事由区分 */
     zrnzougenkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）増減区分 */
     zrnidourecordkbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）異動レコード区分 */
     zrnkeijyouctrlkbn                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）計上コントロール区分 */
     zrnhenkousyoriymd                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）変更処理年月日 */
     zrnkykmfksnctr                                     NUMBER      (7)                                                       NOT NULL  ,  /* （連携用）契約ＭＦ更新ＣＴＲ */
     zrnrecordctr                                       NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）レコードＣＴＲ */
     zrnsuuriyoukouryokukaisiymd                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）数理用効力開始年月日 */
     zrndenymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）伝票日付 */
     zrnbluekeizokuhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｂｌｕｅ継続表示 */
     zrnsuuriyouyobin1x2                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１＿２ */
     zrntoukeikeijyoukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）統計計上区分 */
     zrnraysystemhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＲＡＹシステム表示 */
     zrnzenkiidouteiseikbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）前期異動訂正区分 */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrntenkangokeiyakubosyuuym                         CHAR        (6)                                                       NOT NULL  ,  /* （連携用）転換後契約募集年月 */
     zrnidoujiyuucd                                     CHAR        (3)                                                       NOT NULL  ,  /* （連携用）異動事由コード */
     zrnsyoricd                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）処理コード */
     zrnsekininteiseihyouji                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）責任訂正表示 */
     zrnsuuriyouyobin8                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ８ */
     zrnsihankibikinkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）四半期備金区分 */
     zrnsuuriyouyobin1x3                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１＿３ */
     zrndatakanrino                                     CHAR        (11)                                                      NOT NULL  ,  /* （連携用）データ管理番号 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ免区分 */
     zrnstdssytikbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出集定区分 */
     zrnstdssnskbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出診査区分 */
     zrnsotodasimanagehyouji                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出満年令表示 */
     zrnsotodasiphkbnmnoshyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ不可分見直表示 */
     zrnstdsstkjytkyuhyj                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出新特条適用表示 */
     zrnkbnkeiriyousegmentkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理種類コード */
     zrnhosyoukinoukbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保障機能区分 */
     zrndaikbn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）大区分 */
     zrntyuukbn                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）中区分 */
     zrnsyoukbn                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）小区分 */
     zrnsedaikbn                                        CHAR        (4)                                                       NOT NULL  ,  /* （連携用）世代区分 */
     zrnharaikatakbn                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払方区分 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrntksyuannaikykkbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特殊案内契約区分 */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrnsdpdkbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ建Ｐ建区分 */
     zrnryouritukbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）料率区分 */
     zrnao3tyou3sibousdatehyouji                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）青３長３死亡Ｓ建表示 */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令Ｖ２ */
     zrnkyksyanen                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約者年令 */
     zrndai2hhknnen                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２被保険者年令 */
     zrntkbthsyumnryuhyouji                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特別保障満了表示 */
     zrnsyukeiyakupwaribikikbn                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約Ｐ割引区分 */
     zrntenkanwaribikikbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）転換割引区分 */
     zrnyuuhitutnknyuguryurtkbn                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）有配当転換優遇料率区分 */
     zrnsyukeiyakup                                     NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約Ｐ */
     zrntokujyoup                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）特条Ｐ */
     zrnsiteizukisyukeiyakup                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）指定月主契約Ｐ */
     zrnkihons                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）基本Ｓ */
     zrnsibous                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）死亡Ｓ */
     zrnhenkougokihons                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）変更後基本Ｓ */
     zrnhenkougosibous                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）変更後死亡Ｓ */
     zrnhenkouymd                                       CHAR        (8)                                                       NOT NULL  ,  /* （連携用）変更年月日 */
     zrnentyoukikan                                     CHAR        (4)                                                       NOT NULL  ,  /* （連携用）延長期間 */
     zrnseizonkyuuhukinsiteimd                          CHAR        (4)                                                       NOT NULL  ,  /* （連携用）生存給付金指定月日 */
     zrnsyukeiyakusiharaikingaku                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約支払金額 */
     zrnatukaisisyatodouhukencd                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）扱支社都道府県コード */
     zrntokuyakuhukasuu                                 NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）特約付加数 */
     zrndi2hknkknikoujihisyaage                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２保険期間移行時被者年令 */
     zrnhrimnentyoumaephrkkkn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払満延長前Ｐ払込期間 */
     zrntokubetuhosyoukikan                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特別保障期間 */
     zrnkousinmanryouage                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）更新満了年令 */
     zrnknkuzusnzyrttekitkarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）健康増進乗率適用特約有表示 */
     zrnkuriagekurisagekbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）繰上げ繰下げ区分 */
     zrnhrizmjhknsyukigousdkbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払済時保険種類記号世代区分 */
     zrnkrsgjhknsyukigousdkbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）繰下げ時保険種類記号世代区分 */
     zrnsotodasisyouhinkaiteikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出商品改定区分 */
     zrnyobiv4                                          CHAR        (4)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ４ */
     zrngoukeitenkans                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計転換Ｓ */
     zrngoukeipbubuntenkans                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計Ｐ部分転換Ｓ */
     zrntenkanteikisyuruikigou                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）転換定期種類記号 */
     zrntenkanteikikigousedaikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期記号世代区分 */
     zrntnkntiksotodasikusnkbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期外出更新区分 */
     zrntnkntikstdspmenkbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期外出Ｐ免区分 */
     zrntenkanteikikigouyobi                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期記号予備 */
     zrntenkanteikikikan                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）転換定期期間 */
     zrngoukeitenkanteikis                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計転換定期Ｓ */
     zrntnknteikinkshrkkn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）転換定期年金支払期間 */
     zrntenkansiharaikingaku                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換支払金額 */
     zrntnkntikshrkngk                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換定期支払金額 */
     zrntenkankaisuu                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換回数 */
     zrngoukeitenkankakaku                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計転換価格 */
     zrntnknkhnbbnjyuturt                               NUMBER      (11,6)                                                    NOT NULL  ,  /* （連携用）転換基本部分充当率 */
     zrnwnasigoukeitenkanteikis                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｗなし合計転換定期Ｓ */
     zrntnknteikikousinmnryouage                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）転換定期更新満了年令 */
     zrnyobiv5                                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ５ */
     zrnkanyujidatakanrino                              CHAR        (11)                                                      NOT NULL  ,  /* （連携用）加入時データ管理番号 */
     zrnkanyujikykymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）加入時契約年月日 */
     zrnkanyuujihihokensyaage                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）加入時被保険者年令 */
     zrnkanyuujitenkanhyouji                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）加入時転換表示 */
     zrnhsyuikktminaosikaisu                            CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保障一括見直回数 */
     zrnsknnjynbknsisnrt                                NUMBER      (11,9)                                                    NOT NULL  ,  /* （連携用）責任準備金精算率 */
     zrntkjykbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特条区分 */
     zrnsakugenkikan                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）削減期間 */
     zrnryoumasihyouten                                 NUMBER      (5)                                                       NOT NULL  ,  /* （連携用）料増標点 */
     zrnsykyktkjyuryumsratehyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）主契約特条料増レート表示 */
     zrnsykyktkjyuryumsrate                             NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）主契約特条料増レート */
     zrndai2tokujyoukbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第２特条区分 */
     zrndai2sakugenkikan                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２削減期間 */
     zrndai2ryoumasihyouten                             NUMBER      (5)                                                       NOT NULL  ,  /* （連携用）第２料増標点 */
     zrntokuteibuijyoukenhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定部位条件表示 */
     zrntokuteibuino1                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特定部位番号１ */
     zrnhtnpkkn1                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）不担保期間１ */
     zrntokuteibuino2                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特定部位番号２ */
     zrnhtnpkkn2                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）不担保期間２ */
     zrnmhituiryuyutktbijyknhyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）無配当医療用特定部位条件表示 */
     zrnmuhaitouiryouyoutktbino1                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）無配当医療用特定部位番号１ */
     zrnmuhaitouiryouyouhtnpkkn1                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）無配当医療用不担保期間１ */
     zrnmuhaitouiryouyoutktbino2                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）無配当医療用特定部位番号２ */
     zrnmuhaitouiryouyouhtnpkkn2                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）無配当医療用不担保期間２ */
     zrnsiteizukipwarimasihyouji                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）指定月Ｐ割増表示 */
     zrnpwarimasisiteim1                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ割増指定月１ */
     zrnpwarimasisiteim2                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ割増指定月２ */
     zrnsiteimsykykpbairitu                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）指定月主契約Ｐ倍率 */
     zrnsaisyuusiteiym                                  CHAR        (6)                                                       NOT NULL  ,  /* （連携用）最終指定年月 */
     zrnsykykkitmttvkeisanym                            CHAR        (6)                                                       NOT NULL  ,  /* （連携用）主契約既積立Ｖ計算年月 */
     zrnsykykkitmttsknnjynbkngk                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約既積立責任準備金額 */
     zrndftumitatekingaku                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ積立金額 */
     zrndftumimasikin                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ積増金 */
     zrnvbubundftenkankakaku                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｖ部分ＤＦ転換価格 */
     zrndpbubundftenkankakaku                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＰ部分ＤＦ転換価格 */
     zrndftmttkngkitjbrbbn                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ積立金額一時払部分 */
     zrnhendous                                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）変動Ｓ */
     zrnhengakujigyounendomatucv                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）変額事業年度末ＣＶ */
     zrnitibuitijibarais                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）一部一時払Ｓ */
     zrnitibuitijibaraip                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）一部一時払Ｐ */
     zrnitibitjbrshrkngk                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）一部一時払支払金額 */
     zrngoukeicv                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計ＣＶ */
     zrnminasicv                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）みなしＣＶ */
     zrnloanfund                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ローンファンド */
     zrnsaiteihosyougaku                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）最低保証額 */
     zrnhngksitihsyuyusykykp                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）変額最低保証用主契約Ｐ */
     zrnhijynbrivasbujsitihsyugk                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）平準払ＶＡ死亡時最低保証金額 */
     zrnhijynbrivamnkjsitihsyugk                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）平準払ＶＡ満期時最低保証金額 */
     zrnsiinkbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）死因区分 */
     zrnmudkaimasikihons                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ミューＤ買増基本Ｓ */
     zrnkaimasiymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）買増年月日 */
     zrnkaimasikikan                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）買増期間 */
     zrnhikitugikaimasis                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）引継買増Ｓ */
     zrnmudkaimasisiharaikingaku                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ミューＤ買増支払金額 */
     zrnszoukouryokukaisiymdx1                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）Ｓ増効力開始年月日＿１ */
     zrnszouhokensyuruikigoux1                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増保険種類記号＿１ */
     zrnszoukigousedaikbnx1                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ増記号世代区分＿１ */
     zrnszoukikanx1                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増期間＿１ */
     zrnszouhihokensyaagex1                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増被保険者年令＿１ */
     zrnszoudai2hihknsyaagex1                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増第２被保険者年令＿１ */
     zrnzoukasx1                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）増加Ｓ＿１ */
     zrnzennendozoukasx1                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）前年度増加Ｓ＿１ */
     zrnszousiharaikingakux1                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｓ増支払金額＿１ */
     zrnszoukouryokukaisiymdx2                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）Ｓ増効力開始年月日＿２ */
     zrnszouhokensyuruikigoux2                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増保険種類記号＿２ */
     zrnszoukigousedaikbnx2                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ増記号世代区分＿２ */
     zrnszoukikanx2                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増期間＿２ */
     zrnszouhihokensyaagex2                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増被保険者年令＿２ */
     zrnszoudai2hihknsyaagex2                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｓ増第２被保険者年令＿２ */
     zrnzoukasx2                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）増加Ｓ＿２ */
     zrnzennendozoukasx2                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）前年度増加Ｓ＿２ */
     zrnszousiharaikingakux2                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｓ増支払金額＿２ */
     zrnsuuriyouyobin1x5                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１＿５ */
     zrnsuuriyouyobin1x6                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１＿６ */
     zrnhrimngkizktkykpmenhyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払満後継続特約Ｐ免表示 */
     zrnmisyuustartym                                   CHAR        (6)                                                       NOT NULL  ,  /* （連携用）未収開始年月 */
     zrnmisyuukaisuu                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）未収回数 */
     zrnitjbrtkykkousnuktkarhyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）一時払特約更新受付有表示 */
     zrngyousekihyoujis                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）業績表示Ｓ */
     zrnsykykgyusekihyjs                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約業績表示Ｓ */
     zrntenkangyousekihyoujis                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換業績表示Ｓ */
     zrntnknteikigyousekihyjs                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換定期業績表示Ｓ */
     zrntnkndpbbngyuskhyjs                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換ＤＰ部分業績表示Ｓ */
     zrnkykjyoutai                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約状態 */
     zrnpmenhukakbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免付加区分 */
     zrnkousinkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新区分 */
     zrnmankiyoteikbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）満期予定区分 */
     zrnsykyktikmnkyoteikbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）主契約定期満期予定区分 */
     zrntnknsykykkhnmnkytikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換主契約基本満期予定区分 */
     zrntnknsykyktikmnkytikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換主契約定期満期予定区分 */
     zrntenkanteikimankiyoteikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期満期予定区分 */
     zrnszoumankiyoteikbnx1                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ増満期予定区分＿１ */
     zrnszoumankiyoteikbnx2                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ増満期予定区分＿２ */
     zrnvestingmankiyoteikbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ベスティング満期予定区分 */
     zrnvkeisanhyouji                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｖ計算表示 */
     zrntoukisinkeiyakuhyouji                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）当期新契約表示 */
     zrnsykykhokenhoutekiyouhyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）主契約保険法適用表示 */
     zrntokuteijyoutaihushrhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定状態不支払表示 */
     zrnytirrthndsysnmnskaisuu                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）予定利率変動終身見直回数 */
     zrnsuuriyouyobin3                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ３ */
     zrnsuuriyouyobin11                                 CHAR        (11)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１１ */
     zrnwnasigoukeitenkankakaku                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｗなし合計転換価格 */
     zrnyobin11                                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１ */
     zrnyobin11x2                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２ */
     zrnyobin11x3                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３ */
     zrntukibaraikansantokujyoup                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）月払換算特条Ｐ */
     zrntnkngkykkssnkijyuym                             CHAR        (6)                                                       NOT NULL  ,  /* （連携用）転換後契約決算計上年月 */
     zrnsaiteihosyouhyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）最低保証表示 */
     zrnsuuriyouyobin8x2                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ８＿２ */
     zrnsuuriyouyobin14                                 CHAR        (14)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１４ */
     zrnhrimngtkykphrkkaisuukbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払満後特約Ｐ払込回数区分 */
     zrnhrimngtkykphrkkirkbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払満後特約Ｐ払込経路区分 */
     zrnhrimngtkykpryurtkbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払満後特約Ｐ料率区分 */
     zrnyobiv13                                         CHAR        (13)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１３ */
     zrnidoujisaiteihosyoukngk                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）異動時最低保証金額 */
     zrnidoujisaiteihosyoucost                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）異動時最低保証コスト */
     zrnsinhokenfundtumitatekin                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）新保険ファンド積立金 */
     zrnmsyuptusshkgkaiykhnrikn                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）未収Ｐ等差引後解約返戻金 */
     zrnrrthndugtnkgetumatuv                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動型年金月末Ｖ */
     zrnrrthndnksaiteihosyonkgns                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動年金最低保証年金原資 */
     zrnrrthendougatanksibous                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動型年金死亡Ｓ */
     zrnalmyousohutomeisyoukbn                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）ＡＬＭ用ソフト名称区分 */
     zrnsnkyksoftmeisyoukbn                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）新契約ソフト名称区分 */
     zrnsoftmeisyoukbn                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）ソフト名称区分 */
     zrnkykjitokujyouarihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約時特条有表示 */
     zrnbnkttnknkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分割転換区分 */
     zrntenkanminaosikbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換見直区分 */
     zrnsoujikeitenkankbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）相似形転換区分 */
     zrnnenkinkaisinendo                                CHAR        (4)                                                       NOT NULL  ,  /* （連携用）年金開始年度 */
     zrnnenkingatakbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金型区分 */
     zrnnknshry                                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）年金支払期間 */
     zrnheiyoubaraikeiyakukbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）併用払契約区分 */
     zrnnenkinmaruteihukakbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金マル定付加区分 */
     zrnsinseizonmrtiarihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新生存マル定有表示 */
     zrnsnkykyouibokijyukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約用異募計上区分 */
     zrntokusitujyuusitusetkbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特疾重疾セット区分 */
     zrnsiktsyuknbyugnhsyunshyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）生活習慣病がん保障無表示 */
     zrnpmensugugtganhsyunshyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免総合型がん保障無表示 */
     zrntkykgyousekihyjszerohyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約業績表示Ｓゼロ表示 */
     zrnsuuriyouyobin7                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ７ */
     zrnsyussaikeitaikbn                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）出再形態区分 */
     zrnyobiv6                                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ６ */
     zrnbosyuukeitaikbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）募集形態区分 */
     zrnaatukaisosikicd                                 CHAR        (7)                                                       NOT NULL  ,  /* （連携用）Ａ扱者組織コード */
     zrnaatukaikojincd                                  CHAR        (6)                                                       NOT NULL  ,  /* （連携用）Ａ扱者個人コード */
     zrnbsydrtencd                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）募集代理店コード */
     zrncifcd                                           CHAR        (15)                                                      NOT NULL  ,  /* （連携用）ＣＩＦコード */
     zrnsuuriyouyobiv8                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｖ８ */
     zrnsinsakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）診査区分 */
     zrndai2hihokensyasinsakbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第２被保険者診査区分 */
     zrntoukeiyousinsakbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）統計用診査区分 */
     zrndai2toukeiyousinsakbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２統計用診査区分 */
     zrnketteikijyunkanwakbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）決定基準緩和区分 */
     zrnkihonsibouhyoukbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）基本死亡表区分 */
     zrnteikisibouhyoukbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）定期死亡表区分 */
     zrnsonotasibouhyoukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）その他死亡表区分 */
     zrnmrarihyj                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＭＲ有表示 */
     zrnsentakujyouhouarihyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）選択情報有表示 */
     zrndugktnknsntkhuhukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）同額転換選択方法区分 */
     zrngengakutenkankykhyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）減額転換契約表示 */
     zrnsykgycd                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）職業コード */
     zrnjidoukousinkykkanyuuymd                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）自動更新契約加入年月日 */
     zrnsaikohtnknkykkykymd                             CHAR        (8)                                                       NOT NULL  ,  /* （連携用）最古被転換契約契約年月日 */
     zrnkousinmaesykyksburtkbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新前主契約死亡率区分 */
     zrnhjnkykhyj                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）法人契約表示 */
     zrnanniskcd                                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）案内先コード */
     zrnhjncd                                           CHAR        (9)                                                       NOT NULL  ,  /* （連携用）法人コード */
     zrnhjnjigyosyocd                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）法人事業所コード */
     zrnsaihokenno                                      CHAR        (5)                                                       NOT NULL  ,  /* （連携用）再保険番号 */
     zrndakuhikettikekkacd                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定結果コード */
     zrndai2dakuhiketteikekkacd                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２諾否決定結果コード */
     zrnpmenkbnv2                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ免区分Ｖ２ */
     zrnsiboukyuuhukin                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）死亡給付金 */
     zrnjyudthumeharaitkykhkhyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）重度痴呆前払特約付加表示 */
     zrnhaitoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）配当区分 */
     zrnhhknnentysihyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者年令調整表示 */
     zrndai2hhknnentysihyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第２被保険者年令調整表示 */
     zrnkyksyaagetyouseihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者年令調整表示 */
     zrnkituenkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）喫煙区分 */
     zrnkituenhonsuu                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）喫煙本数 */
     zrnmusentakukeiyakukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）無選択契約区分 */
     zrnyobiv6x2                                        CHAR        (6)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ６＿２ */
     zrnlivingneedstkykarihyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リビングニーズ特約有表示 */
     zrnlivingneedssiharaihyouji                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リビングニーズ支払表示 */
     zrnlnseikyuuymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）ＬＮ請求年月日 */
     zrnlnshrgenincd                                    CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ＬＮ支払原因コード */
     zrndakuhikettisyacd                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定者コード */
     zrndai2dakuhiketteisyacd                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）第２諾否決定者コード */
     zrngansapotokuyakuarihyouji                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）がんサポ特約有表示 */
     zrngnspshrhyj                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）がんサポ支払表示 */
     zrngansaposeikyuuymd                               CHAR        (8)                                                       NOT NULL  ,  /* （連携用）がんサポ請求年月日 */
     zrngnspshrgenincd                                  CHAR        (4)                                                       NOT NULL  ,  /* （連携用）がんサポ支払原因コード */
     zrnyobiv3x2                                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ３＿２ */
     zrntargetmokuhyouritu                              CHAR        (3)                                                       NOT NULL  ,  /* （連携用）ターゲット目標率 */
     zrnautoswitchmokuhyouritu                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）オートスイッチ目標率 */
     zrntumitatekinitenarihyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）積立金移転有表示 */
     zrntumitatekinitenkaisuu                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）積立金移転回数 */
     zrndatakanrino2                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号２ */
     zrndatakanrino3                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号３ */
     zrnknkuzusnzyrttekinendo                           CHAR        (4)                                                       NOT NULL  ,  /* （連携用）健康増進乗率適用年度 */
     zrnknkuzusnzyrt                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率 */
     zrnknkuzusnzyrtx2                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率＿２ */
     zrnknkuzusnzyrtx3                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率＿３ */
     zrnsinkeiyakujiknkuzusnzyrt                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）新契約時健康増進乗率 */
     zrntenkanjiknkuzusnzyrt                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）転換時健康増進乗率 */
     zrnsinkeiyakujivithkhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約時Ｖｉｔ保険表示 */
     zrnkykjivithukusuukykhyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約時Ｖｉｔ複数契約表示 */
     zrnsuuriyouyobin9x2                                CHAR        (9)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ９＿２ */
     zrnpwrbksidhitekiyouhyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険料割引制度非適用表示 */
     zrnsuuriyouyobin9                                  CHAR        (9)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ９ */
     zrnsuuriyouyobin10x7                               CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０＿７ */
     zrnsuuriyouyobin10x8                               CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０＿８ */
     zrnsuuriyouyobin10x9                               CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０＿９ */
     zrntumitatekinitenbubun                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）積立金移転部分 */
     zrnsagakusknnjynbknzndk                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）差額責任準備金残高 */
     zrnyobin11x5                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿５ */
     zrnyobin11x6                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿６ */
     zrnyobin11x7                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿７ */
     zrnyobin11x8                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿８ */
     zrnyobin11x9                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿９ */
     zrnyobin11x10                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１０ */
     zrnyobin11x11                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１１ */
     zrnyobin11x12                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１２ */
     zrnyobin11x13                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１３ */
     zrnyobin11x14                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１４ */
     zrnyobin11x15                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１５ */
     zrnyobin11x16                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１６ */
     zrnyobin11x17                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿１７ */
     zrnzyrthntiyustatuskbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分 */
     zrnzyrthntiyustatuskbnx2                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿２ */
     zrnzyrthntiyustatuskbnx3                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿３ */
     zrnzyrthntiyustatuskbnx4                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿４ */
     zrnzyrthntiyustatuskbnx5                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿５ */
     zrnyobiv10                                         CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０ */
     zrnyobiv15x2                                       CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５＿２ */
     zrnyobiv15x3                                       CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５＿３ */
     zrnyobiv15x4                                       CHAR        (15)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１５＿４ */
     zrngaikakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外貨区分 */
     zrnkawaserate1                                     NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）為替レート１ */
     zrnkawaseratetekiyouymd1                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）為替レート適用年月日１ */
     zrnkawaserate2                                     NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）為替レート２ */
     zrnkawaseratetekiyouymd2                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）為替レート適用年月日２ */
     zrnkykjikawaserate                                 NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）契約時為替レート */
     zrnkykjikawaseratetkyuymd                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約時為替レート適用年月日 */
     zrnmvatyouseigow                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnkaiyakukoujyoritu                               NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）解約控除率 */
     zrnrendouritu                                      NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）連動率 */
     zrnsrkaiyakusjkkktyouseirrt                        NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）数理用解約時市場価格調整用利率 */
     zrnsrkyksjkkktyouseiriritu                         NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）数理用契約時市場価格調整用利率 */
     zrnmvakeisankijyunymd                              CHAR        (8)                                                       NOT NULL  ,  /* （連携用）ＭＶＡ計算基準年月日 */
     zrnmvatyouseikou                                   NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）ＭＶＡ調整項 */
     zrnenkdtsbujsitihsyukngk                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円貨建死亡時最低保証金額 */
     zrnenkdtsbujsitihsyucost                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円貨建死亡時最低保証コスト */
     zrnenkdtsbujsitihsyuarihyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）円貨建死亡時最低保証あり表示 */
     zrnkeiyakujiyoteiriritu                            NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）契約時予定利率 */
     zrntumitateriritu                                  NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）積立利率 */
     zrnkaigomaebaraitkykarihyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護前払特約あり表示 */
     zrnsibouhyoukbn                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）死亡表区分 */
     zrnnyuukintuukakbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）入金通貨区分 */
     zrnsiharaituukakbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払通貨区分 */
     zrnwyendttargetmokuhyouritu                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）円建Ｗターゲット目標率 */
     zrnsisuurendourate                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）指数連動部分割合 */
     zrnsisuukbn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）指数区分 */
     zrnteirituikouhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）定率移行表示 */
     zrnsuuriyouyobin2x3                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ２＿３ */
     zrnsuuriyouyobin10x11                              CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０＿１１ */
     zrntmttknzoukaritujygn                             NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）積立金増加率上限 */
     zrnsetteibairitu                                   NUMBER      (3,2)                                                     NOT NULL  ,  /* （連携用）設定倍率 */
     zrntykzenoutouymdsisuu                             NUMBER      (10,5)                                                    NOT NULL  ,  /* （連携用）直前応当日指数 */
     zrnkimatusisuu                                     NUMBER      (10,5)                                                    NOT NULL  ,  /* （連携用）期末指数 */
     zrnyobiv3                                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ３ */
     zrnyenkadatekihons                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円貨建基本Ｓ */
     zrnsitihsyumegkdtsibous                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）最低保証前外貨建死亡Ｓ */
     zrnenkdtssrentumitatekin                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円貨建指数連動部分積立金 */
     zrnsisuurentumitatekin                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）指数連動部分積立金 */
     zrnnksjitirttumitatekin                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）年金開始時定率部分積立金 */
     zrnkimatutirttumitatekin                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）期末定率部分積立金 */
     zrngaikadatejyuutoup                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ */
     zrnyendttargetkijyunkingaku                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円建ターゲット基準金額 */
     zrnyobiv7                                          CHAR        (7)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ７ */
     zrnsitivkisnyukykjikwsrate                         NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）最低Ｖ計算用契約時為替レート */
     zrnsisuurentyokugotmttkn                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）指数連動部分直後積立金 */
     zrnyoteiririturironbase                            NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率（理論ベース） */
     zrnyoteiriritujtnyknbase                           NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率（実入金ベース） */
     zrnkihrkmpjtnyknbase                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）既払込Ｐ（実入金ベース） */
     zrnsyuptumitatekin                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約保険料積立金 */
     zrnsyuptumitatekingsc                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約保険料積立金（月初） */
     zrngaikadatenkgns                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建年金原資 */
     zrnjikaipjyuutouym2                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回Ｐ充当年月２ */
     zrnsuuriyobin9                                     NUMBER      (9)                                                       NOT NULL  ,  /* （連携用）数理予備項目Ｎ９ */
     zrngessitumitatekin                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）月始積立金 */
     zrngaikadatetougetujuutoup                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建当月充当Ｐ */
     zrnkihrkmpmsukisymbase                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）既払込Ｐ（未収開始月ベース） */
     zrnkeisanhanteiyoutmttkn                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）計算判定用積立金 */
     zrngtmtv                                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）月末Ｖ */
     zrnzettaisibouritu                                 NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）絶対死亡率 */
     zrnsoutaisibouritu                                 NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）相対死亡率 */
     zrnsoutaikaiyakuritu                               NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）相対解約率 */
     zrnvhireilritu2                                    NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）Ｖ比例Ｌ率２ */
     zrnphireialpha                                     NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）Ｐ比例α */
     zrnphireibeta                                      NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）Ｐ比例β */
     zrnphireiganma                                     NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）Ｐ比例γ */
     zrnphireilwrbkritu                                 NUMBER      (13,11)                                                   NOT NULL  ,  /* （連携用）Ｐ比例Ｌ割引率 */
     zrnyoteiriritumsukisymbase                         NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率（未収開始月ベース） */
     zrnrrthnduhknvkisovkisnyu1                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用１ */
     zrnrrthnduhknvkisovkisnyu2                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用２ */
     zrnrrthnduhknvkisovkisnyu3                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用３ */
     zrnrrthnduhknvkisovkisnyu4                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用４ */
     zrnrrthnduhknvkiso                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ */
     zrntumitatekin                                     NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）積立金 */
     zrnkiharaikomip                                    NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）既払込Ｐ */
     zrngaikadatesyukeiyakup                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建主契約Ｐ */
     zrnkykkjmmvatyouseigow                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）解約控除前ＭＶＡ調整後Ｗ */
     zrnyobin11x39                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３９ */
     zrnyobin11x41                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４１ */
     zrnyobin11x42                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４２ */
     zrnyobin11x43                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４３ */
     zrnyobin11x44                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４４ */
     zrnyobin11x45                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿４５ */
     zrnsuuriyouyobin15x3                               CHAR        (15)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１５＿３ */
     zrnsuuriyouyobin15x4                               CHAR        (15)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１５＿４ */
     zrnsuuriyouyobin15x5                               CHAR        (15)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１５＿５ */
     zrnsuuriyouyobin15x6                               CHAR        (15)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１５＿６ */
     zrnyobiv14                                         CHAR        (14)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１４ */
     zrnkyksyhhknsydouituhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者被保険者同一表示 */
     zrnkyksyaskinmeino                                 CHAR        (10)                                                      NOT NULL  ,  /* （連携用）契約者索引名番号 */
     zrngoukeikihons                                    NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計基本Ｓ */
     zrngoukeigyousekihyjsibous                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計業績表示死亡Ｓ */
     zrnalmyousibous                                    NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＡＬＭ用死亡Ｓ */
     zrnharaikomip                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）払込Ｐ */
     zrnsiteizukiharaikomip                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）指定月払込Ｐ */
     zrnsaisyuusiteimhrkp                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）最終指定月払込Ｐ */
     zrngoukeinenbaraikansanp                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計年払換算Ｐ */
     zrngyousekihyoujisrank                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）業績表示Ｓランク */
     zrnteikibairitu                                    NUMBER      (5,1)                                                     NOT NULL  ,  /* （連携用）定期倍率 */
     zrntenkangodatakanrino                             CHAR        (11)                                                      NOT NULL  ,  /* （連携用）転換後データ管理番号 */
     zrnaitekykdatakanrino1                             CHAR        (11)                                                      NOT NULL  ,  /* （連携用）相手契約データ管理番号１ */
     zrnaitekykdatakanrino2                             CHAR        (11)                                                      NOT NULL  ,  /* （連携用）相手契約データ管理番号２ */
     zrntnknsyokaipcashlesshyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換初回Ｐキャッシュレス表示 */
     zrnsyokaipannaikbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）初回Ｐ案内区分 */
     zrnzennoukaisiymd                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前納開始年月日 */
     zrnzennoukikan                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）前納期間 */
     zrnseizonkyuuhukinsiteiy                           CHAR        (4)                                                       NOT NULL  ,  /* （連携用）生存給付金指定年 */
     zrnalmyouseizonkyhknsiteimd                        CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ＡＬＭ用生存給付金指定月日 */
     zrnjikaipjyuutouym                                 CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回Ｐ充当年月 */
     zrnkykjiqpackhyj                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約時Ｑパック表示 */
     zrnhktgtikkikkkn3x1                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間３＿１ */
     zrnhktgtikkikkkn3x2                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間３＿２ */
     zrnhktgtikkikkkn3x3                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間３＿３ */
     zrnhktgtikkikkkn3x4                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間３＿４ */
     zrnkappadkeisankbnx1                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カッパーＤ計算区分＿１ */
     zrnkappadkeisankbnx2                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カッパーＤ計算区分＿２ */
     zrnkappadkeisankbnx3                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カッパーＤ計算区分＿３ */
     zrnkappadkeisankbnx4                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カッパーＤ計算区分＿４ */
     zrnsuuriyouyobin2                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ２ */
     zrnyobiv6x3                                        CHAR        (6)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ６＿３ */
     zrnkimatuvyoutumimasikin                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）期末Ｖ用積増金 */
     zrnkmtvyusnhknfundtmttkin                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）期末Ｖ用新保険ファンド積立金 */
     zrngoukeinenkansanp3x1                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計年換算Ｐ３＿１ */
     zrngoukeinenkansanp3x2                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計年換算Ｐ３＿２ */
     zrngoukeinenkansanp3x3                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計年換算Ｐ３＿３ */
     zrngoukeinenkansanp3x4                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計年換算Ｐ３＿４ */
     zrnkmtvyuhijynbritmttkin                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）期末Ｖ用平準払積立金 */
     zrnkimatuvyouitjbrtmttkin                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）期末Ｖ用一時払積立金 */
     zrnyobin11x26                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２６ */
     zrnyobin11x27                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２７ */
     zrnyobin11x28                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２８ */
     zrnyobin11x29                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿２９ */
     zrnyobin11x30                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３０ */
     zrnyobin11x31                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３１ */
     zrnyobin11x32                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３２ */
     zrnyobin11x33                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３３ */
     zrnhaitouyouloadingkijyuns                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）配当用ローディング基準Ｓ */
     zrntouduketorihouhoukbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）当Ｄ受取方法区分 */
     zrntumitated                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）積立Ｄ */
     zrnkariwariated                                    NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）仮割当Ｄ */
     zrntyokuzensiharaikijitu                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）直前支払期日 */
     zrntyokuzentuusanhanteis                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）直前通算判定Ｓ */
     zrntyokugosiharaikijitu                            CHAR        (8)                                                       NOT NULL  ,  /* （連携用）直後支払期日 */
     zrntyokugotuusanhanteis                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）直後通算判定Ｓ */
     zrntyokugokyuuhutaisyous                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）直後給付対象Ｓ */
     zrntyokugocbkingaku                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）直後ＣＢ金額 */
     zrnsyokaisiharaikijitu                             CHAR        (8)                                                       NOT NULL  ,  /* （連携用）初回支払期日 */
     zrnsyokaituusanhanteis                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）初回通算判定Ｓ */
     zrncbnayosetuusanhanteis                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＣＢ名寄せ通算判定Ｓ */
     zrnhitenkankeiyakusuu                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被転換契約数 */
     zrngoukeipbubuntenkanteikis                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）合計Ｐ部分転換定期Ｓ */
     zrnsaidaihktgtikkikkkn                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）最大引継定期経過期間 */
     zrnsisyutnknhktgkujygk                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）最終転換引継控除額 */
     zrnyobin11x34                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３４ */
     zrnhtnknkykkykymdx1                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被転換契約契約年月日＿１ */
     zrntnkntkbtdkisnyusx1                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換特別Ｄ計算用Ｓ＿１ */
     zrntnknkaiykkujytksux1                             CHAR        (3)                                                       NOT NULL  ,  /* （連携用）転換解約控除月数＿１ */
     zrntnknkaiykkujygkx1                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換解約控除額＿１ */
     zrntenkanteikihyoujix1                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期表示＿１ */
     zrnhtnknkyknenknsnpx1                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）被転換契約年換算Ｐ＿１ */
     zrnhktgtikkikkknx1                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間＿１ */
     zrnhtnknkykkykymdx2                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被転換契約契約年月日＿２ */
     zrntnkntkbtdkisnyusx2                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換特別Ｄ計算用Ｓ＿２ */
     zrntnknkaiykkujytksux2                             CHAR        (3)                                                       NOT NULL  ,  /* （連携用）転換解約控除月数＿２ */
     zrntnknkaiykkujygkx2                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換解約控除額＿２ */
     zrntenkanteikihyoujix2                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期表示＿２ */
     zrnhtnknkyknenknsnpx2                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）被転換契約年換算Ｐ＿２ */
     zrnhktgtikkikkknx2                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間＿２ */
     zrnhtnknkykkykymdx3                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被転換契約契約年月日＿３ */
     zrntnkntkbtdkisnyusx3                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換特別Ｄ計算用Ｓ＿３ */
     zrntnknkaiykkujytksux3                             CHAR        (3)                                                       NOT NULL  ,  /* （連携用）転換解約控除月数＿３ */
     zrntnknkaiykkujygkx3                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換解約控除額＿３ */
     zrntenkanteikihyoujix3                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期表示＿３ */
     zrnhtnknkyknenknsnpx3                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）被転換契約年換算Ｐ＿３ */
     zrnhktgtikkikkknx3                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間＿３ */
     zrnhtnknkykkykymdx4                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被転換契約契約年月日＿４ */
     zrntnkntkbtdkisnyusx4                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換特別Ｄ計算用Ｓ＿４ */
     zrntnknkaiykkujytksux4                             CHAR        (3)                                                       NOT NULL  ,  /* （連携用）転換解約控除月数＿４ */
     zrntnknkaiykkujygkx4                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）転換解約控除額＿４ */
     zrntenkanteikihyoujix4                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換定期表示＿４ */
     zrnhtnknkyknenknsnpx4                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）被転換契約年換算Ｐ＿４ */
     zrnhktgtikkikkknx4                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）引継定期経過期間＿４ */
     zrnsknjyututkykkykkbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）資金充当特約契約区分 */
     zrnswingminyuuphrkekngk                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）スイング未入Ｐ振替金額 */
     zrnswingminyuuphrkejyutuym                         CHAR        (6)                                                       NOT NULL  ,  /* （連携用）スイング未入Ｐ振替充当年月 */
     zrndftounendoitijitounyuup                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ当年度一時投入Ｐ */
     zrndfkaiyakukujyhktggk                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ解約控除引継額 */
     zrnkaiyakukoujyotukisuu                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）解約控除月数 */
     zrndfkaiyakuhenreikin                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＤＦ解約返戻金 */
     zrnsyuuseis                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）修正Ｓ */
     zrnaatukaisyakeisyousisyacd                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）Ａ扱者継承支社コード */
     zrnaatukaisyazaisekihyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ａ扱者在籍表示 */
     zrnaatukaisyabosyuujiage                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ａ扱者募集時年令 */
     zrnaatukaisyabsyjisikakucd                         CHAR        (5)                                                       NOT NULL  ,  /* （連携用）Ａ扱者募集時資格コード */
     zrnaatukaisyasikakucd                              CHAR        (5)                                                       NOT NULL  ,  /* （連携用）Ａ扱者資格コード */
     zrnokyksmkuztrhkkitikbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）お客様口座取引形態区分 */
     zrnhoyuusisyacd                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）保有支社コード */
     zrnsyokansisyacd                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）所管支社コード */
     zrntantousyakbn                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）担当者区分 */
     zrntantousyakbnnew                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）担当者区分（新） */
     zrnclubsumiseikbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）クラブスミセイ区分 */
     zrnfollowtantousyakbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）フォロー担当者区分 */
     zrntantousyajyoutaikbn                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）担当者状態区分 */
     zrnkihonyoteii                                     CHAR        (4)                                                       NOT NULL  ,  /* （連携用）基本予定ｉ */
     zrnteikiyoteii                                     CHAR        (4)                                                       NOT NULL  ,  /* （連携用）定期予定ｉ */
     zrnsonotayoteii                                    CHAR        (4)                                                       NOT NULL  ,  /* （連携用）その他予定ｉ */
     zrnitijibaraikihonyoteii                           CHAR        (4)                                                       NOT NULL  ,  /* （連携用）一時払基本予定ｉ */
     zrnitijibaraiteikiyoteii                           CHAR        (4)                                                       NOT NULL  ,  /* （連携用）一時払定期予定ｉ */
     zrnitijibaraisonotayoteii                          CHAR        (4)                                                       NOT NULL  ,  /* （連携用）一時払その他予定ｉ */
     zrntenkankihonyoteii                               CHAR        (4)                                                       NOT NULL  ,  /* （連携用）転換基本予定ｉ */
     zrntenkanteikiyoteii                               CHAR        (4)                                                       NOT NULL  ,  /* （連携用）転換定期予定ｉ */
     zrnszouyoteii                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）Ｓ増予定ｉ */
     zrnvestingyoteii                                   CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ベスティング予定ｉ */
     zrnsippeitokuyakuyoteii                            CHAR        (4)                                                       NOT NULL  ,  /* （連携用）疾病特約予定ｉ */
     zrnseijinbyoutokuyakuyoteii                        CHAR        (4)                                                       NOT NULL  ,  /* （連携用）成人病特約予定ｉ */
     zrnjyoseitokuyakuyoteii                            CHAR        (4)                                                       NOT NULL  ,  /* （連携用）女性特約予定ｉ */
     zrntuuintokuyakuyoteii                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）通院特約予定ｉ */
     zrnsaiteihosyoui                                   CHAR        (4)                                                       NOT NULL  ,  /* （連携用）最低保証ｉ */
     zrnvkisoitjbrkhnyoteii                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）Ｖ基礎一時払基本予定ｉ */
     zrnvkisorrtzeroikahyouji                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｖ基礎利率ゼロ％以下表示 */
     zrnsuuriyouyobin3x2                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ３＿２ */
     zrnhoyuusisyacd2                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）保有支社コード２ */
     zrndftujyukujykisnkisiym                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）ＤＦ通常控除計算期始年月 */
     zrntikikktbrijyututksu                             CHAR        (2)                                                       NOT NULL  ,  /* （連携用）定期一括払充当月数 */
     zrnsyunyumrtikykjtigngtkbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）収入マル定契約時逓減型区分 */
     zrnsuuriyouyobin2x2                                CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ２＿２ */
     zrnyobiv10x14                                      CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０＿１４ */
     zrnkappadhktgkujygkx1                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）カッパーＤ引継控除額＿１ */
     zrnkappadhktgkujygkx2                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）カッパーＤ引継控除額＿２ */
     zrnkappadhktgkujygkx3                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）カッパーＤ引継控除額＿３ */
     zrnkappadhktgkujygkx4                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）カッパーＤ引継控除額＿４ */
     zrntrkzsgkaiykkjynstmtkzndk                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）取崩後解約控除なし積立金残高 */
     zrnpmenkouryokuhasseiymd                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）Ｐ免効力発生年月日 */
     zrnsuuriyouyobin5                                  CHAR        (5)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ５ */
     zrnsuuriyouyobin13                                 CHAR        (13)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１３ */
     zrnyobin11x35                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３５ */
     zrnyobin11x36                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３６ */
     zrnyobin11x37                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）予備項目Ｎ１１＿３７ */
     zrntokuyakukoumokuv200                             CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００ */
     zrntokuyakukoumokuv200x2                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２ */
     zrntokuyakukoumokuv200x3                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３ */
     zrntokuyakukoumokuv200x4                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿４ */
     zrntokuyakukoumokuv200x5                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿５ */
     zrntokuyakukoumokuv200x6                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿６ */
     zrntokuyakukoumokuv200x7                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿７ */
     zrntokuyakukoumokuv200x8                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿８ */
     zrntokuyakukoumokuv200x9                           CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿９ */
     zrntokuyakukoumokuv200x10                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１０ */
     zrntokuyakukoumokuv200x11                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１１ */
     zrntokuyakukoumokuv200x12                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１２ */
     zrntokuyakukoumokuv200x13                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１３ */
     zrntokuyakukoumokuv200x14                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１４ */
     zrntokuyakukoumokuv200x15                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１５ */
     zrntokuyakukoumokuv200x16                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１６ */
     zrntokuyakukoumokuv200x17                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１７ */
     zrntokuyakukoumokuv200x18                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１８ */
     zrntokuyakukoumokuv200x19                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿１９ */
     zrntokuyakukoumokuv200x20                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２０ */
     zrntokuyakukoumokuv200x21                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２１ */
     zrntokuyakukoumokuv200x22                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２２ */
     zrntokuyakukoumokuv200x23                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２３ */
     zrntokuyakukoumokuv200x24                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２４ */
     zrntokuyakukoumokuv200x25                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２５ */
     zrntokuyakukoumokuv200x26                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２６ */
     zrntokuyakukoumokuv200x27                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２７ */
     zrntokuyakukoumokuv200x28                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２８ */
     zrntokuyakukoumokuv200x29                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿２９ */
     zrntokuyakukoumokuv200x30                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３０ */
     zrntokuyakukoumokuv200x31                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３１ */
     zrntokuyakukoumokuv200x32                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３２ */
     zrntokuyakukoumokuv200x33                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３３ */
     zrntokuyakukoumokuv200x34                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３４ */
     zrntokuyakukoumokuv200x35                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３５ */
     zrntokuyakukoumokuv200x36                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３６ */
     zrntokuyakukoumokuv200x37                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３７ */
     zrntokuyakukoumokuv200x38                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３８ */
     zrntokuyakukoumokuv200x39                          CHAR        (200)                                                     NOT NULL  ,  /* （連携用）特約項目Ｖ２００＿３９ */
     zrntokuyakukoumokuv200x40                          CHAR        (200)                                                     NOT NULL     /* （連携用）特約項目Ｖ２００＿４０ */
)
;

ALTER TABLE ZT_BikinIdouMeisaiRn ADD CONSTRAINT PK_BikinIdouMeisaiRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
