CREATE TABLE ZT_DairitenRn (
     zrndairitencd                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）代理店コード */
     zrndairitennm                                      CHAR        (30)                                                      NOT NULL  ,  /* （連携用）代理店名 */
     zrnkanjidairitennm                                 VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）漢字代理店名 */
     zrnitakukeiyakuymd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）委託契約年月日 */
     zrnitakukeiyakukaiyakuymd                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）委託契約解約年月日 */
     zrndairitentourokuymd                              CHAR        (8)                                                       NOT NULL  ,  /* （連携用）代理店登録年月日 */
     zrndaisinhidaisinkbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）代申非代申区分 */
     zrnkanrisosikicd1                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）管理組織コード（１） */
     zrnkanrisosikicd2                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）管理組織コード（２） */
     zrnkanrisosikicd3                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）管理組織コード（３） */
     zrnkeisyousakidairitencd                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）継承先代理店コード */
     zrnkeisyoumotodairitencd                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）継承元代理店コード */
     zrndrtensyouhncdkami3x1                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１ */
     zrntsryshrkbntougetux1                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１ */
     zrntsryshrkbnyokugetux1                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１ */
     zrnbntnptnkbnx1                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１ */
     zrndrtensyouhncdkami3x2                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿２ */
     zrntsryshrkbntougetux2                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿２ */
     zrntsryshrkbnyokugetux2                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿２ */
     zrnbntnptnkbnx2                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿２ */
     zrndrtensyouhncdkami3x3                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿３ */
     zrntsryshrkbntougetux3                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿３ */
     zrntsryshrkbnyokugetux3                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿３ */
     zrnbntnptnkbnx3                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿３ */
     zrndrtensyouhncdkami3x4                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿４ */
     zrntsryshrkbntougetux4                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿４ */
     zrntsryshrkbnyokugetux4                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿４ */
     zrnbntnptnkbnx4                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿４ */
     zrndrtensyouhncdkami3x5                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿５ */
     zrntsryshrkbntougetux5                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿５ */
     zrntsryshrkbnyokugetux5                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿５ */
     zrnbntnptnkbnx5                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿５ */
     zrndrtensyouhncdkami3x6                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿６ */
     zrntsryshrkbntougetux6                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿６ */
     zrntsryshrkbnyokugetux6                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿６ */
     zrnbntnptnkbnx6                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿６ */
     zrndrtensyouhncdkami3x7                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿７ */
     zrntsryshrkbntougetux7                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿７ */
     zrntsryshrkbnyokugetux7                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿７ */
     zrnbntnptnkbnx7                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿７ */
     zrndrtensyouhncdkami3x8                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿８ */
     zrntsryshrkbntougetux8                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿８ */
     zrntsryshrkbnyokugetux8                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿８ */
     zrnbntnptnkbnx8                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿８ */
     zrndrtensyouhncdkami3x9                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿９ */
     zrntsryshrkbntougetux9                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿９ */
     zrntsryshrkbnyokugetux9                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿９ */
     zrnbntnptnkbnx9                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿９ */
     zrndrtensyouhncdkami3x10                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１０ */
     zrntsryshrkbntougetux10                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１０ */
     zrntsryshrkbnyokugetux10                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１０ */
     zrnbntnptnkbnx10                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１０ */
     zrndrtensyouhncdkami3x11                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１１ */
     zrntsryshrkbntougetux11                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１１ */
     zrntsryshrkbnyokugetux11                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１１ */
     zrnbntnptnkbnx11                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１１ */
     zrndrtensyouhncdkami3x12                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１２ */
     zrntsryshrkbntougetux12                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１２ */
     zrntsryshrkbnyokugetux12                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１２ */
     zrnbntnptnkbnx12                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１２ */
     zrndrtensyouhncdkami3x13                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１３ */
     zrntsryshrkbntougetux13                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１３ */
     zrntsryshrkbnyokugetux13                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１３ */
     zrnbntnptnkbnx13                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１３ */
     zrndrtensyouhncdkami3x14                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１４ */
     zrntsryshrkbntougetux14                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１４ */
     zrntsryshrkbnyokugetux14                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１４ */
     zrnbntnptnkbnx14                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１４ */
     zrndrtensyouhncdkami3x15                           CHAR        (3)                                                       NOT NULL  ,  /* （連携用）代理店商品コード上３桁＿１５ */
     zrntsryshrkbntougetux15                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（当月）＿１５ */
     zrntsryshrkbnyokugetux15                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手数料支払区分（翌月）＿１５ */
     zrnbntnptnkbnx15                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分担パターン区分＿１５ */
     zrntsrybntnaitedrtencdx1                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）手数料分担相手代理店コード＿１ */
     zrntsrybntnwarix1                                  NUMBER      (3,2)                                                     NOT NULL  ,  /* （連携用）手数料分担割合＿１ */
     zrntsrybntnaitedrtencdx2                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）手数料分担相手代理店コード＿２ */
     zrntsrybntnwarix2                                  NUMBER      (3,2)                                                     NOT NULL  ,  /* （連携用）手数料分担割合＿２ */
     zrntsrybntnaitedrtencdx3                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）手数料分担相手代理店コード＿３ */
     zrntsrybntnwarix3                                  NUMBER      (3,2)                                                     NOT NULL  ,  /* （連携用）手数料分担割合＿３ */
     zrntsrybntnaitedrtencdx4                           CHAR        (7)                                                       NOT NULL  ,  /* （連携用）手数料分担相手代理店コード＿４ */
     zrntsrybntnwarix4                                  NUMBER      (3,2)                                                     NOT NULL  ,  /* （連携用）手数料分担割合＿４ */
     zrnhnsituhykranktougetu                            NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）品質評価ランク（当月） */
     zrnhnsituhykrankyokugetu                           NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）品質評価ランク（翌月） */
     zrnyobiv2x6                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿６ */
     zrndairitentelno                                   CHAR        (14)                                                      NOT NULL  ,  /* （連携用）代理店電話番号 */
     zrndairitenfaxno                                   CHAR        (14)                                                      NOT NULL  ,  /* （連携用）代理店ＦＡＸ番号 */
     zrnyobiv1                                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ１ */
     zrnyobiv2                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２ */
     zrnyobiv2x2                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿２ */
     zrnyobiv2x3                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿３ */
     zrnyobiv2x4                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿４ */
     zrnyobiv2x5                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿５ */
     zrnoyadairitencd                                   CHAR        (7)                                                       NOT NULL  ,  /* （連携用）親代理店コード */
     zrndairitenkouryokustartymd                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）代理店効力開始年月日 */
     zrndairitenkouryokuendymd                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）代理店効力終了年月日 */
     zrnkinyuukikancd                                   CHAR        (4)                                                       NOT NULL  ,  /* （連携用）金融機関コード */
     zrnkinyuukikansitencd                              CHAR        (4)                                                       NOT NULL  ,  /* （連携用）金融機関支店コード */
     zrndairitenjimusyocd                               CHAR        (4)                                                       NOT NULL  ,  /* （連携用）代理店事務所コード */
     zrndaihyoubosyuunincd                              CHAR        (6)                                                       NOT NULL  ,  /* （連携用）代表募集人コード */
     zrnbuntanaitedairitencd                            CHAR        (7)                                                       NOT NULL  ,  /* （連携用）分担相手代理店コード */
     zrnbuntanwariai                                    NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）分担割合 */
     zrntokureitiikihyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特例地域金融機関表示 */
     zrnkyoudousosikhyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）協同組織金融機関表示 */
     zrnkyoudoubosyuhyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）共同募集代理店表示 */
     zrnyuuseijimusyocd                                 CHAR        (6)                                                       NOT NULL  ,  /* （連携用）郵政事務所コード */
     zrntoukatudairitencd                               CHAR        (7)                                                       NOT NULL  ,  /* （連携用）統括代理店コード */
     zrnmdhnschemedrtenhyouji                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）窓販スキーム代理店表示 */
     zrntykatukaiyoudrtenhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）直扱用代理店表示 */
     zrndrtentrkno                                      CHAR        (13)                                                      NOT NULL  ,  /* （連携用）代理店登録番号 */
     zrnyobiv21                                         CHAR        (21)                                                      NOT NULL     /* （連携用）予備項目Ｖ２１ */
)
;

ALTER TABLE ZT_DairitenRn ADD CONSTRAINT PK_DairitenRn PRIMARY KEY (
     zrndairitencd                                              /* （連携用）代理店コード */
) ;
