CREATE TABLE ZT_EgsyokuinSysRendouRn (
     zrnsequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnatukaikojincd                                   CHAR        (6)                                                       NOT NULL  ,  /* （連携用）扱者個人コード */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrnsdpdkbn                                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｓ建Ｐ建区分 */
     zrnkihons                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）基本Ｓ */
     zrnharaikomip                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）払込Ｐ */
     zrnsyukeiyakup                                     NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約Ｐ */
     zrngyousekiyouhosyous                              NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）業績用保障Ｓ */
     zrnkydatkikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）共同扱区分 */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrntsinkihontikucd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）通信先基本地区コード */
     zrnatukaisosikicd                                  CHAR        (7)                                                       NOT NULL  ,  /* （連携用）扱者組織コード */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhhknnen2keta                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令（２桁） */
     zrnhensyuukeiyakusyamei                            CHAR        (41)                                                      NOT NULL  ,  /* （連携用）編集契約者名 */
     zrnhnsyuknjkyksynm                                 VARCHAR     (35)                                                      NOT NULL  ,  /* （連携用）編集漢字契約者名 */
     zrnkyksyanen                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約者年令 */
     zrnkurikosihyj                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）繰越表示 */
     zrnlivingneedstkykarihyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）リビングニーズ特約有表示 */
     zrnkyksyhhknsydouituhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者被保険者同一表示 */
     zrnhaitousiharaikbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）配当支払区分 */
     zrndairitenatkikeitaikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）代理店扱形態区分 */
     zrndrtenegsyokuinatkiwari                          NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）代理店営業職員扱割合 */
     zrnkjsakisosikisetteihyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）計上先組織設定表示 */
     zrnbsydrtencd                                      CHAR        (7)                                                       NOT NULL  ,  /* （連携用）募集代理店コード */
     zrnsimetyokuzenbosyuuhyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）〆切直前募集表示 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrnmosnyuuryokuymd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込入力年月日 */
     zrnhhknsakuinmeino                                 CHAR        (10)                                                      NOT NULL  ,  /* （連携用）被保険者索引名番号 */
     zrntokusyujimutoriatukaikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特殊事務取扱区分 */
     zrncifcd                                           CHAR        (15)                                                      NOT NULL  ,  /* （連携用）ＣＩＦコード */
     zrnhokensyuruikigouyobi1x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１ */
     zrnhokensyuruikigouyobi1x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿２ */
     zrnhokensyuruikigouyobi1x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿３ */
     zrnhokensyuruikigouyobi1x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿４ */
     zrnhokensyuruikigouyobi1x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿５ */
     zrnhokensyuruikigouyobi1x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿６ */
     zrnhokensyuruikigouyobi1x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿７ */
     zrnhokensyuruikigouyobi1x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿８ */
     zrnhokensyuruikigouyobi1x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿９ */
     zrnhokensyuruikigouyobi1x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１０ */
     zrnhokensyuruikigouyobi1x11                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１１ */
     zrnhokensyuruikigouyobi1x12                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１２ */
     zrnhokensyuruikigouyobi1x13                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１３ */
     zrnhokensyuruikigouyobi1x14                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１４ */
     zrnhokensyuruikigouyobi1x15                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１５ */
     zrnhokensyuruikigouyobi2x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿１ */
     zrnhokensyuruikigouyobi2x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿２ */
     zrnhokensyuruikigouyobi2x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿３ */
     zrnhokensyuruikigouyobi2x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿４ */
     zrnhokensyuruikigouyobi2x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿５ */
     zrnhokensyuruikigouyobi2x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿６ */
     zrnhokensyuruikigouyobi2x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿７ */
     zrnhokensyuruikigouyobi2x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿８ */
     zrnhokensyuruikigouyobi2x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿９ */
     zrnhokensyuruikigouyobi2x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿１０ */
     zrnhokensyuruikigouyobi3x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿１ */
     zrnhokensyuruikigouyobi3x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿２ */
     zrnhokensyuruikigouyobi3x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿３ */
     zrnhokensyuruikigouyobi3x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿４ */
     zrnhokensyuruikigouyobi3x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿５ */
     zrnhokensyuruikigouyobi3x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿６ */
     zrnhokensyuruikigouyobi3x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿７ */
     zrnhokensyuruikigouyobi3x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿８ */
     zrnhokensyuruikigouyobi3x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿９ */
     zrnhokensyuruikigouyobi3x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿１０ */
     zrnnstkarihyj                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金支払特約有表示 */
     zrnmosno                                           CHAR        (9)                                                       NOT NULL  ,  /* （連携用）申込番号 */
     zrnstdairiseikyuutkykarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）指定代理請求特約有表示 */
     zrnnenkansanp                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）年換算Ｐ */
     zrnkyksyaskinmeino                                 CHAR        (10)                                                      NOT NULL  ,  /* （連携用）契約者索引名番号 */
     zrnsibous                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）死亡Ｓ */
     zrnjissyuup                                        NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）実収Ｐ */
     zrnsekininkaisiymd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）責任開始年月日 */
     zrnkokutiymd                                       CHAR        (8)                                                       NOT NULL  ,  /* （連携用）告知年月日 */
     zrnsyokaipryosyuymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）初回Ｐ領収年月日 */
     zrnseirituymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）成立年月日 */
     zrnbosdairitentsratkiwari                          NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）募集代理店手数料扱割合 */
     zrnbosyuunincd                                     CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集人コード */
     zrndrtentsryhushrkykhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）代理店手数料不支払契約表示 */
     zrnmdhnaisyoumeikbn                                CHAR        (3)                                                       NOT NULL  ,  /* （連携用）窓販用愛称名区分 */
     zrndairitenkykkanrino                              CHAR        (11)                                                      NOT NULL  ,  /* （連携用）代理店契約管理番号 */
     zrnkanjitsinkaiadr                                 VARCHAR     (62)                                                      NOT NULL  ,  /* （連携用）漢字通信先下位住所 */
     zrntsintelno                                       CHAR        (14)                                                      NOT NULL  ,  /* （連携用）通信先電話番号 */
     zrnhensyuuyoukyksyaseikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）編集用契約者性別区分 */
     zrnhensyuuyoukyksyaseiymd                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）編集用契約者生年月日 */
     zrnhhknmei                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）被保険者名 */
     zrnknjhhknmei                                      VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字被保険者名 */
     zrnhhknseiymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）被保険者生年月日 */
     zrnnksyuruikbn1                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年金種類区分（１文字） */
     zrnmusymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込年月日 */
     zrnmossyosakuseiymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込書作成年月日 */
     zrnitijibaraipkyktuuka                             NUMBER      (15,2)                                                    NOT NULL  ,  /* （連携用）一時払Ｐ（契約通貨建） */
     zrnkawaseraten5                                    NUMBER      (5,2)                                                     NOT NULL  ,  /* （連携用）為替レートＮ５ */
     zrnhrktuukakbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込通貨区分 */
     zrnsiteituukakbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）指定通貨区分 */
     zrnsyksbsitihsyutkykarihyj                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）初期死亡時最低保証特約有表示 */
     zrnskkaigomaehrtkykarihyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）（新契約）介護前払特約有表示 */
     zrnkihonskyktuuka                                  NUMBER      (15)                                                      NOT NULL  ,  /* （連携用）基本Ｓ（契約通貨建） */
     zrnzenkizennouhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）全期前納表示 */
     zrnnnknsnpssysyup                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）年換算Ｐ算出用主契約Ｐ */
     zrnnknsnpssyhrkkskbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）年換算Ｐ算出用払込回数区分 */
     zrnkykdrtkykarihyj                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者代理特約有表示 */
     zrnkzktrkservicearihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ご家族登録サービス有表示 */
     zrnyobiv250x1                                      CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０＿１ */
     zrnyobiv250x2                                      CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０＿２ */
     zrnyobiv250x3                                      CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０＿３ */
     zrnyobiv250x4                                      CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０＿４ */
     zrnyobiv250x5                                      CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０＿５ */
     zrnyobiv118                                        CHAR        (118)                                                     NOT NULL     /* （連携用）予備項目Ｖ１１８ */
)
;

ALTER TABLE ZT_EgsyokuinSysRendouRn ADD CONSTRAINT PK_EgsyokuinSysRendouRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
