CREATE TABLE ZT_HonsyaToukeiRn (
     zrnkijyunym                                        CHAR        (6)                                                       NOT NULL  ,  /* （連携用）基準年月 */
     zrnmosym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）申込月度 */
     zrnmosno                                           CHAR        (9)                                                       NOT NULL  ,  /* （連携用）申込番号 */
     zrnsosikicd                                        CHAR        (7)                                                       NOT NULL  ,  /* （連携用）組織コード */
     zrnmossyoumetukbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）申込消滅区分 */
     zrnmossyumtkktymd                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込消滅確定年月日 */
     zrnrenseihhknkbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）連生被保険者区分 */
     zrndakuhikettikekkacd                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定結果コード */
     zrndkhktiymd                                       CHAR        (8)                                                       NOT NULL  ,  /* （連携用）諾否決定年月日 */
     zrnketkbn                                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）決定区分 */
     zrntoukeihknsyruikbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）統計用保険種類区分 */
     zrnhhknnen2keta                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令（２桁） */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhjykktkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）報状告知区分 */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnhrkkeirokbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込経路区分 */
     zrnryouritukbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）料率区分 */
     zrndakuhikts                                       NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）諾否決定Ｓ */
     zrnkihons                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）基本Ｓ */
     zrnhhkndaisansyakykkbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者第三者契約区分 */
     zrndainisentakuinfokakjkkbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）第２選択情報確認状況区分 */
     zrnmusymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込年月日 */
     zrnryousyuuymd                                     CHAR        (8)                                                       NOT NULL  ,  /* （連携用）領収年月日 */
     zrnkokutiymd                                       CHAR        (8)                                                       NOT NULL  ,  /* （連携用）告知年月日 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnseikeirenrakuymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）成契連絡年月日 */
     zrnnyknnyuuryokuymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）入金入力年月日 */
     zrnsisyaketnyuuryokuymd                            CHAR        (8)                                                       NOT NULL  ,  /* （連携用）支社決定入力年月日 */
     zrnkykkakiraiymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約確認依頼年月日 */
     zrnkeiyakukakuninsyuruikbn                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約確認種類区分 */
     zrnsiteidairikbn2                                  CHAR        (2)                                                       NOT NULL  ,  /* （連携用）指定代理人区分（２文字） */
     zrnkykkakjkkbn1                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約確認状況区分（１文字） */
     zrnkykkakkanryouymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約確認完了年月日 */
     zrnkykkakketymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約確認決定年月日 */
     zrnkykkakketkekkakbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約確認決定結果区分 */
     zrnkykkaktantoukojincd                             CHAR        (6)                                                       NOT NULL  ,  /* （連携用）契約確認担当者個人コード */
     zrnketsyacd                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）決定者コード */
     zrnsyosakuseiymd                                   CHAR        (8)                                                       NOT NULL  ,  /* （連携用）証券作成年月日 */
     zrnseisekiym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）成績計上年月 */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrnsyokaiharaikomip                                NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）初回払込Ｐ */
     zrnmossyosakuseiymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）申込書作成年月日 */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrndakuhiketteiriyuucdx1                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定理由コード＿１ */
     zrndakuhiketteiriyuucdx2                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定理由コード＿２ */
     zrndakuhiketteiriyuucdx3                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定理由コード＿３ */
     zrndakuhiketteiriyuucdx4                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定理由コード＿４ */
     zrnhenkouteiseisyorikaisuu                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）変更訂正処理回数 */
     zrnsyosisyatodokekibouhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）証券支社届希望表示 */
     zrnhndketkaisuu                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ハンド決定回数 */
     zrndakuhiketkeiikekkacd1                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード１ */
     zrndakuhiketkeiiketmd1                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日１ */
     zrndakuhiketkeiikekkacd2                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード２ */
     zrndakuhiketkeiiketmd2                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日２ */
     zrndakuhiketkeiikekkacd3                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード３ */
     zrndakuhiketkeiiketmd3                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日３ */
     zrndakuhiketkeiikekkacd4                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード４ */
     zrndakuhiketkeiiketmd4                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日４ */
     zrndakuhiketkeiikekkacd5                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード５ */
     zrndakuhiketkeiiketmd5                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日５ */
     zrndakuhiketkeiikekkacd6                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯結果コード６ */
     zrndakuhiketkeiiketmd6                             CHAR        (4)                                                       NOT NULL  ,  /* （連携用）諾否決定経緯決定月日６ */
     zrnkojincd                                         CHAR        (6)                                                       NOT NULL  ,  /* （連携用）個人コード */
     zrnsyokaipnyuukinhouhoukbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）初回Ｐ入金方法区分 */
     zrnsentakuinfoumuhyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）選択情報有無表示 */
     zrnhaitousiharaikbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）配当支払区分 */
     zrnhonsyatkkohojyunhsys                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）本社統計個保純保障Ｓ */
     zrntoukeiyousinsakbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）統計用診査区分 */
     zrnsknnkaisiymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）責任開始日 */
     zrnbsudirtnatkikeitaikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）募集代理店扱形態区分 */
     zrnhhknsynensyuukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者年収区分 */
     zrntokusyujimutoriatukaikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特殊事務取扱区分 */
     zrninputmissteiseikaisuu                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）インプットミス訂正処理回数 */
     zrnkjkyknm                                         VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字契約者名 */
     zrnknjhhknmei                                      VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字被保険者名 */
     zrnhonninkknnkbn                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）本人確認区分 */
     zrnnyknzumihyouji                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）入金済表示 */
     zrnhhknsykgycd                                     CHAR        (3)                                                       NOT NULL  ,  /* （連携用）被保険者職業コード */
     zrnnyknjkkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）入金状況区分 */
     zrnbatukaisyakojincd                               CHAR        (6)                                                       NOT NULL  ,  /* （連携用）Ｂ扱者個人コード */
     zrnsinfstpnyknhouhoukbn                            CHAR        (2)                                                       NOT NULL  ,  /* （連携用）新初回Ｐ入金方法区分 */
     zrnmostorikesikbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）申込取消区分 */
     zrnmostrkssyousairiyuukbn                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）申込取消詳細理由区分 */
     zrnmossakuseino                                    CHAR        (9)                                                       NOT NULL  ,  /* （連携用）申込書作成番号 */
     zrnsibous                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）死亡Ｓ */
     zrnharaikomip                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）払込Ｐ */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnkyknm                                           CHAR        (18)                                                      NOT NULL  ,  /* （連携用）契約者名 */
     zrnkyktdkkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者続柄区分 */
     zrnkyksyanen                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約者年令 */
     zrnkyksyaseikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者性別区分 */
     zrnmosjihonninkknnkbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）申込時本人確認区分 */
     zrnhhknmei                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）被保険者名 */
     zrnsbuktkbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）死亡受取人区分 */
     zrnkjsbuktnm                                       VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字死亡受取人名 */
     zrnsbuktnm                                         CHAR        (18)                                                      NOT NULL  ,  /* （連携用）死亡受取人名 */
     zrnsbuktseiymd                                     CHAR        (8)                                                       NOT NULL  ,  /* （連携用）死亡受取人生年月日 */
     zrnsbukttdkkbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）死亡受取人続柄区分 */
     zrnkjsiteidairininnm                               VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字指定代理人名 */
     zrnsiteidairininnm                                 CHAR        (18)                                                      NOT NULL  ,  /* （連携用）指定代理人名 */
     zrnfatcakakkekkakbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＦＡＴＣＡ確認結果区分 */
     zrnfatcamosjikakkokusekikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＦＡＴＣＡ申込時確認国籍区分 */
     zrnfatcatorjikakkokusekikbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＦＡＴＣＡ取引時確認国籍区分 */
     zrnkzkakiraikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）口座確認依頼区分 */
     zrnkzkakiraiymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）口座確認依頼年月日 */
     zrnbankyohurikzhyouji                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）銀行預振口座表示 */
     zrnkzmeigikakuninzumikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）口座名義人確認済区分 */
     zrnznnkai                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）前納回数 */
     zrnkzktrkservicekbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ご家族登録サービス区分 */
     zrnkykdrkbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者代理人区分 */
     zrnkjkykdairinm                                    VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字契約者代理人名 */
     zrnkykdairinm                                      CHAR        (18)                                                      NOT NULL  ,  /* （連携用）契約者代理人名 */
     zrntrkkzktdk1keta1                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）登録家族続柄１（１桁） */
     zrnkjkzktourokunm1                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字家族登録名１ */
     zrnkzktourokunm1                                   CHAR        (18)                                                      NOT NULL  ,  /* （連携用）家族登録名１ */
     zrntrkkzktdk2keta1                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）登録家族続柄２（１桁） */
     zrnkjkzktourokunm2                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）漢字家族登録名２ */
     zrnkzktourokunm2                                   CHAR        (18)                                                      NOT NULL  ,  /* （連携用）家族登録名２ */
     zrnyakkanjyuryouhoukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）約款受領方法区分 */
     zrnyakkanbunsyono                                  CHAR        (16)                                                      NOT NULL  ,  /* （連携用）約款文書番号 */
     zrnyobiv250                                        CHAR        (250)                                                     NOT NULL  ,  /* （連携用）予備項目Ｖ２５０ */
     zrnyobiv28                                         CHAR        (28)                                                      NOT NULL     /* （連携用）予備項目Ｖ２８ */
)
;

ALTER TABLE ZT_HonsyaToukeiRn ADD CONSTRAINT PK_HonsyaToukeiRn PRIMARY KEY (
     zrnkijyunym                                              , /* （連携用）基準年月 */
     zrnmosno                                                   /* （連携用）申込番号 */
) ;
