CREATE TABLE ZT_HoyuuJyunzouZougenFTy (
     ztysequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztytantoukojincd                                   VARCHAR     (6)                                                                 ,  /* （中継用）担当者個人コード */
     ztytantousyasetteiym                               VARCHAR     (6)                                                                 ,  /* （中継用）担当者設定年月 */
     ztykeijyousakikbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）計上先区分 */
     ztykeijyousakisosiki                               VARCHAR     (7)                                                                 ,  /* （中継用）計上先組織 */
     ztykeijyouym                                       VARCHAR     (6)                                                                 ,  /* （中継用）計上年月 */
     ztydenymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）伝票日付 */
     ztyutiwakekbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）内訳区分 */
     ztytantoukeiyakukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）担当契約区分 */
     ztykydatkikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）共同扱区分 */
     ztysyono                                           VARCHAR     (11)                                                                ,  /* （中継用）証券番号 */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztysaisinbsyym                                     VARCHAR     (6)                                                                 ,  /* （中継用）最新募集年月 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztymaruteisyuruikigou                              VARCHAR     (2)                                                                 ,  /* （中継用）マル定種類記号 */
     ztyyobin3                                          NUMBER      (3)                                                                 ,  /* （中継用）予備項目Ｎ３ */
     ztyyobiv1                                          VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１ */
     ztyyobiv1x2                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿２ */
     ztykykniyutksytioukbn                              VARCHAR     (1)                                                                 ,  /* （中継用）契約内容特殊対応区分 */
     ztyyobiv1x3                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿３ */
     ztyteisyuuhyj                                      VARCHAR     (1)                                                                 ,  /* （中継用）定終表示 */
     ztyitijibryourouhyj                                VARCHAR     (1)                                                                 ,  /* （中継用）一時払養老表示 */
     ztymrtihukahyj                                     VARCHAR     (1)                                                                 ,  /* （中継用）マル定付加表示 */
     ztyseizonmrtihukahyj                               VARCHAR     (1)                                                                 ,  /* （中継用）生存マル定付加表示 */
     ztyteigenmrtihukahyj                               VARCHAR     (1)                                                                 ,  /* （中継用）逓減マル定付加表示 */
     ztysynymrtihukahyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）収入マル定付加表示 */
     ztylivingneedstkykarihyj                           VARCHAR     (1)                                                                 ,  /* （中継用）リビングニーズ特約有表示 */
     ztyreguardmrtihukahyj                              VARCHAR     (1)                                                                 ,  /* （中継用）リガードマル定付加表示 */
     ztyreguardmrsyuhukahyj                             VARCHAR     (1)                                                                 ,  /* （中継用）リガードマル終付加表示 */
     ztyvguardmrtihukahyj                               VARCHAR     (1)                                                                 ,  /* （中継用）Ｖガードマル定付加表示 */
     ztykaigonktkykhukahyj                              VARCHAR     (1)                                                                 ,  /* （中継用）介護年金特約付加表示 */
     ztygoukeisisttkyktkknsnp                           NUMBER      (11)                                                                ,  /* （中継用）合計災疾特約月換算Ｐ */
     ztyhsys                                            NUMBER      (11)                                                                ,  /* （中継用）保障Ｓ */
     ztykensuun3                                        NUMBER      (3,1)                                                               ,  /* （中継用）件数Ｎ３ */
     ztyhenkougohosyous                                 NUMBER      (11)                                                                ,  /* （中継用）変更後保障Ｓ */
     ztyhtns                                            NUMBER      (11)                                                                ,  /* （中継用）被転換Ｓ */
     ztyharaikomip                                      NUMBER      (11)                                                                ,  /* （中継用）払込Ｐ */
     ztykaiyakusiharaikngk                              NUMBER      (11)                                                                ,  /* （中継用）解約支払金額 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztyanniskcd                                        VARCHAR     (8)                                                                 ,  /* （中継用）案内先コード */
     ztytenkankaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）転換回数 */
     ztysikkounyknkaisuu                                VARCHAR     (2)                                                                 ,  /* （中継用）失効入金回数 */
     ztyyobiv2                                          VARCHAR     (2)                                                                 ,  /* （中継用）予備項目Ｖ２ */
     ztyhhknnen2keta                                    VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令（２桁） */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztykjkyknm                                         VARCHAR     (15)                                                                ,  /* （中継用）漢字契約者名 */
     ztytsinkihontikucd                                 VARCHAR     (8)                                                                 ,  /* （中継用）通信先基本地区コード */
     ztyhjnkykhyj                                       VARCHAR     (1)                                                                 ,  /* （中継用）法人契約表示 */
     ztyhjncd                                           VARCHAR     (9)                                                                 ,  /* （中継用）法人コード */
     ztyhjnjigyosyocd                                   VARCHAR     (3)                                                                 ,  /* （中継用）法人事業所コード */
     ztysyorisosikicd                                   VARCHAR     (7)                                                                 ,  /* （中継用）処理組織コード */
     ztytikusyokansisyakijyhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）地区所管支社計上表示 */
     ztykeizokutyuuihyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）継続注意表示 */
     ztytyohkkeiyakutyuuikbn                            VARCHAR     (1)                                                                 ,  /* （中継用）重複契約注意区分 */
     ztyyobiv1x4                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿４ */
     ztydantaisyozokucd                                 VARCHAR     (10)                                                                ,  /* （中継用）団体所属コード */
     ztysuperknkuseikatupackhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）スーパー健康生活パック表示 */
     ztyjikokykhyj                                      VARCHAR     (1)                                                                 ,  /* （中継用）自己契約表示 */
     ztykikeiyakutyuuihyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）既契約注意表示 */
     ztysyuuseis                                        NUMBER      (11)                                                                ,  /* （中継用）修正Ｓ */
     ztyclubsumiseikaiinkykkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）クラブスミセイ会員契約区分 */
     ztygatkihmkknrkmaekykhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）Ｇ扱者訪問結果入力前契約表示 */
     ztygatkisetteikouhokykhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）Ｇ扱者設定候補契約表示 */
     ztybosyuu25keikahyj                                VARCHAR     (1)                                                                 ,  /* （中継用）募集２５カ月経過表示 */
     ztytokuteidaisyokudanhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）特定大職団表示 */
     ztyhoyuuikantsgkykhyj                              VARCHAR     (1)                                                                 ,  /* （中継用）保有移管対象外契約表示 */
     ztytokubeturuletikuhyj                             VARCHAR     (1)                                                                 ,  /* （中継用）特別ルール地区表示 */
     ztyfieldtantousyaarihyj                            VARCHAR     (1)                                                                 ,  /* （中継用）フィールド担当者有表示 */
     ztyyobiv1x5                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿５ */
     ztycatkihmkknrkmaekykhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）Ｃ扱者訪問結果入力前契約表示 */
     ztycatkisetteikouhokykhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）Ｃ扱者設定候補契約表示 */
     ztyseppankeijyoukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）折半計上区分 */
     ztyyobiv6                                          VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６ */
     ztyfollowtantousyakbn                              VARCHAR     (2)                                                                 ,  /* （中継用）フォロー担当者区分 */
     ztyyobiv7                                          VARCHAR     (7)                                                                 ,  /* （中継用）予備項目Ｖ７ */
     ztyhosyouminaosikaisuuv2                           VARCHAR     (2)                                                                 ,  /* （中継用）保障見直回数Ｖ２ */
     ztybnkttnknkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）分割転換区分 */
     ztytenkangosyono                                   VARCHAR     (11)                                                                ,  /* （中継用）転換後証券番号 */
     ztyqpackhyj                                        VARCHAR     (1)                                                                 ,  /* （中継用）Ｑパック表示 */
     ztytenkangoqpackhyj                                VARCHAR     (1)                                                                 ,  /* （中継用）転換後Ｑパック表示 */
     ztysyuruihnkutkbttrtkhyj                           VARCHAR     (1)                                                                 ,  /* （中継用）種類変更特別取扱表示 */
     ztytnkngsyuhnkutkbttrtkhyj                         VARCHAR     (1)                                                                 ,  /* （中継用）転換後種類変更特別取扱表示 */
     ztyyobin11                                         NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１ */
     ztykibanhikitugikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）基盤引継加算区分 */
     ztyyobiv1x6                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿６ */
     ztysyoumetucd                                      VARCHAR     (4)                                                                 ,  /* （中継用）消滅コード */
     ztyjikaipjyuutouym                                 VARCHAR     (6)                                                                 ,  /* （中継用）次回Ｐ充当年月 */
     ztykaigomarusyuuhukahyj                            VARCHAR     (1)                                                                 ,  /* （中継用）介護マル終付加表示 */
     ztyyobiv1x7                                        VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿７ */
     ztysyoritorikesihyj                                VARCHAR     (1)                                                                 ,  /* （中継用）処理取消表示 */
     ztymrtikousinkatakbn                               VARCHAR     (1)                                                                 ,  /* （中継用）マル定更新型区分 */
     ztypmenkbnv1                                       VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免区分Ｖ１ */
     ztysyukeiyakutkknsnp                               NUMBER      (11)                                                                ,  /* （中継用）主契約月換算Ｐ */
     ztynenkansanp                                      NUMBER      (11)                                                                ,  /* （中継用）年換算Ｐ */
     ztydai3bunyanenkansanp                             NUMBER      (11)                                                                ,  /* （中継用）第３分野年換算Ｐ */
     ztynyuuintkykhukahyj                               VARCHAR     (1)                                                                 ,  /* （中継用）入院特約付加表示 */
     ztynyuuintkykhukahyj20ijyou                        VARCHAR     (1)                                                                 ,  /* （中継用）２０日以上入院特約付加表示 */
     ztynyuuintkykhukahyj5ijyou                         VARCHAR     (1)                                                                 ,  /* （中継用）５日以上入院特約付加表示 */
     ztymarusyotkykhukahyj                              VARCHAR     (1)                                                                 ,  /* （中継用）マル初特約付加表示 */
     ztymarujyuutkykhukahyj                             VARCHAR     (1)                                                                 ,  /* （中継用）マル重特約付加表示 */
     ztykakudaimaruitkykhukahyj                         VARCHAR     (1)                                                                 ,  /* （中継用）拡大マル医系特約付加表示 */
     ztykakunyuutkykhukahyj                             VARCHAR     (1)                                                                 ,  /* （中継用）カク入特約付加表示 */
     ztymaruitkykhukahyj                                VARCHAR     (1)                                                                 ,  /* （中継用）マル医特約付加表示 */
     ztystdairiseikyuutkykarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）指定代理請求特約有表示 */
     ztykensuuyuuguukbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）件数優遇区分 */
     ztykaigosynyteikikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）（介護）収入定期区分 */
     ztykaigosynyteikishrkskbn                          VARCHAR     (1)                                                                 ,  /* （中継用）（介護）収入定期支払回数区分 */
     ztygyousekibosyujisikakucd                         VARCHAR     (5)                                                                 ,  /* （中継用）業績用募集時資格コード */
     ztygyskboshtnsineiyksnkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）業績用募集時発展新鋭躍進区分 */
     ztysiktsynymrtihukahyj                             VARCHAR     (1)                                                                 ,  /* （中継用）生活収入マル定付加表示 */
     ztysiktsynyteikikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）生活収入定期区分 */
     ztyseikatusyuunyuumrtis                            NUMBER      (11)                                                                ,  /* （中継用）生活収入マル定Ｓ */
     ztylivguardhukahyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）ＬＩＶガード付加表示 */
     ztylivguards                                       NUMBER      (11)                                                                ,  /* （中継用）ＬＩＶガードＳ */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekzjtkaisiymd                                VARCHAR     (8)                                                                 ,  /* （中継用）Ｂｌｕｅ継続状態開始年月日　 */
     ztyknkuzusnzyrtstkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率用ステータス区分 */
     ztykykdrtkykarihyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）契約者代理特約有表示 */
     ztykzktourokuservicearihyj                         VARCHAR     (1)                                                                 ,  /* （中継用）家族登録サービス有表示 */
     ztyyobiv1x11                                       VARCHAR     (1)                                                                 ,  /* （中継用）予備項目Ｖ１＿１１ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_HoyuuJyunzouZougenFTy ADD CONSTRAINT PK_HoyuuJyunzouZougenFTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
