CREATE TABLE ZT_HonsyaToukeiTy (
     ztykijyunym                                        VARCHAR     (6)                                                       NOT NULL  ,  /* （中継用）基準年月 */
     ztymosym                                           VARCHAR     (6)                                                                 ,  /* （中継用）申込月度 */
     ztymosno                                           VARCHAR     (9)                                                       NOT NULL  ,  /* （中継用）申込番号 */
     ztysosikicd                                        VARCHAR     (7)                                                                 ,  /* （中継用）組織コード */
     ztymossyoumetukbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）申込消滅区分 */
     ztymossyumtkktymd                                  VARCHAR     (8)                                                                 ,  /* （中継用）申込消滅確定年月日 */
     ztyrenseihhknkbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）連生被保険者区分 */
     ztydakuhikettikekkacd                              VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定結果コード */
     ztydkhktiymd                                       VARCHAR     (8)                                                                 ,  /* （中継用）諾否決定年月日 */
     ztyketkbn                                          VARCHAR     (1)                                                                 ,  /* （中継用）決定区分 */
     ztytoukeihknsyruikbn                               VARCHAR     (2)                                                                 ,  /* （中継用）統計用保険種類区分 */
     ztyhhknnen2keta                                    VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令（２桁） */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhjykktkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）報状告知区分 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztyryouritukbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）料率区分 */
     ztydakuhikts                                       NUMBER      (11)                                                                ,  /* （中継用）諾否決定Ｓ */
     ztykihons                                          NUMBER      (11)                                                                ,  /* （中継用）基本Ｓ */
     ztyhhkndaisansyakykkbn                             VARCHAR     (1)                                                                 ,  /* （中継用）被保険者第三者契約区分 */
     ztydainisentakuinfokakjkkbn                        VARCHAR     (1)                                                                 ,  /* （中継用）第２選択情報確認状況区分 */
     ztymusymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）申込年月日 */
     ztyryousyuuymd                                     VARCHAR     (8)                                                                 ,  /* （中継用）領収年月日 */
     ztykokutiymd                                       VARCHAR     (8)                                                                 ,  /* （中継用）告知年月日 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztyseikeirenrakuymd                                VARCHAR     (8)                                                                 ,  /* （中継用）成契連絡年月日 */
     ztynyknnyuuryokuymd                                VARCHAR     (8)                                                                 ,  /* （中継用）入金入力年月日 */
     ztysisyaketnyuuryokuymd                            VARCHAR     (8)                                                                 ,  /* （中継用）支社決定入力年月日 */
     ztykykkakiraiymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）契約確認依頼年月日 */
     ztykeiyakukakuninsyuruikbn                         VARCHAR     (2)                                                                 ,  /* （中継用）契約確認種類区分 */
     ztysiteidairikbn2                                  VARCHAR     (2)                                                                 ,  /* （中継用）指定代理人区分（２文字） */
     ztykykkakjkkbn1                                    VARCHAR     (1)                                                                 ,  /* （中継用）契約確認状況区分（1文字） */
     ztykykkakkanryouymd                                VARCHAR     (8)                                                                 ,  /* （中継用）契約確認完了年月日 */
     ztykykkakketymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）契約確認決定年月日 */
     ztykykkakketkekkakbn                               VARCHAR     (1)                                                                 ,  /* （中継用）契約確認決定結果区分 */
     ztykykkaktantoukojincd                             VARCHAR     (6)                                                                 ,  /* （中継用）契約確認担当者個人コード */
     ztyketsyacd                                        VARCHAR     (2)                                                                 ,  /* （中継用）決定者コード */
     ztysyosakuseiymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）証券作成年月日 */
     ztyseisekiym                                       VARCHAR     (6)                                                                 ,  /* （中継用）成績計上年月 */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztysyokaiharaikomip                                NUMBER      (11)                                                                ,  /* （中継用）初回払込Ｐ */
     ztymossyosakuseiymd                                VARCHAR     (8)                                                                 ,  /* （中継用）申込書作成年月日 */
     ztysyono                                           VARCHAR     (11)                                                                ,  /* （中継用）証券番号 */
     ztydakuhiketteiriyuucdx1                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定理由コード＿１ */
     ztydakuhiketteiriyuucdx2                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定理由コード＿２ */
     ztydakuhiketteiriyuucdx3                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定理由コード＿３ */
     ztydakuhiketteiriyuucdx4                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定理由コード＿４ */
     ztyhenkouteiseisyorikaisuu                         VARCHAR     (2)                                                                 ,  /* （中継用）変更訂正処理回数 */
     ztysyosisyatodokekibouhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）証券支社届希望表示 */
     ztyhndketkaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）ハンド決定回数 */
     ztydakuhiketkeiikekkacd1                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード１ */
     ztydakuhiketkeiiketmd1                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日１ */
     ztydakuhiketkeiikekkacd2                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード２ */
     ztydakuhiketkeiiketmd2                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日２ */
     ztydakuhiketkeiikekkacd3                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード３ */
     ztydakuhiketkeiiketmd3                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日３ */
     ztydakuhiketkeiikekkacd4                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード４ */
     ztydakuhiketkeiiketmd4                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日４ */
     ztydakuhiketkeiikekkacd5                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード５ */
     ztydakuhiketkeiiketmd5                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日５ */
     ztydakuhiketkeiikekkacd6                           VARCHAR     (2)                                                                 ,  /* （中継用）諾否決定経緯結果コード６ */
     ztydakuhiketkeiiketmd6                             VARCHAR     (4)                                                                 ,  /* （中継用）諾否決定経緯決定月日６ */
     ztykojincd                                         VARCHAR     (6)                                                                 ,  /* （中継用）個人コード */
     ztysyokaipnyuukinhouhoukbn                         VARCHAR     (1)                                                                 ,  /* （中継用）初回Ｐ入金方法区分 */
     ztysentakuinfoumuhyj                               VARCHAR     (1)                                                                 ,  /* （中継用）選択情報有無表示 */
     ztyhaitousiharaikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）配当支払区分 */
     ztyhonsyatkkohojyunhsys                            NUMBER      (11)                                                                ,  /* （中継用）本社統計個保純保障Ｓ */
     ztytoukeiyousinsakbn                               VARCHAR     (2)                                                                 ,  /* （中継用）統計用診査区分 */
     ztysknnkaisiymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）責任開始日 */
     ztybsudirtnatkikeitaikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）募集代理店扱形態区分 */
     ztyhhknsynensyuukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）被保険者年収区分 */
     ztytokusyujimutoriatukaikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）特殊事務取扱区分 */
     ztyinputmissteiseikaisuu                           VARCHAR     (2)                                                                 ,  /* （中継用）インプットミス訂正処理回数 */
     ztykjkyknm                                         VARCHAR     (15)                                                                ,  /* （中継用）漢字契約者名 */
     ztyknjhhknmei                                      VARCHAR     (15)                                                                ,  /* （中継用）漢字被保険者名 */
     ztyhonninkknnkbn                                   VARCHAR     (2)                                                                 ,  /* （中継用）本人確認区分 */
     ztynyknzumihyouji                                  VARCHAR     (1)                                                                 ,  /* （中継用）入金済表示 */
     ztyhhknsykgycd                                     VARCHAR     (3)                                                                 ,  /* （中継用）被保険者職業コード */
     ztynyknjkkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）入金状況区分 */
     ztybatukaisyakojincd                               VARCHAR     (6)                                                                 ,  /* （中継用）Ｂ扱者個人コード */
     ztysinfstpnyknhouhoukbn                            VARCHAR     (2)                                                                 ,  /* （中継用）新初回Ｐ入金方法区分 */
     ztymostorikesikbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）申込取消区分 */
     ztymostrkssyousairiyuukbn                          VARCHAR     (2)                                                                 ,  /* （中継用）申込取消詳細理由区分 */
     ztymossakuseino                                    VARCHAR     (9)                                                                 ,  /* （中継用）申込書作成番号 */
     ztysibous                                          NUMBER      (11)                                                                ,  /* （中継用）死亡Ｓ */
     ztyharaikomip                                      NUMBER      (11)                                                                ,  /* （中継用）払込Ｐ */
     ztyhknkkn                                          VARCHAR     (2)                                                                 ,  /* （中継用）保険期間 */
     ztyphrkkikn                                        VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）才満期契約表示 */
     ztykyknm                                           VARCHAR     (18)                                                                ,  /* （中継用）契約者名 */
     ztykyktdkkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）契約者続柄区分 */
     ztykyksyanen                                       VARCHAR     (2)                                                                 ,  /* （中継用）契約者年令 */
     ztykyksyaseikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）契約者性別区分 */
     ztymosjihonninkknnkbn                              VARCHAR     (2)                                                                 ,  /* （中継用）申込時本人確認区分 */
     ztyhhknmei                                         VARCHAR     (18)                                                                ,  /* （中継用）被保険者名 */
     ztysbuktkbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）死亡受取人区分 */
     ztykjsbuktnm                                       VARCHAR     (15)                                                                ,  /* （中継用）漢字死亡受取人名 */
     ztysbuktnm                                         VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名 */
     ztysbuktseiymd                                     VARCHAR     (8)                                                                 ,  /* （中継用）死亡受取人生年月日 */
     ztysbukttdkkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）死亡受取人続柄区分 */
     ztykjsiteidairininnm                               VARCHAR     (15)                                                                ,  /* （中継用）漢字指定代理人名 */
     ztysiteidairininnm                                 VARCHAR     (18)                                                                ,  /* （中継用）指定代理人名 */
     ztyfatcakakkekkakbn                                VARCHAR     (1)                                                                 ,  /* （中継用）ＦＡＴＣＡ確認結果区分 */
     ztyfatcamosjikakkokusekikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）ＦＡＴＣＡ申込時確認国籍区分 */
     ztyfatcatorjikakkokusekikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）ＦＡＴＣＡ取引時確認国籍区分 */
     ztykzkakiraikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）口座確認依頼区分 */
     ztykzkakiraiymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）口座確認依頼年月日 */
     ztybankyohurikzhyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）銀行預振口座表示 */
     ztykzmeigikakuninzumikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）口座名義人確認済区分 */
     ztyznnkai                                          VARCHAR     (2)                                                                 ,  /* （中継用）前納回数 */
     ztykzktrkservicekbn                                VARCHAR     (1)                                                                 ,  /* （中継用）ご家族登録サービス区分 */
     ztykykdrkbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）契約者代理人区分 */
     ztykjkykdairinm                                    VARCHAR     (15)                                                                ,  /* （中継用）漢字契約者代理人名 */
     ztykykdairinm                                      VARCHAR     (18)                                                                ,  /* （中継用）契約者代理人名 */
     ztytrkkzktdk1keta1                                 VARCHAR     (1)                                                                 ,  /* （中継用）登録家族続柄１（１桁） */
     ztykjkzktourokunm1                                 VARCHAR     (15)                                                                ,  /* （中継用）漢字家族登録名１ */
     ztykzktourokunm1                                   VARCHAR     (18)                                                                ,  /* （中継用）家族登録名１ */
     ztytrkkzktdk2keta1                                 VARCHAR     (1)                                                                 ,  /* （中継用）登録家族続柄２（１桁） */
     ztykjkzktourokunm2                                 VARCHAR     (15)                                                                ,  /* （中継用）漢字家族登録名２ */
     ztykzktourokunm2                                   VARCHAR     (18)                                                                ,  /* （中継用）家族登録名２ */
     ztyyakkanjyuryouhoukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）約款受領方法区分 */
     ztyyakkanbunsyono                                  VARCHAR     (16)                                                                ,  /* （中継用）約款文書番号 */
     ztyyobiv250                                        VARCHAR     (250)                                                               ,  /* （中継用）予備項目Ｖ２５０ */
     ztyyobiv28                                         VARCHAR     (28)                                                                ,  /* （中継用）予備項目Ｖ２８ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_HonsyaToukeiTy ADD CONSTRAINT PK_HonsyaToukeiTy PRIMARY KEY (
     ztykijyunym                                              , /* （中継用）基準年月 */
     ztymosno                                                   /* （中継用）申込番号 */
) ;
