CREATE TABLE ZT_KyhknShrJyoukyouRnrkTy (
     ztysequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztyyobiv12                                         VARCHAR     (12)                                                                ,  /* （中継用）予備項目Ｖ１２ */
     ztydatakanrino                                     VARCHAR     (11)                                                                ,  /* （中継用）データ管理番号 */
     ztyyobiv4                                          VARCHAR     (4)                                                                 ,  /* （中継用）予備項目Ｖ４ */
     ztytksyukgu                                        VARCHAR     (2)                                                                 ,  /* （中継用）特約種類記号 */
     ztytokuyakugatakbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）特約型区分 */
     ztytokuyakukisi                                    VARCHAR     (8)                                                                 ,  /* （中継用）特約期始 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztytyuutohukakbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）中途付加区分 */
     ztyhyoukataikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）標下体区分 */
     ztyatukaisisyatodouhukencd                         VARCHAR     (2)                                                                 ,  /* （中継用）扱支社都道府県コード */
     ztytokuyakusinkyuukbn                              VARCHAR     (1)                                                                 ,  /* （中継用）特約新旧区分 */
     ztybsyym                                           VARCHAR     (6)                                                                 ,  /* （中継用）募集年月 */
     ztytkykdai2hihokensyahyj                           VARCHAR     (1)                                                                 ,  /* （中継用）特約第２被保険者表示 */
     ztytokuteisippeisethyj                             VARCHAR     (1)                                                                 ,  /* （中継用）特定疾病セット表示 */
     ztyjyusyousyaseibetukbn                            VARCHAR     (1)                                                                 ,  /* （中継用）受傷者性別区分 */
     ztykazokujyusyousyakbn                             VARCHAR     (1)                                                                 ,  /* （中継用）家族受傷者区分 */
     ztykeiyakunen                                      VARCHAR     (2)                                                                 ,  /* （中継用）契約年令 */
     ztymannenreihyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）満年令表示 */
     ztyhhknnentysihyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）被保険者年令調整表示 */
     ztyyobiv2                                          VARCHAR     (2)                                                                 ,  /* （中継用）予備項目Ｖ２ */
     ztykyuuhukbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）給付区分 */
     ztysiharaijyoutaikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）支払状態区分 */
     ztysyouincd                                        VARCHAR     (3)                                                                 ,  /* （中継用）消因コード */
     ztyjikohasseiymd2                                  VARCHAR     (8)                                                                 ,  /* （中継用）事故発生年月日 */
     ztysyougaikoteiymd                                 VARCHAR     (8)                                                                 ,  /* （中継用）傷害固定年月日 */
     ztynyuuinymd                                       VARCHAR     (8)                                                                 ,  /* （中継用）入院年月日 */
     ztyshrymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）支払年月日 */
     ztykyuuhuwariai                                    VARCHAR     (3)                                                                 ,  /* （中継用）給付割合 */
     ztysiharaikingakun9                                NUMBER      (9)                                                                 ,  /* （中継用）支払金額Ｎ９ */
     ztykyoukaihoukokuyoukingaku                        NUMBER      (9)                                                                 ,  /* （中継用）協会報告用金額 */
     ztytuuinkakujyuuhukakbn                            VARCHAR     (1)                                                                 ,  /* （中継用）通院カク充付加区分 */
     ztykangohukahyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）看護付加表示 */
     ztysonsyoukyuuhukinkbn                             VARCHAR     (1)                                                                 ,  /* （中継用）損傷給付金区分 */
     ztysiboukoudosyougaicd                             VARCHAR     (1)                                                                 ,  /* （中継用）死亡高度障害コード */
     ztysyokikyuuhutandokushrhyj                        VARCHAR     (1)                                                                 ,  /* （中継用）初期給付単独支払表示 */
     ztykakuseikyuuhukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）カク成給付区分 */
     ztysoukikeakyuuhutuusankisu                        VARCHAR     (2)                                                                 ,  /* （中継用）早期ケア給付通算回数 */
     ztysyonendokyuuhuwariai                            VARCHAR     (3)                                                                 ,  /* （中継用）初年度給付割合 */
     ztysyonendosiharaihyj                              VARCHAR     (1)                                                                 ,  /* （中継用）初年度支払表示 */
     ztyyobiv4x2                                        VARCHAR     (4)                                                                 ,  /* （中継用）予備項目Ｖ４＿２ */
     ztykousingohasseihyj                               VARCHAR     (1)                                                                 ,  /* （中継用）更新後発生表示 */
     ztybyoumeicd1                                      VARCHAR     (4)                                                                 ,  /* （中継用）病名コード１ */
     ztybyoumeicd2                                      VARCHAR     (4)                                                                 ,  /* （中継用）病名コード２ */
     ztysaigaigenincd                                   VARCHAR     (1)                                                                 ,  /* （中継用）災害原因コード */
     ztysyougaitoukyuugou                               VARCHAR     (3)                                                                 ,  /* （中継用）障害等級号 */
     ztysyujyutucd                                      VARCHAR     (3)                                                                 ,  /* （中継用）手術コード */
     ztysyujyutumeicd                                   VARCHAR     (3)                                                                 ,  /* （中継用）手術名コード */
     ztytuuinkangogeninkbn                              VARCHAR     (1)                                                                 ,  /* （中継用）通院看護原因区分 */
     ztyundoukisonsyoukbn                               VARCHAR     (1)                                                                 ,  /* （中継用）運動器損傷区分 */
     ztyganmensonsyoukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）顔面損傷区分 */
     ztysonsyougeninkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）損傷原因区分 */
     ztykikensportskbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）危険スポーツ区分 */
     ztyyobiv2x2                                        VARCHAR     (2)                                                                 ,  /* （中継用）予備項目Ｖ２＿２ */
     ztysiharainissuukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）支払日数区分 */
     ztykakuseikatakbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）カク成型区分 */
     ztybosyuukeirokbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）募集経路区分 */
     ztypmenhutanpohyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免不担保表示 */
     ztykousinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）更新区分 */
     ztykusnmetkyksykipjyutuym                          VARCHAR     (6)                                                                 ,  /* （中継用）更新前特約初回Ｐ充当年月 */
     ztytoukeiyousinsakbn                               VARCHAR     (2)                                                                 ,  /* （中継用）統計用診査区分 */
     ztypmenhukakbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）Ｐ免付加区分 */
     ztypmenkbnv2                                       VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ免区分Ｖ２ */
     ztyketteikijyunkanwakbn                            VARCHAR     (1)                                                                 ,  /* （中継用）決定基準緩和区分 */
     ztyhknsyuruikigousedaikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号世代区分 */
     ztytokuyakukigousedaikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）特約記号世代区分 */
     ztysotodasipmenkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ免区分 */
     ztystdssnskbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）外出診査区分 */
     ztysotodasikousinkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）外出更新区分 */
     ztybosyuukeitaikbn                                 VARCHAR     (2)                                                                 ,  /* （中継用）募集形態区分 */
     ztyyobiv5                                          VARCHAR     (5)                                                                 ,  /* （中継用）予備項目Ｖ５ */
     ztyqpackhyj                                        VARCHAR     (1)                                                                 ,  /* （中継用）Ｑパック表示 */
     ztybunkatukbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）分割区分 */
     ztytenkanhosyouminaosikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）転換保障見直区分 */
     ztykousinmaesiharaihyj                             VARCHAR     (1)                                                                 ,  /* （中継用）更新前支払表示 */
     ztydouitunyuuinno                                  VARCHAR     (3)                                                                 ,  /* （中継用）同一入院番号 */
     ztysyujyutujinyuuinkbn                             VARCHAR     (1)                                                                 ,  /* （中継用）手術時入院区分 */
     ztysyujyutusyuruikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）手術種類区分 */
     ztygannyuuinkbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）がん入院区分 */
     ztyhokenhoutekiyouhyouji                           VARCHAR     (1)                                                                 ,  /* （中継用）保険法適用表示 */
     ztysotodasiphkbnmnoshyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ不可分見直表示 */
     ztytokuteijyoutaihushrhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）特定状態不支払表示 */
     ztysisyacd                                         VARCHAR     (3)                                                                 ,  /* （中継用）支社コード */
     ztysykgycd                                         VARCHAR     (3)                                                                 ,  /* （中継用）職業コード */
     ztysuuriyouyobiv11                                 VARCHAR     (11)                                                                ,  /* （中継用）数理用予備項目Ｖ１１ */
     ztyyoukaigojyoutaikaisiymd                         VARCHAR     (8)                                                                 ,  /* （中継用）要介護状態開始年月日 */
     ztyyoukaigojyoutaiendymd                           VARCHAR     (8)                                                                 ,  /* （中継用）要介護状態終了年月日 */
     ztyrendouyousntkjyubbnhyj                          VARCHAR     (1)                                                                 ,  /* （中継用）連動用新特条部分表示 */
     ztymusentakukeiyakukbn                             VARCHAR     (1)                                                                 ,  /* （中継用）無選択契約区分 */
     ztymaruteiskeijihukahyj                            VARCHAR     (1)                                                                 ,  /* （中継用）マル定新契約時付加表示 */
     ztytoliplhyj                                       VARCHAR     (1)                                                                 ,  /* （中継用）ＴＯＬＩＰＬ表示 */
     ztystdssytikbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）外出集定区分 */
     ztyhisei                                           VARCHAR     (1)                                                                 ,  /* （中継用）被性 */
     ztysuuriyobin9                                     NUMBER      (9)                                                                 ,  /* （中継用）数理予備項目Ｎ９ */
     ztysaigaisibousiharaikngk                          NUMBER      (11)                                                                ,  /* （中継用）災害死亡支払金額 */
     ztytokuyakuhinen                                   VARCHAR     (2)                                                                 ,  /* （中継用）特約被年令 */
     ztygnykbttryukyuhkntusnkisu                        NUMBER      (3)                                                                 ,  /* （中継用）がん薬物治療給付金通算回数 */
     ztygansyuruikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）がん種類区分 */
     ztyganyakubutusyuruikbn                            VARCHAR     (1)                                                                 ,  /* （中継用）がん薬物種類区分 */
     ztysyuuroukigjyujtjyutikbn                         VARCHAR     (1)                                                                 ,  /* （中継用）就労介護充実状態区分 */
     ztysyuuroukigjyujtgeninkbn                         VARCHAR     (1)                                                                 ,  /* （中継用）就労介護充実原因区分 */
     ztykigjyujtjyoutaigeninkbn                         VARCHAR     (1)                                                                 ,  /* （中継用）介護充実状態原因区分 */
     ztysykmtssyukahikbn                                VARCHAR     (1)                                                                 ,  /* （中継用）食物摂取可否区分 */
     ztyfktrsmtkahikbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）拭き取り始末可否区分 */
     ztyhokoukahikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）歩行可否区分 */
     ztynyykkahikbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）入浴可否区分 */
     ztyihukutyakudatukahikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）衣服着脱可否区分 */
     ztyngerkahikbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）寝返り可否区分 */
     ztyseiketuseiyoukahikbn                            VARCHAR     (1)                                                                 ,  /* （中継用）清潔整容可否区分 */
     ztynintisyougeninkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）認知症原因区分 */
     ztysyuruhnujyujtjyutikbn                           VARCHAR     (2)                                                                 ,  /* （中継用）就労不能充実状態区分 */
     ztytokuteisyougaikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）特定障害区分 */
     ztydatakanrino2                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号２ */
     ztydatakanrino3                                    VARCHAR     (10)                                                                ,  /* （中継用）データ管理番号３ */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztybluekeizokuhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）Ｂｌｕｅ継続表示 */
     ztyzyrthntiyustatuskbn                             VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分 */
     ztyzyrthntiyustatuskbnx2                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿２ */
     ztyzyrthntiyustatuskbnx3                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿３ */
     ztyzyrthntiyustatuskbnx4                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿４ */
     ztyzyrthntiyustatuskbnx5                           VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分＿５ */
     ztyknkuzusnzyrt                                    VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率 */
     ztyknkuzusnzyrtx2                                  VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率＿２ */
     ztysinkeiyakujivithkhyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）新契約時Ｖｉｔ保険表示 */
     ztypwrbksidhitekiyouhyj                            VARCHAR     (1)                                                                 ,  /* （中継用）保険料割引制度非適用表示 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztysuuriyouyobin4                                  VARCHAR     (4)                                                                 ,  /* （中継用）数理用予備項目Ｎ４ */
     ztyraysystemhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）外貨区分 */
     ztykawaserate                                      NUMBER      (9,6)                                                               ,  /* （中継用）為替レート */
     ztykawaseratetekiyouymd                            VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日 */
     ztykeiyakujiyoteiriritu                            NUMBER      (5,4)                                                               ,  /* （中継用）契約時予定利率 */
     ztygaikadatesiharais                               NUMBER      (11)                                                                ,  /* （中継用）外貨建支払Ｓ */
     ztygaikadatesyukeiyakus                            NUMBER      (11)                                                                ,  /* （中継用）外貨建主契約Ｓ */
     ztygaikadatesyukeiyakup                            NUMBER      (11)                                                                ,  /* （中継用）外貨建主契約Ｐ */
     ztyenkdtsbujsitihsyukngk                           NUMBER      (11)                                                                ,  /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10                                 VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０ */
     ztyyobiv10x2                                       VARCHAR     (10)                                                                ,  /* （中継用）予備項目Ｖ１０＿２ */
     ztymvatyouseigow                                   NUMBER      (11)                                                                ,  /* （中継用）ＭＶＡ調整後Ｗ */
     ztymvakeisanjisknnjynbkn                           NUMBER      (11)                                                                ,  /* （中継用）ＭＶＡ計算時責任準備金 */
     ztyyobiv6                                          VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_KyhknShrJyoukyouRnrkTy ADD CONSTRAINT PK_KyhknShrJyoukyouRnrkTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
