CREATE TABLE ZT_KessanYokukiPRn (
     zrnkeijyouym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）計上年月 */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrnhokensyuruikigouyobi1x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１ */
     zrnhokensyuruikigouyobi1x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿２ */
     zrnhokensyuruikigouyobi1x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿３ */
     zrnhokensyuruikigouyobi1x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿４ */
     zrnhokensyuruikigouyobi1x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿５ */
     zrnhokensyuruikigouyobi1x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿６ */
     zrnhokensyuruikigouyobi1x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿７ */
     zrnhokensyuruikigouyobi1x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿８ */
     zrnhokensyuruikigouyobi1x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿９ */
     zrnhokensyuruikigouyobi1x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１０ */
     zrnhokensyuruikigouyobi1x11                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１１ */
     zrnhokensyuruikigouyobi1x12                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１２ */
     zrnhokensyuruikigouyobi1x13                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１３ */
     zrnhokensyuruikigouyobi1x14                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１４ */
     zrnhokensyuruikigouyobi1x15                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備１＿１５ */
     zrnhokensyuruikigouyobi2x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿１ */
     zrnhokensyuruikigouyobi2x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿２ */
     zrnhokensyuruikigouyobi2x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿３ */
     zrnhokensyuruikigouyobi2x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿４ */
     zrnhokensyuruikigouyobi2x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿５ */
     zrnhokensyuruikigouyobi2x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿６ */
     zrnhokensyuruikigouyobi2x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿７ */
     zrnhokensyuruikigouyobi2x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿８ */
     zrnhokensyuruikigouyobi2x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿９ */
     zrnhokensyuruikigouyobi2x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備２＿１０ */
     zrnhokensyuruikigouyobi3x1                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿１ */
     zrnhokensyuruikigouyobi3x2                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿２ */
     zrnhokensyuruikigouyobi3x3                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿３ */
     zrnhokensyuruikigouyobi3x4                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿４ */
     zrnhokensyuruikigouyobi3x5                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿５ */
     zrnhokensyuruikigouyobi3x6                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿６ */
     zrnhokensyuruikigouyobi3x7                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿７ */
     zrnhokensyuruikigouyobi3x8                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿８ */
     zrnhokensyuruikigouyobi3x9                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿９ */
     zrnhokensyuruikigouyobi3x10                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号予備３＿１０ */
     zrnkeiyakuymd                                      CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約日 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnsyoumetucd                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）消滅コード */
     zrnjikaipjyuutouym                                 CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回Ｐ充当年月 */
     zrnharaikomip                                      NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）払込Ｐ */
     zrnsyukeiyakup                                     NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約Ｐ */
     zrnzennyknmonth                                    NUMBER      (2)                                                       NOT NULL  ,  /* （連携用）前回入金月数 */
     zrnzenyuukinymd                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前回入金年月日 */
     zrnjidoukousinhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）自動更新表示 */
     zrntenkanhyouji                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換表示 */
     zrnhosyouikkatumnoshyouji                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保障一括見直表示 */
     zrnyobi01xv40                                      CHAR        (40)                                                      NOT NULL  ,  /* （連携用）予備０１＿Ｖ４０ */
     zrntkkzkp                                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）特約継続Ｐ */
     zrnkeizokuphurikaekngk                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）継続Ｐ振替金額 */
     zrnkeizokuphurikaekaisiym                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）継続Ｐ振替開始年月 */
     zrnharaikomipannaisaikaiym                         CHAR        (6)                                                       NOT NULL  ,  /* （連携用）払込Ｐ案内再開年月 */
     zrntkkzkkouryokukaisiymd                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）特約継続効力開始年月日 */
     zrnhrimngtkykpjyuutouhoukbn                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払満後特約Ｐ充当方法区分 */
     zrnjkitkpjytym                                     CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回特約Ｐ充当年月 */
     zrnitijibrzugktkp                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）一時払増額特約Ｐ */
     zrnpazukarikingk                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）Ｐ預り金額 */
     zrnzennoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）前納区分 */
     zrnzennoukaisiymd                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前納開始年月日 */
     zrnzennounyuukinymd                                CHAR        (8)                                                       NOT NULL  ,  /* （連携用）前納入金年月日 */
     zrnyokukipbunruicd                                 CHAR        (3)                                                       NOT NULL  ,  /* （連携用）翌期Ｐ分類コード */
     zrnmisyoricd1                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード１ */
     zrnmisyoricd2                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード２ */
     zrnmisyoricd3                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード３ */
     zrnmisyoricd4                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード４ */
     zrnmisyoricd5                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード５ */
     zrnmisyoricd6                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード６ */
     zrnmisyoricd7                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード７ */
     zrnmisyoricd8                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード８ */
     zrnmisyoricd9                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード９ */
     zrnmisyoricd10                                     CHAR        (4)                                                       NOT NULL  ,  /* （連携用）未処理コード１０ */
     zrnyobi02xv39                                      CHAR        (39)                                                      NOT NULL  ,  /* （連携用）予備０２＿Ｖ３９ */
     zrnkbnkeiriyousegmentkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理種類コード */
     zrnhrkkaisuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）払込回数区分 */
     zrnkeiyakunendo                                    CHAR        (4)                                                       NOT NULL  ,  /* （連携用）契約年度 */
     zrnkeiyakum                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約月 */
     zrnharaikatakbn                                    CHAR        (2)                                                       NOT NULL  ,  /* （連携用）払方区分 */
     zrniktyknndp                                       NUMBER      (15)                                                      NOT NULL  ,  /* （連携用）一括払翌年度保険料 */
     zrnkigetumaenyknyknndp                             NUMBER      (15)                                                      NOT NULL  ,  /* （連携用）期月前入金翌年度保険料 */
     zrnyknndpkei                                       NUMBER      (15)                                                      NOT NULL  ,  /* （連携用）翌年度保険料合計 */
     zrnyobi03xn15                                      NUMBER      (15)                                                      NOT NULL  ,  /* （連携用）予備０３＿Ｎ１５ */
     zrnyobi04xv23                                      CHAR        (23)                                                      NOT NULL     /* （連携用）予備０４＿Ｖ２３ */
)
;

ALTER TABLE ZT_KessanYokukiPRn ADD CONSTRAINT PK_KessanYokukiPRn PRIMARY KEY (
     zrnkeijyouym                                             , /* （連携用）計上年月 */
     zrnsyono                                                   /* （連携用）証券番号 */
) ;
