CREATE TABLE ZT_KydGWKykInfoTy (
     ztysyono                                           VARCHAR     (11)                                                      NOT NULL  ,  /* （中継用）証券番号 */
     ztyhknsyurui2keta                                  VARCHAR     (2)                                                                 ,  /* （中継用）保険種類（２桁） */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztysinkeizkkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）新規継続区分 */
     ztysyuhosyucd                                      VARCHAR     (7)                                                                 ,  /* （中継用）主契約保種コード */
     ztymdhnaisyoumeicd                                 VARCHAR     (3)                                                                 ,  /* （中継用）窓販用愛称名コード */
     ztysyouhncd                                        VARCHAR     (2)                                                                 ,  /* （中継用）商品コード */
     ztymusymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）申込年月日 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztykykseirituymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）契約成立年月日 */
     ztysekininkaisiymd                                 VARCHAR     (8)                                                                 ,  /* （中継用）責任開始年月日 */
     ztysyokaipymd                                      VARCHAR     (8)                                                                 ,  /* （中継用）初回Ｐ入金年月日 */
     ztyhjnkojinkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）法人個人区分 */
     ztyhrkkeirokbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）払込経路区分 */
     ztyhrkhuhukbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）払込方法区分 */
     ztyhrkymd                                          VARCHAR     (2)                                                                 ,  /* （中継用）払込日 */
     ztygoukeip2                                        NUMBER      (11)                                                                ,  /* （中継用）合計保険料２ */
     ztyitijibrp                                        NUMBER      (11)                                                                ,  /* （中継用）一時払保険料 */
     ztybnkaisuu                                        VARCHAR     (2)                                                                 ,  /* （中継用）分割回数 */
     ztybnsyuruikbn                                     VARCHAR     (2)                                                                 ,  /* （中継用）分割種類区分 */
     ztybnkyk1kaip                                      NUMBER      (11)                                                                ,  /* （中継用）分割払契約１回分保険料 */
     ztyyobiv20                                         VARCHAR     (20)                                                                ,  /* （中継用）予備項目Ｖ２０ */
     ztysyuhknkknkbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）主契約保険期間区分 */
     ztysyuhknkkn                                       VARCHAR     (2)                                                                 ,  /* （中継用）主契約保険期間 */
     ztysyuhrkkknkbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）主契約払込期間区分 */
     ztysyuhrkkkn                                       VARCHAR     (2)                                                                 ,  /* （中継用）主契約払込期間 */
     ztysyus                                            NUMBER      (11)                                                                ,  /* （中継用）主契約保険金額 */
     ztysyunm                                           VARCHAR     (8)                                                                 ,  /* （中継用）主契約名称 */
     ztyidojiyukbn                                      VARCHAR     (2)                                                                 ,  /* （中継用）異動事由区分 */
     ztysyoumetucd                                      VARCHAR     (4)                                                                 ,  /* （中継用）消滅コード */
     ztyidokaiyakuymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）異動解約年月日 */
     ztymankiymd                                        VARCHAR     (8)                                                                 ,  /* （中継用）満期年月日 */
     ztysibous                                          NUMBER      (11)                                                                ,  /* （中継用）死亡Ｓ */
     ztyidoukaiyakup                                    NUMBER      (11)                                                                ,  /* （中継用）異動解約保険料 */
     ztysyukinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）集金区分 */
     ztyhaitoukbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）配当区分 */
     ztycreditcardhrkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）クレジットカード払区分 */
     ztytkjykbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）特条区分 */
     ztysinsakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）診査区分 */
     ztyzeiseitekikakuhyj                               VARCHAR     (1)                                                                 ,  /* （中継用）税制適格表示 */
     ztylivhukauhyj                                     VARCHAR     (1)                                                                 ,  /* （中継用）リビングニーズ付加表示 */
     ztyhrizmentyouhyj                                  VARCHAR     (1)                                                                 ,  /* （中継用）払済延長表示 */
     ztykisokyknkshrhsykn                               VARCHAR     (2)                                                                 ,  /* （中継用）基礎契約年金支払保証期間 */
     ztynkshrkknkbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）年金支払期間区分 */
     ztynkshrkknnen                                     VARCHAR     (3)                                                                 ,  /* （中継用）年金支払期間年 */
     ztynksueokikn                                      VARCHAR     (2)                                                                 ,  /* （中継用）年金据置期間 */
     ztynkshrstartymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）年金支払開始年月日 */
     ztynkuketorininkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）年金受取人区分 */
     ztyzennoup                                         NUMBER      (11)                                                                ,  /* （中継用）前納保険料 */
     ztyzennouendym                                     VARCHAR     (6)                                                                 ,  /* （中継用）前納終了年月 */
     ztyteikaiyakuhrkn                                  VARCHAR     (2)                                                                 ,  /* （中継用）低解約返戻金期間 */
     ztymosno                                           VARCHAR     (9)                                                                 ,  /* （中継用）申込番号 */
     ztytratkisyacd1                                    VARCHAR     (6)                                                                 ,  /* （中継用）取扱者コード１ */
     ztytratkisyacd2                                    VARCHAR     (6)                                                                 ,  /* （中継用）取扱者コード２ */
     ztydairiten1cd                                     VARCHAR     (7)                                                                 ,  /* （中継用）代理店１コード */
     ztydairiten2cd                                     VARCHAR     (7)                                                                 ,  /* （中継用）代理店２コード */
     ztybsudirtnatkikeitaikbn                           VARCHAR     (1)                                                                 ,  /* （中継用）募集代理店扱形態区分 */
     ztybsyudiritnatkiwari1                             NUMBER      (3)                                                                 ,  /* （中継用）募集代理店扱割合１ */
     ztybsyudiritnatkiwari2                             NUMBER      (3)                                                                 ,  /* （中継用）募集代理店扱割合２ */
     ztyyobiv20x2                                       VARCHAR     (20)                                                                ,  /* （中継用）予備項目Ｖ２０＿２ */
     ztytktyuutohukahyj                                 VARCHAR     (1)                                                                 ,  /* （中継用）特約中途付加表示 */
     ztytksuu                                           VARCHAR     (3)                                                                 ,  /* （中継用）特約数 */
     ztytkhosyucd1                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード１ */
     ztytknm1                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称１ */
     ztytks1                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額１ */
     ztytkhknkknkbn1                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分１ */
     ztytkhknkkn1                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間１ */
     ztytkhrkkknkbn1                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分１ */
     ztytkhrkkkn1                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間１ */
     ztytkhosyucd2                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード２ */
     ztytknm2                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称２ */
     ztytks2                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額２ */
     ztytkhknkknkbn2                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分２ */
     ztytkhknkkn2                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間２ */
     ztytkhrkkknkbn2                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分２ */
     ztytkhrkkkn2                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間２ */
     ztytkhosyucd3                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード３ */
     ztytknm3                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称３ */
     ztytks3                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額３ */
     ztytkhknkknkbn3                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分３ */
     ztytkhknkkn3                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間３ */
     ztytkhrkkknkbn3                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分３ */
     ztytkhrkkkn3                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間３ */
     ztytkhosyucd4                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード４ */
     ztytknm4                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称４ */
     ztytks4                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額４ */
     ztytkhknkknkbn4                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分４ */
     ztytkhknkkn4                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間４ */
     ztytkhrkkknkbn4                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分４ */
     ztytkhrkkkn4                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間４ */
     ztytkhosyucd5                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード５ */
     ztytknm5                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称５ */
     ztytks5                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額５ */
     ztytkhknkknkbn5                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分５ */
     ztytkhknkkn5                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間５ */
     ztytkhrkkknkbn5                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分５ */
     ztytkhrkkkn5                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間５ */
     ztytkhosyucd6                                      VARCHAR     (7)                                                                 ,  /* （中継用）特約保種コード６ */
     ztytknm6                                           VARCHAR     (8)                                                                 ,  /* （中継用）特約名称６ */
     ztytks6                                            NUMBER      (11)                                                                ,  /* （中継用）特約保険金額６ */
     ztytkhknkknkbn6                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約保険期間区分６ */
     ztytkhknkkn6                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約保険期間６ */
     ztytkhrkkknkbn6                                    VARCHAR     (1)                                                                 ,  /* （中継用）特約払込期間区分６ */
     ztytkhrkkkn6                                       VARCHAR     (2)                                                                 ,  /* （中継用）特約払込期間６ */
     ztysbuktnm                                         VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名 */
     ztykjsbuktnm                                       VARCHAR     (15)                                                                ,  /* （中継用）漢字死亡受取人名 */
     ztysbukttdk                                        VARCHAR     (2)                                                                 ,  /* （中継用）死亡受取人続柄 */
     ztysbuktnin                                        VARCHAR     (2)                                                                 ,  /* （中継用）死亡受取人人数 */
     ztyyobiv28                                         VARCHAR     (28)                                                                ,  /* （中継用）予備項目Ｖ２８ */
     ztyyno7keta                                        VARCHAR     (7)                                                                 ,  /* （中継用）郵便番号（７桁） */
     ztytelnokydgw                                      VARCHAR     (14)                                                                ,  /* （中継用）電話番号（共同ＧＷ） */
     ztykyknmknkydgw                                    VARCHAR     (18)                                                                ,  /* （中継用）契約者名（カナ）（共同ＧＷ） */
     ztykyksyaseiymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）契約者生年月日 */
     ztykyksyaseikbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）契約者性別区分 */
     ztytsinkihontikucd                                 VARCHAR     (8)                                                                 ,  /* （中継用）通信先基本地区コード */
     ztykykadrkj50                                      VARCHAR     (50)                                                                ,  /* （中継用）契約者漢字住所５０ */
     ztykyknmkjkydgw                                    VARCHAR     (15)                                                                ,  /* （中継用）契約者名（漢字）（共同ＧＷ） */
     ztyhhknmei                                         VARCHAR     (18)                                                                ,  /* （中継用）被保険者名 */
     ztyhhknnmkj                                        VARCHAR     (15)                                                                ,  /* （中継用）被保険者名（漢字） */
     ztyhhknseiymd                                      VARCHAR     (8)                                                                 ,  /* （中継用）被保険者生年月日 */
     ztyhhknnen                                         VARCHAR     (3)                                                                 ,  /* （中継用）被保険者年齢 */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhhkntdk                                         VARCHAR     (2)                                                                 ,  /* （中継用）被保険者続柄 */
     ztykzsyurui                                        VARCHAR     (1)                                                                 ,  /* （中継用）口座種類 */
     ztykouzano7keta                                    VARCHAR     (7)                                                                 ,  /* （中継用）口座番号（７桁） */
     ztykzhurikaebankcd                                 VARCHAR     (4)                                                                 ,  /* （中継用）口座振替銀行番号 */
     ztykzhurikaesitencd                                VARCHAR     (3)                                                                 ,  /* （中継用）口座振替支店番号 */
     ztykanyuusyaknrno                                  VARCHAR     (15)                                                                ,  /* （中継用）加入者管理番号 */
     ztykyksiboumeighnkhyj                              VARCHAR     (1)                                                                 ,  /* （中継用）契約者死亡名義変更表示 */
     ztyyobiv11                                         VARCHAR     (11)                                                                ,  /* （中継用）予備項目Ｖ１１ */
     ztymnkuktkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）満期受取人区分 */
     ztymnkuktnm1                                       VARCHAR     (18)                                                                ,  /* （中継用）満期受取人名１ */
     ztymnkuktnm2                                       VARCHAR     (18)                                                                ,  /* （中継用）満期受取人名２ */
     ztymnkuktnm3                                       VARCHAR     (18)                                                                ,  /* （中継用）満期受取人名３ */
     ztymnkuktnm4                                       VARCHAR     (18)                                                                ,  /* （中継用）満期受取人名４ */
     ztysbuktkbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）死亡受取人区分 */
     ztysbuktnm1                                        VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名１ */
     ztysbuktnm2                                        VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名２ */
     ztysbuktnm3                                        VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名３ */
     ztysbuktnm4                                        VARCHAR     (18)                                                                ,  /* （中継用）死亡受取人名４ */
     ztyyobiv20x3                                       VARCHAR     (20)                                                                ,  /* （中継用）予備項目Ｖ２０＿３ */
     ztysyoriymd                                        VARCHAR     (8)                                                       NOT NULL  ,  /* （中継用）処理年月日 */
     ztykykmfksnctrlkh                                  NUMBER      (7)                                                       NOT NULL  ,  /* （中継用）契約ＭＦ更新ＣＴＲ（保全） */
     ztymkhtoutatuymd                                   VARCHAR     (8)                                                                 ,  /* （中継用）目標到達年月日 */
     ztykykhrkmtuuka                                    VARCHAR     (5)                                                                 ,  /* （中継用）契約者振込通貨 */
     ztykykhrkmgk                                       NUMBER      (11)                                                                ,  /* （中継用）契約者振込金額 */
     ztyikkatubaraikbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）一括払区分 */
     ztyikkatubaraikaisuu                               VARCHAR     (2)                                                                 ,  /* （中継用）一括払回数 */
     ztytousyokykjiyennyknrate                          NUMBER      (7,2)                                                               ,  /* （中継用）当初契約時円入金レート */
     ztyrendouritu                                      NUMBER      (5,4)                                                               ,  /* （中継用）連動率 */
     ztyteikishrritu                                    NUMBER      (5,4)                                                               ,  /* （中継用）定期支払率 */
     ztyyobiv25                                         VARCHAR     (25)                                                                ,  /* （中継用）予備項目Ｖ２５ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_KydGWKykInfoTy ADD CONSTRAINT PK_KydGWKykInfoTy PRIMARY KEY (
     ztysyono                                                 , /* （中継用）証券番号 */
     ztysyoriymd                                              , /* （中継用）処理年月日 */
     ztykykmfksnctrlkh                                          /* （中継用）契約ＭＦ更新ＣＴＲ（保全） */
) ;
