CREATE TABLE ZT_KyhknShrJyoukyouRnrkRn (
     zrnsequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnyobiv12                                         CHAR        (12)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１２ */
     zrndatakanrino                                     CHAR        (11)                                                      NOT NULL  ,  /* （連携用）データ管理番号 */
     zrnyobiv4                                          CHAR        (4)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ４ */
     zrntksyukgu                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約種類記号 */
     zrntokuyakugatakbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約型区分 */
     zrntokuyakukisi                                    CHAR        (8)                                                       NOT NULL  ,  /* （連携用）特約期始 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrntyuutohukakbn                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）中途付加区分 */
     zrnhyoukataikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）標下体区分 */
     zrnatukaisisyatodouhukencd                         CHAR        (2)                                                       NOT NULL  ,  /* （連携用）扱支社都道府県コード */
     zrntokuyakusinkyuukbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約新旧区分 */
     zrnbsyym                                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）募集年月 */
     zrntkykdai2hihokensyahyj                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約第２被保険者表示 */
     zrntokuteisippeisethyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定疾病セット表示 */
     zrnjyusyousyaseibetukbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）受傷者性別区分 */
     zrnkazokujyusyousyakbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）家族受傷者区分 */
     zrnkeiyakunen                                      CHAR        (2)                                                       NOT NULL  ,  /* （連携用）契約年令 */
     zrnmannenreihyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）満年令表示 */
     zrnhhknnentysihyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者年令調整表示 */
     zrnyobiv2                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２ */
     zrnkyuuhukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）給付区分 */
     zrnsiharaijyoutaikbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払状態区分 */
     zrnsyouincd                                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）消因コード */
     zrnjikohasseiymd2                                  CHAR        (8)                                                       NOT NULL  ,  /* （連携用）事故発生年月日 */
     zrnsyougaikoteiymd                                 CHAR        (8)                                                       NOT NULL  ,  /* （連携用）傷害固定年月日 */
     zrnnyuuinymd                                       CHAR        (8)                                                       NOT NULL  ,  /* （連携用）入院年月日 */
     zrnshrymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）支払年月日 */
     zrnkyuuhuwariai                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）給付割合 */
     zrnsiharaikingakun9                                NUMBER      (9)                                                       NOT NULL  ,  /* （連携用）支払金額Ｎ９ */
     zrnkyoukaihoukokuyoukingaku                        NUMBER      (9)                                                       NOT NULL  ,  /* （連携用）協会報告用金額 */
     zrntuuinkakujyuuhukakbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）通院カク充付加区分 */
     zrnkangohukahyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）看護付加表示 */
     zrnsonsyoukyuuhukinkbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）損傷給付金区分 */
     zrnsiboukoudosyougaicd                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）死亡高度障害コード */
     zrnsyokikyuuhutandokushrhyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）初期給付単独支払表示 */
     zrnkakuseikyuuhukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カク成給付区分 */
     zrnsoukikeakyuuhutuusankisu                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）早期ケア給付通算回数 */
     zrnsyonendokyuuhuwariai                            CHAR        (3)                                                       NOT NULL  ,  /* （連携用）初年度給付割合 */
     zrnsyonendosiharaihyj                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）初年度支払表示 */
     zrnyobiv4x2                                        CHAR        (4)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ４＿２ */
     zrnkousingohasseihyj                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新後発生表示 */
     zrnbyoumeicd1                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）病名コード１ */
     zrnbyoumeicd2                                      CHAR        (4)                                                       NOT NULL  ,  /* （連携用）病名コード２ */
     zrnsaigaigenincd                                   CHAR        (1)                                                       NOT NULL  ,  /* （連携用）災害原因コード */
     zrnsyougaitoukyuugou                               CHAR        (3)                                                       NOT NULL  ,  /* （連携用）障害等級号 */
     zrnsyujyutucd                                      CHAR        (3)                                                       NOT NULL  ,  /* （連携用）手術コード */
     zrnsyujyutumeicd                                   CHAR        (3)                                                       NOT NULL  ,  /* （連携用）手術名コード */
     zrntuuinkangogeninkbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）通院看護原因区分 */
     zrnundoukisonsyoukbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）運動器損傷区分 */
     zrnganmensonsyoukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）顔面損傷区分 */
     zrnsonsyougeninkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）損傷原因区分 */
     zrnkikensportskbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）危険スポーツ区分 */
     zrnyobiv2x2                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ２＿２ */
     zrnsiharainissuukbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払日数区分 */
     zrnkakuseikatakbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）カク成型区分 */
     zrnbosyuukeirokbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）募集経路区分 */
     zrnpmenhutanpohyj                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免不担保表示 */
     zrnkousinkbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新区分 */
     zrnkusnmetkyksykipjyutuym                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）更新前特約初回Ｐ充当年月 */
     zrntoukeiyousinsakbn                               CHAR        (2)                                                       NOT NULL  ,  /* （連携用）統計用診査区分 */
     zrnpmenhukakbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｐ免付加区分 */
     zrnpmenkbnv2                                       CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ免区分Ｖ２ */
     zrnketteikijyunkanwakbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）決定基準緩和区分 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrntokuyakukigousedaikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特約記号世代区分 */
     zrnsotodasipmenkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ免区分 */
     zrnstdssnskbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出診査区分 */
     zrnsotodasikousinkbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出更新区分 */
     zrnbosyuukeitaikbn                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）募集形態区分 */
     zrnyobiv5                                          CHAR        (5)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ５ */
     zrnqpackhyj                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｑパック表示 */
     zrnbunkatukbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）分割区分 */
     zrntenkanhosyouminaosikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）転換保障見直区分 */
     zrnkousinmaesiharaihyj                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）更新前支払表示 */
     zrndouitunyuuinno                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）同一入院番号 */
     zrnsyujyutujinyuuinkbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手術時入院区分 */
     zrnsyujyutusyuruikbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）手術種類区分 */
     zrngannyuuinkbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）がん入院区分 */
     zrnhokenhoutekiyouhyouji                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険法適用表示 */
     zrnsotodasiphkbnmnoshyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ不可分見直表示 */
     zrntokuteijyoutaihushrhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定状態不支払表示 */
     zrnsisyacd                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支社コード */
     zrnsykgycd                                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）職業コード */
     zrnsuuriyouyobiv11                                 CHAR        (11)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｖ１１ */
     zrnyoukaigojyoutaikaisiymd                         CHAR        (8)                                                       NOT NULL  ,  /* （連携用）要介護状態開始年月日 */
     zrnyoukaigojyoutaiendymd                           CHAR        (8)                                                       NOT NULL  ,  /* （連携用）要介護状態終了年月日 */
     zrnrendouyousntkjyubbnhyj                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）連動用新特条部分表示 */
     zrnmusentakukeiyakukbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）無選択契約区分 */
     zrnmaruteiskeijihukahyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）マル定新契約時付加表示 */
     zrntoliplhyj                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＴＯＬＩＰＬ表示 */
     zrnstdssytikbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出集定区分 */
     zrnhisei                                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被性 */
     zrnsuuriyobin9                                     NUMBER      (9)                                                       NOT NULL  ,  /* （連携用）数理予備項目Ｎ９ */
     zrnsaigaisibousiharaikngk                          NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）災害死亡支払金額 */
     zrntokuyakuhinen                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）特約被年令 */
     zrngnykbttryukyuhkntusnkisu                        NUMBER      (3)                                                       NOT NULL  ,  /* （連携用）がん薬物治療給付金通算回数 */
     zrngansyuruikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）がん種類区分 */
     zrnganyakubutusyuruikbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）がん薬物種類区分 */
     zrnsyuuroukigjyujtjyutikbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）就労介護充実状態区分 */
     zrnsyuuroukigjyujtgeninkbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）就労介護充実原因区分 */
     zrnkigjyujtjyoutaigeninkbn                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）介護充実状態原因区分 */
     zrnsykmtssyukahikbn                                CHAR        (1)                                                       NOT NULL  ,  /* （連携用）食物摂取可否区分 */
     zrnfktrsmtkahikbn                                  CHAR        (1)                                                       NOT NULL  ,  /* （連携用）拭き取り始末可否区分 */
     zrnhokoukahikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）歩行可否区分 */
     zrnnyykkahikbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）入浴可否区分 */
     zrnihukutyakudatukahikbn                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）衣服着脱可否区分 */
     zrnngerkahikbn                                     CHAR        (1)                                                       NOT NULL  ,  /* （連携用）寝返り可否区分 */
     zrnseiketuseiyoukahikbn                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）清潔整容可否区分 */
     zrnnintisyougeninkbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）認知症原因区分 */
     zrnsyuruhnujyujtjyutikbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）就労不能充実状態区分 */
     zrntokuteisyougaikbn                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）特定障害区分 */
     zrndatakanrino2                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号２ */
     zrndatakanrino3                                    CHAR        (10)                                                      NOT NULL  ,  /* （連携用）データ管理番号３ */
     zrnknkuzusnzyrttekitkarihyj                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）健康増進乗率適用特約有表示 */
     zrnbluekeizokuhyouji                               CHAR        (1)                                                       NOT NULL  ,  /* （連携用）Ｂｌｕｅ継続表示 */
     zrnzyrthntiyustatuskbn                             CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分 */
     zrnzyrthntiyustatuskbnx2                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿２ */
     zrnzyrthntiyustatuskbnx3                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿３ */
     zrnzyrthntiyustatuskbnx4                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿４ */
     zrnzyrthntiyustatuskbnx5                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）乗率判定用ステータス区分＿５ */
     zrnknkuzusnzyrt                                    CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率 */
     zrnknkuzusnzyrtx2                                  CHAR        (3)                                                       NOT NULL  ,  /* （連携用）健康増進乗率＿２ */
     zrnsinkeiyakujivithkhyouji                         CHAR        (1)                                                       NOT NULL  ,  /* （連携用）新契約時Ｖｉｔ保険表示 */
     zrnpwrbksidhitekiyouhyj                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険料割引制度非適用表示 */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnsuuriyouyobin4                                  CHAR        (4)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ４ */
     zrnraysystemhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＲＡＹシステム表示 */
     zrngaikakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外貨区分 */
     zrnkawaserate                                      NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）為替レート */
     zrnkawaseratetekiyouymd                            CHAR        (8)                                                       NOT NULL  ,  /* （連携用）為替レート適用年月日 */
     zrnkeiyakujiyoteiriritu                            NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）契約時予定利率 */
     zrngaikadatesiharais                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建支払Ｓ */
     zrngaikadatesyukeiyakus                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建主契約Ｓ */
     zrngaikadatesyukeiyakup                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建主契約Ｐ */
     zrnenkdtsbujsitihsyukngk                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）円貨建死亡時最低保証金額 */
     zrnsuuriyouyobin10                                 CHAR        (10)                                                      NOT NULL  ,  /* （連携用）数理用予備項目Ｎ１０ */
     zrnyobiv10x2                                       CHAR        (10)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１０＿２ */
     zrnmvatyouseigow                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ調整後Ｗ */
     zrnmvakeisanjisknnjynbkn                           NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）ＭＶＡ計算時責任準備金 */
     zrnyobiv6                                          CHAR        (6)                                                       NOT NULL     /* （連携用）予備項目Ｖ６ */
)
;

ALTER TABLE ZT_KyhknShrJyoukyouRnrkRn ADD CONSTRAINT PK_KyhknShrJyoukyouRnrkRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
