CREATE TABLE ZT_KaiykHrSoutougakuTy (
     ztysequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztyyobiv12                                         VARCHAR     (12)                                                                ,  /* （中継用）予備項目Ｖ１２ */
     ztykeisankijyunym                                  VARCHAR     (6)                                                                 ,  /* （中継用）計算基準年月 */
     ztydatakanrino                                     VARCHAR     (11)                                                                ,  /* （中継用）データ管理番号 */
     ztysyutkkbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）主契約特約区分 */
     ztysuurisyuruicd                                   VARCHAR     (2)                                                                 ,  /* （中継用）数理種類コード */
     ztykbnkeiriyousegmentkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用利源分析区分 */
     ztyharaikatakbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）払方区分 */
     ztytenkanitijibaraikbn                             VARCHAR     (1)                                                                 ,  /* （中継用）転換一時払区分 */
     ztytyuutohukahyouji                                VARCHAR     (1)                                                                 ,  /* （中継用）中途付加表示 */
     ztysuuriyouyobin6                                  VARCHAR     (6)                                                                 ,  /* （中継用）数理用予備項目Ｎ６ */
     ztyyobiv6x2                                        VARCHAR     (6)                                                                 ,  /* （中継用）予備項目Ｖ６＿２ */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztyhknsyuruikigousedaikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号世代区分 */
     ztysotodasipmenkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ免区分 */
     ztysotodasikousinkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）外出更新区分 */
     ztysotodasimanagehyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）外出満年令表示 */
     ztysotodasiphkbnmnoshyouji                         VARCHAR     (1)                                                                 ,  /* （中継用）外出Ｐ不可分見直表示 */
     ztyknkuzusnzyrttekitkarihyj                        VARCHAR     (1)                                                                 ,  /* （中継用）健康増進乗率適用特約有表示 */
     ztyhokensyuruikigouyobi                            VARCHAR     (5)                                                                 ,  /* （中継用）保険種類記号予備 */
     ztytokuyakugatakbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）特約型区分 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyryouritukbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）料率区分 */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2                                 VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令Ｖ２ */
     ztykyksyanen                                       VARCHAR     (2)                                                                 ,  /* （中継用）契約者年令 */
     ztyhknkkn                                          VARCHAR     (2)                                                                 ,  /* （中継用）保険期間 */
     ztyphrkkikn                                        VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）才満期契約表示 */
     ztytkbthsyumnryuhyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）特別保障満了表示 */
     ztynknshry                                         VARCHAR     (2)                                                                 ,  /* （中継用）年金支払期間 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztykykjyoutai                                      VARCHAR     (1)                                                                 ,  /* （中継用）契約状態 */
     ztyharaizumientyoujiage                            VARCHAR     (2)                                                                 ,  /* （中継用）払済延長時年令 */
     ztyentyoukikan                                     VARCHAR     (4)                                                                 ,  /* （中継用）延長期間 */
     ztysiteimpbairitu                                  VARCHAR     (2)                                                                 ,  /* （中継用）指定月Ｐ倍率 */
     ztypwarimasisiteim1                                VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ割増指定月１ */
     ztypwarimasisiteim2                                VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ割増指定月２ */
     ztysaisyuusiteiym                                  VARCHAR     (6)                                                                 ,  /* （中継用）最終指定年月 */
     ztyseizonkyuuhukinshrmd                            VARCHAR     (4)                                                                 ,  /* （中継用）生存給付支払月日 */
     ztykeikanensuu                                     VARCHAR     (2)                                                                 ,  /* （中継用）経過年数 */
     ztykeikatukisuu                                    VARCHAR     (2)                                                                 ,  /* （中継用）経過月数 */
     ztyjikaipjyuutouym                                 VARCHAR     (6)                                                                 ,  /* （中継用）次回Ｐ充当年月 */
     ztytnknhktgkujyarhyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）転換引継控除有表示 */
     ztytokuyakukbn                                     VARCHAR     (1)                                                                 ,  /* （中継用）特約区分 */
     ztytokuyakuno                                      VARCHAR     (2)                                                                 ,  /* （中継用）特約番号 */
     ztydi2hknkknikoujihisyaage                         VARCHAR     (2)                                                                 ,  /* （中継用）第２保険期間移行時被者年令 */
     ztyrecordno                                        VARCHAR     (2)                                                                 ,  /* （中継用）レコード番号 */
     ztymfkuriagekurisagekbn                            VARCHAR     (1)                                                                 ,  /* （中継用）ＭＦ繰上げ繰下げ区分 */
     ztymfannaihuyouriyuukbn                            VARCHAR     (2)                                                                 ,  /* （中継用）ＭＦ案内不要理由区分 */
     ztyhrizmjhknsyukigousdkbn                          VARCHAR     (1)                                                                 ,  /* （中継用）払済時保険種類記号世代区分 */
     ztyhokenhoutekiyouhyouji                           VARCHAR     (1)                                                                 ,  /* （中継用）保険法適用表示 */
     ztytokubetuhosyoukikan                             VARCHAR     (2)                                                                 ,  /* （中継用）特別保障期間 */
     ztysintokujyouhyouji                               VARCHAR     (1)                                                                 ,  /* （中継用）新特条表示 */
     ztytkjykbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）特条区分 */
     ztyryoumasihyouten                                 NUMBER      (5)                                                                 ,  /* （中継用）料増標点 */
     ztydai2tokujyoukbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）第２特条区分 */
     ztydai2ryoumasihyouten                             NUMBER      (5)                                                                 ,  /* （中継用）第２料増標点 */
     ztyytirrthndsysnmnskaisuu                          VARCHAR     (1)                                                                 ,  /* （中継用）予定利率変動終身見直回数 */
     ztykousinmanryouage                                VARCHAR     (2)                                                                 ,  /* （中継用）更新満了年令 */
     ztysuuriyouyobin9                                  VARCHAR     (9)                                                                 ,  /* （中継用）数理用予備項目Ｎ９ */
     ztykrsgjhknsyukigousdkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）繰下げ時保険種類記号世代区分 */
     ztyknkuzusnzyrt                                    VARCHAR     (3)                                                                 ,  /* （中継用）健康増進乗率 */
     ztyzyrthntiyustatuskbn                             VARCHAR     (1)                                                                 ,  /* （中継用）乗率判定用ステータス区分 */
     ztyyobiv15                                         VARCHAR     (15)                                                                ,  /* （中継用）予備項目Ｖ１５ */
     ztyerrtokuteikoumoku                               VARCHAR     (10)                                                                ,  /* （中継用）エラー特定項目 */
     ztykihons                                          NUMBER      (11)                                                                ,  /* （中継用）基本Ｓ */
     ztyhenkougokihons                                  NUMBER      (11)                                                                ,  /* （中継用）変更後基本Ｓ */
     ztyhenkougosibous                                  NUMBER      (11)                                                                ,  /* （中継用）変更後死亡Ｓ */
     ztygyousekihyoujis                                 NUMBER      (11)                                                                ,  /* （中継用）業績表示Ｓ */
     ztygoukeitenkankakaku                              NUMBER      (11)                                                                ,  /* （中継用）合計転換価格 */
     ztywnasigoukeitenkanteikis                         NUMBER      (11)                                                                ,  /* （中継用）Ｗなし合計転換定期Ｓ */
     ztyyobin11                                         NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２ */
     ztykaiyakuhr                                       NUMBER      (11)                                                                ,  /* （中継用）解約返戻金 */
     ztyryumsbbnkaiyakuhr                               NUMBER      (11)                                                                ,  /* （中継用）料増部分解約返戻金 */
     ztyyobin11x3                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿３ */
     ztyyobin11x4                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿４ */
     ztyraysystemhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）外貨区分 */
     ztykawaserate                                      NUMBER      (9,6)                                                               ,  /* （中継用）為替レート */
     ztykawaseratetekiyouymd                            VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日 */
     ztysaisinyoteiriritu                               NUMBER      (5,4)                                                               ,  /* （中継用）最新予定利率 */
     ztysrkaiyakusjkkktyouseirrt                        NUMBER      (5,4)                                                               ,  /* （中継用）数理用解約時市場価格調整用利率 */
     ztysrkyksjkkktyouseiriritu                         NUMBER      (5,4)                                                               ,  /* （中継用）数理用契約時市場価格調整用利率 */
     ztymvakeisankijyunymd                              VARCHAR     (8)                                                                 ,  /* （中継用）ＭＶＡ計算基準年月日 */
     ztymvatyouseikou                                   NUMBER      (5,4)                                                               ,  /* （中継用）ＭＶＡ調整項 */
     ztykeiyakujiyoteiriritu                            NUMBER      (5,4)                                                               ,  /* （中継用）契約時予定利率 */
     ztysuuriyouyobin10                                 VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０ */
     ztysuuriyouyobin10x2                               VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０＿２ */
     ztyyobin11x5                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿５ */
     ztyyobin11x6                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿６ */
     ztyyobin11x7                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿７ */
     ztyyobin11x8                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿８ */
     ztyyobin11x9                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿９ */
     ztyyobiv12x2                                       VARCHAR     (12)                                                                ,  /* （中継用）予備項目Ｖ１２＿２ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_KaiykHrSoutougakuTy ADD CONSTRAINT PK_KaiykHrSoutougakuTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
