CREATE TABLE ZT_RrtHndugtHknVKnsyuyuRn (
     zrnsequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （連携用）シーケンス番号 */
     zrnyuukourecordlength                              NUMBER      (7)                                                       NOT NULL  ,  /* （連携用）有効レコード長 */
     zrnrdwarea                                         CHAR        (4)                                                       NOT NULL  ,  /* （連携用）ＲＤＷ領域 */
     zrnkeijyouym                                       CHAR        (6)                                                       NOT NULL  ,  /* （連携用）計上年月 */
     zrnraysystemhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）ＲＡＹシステム表示 */
     zrndatakanrino                                     CHAR        (11)                                                      NOT NULL  ,  /* （連携用）データ管理番号 */
     zrnhknsyukigou                                     CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険種類記号 */
     zrnhknsyuruikigousedaikbn                          CHAR        (1)                                                       NOT NULL  ,  /* （連携用）保険種類記号世代区分 */
     zrnsotodasipmenkbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出Ｐ免区分 */
     zrnsotodasimanagehyouji                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外出満年令表示 */
     zrnsuuriyouyobin6                                  CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６ */
     zrnyobiv12                                         CHAR        (12)                                                      NOT NULL  ,  /* （連携用）予備項目Ｖ１２ */
     zrnkbnkeiriyousegmentkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用セグメント区分 */
     zrnkbnkeiriyourgnbnskkbn                           CHAR        (2)                                                       NOT NULL  ,  /* （連携用）区分経理用利源分析区分 */
     zrnsuurisyuruicd                                   CHAR        (2)                                                       NOT NULL  ,  /* （連携用）数理種類コード */
     zrnsuuriyouyobin6x2                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６＿２ */
     zrnyobiv8                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ８ */
     zrnkykymd                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）契約年月日 */
     zrnhknkkn                                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）保険期間 */
     zrnphrkkikn                                        CHAR        (2)                                                       NOT NULL  ,  /* （連携用）Ｐ払込期間 */
     zrnsaimnkkykhyj                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）才満期契約表示 */
     zrnannaifuyouriyuukbn                              CHAR        (2)                                                       NOT NULL  ,  /* （連携用）案内不要理由区分 */
     zrnhhknseikbn                                      CHAR        (1)                                                       NOT NULL  ,  /* （連携用）被保険者性別区分 */
     zrnhihokensyaagev2                                 CHAR        (2)                                                       NOT NULL  ,  /* （連携用）被保険者年令Ｖ２ */
     zrnkuriagekurisagekbn                              CHAR        (1)                                                       NOT NULL  ,  /* （連携用）繰上げ繰下げ区分 */
     zrnsyukeiyakupwaribikikbn                          CHAR        (2)                                                       NOT NULL  ,  /* （連携用）主契約Ｐ割引区分 */
     zrnjikaipjyuutouym2                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）次回Ｐ充当年月２ */
     zrnsyokainyknjikawasekjnymd                        CHAR        (8)                                                       NOT NULL  ,  /* （連携用）初回入金時為替基準年月日 */
     zrnsuuriyouyobin6x3                                CHAR        (6)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ６＿３ */
     zrnyobiv7                                          CHAR        (7)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ７ */
     zrngaikakbn                                        CHAR        (1)                                                       NOT NULL  ,  /* （連携用）外貨区分 */
     zrnkimatukawaserate                                NUMBER      (9,6)                                                     NOT NULL  ,  /* （連携用）期末為替レート */
     zrnyoteiriritun5                                   NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５ */
     zrnyoteiriritun5x2                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿２ */
     zrnyoteiriritun5x3                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿３ */
     zrnyoteiriritun5x4                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿４ */
     zrnyoteiriritun5x5                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿５ */
     zrnyoteiriritun5x6                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿６ */
     zrnyoteiriritun5x7                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿７ */
     zrnyoteiriritun5x8                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿８ */
     zrnyoteiriritun5x9                                 NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿９ */
     zrnyoteiriritun5x10                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１０ */
     zrnyoteiriritun5x11                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１１ */
     zrnyoteiriritun5x12                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１２ */
     zrnyoteiriritun5x13                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１３ */
     zrnyoteiriritun5x14                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１４ */
     zrnyoteiriritun5x15                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１５ */
     zrnyoteiriritun5x16                                NUMBER      (5,4)                                                     NOT NULL  ,  /* （連携用）予定利率Ｎ５＿１６ */
     zrnyobiv6                                          CHAR        (6)                                                       NOT NULL  ,  /* （連携用）予備項目Ｖ６ */
     zrnsyukeiyakup                                     NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約Ｐ */
     zrnsyuptumitatekin                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約保険料積立金 */
     zrnptumitatekin                                    NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金 */
     zrnptumitatekinx2                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿２ */
     zrnptumitatekinx3                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿３ */
     zrnptumitatekinx4                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿４ */
     zrnptumitatekinx5                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿５ */
     zrnptumitatekinx6                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿６ */
     zrnptumitatekinx7                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿７ */
     zrnptumitatekinx8                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿８ */
     zrnptumitatekinx9                                  NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿９ */
     zrnptumitatekinx10                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１０ */
     zrnptumitatekinx11                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１１ */
     zrnptumitatekinx12                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１２ */
     zrnptumitatekinx13                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１３ */
     zrnptumitatekinx14                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１４ */
     zrnptumitatekinx15                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１５ */
     zrnptumitatekinx16                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）保険料積立金＿１６ */
     zrngaikadatejyuutoup                               NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ */
     zrngaikadatejyuutoupx2                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿２ */
     zrngaikadatejyuutoupx3                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿３ */
     zrngaikadatejyuutoupx4                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿４ */
     zrngaikadatejyuutoupx5                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿５ */
     zrngaikadatejyuutoupx6                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿６ */
     zrngaikadatejyuutoupx7                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿７ */
     zrngaikadatejyuutoupx8                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿８ */
     zrngaikadatejyuutoupx9                             NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿９ */
     zrngaikadatejyuutoupx10                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１０ */
     zrngaikadatejyuutoupx11                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１１ */
     zrngaikadatejyuutoupx12                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１２ */
     zrngaikadatejyuutoupx13                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１３ */
     zrngaikadatejyuutoupx14                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１４ */
     zrngaikadatejyuutoupx15                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１５ */
     zrngaikadatejyuutoupx16                            NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）外貨建充当Ｐ＿１６ */
     zrnsykykkitmttvkeisanym1                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）主契約既積立Ｖ計算年月１ */
     zrnsykykkitmttv1                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約既積立Ｖ１ */
     zrnsykykkitmttvkeisanym2                           CHAR        (6)                                                       NOT NULL  ,  /* （連携用）主契約既積立Ｖ計算年月２ */
     zrnsykykkitmttv2                                   NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）主契約既積立Ｖ２ */
     zrnrrthnduhknvkisovkisnyu1                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用１ */
     zrnrrthnduhknvkisovkisnyu2                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用２ */
     zrnrrthnduhknvkisovkisnyu3                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用３ */
     zrnrrthnduhknvkisovkisnyu4                         NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ計算用４ */
     zrnrrthnduhknvkiso                                 NUMBER      (11)                                                      NOT NULL  ,  /* （連携用）利率変動保険Ｖ基礎Ｖ */
     zrnsuuriyouyobin9                                  CHAR        (9)                                                       NOT NULL  ,  /* （連携用）数理用予備項目Ｎ９ */
     zrnyobiv14                                         CHAR        (14)                                                      NOT NULL     /* （連携用）予備項目Ｖ１４ */
)
;

ALTER TABLE ZT_RrtHndugtHknVKnsyuyuRn ADD CONSTRAINT PK_RrtHndugtHknVKnsyuyuRn PRIMARY KEY (
     zrnsequenceno                                              /* （連携用）シーケンス番号 */
) ;
