CREATE TABLE ZT_SiShrdetailRn (
     zrnsyoruicd                                        CHAR        (5)                                                       NOT NULL  ,  /* （連携用）書類コード */
     zrntyouhyouymd                                     CHAR        (8)                                                       NOT NULL  ,  /* （連携用）帳票作成日 */
     zrnsyono                                           CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号 */
     zrnhassoukbn                                       CHAR        (1)                                                       NOT NULL  ,  /* （連携用）発送区分 */
     zrnsyodouhuukbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）証券同封区分 */
     zrnsikibetuno                                      CHAR        (20)                                                      NOT NULL  ,  /* （連携用）識別番号 */
     zrnsikytkmkyobi1                                   CHAR        (104)                                                     NOT NULL  ,  /* （連携用）保険金共通項目予備１ */
     zrnshskyno                                         CHAR        (7)                                                       NOT NULL  ,  /* （連携用）送付先郵便番号 */
     zrnshskadr1kj                                      VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）送付先住所１（漢字） */
     zrnshskadr2kj                                      VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）送付先住所２（漢字） */
     zrnshskadr3kj                                      VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）送付先住所３（漢字） */
     zrnshsnmkjsimisi                                   VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）送付先名（漢字）（支払明細） */
     zrnsimisituutimei                                  VARCHAR     (22)                                                      NOT NULL  ,  /* （連携用）支払明細書通知名 */
     zrnsimisiosirasemongon1x1                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言１－１ */
     zrnsimisiosirasemongon1x2                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言１－２ */
     zrnsimisiosirasemongon2x1                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言２－１ */
     zrnsimisiosirasemongon2x2                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言２－２ */
     zrnsimisiosirasemongon2x3                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言２－３ */
     zrnsimisiosirasemongon2x4                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言２－４ */
     zrnsimisiosirasemongon2x5                          VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言２－５ */
     zrntawyno                                          CHAR        (8)                                                       NOT NULL  ,  /* （連携用）問合せ先郵便番号 */
     zrntawadr1kj30                                     VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）問合せ先住所１（漢字３０桁） */
     zrntawadr2kj30                                     VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）問合せ先住所２（漢字３０桁） */
     zrntawadr3kj30                                     VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）問合せ先住所３（漢字３０桁） */
     zrntawtelno                                        CHAR        (15)                                                      NOT NULL  ,  /* （連携用）問合せ先電話番号 */
     zrnsimisiatenabuyobi1                              CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書宛名部予備１ */
     zrnsimisiatenabuyobi2                              CHAR        (74)                                                      NOT NULL  ,  /* （連携用）支払明細書宛名部予備２ */
     zrnsyono2                                          CHAR        (11)                                                      NOT NULL  ,  /* （連携用）証券番号２ */
     zrnkyknmkj                                         VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）契約者名（漢字） */
     zrnhhknnmkj                                        VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）被保険者名（漢字） */
     zrntyouhyouymdwa                                   VARCHAR     (11)                                                      NOT NULL  ,  /* （連携用）帳票作成日（和暦） */
     zrnsiharaibiwareki                                 VARCHAR     (11)                                                      NOT NULL  ,  /* （連携用）支払日（和暦） */
     zrnbanknmkj                                        VARCHAR     (20)                                                      NOT NULL  ,  /* （連携用）銀行名（漢字） */
     zrnsitennmkj                                       VARCHAR     (20)                                                      NOT NULL  ,  /* （連携用）支店名（漢字） */
     zrnyokinsyumokumeikanji                            VARCHAR     (7)                                                       NOT NULL  ,  /* （連携用）預金種目名（漢字） */
     zrnkouzano12keta                                   CHAR        (12)                                                      NOT NULL  ,  /* （連携用）口座番号（１２桁） */
     zrnkzmeiginmkn                                     VARCHAR     (30)                                                      NOT NULL  ,  /* （連携用）口座名義人氏名（カナ） */
     zrnkouzamaskingmsg                                 VARCHAR     (32)                                                      NOT NULL  ,  /* （連携用）口座マスキングＭＳＧ */
     zrnsimisisummarybuyobi1                            CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書サマリー部予備１ */
     zrnsimisisummarybuyobi2                            CHAR        (55)                                                      NOT NULL  ,  /* （連携用）支払明細書サマリー部予備２ */
     zrnsimisitekiyouranmidasi                          VARCHAR     (5)                                                       NOT NULL  ,  /* （連携用）支払明細書摘要欄見出し */
     zrnsimisimeisairanmidasi                           VARCHAR     (7)                                                       NOT NULL  ,  /* （連携用）支払金額明細欄見出し */
     zrnsimisibikouranmidasi                            VARCHAR     (10)                                                      NOT NULL  ,  /* （連携用）支払明細書備考欄見出し */
     zrnsimisimeisaibumidasiyobi                        CHAR        (120)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部見出し予備 */
     zrnsimisitekiyou1                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１ */
     zrnsimisikngkmisi1                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１ */
     zrnsimisikngkmisituukasyu1                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１ */
     zrnsimisimeisaibikou1                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１ */
     zrnsimisikngkmisihugou1                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１ */
     zrnsimisimeisaiyobi1                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１ */
     zrnsimisitekiyou2                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２ */
     zrnsimisikngkmisi2                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２ */
     zrnsimisikngkmisituukasyu2                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２ */
     zrnsimisimeisaibikou2                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２ */
     zrnsimisikngkmisihugou2                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２ */
     zrnsimisimeisaiyobi2                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２ */
     zrnsimisitekiyou3                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要３ */
     zrnsimisikngkmisi3                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細３ */
     zrnsimisikngkmisituukasyu3                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類３ */
     zrnsimisimeisaibikou3                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考３ */
     zrnsimisikngkmisihugou3                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号３ */
     zrnsimisimeisaiyobi3                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備３ */
     zrnsimisitekiyou4                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要４ */
     zrnsimisikngkmisi4                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細４ */
     zrnsimisikngkmisituukasyu4                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類４ */
     zrnsimisimeisaibikou4                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考４ */
     zrnsimisikngkmisihugou4                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号４ */
     zrnsimisimeisaiyobi4                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備４ */
     zrnsimisitekiyou5                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要５ */
     zrnsimisikngkmisi5                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細５ */
     zrnsimisikngkmisituukasyu5                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類５ */
     zrnsimisimeisaibikou5                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考５ */
     zrnsimisikngkmisihugou5                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号５ */
     zrnsimisimeisaiyobi5                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備５ */
     zrnsimisitekiyou6                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要６ */
     zrnsimisikngkmisi6                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細６ */
     zrnsimisikngkmisituukasyu6                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類６ */
     zrnsimisimeisaibikou6                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考６ */
     zrnsimisikngkmisihugou6                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号６ */
     zrnsimisimeisaiyobi6                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備６ */
     zrnsimisitekiyou7                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要７ */
     zrnsimisikngkmisi7                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細７ */
     zrnsimisikngkmisituukasyu7                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類７ */
     zrnsimisimeisaibikou7                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考７ */
     zrnsimisikngkmisihugou7                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号７ */
     zrnsimisimeisaiyobi7                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備７ */
     zrnsimisitekiyou8                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要８ */
     zrnsimisikngkmisi8                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細８ */
     zrnsimisikngkmisituukasyu8                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類８ */
     zrnsimisimeisaibikou8                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考８ */
     zrnsimisikngkmisihugou8                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号８ */
     zrnsimisimeisaiyobi8                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備８ */
     zrnsimisitekiyou9                                  VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要９ */
     zrnsimisikngkmisi9                                 CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細９ */
     zrnsimisikngkmisituukasyu9                         CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類９ */
     zrnsimisimeisaibikou9                              VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考９ */
     zrnsimisikngkmisihugou9                            CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号９ */
     zrnsimisimeisaiyobi9                               CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備９ */
     zrnsimisitekiyou10                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１０ */
     zrnsimisikngkmisi10                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１０ */
     zrnsimisikngkmisituukasyu10                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１０ */
     zrnsimisimeisaibikou10                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１０ */
     zrnsimisikngkmisihugou10                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１０ */
     zrnsimisimeisaiyobi10                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１０ */
     zrnsimisitekiyou11                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１１ */
     zrnsimisikngkmisi11                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１１ */
     zrnsimisikngkmisituukasyu11                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１１ */
     zrnsimisimeisaibikou11                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１１ */
     zrnsimisikngkmisihugou11                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１１ */
     zrnsimisimeisaiyobi11                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１１ */
     zrnsimisitekiyou12                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１２ */
     zrnsimisikngkmisi12                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１２ */
     zrnsimisikngkmisituukasyu12                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１２ */
     zrnsimisimeisaibikou12                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１２ */
     zrnsimisikngkmisihugou12                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１２ */
     zrnsimisimeisaiyobi12                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１２ */
     zrnsimisitekiyou13                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１３ */
     zrnsimisikngkmisi13                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１３ */
     zrnsimisikngkmisituukasyu13                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１３ */
     zrnsimisimeisaibikou13                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１３ */
     zrnsimisikngkmisihugou13                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１３ */
     zrnsimisimeisaiyobi13                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１３ */
     zrnsimisitekiyou14                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１４ */
     zrnsimisikngkmisi14                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１４ */
     zrnsimisikngkmisituukasyu14                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１４ */
     zrnsimisimeisaibikou14                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１４ */
     zrnsimisikngkmisihugou14                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１４ */
     zrnsimisimeisaiyobi14                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１４ */
     zrnsimisitekiyou15                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１５ */
     zrnsimisikngkmisi15                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１５ */
     zrnsimisikngkmisituukasyu15                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１５ */
     zrnsimisimeisaibikou15                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１５ */
     zrnsimisikngkmisihugou15                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１５ */
     zrnsimisimeisaiyobi15                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１５ */
     zrnsimisitekiyou16                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１６ */
     zrnsimisikngkmisi16                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１６ */
     zrnsimisikngkmisituukasyu16                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１６ */
     zrnsimisimeisaibikou16                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１６ */
     zrnsimisikngkmisihugou16                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１６ */
     zrnsimisimeisaiyobi16                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１６ */
     zrnsimisitekiyou17                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１７ */
     zrnsimisikngkmisi17                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１７ */
     zrnsimisikngkmisituukasyu17                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１７ */
     zrnsimisimeisaibikou17                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１７ */
     zrnsimisikngkmisihugou17                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１７ */
     zrnsimisimeisaiyobi17                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１７ */
     zrnsimisitekiyou18                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１８ */
     zrnsimisikngkmisi18                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１８ */
     zrnsimisikngkmisituukasyu18                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１８ */
     zrnsimisimeisaibikou18                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１８ */
     zrnsimisikngkmisihugou18                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１８ */
     zrnsimisimeisaiyobi18                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１８ */
     zrnsimisitekiyou19                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要１９ */
     zrnsimisikngkmisi19                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細１９ */
     zrnsimisikngkmisituukasyu19                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類１９ */
     zrnsimisimeisaibikou19                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考１９ */
     zrnsimisikngkmisihugou19                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号１９ */
     zrnsimisimeisaiyobi19                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備１９ */
     zrnsimisitekiyou20                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２０ */
     zrnsimisikngkmisi20                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２０ */
     zrnsimisikngkmisituukasyu20                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２０ */
     zrnsimisimeisaibikou20                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２０ */
     zrnsimisikngkmisihugou20                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２０ */
     zrnsimisimeisaiyobi20                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２０ */
     zrnsimisitekiyou21                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２１ */
     zrnsimisikngkmisi21                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２１ */
     zrnsimisikngkmisituukasyu21                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２１ */
     zrnsimisimeisaibikou21                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２１ */
     zrnsimisikngkmisihugou21                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２１ */
     zrnsimisimeisaiyobi21                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２１ */
     zrnsimisitekiyou22                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２２ */
     zrnsimisikngkmisi22                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２２ */
     zrnsimisikngkmisituukasyu22                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２２ */
     zrnsimisimeisaibikou22                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２２ */
     zrnsimisikngkmisihugou22                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２２ */
     zrnsimisimeisaiyobi22                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２２ */
     zrnsimisitekiyou23                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２３ */
     zrnsimisikngkmisi23                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２３ */
     zrnsimisikngkmisituukasyu23                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２３ */
     zrnsimisimeisaibikou23                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２３ */
     zrnsimisikngkmisihugou23                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２３ */
     zrnsimisimeisaiyobi23                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２３ */
     zrnsimisitekiyou24                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２４ */
     zrnsimisikngkmisi24                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２４ */
     zrnsimisikngkmisituukasyu24                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２４ */
     zrnsimisimeisaibikou24                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２４ */
     zrnsimisikngkmisihugou24                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２４ */
     zrnsimisimeisaiyobi24                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２４ */
     zrnsimisitekiyou25                                 VARCHAR     (15)                                                      NOT NULL  ,  /* （連携用）支払明細書摘要２５ */
     zrnsimisikngkmisi25                                CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書金額明細２５ */
     zrnsimisikngkmisituukasyu25                        CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細通貨種類２５ */
     zrnsimisimeisaibikou25                             VARCHAR     (28)                                                      NOT NULL  ,  /* （連携用）支払明細書明細備考２５ */
     zrnsimisikngkmisihugou25                           CHAR        (1)                                                       NOT NULL  ,  /* （連携用）支払明細書金額明細符号２５ */
     zrnsimisimeisaiyobi25                              CHAR        (33)                                                      NOT NULL  ,  /* （連携用）支払明細書明細予備２５ */
     zrnsimisimeisaibuyobi1x1                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－１ */
     zrnsimisimeisaibuyobi1x2                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－２ */
     zrnsimisimeisaibuyobi1x3                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－３ */
     zrnsimisimeisaibuyobi1x4                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－４ */
     zrnsimisimeisaibuyobi1x5                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－５ */
     zrnsimisimeisaibuyobi1x6                           CHAR        (130)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備１－６ */
     zrnsimisisigoukeikingaku                           CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書支払合計金額 */
     zrnsimisisigoukeituukasyu                          CHAR        (3)                                                       NOT NULL  ,  /* （連携用）支払明細書支払合計通貨種類 */
     zrnsimisimeisaibuyobi2                             CHAR        (112)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備２ */
     zrnsimisituutiranmidasi                            VARCHAR     (8)                                                       NOT NULL  ,  /* （連携用）支払明細書通知欄見出し */
     zrnsimisifreemsg1                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１ */
     zrnsimisifreemsg2                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２ */
     zrnsimisifreemsg3                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３ */
     zrnsimisifreemsg4                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４ */
     zrnsimisifreemsg5                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ５ */
     zrnsimisifreemsg6                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ６ */
     zrnsimisifreemsg7                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ７ */
     zrnsimisifreemsg8                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ８ */
     zrnsimisifreemsg9                                  VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ９ */
     zrnsimisifreemsg10                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１０ */
     zrnsimisifreemsg11                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１１ */
     zrnsimisifreemsg12                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１２ */
     zrnsimisifreemsg13                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１３ */
     zrnsimisifreemsg14                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１４ */
     zrnsimisifreemsg15                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１５ */
     zrnsimisifreemsg16                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１６ */
     zrnsimisifreemsg17                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１７ */
     zrnsimisifreemsg18                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１８ */
     zrnsimisifreemsg19                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ１９ */
     zrnsimisifreemsg20                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２０ */
     zrnsimisifreemsg21                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２１ */
     zrnsimisifreemsg22                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２２ */
     zrnsimisifreemsg23                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２３ */
     zrnsimisifreemsg24                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２４ */
     zrnsimisifreemsg25                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２５ */
     zrnsimisifreemsg26                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２６ */
     zrnsimisifreemsg27                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２７ */
     zrnsimisifreemsg28                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２８ */
     zrnsimisifreemsg29                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ２９ */
     zrnsimisifreemsg30                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３０ */
     zrnsimisifreemsg31                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３１ */
     zrnsimisifreemsg32                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３２ */
     zrnsimisifreemsg33                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３３ */
     zrnsimisifreemsg34                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３４ */
     zrnsimisifreemsg35                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３５ */
     zrnsimisifreemsg36                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３６ */
     zrnsimisifreemsg37                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３７ */
     zrnsimisifreemsg38                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３８ */
     zrnsimisifreemsg39                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ３９ */
     zrnsimisifreemsg40                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４０ */
     zrnsimisifreemsg41                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４１ */
     zrnsimisifreemsg42                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４２ */
     zrnsimisifreemsg43                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４３ */
     zrnsimisifreemsg44                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４４ */
     zrnsimisifreemsg45                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４５ */
     zrnsimisifreemsg46                                 VARCHAR     (45)                                                      NOT NULL  ,  /* （連携用）支払明細書フリーメッセージ４６ */
     zrnsimisiosirasemongon3x1                          VARCHAR     (53)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言３－１ */
     zrnsimisiosirasemongon3x2                          VARCHAR     (53)                                                      NOT NULL  ,  /* （連携用）支払明細書お知らせ文言３－２ */
     zrnsimisisynykngk                                  CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書収入金額 */
     zrnsimisihtykeihi                                  CHAR        (15)                                                      NOT NULL  ,  /* （連携用）支払明細書必要経費 */
     zrnkztkgk                                          CHAR        (15)                                                      NOT NULL  ,  /* （連携用）課税対象金額 */
     zrnzeitratkikbn                                    CHAR        (1)                                                       NOT NULL  ,  /* （連携用）税取扱区分 */
     zrnkykhenkouumukbn                                 CHAR        (1)                                                       NOT NULL  ,  /* （連携用）契約者変更有無区分 */
     zrnshrkykhtykeihi                                  CHAR        (13)                                                      NOT NULL  ,  /* （連携用）支払時契約者必要経費 */
     zrnsimisimeisaibuyobi3x1                           CHAR        (250)                                                     NOT NULL  ,  /* （連携用）支払明細書明細部予備３－１ */
     zrnsimisimeisaibuyobi3x2                           CHAR        (118)                                                     NOT NULL     /* （連携用）支払明細書明細部予備３－２ */
)
;

ALTER TABLE ZT_SiShrdetailRn ADD CONSTRAINT PK_SiShrdetailRn PRIMARY KEY (
     zrntyouhyouymd                                           , /* （連携用）帳票作成日 */
     zrnsyono                                                 , /* （連携用）証券番号 */
     zrnsikibetuno                                              /* （連携用）識別番号 */
) ;
