CREATE TABLE ZT_TjHitsyyugkNplusZeroTy (
     ztysequenceno                                      NUMBER      (8)                                                       NOT NULL  ,  /* （中継用）シーケンス番号 */
     ztyyuukourecordlength                              NUMBER      (7)                                                                 ,  /* （中継用）有効レコード長 */
     ztyrdwarea                                         VARCHAR     (4)                                                                 ,  /* （中継用）ＲＤＷ領域 */
     ztyerrkbnv2                                        VARCHAR     (2)                                                                 ,  /* （中継用）エラー区分Ｖ２ */
     ztyratekbn                                         VARCHAR     (1)                                                                 ,  /* （中継用）レート区分 */
     ztykeisandnendo                                    VARCHAR     (4)                                                                 ,  /* （中継用）計算Ｄ年度 */
     ztykeijyouym                                       VARCHAR     (6)                                                                 ,  /* （中継用）計上年月 */
     ztysyouinkbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）消因区分 */
     ztykbnkeiriyousegmentkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用セグメント区分 */
     ztykbnkeiriyourgnbnskkbn                           VARCHAR     (2)                                                                 ,  /* （中継用）区分経理用利源分析区分 */
     ztysyukeiyakusyuruicdv2                            VARCHAR     (2)                                                                 ,  /* （中継用）主契約種類コードＶ２ */
     ztydaihyouyoteiriritu                              NUMBER      (5,4)                                                               ,  /* （中継用）代表予定利率 */
     ztyharaikatakbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）払方区分 */
     ztynenkinkaisigohyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）年金開始後表示 */
     ztykykjyoutai                                      VARCHAR     (1)                                                                 ,  /* （中継用）契約状態 */
     ztynaizouteikiyoteiriritu                          NUMBER      (5,4)                                                               ,  /* （中継用）内蔵定期予定利率 */
     ztygoukeigyousekihyoujis                           NUMBER      (11)                                                                ,  /* （中継用）合計業績表示Ｓ */
     ztysykykgyusekihyjs                                NUMBER      (11)                                                                ,  /* （中継用）主契約業績表示Ｓ */
     ztytnknitjbrsykykgyuskhyjs                         NUMBER      (11)                                                                ,  /* （中継用）転換一時払主契約業績表示Ｓ */
     ztydatakanrino                                     VARCHAR     (11)                                                                ,  /* （中継用）データ管理番号 */
     ztyhknsyukigou                                     VARCHAR     (2)                                                                 ,  /* （中継用）保険種類記号 */
     ztyannaifuyouriyuukbn                              VARCHAR     (2)                                                                 ,  /* （中継用）案内不要理由区分 */
     ztytkbthsyumnryuhyouji                             VARCHAR     (1)                                                                 ,  /* （中継用）特別保障満了表示 */
     ztykykymd                                          VARCHAR     (8)                                                                 ,  /* （中継用）契約年月日 */
     ztyhhknseikbn                                      VARCHAR     (1)                                                                 ,  /* （中継用）被保険者性別区分 */
     ztyhihokensyaagev2                                 VARCHAR     (2)                                                                 ,  /* （中継用）被保険者年令Ｖ２ */
     ztyhknkkn                                          VARCHAR     (2)                                                                 ,  /* （中継用）保険期間 */
     ztyphrkkikn                                        VARCHAR     (2)                                                                 ,  /* （中継用）Ｐ払込期間 */
     ztysaimnkkykhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）才満期契約表示 */
     ztyhrkkaisuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）払込回数区分 */
     ztyannaikigetu                                     VARCHAR     (2)                                                                 ,  /* （中継用）案内期月 */
     ztyao3tyou3sibousdatehyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）青３長３死亡Ｓ建表示 */
     ztykihons                                          NUMBER      (11)                                                                ,  /* （中継用）基本Ｓ */
     ztyharaizumiymd                                    VARCHAR     (8)                                                                 ,  /* （中継用）払済年月日 */
     ztyharaizumis                                      NUMBER      (11)                                                                ,  /* （中継用）払済Ｓ */
     ztyentyous                                         NUMBER      (11)                                                                ,  /* （中継用）延長Ｓ */
     ztyseizons                                         NUMBER      (11)                                                                ,  /* （中継用）生存Ｓ */
     ztypmens                                           NUMBER      (11)                                                                ,  /* （中継用）Ｐ免Ｓ */
     ztyhendous                                         NUMBER      (11)                                                                ,  /* （中継用）変動Ｓ */
     ztyitibuitijibarais                                NUMBER      (11)                                                                ,  /* （中継用）一部一時払Ｓ */
     ztytenkanteikisyuruikigou                          VARCHAR     (2)                                                                 ,  /* （中継用）転換定期種類記号 */
     ztytenkanteikikikan                                VARCHAR     (2)                                                                 ,  /* （中継用）転換定期期間 */
     ztytnknteikinkshrkkn                               VARCHAR     (2)                                                                 ,  /* （中継用）転換定期年金支払期間 */
     ztygoukeitenkans                                   NUMBER      (11)                                                                ,  /* （中継用）合計転換Ｓ */
     ztygoukeitenkanteikis                              NUMBER      (11)                                                                ,  /* （中継用）合計転換定期Ｓ */
     ztygoukeipbubuntenkans                             NUMBER      (11)                                                                ,  /* （中継用）合計Ｐ部分転換Ｓ */
     ztytenkankaisuu                                    VARCHAR     (1)                                                                 ,  /* （中継用）転換回数 */
     ztydgoukei                                         NUMBER      (11)                                                                ,  /* （中継用）Ｄ合計 */
     ztysrankbetuhisad                                  NUMBER      (11)                                                                ,  /* （中継用）Ｓランク別費差Ｄ */
     ztysyumtjsrankbetuhisad                            NUMBER      (11)                                                                ,  /* （中継用）消滅時Ｓランク別費差Ｄ */
     ztybairitubetuhisad                                NUMBER      (11)                                                                ,  /* （中継用）倍率別費差Ｄ */
     ztysyumtjtikbairtbetuhisad                         NUMBER      (11)                                                                ,  /* （中継用）消滅時定期倍率別費差Ｄ */
     ztysyukeiyakukihongoukeid                          NUMBER      (11)                                                                ,  /* （中継用）主契約基本合計Ｄ */
     ztysyukeiyakukihonsisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約基本死差Ｄ */
     ztysyukeiyakukihonrisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約基本利差Ｄ */
     ztysyukeiyakukihonramudad                          NUMBER      (11)                                                                ,  /* （中継用）主契約基本ラムダＤ */
     ztysyukeiyakukihonhisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約基本費差Ｄ */
     ztysyukeiyakukihondtaisyous                        NUMBER      (11)                                                                ,  /* （中継用）主契約基本Ｄ対象Ｓ */
     ztysyukeiyakukihondyouv                            NUMBER      (11)                                                                ,  /* （中継用）主契約基本Ｄ用Ｖ */
     ztysyukeiyakukihondkikens                          NUMBER      (11)                                                                ,  /* （中継用）主契約基本Ｄ危険Ｓ */
     ztysykykkhnhisadtisyus                             NUMBER      (11)                                                                ,  /* （中継用）主契約基本費差Ｄ対象Ｓ */
     ztysyukeiyakuteikigoukeid                          NUMBER      (11)                                                                ,  /* （中継用）主契約定期合計Ｄ */
     ztysyukeiyakuteikisisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約定期死差Ｄ */
     ztysyukeiyakuteikirisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約定期利差Ｄ */
     ztysyukeiyakuteikiramudad                          NUMBER      (11)                                                                ,  /* （中継用）主契約定期ラムダＤ */
     ztysyukeiyakuteikihisad                            NUMBER      (11)                                                                ,  /* （中継用）主契約定期費差Ｄ */
     ztysyukeiyakuteikidtaisyous                        NUMBER      (11)                                                                ,  /* （中継用）主契約定期Ｄ対象Ｓ */
     ztysyukeiyakuteikidyouv                            NUMBER      (11)                                                                ,  /* （中継用）主契約定期Ｄ用Ｖ */
     ztysyukeiyakuteikidkikens                          NUMBER      (11)                                                                ,  /* （中継用）主契約定期Ｄ危険Ｓ */
     ztysykyktikhisadtisyus                             NUMBER      (11)                                                                ,  /* （中継用）主契約定期費差Ｄ対象Ｓ */
     ztytenkankihongoukeid                              NUMBER      (11)                                                                ,  /* （中継用）転換基本合計Ｄ */
     ztytenkankihonsisad                                NUMBER      (11)                                                                ,  /* （中継用）転換基本死差Ｄ */
     ztytenkankihonrisad                                NUMBER      (11)                                                                ,  /* （中継用）転換基本利差Ｄ */
     ztytenkankihonramudad                              NUMBER      (11)                                                                ,  /* （中継用）転換基本ラムダＤ */
     ztytenkankihonhisad                                NUMBER      (11)                                                                ,  /* （中継用）転換基本費差Ｄ */
     ztytenkankihondtaisyous                            NUMBER      (11)                                                                ,  /* （中継用）転換基本Ｄ対象Ｓ */
     ztytenkankihondyouv                                NUMBER      (11)                                                                ,  /* （中継用）転換基本Ｄ用Ｖ */
     ztytenkankihondkikens                              NUMBER      (11)                                                                ,  /* （中継用）転換基本Ｄ危険Ｓ */
     ztytenkankihonhisadtaisyous                        NUMBER      (11)                                                                ,  /* （中継用）転換基本費差Ｄ対象Ｓ */
     ztytenkanteikigoukeid                              NUMBER      (11)                                                                ,  /* （中継用）転換定期合計Ｄ */
     ztytenkanteikisisad                                NUMBER      (11)                                                                ,  /* （中継用）転換定期死差Ｄ */
     ztytenkanteikirisad                                NUMBER      (11)                                                                ,  /* （中継用）転換定期利差Ｄ */
     ztytenkanteikiramudad                              NUMBER      (11)                                                                ,  /* （中継用）転換定期ラムダＤ */
     ztytenkanteikihisad                                NUMBER      (11)                                                                ,  /* （中継用）転換定期費差Ｄ */
     ztytenkanteikidtaisyous                            NUMBER      (11)                                                                ,  /* （中継用）転換定期Ｄ対象Ｓ */
     ztytenkanteikidyouv                                NUMBER      (11)                                                                ,  /* （中継用）転換定期Ｄ用Ｖ */
     ztytenkanteikidkikens                              NUMBER      (11)                                                                ,  /* （中継用）転換定期Ｄ危険Ｓ */
     ztytenkanteikihisadtaisyous                        NUMBER      (11)                                                                ,  /* （中継用）転換定期費差Ｄ対象Ｓ */
     ztysyumtjtyusiyutnkntikgukd                        NUMBER      (11)                                                                ,  /* （中継用）消滅時調整用転換定期合計Ｄ */
     ztysyumtjtyusiyutnkntiksisd                        NUMBER      (11)                                                                ,  /* （中継用）消滅時調整用転換定期死差Ｄ */
     ztysyumtjtyusiyutnkntikrisd                        NUMBER      (11)                                                                ,  /* （中継用）消滅時調整用転換定期利差Ｄ */
     ztysyumtjtyusiyutnkntikhisd                        NUMBER      (11)                                                                ,  /* （中継用）消滅時調整用転換定期費差Ｄ */
     ztysyumtjtnkntikdtaisyous                          NUMBER      (11)                                                                ,  /* （中継用）消滅時転換定期Ｄ対象Ｓ */
     ztysyumtjtnkntikdyouv                              NUMBER      (11)                                                                ,  /* （中継用）消滅時転換定期Ｄ用Ｖ */
     ztysyumtjtnkntikdkikens                            NUMBER      (11)                                                                ,  /* （中継用）消滅時転換定期Ｄ危険Ｓ */
     ztyhendougoukeid                                   NUMBER      (11)                                                                ,  /* （中継用）変動合計Ｄ */
     ztyhendousisad                                     NUMBER      (11)                                                                ,  /* （中継用）変動死差Ｄ */
     ztyhendouhisad                                     NUMBER      (11)                                                                ,  /* （中継用）変動費差Ｄ */
     ztyhendoudtaisyous                                 NUMBER      (11)                                                                ,  /* （中継用）変動Ｄ対象Ｓ */
     ztyhendoudyouv                                     NUMBER      (11)                                                                ,  /* （中継用）変動Ｄ用Ｖ */
     ztyhendoudkikens                                   NUMBER      (11)                                                                ,  /* （中継用）変動Ｄ危険Ｓ */
     ztyitibuitijibaraigoukeid                          NUMBER      (11)                                                                ,  /* （中継用）一部一時払合計Ｄ */
     ztyitibuitijibaraisisad                            NUMBER      (11)                                                                ,  /* （中継用）一部一時払死差Ｄ */
     ztyitibuitijibaraihisad                            NUMBER      (11)                                                                ,  /* （中継用）一部一時払費差Ｄ */
     ztyitibuitijibaraidtaisyous                        NUMBER      (11)                                                                ,  /* （中継用）一部一時払Ｄ対象Ｓ */
     ztyitibuitijibaraidyouv                            NUMBER      (11)                                                                ,  /* （中継用）一部一時払Ｄ用Ｖ */
     ztyitibuitijibaraidkikens                          NUMBER      (11)                                                                ,  /* （中継用）一部一時払Ｄ危険Ｓ */
     ztyitibitjbrhisadtisyus                            NUMBER      (11)                                                                ,  /* （中継用）一部一時払費差Ｄ対象Ｓ */
     ztyszoukouryokukaisiymd                            VARCHAR     (8)                                                                 ,  /* （中継用）Ｓ増効力開始年月日 */
     ztyszouhokensyuruikigou                            VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増保険種類記号 */
     ztyszoukikan                                       VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増期間 */
     ztyszouhihokensyaage                               VARCHAR     (2)                                                                 ,  /* （中継用）Ｓ増被保険者年令 */
     ztyzoukagoukeid                                    NUMBER      (11)                                                                ,  /* （中継用）増加合計Ｄ */
     ztyzoukasisad                                      NUMBER      (11)                                                                ,  /* （中継用）増加死差Ｄ */
     ztyzoukarisad                                      NUMBER      (11)                                                                ,  /* （中継用）増加利差Ｄ */
     ztyzoukaramudad                                    NUMBER      (11)                                                                ,  /* （中継用）増加ラムダＤ */
     ztyzoukahisad                                      NUMBER      (11)                                                                ,  /* （中継用）増加費差Ｄ */
     ztyzoukadtaisyous                                  NUMBER      (11)                                                                ,  /* （中継用）増加Ｄ対象Ｓ */
     ztyzoukadyouv                                      NUMBER      (11)                                                                ,  /* （中継用）増加Ｄ用Ｖ */
     ztyzoukadkikens                                    NUMBER      (11)                                                                ,  /* （中継用）増加Ｄ危険Ｓ */
     ztykakuteikakusasyuruikgu                          VARCHAR     (2)                                                                 ,  /* （中継用）カク定カクサ種類記号 */
     ztykakuteikakusad                                  NUMBER      (11)                                                                ,  /* （中継用）カク定カクサＤ */
     ztykakuteikakusas                                  NUMBER      (11)                                                                ,  /* （中継用）カク定カクサＳ */
     ztykakuteikakusamanryoujid                         NUMBER      (11)                                                                ,  /* （中継用）カク定カクサ満了時Ｄ */
     ztynaizoumarusasyuruikigou                         VARCHAR     (2)                                                                 ,  /* （中継用）内蔵マルサ種類記号 */
     ztynaizoumarusad                                   NUMBER      (11)                                                                ,  /* （中継用）内蔵マルサＤ */
     ztynaizoumarusas                                   NUMBER      (11)                                                                ,  /* （中継用）内蔵マルサＳ */
     ztynaizoukakusasyuruikigou                         VARCHAR     (2)                                                                 ,  /* （中継用）内蔵カクサ種類記号 */
     ztynaizoukakusad                                   NUMBER      (11)                                                                ,  /* （中継用）内蔵カクサＤ */
     ztynaizoukakusas                                   NUMBER      (11)                                                                ,  /* （中継用）内蔵カクサＳ */
     ztytenkanpbubund                                   NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分Ｄ */
     ztytenkanpbubunsisad                               NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分死差Ｄ */
     ztytenkanpbubunrisad                               NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分利差Ｄ */
     ztytenkanpbubunhisad                               NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分費差Ｄ */
     ztytenkanpbubundtaisyous                           NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分Ｄ対象Ｓ */
     ztytenkanpbubundyouv                               NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分Ｄ用Ｖ */
     ztytenkanpbubundkikens                             NUMBER      (11)                                                                ,  /* （中継用）転換Ｐ部分Ｄ危険Ｓ */
     ztynaizougatateikimud                              NUMBER      (11)                                                                ,  /* （中継用）内蔵型定期ミューＤ */
     ztynaizougatanenkansanp                            NUMBER      (11)                                                                ,  /* （中継用）内蔵型年換算Ｐ */
     ztyvhktgbbntnkntikmud                              NUMBER      (11)                                                                ,  /* （中継用）Ｖ引継部分転換定期ミューＤ */
     ztyhikitugitenkanphireimud                         NUMBER      (11)                                                                ,  /* （中継用）引継転換Ｐ比例ミューＤ */
     ztyitibitjbrgyuskhyjs                              NUMBER      (11)                                                                ,  /* （中継用）一部一時払業績表示Ｓ */
     ztykariwariate4nenmae                              NUMBER      (11)                                                                ,  /* （中継用）仮割当（４年前） */
     ztykariwariate3nenmae                              NUMBER      (11)                                                                ,  /* （中継用）仮割当（３年前） */
     ztykariwariate2nenmae                              NUMBER      (11)                                                                ,  /* （中継用）仮割当（２年前） */
     ztykariwariate1nenmae                              NUMBER      (11)                                                                ,  /* （中継用）仮割当（１年前） */
     ztygukisisntnkntikmud                              NUMBER      (11)                                                                ,  /* （中継用）合計精算転換定期ミューＤ */
     ztygoukeiseisanteikis                              NUMBER      (11)                                                                ,  /* （中継用）合計精算定期Ｓ */
     ztygukisisntnknnenknsnp                            NUMBER      (11)                                                                ,  /* （中継用）合計精算転換年換算Ｐ */
     ztytnkntikhtnknkykymd                              VARCHAR     (8)                                                                 ,  /* （中継用）転換定期被転換契約年月日 */
     ztytenkangophireimuritu                            NUMBER      (7,3)                                                               ,  /* （中継用）転換後Ｐ比例ミュー率 */
     ztygoukeitenkannenkansanp                          NUMBER      (11)                                                                ,  /* （中継用）合計転換年換算Ｐ */
     ztygoukeitenkanteikimud                            NUMBER      (11)                                                                ,  /* （中継用）合計転換定期ミューＤ */
     ztytyoukikeizokutokubetud                          NUMBER      (11)                                                                ,  /* （中継用）長期継続特別Ｄ */
     ztytyouseimaed                                     NUMBER      (11)                                                                ,  /* （中継用）調整前Ｄ */
     ztytuutokuhituusand                                NUMBER      (11)                                                                ,  /* （中継用）通特非通算Ｄ */
     ztyhknsyuruikigousedaikbn                          VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号世代区分 */
     ztytenkanteikikigousedaikbn                        VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号世代区分 */
     ztyszoukigousedaikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）Ｓ増記号世代区分 */
     ztymankihyouji                                     VARCHAR     (1)                                                                 ,  /* （中継用）満期表示 */
     ztykeiyakuoutoubikbn                               VARCHAR     (1)                                                                 ,  /* （中継用）契約応当日区分 */
     ztysuuriyouyobin2                                  VARCHAR     (2)                                                                 ,  /* （中継用）数理用予備項目Ｎ２ */
     ztytokuyakuhukasuu                                 NUMBER      (3)                                                                 ,  /* （中継用）特約付加数 */
     ztyhokensyuruikigouyobi1x1                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１ */
     ztyhokensyuruikigouyobi1x2                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿２ */
     ztyhokensyuruikigouyobi1x3                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿３ */
     ztyhokensyuruikigouyobi1x4                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿４ */
     ztyhokensyuruikigouyobi1x5                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿５ */
     ztyhokensyuruikigouyobi1x6                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿６ */
     ztyhokensyuruikigouyobi1x7                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿７ */
     ztyhokensyuruikigouyobi1x8                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿８ */
     ztyhokensyuruikigouyobi1x9                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿９ */
     ztyhokensyuruikigouyobi1x10                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１０ */
     ztyhokensyuruikigouyobi1x11                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１１ */
     ztyhokensyuruikigouyobi1x12                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１２ */
     ztyhokensyuruikigouyobi1x13                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１３ */
     ztyhokensyuruikigouyobi1x14                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１４ */
     ztyhokensyuruikigouyobi1x15                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備１＿１５ */
     ztyhokensyuruikigouyobi2x1                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿１ */
     ztyhokensyuruikigouyobi2x2                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿２ */
     ztyhokensyuruikigouyobi2x3                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿３ */
     ztyhokensyuruikigouyobi2x4                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿４ */
     ztyhokensyuruikigouyobi2x5                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿５ */
     ztyhokensyuruikigouyobi2x6                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿６ */
     ztyhokensyuruikigouyobi2x7                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿７ */
     ztyhokensyuruikigouyobi2x8                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿８ */
     ztyhokensyuruikigouyobi2x9                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿９ */
     ztyhokensyuruikigouyobi2x10                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備２＿１０ */
     ztyhokensyuruikigouyobi3x1                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿１ */
     ztyhokensyuruikigouyobi3x2                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿２ */
     ztyhokensyuruikigouyobi3x3                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿３ */
     ztyhokensyuruikigouyobi3x4                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿４ */
     ztyhokensyuruikigouyobi3x5                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿５ */
     ztyhokensyuruikigouyobi3x6                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿６ */
     ztyhokensyuruikigouyobi3x7                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿７ */
     ztyhokensyuruikigouyobi3x8                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿８ */
     ztyhokensyuruikigouyobi3x9                         VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿９ */
     ztyhokensyuruikigouyobi3x10                        VARCHAR     (1)                                                                 ,  /* （中継用）保険種類記号予備３＿１０ */
     ztytenkanteikikigouyobix1                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備＿１ */
     ztytenkanteikikigouyobix2                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備＿２ */
     ztytenkanteikikigouyobix3                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備＿３ */
     ztytenkanteikikigouyobix4                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備＿４ */
     ztytenkanteikikigouyobix5                          VARCHAR     (1)                                                                 ,  /* （中継用）転換定期記号予備＿５ */
     ztykakuteikakusakgusdkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号世代区分 */
     ztykakuteikakusakguybx1                            VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号予備＿１ */
     ztykakuteikakusakguybx2                            VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号予備＿２ */
     ztykakuteikakusakguybx3                            VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号予備＿３ */
     ztykakuteikakusakguybx4                            VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号予備＿４ */
     ztykakuteikakusakguybx5                            VARCHAR     (1)                                                                 ,  /* （中継用）カク定カクサ記号予備＿５ */
     ztynaizoumarusakgusdkbn                            VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号世代区分 */
     ztynaizoumarusakigouyobix1                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号予備＿１ */
     ztynaizoumarusakigouyobix2                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号予備＿２ */
     ztynaizoumarusakigouyobix3                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号予備＿３ */
     ztynaizoumarusakigouyobix4                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号予備＿４ */
     ztynaizoumarusakigouyobix5                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵マルサ記号予備＿５ */
     ztynaizoukakusakgusdkbn                            VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号世代区分 */
     ztynaizoukakusakigouyobix1                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号予備＿１ */
     ztynaizoukakusakigouyobix2                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号予備＿２ */
     ztynaizoukakusakigouyobix3                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号予備＿３ */
     ztynaizoukakusakigouyobix4                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号予備＿４ */
     ztynaizoukakusakigouyobix5                         VARCHAR     (1)                                                                 ,  /* （中継用）内蔵カクサ記号予備＿５ */
     ztyyobiv92                                         VARCHAR     (92)                                                                ,  /* （中継用）予備項目Ｖ９２ */
     ztyraysystemhyj                                    VARCHAR     (1)                                                                 ,  /* （中継用）ＲＡＹシステム表示 */
     ztygaikakbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）外貨区分 */
     ztykawaserate                                      NUMBER      (9,6)                                                               ,  /* （中継用）為替レート */
     ztykawaseratetekiyouymd                            VARCHAR     (8)                                                                 ,  /* （中継用）為替レート適用年月日 */
     ztyenkdtsbujsitihsyukngk                           NUMBER      (11)                                                                ,  /* （中継用）円貨建死亡時最低保証金額 */
     ztysuuriyouyobin10                                 VARCHAR     (10)                                                                ,  /* （中継用）数理用予備項目Ｎ１０ */
     ztyyobiv10x2                                       VARCHAR     (10)                                                                ,  /* （中継用）予備項目Ｖ１０＿２ */
     ztyyobin11                                         NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１ */
     ztyyobin11x2                                       NUMBER      (11)                                                                ,  /* （中継用）予備項目Ｎ１１＿２ */
     ztyyobiv17                                         VARCHAR     (17)                                                                ,  /* （中継用）予備項目Ｖ１７ */
     ztysisadrate                                       NUMBER      (9,6)                                                               ,  /* （中継用）死差Ｄレート */
     ztyrisadrate                                       NUMBER      (9,6)                                                               ,  /* （中継用）利差Ｄレート */
     ztyhisadrate                                       NUMBER      (9,6)                                                               ,  /* （中継用）費差Ｄレート */
     ztydyouvrate                                       NUMBER      (9,6)                                                               ,  /* （中継用）Ｄ用Ｖレート */
     ztykikensrate                                      NUMBER      (9,6)                                                               ,  /* （中継用）危険Ｓレート */
     ztygoukeidrate                                     NUMBER      (9,6)                                                               ,  /* （中継用）合計Ｄレート */
     ztytokuyakukoumokuv180                             VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０ */
     ztytokuyakukoumokuv180x2                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２ */
     ztytokuyakukoumokuv180x3                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３ */
     ztytokuyakukoumokuv180x4                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４ */
     ztytokuyakukoumokuv180x5                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿５ */
     ztytokuyakukoumokuv180x6                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿６ */
     ztytokuyakukoumokuv180x7                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿７ */
     ztytokuyakukoumokuv180x8                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿８ */
     ztytokuyakukoumokuv180x9                           VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿９ */
     ztytokuyakukoumokuv180x10                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１０ */
     ztytokuyakukoumokuv180x11                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１１ */
     ztytokuyakukoumokuv180x12                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１２ */
     ztytokuyakukoumokuv180x13                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１３ */
     ztytokuyakukoumokuv180x14                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１４ */
     ztytokuyakukoumokuv180x15                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１５ */
     ztytokuyakukoumokuv180x16                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１６ */
     ztytokuyakukoumokuv180x17                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１７ */
     ztytokuyakukoumokuv180x18                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１８ */
     ztytokuyakukoumokuv180x19                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿１９ */
     ztytokuyakukoumokuv180x20                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２０ */
     ztytokuyakukoumokuv180x21                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２１ */
     ztytokuyakukoumokuv180x22                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２２ */
     ztytokuyakukoumokuv180x23                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２３ */
     ztytokuyakukoumokuv180x24                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２４ */
     ztytokuyakukoumokuv180x25                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２５ */
     ztytokuyakukoumokuv180x26                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２６ */
     ztytokuyakukoumokuv180x27                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２７ */
     ztytokuyakukoumokuv180x28                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２８ */
     ztytokuyakukoumokuv180x29                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿２９ */
     ztytokuyakukoumokuv180x30                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３０ */
     ztytokuyakukoumokuv180x31                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３１ */
     ztytokuyakukoumokuv180x32                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３２ */
     ztytokuyakukoumokuv180x33                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３３ */
     ztytokuyakukoumokuv180x34                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３４ */
     ztytokuyakukoumokuv180x35                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３５ */
     ztytokuyakukoumokuv180x36                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３６ */
     ztytokuyakukoumokuv180x37                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３７ */
     ztytokuyakukoumokuv180x38                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３８ */
     ztytokuyakukoumokuv180x39                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿３９ */
     ztytokuyakukoumokuv180x40                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４０ */
     ztytokuyakukoumokuv180x41                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４１ */
     ztytokuyakukoumokuv180x42                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４２ */
     ztytokuyakukoumokuv180x43                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４３ */
     ztytokuyakukoumokuv180x44                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４４ */
     ztytokuyakukoumokuv180x45                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４５ */
     ztytokuyakukoumokuv180x46                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４６ */
     ztytokuyakukoumokuv180x47                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４７ */
     ztytokuyakukoumokuv180x48                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４８ */
     ztytokuyakukoumokuv180x49                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿４９ */
     ztytokuyakukoumokuv180x50                          VARCHAR     (180)                                                               ,  /* （中継用）特約項目Ｖ１８０＿５０ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                ,  /* 更新機能 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                    /* バージョン */
)
;

ALTER TABLE ZT_TjHitsyyugkNplusZeroTy ADD CONSTRAINT PK_TjHitsyyugkNplusZeroTy PRIMARY KEY (
     ztysequenceno                                              /* （中継用）シーケンス番号 */
) ;
