CREATE TABLE ZT_TtdkKanTy (
     ztysyoruicd                                        VARCHAR     (5)                                                                 ,  /* （中継用）書類コード */
     ztytyouhyouymd                                     VARCHAR     (8)                                                       NOT NULL  ,  /* （中継用）帳票作成日 */
     ztytyouhyouymdwa                                   VARCHAR     (11)                                                                ,  /* （中継用）帳票作成日（和暦） */
     ztysyono                                           VARCHAR     (11)                                                      NOT NULL  ,  /* （中継用）証券番号 */
     ztyhassoukbn                                       VARCHAR     (1)                                                                 ,  /* （中継用）発送区分 */
     ztytantousitukbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）担当室区分 */
     ztysyodouhuukbn                                    VARCHAR     (1)                                                                 ,  /* （中継用）証券同封区分 */
     ztysikibetuno                                      VARCHAR     (20)                                                      NOT NULL  ,  /* （中継用）識別番号 */
     ztyyobiv21                                         VARCHAR     (21)                                                                ,  /* （中継用）予備項目Ｖ２１ */
     ztyshskyno                                         VARCHAR     (7)                                                                 ,  /* （中継用）送付先郵便番号 */
     ztyshskadr1kj                                      VARCHAR     (30)                                                                ,  /* （中継用）送付先住所１（漢字） */
     ztyshskadr2kj                                      VARCHAR     (30)                                                                ,  /* （中継用）送付先住所２（漢字） */
     ztyshskadr3kj                                      VARCHAR     (30)                                                                ,  /* （中継用）送付先住所３（漢字） */
     ztyshsnmkjttdk                                     VARCHAR     (15)                                                                ,  /* （中継用）送付先名（漢字）（手続完了） */
     ztyshsnmkjttdk2                                    VARCHAR     (15)                                                                ,  /* （中継用）送付先名（漢字）（手続完了）２ */
     ztyyobiv3                                          VARCHAR     (3)                                                                 ,  /* （中継用）予備項目Ｖ３ */
     ztytawyno                                          VARCHAR     (8)                                                                 ,  /* （中継用）問合せ先郵便番号 */
     ztytawadr1kj                                       VARCHAR     (15)                                                                ,  /* （中継用）問合せ先住所１（漢字） */
     ztytawadr2kj                                       VARCHAR     (15)                                                                ,  /* （中継用）問合せ先住所２（漢字） */
     ztytoiawasekaisyanmkj                              VARCHAR     (10)                                                                ,  /* （中継用）問合せ先会社名（漢字） */
     ztytawsosikikj                                     VARCHAR     (15)                                                                ,  /* （中継用）問合せ先組織名（漢字） */
     ztytawtelnov14                                     VARCHAR     (14)                                                                ,  /* （中継用）問合せ先電話番号Ｖ１４ */
     ztytawteluktkkanou1x18keta                         VARCHAR     (18)                                                                ,  /* （中継用）問合せ先電話受付可能時間１（１８桁） */
     ztytawteluktkkanou2x18keta                         VARCHAR     (18)                                                                ,  /* （中継用）問合せ先電話受付可能時間２（１８桁） */
     ztyyobiv26                                         VARCHAR     (26)                                                                ,  /* （中継用）予備項目Ｖ２６ */
     ztytetudukisyunm                                   VARCHAR     (30)                                                                ,  /* （中継用）手続種類名 */
     ztysyokakmngnumkbn                                 VARCHAR     (1)                                                                 ,  /* （中継用）証券確認文言有無区分 */
     ztysyono2                                          VARCHAR     (11)                                                                ,  /* （中継用）証券番号２ */
     ztykyknmkj                                         VARCHAR     (15)                                                                ,  /* （中継用）契約者名（漢字） */
     ztyhhknnmkj                                        VARCHAR     (15)                                                                ,  /* （中継用）被保険者名（漢字） */
     ztyyobiv28                                         VARCHAR     (28)                                                                ,  /* （中継用）予備項目Ｖ２８ */
     ztyttdknaiyou1                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容１ */
     ztyttdknaiyou2                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容２ */
     ztyttdknaiyou3                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容３ */
     ztyttdknaiyou4                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容４ */
     ztyttdknaiyou5                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容５ */
     ztyttdknaiyou6                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容６ */
     ztyttdknaiyou7                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容７ */
     ztyttdknaiyou8                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容８ */
     ztyttdknaiyou9                                     VARCHAR     (60)                                                                ,  /* （中継用）手続内容９ */
     ztyttdknaiyou10                                    VARCHAR     (60)                                                                ,  /* （中継用）手続内容１０ */
     ztyttdknaiyouumukbn                                VARCHAR     (1)                                                                 ,  /* （中継用）手続内容有無区分 */
     ztykykniyuhnkkbn                                   VARCHAR     (1)                                                                 ,  /* （中継用）契約内容変更区分 */
     ztykykniyuhnkymd                                   VARCHAR     (11)                                                                ,  /* （中継用）契約内容変更日 */
     ztykykniyuhnkinfo                                  VARCHAR     (30)                                                                ,  /* （中継用）契約内容変更情報 */
     ztykykniyuhnkkngkhugou1                            VARCHAR     (1)                                                                 ,  /* （中継用）契約内容変更金額明細符号１ */
     ztykykniyuhnkkngk1                                 VARCHAR     (13)                                                                ,  /* （中継用）契約内容変更金額１ */
     ztykykniyuhnkkngktuksyu1                           VARCHAR     (3)                                                                 ,  /* （中継用）契約内容変更金額通貨種類１ */
     ztykykniyuhnkkngkhugou2                            VARCHAR     (1)                                                                 ,  /* （中継用）契約内容変更金額明細符号２ */
     ztykykniyuhnkkngk2                                 VARCHAR     (13)                                                                ,  /* （中継用）契約内容変更金額２ */
     ztykykniyuhnkkngktuksyu2                           VARCHAR     (3)                                                                 ,  /* （中継用）契約内容変更金額通貨種類２ */
     ztyyobiv102                                        VARCHAR     (102)                                                               ,  /* （中継用）予備項目Ｖ１０２ */
     ztysiharaibiwareki                                 VARCHAR     (11)                                                                ,  /* （中継用）支払日（和暦） */
     ztykaiyakuymdwa                                    VARCHAR     (11)                                                                ,  /* （中継用）解約日（和暦） */
     ztytekiyou1                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要１ */
     ztyshrkngkmeisaihugou1                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号１ */
     ztyshrgkmeisai1                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細１ */
     ztyshrgktuukasyu1                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類１ */
     ztybikou1                                          VARCHAR     (25)                                                                ,  /* （中継用）備考１ */
     ztytekiyou2                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要２ */
     ztyshrkngkmeisaihugou2                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号２ */
     ztyshrgkmeisai2                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細２ */
     ztyshrgktuukasyu2                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類２ */
     ztybikou2                                          VARCHAR     (25)                                                                ,  /* （中継用）備考２ */
     ztytekiyou3                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要３ */
     ztyshrkngkmeisaihugou3                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号３ */
     ztyshrgkmeisai3                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細３ */
     ztyshrgktuukasyu3                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類３ */
     ztybikou3                                          VARCHAR     (25)                                                                ,  /* （中継用）備考３ */
     ztytekiyou4                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要４ */
     ztyshrkngkmeisaihugou4                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号４ */
     ztyshrgkmeisai4                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細４ */
     ztyshrgktuukasyu4                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類４ */
     ztybikou4                                          VARCHAR     (25)                                                                ,  /* （中継用）備考４ */
     ztytekiyou5                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要５ */
     ztyshrkngkmeisaihugou5                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号５ */
     ztyshrgkmeisai5                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細５ */
     ztyshrgktuukasyu5                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類５ */
     ztybikou5                                          VARCHAR     (25)                                                                ,  /* （中継用）備考５ */
     ztytekiyou6                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要６ */
     ztyshrkngkmeisaihugou6                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号６ */
     ztyshrgkmeisai6                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細６ */
     ztyshrgktuukasyu6                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類６ */
     ztybikou6                                          VARCHAR     (25)                                                                ,  /* （中継用）備考６ */
     ztytekiyou7                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要７ */
     ztyshrkngkmeisaihugou7                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号７ */
     ztyshrgkmeisai7                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細７ */
     ztyshrgktuukasyu7                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類７ */
     ztybikou7                                          VARCHAR     (25)                                                                ,  /* （中継用）備考７ */
     ztytekiyou8                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要８ */
     ztyshrkngkmeisaihugou8                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号８ */
     ztyshrgkmeisai8                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細８ */
     ztyshrgktuukasyu8                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類８ */
     ztybikou8                                          VARCHAR     (25)                                                                ,  /* （中継用）備考８ */
     ztytekiyou9                                        VARCHAR     (12)                                                                ,  /* （中継用）摘要９ */
     ztyshrkngkmeisaihugou9                             VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号９ */
     ztyshrgkmeisai9                                    VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細９ */
     ztyshrgktuukasyu9                                  VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類９ */
     ztybikou9                                          VARCHAR     (25)                                                                ,  /* （中継用）備考９ */
     ztytekiyou10                                       VARCHAR     (12)                                                                ,  /* （中継用）摘要１０ */
     ztyshrkngkmeisaihugou10                            VARCHAR     (1)                                                                 ,  /* （中継用）支払金額明細符号１０ */
     ztyshrgkmeisai10                                   VARCHAR     (13)                                                                ,  /* （中継用）支払金額明細１０ */
     ztyshrgktuukasyu10                                 VARCHAR     (3)                                                                 ,  /* （中継用）支払金額通貨種類１０ */
     ztybikou10                                         VARCHAR     (25)                                                                ,  /* （中継用）備考１０ */
     ztyshrgkgoukei                                     VARCHAR     (13)                                                                ,  /* （中継用）支払額合計 */
     ztyshrtuukasyu                                     VARCHAR     (3)                                                                 ,  /* （中継用）支払通貨種類 */
     ztydseisanshrttdknm                                VARCHAR     (2)                                                                 ,  /* （中継用）Ｄ精算支払手続名 */
     ztyyobiv26x3                                       VARCHAR     (26)                                                                ,  /* （中継用）予備項目Ｖ２６＿３ */
     ztybanknmkj                                        VARCHAR     (20)                                                                ,  /* （中継用）銀行名（漢字） */
     ztysitennmkj                                       VARCHAR     (20)                                                                ,  /* （中継用）支店名（漢字） */
     ztyyokinkbn                                        VARCHAR     (1)                                                                 ,  /* （中継用）預金種目区分 */
     ztykouzano12keta                                   VARCHAR     (12)                                                                ,  /* （中継用）口座番号（１２桁） */
     ztykzmeiginmknhan                                  VARCHAR     (30)                                                                ,  /* （中継用）口座名義人氏名（カナ）（半角） */
     ztykouzasyuruikbn                                  VARCHAR     (1)                                                                 ,  /* （中継用）口座種類区分 */
     ztyyobiv26x2                                       VARCHAR     (26)                                                                ,  /* （中継用）予備項目Ｖ２６＿２ */
     ztysynykngk                                        VARCHAR     (10)                                                                ,  /* （中継用）収入金額 */
     ztysynykngktuukasyu                                VARCHAR     (3)                                                                 ,  /* （中継用）収入金額通貨種類 */
     ztyhtykeihi                                        VARCHAR     (10)                                                                ,  /* （中継用）必要経費 */
     ztyhtykeihituukasyu                                VARCHAR     (3)                                                                 ,  /* （中継用）必要経費通貨種類 */
     ztyshrkyksyahtykeihi                               VARCHAR     (10)                                                                ,  /* （中継用）お支払時の契約者の必要経費 */
     ztyshrkykhtykeihituukasyu                          VARCHAR     (3)                                                                 ,  /* （中継用）お支払時の契約者の必要経費通貨種類 */
     ztygsbnrkzthtykeihi                                VARCHAR     (10)                                                                ,  /* （中継用）源泉分離課税対象の必要経費 */
     ztygsbnrkzthtykeihituksyu                          VARCHAR     (3)                                                                 ,  /* （中継用）源泉分離課税対象の必要経費通貨種類 */
     ztygsbnrkztsaeki                                   VARCHAR     (10)                                                                ,  /* （中継用）源泉分離課税対象の差益 */
     ztygsbnrkztsaekituksyu                             VARCHAR     (3)                                                                 ,  /* （中継用）源泉分離課税対象の差益通貨種類 */
     ztyzeimunaiyouhensyuctrlkbn                        VARCHAR     (1)                                                                 ,  /* （中継用）税務内容編集制御区分 */
     ztyzeimumongonoutkbn                               VARCHAR     (1)                                                                 ,  /* （中継用）税務文言出力区分 */
     ztyzeimumongon1                                    VARCHAR     (30)                                                                ,  /* （中継用）税務文言１ */
     ztyzeimumongon2                                    VARCHAR     (30)                                                                ,  /* （中継用）税務文言２ */
     ztyzeimumongon3                                    VARCHAR     (30)                                                                ,  /* （中継用）税務文言３ */
     ztyzeimumongon4                                    VARCHAR     (30)                                                                ,  /* （中継用）税務文言４ */
     ztyzeimumongon5                                    VARCHAR     (30)                                                                ,  /* （中継用）税務文言５ */
     ztyyendthnkzeimuinfohskkbn                         VARCHAR     (1)                                                                 ,  /* （中継用）円建変更時税務情報補足区分 */
     ztyyobiv36                                         VARCHAR     (36)                                                                ,  /* （中継用）予備項目Ｖ３６ */
     ztyosirasehyoudai                                  VARCHAR     (17)                                                                ,  /* （中継用）お知らせ表題 */
     ztyosirasemongon1                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１ */
     ztyosirasemongon2                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２ */
     ztyosirasemongon3                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３ */
     ztyosirasemongon4                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４ */
     ztyosirasemongon5                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言５ */
     ztyosirasemongon6                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言６ */
     ztyosirasemongon7                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言７ */
     ztyosirasemongon8                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言８ */
     ztyosirasemongon9                                  VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言９ */
     ztyosirasemongon10                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１０ */
     ztyosirasemongon11                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１１ */
     ztyosirasemongon12                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１２ */
     ztyosirasemongon13                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１３ */
     ztyosirasemongon14                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１４ */
     ztyosirasemongon15                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１５ */
     ztyosirasemongon16                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１６ */
     ztyosirasemongon17                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１７ */
     ztyosirasemongon18                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１８ */
     ztyosirasemongon19                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言１９ */
     ztyosirasemongon20                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２０ */
     ztyosirasemongon21                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２１ */
     ztyosirasemongon22                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２２ */
     ztyosirasemongon23                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２３ */
     ztyosirasemongon24                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２４ */
     ztyosirasemongon25                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２５ */
     ztyosirasemongon26                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２６ */
     ztyosirasemongon27                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２７ */
     ztyosirasemongon28                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２８ */
     ztyosirasemongon29                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言２９ */
     ztyosirasemongon30                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３０ */
     ztyosirasemongon31                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３１ */
     ztyosirasemongon32                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３２ */
     ztyosirasemongon33                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３３ */
     ztyosirasemongon34                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３４ */
     ztyosirasemongon35                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３５ */
     ztyosirasemongon36                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３６ */
     ztyosirasemongon37                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３７ */
     ztyosirasemongon38                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３８ */
     ztyosirasemongon39                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言３９ */
     ztyosirasemongon40                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４０ */
     ztyosirasemongon41                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４１ */
     ztyosirasemongon42                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４２ */
     ztyosirasemongon43                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４３ */
     ztyosirasemongon44                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４４ */
     ztyosirasemongon45                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４５ */
     ztyosirasemongon46                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４６ */
     ztyosirasemongon47                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４７ */
     ztyosirasemongon48                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４８ */
     ztyosirasemongon49                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言４９ */
     ztyosirasemongon50                                 VARCHAR     (52)                                                                ,  /* （中継用）お知らせ文言５０ */
     ztyosiraseinjihuyouhyouji                          VARCHAR     (1)                                                                 ,  /* （中継用）お知らせ印字不要表示 */
     ztyyobiv254                                        VARCHAR     (254)                                                               ,  /* （中継用）予備項目Ｖ２５４ */
     ztyshrnaiyouhskmongon1                             VARCHAR     (50)                                                                ,  /* （中継用）支払内容補足文言１ */
     ztyshrnaiyouhskmongon2                             VARCHAR     (50)                                                                ,  /* （中継用）支払内容補足文言２ */
     ztydocumentid                                      VARCHAR     (24)                                                                ,  /* （中継用）ドキュメントＩＤ */
     ztysksmongonkbn1                                   VARCHAR     (3)                                                                 ,  /* （中継用）請求書文言区分１ */
     ztysksmongonkbn2                                   VARCHAR     (3)                                                                 ,  /* （中継用）請求書文言区分２ */
     ztytoritugisyasyozokunm                            VARCHAR     (15)                                                                ,  /* （中継用）取次者所属名 */
     ztytoritugisyakjncd                                VARCHAR     (8)                                                                 ,  /* （中継用）取次者個人コード */
     ztytoritugisyanm                                   VARCHAR     (15)                                                                ,  /* （中継用）取次者氏名 */
     ztyhozonkkny                                       VARCHAR     (2)                                                                 ,  /* （中継用）保存期間（年） */
     ztytsintelno                                       VARCHAR     (14)                                                                ,  /* （中継用）通信先電話番号 */
     version                                            BIGINT      NOT NULL  DEFAULT 0                                                 ,  /* バージョン */
     ztytrkkzkkbn1                                      VARCHAR     (1)                                                                 ,  /* （中継用）登録家族区分１ */
     ztytrkkzknmkj1                                     VARCHAR     (15)                                                                ,  /* （中継用）登録家族名（漢字）１ */
     ztytrkkzkseiymd1zenkaku                            VARCHAR     (11)                                                                ,  /* （中継用）登録家族１人目生年月日 */
     ztytrkkzkyno1                                      VARCHAR     (7)                                                                 ,  /* （中継用）登録家族郵便番号１ */
     ztytrkkzkadr1kj1                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所１（漢字）１　 */
     ztytrkkzkadr2kj1                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所２（漢字）１　 */
     ztytrkkzkadr3kj1                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所３（漢字）１　 */
     ztytrkkzktelno1                                    VARCHAR     (14)                                                                ,  /* （中継用）登録家族電話番号１ */
     ztytrkkzktelnomtrkhyouji1                          VARCHAR     (1)                                                                 ,  /* （中継用）登録家族電話番号未登録表示１ */
     ztytrkkzkkbn2                                      VARCHAR     (1)                                                                 ,  /* （中継用）登録家族区分２ */
     ztytrkkzknmkj2                                     VARCHAR     (15)                                                                ,  /* （中継用）登録家族名（漢字）２ */
     ztytrkkzkseiymd2zenkaku                            VARCHAR     (11)                                                                ,  /* （中継用）登録家族２人目生年月日 */
     ztytrkkzkyno2                                      VARCHAR     (7)                                                                 ,  /* （中継用）登録家族郵便番号２ */
     ztytrkkzkadr1kj2                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所１（漢字）２　 */
     ztytrkkzkadr2kj2                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所２（漢字）２　 */
     ztytrkkzkadr3kj2                                   VARCHAR     (30)                                                                ,  /* （中継用）登録家族住所３（漢字）２　 */
     ztytrkkzktelno2                                    VARCHAR     (14)                                                                ,  /* （中継用）登録家族電話番号２ */
     ztykykdairinmkj                                    VARCHAR     (15)                                                                ,  /* （中継用）契約者代理人名（漢字） */
     ztykykomttutkbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）契約者用表通知区分 */
     ztykzkomttutkbn1                                   VARCHAR     (2)                                                                 ,  /* （中継用）家族１用表通知区分 */
     ztykzkomttutkbn2                                   VARCHAR     (2)                                                                 ,  /* （中継用）家族２用表通知区分 */
     ztyhhkomttutkbn                                    VARCHAR     (2)                                                                 ,  /* （中継用）被保険者用表通知区分 */
     ztyhhkdromttutkbn                                  VARCHAR     (2)                                                                 ,  /* （中継用）被保険者代理人用表通知区分 */
     ztykykdairiomttutkbn                               VARCHAR     (2)                                                                 ,  /* （中継用）契約者代理人用表通知区分 */
     ztykykurtutkbn                                     VARCHAR     (2)                                                                 ,  /* （中継用）契約者用裏通知区分 */
     ztykzkurtutkbn1                                    VARCHAR     (2)                                                                 ,  /* （中継用）家族１用裏通知区分 */
     ztykzkurtutkbn2                                    VARCHAR     (2)                                                                 ,  /* （中継用）家族２用裏通知区分 */
     ztyhhkdrurtutkbn                                   VARCHAR     (2)                                                                 ,  /* （中継用）被保険者代理人用裏通知区分 */
     ztykykdairiurtutkbn                                VARCHAR     (2)                                                                 ,  /* （中継用）契約者代理人用裏通知区分 */
     ztykykaistmsgkbn                                   VARCHAR     (2)                                                                 ,  /* （中継用）契約者用挨拶ＭＳＧ区分 */
     ztykzkaistmsgkbn1                                  VARCHAR     (2)                                                                 ,  /* （中継用）家族１用挨拶ＭＳＧ区分 */
     ztykzkaistmsgkbn2                                  VARCHAR     (2)                                                                 ,  /* （中継用）家族２用挨拶ＭＳＧ区分 */
     ztyhhkaistmsgkbn                                   VARCHAR     (2)                                                                 ,  /* （中継用）被保険者用挨拶ＭＳＧ区分 */
     ztyhhkdraistmsgkbn                                 VARCHAR     (2)                                                                 ,  /* （中継用）被保険者代理人用挨拶ＭＳＧ区分 */
     ztykykdairiaistmsgkbn                              VARCHAR     (2)                                                                 ,  /* （中継用）契約者代理人用挨拶ＭＳＧ区分 */
     ztysakujyokzknmkj                                  VARCHAR     (15)                                                                ,  /* （中継用）削除家族名 */
     ztyttdknaiyoukbn                                   VARCHAR     (2)                                                                 ,  /* （中継用）手続内容区分 */
     ztykzktaisyoukykkbn                                VARCHAR     (1)                                                                 ,  /* （中継用）家族用対象契約区分 */
     ztyhhkdrtaisyoukykkbn                              VARCHAR     (1)                                                                 ,  /* （中継用）被保険者代理人用対象契約区分 */
     ztykykdairitaisyoukykkbn                           VARCHAR     (1)                                                                 ,  /* （中継用）契約者代理人用対象契約区分 */
     ztymoshnkniymsgkbn1                                VARCHAR     (2)                                                                 ,  /* （中継用）申込変更内容ＭＳＧ区分１ */
     ztykykmoshnkniymsg2                                VARCHAR     (2)                                                                 ,  /* （中継用）契約者用申込変更内容ＭＳＧ区分２ */
     ztykzkmoshnkniymsg21                               VARCHAR     (2)                                                                 ,  /* （中継用）家族１用申込変更内容ＭＳＧ区分２ */
     ztykzkmoshnkniymsg22                               VARCHAR     (2)                                                                 ,  /* （中継用）家族２用申込変更内容ＭＳＧ区分２ */
     ztyhhkdrmoshnkniymsg2                              VARCHAR     (2)                                                                 ,  /* （中継用）被保険者代理人用申込変更内容ＭＳＧ区分２ */
     ztykykdairimoshnkniymsg2                           VARCHAR     (2)                                                                 ,  /* （中継用）契約者代理人用申込変更内容ＭＳＧ区分２ */
     ztykykdrmsgkbn                                     VARCHAR     (2)                                                                 ,  /* （中継用）契約者代理ＭＳＧ区分 */
     ztykykhhkdrmsg                                     VARCHAR     (2)                                                                 ,  /* （中継用）契約者用被保険者代理ＭＳＧ区分 */
     ztykzkhhkdrmsg1                                    VARCHAR     (2)                                                                 ,  /* （中継用）家族１用被保険者代理ＭＳＧ区分 */
     ztykzkhhkdrmsg2                                    VARCHAR     (2)                                                                 ,  /* （中継用）家族２用被保険者代理ＭＳＧ区分 */
     ztyhhkdrnmkj                                       VARCHAR     (15)                                                                ,  /* （中継用）被保険者代理人名（漢字） */
     ztyduhubutumsg1                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分１ */
     ztyduhubutumsg2                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分２ */
     ztyduhubutumsg3                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分３ */
     ztyduhubutumsg4                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分４ */
     ztyduhubutumsg5                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分５ */
     ztyduhubutumsg6                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分６ */
     ztyduhubutumsg7                                    VARCHAR     (2)                                                                 ,  /* （中継用）同封物ＭＳＧ区分７ */
     ztykykigaidhbtmsg1                                 VARCHAR     (2)                                                                 ,  /* （中継用）契約者以外用同封物ＭＳＧ区分１ */
     ztykykigaidhbtmsg2                                 VARCHAR     (2)                                                                 ,  /* （中継用）契約者以外用同封物ＭＳＧ区分２ */
     ztykykigaidhbtmsg3                                 VARCHAR     (2)                                                                 ,  /* （中継用）契約者以外用同封物ＭＳＧ区分３ */
     ztykykigaidhbtmsg4                                 VARCHAR     (2)                                                                 ,  /* （中継用）契約者以外用同封物ＭＳＧ区分４ */
     ztyyakkankiyakuhunyuuhyouji                        VARCHAR     (1)                                                                 ,  /* （中継用）約款規約封入表示 */
     ztykyktrktrshuunyuuhyouji                          VARCHAR     (1)                                                                 ,  /* （中継用）登録チラシ封入表示（契） */
     ztykzktrktrshuunyuuhyouji1                         VARCHAR     (1)                                                                 ,  /* （中継用）登録チラシ封入表示（家族１） */
     ztykzktrktrshuunyuuhyouji2                         VARCHAR     (1)                                                                 ,  /* （中継用）登録チラシ封入表示（家族２） */
     ztykykdrhuunyuuhyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）契約者代理封入表示 */
     ztyhhkdrhuunyuuhyouji                              VARCHAR     (1)                                                                 ,  /* （中継用）被保険者代理封入表示 */
     ztykykdairinmkj2                                   VARCHAR     (15)                                                                ,  /* （中継用）契約者代理人名（漢字）２ */
     ztykykdrseiymd                                     VARCHAR     (11)                                                                ,  /* （中継用）契約者代理人生年月日 */
     ztykykdryno                                        VARCHAR     (7)                                                                 ,  /* （中継用）契約者代理人郵便番号 */
     ztykykdradr1kj                                     VARCHAR     (30)                                                                ,  /* （中継用）契約者代理人住所１（漢字） */
     ztykykdradr2kj                                     VARCHAR     (30)                                                                ,  /* （中継用）契約者代理人住所２（漢字） */
     ztykykdradr3kj                                     VARCHAR     (30)                                                                ,  /* （中継用）契約者代理人住所３（漢字） */
     ztykykdrtelno                                      VARCHAR     (14)                                                                ,  /* （中継用）契約者代理人電話番号 */
     ztyhhkdrnmkj2                                      VARCHAR     (15)                                                                ,  /* （中継用）被保険者代理人名（漢字）２ */
     ztyhhkdrseiymd                                     VARCHAR     (11)                                                                ,  /* （中継用）被保険者代理人生年月日 */
     ztyhhkdryno                                        VARCHAR     (7)                                                                 ,  /* （中継用）被保険者代理人郵便番号 */
     ztyhhkdradr1kj                                     VARCHAR     (30)                                                                ,  /* （中継用）被保険者代理人住所１（漢字） */
     ztyhhkdradr2kj                                     VARCHAR     (30)                                                                ,  /* （中継用）被保険者代理人住所２（漢字） */
     ztyhhkdradr3kj                                     VARCHAR     (30)                                                                ,  /* （中継用）被保険者代理人住所３（漢字） */
     ztyhhkdrtelno                                      VARCHAR     (14)                                                                ,  /* （中継用）被保険者代理人電話番号 */
     ztyhhkdrtelnomtrkhyouji                            VARCHAR     (1)                                                                 ,  /* （中継用）被保険者代理人電話番号未登録表示 */
     ztykhsyono2                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号２ */
     ztykhsyono3                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号３ */
     ztykhsyono4                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号４ */
     ztykhsyono5                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号５ */
     ztykhsyono6                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号６ */
     ztykhsyono7                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号７ */
     ztykhsyono8                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号８ */
     ztykhsyono9                                        VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号９ */
     ztykhsyono10                                       VARCHAR     (11)                                                                ,  /* （中継用）（契約保全）証券番号１０ */
     ztykhmosno1                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号１ */
     ztykhmosno2                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号２ */
     ztykhmosno3                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号３ */
     ztykhmosno4                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号４ */
     ztykhmosno5                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号５ */
     ztykhmosno6                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号６ */
     ztykhmosno7                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号７ */
     ztykhmosno8                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号８ */
     ztykhmosno9                                        VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号９ */
     ztykhmosno10                                       VARCHAR     (9)                                                                 ,  /* （中継用）（契約保全）申込番号１０ */
     ztyhnsnhutouhuunyuuhyouji                          VARCHAR     (1)                                                                 ,  /* （中継用）返信用封筒封入表示 */
     ztyyobiv204                                        VARCHAR     (204)                                                               ,  /* （中継用）予備項目Ｖ２０４ */
     ztyyobiv255x2                                      VARCHAR     (255)                                                               ,  /* （中継用）予備項目Ｖ２５５＿２ */
     ztyyobiv255x3                                      VARCHAR     (255)                                                               ,  /* （中継用）予備項目Ｖ２５５＿３ */
     ztyyobiv255x4                                      VARCHAR     (255)                                                               ,  /* （中継用）予備項目Ｖ２５５＿４ */
     ztyyobiv141                                        VARCHAR     (141)                                                               ,  /* （中継用）予備項目Ｖ１４１ */
     kousinsyaId                                        VARCHAR     (30)                                                                ,  /* 更新者ＩＤ */
     kousinTime                                         VARCHAR     (17)                                                                ,  /* 更新時間 */
     kousinKinou                                        VARCHAR     (50)                                                                   /* 更新機能 */
)
;

ALTER TABLE ZT_TtdkKanTy ADD CONSTRAINT PK_TtdkKanTy PRIMARY KEY (
     ztytyouhyouymd                                           , /* （中継用）帳票作成日 */
     ztysyono                                                 , /* （中継用）証券番号 */
     ztysikibetuno                                              /* （中継用）識別番号 */
) ;
