CREATE VIEW BV_HJYBRUIKEIGAKUDATA AS SELECT
 RUIKEIGAKUTEISEILIST.HJYBTANTOSITUCD,
 RUIKEIGAKUTEISEILIST.KANJYOUKMKCD,
 RUIKEIGAKUTEISEILIST.DENYM,
 RUIKEIGAKUTEISEILIST.KARIKATARUIGK,
 RUIKEIGAKUTEISEILIST.KARIKATARUIGK$,
 RUIKEIGAKUTEISEILIST.KASIKATARUIGK,
 RUIKEIGAKUTEISEILIST.KASIKATARUIGK$,
 RUIKEIGAKUTEISEILIST.KASIKATATEISEIGK,
 RUIKEIGAKUTEISEILIST.KASIKATATEISEIGK$,
 RUIKEIGAKUTEISEILIST.KARIKATATEISEIGK,
 RUIKEIGAKUTEISEILIST.KARIKATATEISEIGK$,
 KAMOKU.HJYBRUIGKTEISEIUMUKBN,
 '' AS KOUSINSYAID,
 '' AS KOUSINTIME,
 '' AS KOUSINKINOU,
 0 AS VERSION
FROM (
 SELECT
  RUIKEIGAKU1.HJYBTANTOSITUCD,
  RUIKEIGAKU1.KANJYOUKMKCD,
  RUIKEIGAKU1.DENYM,
  RUIKEIGAKU1.KARIKATARUIGK,
  RUIKEIGAKU1.KARIKATARUIGK$,
  RUIKEIGAKU1.KASIKATARUIGK,
  RUIKEIGAKU1.KASIKATARUIGK$,
  TEISEI1.KASIKATATEISEIGK,
  TEISEI1.KASIKATATEISEIGK$,
  TEISEI1.KARIKATATEISEIGK,
  TEISEI1.KARIKATATEISEIGK$
 FROM (
  SELECT
   HJYBTANTOSITUCD,
   KANJYOUKMKCD,
   DENYM,
   KARIKATARUIGK,
   KARIKATARUIGK$,
   KASIKATARUIGK,
   KASIKATARUIGK$
  FROM
   BT_HJYBRUIKEIGAKU_Z AS T1
  WHERE T1.DENYM = (
   SELECT MAX(DENYM) FROM BT_HJYBRUIKEIGAKU_Z AS T2
   WHERE T1.HJYBTANTOSITUCD = T2.HJYBTANTOSITUCD
   AND   T1.KANJYOUKMKCD = T2.KANJYOUKMKCD
   GROUP BY HJYBTANTOSITUCD, KANJYOUKMKCD)
 ) AS RUIKEIGAKU1
 LEFT JOIN BT_HJYBRUIKEIGAKUTEISEI_Z AS TEISEI1
  ON  RUIKEIGAKU1.HJYBTANTOSITUCD = TEISEI1.HJYBRUIGKTEISEITANTOSITUCD
  AND RUIKEIGAKU1.KANJYOUKMKCD = TEISEI1.KANJYOUKMKCD

 UNION

 SELECT
  TEISEI2.HJYBRUIGKTEISEITANTOSITUCD AS HJYBTANTOSITUCD,
  TEISEI2.KANJYOUKMKCD,
  RUIKEIGAKU2.DENYM,
  RUIKEIGAKU2.KARIKATARUIGK,
  RUIKEIGAKU2.KARIKATARUIGK$,
  RUIKEIGAKU2.KASIKATARUIGK,
  RUIKEIGAKU2.KASIKATARUIGK$,
  TEISEI2.KASIKATATEISEIGK,
  TEISEI2.KASIKATATEISEIGK$,
  TEISEI2.KARIKATATEISEIGK,
  TEISEI2.KARIKATATEISEIGK$
 FROM
  BT_HJYBRUIKEIGAKUTEISEI_Z AS TEISEI2
 LEFT JOIN (
  SELECT
   HJYBTANTOSITUCD,
   KANJYOUKMKCD,
   DENYM,
   KARIKATARUIGK,
   KARIKATARUIGK$,
   KASIKATARUIGK,
   KASIKATARUIGK$
  FROM
   BT_HJYBRUIKEIGAKU_Z AS T3
  WHERE T3.DENYM = (
   SELECT MAX(DENYM) FROM BT_HJYBRUIKEIGAKU_Z AS T4
   WHERE T3.HJYBTANTOSITUCD = T4.HJYBTANTOSITUCD
   AND   T3.KANJYOUKMKCD = T4.KANJYOUKMKCD
   GROUP BY HJYBTANTOSITUCD, KANJYOUKMKCD)
 ) AS RUIKEIGAKU2
  ON  RUIKEIGAKU2.HJYBTANTOSITUCD = TEISEI2.HJYBRUIGKTEISEITANTOSITUCD
  AND RUIKEIGAKU2.KANJYOUKMKCD = TEISEI2.KANJYOUKMKCD
) AS RUIKEIGAKUTEISEILIST
LEFT JOIN BM_KANJYOUKAMOKU_Z AS KAMOKU
 ON RUIKEIGAKUTEISEILIST.KANJYOUKMKCD = KAMOKU.KANJYOUKMKCD
;